### ISSUE TITLE
Hide Dart VM flags for flutter web

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1007]
<img width="955" alt="Screen Shot 2019-09-06 at 9 08 32 AM" src="https://user-images.githubusercontent.com/43759233/64443122-1ea78180-d086-11e9-8d08-4a866207b7e3.png">

We should either disable this for flutter web, or implement the method @jakemac53 @grouma

**Comment by grouma** [comment]
What would the value be here? I assume empty because technically DDC doesn't respond to VM flags? If so it would be trivial to implement.

**Comment by kenzieschmoll** [comment]
Are Dart VM flags irrelevant for flutter web users?

**Comment by grouma** [comment]
I think so. @jonahwilliams can you confirm?

**Comment by jonahwilliams** [comment]
I can't think of anything that would be of value here. Returning an empty list seems reasonable

**Comment by kenzieschmoll** [comment]
Okay, then we should hide the dart vm flag UI for flutter web users. We'll let this issue track that.
