### ISSUE TITLE
Thoughts on Memory View

### ISSUE THREAD

**Issue by escamoteur** [flutter/devtools#1031]
Hi,
I really like this view! I would like to share some thoughts:

- I think it would be awesome if we could make more than one snapshot and compare them
- It would be helpfull if we could send a signal or even trigger a snapshot from inside the tested app to know exactly where it happened
- Currently the single instance view doesn't show anything. I guess there is something in the pipeline for it :-) I don't know if this is possible but could you add the source position where a instance was created?

Thanks
Thomas

**Comment by jacob314** [comment]
Fyi @terrylucas

**Comment by jacob314** [comment]
We use a kernel transformer to track source positions where Widgets were created. We could provide an option to extend it to work for more classes but there would be performance and risks so we wouldn't likely want to turn it on for all instances unless users opted in to re-run their app in a memory usage profiling debug mode. If there are a few more flutter specific classes that it would be useful for it could be practical to add them to the list.

**Comment by escamoteur** [comment]
IMHO  performance should not be a problem while profiling memory usage. It could be enable as an option when building a profile build. Am 11.09.2019 01:22 schrieb Jacob Richman <notifications@github.com>:We use a kernel transformer to track source positions where Widgets were created. We could provide an option to extend it to work for more classes but there would be performance and risks so we wouldn't likely want to turn it on for all instances unless users opted in to re-run their app in a memory usage profiling debug mode. If there are a few more flutter specific classes that it would be useful for it could be practical to add them to the list.
