### ISSUE TITLE
Improve error messaging when CPU profiles are unavailable.

### ISSUE THREAD

**Issue by escamoteur** [flutter/devtools#1032]
Hi,

I'm testing the latest version 

```
Flutter:
1.10.1-pre.41 • channel master • https://github.com/flutter/flutter
Framework:
revision 5a3a46ada2 • 2019-09-07 18:37:41 -0400
Engine:
revision c9ea4dba8d
Dart SDK:
2.5.0-dev.4.0.flutter-ec7ec4ecf7
DevTools:
0.1.7
```

And my CPU profile doesn't show anything for any frame see:

![image](https://user-images.githubusercontent.com/16635729/64608863-dc56ab00-d3cb-11e9-8c57-c9c1b1a2cb9f.png)

I run a profile build:

![image](https://user-images.githubusercontent.com/16635729/64608927-0740ff00-d3cc-11e9-853f-88b16884bb38.png)

Do I something wrong?
Cheers
Thomas

**Comment by kenzieschmoll** [comment]
Unfortunately this is behaving as expected. I see you are using "profile granularity: high". When you selected that, a warning should have popped up with a link to this [documentation](https://flutter.dev/docs/development/tools/devtools/performance#profile-granularity) that explains the tradeoffs for profile granularity.  

The Dart VM has a buffer that holds CPU samples. Once that buffer is full, the oldest samples will be dropped to make room for new ones. The more you sample ("profile granularity: high" being the most often), the quicker this buffer fills up. The frame you selected appears to be farther back in the frame timeline, so the CPU sample data for this frame was dropped from the buffer to make room for newer CPU samples.

**Comment by escamoteur** [comment]
![image](https://user-images.githubusercontent.com/16635729/64629877-4edb8100-d3f4-11e9-947b-4a8689d7ca66.png)

It doesn't work on **medium** either even on the first samples.
Only on **low**  I manage to see CPU profiles

The warning only comes when you select high. 
I think it would be good to place also more information in the bottom. This is already at the third sample so it would be good to tell people why they don't see anything and that they should do a new recording the moment for that when they want to see data.

![image](https://user-images.githubusercontent.com/16635729/64630331-299b4280-d3f5-11e9-8682-8204caab516e.png)

**Comment by escamoteur** [comment]
Just double checked, I only get CPU samples for the first 4 Samples on the left. If I select any sample to the far right I get no samples at all.

**Comment by kenzieschmoll** [comment]
Can you reproduce this and click the Export button? Then attach it here. Thanks.

**Comment by escamoteur** [comment]
Will do tomorrow Am 10.09.2019 18:42 schrieb Kenzie Schmoll <notifications@github.com>:Can you reproduce this and click the Export button? Then attach it here. Thanks.

**Comment by escamoteur** [comment]
I tried it again. When I click the one at the far right that isn't completely there I get CPU samples but not for any others on the right side. On the left I get 4 samples again.

![image](https://user-images.githubusercontent.com/16635729/64679883-ea183900-d47c-11e9-9988-494b4f178f3f.png)
 

[timeline_2019_9_11-1568189493070000.zip](https://github.com/flutter/devtools/files/3599686/timeline_2019_9_11-1568189493070000.zip)
