### ISSUE TITLE
Please add a search function to the Performance View

### ISSUE THREAD

**Issue by escamoteur** [flutter/devtools#1034]
Hi,

it would be awesome if you could add a search function to locate a specific function on the charts of the different performance views.

Cheers
Thomas

**Comment by kenzieschmoll** [comment]
Thanks for the feature request! Tracking issue for search/filtering tables here: https://github.com/flutter/devtools/issues/785. We'll keep this issue open as well since searching tables won't apply to the CPU flame chart.

**Comment by kenzieschmoll** [comment]
The flame chart supports search. Supporting search in the tree tables (call tree and bottom up) is tracked here: https://github.com/flutter/devtools/issues/2524
