### ISSUE TITLE
Set up a way to run devtools_server with debug/DDC version of devtools for local development

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#1036]
Currently we'll only connect to the server for release builds where we know the server is serving:

https://github.com/flutter/devtools/pull/987#pullrequestreview-286518143

**Comment by kenzieschmoll** [comment]
Polishing / normalizing this workflow would be a velocity improvement.

**Comment by kenzieschmoll** [comment]
closing as a duplicate of https://github.com/flutter/devtools/issues/6486
