### ISSUE TITLE
Vision: Zoom in on errors with DevTools

### ISSUE THREAD

**Issue by csells** [flutter/devtools#1044]
Right now, even folks that know about DevTools don't tend to use it very much. In the case where it's most useful, i.e. an exception happens in your app and shows up in red in your debug output, starting DevTools at that point is too late -- it won't have the data to debug the problem since it will only get new messages.

However, if we were able to cache logging messages for DevTools and do a better job highlighting errors when we found them, we could enable the following:

- developer starts their app as normal

- oh oh -- red text in my debug output? what's wrong? ok... that's a lot of text... am I supposed to map all of that manually to my code? there has to be a better way! oh wait... it says here to start up Dart DevTools to see this exception in context. And there's a link!

- developer starts DevTools and sees that it has loaded the logs already generated by the app

- further, DevTools has a couple of places where it has shown the latest exception in context, e.g. the Logging tab and the Inspector tab. How does the developer know this? Because both of them have red error icons on them.

- Clicking on those tabs brings the developer immediate to the exception in context, where the appropriate elements are also lit up in red with all of the same info as the Exception, but now shown in context.

- Developer sees what the problem is using the full power of Dart DevTools and tells two friends. Then they tell two friends. And so on and so.

- ...

- Profit!

**Comment by csells** [comment]
One set of comment problems to debug in DevTools would be layout issues. To do that requires seeing and understanding the size and constraints properties of any RenderObject associated with a Widget. This is represented as two separate trees in the IntelliJ/Android Studio plugin and collapsed into a renderObject property for widgets in the Inspector that have associated RenderObjects. UX studies show that ROs are scary to people.

If we were to promote just the constraints and size properties from the renderObject to the parent widget, marking them in some way to represent them as different (perhaps calculated?) e.g. [constraints] and [size], they become more accessible and easier to access w/o explicitly digging into a scary RenderObject (which isn't expanded by default because -- you guessed it -- it's scary!). 

Further, if there were problems with the constraints or size values traveling up and down the RO tree, then those properties could be marked in red as appropriate based on data from an exception as described above.

**Comment by jacob314** [comment]
> @csells This would be extremely helpful. Especially to see if the size of a widget is constrained by its parent or child or itself.
> 
> Just as a side Thought on the Inspector:
> 
> * It's absolute unclear what Widgets are displayed in the left tree and why you see others only in  the right one
The widgets in the left tree are the ones you created directly in your package. The right one includes all widgets.
Do you have examples where the left tree displays an unintuitive set of widgets? Is your project split up into a number of packages? In that case, the left tree may be unintuitive as you could expect to see widgets from all your packages not just your main package.
