### ISSUE TITLE
use grind to perform extra checks before committing changes to package:devtools

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#1046]
`https://github.com/flutter/devtools/blob/master/packages/devtools/tool/version_check.dart`
is an existing check that could be converted over.
We could also use additional checks to prevent direct imports of `dart:html` and potentially in the future direct imports of `package:flutter` as part of the migration to flutter.

**Comment by parlough** [comment]
There's now a standardized `devtools_tool` CI tool for contributing to this repo in the [`/tool` directory](https://github.com/flutter/devtools/tree/master/tool). Check out [Set up your DevTools environment](https://github.com/flutter/devtools/blob/master/CONTRIBUTING.md#set-up-your-devtools-environment) for details on setting up and using the tool :D
