### ISSUE TITLE
Should package:devtools_server depend on package:devtools?

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#1065]
For `package:devtools_server` to properly work properly it assumes a `package:devtools` dependency:
https://github.com/flutter/devtools/blob/acf26c7dc231fdc35c24eff8ef33b44a7054755d/packages/devtools_server/lib/src/handlers.dart#L18

Should we make this dependency explicit to prevent unexpected errors?

**Comment by devoncarew** [comment]
That might be challenging - `package:devtools` itself has a dep. on `package:devtools_server`.

**Comment by grouma** [comment]
That shouldn't be an issue. You are allowed cyclic dependencies.

**Comment by devoncarew** [comment]
I tend to think of them (cycles) as a code smell - that we should prefer a layered approach, where lower layers don't know about higher level ones.

**Comment by grouma** [comment]
I agree. The issue here is that we want to be able to run `devtools` by global activating that package instead of `devtools_server`. Nonetheless, the dependency is still required, so we might as well make it explicit.
