### ISSUE TITLE
Add support for CSS prefers-color-scheme in Debugger html page

### ISSUE THREAD

**Issue by natebosch** [flutter/devtools#1073]
It looks like things work if I move all of `styles_dark.css` and `styles_light.css` into `styles.css` and wrap each with the appropriate`@media` query and empty both original files.

```css
@media (prefers-color-scheme: dark) {
  /* all of styles_dart.css */
}

@media (prefers-color-scheme: light) {
  /* all of styles_light.css */
}
```

I didn't do extensive testing though...

**Comment by natebosch** [comment]
https://caniuse.com/#search=prefers-color-scheme

**Comment by natebosch** [comment]
After the migration to flutter this is handled in https://github.com/flutter/devtools/issues/1363 since it will be automatically based on the media query. Closing since it's not worth doing in the html app before the migration to flutter.

**Comment by DaveShuckerow** [comment]
I'd like to still track this since we do have the debugger page written in web still.

**Comment by kenzieschmoll** [comment]
html app is now deleted
