### ISSUE TITLE
Memory legend renames.

### ISSUE THREAD

**Issue by terrylucas** [flutter/devtools#1081]
1) explain more in the doc? Need to review I think it is explained.  I think a possible solution was for get info circle with ? near the legends that tells what it is.

2) Capacity = Allocated
3) Used = Dart/Flutter
4) External = Flutter engine/rendering

**Comment by cobblest** [comment]
It will also be great if we could show the complete legend list when user open the Memory page. Right now they need to scroll down to see the whole list and all the legend options.

**Comment by cobblest** [comment]
@terrylucas could we update these, especially the Used - Dart renaming?
