### ISSUE TITLE
Legends not fully visible.

### ISSUE THREAD

**Issue by terrylucas** [flutter/devtools#1082]
Legend is not fully visible until another UX widget is in the view (e.g., snapshot) then a resize will display the entire legend.

**Comment by raison00** [comment]
![dart-android-memory-profiler](https://user-images.githubusercontent.com/8105802/81734456-628a2c00-9448-11ea-83fd-d9bdf45be2f1.png)

I've created a mock to show how the legend can be implemented on a split Dart / Android Profile.

**Comment by kenzieschmoll** [comment]
obsolete
