### ISSUE TITLE
Make it easier to reconnect to a new VM

### ISSUE THREAD

**Issue by natebosch** [flutter/devtools#1092]
If  I repeatedly need to run a new VM to see my code changes the workflow is a little annoying today. What I was doing to connect to a new VM is:

- Click into the URL bar.
- Highlight the chunk of the URL after the port
- Hit delete
- Hit enter
- Paste the observatory URL into the text box

Can we shorten this? It could be as simple as making a click on header take us back to the "home" page with the text box instead of requiring a manual URL edit. Or maybe we could add a small icon somewhere to reconnect to a different VM.

**Comment by devoncarew** [comment]
We have an issue similar to this here: https://github.com/flutter/devtools/issues/433.

**Comment by kenzieschmoll** [comment]
Also related, initial work for that here: https://github.com/flutter/devtools/pull/987
