### ISSUE TITLE
Analytics on first screen load in DevTools is empty string

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1098]
Setting up bazel analytics, I'm noticing that the first call to ga.screen() when loading DevTools from IntelliJ (with the inspector page as the landing screen) is coming up as "" instead of "inspector".

**Comment by devoncarew** [comment]
@grouma - I think you've done work in analytics for DevTools; did you remember if the work you did addressed this issue?

**Comment by kenzieschmoll** [comment]
Do we rely on the url for analytics? When the inspector loads as the default page, `#inspector` is not appended to the url, whereas if it is navigated to via the nav bar, `#inspector` is present.

**Comment by grouma** [comment]
I addressed it with this PR: https://github.com/flutter/devtools/pull/1488
