### ISSUE TITLE
Pull in the DevTools icons to Hummingbird

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1113]
The icons assets for tabs, etc, should all be reused.

**Comment by jacob314** [comment]
We should create a flutter_icon_renderer equivalent to html_icon_renderer that generates widgets rendering the icons. That is key to make all the icons work well in the port of the inspector with minimal extra work.
https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/ui/html_icon_renderer.dart

**Comment by DaveShuckerow** [comment]
We discussed this offline: I believe we'll be able to use AssetImage for everything floating around under widgets.json.

For the Octicons icons, we may need to load the icon font into Flutter.
