### ISSUE TITLE
Development mode on the DevTools server

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1141]
To make file editting easier, we could add an option to the file handler that sets the files it returns to expire immediately so that we don't have to worry about the cache.

**Comment by DaveShuckerow** [comment]
@terrylucas Feel free to share any pain points you run into.

**Comment by DaveShuckerow** [comment]
@jacob314 

We discussed this one today.  I think you suggested a proxy server that the devtools server can forward file requests to.

**Comment by kenzieschmoll** [comment]
Polishing / normalizing this workflow would be a velocity improvement.
