### ISSUE TITLE
Integration tests running on the flutter tool may not get killed properly on Windows

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1145]
Previously, integration tests would run the devtools app via `dart pub.snapshot run` instead of starting pub directly.  This prevented Windows-based dart test runs getting killed, leaving the pub process behind.

Something similar might be needed when using flutter to run these tests.

Flutter's documentation talks about using snapshots to run the tools here: https://github.com/flutter/flutter/wiki/The-flutter-tool#debugging-the-flutter-command-line-tool

**Comment by kenzieschmoll** [comment]
closing as obsolete
