### ISSUE TITLE
Dependencies of devtools end up with illegal ".packages" files

### ISSUE THREAD

**Issue by iskakaushik** [flutter/devtools#1148]
That package doesn't have a lib directory and seems to delegate heavily to devtools_server.

This is interesting in conjunction with https://github.com/dart-archive/dart_enhancement_proposals/blob/master/Accepted/0005%20-%20Package%20Specification/DEP-pkgspec.md, when you have a project that depends on devtools, it would result in an invalid .packages file. Specifically an entry for devtools that points to an invalid lib dir reference.

I discovered this issue downstream in Fuchsia where we try to take actions based on the presence of the value associated with a given pub package.

cc: @rmacnak-google , @jason-simmons 

Previous issue: https://github.com/dart-lang/webdev/issues/720

**Comment by devoncarew** [comment]
Is it that you just need a `lib/` dir to exist? You could create a small .md file in `//packages/devtools/lib/` if that's the case.

**Comment by devoncarew** [comment]
Like this guy: https://github.com/flutter/cupertino_icons/tree/master/lib

**Comment by iskakaushik** [comment]
Done.
