### ISSUE TITLE
Investigate why --delete-conflicting-output is required in the test script

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#1157]
Integration tests appear to sometimes timeout without adding `--delete-conflicting-output`.
Theories are that this is either due to build_runner rebuilding when it shouldn't due to us triggering the file watcher (which cannot be disabled) or due to just running build_runner multiple times ones for the integration tests and once for the server tests.

**Comment by kenzieschmoll** [comment]
This is for legacy integration tests we no longer run. Closing.
