### ISSUE TITLE
package:charts_flutter for current usages of plotly.js

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1175]
https://pub.dev/packages/charts_flutter should provide the charting capabilities we need for DevTools.

https://google.github.io/charts/flutter/gallery.html

**Comment by kenzieschmoll** [comment]
I'll investigate more once I start porting the Timeline, but from an initial look through the linked gallery, I have some skepticism as to whether any of these will support what we will need for the flame chart (at least none of the examples look like they will). We may have to create a custom flame charting lib - TBD.

**Comment by DaveShuckerow** [comment]
From what I can see, the uses for charts versus flame charts are big.

I'm going to create a separate issue for flame charts from the other charts we show.

**Comment by DaveShuckerow** [comment]
We switched from using charts_flutter to another package, package:mp_chart.

This is fixed.
