### ISSUE TITLE
Flame charting in flutter web

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1178]
Creating this issue to collect requirements on the problem:

* [ ] 2-dimensional scrolling
* [ ] Zoom
* [ ] Click for details on a specific widget

![image](https://user-images.githubusercontent.com/14947366/66781516-56c19180-ee88-11e9-898d-f96911015fc6.png)

**Comment by DaveShuckerow** [comment]
@kenzieschmoll

**Comment by DaveShuckerow** [comment]
For the two-dimensional lazy-list scrolling, we can do a pattern like the following:

```
LinkedScrollController horizontalController;
...
// Build the top level of the list
ListView.custom(
  axis: Axis.vertical,
  builder: (context, index) {
    // Build each row of the list lazily
    SizedBox(
      width: flameChartWidthFor(zoom),
      height: flameChartHeightFor(zoom),
      child: ListView.custom(
        axis: Axis.horizontal,
        controller: LinkedController(parent: horizontalController)
        builder: (context, index) {
          // Build the widgets for the row based on the two indices above.
        }
      ),
    );
  }),
```

The idea is that we want to lazily build both horizontally and vertically, so we want a lazy builder for both situations.

We also want to link the scroll of each row, so that we scroll the entire table instead of one row in isolation.

**Comment by filiph** [comment]
FWIW, the current vertical scrolling in DevTools Timeline is probably the number 1 reason why I sometimes get frustrated using DevTools.

2D scrolling and zooming around the timeline is something I do a lot (I often have no idea where I should be looking first, so I have to zoom around the timeline). For this reason, I learned to appreciate the way Observatory Timeline does it. They have WSAD for in/out/left/right, and scroll wheel for up/down. A high learning curve to be sure, but rewarded by fast operation once learned.

This is just to say: 

* This might be a good UI improvement to prioritize, imho, if you're looking for more early adopters on board.
* It doesn't need to be perfect. The `about:tracing` UI is far from perfect, but people are well incentivized to learn it.

**Comment by jacob314** [comment]
This has been implemented.
