### ISSUE TITLE
Google analytics plugin support

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1184]
We need to wire the existing DevTools google analytics into the Devtools app.

On web, I suspect this will work already because the ga.js file is already loaded by index.html, and the Dart2JS compiled code can include the existing ga interop code exactly the same as the dart:html app.

On Desktop, we may need to switch to Flutter's plugin model to be able to talk to analytics properly.

Another option:
If we can teach the DevTools server about how to send data to Google Analytics, then we can pull the GA code to the server, and the client just tells the server what events to send to GA, regardless of environment.

**Comment by devoncarew** [comment]
`package:usage` supports sending analytics via both `dart:html` and `dart:io` - it should be usable from a Flutter desktop app.
