### ISSUE TITLE
[P2] SSE on Flutter

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1185]
Currently, package:sse isn't usable from Flutter on Desktop, only in the web.

This is a blocker for the desktop client, but not for running on the web.

**Comment by jacob314** [comment]
SSE will work on Flutter web just not desktop. This is not a launch blocker as currently Desktop is just a debugging environment for us.

**Comment by devoncarew** [comment]
Moving out of the hummingbird dashboard.
