### ISSUE TITLE
Flaky test: info controller flags test

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#1193]
```
00:50 +14 -1: /Users/travis/build/flutter/devtools/packages/devtools_app/test/info_controller_test.dart: info controller entering [E]                                                                  
  Expected: <0>
    Actual: <2>
  Value of expectedFlags is [[Flag name: causal_async_stacks, comment: Improved async stacks, modified: true], [Flag name: async_debugger, comment: Debugger support async functions., modified: false]]
  
  package:test_api                                         expect
  package:devtools_testing/info_controller_test.dart 80:7  runInfoControllerTests.<fn>.<fn>
```

Looking at the code, I think this would happen only if the returned flags list is empty (if there were any mismatched flags, I think `expect(flags[i].toString(), flagList.flags[i].toString());` would fail).

**Comment by albertusangga** [comment]
@jacob314 the info controller flags test is still flaky especially on macOS machines, should we disable it for now?

**Comment by kenzieschmoll** [comment]
This issue is still happening. Test is skipped for now, but we should get to the bottom of the flake and fix it.

**Comment by kenzieschmoll** [comment]
this test was turned back on has not produced any flakes. We can re-open if it happens again.
