### ISSUE TITLE
Ctrl-F support for ListView.builder

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1194]
The info page uses ListView.builder.  It's only possible to find list items that are visible on screen with ctrl+f.

We should investigate ways to make the whole list searchable.

A simple option is to just build the whole list, but we may be able to get information out of the builder too.

**Comment by jacob314** [comment]
We will Control-F searching of lazy lists in multiple places. We should find a generic solution that doesn't degrade performance. This is equally critical in the inspector and the timeline views.

**Comment by jacob314** [comment]
Related issues:
https://github.com/flutter/devtools/issues/381
https://github.com/flutter/devtools/issues/1034
