### ISSUE TITLE
DevTools does not listen for protocol events until after the first isolate is returned

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#1207]
We should be allowed to return a VM with no isolates since DevTools should react to `IsolateStart` events. DevTools does not listen for events until after it determines if the protocol is serviced by Flutter Web:
https://github.com/flutter/devtools/blob/8404fae413c12b2feb386fcfecd2f31f45b779c4/packages/devtools_app/lib/src/service_manager.dart#L182

If the `Isolates` are empty, that future will never complete if the VM's initial isolates are empty.

**Comment by devoncarew** [comment]
I'd just send a PR that remove that condition. We can unconditionally send in

```
streamIds.addAll(['_Logging', EventStreams.kLogging]);
```

and just ignore errors that come back for platforms that don't support the `_Logging` event. Support for that event is likely pretty rare at this point anyway.

**Comment by devoncarew** [comment]
assumed fixed in https://github.com/flutter/devtools/pull/1211
