### ISSUE TITLE
Measure widths of the tree table columns

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1222]
Currently we're using two steps to measure the width of the `TreeColumnData` columns:

1. Measure the deepest indentation possible in the list
2. Approximate how wide the content of each cell may be with a constant.

The indentation computation is fine, but we don't accurately measure the width of each column.  We can discuss some alternatives here.

**Comment by jacob314** [comment]
Approximating the widths with a constant seems the most practical.
