### ISSUE TITLE
After the update, you can't click and locate the file.

### ISSUE THREAD

**Issue by fangkyi03** [flutter/devtools#1246]
After the update, you can't click and locate the file.
![image](https://user-images.githubusercontent.com/30390014/67276595-a2fb7a00-f4f7-11e9-86f9-afc2d1b744ab.png)
It used to support clicking and then switching to the corresponding file before updating, but now it only supports one level, which is the current page and does not support routing nesting. As long as you jump to the route once, you cannot locate the file.

https://github.com/fangkyi03/rlstyle.git
This is my own project. Now I want to find it very difficult to locate the problem. Secondly, can I add the function of classname or tag to make a mark? Now it's too much trouble to find something.

**Comment by fangkyi03** [comment]
Click to prompt this

════════ Exception caught by Flutter framework ═════════════════════════════════
Id does not exist.

I feel it has something to do with my configuration

  rlstyles:
    path: ../

But it used to work

**Comment by kenzieschmoll** [comment]
Closing as not reproducible.
