### ISSUE TITLE
Scheduling notifications

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1249]
We should have a controller that manages what notifications we propagate to the user so that we can avoid situations where we haphazardly push and remove snackbars.

**Comment by DaveShuckerow** [comment]
See #1242 for an example

**Comment by kenzieschmoll** [comment]
@DaveShuckerow is this resolved by the recent notification work you did?

**Comment by DaveShuckerow** [comment]
It is.

Fixed by #1549.
