### ISSUE TITLE
Make it easy to launch DevTools from IntelliJ for non-flutter apps.

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1252]
For example, the current steps it takes to connect the analysis server to DevTools are:
1. Specify observatory port via flag `--observe=8888`
2. Open observatory at `localhost:8888`
3. Copy vm service uri from observatory (e.g. `ws://127.0.0.1:52048/Ek1Ei7zl824=/ws`)
4. Paste into connect dialog in DevTools

We should have a button in IntelliJ that launches DevTools and connects to your running app.
FYI @lambdabaa

**Comment by devoncarew** [comment]
This is for Dart CLI apps? If so, we should likely add an 'open in DevTools' button in the Dart plugin.

**Comment by kenzieschmoll** [comment]
SGTM. Do we need to move this issue to another repo then?

**Comment by devoncarew** [comment]
Yes, to the JetBrains YouTrack issue track, for the Dart component.

**Comment by kenzieschmoll** [comment]
@alexander-doroshko I opened this [issue](https://youtrack.jetbrains.com/issue/WEB-42217) in the WebStorm component of YouTrack. Is this the correct location for the issue?

**Comment by alexander-doroshko** [comment]
@kenzieschmoll Thanks, yes, that's the right place for Dart plugin bugs and features.

Is this about Dart VM (aka Dart Command Line) apps? Probably one more step needed before `#4`: how to open the DevTools dialog that asks for this uri?

Note: you don't have to specify observatory flag manually, there's already an action to open Observatory, and also a link in the Console:
![image](https://user-images.githubusercontent.com/4499789/67848112-16fbda80-fb15-11e9-8ae1-39b546b5f735.png)

Do you think there's no interest in Observatory anymore and we should replace the button with 'Open DevTools'?

**Comment by alexander-doroshko** [comment]
> how to open the DevTools dialog that asks for this uri?

Ah, that's probably 
```
pub global activate devtools
pub global run devtools
```
And the IDE should do it automatically when needed.

**Comment by kenzieschmoll** [comment]
The plan is for DevTools to replace Observatory. In the meantime, if a user still wants to go to Observatory, they can get to it from the link in the console, but the button should be switched to 'Open DevTools'. The code that does this in the Flutter-IntelliJ plugin can be found at these links:
https://github.com/flutter/flutter-intellij/blob/master/src/io/flutter/run/OpenDevToolsAction.java#L61-L62
https://github.com/flutter/flutter-intellij/blob/master/src/io/flutter/devtools/DevToolsManager.java#L67

And yes you are correct - spawning devtools is done from the pub commands you listed. `pub global activate devtools; devtools`

CC @lambdabaa

**Comment by kenzieschmoll** [comment]
closing as this is tracked in YouTrack https://youtrack.jetbrains.com/issue/WEB-42217
