### ISSUE TITLE
Cleanup after switching to Flutter web

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1258]
TODOs to clean up the code after turning on Flutter web and turning down the HTML app:

* [x] Turn down `package:html_shim`
  * Special packages shouldn't be necessary for flutter web to be a viable development platform.
* [x] Remove code not part of the transitive deps of the `flutter` directories

**Comment by devoncarew** [comment]
Removing from the hummingbird project - this is something we'd tackle (soon) after shipping the hummingbird project.
