### ISSUE TITLE
Forwarding html framework events to Flutter

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1259]
In the debugger page, we need to propagate showMessage, toast, showError messages to the Flutter view.

In particular, we need to do the following:

* Enable the shortcutCallback from the debugger screen.
* Wire showMessage, toast, showError to show messages on the Flutter UI.

**Comment by jacob314** [comment]
Moving to backlog as we might go directly to a a full flutter implementation of the debugger page.

**Comment by jacob314** [comment]
Closing as obsolete with natively implemented debugger page.
