### ISSUE TITLE
Web URL-aware navigator

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1278]
The navigators in Flutter don't have apparent analogs to the following web conventions that we want to be able to include in the address bar:

* [ ] URL parameters `http://www.foo.com/#/?bar=baz`
  * We want to pass parameters from the URL bar and have it still translate to a Flutter route.
* [ ] Heading tags `http://www.foo.com/#section1`
  * This is useful to have in tab navigation: when you click on a tab, the URL should take you to that specific tab on the selected page.
  * We currently use LocalHistoryRoutes for this, but they aren't addressable.

We want to update the browser navigation bar as-needed to stay bound to these values.

**Comment by kenzieschmoll** [comment]
closing as obsolete
