### ISSUE TITLE
Complete logging page

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1286]
Context screenshot:

![image](https://user-images.githubusercontent.com/14947366/68054908-abe50c00-fcac-11e9-8e3c-472ae6b9f607.png)

**Comment by DaveShuckerow** [comment]
A few features that we'll need here:

* [ ] Flat table layouts that work without tree structures
* [ ] A checkbox service extension button
* [ ] Controllers tied to the lifecycle of the app (so that we don't lose the logs every tab change)
* [ ] Flutter implementation of Ansi coloring #1181

**Comment by jacob314** [comment]
This one I'm ok with shipping after we make DevTools the default as this page is P2.

**Comment by devoncarew** [comment]
I'm going to mark this one as complete, as the one remaining item is not a blocker for hummingbird, and is already tracked as a separate issue.
