### ISSUE TITLE
Complete Performance Page

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1287]
Reference Screenshot: 
![image](https://user-images.githubusercontent.com/14947366/68056053-6c6bef00-fcaf-11e9-8e62-89475a4d71a2.png)

**Comment by kenzieschmoll** [comment]
Items remaining:
- [ ] Port Bottom Up profiler view (required for the timeline as well)

**Comment by kenzieschmoll** [comment]
Closing this as the core features are ported and the tree table polish item will be tracked separately for M16.
