### ISSUE TITLE
Complete Memory View

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1288]
Reference screenshot: ![image](https://user-images.githubusercontent.com/14947366/68055538-1a769980-fcae-11e9-8f62-f224e970ba22.png)

**Comment by terrylucas** [comment]
Need to complete with GC, and timeline markup will complete over the next few days.

**Comment by kenzieschmoll** [comment]
Terry - is there anything left for this issue?

**Comment by terrylucas** [comment]
One thing the event pane (allocation events, gc, snapshots, etc.).  Which I'm now adding.

**Comment by terrylucas** [comment]
Completed see #2166
