### ISSUE TITLE
Complete Timeline View

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1289]
Reference screenshot: ![image](https://user-images.githubusercontent.com/14947366/68056150-a50bc880-fcaf-11e9-8c4d-03bfdbf128cd.png)

**Comment by kenzieschmoll** [comment]
Items remaining

Required:
- [ ] Add timeline grid (timestamps and lines) over flame chart 
- [ ] Port Bottom Up profiler view

Nice to have:
- [ ] Implement scroll to zoom (zoom is possible via WASD currently)

**Comment by kenzieschmoll** [comment]
Closing as the required items are complete and the 2 remaining "nice to have"s will be tracked separately for M16
