### ISSUE TITLE
Debugger ctrl+p searching from the library view

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1294]
We need to make sure the library panel is capturing the ctrl+f event for library search.

**Comment by leiboldm** [comment]
+1. I'd also request you adopt Chrome's ctrl+p hotkey for file search as well. It will make transitioning from Chrome devtools to Dart devtools much less painful if we don't have to retrain ourselves to use new hotkeys.

**Comment by jacob314** [comment]
Meaning of the bug has changed slightly as we are implementing the library view directly in Flutter rather than as a plugin.

**Comment by devoncarew** [comment]
Do we have this now? The flutter web library view supports filtering.

**Comment by gmoothart** [comment]
If we follow devtools, then ctrl+f should search in the current source file and ctrl+p should search "Libraries and Classes"
