### ISSUE TITLE
TabBar should have selection highlight for all screen sizes

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1307]
Tab selection is highlighted: ![Screen Shot 2019-11-06 at 9 21 15 AM](https://user-images.githubusercontent.com/43759233/68322082-a3f3e600-0077-11ea-96bc-3c06dea72491.png)
Tab selection is not highlighted: ![Screen Shot 2019-11-06 at 9 21 27 AM](https://user-images.githubusercontent.com/43759233/68322088-a5bda980-0077-11ea-8c61-ce5e58006855.png)

From @DaveShuckerow: "it's caused by both the AppBar and the TabBar having a preferred size, and the appbar's preferred size is smaller than the tabbar's preferred size"

**Comment by DaveShuckerow** [comment]
We may need a better way of enforcing the appbar's size here.  We can place it in the appbar's flexiblespace to do this.
