### ISSUE TITLE
Inspector throwing flutter assertion

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1313]
Another exception was thrown: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/scene_builder.dart:227:12

Repro steps:
- checkout devtools/master and run flutter version of DevTools
- connect to flutter app and navigate to inspector
- attempt to scroll around in either tree

Flutter doctor output:
```
Flutter 1.10.11-pre.457 • channel master • git@github.com:kenzieschmoll/flutter.git
Framework • revision 8cd892b39b (28 hours ago) • 2019-11-06 10:50:16 -0800
Engine • revision 6c763bb551
Tools • Dart 2.7.0
```

**Comment by kenzieschmoll** [comment]
@jacob314

**Comment by kenzieschmoll** [comment]
I am not seeing this on flutter desktop, just flutter web.

**Comment by jacob314** [comment]
This is likely a flutter_web bug. Can you file it on package:flutter with a more detailed stack trace?

**Comment by kenzieschmoll** [comment]
closing as this is tracked in flutter/flutter
