### ISSUE TITLE
Make it easy to jump to recently opened files

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#1333]
Their is no quick way to move between previously opened files. The native browser has tabs which is an OK solution to this, but anything that would be easy to move back and forth between files would be nice. Filtering for files is pretty laborious at this point adding 2-3 steps to get to each common file you are debugging.

**Comment by kenzieschmoll** [comment]
The debugger has a history feature allowing you to navigate back and forward between opened files as well as a history dropdown. Marking as fixed.
