### ISSUE TITLE
Support monospace font in flutter desktop

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1339]
Flutter desktop: 
![Screen Shot 2019-11-13 at 10 31 22 AM](https://user-images.githubusercontent.com/43759233/68964539-76e9b680-078e-11ea-8f89-43109d96c938.png)
Flutter web:
![Screen Shot 2019-11-13 at 10 31 28 AM](https://user-images.githubusercontent.com/43759233/68964542-78b37a00-078e-11ea-84d5-71c4886bfe75.png)

**Comment by jacob314** [comment]
Showing a monospace font is important polish for JSON and source code display.
