### ISSUE TITLE
Incomplete documentation in Performance Overview

### ISSUE THREAD

**Issue by cobblest** [flutter/devtools#1349]
From Q4 DevTools Survey:
The "Identifying problems in the UI graph" section literally says "PENDING: Other than saying “debug with DevTools”, what can be said here?" so that would be a good thing to flesh out :)
URL: https://flutter.dev/docs/perf/rendering/ui-performance

**Comment by jacob314** [comment]
Fyi @kenzieschmoll

**Comment by kenzieschmoll** [comment]
@sfshaza2 @liyuqian this is from the main perf docs https://flutter.dev/docs/perf/rendering/ui-performance
