### ISSUE TITLE
Dart VM Flag List wrong spacing 

### ISSUE THREAD

**Issue by feinstein** [flutter/devtools#1358]
Here's what I see when I open the Dart VM Flag List (arrows by me):

![image](https://user-images.githubusercontent.com/8120472/69190509-4e9be800-0aff-11ea-9ac9-84a7c0cbb9f3.png)

The values are on the opposite side, which makes them really hard to read and follow. A tabulated design, with interposed colors, and less spacing, would help a lot.

**Comment by kenzieschmoll** [comment]
we no longer show the dart vm flags - obsolete
