### ISSUE TITLE
Base ThemedColor on ThemeData.brightness

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1363]
We want to take advantage of logic Flutter exposes on theme brightness. This allows us to, for instance, use Flutter's ThemeMode to respect the system brightness setting when we deploy on desktop.

This could be an interesting, application of extension methods:

```dart
extension DevToolsTheme on Theme {
  Color selectColor(Color light, Color dark);
}

...

build(context) {
  final themedColor = Theme.of(context).selectColor(Colors.lightBlue, Colors.grey);
}
```

I'm not sure if I like the idea of using extension methods like this.

This is something we can refactor ThemedColor to do, so I'll switch to using that for now and leave an issue regarding this.

**Comment by natebosch** [comment]
See also https://github.com/flutter/devtools/issues/1073

Does flutter web currently hook this up for us? Should we file a feature request?

**Comment by jonahwilliams** [comment]
> Does flutter web currently hook this up for us? Should we file a feature request?

It does! https://github.com/flutter/engine/pull/12335

**Comment by jacob314** [comment]
We should still respect the light vs dark theme passed in by the query parameter when it is specified. If your VSCode is in a dark theme we should open devtools in a dark theme regardless of whether your browser is dark theme.
