### ISSUE TITLE
Regression in devtools dart:html app startup screen

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#1380]
We now display a spurious unable to connect error.
<img width="1171" alt="Screen Shot 2019-11-21 at 8 49 44 AM" src="https://user-images.githubusercontent.com/1226812/69358639-02a28d80-0c3c-11ea-94c4-4e4c2f319744.png">
The regression shipped in the live version of the app.
Fyi @kenzieschmoll @DaveShuckerow

**Comment by kenzieschmoll** [comment]
html app is now deleted
