### ISSUE TITLE
Timeline bar chart selection needs refactoring

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1381]
Selecting a bar from the bar chart does not trigger any flutter lifecycle methods. The selection callback should not be triggered during paint, and currently the only way to get it to work is to call the callback in a timer.

**Comment by jacob314** [comment]
The right refactoring is the selection should not be triggered from widget build, layout, or paint.
@kenzieschmoll can you note the exception that gets thrown when the callback is executed at the wrong time?

**Comment by kenzieschmoll** [comment]
```

**Comment by kenzieschmoll** [comment]
Using `addPostFrameCallback` fixes the issue, but I'm still not convinced this is the best solution.
```
WidgetsBinding.instance
          .addPostFrameCallback((_) => onSelected(frameIndex));
```

**Comment by jacob314** [comment]
We should still cleanup to detect outside of rendering the frame but with a simple post frame callback it is a little ugly rather than a hack.

**Comment by jacob314** [comment]
![lgtm](https://i.imgur.com/JgNRalI.png)
