### ISSUE TITLE
Allow devtools data to be queried from code

### ISSUE THREAD

**Issue by bitsydarel** [flutter/devtools#1395]
As a flutter developer i want to be able to launch the devtools from code and also i want to be able to query the data.

So that i can create tests based on those metrics or create test to verify average memory usage of my app after some features have been added.

**Comment by benedicte69** [comment]
import 'package:flutter/rendering.dart';
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    debugPaintSizeEnabled = true;

**Comment by bitsydarel** [comment]
How’s this related to my issue ?

I’m asking for an api to query in code for example the current used memory, cpu by my app.

The same information that we see in the dev tools

**Comment by benedicte69** [comment]
sorry for my bad answers ... may be one day in the flutter.dev channel...hope someone can help you.yours

Envoyé depuis Yahoo Mail pour Android 
 
  Le mar., nov. 26, 2019 à 14:43, Benedicte<notifications@github.com> a écrit :   
import 'package:flutter/rendering.dart';
class MyApp extends StatelessWidget {
@override
Widget build(BuildContext context) {
debugPaintSizeEnabled = true;

**Comment by liyuqian** [comment]
CC @terrylucas who has been working on making memory profiling data more accessible.

**Comment by kenzieschmoll** [comment]
This would be possible without DevTools by establishing a vm service connection from your code to query this data. `package:devtools_app_shared` includes some helpers to establish a vm service connection and a service manager class to interact with it.
