### ISSUE TITLE
Differentiate Flutter Web vs Flutter Desktop detection

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1400]
When connecting DevTools to a flutter desktop application, certain pages (e.g. Performance, Memory) are disabled with a message "This screen does not work with flutter web apps"

The motivation behind disabling these pages for flutter web apps was that Chrome devtools is more suited for web applications, but this rationale does not apply for flutter desktop apps. Perhaps we should even consider enabling both Perf and Memory pages for all apps (including flutter web).

**Comment by devoncarew** [comment]
When we do this change, we may want to take the opportunity to simplify the enablement logic. Last time I was through the code it was hard to reason about. Perhaps, change to having each page know whether it should be enabled based on the connected client?

```
Future<bool> shouldBeEnabled(ConnectClientInfo clientInfo) async {
  if (clientInfo.isWeb) ...

  if (clientInfo.isFlutterDesktop) ...

  ...
}
```
