### ISSUE TITLE
Scrolling logging table with cursor keys feels laggy

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#141]
If you click in the logging table and press and hold up or down, the selected row quickly disappears off the screen and the scrolling doesn't keep up with it. When  you let go, it quickly slides to the correct position.

This may be a similar problem to that described here:

https://github.com/flutter/devtools/blob/8bdb0b303cb4e8730a04a59a510995dacc45db79/lib/logging/logging.dart#L329-L337

However that fix applies only to adding new rows, whereas this is just scrolling the existing rows by moving the selection.

**Comment by kenzieschmoll** [comment]
@CoderDake is this resolved by your recent perf improvements?
