### ISSUE TITLE
Travis takes a long time

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1413]
I regularly have to wait ~20 minutes between starting a travis run and seeing that it's green.  Then tests may flake.  

This regularly makes the last set of comment/iterations on a PR take a half hour or more longer than it should.`

**Comment by jacob314** [comment]
The slow times to run the build bots is hurting our productivity. I would suggest pushing integration tests that only impact the dart:html app to an FYI bot that we can check them when releasing but don't slow down package:flutter iteration due to them.

**Comment by DaveShuckerow** [comment]
A few observations:

* I believe we cache flutter build artifacts.  However, if we run tests off of Flutter master, it's fairly likely new commits have landed in Flutter between test runs of our own bots.  More people work on Flutter than on DevTools.

* The mac bots take a long time to set up and run.  Linux tests are normally all finished within ~10 minutes, but the mac bots can have a longer delay in starting up and can take longer to run.

**Comment by jacob314** [comment]
I'd be fine with moving mac to the FYI bots if it helps performance a lot. We haven't had any mac specific issues as far as I know.

**Comment by DaveShuckerow** [comment]
For the PR I sent out, travis was done in <6 min.  I like this so far.
