### ISSUE TITLE
Layout overflow when inspecting flexes

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1414]
The extra space layout should be scaling the empty space so that it is large enough to display its own dimensions.

![image](https://user-images.githubusercontent.com/14947366/69982500-9f99dc00-1502-11ea-94f7-f83b38b0f310.png)

@albertusangga

**Comment by albertusangga** [comment]
Acknowledged. This is indeed the case when the main axis alignment is set to spaceBetween/spaceAround/spaceEvenly.

**Comment by albertusangga** [comment]
#1419 will fix it by truncating the text into ellipsis and showing the tooltip when hovered
