### ISSUE TITLE
Inspector broken in html app

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1418]
Selecting a widget from the summary tree does not update the details tree: 
![broken_inspector](https://user-images.githubusercontent.com/43759233/70015695-f9b29580-1532-11ea-8d6c-109f23b42261.gif)

**Comment by albertusangga** [comment]
@kenzieschmoll  do you have any idea on what the cause is?
Since I made a lot of changes in the Flutter Inspector Screen that requires changing the controller, I hope I'm not breaking anything in the HTML app

**Comment by kenzieschmoll** [comment]
Found the culprit commit after bisecting: https://github.com/flutter/devtools/commit/2097183716ac5a9c2772f2e5078f8e1919275456. Not entirely sure how that is related to the inspector. Investigating now.
