### ISSUE TITLE
Overflow paint shows up incorrectly on web

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1451]
![image](https://user-images.githubusercontent.com/14947366/70279120-91e68f80-176a-11ea-8110-f09a1d400099.png)

We should see the yellow/black border instead of the pure-black border.

**Comment by jacob314** [comment]
@DaveShuckerow is this a canvaskit bug or a bug on our end?

**Comment by DaveShuckerow** [comment]
This is from upstream.

**Comment by kenzieschmoll** [comment]
closing as not reproducible
