### ISSUE TITLE
RichText spans with fontweight w600 not showing up in CanvasKit renderer

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1465]
![image](https://user-images.githubusercontent.com/14947366/70361736-6b425a80-1837-11ea-8eb3-d4133716b620.png)

Some of the text should be semibold, and some normal.

**Comment by DaveShuckerow** [comment]
@hterkelsen

**Comment by jacob314** [comment]
Is there a matching bug in the flutter engine?

**Comment by hterkelsen** [comment]
Do you still see this issue? This is what I see when I run the latest Flutter with CanvasKit enabled:
![boldtextdevtools](https://user-images.githubusercontent.com/1961493/72020661-1c665700-3221-11ea-8938-40ed63cbee99.png)

Closing this issue. Please re-open if you still see the problem.
