### ISSUE TITLE
Widget Inspector not working in release mode and iOS Simulator

### ISSUE THREAD

**Issue by adalberht** [flutter/devtools#1470]
Repro steps:
- run DevTools flutter app in release mode `flutter run -d macOS --release` 
- connect to Flutter App that is run in iOS simulator
- enable Select Widget Mode
- click on any widget on the simulator
- Inspector fails to scroll and follow the currently selected node

**Comment by jacob314** [comment]
The inspector only works in debug builds.
Please reopen if you cannot open the inspector in debug builds.
The inspector depends on many methods protected behind debug methods in the Flutter framework. Enabling the inspector in release builds would significantly increase code size for release builds.
