### ISSUE TITLE
Layout Explorer is not visible/available 

### ISSUE THREAD

**Issue by KenAragorn** [flutter/devtools#1481]
As per the official documentation link [https://flutter.dev/docs/development/tools/devtools/inspector#inspecting-a-widget](https://flutter.dev/docs/development/tools/devtools/inspector#inspecting-a-widget), in order to access the Flutter Layout Explorer, we have to fulfill the following:

1. This feature is only available in the alpha version of DevTools written in Flutter
2. Currently only supporting flex widget such as Flex, Row and Column
3. Flutter version need to be 1.12.16 or later

However, even though I fulfill all, the layout explorer is noway to be seen.

  
![cap1](https://user-images.githubusercontent.com/14989228/70771008-a77f3900-1daa-11ea-8e94-1e95adc732cb.PNG)

Currently Im in Flutter version 1.12.13+hotfix.6 (which is higher than 1.12.16).

![cap2](https://user-images.githubusercontent.com/14989228/70771054-ca115200-1daa-11ea-9b19-24a2f6138599.PNG)

**Comment by raison00** [comment]
All of the parameters mentioned in your list are necessary to launch this alpha version of the Dart DevTools in Flutter, but there's one more step to launch the Layout Explorer.   

In this image below, I've circled the icon you'll use to launch the Layout Explorer - hint, it's the very last one to the right:

![layout-explorer-icon](https://user-images.githubusercontent.com/8105802/71134379-e6e6c480-21b2-11ea-961b-4115abbfa15e.png)

Once you click on this icon, it will launch the alpha version of the Layout Explorer.  

It should appear similarly to this:

![dart-dev-tools](https://user-images.githubusercontent.com/8105802/71134461-4218b700-21b3-11ea-9665-33e2ac13ad42.png)

If you're still unable to see this, confirm you're properly connected in the Console to your device/simulator.  If these icons are not in full color, the Layout Explorer won't be visible.

![image](https://user-images.githubusercontent.com/8105802/71134689-092d1200-21b4-11ea-9735-ac71d9aba1f3.png)


The Layout Explorer is an alpha version, so look, feel, and functionality will improve as the tool matures. This tool is only available with the newer release of flutter (1.12 or higher).

![image (19)](https://user-images.githubusercontent.com/8105802/71134613-c3704980-21b3-11ea-93da-860b7754c349.png)

**Comment by albertusangga** [comment]
@KenAragorn Yes, just like @raison00 explained, unfortunately you have to switch out to Flutter channel master for now to try out the Layout Explorer (`flutter channel master`)

**Comment by jacob314** [comment]
We're looking forward to you trying out the LayoutExplorer once it is available on the version of Flutter you use!
