### ISSUE TITLE
NaN toInt error in memory chart

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1487]
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following UnsupportedError was thrown during paint():
flutter: Unsupported operation: Infinity or NaN toInt
flutter: 
flutter: The relevant error-causing widget was:
flutter:   LineChart
flutter:   file:///Users/kenzieschmoll/develop/devtools/packages/devtools_app/lib/src/memory/flutter/memory_chart.dart:93:16
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #0      double.toInt (dart:core-patch/double.dart:194:36)
flutter: #1      double.floor (dart:core-patch/double.dart:163:34)
flutter: #2      AxisRenderer.computeAxisValues (package:mp_chart/mp/core/render/axis_renderer.dart:197:44)
flutter: #3      AxisRenderer.computeAxis (package:mp_chart/mp/core/render/axis_renderer.dart:127:5)
flutter: #4      BarLineChartBasePainter.compute (package:mp_chart/mp/painter/bar_line_chart_painter.dart:460:25)
flutter: #5      BarLineChartBasePainter.calculateOffsets (package:mp_chart/mp/painter/bar_line_chart_painter.dart:479:5)
flutter: #6      ChartPainter.paint (package:mp_chart/mp/painter/painter.dart:238:7)
flutter: #7      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:531:13)
flutter: #8      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:572:7)
flutter: #9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #11     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
flutter: #12     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #13     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #14     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
flutter: #15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #17     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
flutter: #18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #20     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2516:15)
flutter: #21     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:587:5)
flutter: #22     RenderStack.paint (package:flutter/src/rendering/stack.dart:595:7)
flutter: #23     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #24     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #25     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
flutter: #26     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2032:11)
flutter: #27     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #28     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #29     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
flutter: #30     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #31     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
flutter: #32     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
flutter: #33     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:201:7)
flutter: #34     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:182:7)
flutter: #35     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
flutter: #36     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #37     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #38     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
flutter: #39     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #40     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #41     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2516:15)
flutter: #42     RenderFlex.paint (package:flutter/src/rendering/flex.dart:948:7)
flutter: #43     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #44     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #45     _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:257:15)
flutter: #46     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #47     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #48     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2516:15)
flutter: #49     RenderFlex.paint (package:flutter/src/rendering/flex.dart:948:7)
flutter: #50     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #51     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #52     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
flutter: #53     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #54     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #55     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
flutter: #56     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #57     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #58     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
flutter: #59     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #60     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
flutter: #61     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
flutter: #62     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:201:7)
flutter: #63     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:182:7)
flutter: #64     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
flutter: #65     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #66     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #67     RenderSliverMultiBoxAdaptor.paint (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:640:17)
flutter: #68     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #69     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #70     RenderSliverEdgeInsetsPadding.paint (package:flutter/src/rendering/sliver_padding.dart:275:15)
flutter: #71     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #72     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #73     RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:586:17)
flutter: #74     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:391:12)
flutter: #75     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:447:7)
flutter: #76     RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:577:15)
flutter: #77     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #78     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
flutter: #79     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
flutter: #80     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:981:29)
flutter: #81     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:403:19)
flutter: #82     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:797:13)
flutter: #83     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
flutter: #84     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1108:15)
flutter: #85     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1047:9)
flutter: #86     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:963:5)
flutter: #90     _invoke (dart:ui/hooks.dart:259:10)
flutter: #91     _drawFrame (dart:ui/hooks.dart:217:3)
flutter: (elided 3 frames from package dart:async)
flutter: 
flutter: The following RenderObject was being processed when the exception was fired: RenderCustomPaint#e26ac:
flutter:   creator: CustomPaint ← _PointerListener ← Listener ← _GestureSemantics ← RawGestureDetector ←
flutter:     GestureDetector ← ConstrainedBox ← Stack ← DecoratedBox ← Container ←
flutter:     RepaintBoundary-[GlobalKey#8f744] ← Screenshot<dynamic> ← ⋯
flutter:   parentData: <none> (can use size)
flutter:   constraints: BoxConstraints(w=1368.0, h=179.3)
flutter:   size: Size(1368.0, 179.3)
flutter: This RenderObject has no descendants.
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: 405.2890625
flutter: 416.74609375
flutter: Another exception was thrown: Unsupported operation: Infinity or NaN toInt
flutter: 432.40234375
flutter: 423.35546875
flutter: Another exception was thrown: Unsupported operation: Infinity or NaN toInt

**Comment by kenzieschmoll** [comment]
@terrylucas you said you have a fix in progress for this, correct?

**Comment by terrylucas** [comment]
Yep, this has been fixed in PR https://github.com/flutter/devtools/pull/1553

**Comment by kenzieschmoll** [comment]
Fixed by #1553
