### ISSUE TITLE
The method 'toFilePath' was called on null 

### ISSUE THREAD

**Issue by apaolino** [flutter/devtools#1497]
When I open devTools on last flutter stable version  (1.12.13+hotfix5) it crashes. I captured this log:

Dart Code extension: 3.7.1
Flutter extension: 3.7.1 (not activated)
VS Code: 1.41.1
Platform: win
Workspace type: Flutter
Multi-root?: false
Dart SDK:
    Loc: C:\Users\ThinkPad\Documents\Development\Flutter_SDK\flutter_new\bin\cache\dart-sdk
    Ver: 2.7.0-dev.2.1
Flutter SDK:
    Loc: C:\Users\ThinkPad\Documents\Development\Flutter_SDK\flutter_new
    Ver: 1.12.13+hotfix.5
HTTP_PROXY: undefined
NO_PROXY: undefined

Mon Dec 23 2019 [12:41:01 GMT+0100 (Ora standard dell’Europa centrale)] Log file started
[12:41:07] [DevTools] [Info] Spawning C:\Users\ThinkPad\Documents\Development\Flutter_SDK\flutter_new\bin\cache\dart-sdk\bin\pub.bat with args ["global","run","devtools","--machine","--enable-notifications","--try-ports","10"]
[12:41:07] [DevTools] [Info]     PID: 3584
[12:41:07] [DevTools] [Error] Unhandled exception:
[12:41:07] [DevTools] [Error] 
NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      defaultHandler (package:devtools_server/src/handlers.dart:28:60)
<asynchronous suspension>
#2      serveDevTools (package:devtools_server/src/server.dart:143:21)
#3      serveDevToolsWithArgs (package:devtools_server/src/server.dart:99:10)
#4      main (file:///C:/Users/ThinkPad/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/devtools-0.1.13/bin/devtools.dart:9:3)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
[12:41:07] [DevTools] [Info] Process terminated! 255, null
[12:41:07] [General] [Error] Dart DevTools exited with code 255
[12:41:07] [General] [Error] Dart DevTools exited with code 255
Mon Dec 23 2019 [12:41:10 GMT+0100 (Ora standard dell’Europa centrale)] Log file ended

**Comment by doppio** [comment]
I'm seeing the same issue. I'm able to run DevTools if I manually run `flutter pub global run devtools`, `flutter run`, and paste the URL into `http://127.0.0.1:9100/`. I just can't use VS Code to debug my app and open DevTools, which would be far more convenient.

**Comment by doppio** [comment]
I found a solution, @apaolino! I just removed my pub cache files (in your case, located at C:/Users/ThinkPad/AppData/Roaming/Pub/Cache). It works now. 🎉

**Comment by apaolino** [comment]
Hi, thanks for suggestion! in particular I deleted only the C:\Users\ThinkPad\AppData\Roaming\Pub\Cache\global_packages\devtools and it works!

**Comment by sunjianan9900** [comment]
> Hi, thanks for suggestion! in particular I deleted only the C:\Users\ThinkPad\AppData\Roaming\Pub\Cache\global_packages\devtools and it works!

do you know what's the mac path  ?
