### ISSUE TITLE
DevTools about dialog / version

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#1511]
There’s no way to know what version of DevTools you’re using from the app UI. This info should be available, even if DevTools is not currently connected to a running app.

**Comment by kenzieschmoll** [comment]
The version is available on the info page
<img width="513" alt="Screen Shot 2020-01-07 at 2 47 04 PM" src="https://user-images.githubusercontent.com/43759233/71935848-b7e1c400-315c-11ea-8d14-e0f8c38c2f84.png">

Though I agree this information should be made available even if you are not connected to an app.
