### ISSUE TITLE
Performance processing take a long long time

### ISSUE THREAD

**Issue by potatoker** [flutter/devtools#1514]
in the performance tab, after recording, I clicked stop, then It always shows : Processing profile.

I can not get the result of the profiling.
![image](https://user-images.githubusercontent.com/5286501/71965788-4f1d4900-323b-11ea-8285-e15fbfe8eab7.png)

It had taken more than 30 minutes, and was like showing that processing forever.

**Comment by kenzieschmoll** [comment]
Thanks for the report! A few questions:

- If you open the Chrome Dev Console, do you see any errors?
- What platform are you using (Mac, Windows, Linux)?
- What platform is your connected app running on (Android emulator, Android physical device, iOS, etc.)?

**Comment by kenzieschmoll** [comment]
Without further information, I'm afraid we cannot solve the issue. My suspicion is that there was an error thrown that prohibited the processing code from completing. There have been some improvements made in recent DevTools releases that may address this issue. The latest version of DevTools you can checkout is 0.1.14-dev.2. Please re-open this issue if you see the problem again. Thanks.
