### ISSUE TITLE
Tooltip error in flame chart

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1518]
To reproduce, select node and move mouse off of selected node before tooltip shows
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'findRenderObject' was called on null.
Receiver: null
Tried calling: findRenderObject()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _TooltipState._createNewEntry (package:flutter/src/material/tooltip.dart:283:35)
#2      _TooltipState.ensureTooltipVisible (package:flutter/src/material/tooltip.dart:277:5)
#3      _rootRun (dart:async/zone.dart:1122:38)
#4      _CustomZone.run (dart:async/zone.dart:1023:19)
#5      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#7      _rootRun (dart:async/zone.dart:1126:13)
#8      _CustomZone.run (dart:async/zone.dart:1023:19)
#9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by kenzieschmoll** [comment]
I believe the fix for this should be on the Flutter side: https://github.com/flutter/flutter/issues/54096

**Comment by jacob314** [comment]
How bad is the issue? Should this block shipping the flutter web version of devtools?

**Comment by kenzieschmoll** [comment]
It just prints errors to console but does not affect the running application. I don't think it is a blocker. If the error output is a problem to ship, we can disable tooltips. 

I also saw this issue in the debugger page when clicking the libraries button to toggle the libraries view visibility. It would be nice if we could get the fix in flutter to prevent this issue. In both cases, the error occurs because we select an element and therefore rebuild it to change the appearance before the original tooltip has time to appear.
