### ISSUE TITLE
build_runner serve web fails when using Flutter's version of pub

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#153]
What I'm doing here might not be very supported, but since the behaviour seemed strange I thought it was worth raising.

When VS Code has a Flutter project open it always uses the Dart SDK from the Flutter SDK. This means if we want to `pub run build_runner watch` this (I know we probably want `webdev`, but this was already here so I tried it) it'll use Flutter's version. I noticed a weird discrepancy when running `pub run build_runner serve web` using this version of pub versus Dart v2.1 (the Dart one works, the Flutter one does not).

I don't know if this is an expected difference because it's in Flutter, or if something changed/broke between v2.1 and vMaster of Dart.

## Dart v2.1

```
dantup-macbookpro:devtools dantup$ which pub
/Users/dantup/Dev/dart-sdk/v2.1/bin/pub

dantup-macbookpro:devtools dantup$ pub run build_runner serve web
[INFO] Generating build script completed, took 293ms
[INFO] Setting up file watchers completed, took 17ms
[INFO] Waiting for all file watchers to be ready completed, took 203ms
[INFO] Reading cached asset graph completed, took 383ms
[INFO] Checking for updates since last build completed, took 573ms
[INFO] Running build completed, took 15.8s
[INFO] Caching finalized dependency graph completed, took 170ms
[INFO] Succeeded after 16.0s with 217 outputs (151 actions)
Serving `web` on http://localhost:8080
```

## Flutter (master)

```
dantup-macbookpro:devtools dantup$ /Users/dantup/Dev/Google/flutter/bin/cache/dart-sdk/bin/pub run build_runner serve web
[INFO] Generating build script completed, took 366ms
[INFO] Setting up file watchers completed, took 21ms
[INFO] Waiting for all file watchers to be ready completed, took 204ms
[WARNING] Throwing away cached asset graph due to Dart SDK update.
[INFO] Cleaning up outputs from previous builds. completed, took 229ms
[INFO] Reading cached asset graph completed, took 576ms
[INFO] Building new asset graph completed, took 1.2s
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[WARNING] build_modules|dartdevc on lib/.dartdevc.meta_module.raw:
Unable to read module information for package:flutter, make sure you have a dependency on it in your pubspec.
[SEVERE] build_web_compilers|ddc on package:vm_service_lib/vm_service_lib.dartdevc.module:

ProcessException: No such file or directory
  Command: /Users/dantup/Dev/Google/flutter/bin/cache/dart-sdk/bin/dartdevc --persistent_worker
[SEVERE] build_web_compilers|ddc on package:meta/meta.dartdevc.module:

ProcessException: No such file or directory
  Command: /Users/dantup/Dev/Google/flutter/bin/cache/dart-sdk/bin/dartdevc --persistent_worker
[SEVERE] build_web_compilers|ddc on package:intl/number_symbols.dartdevc.module:

ProcessException: No such file or directory
  Command: /Users/dantup/Dev/Google/flutter/bin/cache/dart-sdk/bin/dartdevc --persistent_worker
[SEVERE] build_web_compilers|ddc on package:intl/date_symbols.dartdevc.module:

ProcessException: No such file or directory
  Command: /Users/dantup/Dev/Google/flutter/bin/cache/dart-sdk/bin/dartdevc --persistent_worker
[WARNING] build_web_compilers|entrypoint on web/main.dart:
Unable to read intl|lib/date_symbols.ddc.js, check your console or the `.dart_tool/build/generated/intl/lib/date_symbols.ddc.js.errors` log file.
[WARNING] build_web_compilers|entrypoint on web/main.dart:
Unable to read vm_service_lib|lib/vm_service_lib.ddc.js, check your console or the `.dart_tool/build/generated/vm_service_lib/lib/vm_service_lib.ddc.js.errors` log file.
[WARNING] build_web_compilers|entrypoint on web/main.dart:
Unable to read intl|lib/number_symbols.ddc.js, check your console or the `.dart_tool/build/generated/intl/lib/number_symbols.ddc.js.errors` log file.
[WARNING] build_web_compilers|entrypoint on web/main.dart:
Unable to read meta|lib/meta.ddc.js, check your console or the `.dart_tool/build/generated/meta/lib/meta.ddc.js.errors` log file.
[WARNING] No actions completed for 15.1s, waiting on:
  - build_web_compilers|ddc on package:path/path.dartdevc.module
  - build_web_compilers|ddc on package:intl/number_symbols_data.dartdevc.module
  - build_web_compilers|ddc on package:intl/src/plural_rules.dartdevc.module
  - build_web_compilers|ddc on package:intl/intl.dartdevc.module
  - build_web_compilers|ddc on package:collection/src/utils.dartdevc.module
  .. and 12 more

[WARNING] No actions completed for 15.1s, waiting on:
  - build_web_compilers|ddc on package:path/path.dartdevc.module
  - build_web_compilers|ddc on package:intl/number_symbols_data.dartdevc.module
  - build_web_compilers|ddc on package:intl/src/plural_rules.dartdevc.module
  - build_web_compilers|ddc on package:intl/intl.dartdevc.module
  - build_web_compilers|ddc on package:collection/src/utils.dartdevc.module
  .. and 12 more
```

@devoncarew @jacob314

**Comment by DanTup** [comment]
`pub global run webdev serve web` seemed to work (even using Flutter's version), so I'll try switching over to that (it turns out I can't re-use the existing commands anyway, as I have no hook to know when the build finishes and it's safe to launch the browser). So this isn't blocking me, I'm raising more out of concern/curiosity :-)

```
dantup-macbookpro:devtools dantup$ pub global run webdev serve web
Creating build script, took 5667ms
[INFO] Setting up file watchers completed, took 18ms
[INFO] Waiting for all file watchers to be ready completed, took 204ms
[INFO] Reading cached asset graph completed, took 412ms
[INFO] Checking for updates since last build completed, took 524ms
[INFO] Running build completed, took 17.7s
[INFO] Caching finalized dependency graph completed, took 171ms
[INFO] Succeeded after 17.9s with 217 outputs (151 actions)
Serving `web` on http://localhost:8080
```

**Comment by DanTup** [comment]
(deleted that last comment, it was wrong...)

Same happens when running `pub global run webdev serve web` using Flutter's `pub`. This complicates things, since with a Flutter project open, Flutter's SDK is the only one we know (and in the case of a typical Flutter user, it might be the only one they have).

**Comment by jakemac53** [comment]
Flutter doesn't (today) ship with the web compilers (ddc, dart2js), so its failing because of that.

We may ship them with flutter in the future to resolve this, or we can at least provide a better message, but there isn't much else that can be done on the build side of things.

See the related issue in the build repo https://github.com/dart-lang/build/issues/1946

**Comment by DanTup** [comment]
Understood. In this case I think compiling on the end users machine doesn't make sense and we should pre-compile it. Since this seems expected behaviour (besides not having a good message which is covered in the linked issue) I guess there's nothing to do here.

**Comment by timtraversy** [comment]
Is there a solution to this issue? I'm working on an AngularDart project in Web Storm and my Dart SDK is set to the non-flutter one. But if I have a Flutter project open in Android Studio it tries to use the Flutter Dart SDK when building. Do I just have to work on one thing at a time?

**Comment by DanTup** [comment]
Are you saying that opening a project in Android Studio is changing the SDK that Web Storm uses? This sounds a little strange to me, though I'm not very familiar with them. @devoncarew @pq does this sound expect? Is there a way around it?

(In VS Code, the SDK being used is per-window, so if you had two VS Code windows open and one is a Flutter project and one is not, they'll use their corresponding SDKs.)

**Comment by devoncarew** [comment]
@timtraversy, the behavior you're describing sounds possibly in very old versions of our tools, but hard to understand how it's happening now. I'd update both webstorm and andrtoid studio (and the associated dart and flutter plugins) and see if you can still repro this.

The Dart and Flutter plugins do share a setting for the dart sdk, but that setting is essentially persisted at the project level. Having separate projects should work for you here - allow you to have separate settings for the dart sdk for use in angular and flutter projects.

For this repo, we set the sdk to a flutter one during development. That allows us to analyze one of the flutter apps in this repo that we use for testing purposes. We then do `pub run webdev serve` on the command line, using the regular dart sdk, in order to build and serve the (web based) app.

**Comment by timtraversy** [comment]
Ok I'll try to update and see if I can repro. WebStorm was working fine, and then all of a sudden it started trying to use the Flutter Dart SDK and failing. I'll report back.
