### ISSUE TITLE
memory docs have three 'pending' items

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#1563]
Our documentation for the devtools' memory page have three user-visible pending/todo items in the docs:

https://flutter.dev/docs/development/tools/devtools/memory#class-instances

We should (preferentially) address these, or convert them to markdown comments for todos.

cc @terrylucas

**Comment by cobblest** [comment]
There is also one "pending item" in Overview- Identifying problems in the UI graph 
https://flutter.dev/docs/perf/rendering/ui-performance#identifying-problems-in-the-ui-graph
