### ISSUE TITLE
Can't debug DevTools on Flutter Web

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1564]
Clicking Run or Debug to launch a debug build of DevTools results in 
![Screen Shot 2020-01-22 at 10 47 46 AM](https://user-images.githubusercontent.com/43759233/72924193-5f3a2b80-3d05-11ea-84fd-6a1a40ae197e.png)

Confirmed that release mode is WAI

**Comment by devoncarew** [comment]
@kenzieschmoll - what would be a good milestone for this issue?

**Comment by kenzieschmoll** [comment]
Since release mode is fine, I put it in the next milestone (M15) as opposed to M14 releasing this week.

**Comment by kenzieschmoll** [comment]
No longer seeing this issue after upgrading to the latest flutter.
