### ISSUE TITLE
Closing the app window or canceling  the debugging session via the banner at the top of the chrome page isn't reflected in the DevTools UI

### ISSUE THREAD

**Issue by leonsenft** [flutter/devtools#1589]
When debugging a VM app, normally killing the app produces a notification in DevTools indicating that the connection has been lost. There appears to be no such notification for the web equivalents (such as closing the app window or cancelling the debug session via the Cancel button or X in the debug banner).

@grouma

**Comment by grouma** [comment]
This will be closed by https://github.com/dart-lang/sse/pull/21 (and updating the version in this package)
