### ISSUE TITLE
Adding a breakpoint while paused at a breakpoint disables the stepping buttons

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#1594]
The step buttons are conditionally enabled by the `lastEvent`: https://github.com/flutter/devtools/blob/4edb8cb9d68721701b08be5b0efd9c7b377cfd3c/packages/devtools_app/lib/src/debugger/html_debugger_screen.dart#L302

When you add a breakpoint while paused the `lastEvent` will be of type `kBreakpointAdded`: https://github.com/flutter/devtools/blob/4edb8cb9d68721701b08be5b0efd9c7b377cfd3c/packages/devtools_app/lib/src/debugger/debugger_state.dart#L153

The VM protocol states the following:
```Dart
  // The top stack frame associated with this event, if applicable.
  //
  // This is provided for the event kinds:
  //   PauseBreakpoint
  //   PauseInterrupted
  //   PauseException
  //
  // For PauseInterrupted events, there will be no top frame if the
  // isolate is idle (waiting in the message loop).
  //
  // For the Resume event, the top frame is provided at
  // all times except for the initial resume event that is delivered
  // when an isolate begins execution.
  Frame topFrame [optional];
```
Thus, devtools needs to update its logic to account for events that don't have the topframe set, but don't impact the paused state of the VM.

**Comment by kenzieschmoll** [comment]
This was for the html app. Just tested and verified that this does not happen in the flutter app.
