### ISSUE TITLE
Implement zoom on scroll / shift + scroll for flutter flame charts

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1600]
We need to decide what the DevTools standard for zoom should be. Scroll or shift + scroll? These controls may apply to other views in DevTools and we want to be consistent.

**Comment by jacob314** [comment]
Lets start with making shift + scroll the default for zoom. That is the natural default for all pages other than the timeline which users coming from Chrome DevTools would expect that scroll zooms.
We could display a toast on the timeline page saying to hold down shift to zoom if a user scrolls for the first time.

**Comment by jacob314** [comment]
I'm also open to having a little bit of inconsistency and making the timeline zoom on scroll while other pages where zoom isn't so common require shift.

**Comment by kenzieschmoll** [comment]
Here are some related Flutter bugs filed while working on this issue: https://github.com/flutter/flutter/issues/52767,
https://github.com/flutter/flutter/issues/35723,
https://github.com/flutter/flutter/issues/52762
