### ISSUE TITLE
Prep for Q1-2020 DevTools Survey

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1605]
We need to audit how we store the "surveyActionTaken" bit in devtools_server and make sure our approach works for users who have already filled this bit from Q4-2019. We likely will need to store and check for different values by a key "Q1-2020", "Q2-2020", etc.
FYI @terrylucas 

Survey will run 3/11-4/10.

**Comment by kenzieschmoll** [comment]
Terry, have you had time to look at the server changes we will need for this?

**Comment by terrylucas** [comment]
So would the default properties be:

"Q1-2020": false
"Q2-2020": false

**Comment by terrylucas** [comment]
What about the surveyShownCount do you need this for each qtr survey?

**Comment by kenzieschmoll** [comment]
I was thinking we would have the "Q1-2020" bit be the top level field in the data.
```
{
  "Q1-2020": {
    "surveyActionTaken": false
   "surveyShownCount": 0
  },
  ...
}
```

So for each new survey each quarter, we can query  `json["Q1-2020"]`. If the field is non-null, we can check the properties we are interested in, if it is null, we can set the data to the default values shown above.  Ideally the server would just handle all that.

**Comment by terrylucas** [comment]
When you say the server would handle you mean based on the version of the server being used the server will decide what the current apis are displaying/setting for active surveys we'll of course remember if other qtr surveys have ever been taken.  Do you need a query to tell you what the active quarter survey is?

**Comment by kenzieschmoll** [comment]
I mean the server can handle returning the proper data for the quarter. As in we pass the server a string ("Q1-2020") and it returns the survey data for that quarter (returning the default data if there currently is not data assigned to the given key string).

As we've discussed in previous meetings, the ultimate goal would be to have all survey logic handled server side so that in devtools / intellij, we don't have to make code changes for every quarter. In this world, it would be as simple as `if (shouldShowSurvey) showSurvey();`, but we don't live in this world yet.

So for now, we'll have to modify the devtools_server to handle getting / setting survey data for multiple quarters. In the short term, it would be best if the only change we have to make to the devtools client is changing the survey URL and the "key" ("Q1-2020") we pass to the devtools_server.
