### ISSUE TITLE
"Last" frame in timeline is not last and never moves

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#161]
I'm not I totally understand the relationship between the top graph and the list of frames here, but when my app is rendering frames the very last box here (1.7ms / 16.6ms) never moves - all the others scroll to the left but it seems like one (the first frame?) is stuck to the end of the list.

![screenshot 2019-01-24 at 11 37 29 am](https://user-images.githubusercontent.com/1078012/51675783-9845a000-1fcc-11e9-9029-15889244cb62.png)

**Comment by DanTup** [comment]
@devoncarew I think this is just a typo - should this 1 be a 0 or is there a reason to keep the first frame at the end?

https://github.com/flutter/devtools/blob/a23f7eb60bee9a8ea7b09487fbc091652114418b/lib/timeline/timeline.dart#L249-L257

**Comment by devoncarew** [comment]
That looks very suspicious; I think you're right and it should be a zero. Also cc @kenzieschmoll
