### ISSUE TITLE
Make frames in the live chart clickable?

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#162]
@devoncarew It feels a bit weird (frustrating, even) that we can't click frames in the live chart, and it seems like there's a lot of overlap with the frames shown underneath.

Could we make these clickable, or even maybe combine the two? For ex. we could split the bars in the live chart into two colours (for GPU/Dart) and add a tooltip with the numbers and show the selection in the live chart.

Keyboard navigation to move left/right would be neat too :-)

(I don't know how easy it'll be to figure out the frame under the mouse from the coordinate clicks given it's canvas, but if we think this'd be a good change I'm happy to have a go).

**Comment by devoncarew** [comment]
Agree with all the above, and have discussed with/ Kenzie. We should likely elinate ine graph (perhaps the bottom one) and make the top graph items clickable as well as have them also represent the GPU portion of the frame (which they don't currently). Some of thus is captured in the planning doc.

Happy to have you help here (in which case, please coordinate with @kenzieschmoll).

**Comment by DanTup** [comment]
Sounds good :)

@kenzieschmoll let me know if you want me to look at any of it, as I'm not sure if you already had plans/had started it.

**Comment by devoncarew** [comment]
outdated - we've refactored the UI for this page
