### ISSUE TITLE
we should provide lightweight feedback when we're not able to set a breakpoint

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#165]
When we can't set a breakpoint, we should provide some lightweight feedback to the user (something less than a dialog or toast). Perhaps flashing the associated source line once or twice.

**Comment by devoncarew** [comment]
From discussion on https://github.com/flutter/devtools/pull/164.,

**Comment by kenzieschmoll** [comment]
Are the small dots indicating where you can set a breakpoint sufficient for this issue? @devoncarew

**Comment by devoncarew** [comment]
I think so - they'll have a good sense before they click what should happen.
