### ISSUE TITLE
Handle deeply nested objects

### ISSUE THREAD

**Issue by rrousselGit** [flutter/devtools#1679]
The devtool seems to not support "expanding" deeply nested objects

Diagnosticable objects with diagnosticable members, or lists of diagnosticable objects may print in not show the full information.

To be more specific, it seems like the devtool only a fixed depth and then fallback to showing `toString` instead of having the "expandable" feature.

Would it be possible to remove this `toString` fallback and support deeply nested objects?

**Comment by jacob314** [comment]
Can you provide a repro? There is not a fallback to `toString` but it sounds like something is going wrong with how some objects are deserialized.

**Comment by rrousselGit** [comment]
Sure:

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class A with DiagnosticableTreeMixin {
  A(this.a, this.b);
  final String a;
  final B b;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(StringProperty('a', a));
    properties.add(DiagnosticsProperty<B>('b', b));
  }
}

class B with DiagnosticableTreeMixin {
  B(this.b);

  final String b;
  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(StringProperty('b', b));
  }
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SizedBox.expand();
  }

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);

    properties.add(DiagnosticsProperty('a', A('a', B('b'))));
    properties.add(DiagnosticsProperty('b', B('b')));
  }
}
```

<img width="175" alt="Screenshot 2020-02-28 at 18 03 14" src="https://user-images.githubusercontent.com/20165741/75573373-98786080-5a54-11ea-8d7b-c83446c33ff1.png">


In this screenshot, we can see that `B` cannot be expanded if it is a descendant of `A`.
But if we use it independently from `A`, then `B` can correctly be expanded.

**Comment by rrousselGit** [comment]
Anything I can do to help this progress?

**Comment by kenzieschmoll** [comment]
@jacob314 any updates on this?
