### ISSUE TITLE
Support instruction size analysis

### ISSUE THREAD

**Issue by dnfield** [flutter/devtools#1697]
Dart can produce a dump of the instruction size usage, which it provides a tool for turning into a D3 based tree map.

For example, these commands work:

```
flutter build aot --release --extra-gen-snapshot-options=--print-instructions-sizes-to=./gallery_instruction_sizes.json
dart ~/src/flutter/engine/src/third_party/dart/pkg/vm/bin/run_binary_size_analysis.dart gallery_instruction_sizes.json ./gallerysize
```

But require you to have that package avaliable locally (generally via a dart checkout or an engine checkout), and require you to have and distribute d3 assets/licenses.  It'd be pretty slick if devtools could help us visualize this data without needing to create separate treemaps and copies of the d3 bundle to render it all.

**Comment by dnfield** [comment]
Related to https://github.com/flutter/flutter/issues/51594

**Comment by devoncarew** [comment]
Do you mind attaching a sample of one of those json files to this issue, and including a screen shot of what the visualization looks like in d3? Thanks!

**Comment by dnfield** [comment]
the JSON is pretty big - I put a formatted version of it for the hello_world example app from Flutter here: https://gist.github.com/dnfield/52a5e244407f483369f148b1c83e9090

Here's a screenshot of the treemap that creates:

![image](https://user-images.githubusercontent.com/8620741/75834215-4004d400-5d70-11ea-90df-21b1aa6436c2.png)

And another view with hover over it:

![image](https://user-images.githubusercontent.com/8620741/75834235-4eeb8680-5d70-11ea-936c-4cf38a5c389d.png)


We do interactive versions of this for the engine C++ binary code here - it's not from Dart code and is generated a little differently but the interface is similar.

https://storage.googleapis.com/flutter_infra/flutter/56398d2f3bd5ef1c7334fcfb9628517b2cfcdb57/android-arm64-release/sizes/index.html

**Comment by devoncarew** [comment]
Thanks! App size tooling is something we're thinking about but haven't yet done much research into (what are the existing tools; should generally document what exists and polish workflow issues; should we recommend everything write to an industry standard data format, and recommend off-the shelf tooling to analyze it; should we write to a data format but build our own visualization tooling, ...)

I created an `app size tooling` label for this so we can collect thoughts. cc @jacob314 @csells

**Comment by kenzieschmoll** [comment]
This is fixed.
