### ISSUE TITLE
Can't run Flutter Web DevTools in debug mode

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1707]
Launching DevTools in debug mode (target device Chrome) doesn't load DevTools. Stuck on loading:
<img width="1060" alt="Screen Shot 2020-03-09 at 2 14 04 PM" src="https://user-images.githubusercontent.com/43759233/76258211-644d2e80-6210-11ea-838f-a3702aba85bf.png">

Refreshing the page appends "#/connect" to the URL and the Flutter web app loads as expected. Profile build of DevTools works fine.

**Comment by jacob314** [comment]
Did we regress or is this an upstream Flutter issue?

**Comment by kenzieschmoll** [comment]
I tried to bisect and went all the way back to https://github.com/flutter/devtools/pull/1631 (where I know the Flutter Web app was working because I was launching it to test the import / export feature), and I'm still seeing the issue.

Perhaps this is an upstream issue or related to some chrome caching related bug?

**Comment by jacob314** [comment]
Ideas:
1. Can you reproduce if you clear your cache completely before reloading the package?
2. If that doesn't fix it, can you reproduce if you use flutter from a week ago?

**Comment by kenzieschmoll** [comment]
Cleared chrome cache and still seeing the issue. `flutter clean` also did nothing. Are you able to reproduce, Jacob? 

3edd3eb4a2e17186558f930a0885fc8a6d32256c is the latest commit of flutter I can checkout and run DevTools because of dependency issues. In order to go back further, we'd have to pin devtools to an older version of the vm service. The issue still happens there except it looks a little different:
![Screen Shot 2020-03-11 at 10 37 04 AM](https://user-images.githubusercontent.com/43759233/76446478-5b7d6980-6384-11ea-9ad9-10abf7de15b0.png)

Refreshing the page still works around the issue.

**Comment by kenzieschmoll** [comment]
This seems to be working again - no longer can reproduce.
