### ISSUE TITLE
Re-enable testing on windows bots

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#1715]
We should re-enable testing on windows bots; they were disabled to work around a (likely) regression in the travis CI (and they'd been FYI for failures in any case).

Context:
- https://github.com/flutter/devtools/pull/1714
- https://travis-ci.org/flutter/devtools/builds/660771129?utm_source=github_status&utm_medium=notification

**Comment by kenzieschmoll** [comment]
closing as obsolete since we no longer use travis.
