### ISSUE TITLE
when the application is paused at a breakpoint, we should clearly indicate this globally in the UI

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#172]
When the application is paused at a breakpoint (or at an exception, or while stepping), we should clearly indicate this globally in the UI. Otherwise user's may interact with the app under debug and not be aware of why the UI is not responding.

Some options for indicating the paused state are a full width stripe across the top of the app, and / or a  badge on the title of the 'Debugger' tab.

**Comment by devoncarew** [comment]
Or, when execution is paused, automatically switch to the debugger page if we're not already on it.

**Comment by devoncarew** [comment]
To implement this, we'd want to hoist some of the logic to watch pause events out of the debugger.dart file, and into a non-page specific part of the app .

**Comment by kenzieschmoll** [comment]
![Screenshot 2024-10-17 at 1 47 33 PM](https://github.com/user-attachments/assets/e11547f1-b328-4e0b-8e2c-b522204884b1)
