### ISSUE TITLE
Memory live graph UX feedback

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#1724]
Clicking pause has no impact.
The default zoom also appears a bit to zoomed in as the content scrolls by very quickly even when actual memory usage is unchanged.
We should also avoid updating unless Flutter renders a frame.

**Comment by kenzieschmoll** [comment]
Renaming and re-triaging this issue as the bug "Clicking pause has no impact" has been resolved, but the other UX feedback is still relevant.

**Comment by jacob314** [comment]
Fixed with change to a custom graph for the memory page.
