### ISSUE TITLE
P1: Badge tabs with red dot / count for errors

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#173]
When the logging page is not active, and we receive framework error messages, we should badge the 'Logging' page with the number of framework error messages received. This will indicate to the user that there are messages in the logging view that they may want to see. When the logging view next becomes active, the badge count on that page can be cleared out.

<img width="67" alt="screen shot 2019-01-26 at 6 04 49 pm" src="https://user-images.githubusercontent.com/1269969/51795257-13f24900-2195-11e9-8016-f35349b3a8cc.png">

<img width="144" alt="screen shot 2019-01-26 at 6 05 33 pm" src="https://user-images.githubusercontent.com/1269969/51795258-18b6fd00-2195-11e9-910a-0866a34b5004.png">

**Comment by kenzieschmoll** [comment]
Modifying this issue to track all cases where we should be badging tabs with errors:
e.g. overflow errors in inspector tab, log exceptions, etc

we should also support more detailed badging within these views (i.e. badge the specific row in the inspector that has the error, badge the specific log entries with exceptions/errors)

**Comment by kenzieschmoll** [comment]
Copying from the Dart DevTools 2.0 PRD:

> When running DevTools, if there is an error on any of the tabs, e.g. an exception in the log or a failed network operation or a layout error, provide a red dot in the appropriate tabs. When the user clicks on a tab w/ an error on it, show a red dot on the appropriate element on that tab, e.g. the log entry with the error, the widget w/ the layout error, the failed network communication, etc.

**Comment by kenzieschmoll** [comment]
Badging the memory tab for leaks is dependent upon us being able to definitively detect a leak (see https://github.com/flutter/devtools/issues/1437). Added a comment to that issue to note that we should badge the memory tab when we have the proper signal.

This issue can be closed out once the performance tab badging CL lands.
