### ISSUE TITLE
Devtools page in lib model write by flutter, can't select and copy text

### ISSUE THREAD

**Issue by yk3372** [flutter/devtools#1753]
For example：
lab:
![image](https://user-images.githubusercontent.com/1514899/77131006-fa951600-6a94-11ea-978a-21948f9dc959.png)
before:
![image](https://user-images.githubusercontent.com/1514899/77131030-0e407c80-6a95-11ea-90a9-7364cb75c3ec.png)

I'm often use this log details to get JSON strings for parsing classes. However, the left and right entries in lab cannot be selected and copy. 
Whether to consider using Selectable instead of Text, or other better methods, thanks

**Comment by jacob314** [comment]
In addition to using Selectable we might want to add a "copy " link in the top right corner of the detail page to make copying all the json quicker and easier.

**Comment by jacob314** [comment]
Fyi @ditman

**Comment by ditman** [comment]
I think I need to enable the structured output, I was looking only at the console in the Debugger screen.

**Comment by ditman** [comment]
I've just added the "Copy to clipboard" feature to the stdio console in the "Debugger" panel. I'll have a PR for the "Logging" panel next tuesday, most likely.

**Comment by shashikantdurge** [comment]
Not able to select copy/paste anything.

**Comment by kenzieschmoll** [comment]
This functionality won't be available until the next release

**Comment by bryanhinkson** [comment]
Being able to select/copy text would also be really nice in the network tab.  There are times when hitting an API that I want to get the response and format it to make it easier to see if the data I am expecting is there.

**Comment by ditman** [comment]
@bryanhinkson Please, can you create a new issue with the feature request? I think more people of the team would see it if you create a new issue, than if you update an issue that was closed almost a year ago. Thanks!
