### ISSUE TITLE
App bar action button padding needs to be adjusted when hot restart / reload are not available.

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1756]
In this screenshot, I am connected to a Dart VM app. The padding should be adjusted since hot restart and hot reload are unavailable

This applies for Profile builds of flutter apps also.

![Screen Shot 2020-03-20 at 10 27 28 AM](https://user-images.githubusercontent.com/43759233/77189967-a5a5cf80-6a95-11ea-9fb0-cb34b85acade.png)

**Comment by haliliceylan** [comment]
Hi @kenzieschmoll  how can i reproduce this error ?
