### ISSUE TITLE
Support arrow key traversal in Tree Tables

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1769]
This is implemented in the dart:html app. We likely need to add a "selected" state to the tree table items so that we have a modifiable starting point of traversal.

**Comment by kenzieschmoll** [comment]
Seeing a couple of strange behaviors with the tree table row selection / key navigation:

Dual selection - there are two highlighted rows (in different colors albeit) as I use the down arrow to traverse down the table.
![tree_table_dual_selection](https://user-images.githubusercontent.com/43759233/79398633-fc3be780-7f35-11ea-9181-8c1cd7fd77ef.gif)

Table scrolls when it doesn't need to - the selected row should change but the list does not need to scroll until the newly selected index is out of view
![tree_table_selection_staying](https://user-images.githubusercontent.com/43759233/79398721-2ab9c280-7f36-11ea-9aff-39c69f0b51bd.gif)

**Comment by gmoothart** [comment]
These both happen in the macos build of devtools, but not in the web version. You also sometimes get weird behavior where if you arrow-down past the end of the list it starts cycling the top-level tabs.

I didn't try other targets but my assumption is that something is weird with the macos implementation. I looked through the widget hierarchy and couldn't find anything else that was explicitly handling the keystrokes.

**Comment by gmoothart** [comment]
I reported this as a bug to flutter, we'll see if that leads to any resolution.

**Comment by gmoothart** [comment]
FYI the dual selection and arrow-key issue mentioned above is fixed now running against the latest flutter.
