### ISSUE TITLE
timeline_controller_test is failing on master

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1778]
Example run: https://travis-ci.org/github/flutter/devtools/jobs/669444314?utm_medium=notification&utm_source=github_status

`await env.setupEnvironment();` is not completing, which is called at the beginning of each test.  We get stuck in connected_app.dart at the line 
`await serviceManager.serviceExtensionManager.extensionStatesUpdated.future;`

`extensionStatesUpdated` is never completed from service_manager.dart.

**Comment by devoncarew** [comment]
I think it's not getting a frame event?

When I looked at this a few days ago, stepping through it in the debugger meant that we didn't hit the race condition. I then tried adding print statements to diagnose but didn't complete the task.

We could try bisecting the failure to see if there's a specific PR where this was introduced?
