### ISSUE TITLE
Move to the new RTI

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1789]
To fix #1610, we had to turn off Dart's new RTI implementation in our release builds.

Our dependency, plotly.js, uses a recursive walk of both object symbols and object.keys as part of the drawing process.

The old RTI is deprecated and will be deleted soon.

CC @rakudrama

The JS code we're running into this difficulty interopping with is detailed at this comment: 
https://github.com/flutter/devtools/issues/1610#issuecomment-588028260

**Comment by rakudrama** [comment]
The code uses `Object.keys`.
```
   ...
   var keys = Object.keys(container);
   ...
```
Can we verify that `Object.keys` has the original value?
It should print in the console as
   `function keys() { [native code] }`
or
   _f keys() { [native code] }_

**Comment by rakudrama** [comment]
I have two working hypotheses:
- `Object.keys` is overwritten or somehow behaving differently
- The initial value passed to plotly.js is a Dart object, or contains a Dart object other than an Array.
What is the value passed in just before the recursion?

**Comment by DaveShuckerow** [comment]
From a pair debugging session, it looks like we're passing Null instead of null (the Null type instead of the absence of an object) to Plotly.  This is fixable with a 4-line change on our end.

**Comment by jacob314** [comment]
Looks like this was fixed by https://github.com/flutter/devtools/pull/1791/files but not closed.
