### ISSUE TITLE
Show the debugger in DevTools when launching from VS Code

### ISSUE THREAD

**Issue by cfanatic** [flutter/devtools#1792]
## Steps to Reproduce

I am running the following setup which is generally working fine:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.10-pre.1, on Mac OS X 10.15.4 19E266, locale en-DE)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] VS Code (version 1.43.2)
```
Whenever I want to debug my app on the iOS simulator or device, I select `Dart: Open DevTools` in vscode.

But for some reason, the Debugger tab is deactivated in Chrome as you can tell from the screenshot:

<img width="1331" alt="Screenshot 2020-04-05 at 12 21 06" src="https://user-images.githubusercontent.com/44242607/78472453-28d35080-7739-11ea-9a9e-95f8883b91bb.png">

Is there any way to enable debugging inside Chrome DevTools by default? Stripping away `hide=debugger` from the URL serves the purpose, but I prefer to avoid this doing manually.

Thanks!

**Comment by kenzieschmoll** [comment]
Going through some old issues - @DanTup do we still add the `hide=debugger` query param when opening devtools from VS Code, and if so, do we still want to be doing this?

**Comment by bkonyi** [comment]
Are you talking about the [client synchronization support](https://github.com/dart-lang/sdk/blob/master/pkg/dds/dds_protocol.md#requirepermissiontoresume) that was added awhile back?

**Comment by bkonyi** [comment]
Nope, this basically just prevents another client from resuming underneath you while trying to reset breakpoints. The best way to handle this right now is probably to track which breakpoints your client has set and only reset them after a reload, leaving the other clients responsible for their own breakpoints.

**Comment by DanTup** [comment]
Ah, got it. I'll look at adding this to the new SDK DAP (I don't think it makes sense to add to the old one we'll soon migrate away from). I think we'll need to ship it both there and in DevTools before we can safely enable the debugger tab (which might take a little while for VS Code, I suspect the switch over to SDK DAPs will probably start quite slowly - and there still a few small things to complete before that can start).

**Comment by jacob314** [comment]
+1 to leveraging the https://github.com/dart-lang/sdk/blob/master/pkg/dds/dds_protocol.md#requirepermissiontoresume API. Only leveraging it in the DAP is fine. We'll need to also use the API in DevTools and verify that DevTools only reapplies its breakpoints and not al breakpoints.

**Comment by DanTup** [comment]
The VS Code debug adapters now use `requirePermissionToResume` and the upcoming version of the Dart-Code extension no longer explicitly hides the debugger when launching DevTools.
