### ISSUE TITLE
Scripts not showing on debugger

### ISSUE THREAD

**Issue by rafante** [flutter/devtools#1797]
Hi, I have this problem when running flutter dev tools on a flutter web app. If i run the app from vscode in debug mode, I can't open up the "Debugger" tab because it says that vscode can provide me with debugging, and if I just run with flutter run -d chrome, and then paste the debug service url onto the flutter dev tools it connects successfully and shows up the debugger tab, but when I click on a script it shows nothing on the right side just a blank space like if the file was empty. If I click on "Pause" it really pauses my app, and because of that I know that it's connected to the app, but shows no script contents (only the scripts names) and therefore I can't set breakpoints

![Screen Shot 2020-04-07 at 18 57 18](https://user-images.githubusercontent.com/4541914/78723326-9df18200-7901-11ea-8363-b89e7f60b8b0.png)

![Screen Shot 2020-04-07 at 18 58 23](https://user-images.githubusercontent.com/4541914/78723421-c4172200-7901-11ea-9780-5c8ab62230ba.png)

Here's my flutter doctor -v
[✓] Flutter (Channel unknown, v1.15.5, on Mac OS X 10.15.2 19C57, locale en-BR)
    • Flutter version 1.15.5 at /Users/brunorafante/flutter
    • Framework revision cbbb7ec5a7 (5 weeks ago), 2020-03-04 12:40:15 -0800
    • Engine revision 90bd6f8148
    • Dart version 2.8.0 (build 2.8.0-dev.11.0 5701c4fd3b)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/brunorafante/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/brunorafante/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/brunorafante/Library/Android/sdk/ndk-bundle
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.163
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.

**Comment by kenzieschmoll** [comment]
Closing as obsolete.
