### ISSUE TITLE
Flutter app immediately terminates when connecting DevTools

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#1814]
I don't know if this is affecting others or just me, but it's reliably reproducible for me. I'm using a recent Flutter master:

```
danny@Dannys-MBP hello_world % flutter --version
Flutter 1.18.0-5.0.pre.100 • channel master • git@github.com:DanTup/flutter.git
Framework • revision fe41c9726a (5 hours ago) • 2020-04-13 06:45:02 -0400
Engine • revision 521c1d4431
Tools • Dart 2.8.0 (build 2.8.0-dev.20.0 c9710e5059)
```

I'm running the hello_world app from the Flutter repo from the terminal (running on the iPhone 11 Simulator on macOS Catalina):

```
cd examples/hello_world && flutter run
```

Then I'm running the latest published version of DevTools:

```
pub global activate devtools && pub global run devtools
```

When I paste the VM service URL from Flutter into DevTools and click Connect, it immediately terminates the `flutter run` process:

```
An Observatory debugger and profiler on iPhone 11 Pro Max is available at: http://127.0.0.1:51337/Jq83Ne6Pqsk=/
Lost connection to device. // <-- This happens as soon as I clicked Connect in DevTools
```

(though the app remains visible on the Simulator screen)

**Comment by duncanmak** [comment]
I'm on Mojave and my project targets the desktop (macOS) and I seem to be experiencing the same thing.

**Comment by duncanmak** [comment]
I tried a few earlier tags and saw that things were working as late as `1.18.0-dev.4.0`.

The regression happened sometime after dev.4.0 to dev.5.0. It's working as late as flutter/flutter@4851888864348524b4065e18cd6e2597f906fd8d.

**Comment by DanTup** [comment]
@devoncarew is this known? I'm not sure if it's DevTools or a Flutter/VM issue.

**Comment by DanTup** [comment]
This appears fixed to me in latest master - might have been related to some VM Service refactor work in Flutter (https://github.com/flutter/flutter/issues/52179) mentioned in the change linked above.

If anyone still sees this on latest, shout back and I'll re-open this.
