### ISSUE TITLE
have a way to filter the scripts shown in the 'Scripts' panel in the debugger

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#184]
We show the scripts in use by the apps in the 'Scripts' panel in a flat list. Apps generally have between 250-800 scripts; this is too many to navigate well in the available space. We should make navigation easier here, perhaps by adding a filter text field in the title area of the Scripts panel.

**Comment by kenzieschmoll** [comment]
This is resolved. The Libraries panel (formerly Scripts) has a search box to filter. A file can also be opened via `ctrl + o`
