### ISSUE TITLE
P1: Visualize box constraints from render objects in Layout Explorer

### ISSUE THREAD

**Issue by InMatrix** [flutter/devtools#1883]
Layout Explorer currently only visualizes layout information for FlexBox-based widgets such as Row or Column. It would be useful to visualize the box constraints data for other types of widgets through their respective render objects. The data is already available as a tree node in the detail view of the widget inspector, but it's hard to find. 

In short, the box constraints visualization should at least communicate these three pieces of data:
* offset
* constraints
* size

In [this example](https://dartpad.dev/28b9cad2a19769ecafe91ecf57016ba5), the Column widget has an offset of (0.0, 56.0), constraints of (0.0<=w<=859.0, 0.0<=h<=687.0), and the size of (360.0, 687.0). As mentioned, this data is available in text from the inspector: 

![image](https://user-images.githubusercontent.com/348942/80433906-2e8e0300-88ad-11ea-8bec-07e9206157bd.png)
 
Visualizing a widget's offset, constraints, and size in the same diagram should make it easier to tell whether the widget was trying to be as large as possible or just large enough to fit its child widget(s). 

Cc: @raison00

**Comment by kenzieschmoll** [comment]
@jacob314 as part of this change, can you please also make the Layout Explorer tab first in the details section?
