### ISSUE TITLE
Clicking anywhere on the Connect dialog attempts to connect

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#1890]
If you load the Connect page then click anywhere on the page, you'll see a message that we failed to connect to a VM (with an empty URI). This seems like it's because the `TextField` uses `onSubmitted` which fires whenever the field loses focus (and it started with focus due to `autofocus`) (see https://github.com/flutter/flutter/issues/49785 and https://github.com/flutter/flutter/issues/54540).

I suspect `onSubmitted` was added to support pressing `<enter>`, but I think it should be done differently given this confusing behaviour.

**Comment by kenzieschmoll** [comment]
Is this issue resolved now, Danny?

**Comment by DanTup** [comment]
It's not - I'm not sure how best to fix. We can (should) remove `onSubmitted`, but it'll mean pressing `<enter>` after pasting a VM ServiCe URL won't work and I'm not sure if there's a good way to handle that (without some solution to #54540).

**Comment by kenzieschmoll** [comment]
I am unable to reproduce this with both the macos and chrome builds. please reopen if this is not actually resolved

**Comment by DanTup** [comment]
Yep, I can't repro either. I'm not sure exactly why, there are no comments on the issues linked above about the behaviour changing - but it seems like `onSubmitted` isn't firing when the field loses focus anymore.
