### ISSUE TITLE
assertion fired in service_manager.dart

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#190]
The assertion at https://github.com/flutter/devtools/blob/master/lib/src/service_manager.dart#L448:

```
  assert(_pendingServiceExtensions.isEmpty);
```

fired while I was using the app. I don't have repro instructions unfortunately. I don't know if this represents a logic issue, or if the assert is too aggressive.

**Comment by kenzieschmoll** [comment]
Maybe we have a race condition between _onFrameEventReceived https://github.com/flutter/devtools/blob/master/packages/devtools/lib/src/service_manager.dart#L389
and _maybeAddServiceExtension https://github.com/flutter/devtools/blob/master/packages/devtools/lib/src/service_manager.dart#L446

If we move `_firstFrameEventReceived = true;` to be after `_pendingServiceExtensions.clear();` in _onFrameEventReceived(), I think that could fix the issue.

**Comment by devoncarew** [comment]
closing as this is likely out of date
