### ISSUE TITLE
have a way in the UI to disconnect to the existing connection

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#1900]
We should have a way in the UI to disconnect to the existing connection.

**Comment by jacob314** [comment]
One other thing to evaluate improving as part of this is how we connect and disconnect from viewing an offline snapshot.

**Comment by kenzieschmoll** [comment]
related https://github.com/flutter/devtools/issues/1092

**Comment by kenzieschmoll** [comment]
![Screen Shot 2021-01-20 at 5 09 57 PM](https://user-images.githubusercontent.com/43759233/105260475-b6562480-5b42-11eb-99b8-35fcafd9a267.png)

Selecting "Connect to a new app" disconnects the current application and returns to the connect screen
