### ISSUE TITLE
DevTools Info Page: UX Punch List 2020

### ISSUE THREAD

**Issue by raison00** [flutter/devtools#1957]
## Update Overall UX 
- [x] Update borders
- [ ] Update UX for priority and emphasis
- [ ] Ensure unified layout with other pages
- [ ] Update/Add unified color themes
- - [x] Rows need alternate colors
- - [ ] Update selected color from gray  to `#36c6f4`

## VM Flag List
- [ ] Add two lines per entry
- [ ] Add description on separate line
- [x] Include column headers 
- [x] Add Label value to column
- [x] Add Search / Filter for flags
- [ ] Add Value / Percentages for flags

##  Open Questions
- [x] Move content/ consolidate to an observatory specific page?

#### Current ( DevTools 0.2.5 Info Page)
![image](https://user-images.githubusercontent.com/8105802/81869365-c84de500-9528-11ea-84e6-aee9997d3bc3.png)
![image](https://user-images.githubusercontent.com/8105802/81869409-db60b500-9528-11ea-82fb-830b91d7c837.png)

:sparkles:

**Comment by devoncarew** [comment]
I believe that many of the items here will be addressed by https://github.com/flutter/devtools/pull/2027; that will:
- remove the info page
- add a 'device info' dialog, openable by clicking on the device name on the status line
- make the device name on the status line more clearly actionable
- have the vm flags info available from the device dialog, opening in a subsidiary dialog
- convert the flags presentation to use our std table, which should address several of the ux items raised here

**Comment by devoncarew** [comment]
Here's the current state of affairs:

<img width="205" alt="Screen Shot 2020-06-02 at 1 33 06 PM" src="https://user-images.githubusercontent.com/1269969/83567029-cc40a780-a4d5-11ea-9a7a-e5733fbb5bc2.png">

<img width="421" alt="Screen Shot 2020-06-02 at 1 33 17 PM" src="https://user-images.githubusercontent.com/1269969/83567046-d2cf1f00-a4d5-11ea-8d71-7095cc40da2b.png">

<img width="948" alt="Screen Shot 2020-06-02 at 1 33 27 PM" src="https://user-images.githubusercontent.com/1269969/83567055-d82c6980-a4d5-11ea-8b49-ca56d3bf9cba.png">

<img width="943" alt="Screen Shot 2020-06-02 at 1 33 43 PM" src="https://user-images.githubusercontent.com/1269969/83567069-debae100-a4d5-11ea-8b9c-22464675c9c6.png">

**Comment by devoncarew** [comment]
Closing this as the page has been removed, the content incorporated into dialogs, and I believe the issues that are still relevant addressed in converting the list of flags to use our std table component.
