### ISSUE TITLE
DevTools Network Page: UX Punch List 2020

### ISSUE THREAD

**Issue by raison00** [flutter/devtools#1980]
##
## Fix Known Issue(s):
- [ ] Fix Colors
- [ ] Fix Timing 
- [ ] Fix Scroll & Zoom
##
## Update Overall UX 
- [x] Update Table to match DevTools Standard tables
- [x] (P3) Display timing as mini-flamechart
- [x] (P3) Visualize timestamps:  currently Timing tab is forcing users to do math
- [x] Make table colors accessible and match DevTools pages
- [x] Ensure horizontal scrolling consistency
- [x] Update with unified light theme - many issues
- - [x] white text on white background for tab controller
- - [x] status colors lack contrast
- [x] Disable tab controller horizontal scrolling
- [x] Update Timestamps for relevancy
- - [x] Remove year
- - [x] remove any redundant info
- [x] Distinguish Network Tabs
- - [x] Network: Tracking Network Data
- - [x] Network: Log Network Traffic Update

#### Current ( DevTools 0.2.5 Network Page)
![image](https://user-images.githubusercontent.com/8105802/82237712-f2b5ee80-98ea-11ea-9f1e-e235024ce746.png)

![image](https://user-images.githubusercontent.com/8105802/82237727-fb0e2980-98ea-11ea-9635-9c02e1d4cdb2.png)

![image](https://user-images.githubusercontent.com/8105802/82237752-06615500-98eb-11ea-963d-6bdea703ab43.png)

**Comment by devoncarew** [comment]
Here's the current UI - updated to use our standard devtools table:

<img width="1460" alt="Screen Shot 2020-05-24 at 11 43 46 AM" src="https://user-images.githubusercontent.com/1269969/83567225-204b8c00-a4d6-11ea-9d71-0d1b9ef461c1.png">
