### ISSUE TITLE
DevTools Logging Page: UX Punch List 2020

### ISSUE THREAD

**Issue by raison00** [flutter/devtools#1982]
##
## Update Overall UX 
- [x] Add header for 'details' section
 - [x] Use consistent borders matching other DevTools pages
- [x] Create consistent search / filter bindings matching other DevTools pages
- [x] Use DevTools standard table
 - [x] ~Unify Search & Filter Expectations~ 
 - [x] **Update/Add unified color themes**
 - - [x] Rows need alternate colors 
 - - [x] Distinguish color on hover `#36c6f4`

#### Current ( DevTools 0.2.5 Logging Page)
![image](https://user-images.githubusercontent.com/8105802/82244228-c3f14580-98f5-11ea-9e8d-ea6ed782f11e.png)

![image](https://user-images.githubusercontent.com/8105802/82244084-8096d700-98f5-11ea-9afd-e79b6198b64b.png)

:sparkles:

**Comment by devoncarew** [comment]
@raison00, are 'Create consistent search / filter bindings matching other DevTools pages' and  'Unify Search & Filter Expectations' the same item?

And, wrt the 'Search' and 'Filter' nomenclature, have you thought about what to name these fields? I believe we have a search/filter text filed in the device info dialog, the logging page, the debugger scripts view, and the memory snapshot view. We'll likely get search boxes in the timeline page and possibly the inspector page.

Here are some thoughts, but please add your own:
- we call the field 'Filter' when it is reducing the number of items shown
- where space is available, when the filter is non-empty, we should text near it indicating the number of matches (`showing 7 or 423 items`)
- where the field is matching items but not hiding any from display, we call the field 'Search'
- we might consider (where space permits), indicate the number of matches ('4 matches', or if we can toggle through the selections, '2 of 4 matches')

**Comment by raison00** [comment]
We're on the same page;  I have been looking at the holistic approach and familiar conventions.
I will update/expand/etc the various pages/requirements.  

To parse it down:
**Filtering** takes an existing full list and removes items based on criteria that matches/doesn't match.

**Search** takes a blank slate and adds to it based on criteria that matches/doesn't match.

**Comment by devoncarew** [comment]
> **Search** takes a blank slate and adds to it based on criteria that matches/doesn't match.

Yes, or possibly, advances through the matches in the content being searched.

**Comment by raison00** [comment]
The Punch List has been updated for Filter / Search for DevTools.  The outlier is the Memory Profiler, and will be addressed separately.

My research and resources on patterns, practices, ux pitfalls of  Filter / Search  are compiled [here](https://github.com/raison00/Design-Resources#search-sort-filter-and-findability).

**Comment by devoncarew** [comment]
@raison00 - thanks for the guidance!

Wrt the table selection color (above, mentioned as the hover color), I tried this locally, and we may need more contrast. Here is what it looks like with our light and dark themes:

<img width="367" alt="Screen Shot 2020-06-12 at 11 19 37 AM" src="https://user-images.githubusercontent.com/1269969/84534850-89ce5600-ac9f-11ea-85a8-13b24e42a1c4.png">

<img width="379" alt="Screen Shot 2020-06-12 at 11 19 48 AM" src="https://user-images.githubusercontent.com/1269969/84534894-9488eb00-ac9f-11ea-8153-7c4a9876c631.png">

Note that we can adjust the foreground color as well (in order to help with contrast).

**Comment by raison00** [comment]
@devoncarew here's an update to visualize changing the font color to black for both light/dark themes when the the item is selected.  [AA] + [A] are my suggestions.  

As illustrated:
[AA]: Remove the highlighted bar and change the font color to `#36c6f4`
[A]: Update font color on select to `#000000` for both light/dark themes. 
[B]: Update on Select: font : bold and font color: `#000000` for both light/dark themes
[C] Update font color on select to `#FFFFFF` for both light/dark themes. 
[D, E]: Current/Previous colors without  `#36c6f4` background

![selection-call-stack-dark-light](https://user-images.githubusercontent.com/8105802/84543527-6069f600-acb0-11ea-8352-f686b93abe36.png)

**Comment by devoncarew** [comment]
I guess I like A and C. I have some changes for this on disk, and they'll make it a bit easier to tweak the colors and style for table foreground and background in the future.

**Comment by kenzieschmoll** [comment]
A is my favorite
