### ISSUE TITLE
The snapshot of Memroy Page dose not showing as same as the official docs

### ISSUE THREAD

**Issue by g52302010** [flutter/devtools#2032]
My app has lots of images but snapshot never show them. Also snapshot dose not show any of my own class category. Am i using it wrong way? 
My:
![图片](https://user-images.githubusercontent.com/15604031/83622680-e4422500-a5c2-11ea-9dfb-1b216739093c.png)
Oficial:
![图片](https://user-images.githubusercontent.com/15604031/83623337-c9bc7b80-a5c3-11ea-84bc-db0b55ecdad3.png)

And Timeline also dose not showing dart method invoke info, it shows many c++ method invoke info. 
![图片](https://user-images.githubusercontent.com/15604031/83624359-181e4a00-a5c5-11ea-88d4-926c7a08463f.png)

**Comment by helin24** [comment]
You're not mistaken, this is something we are actively working on and will be appearing soon.
