### ISSUE TITLE
Find source file once widget in inspector is selected

### ISSUE THREAD

**Issue by xster** [flutter/devtools#2046]
I'm fairly sure we implemented this feature but I can't seem to find how it works. 

<img width="2345" alt="Screen Shot 2020-06-05 at 12 34 59 PM" src="https://user-images.githubusercontent.com/156888/83915994-3dc46400-a729-11ea-9b6a-f067dd4e267c.png">

Now that I have a node selected, how do I find which of my own source files constructed the widget?

**Comment by devoncarew** [comment]
cc @jacob314

**Comment by kenzieschmoll** [comment]
Selecting a widget automatically jumps to the widget creation location in the IDE.
