### ISSUE TITLE
Add new a debug feature/tool.

### ISSUE THREAD

**Issue by rainwashed** [flutter/devtools#2070]
ClipPath is very similar to the css property of clip-path, in Firefox when the clip-path is on an object, you can go to the developer tools and are able to move the points of the path and it will update automatically, I hope to see this to the Flutter debug tools as it's way easier to see the points then just seeing the numbers.

**Comment by kenzieschmoll** [comment]
Closing as not planned. We are actively working on a Flutter property editor experience which may help with this use case, although it will not be a GUI editor for clip paths.
