### ISSUE TITLE
DevTools indefinitely loading

### ISSUE THREAD

**Issue by katisari** [flutter/devtools#2075]
@filiph 
I opened devtools (version 0.2.5) to debug layout errors, and it was indefinitely loading with the following error messages:

![image](https://user-images.githubusercontent.com/39178730/84426621-87adbe00-abf1-11ea-840d-d7cfa6af7dff.png)

To replicate the error, replace the contents of main.dart with the following:

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
 @override
 Widget build(BuildContext context) {
   return MaterialApp(
     home: Scaffold(
       appBar: AppBar(
         title: Text('Example of the “renderbox was not laid out” error'),
       ),
       body: Center(
         child: Column(
           children: <Widget>[
             ListView(
               children: <Widget>[
                 ListTile(
                   leading: Icon(Icons.map),
                   title: Text('Map'),
                 ),
               ],
             ),
           ],
         ),
       ),
     ),
   );
 }
}
```

**Comment by filiph** [comment]
cc @kenzieschmoll - I was able to reproduce this.

**Comment by kenzieschmoll** [comment]
Try stripping the URL down to 127.0.0.1:52030/ and refreshing. If that doesn't work, you can try the dev release by running `pub global activate devtools 0.2.6-dev.1; devtools`

**Comment by katisari** [comment]
It's still saying devtools is loading after trying both of those options

**Comment by kenzieschmoll** [comment]
running `pub global activate devtools 0.2.6-dev.1; devtools` should have launched a different version of DevTools. You'll need to do this from the command line, and then manually copy and paste the VM service URI (which is the URI in the console output after running `flutter run`) into the connect dialog of DevTools

**Comment by kenzieschmoll** [comment]
This bug is for the old html version of DevTools - closing.
