### ISSUE TITLE
Dev tools unable to connect to VM service

### ISSUE THREAD

**Issue by AlraziBashir** [flutter/devtools#2076]
![Screen Shot 2020-06-11 at 4 49 46 PM](https://user-images.githubusercontent.com/53784936/84437837-a2892e00-ac03-11ea-9df1-8b5bf15e7e3b.png)
I am having a very difficult time launching my Flutter Web App in local debugger (chrome/Web). I have updated Flutter/Dart, switch multiple Flutter Channels + upgraded each time. I cannot figure what the issue is, any help is appreciated. Thanks
![Screen Shot 2020-06-11 at 4 41 55 PM](https://user-images.githubusercontent.com/53784936/84437389-e3cd0e00-ac02-11ea-85f8-0eeab17f282d.png)
![Screen Shot 2020-06-11 at 12 24 42 PM](https://user-images.githubusercontent.com/53784936/84437403-e891c200-ac02-11ea-8814-2d1c5d7c213f.png)
![Screen Shot 2020-06-11 at 12 24 14 PM](https://user-images.githubusercontent.com/53784936/84437407-eb8cb280-ac02-11ea-8c6d-93d1f5c438a9.png)

![Screen Shot 2020-06-11 at 4 54 32 PM](https://user-images.githubusercontent.com/53784936/84438281-483c9d00-ac04-11ea-98a6-5cb4137c8be3.png)

**Comment by kenzieschmoll** [comment]
Are you still unable to connect when you use the dev version of DevTools? `flutter pub global activate devtools 0.2.6-dev.1; devtools`

**Comment by AlraziBashir** [comment]
I was unable to have any success with that after running that command in the terminal.
![Screen Shot 2020-06-11 at 4 57 54 PM](https://user-images.githubusercontent.com/53784936/84438630-dca6ff80-ac04-11ea-8ec1-aaede2324cf9.png)

**Comment by kenzieschmoll** [comment]
you need to put `export PATH="$PATH":"$HOME/Desktop/dev/flutter/.pub-cache/bin"` in your `.bashrc` (linux) or `.bash_profile` (mac). If you use z shell, put it in your `.zshrc` file.

You can edit these with the editor of your choice. If you use VS code, you can open the file from terminal via `code ~/.bash_profile` and add that line to modify your path.

**Comment by AlraziBashir** [comment]
I am currently on the master branch (Flutter: 1.20.0-1.0.pre.25), if that helps.

**Comment by AlraziBashir** [comment]
I have updated path without success. web app fails to load.

![Screen Shot 2020-06-11 at 5 32 27 PM](https://user-images.githubusercontent.com/53784936/84441306-8ee0c600-ac09-11ea-8def-e2fb0aedc738.png)

**Comment by devoncarew** [comment]
I would try:

```
flutter pub global activate devtools 0.2.6-dev.1
```

and

```
flutter pub global run devtools
```

Which will avoid the PATH issue.

**Comment by kenzieschmoll** [comment]
You need to make the path you added point to your Flutter. In the error message you pasted, it looks like yours should be
export PATH="$PATH":"$HOME/desktop/tools/flutter/.pub-cache/bin"

**Comment by AlraziBashir** [comment]
I have updated the path to point to my Flutter, restarted VS code with the same issues

![Screen Shot 2020-06-11 at 5 45 06 PM](https://user-images.githubusercontent.com/53784936/84442276-4cb88400-ac0b-11ea-89f0-7cf9d9b1c32e.png)
![Screen Shot 2020-06-11 at 5 46 59 PM](https://user-images.githubusercontent.com/53784936/84442401-8f7a5c00-ac0b-11ea-8225-d97ca976c1bc.png)

**Comment by AlraziBashir** [comment]
![Screen Shot 2020-06-11 at 5 49 54 PM](https://user-images.githubusercontent.com/53784936/84442616-fac42e00-ac0b-11ea-8ab1-c9b899de62b6.png)

**Comment by AlraziBashir** [comment]
@devoncarew I am getting the following after running both.


![Screen Shot 2020-06-11 at 5 51 46 PM](https://user-images.githubusercontent.com/53784936/84442753-3959e880-ac0c-11ea-8a1a-7e6f2d005c32.png)

**Comment by kenzieschmoll** [comment]
You will need to launch DevTools from command line in order to see the version you activated from pub. That is saying that port 9100 is in use. Run `flutter pub global run devtools -p 9101` to try it on port 9101

**Comment by AlraziBashir** [comment]
![Screen Shot 2020-06-11 at 5 58 41 PM](https://user-images.githubusercontent.com/53784936/84443234-301d4b80-ac0d-11ea-8467-ca7696ffd67d.png)

**Comment by kenzieschmoll** [comment]
To fix the PATH error, you may need to run `source ~/.bash_profile` to ensure the terminal us using the latest updated copy of `.bash_profile`

**Comment by kenzieschmoll** [comment]
Great. Now go to `localhost:9101` in your browser to open DevTools

**Comment by AlraziBashir** [comment]
![Screen Shot 2020-06-11 at 6 01 33 PM](https://user-images.githubusercontent.com/53784936/84443434-97d39680-ac0d-11ea-9ead-c0addfd6e02f.png)

**Comment by kenzieschmoll** [comment]
When you run your app via `flutter run`, a URI will be printed to the console. Copy and paste that URI into this connect dialog.

**Comment by AlraziBashir** [comment]
![Screen Shot 2020-06-11 at 6 06 44 PM](https://user-images.githubusercontent.com/53784936/84443778-55f72000-ac0e-11ea-9a0c-9ec39d8f6eba.png)

**Comment by AlraziBashir** [comment]
Debug console

![Screen Shot 2020-06-11 at 6 07 18 PM](https://user-images.githubusercontent.com/53784936/84443812-64453c00-ac0e-11ea-8487-b938efe3c35e.png)

**Comment by kenzieschmoll** [comment]
copy and paste starting at `ws`

**Comment by AlraziBashir** [comment]
looks like I was able to launch the app multiple times using the command flutter run -d chrome. The issue seems to be when utilizing the start debugger button to launch chrome debugger which fails to completely load the app. This has only started to occur with the latest upgrade from Flutter 1.17=>1.20 

![Screen Shot 2020-06-11 at 6 14 06 PM](https://user-images.githubusercontent.com/53784936/84444362-97d49600-ac0f-11ea-8f46-2099cb1414bd.png)

**Comment by AlraziBashir** [comment]
Thanks for your help
