### ISSUE TITLE
'flutter run --start-paused' hangs waiting for _connectedToProfileBuild

### ISSUE THREAD

**Issue by terrylucas** [flutter/devtools#2082]
hangs waiting for

    await serviceManager.serviceExtensionManager.extensionStatesUpdated.future;

Temporary work around if eval works we're not profile otherwise we're a profile build.  Review _connectedToProfileBuild method.

**Comment by kenzieschmoll** [comment]
@terrylucas can this be closed?

**Comment by kenzieschmoll** [comment]
closing as obsolete.
