### ISSUE TITLE
[Question]: A memory benchmark shows surprising numbers. Is this a bug?

### ISSUE THREAD

**Issue by rrousselGit** [flutter/devtools#2083]
Hello!

An open-source memory benchmark of different packages  has been released recently using flutter/devtool: https://github.com/jonataslaw/benchmarks/tree/master

The benchmark claims that there is a difference of up to 50BK of memory between approaches, for an application that only shows 10 items.

50BK seems like a very big number for a list of 10 items, but the flutter/devtool consistently gives these numbers.

Considering the difference in how these apps works is about changing `ChangeNotifier` into `Stream` /etc, I believe the difference should be measured at best in hundreds of bytes, not 0.5mb.

Is there an external factor that could explain such large difference?

This has caused  a lot of confusion in the community in the past few days.

**Comment by kenzieschmoll** [comment]
@terrylucas

**Comment by jonataslaw** [comment]
I'm also interested in this to find out if Get's performance on RAM consumption is real, or devtool benefits it in some way.

**Comment by rrousselGit** [comment]
Any update? :smiley:

**Comment by elliette** [comment]
As https://github.com/jonataslaw/benchmarks/tree/master no longer exists, closing this issue since I don't know how we could compare.
