### ISSUE TITLE
can no longer debug, inspect flutter web apps

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#2096]
It looks like this commit: https://github.com/flutter/devtools/commit/25fca234e0c3719abe2127d8675e057bac21b4ff regressed behavior wrt flutter and dart web apps. The various devtools pages believe that they're in profile mode; we should adjust our detection logic.

Marking as a P1 as I don't believe we can ship with this issue.

**Comment by devoncarew** [comment]
cc @terrylucas

**Comment by terrylucas** [comment]
Sorry and thanks Devon.  I'll change eval check to do a simple eval e.g., 10 + 5 to avoid any assumed library.

**Comment by devoncarew** [comment]
Gotcha, no worries.

I think assuming that web != profile will still be safe however, and will avoid some places where web does not yet support eval.
