### ISSUE TITLE
Timeline is not showing any update from the device

### ISSUE THREAD

**Issue by CareF** [flutter/devtools#2100]
![image](https://user-images.githubusercontent.com/11715538/85061357-b2a98c00-b174-11ea-8e34-106f01e4b9d4.png)

Run the sample code created from `flutter create` on a Pixel4 device with profile mode (`flutter run --profile`), The timeline tab just don't upgrade anything with whatever operation I did on the device. The memory tab is working fine. 

The `flutter doctor` shows: 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.20.0-1.0.pre.91, on Mac OS X 10.15.5 19F101, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (6 available)

• No issues found!
```

Is there anything I can do to debug it?

**Comment by devoncarew** [comment]
I believe there was a regression in the events sent from the Flutter engine, and that the change is being or has been reverted. I see you're on flutter master; can you get the latest and re-try?

Otherwise you may want to switch to something like flutter dev.

**Comment by devoncarew** [comment]
cc @kenzieschmoll

**Comment by CareF** [comment]
> I believe there was a regression in the events sent from the Flutter engine, and that the change is being or has been reverted. I see you're on flutter master; can you get the latest and re-try?
> 
> Otherwise you may want to switch to something like flutter dev.

I can confirm that current master branch still has the problem on my device, so is the dev branch. @devoncarew

**Comment by kenzieschmoll** [comment]
I just upgraded to the latest Flutter and am no longer seeing the issue. Can you try to upgrade one more time and confirm?

**Comment by kenzieschmoll** [comment]
Here is the related issue explaining the regression: https://github.com/flutter/devtools/issues/2091

**Comment by CareF** [comment]
I confirm the issue if solved.
