### ISSUE TITLE
Rendering smaller nodes in Treemap

### ISSUE THREAD

**Issue by peterdjlee** [flutter/devtools#2106]
Currently, all cells are shown in a Treemap regardless of their size. This results in a cluster of tiny cells that are hard to select and make the UI look a bit clunky. 

A possible solution could be having a  `minSizeToDisplay` const where all cells that have sizes less than `minSizeToDisplay` are put in a bigger cell (e.g. a cell named 'Other'). A potential problem with this solution is that the combined cell will now change its position since it's become bigger, and would blend in with other cells.

<img width="1407" alt="Screen Shot 2020-06-22 at 2 27 25 PM" src="https://user-images.githubusercontent.com/22206026/85325722-1942e880-b49a-11ea-9e6d-e83246031eec.png">

**Comment by devoncarew** [comment]
If they're small (smaller than some threshold), you could render then w/o a border. Then they'd just effectively merge into one slightly rectilinear shape, and you could see more details when exploring the section it was in (and it wouldn't change position, which would be a nice benefit).

**Comment by jacob314** [comment]
This has been fixed.
