### ISSUE TITLE
devtools_app flutter pub get

### ISSUE THREAD

**Issue by xiaoxiaowesley** [flutter/devtools#2136]
I am using master branch and follow the [this](https://github.com/flutter/devtools/blob/master/CONTRIBUTING.md)  instruction . but when I enter the packages/devtools_app and use `flutter pub get`，things get worng:

 ` ` `flutter pub get ` ` ` 
` ` ` Because every version of flutter_test from sdk depends on path 1.6.4 and every version of vm_snapshot_analysis depends on path ^1.7.0, flutter_test from sdk is incompatible with vm_snapshot_analysis.
So, because devtools_app depends on both vm_snapshot_analysis ^0.3.0 and flutter_test any from sdk, version solving failed.
Running "flutter pub get" in devtools_app...                            
pub get failed (1; So, because devtools_app depends on both vm_snapshot_analysis ^0.3.0 and flutter_test any from
sdk, version solving failed.)
` ` `

Is master branch has been tested?

Here is my futter version :

Flutter 1.17.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1ad9baa8b9 (11 days ago) • 2020-06-17 14:41:16 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

And Of course the devtools is in master .

**Comment by devoncarew** [comment]
Have you tried using the flutter master / flutter dev channel? We generally develop against master and dev - we're still pretty cutting edge from the POV of the flutter features we're using and bug fixes we want to consume, and can work around flutter master versions with issues.

**Comment by xiaoxiaowesley** [comment]
> Have you tried using the flutter master / flutter dev channel? We generally develop against master and dev - we're still pretty cutting edge from the POV of the flutter features we're using and bug fixes we want to consume, and can work around flutter master versions with issues.

I tried master, can not work.
Here below are all the branches when I use command `git branch -a` and I did not find what you said dev branch.

 remotes/origin/0.8.0
  remotes/origin/HEAD -> origin/master
  remotes/origin/bump_vm_service
  remotes/origin/jacob314-cleanup-publish-instructions
  remotes/origin/master
  remotes/origin/release_0.1.6-dev.3
  remotes/origin/remove_thirdparty_packages
  remotes/origin/retry
  remotes/origin/rev_webkit_inspection_protocol
  remotes/origin/revert_unintended_change
  remotes/origin/story-of-layout-avoid-flutter-framework-change
  remotes/origin/story-of-layout-register-service-extension
  remotes/origin/terrylucas-patch-1
  remotes/origin/treemap
  remotes/origin/use_types_for_api

But I found some tags work mostly fine if I fix some bug.
I checkout to tag v0.2.5 and add the missing override the getSupportedProtocols funtion  in lib/src/vm_service_wrapper.dart

```
@override
  Future<ProtocolList> getSupportedProtocols() async {
    if (await isProtocolVersionSupported(
        supportedVersion: SemanticVersion(major: 3, minor: 35))) {
      return _trackFuture(
        'getSupportedProtocols',
        _vmService.getSupportedProtocols(),
      );
    } else {
      return null;
    }
  }
```
Here is my conclusion:
Master did not work, tag v0.2.5 is find if I fix bug.

**Comment by kenzieschmoll** [comment]
Can you try this?
`flutter upgrade --force` (on the master flutter branch - `flutter channel master`)
from `devtools/packages/devtools_app`: `flutter pub get`
from `devtools/packages/devtools`: `flutter pub get`
from `devtools/packages/devtools_server`: `flutter pub get`
from `devtools/packages/devtools_shared`: `flutter pub get`
from `devtools/packages/devtools_testing`: `flutter pub get`

`flutter clean`

**Comment by kenzieschmoll** [comment]
Closing this as stale. Please re-open or file another issue if you are still experiencing problems.
