### ISSUE TITLE
Devtools is not showing up in Brave Browser.

### ISSUE THREAD

**Issue by divyanshub024** [flutter/devtools#2142]
It looks like it's just showing the white screen in the Brave browser. 
![Screenshot 2020-06-30 at 9 48 09 AM](https://user-images.githubusercontent.com/16731434/86083180-2cb40c00-bab7-11ea-8b7b-db2215558308.png)

**Comment by gauravsbagul** [comment]
Having same isssue

**Comment by devoncarew** [comment]
Are there any exceptions in the debug console?

**Comment by gauravsbagul** [comment]
Actually I was using Brave browser, finally I opened it in chrome and its working there.

**Comment by kenzieschmoll** [comment]
closing as obsolete
