### ISSUE TITLE
DevTools -> CallTree -> Expand/Collapse buttons work identically (gif)

### ISSUE THREAD

**Issue by vasilich6107** [flutter/devtools#2162]
In devtools call tree no matter what button you press (expand or collapse) the call tree collapses in both cases. See the gif animation

Flutter version does not matter
In 1.7.4 and in latest master branch from git it works identicaly
![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/6721286/85923801-d8324600-b896-11ea-9766-9212d2b477e6.gif)

**Comment by devoncarew** [comment]
cc @kenzieschmoll

**Comment by devoncarew** [comment]
I believe the issue here may be that we're not preserving state correctly for the `CpuProfiler` widget (and not that the 'Expand all' button is hooked up to the wrong thing).

**Comment by devoncarew** [comment]
Moving out of M19 as I don't think this will block the release.
