### ISSUE TITLE
[Network Screen] Make value selectable or add a 'copy to clipboard' button. Show full on screen.

### ISSUE THREAD

**Issue by nosmirck** [flutter/devtools#2170]
https://github.com/flutter/devtools/blob/24ee3ac1171b459a36b0293c8d8268c27abdd706/packages/devtools_app/lib/src/network/http_request_inspector_views.dart#L68

This is great, and although it is still not showing the actual response content (as described here: #1952) it would be great if we had the value for the fields able to copy so we can paste them somewhere. A max lines limit is ok for displaying the summary, but to make this tool actually useful there needs to be something to get the full data when it is truncated.

Suggestion: when clicked, the whole view for this part of the inspector can become a a Text with the data, maybe if we also have the content type parsed, we can format the data (json, binary, xml, html, etc...)

Also, are there any instructions on how to setup and debug this project, I've been unable to do so, I'd like to get it up and running so I can contribute :)

**Comment by kenzieschmoll** [comment]
There are instructions here: https://github.com/flutter/devtools/blob/master/CONTRIBUTING.md. We generally develop on the Desktop app since hot reload is supported there.

**Comment by DominicOcean** [comment]
Being able to select and copy text in the Network screen would be great.
