### ISSUE TITLE
Android Studio install failed

### ISSUE THREAD

**Issue by tongyangsheng** [flutter/devtools#2172]
When i try to install devtools on Android Studio, it always show "Installing DevTools" and I have been waiting for a long time.Can someone give me some advice?Thank you very much.
![image](https://user-images.githubusercontent.com/32046282/87125878-ce103e80-c2bd-11ea-97bb-1f0c2de46268.png)

**Comment by devoncarew** [comment]
Depending on where you are, or your internet setup, this could be an issue with a proxy. Behind the scenes we're running `pub global activate devtools`, and then, `pub global run devtools`.

You can perform both steps from the command line (if you don't have dart on your path, and just flutter, you'd want to run `flutter pub global activate devtools`). If they work there, you can connect that running instance of devtools to your application.

**Comment by tongyangsheng** [comment]
@devoncarew Thank you very much, I have installed devtools by command line, I just want to open it in a more convenient way. I will check my internet setup, thanks again.
