### ISSUE TITLE
Flutter Inspector not showing Widget Tree when project is added as a submodule.

### ISSUE THREAD

**Issue by Neelansh-ns** [flutter/devtools#2174]
On opening Flutter Inspector in Android Studio or opening dev tools in Chrome, the widget tree is not shown.
Opening the submodule as a separate project works fine in both.

Flutter doctor output:

[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-IN)
    • Flutter version 1.17.5 at /Users/Neelansh/flutter
    • Framework revision 8af6b2f038 (11 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/Neelansh/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

**Comment by pumuckelo** [comment]
same here

**Comment by kenzieschmoll** [comment]
This is resolved by work that was done to more accurately detect the package root directories for a project.
