### ISSUE TITLE
Can't zoom into diff tree map cells

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#2178]
When the code size diff tree map is loaded, I am unable to drill into a cell. I can verify in the tree table that this cell has children, so clicking the cell should re-root the tree.

![cant_drill_into_diff](https://user-images.githubusercontent.com/43759233/87351587-774d7380-c50e-11ea-97f4-aaf26b7f15b4.gif)

**Comment by peterdjlee** [comment]
Fixed in #2181. Closing issue.
