### ISSUE TITLE
Switching from code size diff tab to snapshot tab does not restore state

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#2179]
Repro steps: 
1. load snapshot into code size page
2. switch to diff tab and load diff files into page
3. switch back to snapshot tab and see that the original snapshot data was not loaded (the cells are red like in the diff tab)

![switch_to_snapshot_from_diff](https://user-images.githubusercontent.com/43759233/87351708-afed4d00-c50e-11ea-86e9-c49c82ab5789.gif)

**Comment by peterdjlee** [comment]
Fixed in #2181
