### ISSUE TITLE
Can't deep link into a specific tab

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#2184]
Before the Flutter Web version, a user could deep link into a specific tab e.g. the Debugger with the use of a URL parameter. There doesn't appear to be equivalent functionality with the latest Flutter Web version.

**Comment by devoncarew** [comment]
@DanTup - I believe you did work for deep linking in the flutter web version?

**Comment by DanTup** [comment]
Not yet - I have a sample working at https://github.com/DanTup/tab_route_test/tree/new-router but it requires some changes in Flutter that haven't all landed yet (https://github.com/flutter/flutter/pull/60299). I did try a few other things (like using pushState) as a short-term fix, but none of them worked properly with Flutter.

**Comment by DanTup** [comment]
(this issue is probably a dupe of https://github.com/flutter/devtools/issues/1725)

**Comment by devoncarew** [comment]
closing as a dup of https://github.com/flutter/devtools/issues/1725
