### ISSUE TITLE
Bring Observatory timeline features into DevTools timeline

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#2210]
**[See Observatory -> DevTools Tracking Issue](https://github.com/flutter/devtools/issues/3858).**

Feature requests from discussion @chinmaygarde and I had offline. These features are currently in Observatory and are used by the Engine team for debugging performance issues:

- draw solid lines for VsyncFireCallback events. VsyncFireCallback indicates that we asked to draw a frame. The absence of the VsyncFireCallback means the engine is too busy, so we didn’t consider drawing a frame
- adding arrows for flow events
- background coloring for VsyncProcessCallback. Observatory signals these as gray and white alternating background colors. This event indicates that if you wanted to render a frame, now would be a good time
![Screen Shot 2020-07-30 at 1 42 17 PM](https://user-images.githubusercontent.com/43759233/88972741-dfb88680-d26a-11ea-8ab6-dcaf8999a0d0.png)

- selecting multiple frames and looking at averages / standard deviations. This example is for several GPURasterizer::Draw events:
![Screen Shot 2020-07-30 at 1 42 41 PM](https://user-images.githubusercontent.com/43759233/88972560-9bc58180-d26a-11ea-84d0-19a91cb8ccfa.png)

If we bring some of these features into DevTools, we should update [this article](https://medium.com/flutter/profiling-flutter-applications-using-the-timeline-a1a434964af3) accordingly.

**Comment by kenzieschmoll** [comment]
@chinmaygarde please add any context or details I may have missed. Thanks.

**Comment by bkonyi** [comment]
Adding this to the Observatory migration tracking issue.

**Comment by bkonyi** [comment]
Update: this issue will be resolved once Perfetto integration is complete.

**Comment by kenzieschmoll** [comment]
Closing this now that the embedded Perfetto trace viewer has shipped. Any new reports of missing features should be filed separately. If the Perfetto trace viewer is missing features that Catapult used to have, those feature requests should be filed against the google/perfetto repo: https://github.com/google/perfetto/issues
