### ISSUE TITLE
Support logging HTTPS traffic in the Network page

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#2228]
Requested in this comment: https://medium.com/@jaumard/super-nice-update-8e3cfeaa5406

**Comment by kenzieschmoll** [comment]
From @bkonyi 
"if we care about reporting the body of these requests (unencrypted for HTTPS) that will likely be a lot more work since the body is streamed and I'm not sure how we'd handle that with our current timeline approach.

I'm not an HTTP expert, but I know it's possible for HTTP connections to be kept open for long periods of time and we'd have to be mindful of how we approach this so we don't have giant performance hits."

**Comment by bkonyi** [comment]
@kenzieschmoll this should have been resolved in https://github.com/dart-lang/sdk/commit/7d7c88389056b4284018517f07dc900745f58417#diff-5014705a5d4e165fd43436f8d6015a21. Would you mind confirming it works for HTTPS? I'm fairly certain it should.

**Comment by kenzieschmoll** [comment]
This is resolved
