### ISSUE TITLE
Undefined port when running in iOS simulator - Unable to connect to app.

### ISSUE THREAD

**Issue by hlynurl** [flutter/devtools#2255]
I am running devtools and my app in debug mode, both from VSCode.
Neither I or flutter seem to see what port my app is running on so I am unable to connect to my app to the devtools.

The url that the devtools opens up on is -> `http://127.0.0.1:59176/?hide=debugger&port=undefined`

Why is the devtools package not registering what port the app is on when I run it through VSCode ?

**Comment by tarwin** [comment]
Same problem and cannot find any information but this question so far.

**Comment by CoderDake** [comment]
@hlynurl When you run your app VSCode you should see a `VM Service Url` in the Debug Console output. Just like you would see when running `flutter run`. Hopefully this is helpful!

![Screen Shot 2022-10-17 at 10 12 39 AM](https://user-images.githubusercontent.com/1386322/196200283-85a41df2-be7a-4ac2-9b60-82b5e0230b7e.png)

**Comment by tarwin** [comment]
Thanks @CoderDake that is useful - and hopefully useful for others too.
