### ISSUE TITLE
Add documentation on flutter.dev for new code size tool

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#2260]
@peterdjlee and @kenzieschmoll will work on this

**Comment by kenzieschmoll** [comment]
Happy to collaborate on this if you want @xster

**Comment by xster** [comment]
SG. I can start on a scaffold and might ask for details.

**Comment by kenzieschmoll** [comment]
DevTools code size tool docs written - https://flutter.dev/docs/development/tools/devtools/code-size
