### ISSUE TITLE
VM Service URI run error in VS Code

### ISSUE THREAD

**Issue by doodatales** [flutter/devtools#2271]
When selecting Start Debugging in VS Code, I'm prompted to Paste/Enter VM Service URI.  If I don't enter anything, my code doesn't run and I get a pop-up saying "You must provide a VM service URI/port to attach a debugger". I'm able to run my code from the command line in a simulator but can't debug it.

VS Code version info:
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

[✓] Flutter (Channel master, 1.21.0-8.0.pre.172, on Mac OS X 10.15.6 19G73,
    locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.47.3)
[✓] Connected device (1 available)

• No issues found!

**Comment by kenzieschmoll** [comment]
@DanTup

**Comment by DanTup** [comment]
@doodatales it sounds like you may have a launch config that's set to attach instead of launch. Can you run the **Debug: Open launch.json** command from the VS Code command palette and check whether you have `"request": "attach"`? If so, please change it to `"request": "launch"` and try again.
