### ISSUE TITLE
CanvasKit has encountered multiple erros

### ISSUE THREAD

**Issue by fredlee12345678** [flutter/devtools#2277]
I have some errors when run devtools on Chrome.

![截屏2020-08-17 下午4 26 24](https://user-images.githubusercontent.com/56996566/90375481-9a3bec00-e0a7-11ea-8583-7f1eb37f977a.png)

➜  .pub-cache git:(stable) flutter pub global activate devtools                            
Package devtools is currently active at version 0.9.0.
Resolving dependencies...
+ args 1.6.0
+ async 2.4.2 (2.5.0-nullsafety available)
+ browser_launcher 0.1.7
+ charcode 1.1.3 (1.2.0-nullsafety available)
+ collection 1.14.13 (1.15.0-nullsafety.2 available)
+ convert 2.1.1
+ crypto 2.1.5
+ devtools 0.9.0 (0.9.1-dev.2 available)
+ devtools_server 0.9.0 (0.9.1-dev.2 available)
+ devtools_shared 0.9.0 (0.9.1-dev.2 available)
+ http 0.12.2
+ http_multi_server 2.2.0
+ http_parser 3.1.4
+ intl 0.16.1
+ logging 0.11.4
+ meta 1.2.2 (1.3.0-nullsafety.2 available)
+ mime 0.9.7
+ path 1.7.0 (1.8.0-nullsafety available)
+ pedantic 1.9.2 (1.10.0-nullsafety available)
+ shelf 0.7.9
+ shelf_proxy 0.1.0+7
+ shelf_static 0.2.8
+ source_span 1.7.0 (1.8.0-nullsafety available)
+ sse 3.5.0
+ stack_trace 1.9.5 (1.10.0-nullsafety available)
+ stream_channel 2.0.0 (2.1.0-nullsafety available)
+ string_scanner 1.0.5 (1.1.0-nullsafety available)
+ term_glyph 1.1.0 (1.2.0-nullsafety available)
+ typed_data 1.2.0 (1.3.0-nullsafety.2 available)
+ usage 3.4.2
+ uuid 2.2.0
+ vm_service 4.2.0
+ webkit_inspection_protocol 0.7.3
Precompiling executables...
Precompiled devtools:devtools.
Installed executable devtools.
Activated devtools 0.9.0.

My Flutter version is :
➜  .pub-cache flutter --version
Flutter 1.17.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8af6b2f038 (7 周前) • 2020-06-30 12:53:55 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

I start devtools from command. So could someone help me? Thanks

**Comment by kenzieschmoll** [comment]
@jacob314 could this fallback be absorbing errors that are not canvas kit errors? Perhaps we need to narrow the catch down a bit

**Comment by fredlee12345678** [comment]
Hi, is there any plan for this issue?

**Comment by andesappal** [comment]
I was just thrown this issue as well. Any plans for solving it?

**Comment by elliette** [comment]
This issue looks like it occurred on an old version of DevTools. Are you still experiencing this issue with DevTools on the latest Flutter stable? If so, please reopen and we will take a look. Thanks.
