### ISSUE TITLE
Debugger log pane shows strange characters

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#228]
![screenshot 2019-02-06 at 3 06 11 pm](https://user-images.githubusercontent.com/1078012/52350612-e329d380-2a20-11e9-9657-10d48b0df44c.png)

In VS Code it looked like this (VS Code is doing the red):

<img width="738" alt="screenshot 2019-02-06 at 3 07 06 pm" src="https://user-images.githubusercontent.com/1078012/52350620-e58c2d80-2a20-11e9-9113-fe8994507a7e.png">

**Comment by devoncarew** [comment]
Good catch; sounds like we have some encoding issues somewhere along the way.

**Comment by DanTup** [comment]
I'll take a look. Wrong encoding is my middle nÃ©dÂ©me.

**Comment by DanTup** [comment]
The issues seems to be inside the `vm_service_lib package`. I've opened https://github.com/dart-lang/vm_service_drivers/pull/207 which would fix it, but I don't know whether the encoding can vary, in which case that might not be safe.
