### ISSUE TITLE
Flutter widget inspector not work after hot reload or restart (flutter web)

### ISSUE THREAD

**Issue by mahmoudsalah37** [flutter/devtools#2281]
inspector work good in first time  but after i click hot reload or restart it's not work , then i need to stop and run project again to make it work  again.
[√] Flutter (Channel beta, 1.20.0, on Microsoft Windows [Version 10.0.18363.1016], locale
    en-US)
    • Flutter version 1.20.0 at C:\flutter\flutter
    • Framework revision 916c3ac648 (2 weeks ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)     
    • Android SDK at C:\flutter\sdk
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\flutter\sdk
    • Java binary at: C:\flutter\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)    
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed
      instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Android Studio (version 3.5)
    • Android Studio at C:\flutter\android-studio
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)

[√] VS Code (version 1.48.0)
    • VS Code at C:\Users\Mahmoud salah eldin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.125

! Doctor found issues in 1 category.

**Comment by himanshusharma89** [comment]
Same for me I have to close the Dev Tools and start it again so that inspector works well.

**Comment by SafesystemDev** [comment]
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.19045.3086], locale en-US)
    • Flutter version 3.10.6 on channel stable at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (4 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\devops\AppData\Local\Android\Sdk
    • Platform android-33-ext4, build-tools 33.0.2
    • ANDROID_HOME = C:\Users\devops\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\devops\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33424.131
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.81.0)
    • VS Code at C:\Users\devops\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • YAL L21 (mobile)  • BQLDU19B30007523 • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19045.3086]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 115.0.5790.171
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 114.0.1823.51 (unsupported)

[√] Network resources
    • All expected network resources are available.

• No issues found!



///// the problem here

**Comment by CoderDake** [comment]
@SafesystemDev does the issue still persist if you click the refresh button?

**Comment by CoderDake** [comment]
I've tried reproducing on MacOS and it seemed like the widgetinspector reconnected correctly. Perhaps this behaviour is limited to Windows

**Comment by elliette** [comment]
This issue looks like it occurred on an old version of DevTools. Are you still experiencing this issue with DevTools on the latest Flutter stable? If so, please reopen and we will take a look. Thanks.
