### ISSUE TITLE
Web GL issue in Dart Dev tools

### ISSUE THREAD

**Issue by jpnaveenkumar** [flutter/devtools#2285]
<img width="1440" alt="Screenshot 2020-08-18 at 12 15 21 PM" src="https://user-images.githubusercontent.com/22998437/90469940-c0679780-e14c-11ea-87c3-b70ffe2d0419.png">

The issue #2278 fix is not working in the dev tools version 0.9.1-dev.3 release, still, the Network tab section of Dev tools seems to be blocked out.

**Comment by kenzieschmoll** [comment]
Are there errors in the Chrome dev console?

**Comment by jpnaveenkumar** [comment]
<img width="1440" alt="Screenshot 2020-08-19 at 3 50 03 PM" src="https://user-images.githubusercontent.com/22998437/90607529-eae05000-e233-11ea-980f-24945a8981c6.png">


Screenshot of my chrome console

**Comment by jacob314** [comment]
When you click ok and use the non-canvaskit based fallback does that work?

**Comment by jpnaveenkumar** [comment]
No, it didn't work still the problem persists!!
