### ISSUE TITLE
Google3 URIs are not properly handled in the debug tree view

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#2287]
See this example:

<img width="200" alt="Screen Shot 2020-08-18 at 11 18 52 AM" src="https://user-images.githubusercontent.com/1269969/90550358-b2ae1400-e144-11ea-952b-55f9ca1fb359.png">

**Comment by devoncarew** [comment]
Note, the google3 schema urls look something like `Google3://foo/bar`.
