### ISSUE TITLE
Decouple ObjectGroup and InspectorObjectGroupManager from Flutter

### ISSUE THREAD

**Issue by leonsenft** [flutter/devtools#2293]
[ObjectGroup](https://github.com/flutter/devtools/blob/9effc977ac4e1b60f8dc54675e56d18e002339c3/packages/devtools_app/lib/src/inspector/inspector_service.dart#L411) and [InspectorObjectGroupManager](https://github.com/flutter/devtools/blob/9effc977ac4e1b60f8dc54675e56d18e002339c3/packages/devtools_app/lib/src/inspector/inspector_service.dart#L1031) provide a useful abstraction for managing the lifecycle of remote object references in an inspected app.

We're building a conditional screen for AngularDart developer tools–similar to the widget inspector, but for components–and would like to reuse this pattern. Unfortunately both objects are currently coupled with Flutter.

* Methods on `ObjectGroup` call Flutter service extensions directly.
* `InspectorObjectGroupManager` depends on `InspectorService` which is also specific to Flutter.

Could these objects be refactored to decouple them from Flutter? Framework-specific services could then compose or inherit them to manage their remote object references.

**Comment by jacob314** [comment]
Refactoring them is reasonable. It might make sense to define an `AbstractInspectorService` base class that provides the APIs ObjectGroup and GroupManager call to manage lifecycles as well as other functionality that isn't specific to one ui framework.

**Comment by leonsenft** [comment]
I just discovered this is blocking our ability to reuse `EvalOnDartLibrary` for remote evaluation due to the required `ObjectGroup` argument on `eval`: https://github.com/flutter/devtools/blob/520ad4f32937544a84b523ed65b0afba660e3496/packages/devtools_app/lib/src/eval_on_dart_library.dart#L92-L96

**Comment by leonsenft** [comment]
This is obsolete, but it looks like some progress was made in https://github.com/flutter/devtools/pull/3465.
