### ISSUE TITLE
Refactor InspectorTree into a generic tree with expansion and selection

### ISSUE THREAD

**Issue by leonsenft** [flutter/devtools#2294]
We're building a conditional screen for AngularDart developer tools in google3 similar to the inspector tab. We'd like to render a tree of components in the inspected app, similar to the summary and details trees in the inspector tab. Unfortunately the inspector tree is currently coupled with Flutter–specifically to `RemoteDiagnosticsNode`.

We're currently using the `TreeView` widget, but it falls short of the inspector tree in a number of ways:
* There's no distinction between expansion and selection.
* There's no support for scrolling the selection into view.
* It doesn't draw lines to between nodes when a node has multiple children.

Could the inspector tree be refactored into a generic tree widget that supports these features, without being directly tied to the widget inspector? The comment here implies it's possible:
https://github.com/flutter/devtools/blob/9effc977ac4e1b60f8dc54675e56d18e002339c3/packages/devtools_app/lib/src/inspector/inspector_tree.dart#L48-L51

The generic widget would ideally have the same look and functionality of the inspector tree, with the added capability of defining the data model (not just `RemoteDiagnosticsNode`) and node/row renderer.

**Comment by jacob314** [comment]
I'm working on adding some slick animated searching and filtering functionality to InspectorTree. Would be nice to be able to take advantage of that in Angular as well if you have any of the same problems of huge trees of components.

**Comment by elliette** [comment]
@leonsenft Is this still something that would help ACX? Thanks!

**Comment by leonsenft** [comment]
No, we ended up building our developer tools as a Chrome DevTools tab outside of the Dart DevTools.
