### ISSUE TITLE
Alternative debugger frontends

### ISSUE THREAD

**Issue by hobochild** [flutter/devtools#2299]
Hi :wave:

I'm looking for a terminal frontend to the debugger. I mainly doing cli/serverside stuff at the moment and I just want to jump into a console at a specific breakpoint and debug, but I'm finding the current workflow of opening a browser copying the debug link quite cumbersome. I understand this is probably not on your roadmap, but was wondering anyone is aware of a project like this before I look into building it myself?

**Comment by devoncarew** [comment]
Hi - I'm not aware of any current text based Dart debuggers. I believe there was one in the past (but likely long enough ago that it wasn't using the current, vm service protocol).

package:vm_service would be a good starting point, and some of the code in this repo could serve as an inspiration in terms of a debugger client. If you do take this on, please let us know how it goes.

**Comment by hobochild** [comment]
Great, thanks for the info.
