### ISSUE TITLE
Move fake services to pkg:devtools_testing

### ISSUE THREAD

**Issue by leonsenft** [flutter/devtools#2302]
Testing a conditional screen that depends on the global `serviceManager` requires a very complex setup of fakes and/or mocks.

pkg:devtools_app's own internal tests define a useful set of fakes/mocks [here](https://github.com/flutter/devtools/blob/master/packages/devtools_app/test/support/mocks.dart). Could these be moved to pkg:devtools_testing and exposed for testing other conditional screen implementations?

**Comment by devoncarew** [comment]
@kenzieschmoll and @jacob314 can better speak to our testing setup (and whether or not this change would complicate things). Assuming they're good with the change, is this something you'd be willing to take on?

**Comment by kenzieschmoll** [comment]
mocks.dart imports quite a bit of code from devtools_app/src, though there are other tests in devtools_testing that import devtools_app/src libraries. Assuming it is fine to continue that pattern and move mocks.dart to devtools_testing, I don't think it would affect our tests.
