### ISSUE TITLE
Remove calls to `Isolate.resolvePackageUri` from devtools_server

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#2326]
Calls to `Isolate.resolvePackageUri` won't play well with running the app as an aot snapshot and we're making a couple calls to `Isolate.resolvePackageUri` for convenience to find the directory to serve assets from.

**Comment by jacob314** [comment]
Fyi @jonahwilliams

**Comment by elliette** [comment]
I don't see any references to `Isolate.resolvePackageUri` in devtools_server anymore, so closing.
