### ISSUE TITLE
Cannot activate in VS Code.

### ISSUE THREAD

**Issue by magic3584** [flutter/devtools#2334]
It always be **Activating Dart DevTools...**

**VS Code**
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:09:08.021Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

**Flutter**
Flutter 1.20.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 216dee60c0 (11 days ago) • 2020-09-01 12:24:47 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2

**Comment by helin24** [comment]
@DanTup is this something you're familiar with?

**Comment by DanTup** [comment]
@magic3584 could you try capturing a log when this happens?

- Restart VS Code
- Open your project and start a debug session
- Run the **Dart: Capture Logs** command from the VS Code command palette (untick **Analysis Server** and **VM Service** but leave everythign else ticked and click OK)
- Try to run DevTools so the issue occurs (leave it at least 60 seconds so if there are timeouts for anything they may be recorded in the logs)
- Click the **Cancel** button on the logging dialog to stop logging and open the log file

Thanks!

**Comment by magic3584** [comment]
@DanTup Hi, thanks for your reply, here is the log:

> Dart Code extension: 3.14.1
> Flutter extension: 3.14.1 (activated)
> 
> App: Visual Studio Code
> Version: 1.48.2
> Platform: mac
> 
> Workspace type: Flutter
> Analyzer type: DAS
> Multi-root?: false
> 
> Dart SDK:
>     Loc: /Desktop/flutter/bin/cache/dart-sdk
>     Ver: 2.9.2
> Flutter SDK:
>     Loc: /Desktop/flutter
>     Ver: 1.20.3
> 
> HTTP_PROXY: undefined
> NO_PROXY: undefined
> 
> Tue Sep 15 2020 [13:43:17 GMT+0800 (China Standard Time)] Log file started
> [1:43:41 PM] [General] [Info] Spawning /Desktop/flutter/bin/cache/dart-sdk/bin/pub with args ["global","list"]
> [1:43:41 PM] [CommandProcesses] [Info] (PROC 67053) Logging data for process...
> [1:43:41 PM] [CommandProcesses] [Info] (PROC 67053) exited (0, null)
> [1:43:41 PM] [CommandProcesses] [Info] (PROC 67053) closed (0, null)
> [1:43:45 PM] [General] [Info] Spawning /Desktop/flutter/bin/cache/dart-sdk/bin/pub with args ["global","activate","devtools"]
> [1:43:45 PM] [CommandProcesses] [Info] (PROC 67062) Logging data for process...
> [1:43:45 PM] [CommandProcesses] [Info] (PROC 67062) Resolving dependencies...
> [1:43:45 PM] [CommandProcesses] [Info] (PROC 67062)
> Tue Sep 15 2020 [13:45:55 GMT+0800 (China Standard Time)] Log file ended


I just wonder is that because of the proxy settings. 
I runs a shadowsocks proxy and set the VS Code http proxy to `http://127.0.0.1:7890`.

When the app runs, it shows `ws://localhost:62747/ws`, and I can open the DevTools in terminal with `flutter pub global run devtools`.

**Comment by DanTup** [comment]
> I just wonder is that because of the proxy settings.
> I runs a shadowsocks proxy and set the VS Code http proxy to http://127.0.0.1:7890.

I'm not sure which settings you've set, though it may be possible they're not applying to the extension host. Should the connection work without the proxy? Is it something you can entirely disable just for testing?

Otherwise, can you try running:

```
/Desktop/flutter/bin/cache/dart-sdk/bin/pub global activate devtools
```

directly in a terminal? (note: there's deliberately no `flutter` prefix here).

Also - do you have the `PUB_HOSTED_URL` environment variable set? If so, how have you set it? If it's in a terminal startup script, does it change anything if you initially launch VS Code from within a terminal?

**Comment by magic3584** [comment]
I runned `/Desktop/flutter/bin/cache/dart-sdk/bin/pub global activate devtools` in terminal  **without proxy** it showed 

> Resolving dependencies... (5:05.1s)
> It looks like pub.dartlang.org is having some trouble.
> Pub will wait for a while before trying to connect again.

If I run it **with proxy** it shows

> ...
> Downloading shelf 0.7.9...
> Downloading http_parser 3.1.4...
> Precompiling executables... (3.6s)
> Precompiled devtools:devtools.
> Installed executable devtools.
> Warning: Pub installs executables into $HOME/.pub-cache/bin, which is not on your path.
> You can fix that by adding this to your shell's config file (.bashrc, .bash_profile, etc.):
> 
>   export PATH="$PATH":"$HOME/.pub-cache/bin"
> 
> Activated devtools 0.9.2.

It looks like the proxy problem in China.

And `echo $PUB_HOSTED_URL` in terminal shows blank.

**Comment by DanTup** [comment]
@magic3584 now you've activated it from the terminal, does it work from VS Code, or still fail?

Can you confirm how you're enabling/disabling the proxy, and what you're using it for (do you need it to access the internet?).

**Comment by magic3584** [comment]
@DanTup Hi, I use proxy just set `export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7891` in terminal. And I need proxy to access the sites blocked by GFW.

After I activated DevTools in terminal, it works in VS Code right now, while it wasn't yesterday, and I don't know why.
But it works now eventually anyway.

Really appreciate for your help, have a nice day~

**Comment by DanTup** [comment]
Glad you sorted it. There are known issues with VS Code extensions and proxies (and an open VS Code issue at https://github.com/microsoft/vscode/issues/12588), though it might be possible to handle this using the `dart.env` setting in your VS Code settings:

```js
"dart.env": {
  "https_proxy": "http://127.0.0.1:7890",
  "http_proxy": "http://127.0.0.1:7890",
  "all_proxy": "socks5://127.0.0.1:7891"
}
```

The `dart.env` object is used for environment variables for all Dart/Flutter processes spawned by the Dart/Flutter extensions. If you see the issue again, it's worth trying that.

**Comment by magic3584** [comment]
@DanTup Thanks for the appending information. I have and it in setting.json just in case.
