### ISSUE TITLE
Handle HTTP body events in the network and timeline pages

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#2335]
HTTP body timeline events added in https://github.com/dart-lang/sdk/commit/7d7c88389056b4284018517f07dc900745f58417

**Comment by maks** [comment]
@kenzieschmoll does this mean that the network profiler will get the ability to display request/response details like body contents, headers etc, the way say Chrome devtools does?

**Comment by kenzieschmoll** [comment]
The network profiler already displays request/response headers, but we are working on adding the ability to display the body as well.

**Comment by kenzieschmoll** [comment]
@bkonyi The HTTP body events aren't showing up in the timeline as expected. The trace events are missing the "parentId" argument that is supposed to link the response to the request.

```
{"name":"HTTP CLIENT response of GET","cat":"Dart","tid":15367,"pid":20492,"ts":213468906122,"ph":"b","id":"1","args":{"requestUri":"https://jsonplaceholder.typicode.com/albums/1","statusCode":200,"reasonPhrase":"OK","filterKey":"HTTP/client","isolateId":"isolates/2072390848141751","isolateGroupId":"isolateGroups/616754501538234698"}}
```

Perhaps something is missing in the implementation https://github.com/dart-lang/sdk/commit/7d7c88389056b4284018517f07dc900745f58417#diff-5014705a5d4e165fd43436f8d6015a21

**Comment by bkonyi** [comment]
Yup, looks like it's missing [here](https://github.com/dart-lang/sdk/commit/7d7c88389056b4284018517f07dc900745f58417#diff-9a93a60cb56c68dbbe9ecc961fc5cad9R1197). I'll get a fix out today.

**Comment by kenzieschmoll** [comment]
related: https://github.com/flutter/devtools/issues/1952

**Comment by SeasonLeee** [comment]
Hi, is there any plan of publish the dev tool with http body in the near future? 

(I recommend Flutter as our new APP's main tech... I really don't want to disappoint my team...........)

**Comment by kenzieschmoll** [comment]
The change to support this is here: https://github.com/flutter/devtools/pull/2374. Expecting to land today and publish this week with the latest bits.

**Comment by softboy99** [comment]
Hi,
this seems isn't merged to latest flutter 1.22.1(which includes dart 2.10.1)

**Comment by kenzieschmoll** [comment]
If you switch to the Flutter dev channel, you will be able to use this functionality.

**Comment by softboy99** [comment]
after switch to flutter dev branch, also failed

**Comment by SeasonLeee** [comment]
@kenzieschmoll Hi, there, I'm currently using flutter on master channel, which is 1.23.xx, which is quite latest I think. But I don't have this new feature in the dart devtool panel as there's supposed to be one.

here's the screenshot of my flutter doctor -v:
![image](https://user-images.githubusercontent.com/13610283/96235750-c1426b80-0fcd-11eb-8b67-0122d13425c8.png)

and here's my dart devtool screenshot:
![image](https://user-images.githubusercontent.com/13610283/96235896-e9ca6580-0fcd-11eb-83a5-7399c8e0433e.png)

**Comment by kenzieschmoll** [comment]
@SeasonLeee Do you see http response events in the timeline? They should be attached to the request by a thin guideline.

**Comment by SeasonLeee** [comment]
@kenzieschmoll what do you mean by that response events in the timeline? 

Do I see that event from Timeline tab? 

But isn't the Timeline tab can only record things in release mode? Well, this is what I see when I tap on the timeline tab:
![image](https://user-images.githubusercontent.com/13610283/97786348-e6e28e00-1be5-11eb-8b48-7cf54ebafcde.png)

But after I refresh the dev tool page, it become this:
![image](https://user-images.githubusercontent.com/13610283/97786411-61131280-1be6-11eb-9621-56269afbeec7.png)

And in the third panel, the bottom one, it says to select an event from the Timeline to see detail... hmm.... where is it?? Well, I didn't know at first, until I click at those one of those bar from the first panel then I can see that there's stuff appear in Timeline Events panel... 

hmm... even if this is how we get the Timeline events... but I still don't know where to get the stuff you were referring... sorry...

But there's something interesting you might want to know is that, the Response tab in the Network appear only after the second network request!

You can see the screenshot to get a better idea:

This is the first request(No Response tab appear)
![image](https://user-images.githubusercontent.com/13610283/97786667-26aa7500-1be8-11eb-9c06-b880539030bb.png)

This is the second request(Has Response tab)
![image](https://user-images.githubusercontent.com/13610283/97786745-9de00900-1be8-11eb-8b27-cd2ea3f6780b.png)

**Comment by SeasonLeee** [comment]
By the way, I am using a master channel Flutter SDK, probably the latest one

**Comment by kenzieschmoll** [comment]
By "http response events", I am referring to timeline events in the timeline page:
![Screen Shot 2020-11-02 at 3 42 58 PM](https://user-images.githubusercontent.com/43759233/97931311-3332e880-1d22-11eb-9781-2909b27bbc7e.png)

Here is an example of an HTTP request event. The small event (bottom right of this screenshot) linked to the request event by a thin gray guideline is the http response event.
![Screen Shot 2020-11-02 at 3 35 38 PM](https://user-images.githubusercontent.com/43759233/97930901-527d4600-1d21-11eb-8047-fb7da8d8f20f.png)

Here is the http response event, zoomed in a little further (to zoom in the timeline, scroll in and out, and to pan up/down/left/right, click and drag in the timeline event chart):
![Screen Shot 2020-11-02 at 3 35 22 PM](https://user-images.githubusercontent.com/43759233/97930979-7fc9f400-1d21-11eb-921c-f02fa0f8b641.png)

When using the timeline for debugging performance problems, you should be running your app in profile mode (that is why you are seeing the error banner). However, for looking for the presence of http events, whichever mode you are running in is fine. I'm just trying to verify whether or not the events are showing up as expected in the timeline but not in the network page.

**Comment by SeasonLeee** [comment]
Brilliant! @kenzieschmoll Thanks for this detail response! I will give what you described above a look! Thanks a lot!
