### ISSUE TITLE
Unable to run against Flutter master due to change in Flutter's VelocityTracker constructor

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#2338]
Running against Flutter master currently fails because we import mp_chart which  imports optimized_gesture_detector which creates a `VelocityTracker()` without passing any arguments (in latest Flutter, the constructor has a required arg).

<img width="1276" alt="Screenshot 2020-09-14 at 16 50 24" src="https://user-images.githubusercontent.com/1078012/93113697-6dccbd00-f6b1-11ea-835b-a91cc663d7c1.png">

@terrylucas apparently you're an owner of these packages so may be able to fix them (though any new package may need to have Flutter SDK constraints set to avoid users of older Flutter versions (stable/beta/dev) getting them and being broken the opposite way).

**Comment by kenzieschmoll** [comment]
Looks like this change has now hit our bots: https://travis-ci.org/github/flutter/devtools/jobs/727442720

**Comment by terrylucas** [comment]
Looks like VelocityTracker needs to pass event.kind I'll update the optimized_gesture_detector package and corresponding pubspecs.

**Comment by kenzieschmoll** [comment]
This issue has been resolved.
