### ISSUE TITLE
P1: Rename Dart DevTools 

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#2345]
@csells

**Comment by kenzieschmoll** [comment]
@DanTup can you please add an option in VS code for `Flutter: Open DevTools`? it is fine to leave the `Dart: Open DevTools` command as is and just add an additional command that does the same thing but is prefixed with Flutter. With 2.0, we'll be naming DevTools Flutter DevTools for Flutter devs and we want the tooling to reflect that.

@helin24 can you please do the rename for IntelliJ? In IntelliJ, since DevTools is only available at runtime, maybe we could just conditionally change the string based on whether the running app is a Dart or Flutter app?

**Comment by DanTup** [comment]
I've added an additional command in https://github.com/Dart-Code/Dart-Code/issues/3063 (the Flutter one will only show up if there is a Flutter project in the workspace).
