### ISSUE TITLE
Render in-progress events in the timeline

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#2349]
When an HTTP request is in progress, we will not have received the end timeline event. We should infer the end timestamp of the http request based on the associated async instant events (connection established, response received, etc.).

We should probably color these events slightly different or add some indication that the event is still in progress.

cc @bkonyi

**Comment by bkonyi** [comment]
Do we want to generalize this for all in-progress timeline events, or just the HTTP ones?

**Comment by kenzieschmoll** [comment]
I think it makes sense to do this for all in progress events

Synchronous events:
- infer end time as end of last child (if children are present), or
- vm timestamp at time of refresh

Async events:
- last child event or instant event (if present), or
- vm timestamp at time of refresh

**Comment by kenzieschmoll** [comment]
Now that we use the Perfetto trace viewer, we do not control how timeline information is rendered, so there is nothing for us to do here. Closing this as obsolete.
