### ISSUE TITLE
consider having the search field only show if the user hits cmd-f

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#2376]
Currently, for the timeline page (and I assume others), we show the search field as soon as the page is active. For the timeline page, this is as soon as the 'refresh' button is hit.

<img width="509" alt="Screen Shot 2020-09-24 at 5 38 36 PM" src="https://user-images.githubusercontent.com/1269969/94213924-066ef400-fe8d-11ea-8c89-29645ef6693e.png">

We might consider delaying showing the search field until the user explicitly invokes search (cmd-f, ...).

**Comment by kenzieschmoll** [comment]
obsolete with the perfetto integration
