### ISSUE TITLE
flutter run -d chrome trigger Maximum stack size exceeded exception

### ISSUE THREAD

**Issue by uppet** [flutter/devtools#2378]
fetch origin/master branch of devtools_app。
flutter run -d chrome， try debug any flutter app，trigger a  Maximum stack size exceeded exception

**Comment by uppet** [comment]
this happens in fltuter master channel on master branch of devtools

**Comment by kenzieschmoll** [comment]
@DanTup is looking into this issue.

**Comment by DanTup** [comment]
It seems to be a Flutter/DDC issue (https://github.com/flutter/flutter/issues/66122). There's a possible fix at https://github.com/dart-lang/sdk/commit/c5f478dfa8188b742400eeee303d61cf9e5fa408 but it hasn't made it to Flutter yet.

**Comment by DanTup** [comment]
Actually, it has landed in Fluter's master channel - and I can no longer reproduce it using the steps I had. @uppet can you confirm you also no longer see this on the latest Flutter master? Thanks!
