### ISSUE TITLE
Is there a public API for the debugger?

### ISSUE THREAD

**Issue by gkjpettet** [flutter/devtools#2410]
I'm new to Dart and I really like it. I've been experimenting with the browser-based debugger with some simple command line apps. It works as advertised.

I’m considering adding Dart support to an editor I'm writing and would obviously like to integrate debugger support for it. This has clearly been done for other editors (e.g. VS Code).

Is there a public API for controlling the VM over HTTP / WebSockets? I'm presuming this is how the browser is doing it when I step through code, set breakpoints, etc.

**Comment by devoncarew** [comment]
Yup! These are the docs for the debugger protocol:

    https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md

There's a supported Dart library for talking to the debugger - `package:vm_service` - and an unsupported Java API for the same.

**Comment by gkjpettet** [comment]
Thank you very much.
