### ISSUE TITLE
In recent versions of devtools. Internet access is required to load and so use dev tools.

### ISSUE THREAD

**Issue by elansys-kc** [flutter/devtools#2420]
If you open devtools without being connected to the internet then devtools fails to load and the following message is shown in google chromes console.

unpkg.com/canvaskit-wasm@0.17.2/bin/canvaskit.js:1 Failed to load resource: net::ERR_INTERNET_DISCONNECTED

Opening this issue for tracking as requested by @yjbanov in the following issue:
https://github.com/flutter/devtools/issues/2125

**Comment by elansys-kc** [comment]
This is also true of Android Studio. Without internet you get DevTools failed and even closing android studio and re-opening without  internet access prevents use of dev tools, just like the browser.

**Comment by elansys-kc** [comment]
Installing devtools such as described here:
[devtools](https://flutter.dev/docs/development/tools/devtools/cli)

Also still requires unpkg.com access in the browser and android studio still hangs with "installing devtools".

**Comment by jacob314** [comment]
Fyi @helin24 to resolve the Android Studio issue. Seems like it is time for a more offline friendly solution to run devtools than `pub global activate`

**Comment by dnfield** [comment]
I think the problem here is that it needs some way to bundle the CanvasKit WASM blob witht he package rather than pulling it from a CDN.

This probably would require upstream changes in the web engine to accomodate. @yjbanov

**Comment by dnfield** [comment]
If you set `FLUTTER_WEB_CANVASKIT_URL` as a compiler define, you can override the URL of the wasm blob.

I think it'd work if you just included the blob as an asset and overrode that define to point t the asset URL.

**Comment by dnfield** [comment]
https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/engine/canvaskit/initialization.dart#L51-L79

**Comment by kevlar700** [comment]
Has this regressed?

**Comment by kevlar700** [comment]
It seems that devtools via android studio on the dev channel is useable offline today but still not for web making testing navigation to a local server via ethernet quite tedious

**Comment by jacob314** [comment]
The canvas kit files are now usable offline. The problem is the Android Studio process to activate devtools. We are working to fix that issue and streamline how DevTools is deployed in general by bundling it with the Dart SDK.

**Comment by kevlar700** [comment]
I'm not sure why fonts.gstatic.com for Roboto is required either when I have my own fonts bundled?

**Comment by jacob314** [comment]
Are you talking about your Flutter Web app or Dart DevTools?

**Comment by kevlar700** [comment]
Good point, maybe it was switched to canvaskit in the dev ch from html because it broke about a week or so after the fix if I recall correctly
