### ISSUE TITLE
DevTools TimeLine cannot zoom more

### ISSUE THREAD

**Issue by AlexFeng007** [flutter/devtools#2424]
My DevTools version 0.9.3+4,
 In the Timeline views, i cannot zoom more clear in using my mouse wheels, but GPU Frame chart is ok, what can i do?

**Comment by kenzieschmoll** [comment]
Do you mean that at some level, you cannot zoom in any further? Or are you seeing some zooming jank where when you zoom in, the view jumps around to another horizontal scroll offset?

And just for clarification, [this](https://flutter.dev/docs/development/tools/devtools/timeline#timeline-events-chart) is the part of the timeline you are trying to zoom correct? This is the "zoomable" chart in the Timeline.

**Comment by 152dyn** [comment]
The notes on my computer didn't expand, and they didn't happen on my colleague's computer

![image](https://user-images.githubusercontent.com/19378921/96680743-ac3c5280-13a8-11eb-9bba-42a795ea7142.png)

**Comment by AlexFeng007** [comment]
@kenzieschmoll  Same with my timeline views, just cannot zoom in any further

**Comment by kenzieschmoll** [comment]
What does the chart look like if you zoom all the way out? I suspect the recorded duration is very long, and that the max zoom level is being hit.

**Comment by 152dyn** [comment]
@kenzieschmoll 

The minimum

![image](https://user-images.githubusercontent.com/19378921/96857673-d584dd80-1491-11eb-822a-f77e2d45b34c.png)

The biggest

![image](https://user-images.githubusercontent.com/19378921/96857764-f3ead900-1491-11eb-8092-2d3dfdef2fcd.png)
