### ISSUE TITLE
DevTools tabs are missing???

### ISSUE THREAD

**Issue by theRealBitcoinClub** [flutter/devtools#2434]
Hi,

first I gotta say that I am very grateful to the flutter team for providing such a game changing software.

I just built an app which is available in the Play Store (http://bitcoinmap.cash/coinector) for the first time for web, which worked flawlessly.

Now I would like to use the DevTools as I want to monitor the network.

But when I open the DevTools it does not show me any tabs for networking as mentioned in the Flutter docs (https://flutter.dev/docs/development/tools/devtools/overview).

See a screenshot of my DevTools window here:

![devtools](https://user-images.githubusercontent.com/35400618/96048814-65fe6500-0e77-11eb-955d-4d1fcc792326.png)

**Comment by kenzieschmoll** [comment]
It looks like you are connected to a Flutter Web app. Not all DevTools tools are available for web targets, as some require a connected Dart VM. The network page is one of these tools.

**Comment by theRealBitcoinClub** [comment]
Ok sweet so I started that app in the Android emulator and now I see these tabs.
