### ISSUE TITLE
Support multiline text selection in the Debugger source view

### ISSUE THREAD

**Issue by annagrin** [flutter/devtools#2467]
I am running devtools locally via `pub global run devtools` on Mac and connecting to the app running on remote linux machine using `ddr run //ads/acx2/demo`, stopping on a breakpoint and trying to evaluate expressions. I noticed that I cannot copy text from source window and paste it in expression evaluation box.

Devtools version: 0.9.3+4

**Comment by kenzieschmoll** [comment]
copy-paste is now implemented for single lines in the debugger. Multi-line still to come.

**Comment by kenzieschmoll** [comment]
Related flutter issue: https://github.com/flutter/flutter/issues/81839
