### ISSUE TITLE
Network tab missing requests

### ISSUE THREAD

**Issue by sm2017** [flutter/devtools#2480]
I am using DevTools to inspect network, I figured out that it not shown all requests, I am sure that I clear filters and it must show all requests, but when my app send multiple request in sub-second, network inspection only shows some of them, not all

I am using latest version of DevTools, dart, flutter, android studio, and SDKs
I only tested with simulators and in windows 10

**Comment by kenzieschmoll** [comment]
A few things to check:

1) if you add print logging to your app, are the expected number of requests being sent?
2) can you see http events in the DevTools timeline, and if so, are there the expected number of requests there?
3) http logging is only enabled once you connect devtools to your app and either navigate to the timeline page or start recording from the network page. Are you connected to DevTools and recording on the network page before the requests are sent from your app?

Can you please paste the output of `flutter --version` here as well as the devtools version you are using? Thanks

**Comment by kenzieschmoll** [comment]
CC @bkonyi

**Comment by sm2017** [comment]
@kenzieschmoll 
1. Yes
 2. I see, but no all of them, when in sub-seconds we have multiple request, inspection lost somes
3. Yes, I connected before sending request, I also stop/started app and devtools, I think there is a bug in devtools

For `flutter --version `, I will send later, currently I have no access to my PC, but I upgrade to latest version a week a go

**Comment by sm2017** [comment]
@kenzieschmoll the output of `flutter --version` is here

```
Flutter 1.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 84f3d28555 (3 weeks ago) • 2020-10-15 16:26:19 -0700
Engine • revision b8752bbfff
Tools • Dart 2.10.2
```

**Comment by bkonyi** [comment]
I'll dig into this a bit deeper before EOY.
