### ISSUE TITLE
Not receiving realtime updates on timeline

### ISSUE THREAD

**Issue by erf** [flutter/devtools#2490]
I was trying out Dart DevTools recently in order to profile my Flutter app and i was having some issues.

I'm using Android Studio 4.1 on a macOS and the version is:

```
Flutter 1.24.0-6.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 13896b3bd1 (7 days ago) • 2020-10-28 19:43:19 -0700
Engine • revision 073263e39d
Tools • Dart 2.11.0 (build 2.11.0-260.0.dev)
```

I tested on a real device, Iphone 7.

I started by pressing `Profile main`. I then opened **Flutter Performance** tab and managed to find the tiny `Open DevTools...` button. My browser, Firefox, opened up and i could see the DevTools UI. But nothing was painted on the timeline(!). 

I read the docs some more and figured there was another button to open up the DevTools in Android Studio, a tiny little blue icon above the console output. So i pressed this button and my browser, Firefox, opened up. This time i could see some profiling data when i pressed **Refresh**. After that, it seem i could press the `Open DevTools...` button and get the same result.. I also tested on the Chrome browser but it was the same result.

So my first real question is; is the **timeline** supposed to show realtime updates, or do i have to trigger **refresh** updates myself?

This is the url that opened:
```
http://127.0.0.1:51241/#/?ide=Android-Studio&uri=http%253A%252F%252F127.0.0.1%253A52478%252FLv1Eyh6e9mU%253D
```

Then i noticed this in the Console output:
```
[VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
[VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
```

I'm i supposed to make copies of my plist files (and keep them up to date) as per  instruction to profile my app?

I am able to show an performance Overlay on the app.

Btw. is it possible be profile the startup of an app?

Thanks!

**Comment by jacob314** [comment]
For now you have to click refresh. 
@kenzieschmoll can give you more information on the best way to profile at startup.  There were some issues profiling at startup but they may have now been fixed.

**Comment by kenzieschmoll** [comment]
There is a Flutter issue that is blocking the workflow to profile startup in DevTools: https://github.com/flutter/flutter/issues/70794. As a workaround, you can run your app with the `--start-paused` flag (`flutter run --start-paused`). Once the VM service URI is printed to the command line, connect your app to DevTools. Then, navigate to the Timeline page (the DevTools timeline sets the necessary recording streams by default). You can verify the "Dart", "Embedder", and "GC" streams have been set by clicking the "Timeline Configurations" button at the top right of the Timeline page: 
<img width="46" alt="Screen Shot 2020-11-30 at 9 35 29 AM" src="https://user-images.githubusercontent.com/43759233/100643904-7e272800-32ef-11eb-8b97-b71caabc964f.png">
<img width="647" alt="Screen Shot 2020-11-30 at 9 35 20 AM" src="https://user-images.githubusercontent.com/43759233/100643922-83847280-32ef-11eb-9b12-9944e9d229dc.png">.

Then, navigate to the DevTools debugger and click "Resume" to resume your application. Navigate back to the Timeline screen and click "Refresh" to see the events that occurred at startup.

Once https://github.com/flutter/flutter/issues/70794 is fixed, the timeline events from app start will be automatically populated in the Timeline upon connecting DevTools to your app, and you will not have to use the --start-paused workaround.

**Comment by hirothings** [comment]
I tried the above solution.

DevTools debugger can be used in `--debug` mode.
It is not available in `--profile` mode. In that case, how can I solve this problem?

![image](https://user-images.githubusercontent.com/5630896/103331571-ec573a00-4aa9-11eb-97a2-faaeec0304bb.png)

**Comment by kenzieschmoll** [comment]
The performance page will continue to support a "refresh" model to load new data. Closing this as WAI.
