### ISSUE TITLE
AS 4.1 can't open devTools

### ISSUE THREAD

**Issue by joechan-cq** [flutter/devtools#2495]
Enviroment: MacOs 10.15.4 + Android Studio.4.1

After I upgraded AS from 4.0 to 4.1, and re-installed the Flutter and Dart Plugins, I found that I can't open the 'Flutter inspector' in AS. It always makes the mistake like:
```
Building flutter tool...

/Users/joe/Desktop/flutter/bin/flutter: line 104: ./usr/local/bin/git: No such file or directory


Unhandled exception:
ProcessException: No such file or directory
  Command: ./usr/local/bin/git -c log.showSignature=false log -n 1 --pretty=format:%H
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:498:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:640:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:93:20)
#4      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:417:51)
#5      _runGit (package:flutter_tools/src/version.dart:665:23)
#6      new FlutterVersion (package:flutter_tools/src/version.dart:54:26)
#7      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:133:29)
```
But I can open DevTools from VS Code.

I have installed Git. And 'git' works correctly in "Terminal". "which git" command shows "/usr/bin/git", but "/usr/local/bin/git" also can be ran。

I have tryed to re-install the flutter SDK, but it didn't work.
`flutter doctor -v`:
```
[✓] Flutter (Channel unknown, v1.17.5, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.17.5 at /Users/Joe/Desktop/flutter
    • Framework revision 8af6b2f038 (4 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/Joe/Desktop/android-sdk-macosx
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = /Users/Joe/Desktop/android-sdk-macosx
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one
        being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see
        https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9245
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • MIX 2 • aab3d824 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

```

**Comment by jacob314** [comment]
Are you able to run Flutter applications from Intellij?
The `/Users/joe/Desktop/flutter/bin/flutter: line 104: ./usr/local/bin/git: No such file or directory` error running Flutter tools looks concerning. Perhaps you have a couple different versions of Flutter installed and AS 4.1 is using the wrong one?

### Configuring the Flutter plugin:
* Open preferences (Preferences on macOS, File>Settings on Linux).
* Select Languages & Frameworks>Flutter.
* Enter or browse to your Flutter SDK directory in Flutter SDK path. This is the top-level flutter directory, without the bin * subdirectory. For example, /Users/obiwan/flutter.
* Click OK

**Comment by 1030310877** [comment]
> Are you able to run Flutter applications from Intellij?
> The `/Users/joe/Desktop/flutter/bin/flutter: line 104: ./usr/local/bin/git: No such file or directory` error running Flutter tools looks concerning. Perhaps you have a couple different versions of Flutter installed and AS 4.1 is using the wrong one?
> 
> ### Configuring the Flutter plugin:
> * Open preferences (Preferences on macOS, File>Settings on Linux).
> * Select Languages & Frameworks>Flutter.
> * Enter or browse to your Flutter SDK directory in Flutter SDK path. This is the top-level flutter directory, without the bin * subdirectory. For example, /Users/obiwan/flutter.
> * Click OK

Only 1.17.5 flutter is installed on my Mac, I think it's about enviroment variable, but I can't find out the reason. Finally, I edit the file (fluttersdk/packages/flutter_tools/lib/src/version.dart), and edit the function `gitLog`, use the absolute path of Git instead of the relative path, like: 
```dart
  static List<String> gitLog(List<String> args) {
    return <String>['/usr/bin/git', '-c', 'log.showSignature=false', 'log'] + args;
  }
```

However, If I upgrade the version of flutter-sdk, the error will occur again.
