### ISSUE TITLE
P1: Consider merging functionality from Timeline and Performance pages

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#2497]
@cobblest is running a UX study that should help us determine some direction for this item

**Comment by cobblest** [comment]
Research Brief: https://docs.google.com/document/d/1MndVORQw4jHN8ob-VL2GrvnyxZ1EvAsR89lQJrr50Ag/edit#heading=h.x9snb54sjlu9

**Comment by kenzieschmoll** [comment]
Based on findings from the UX studies, the following tasks should be completed to address this issue:
[ ]
[ ]
[ ]
