### ISSUE TITLE
Service extension state not properly synced between devtools instances

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#2500]
If a service extension is toggled on in one devtools instances, the state remains disabled in the other instance.
Disabling the state in one instance does disable the state in another.

**Comment by kenzieschmoll** [comment]
Which service extension widgets are you seeing this with?

**Comment by jacob314** [comment]
Happens with all of them. It only looks like it works because if you turn an extension off in one devtools that change is reflected in other devtools. turning them on doesn't do anything.

**Comment by kenzieschmoll** [comment]
Closing as not reproducible.
