### ISSUE TITLE
P1: Provide a deep link to the DevTools inspector page when a layout error occurs

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#2504]
This would be useful for linking directly to a widget from error messages. When the inspector is opened, the linked widget should be selected.

**Comment by kenzieschmoll** [comment]
Pre-requisite for this feature: https://github.com/flutter/flutter/issues/71688

**Comment by kenzieschmoll** [comment]
@helin24 and @DanTup - once this is implemented, we are planning to have a link in Flutter error messages like, 

`To inspect this widget, visit http://127.0.0.1:9100/#/inspector?widgetId=123&uri=app-vm-service-uri`.

Clicking that link will open the DevTools inspector to the specified widget. If a user is using the IDE embedded DevTools inspector, however, we'd like clicking that link to point the embedded inspector to the widget in the url. Will this be possible?

**Comment by helin24** [comment]
@jacob314 I recall there's a mechanism to jump to a widget in IntelliJ code and in an inspector tree, but I'm not sure if that's usable here or accessible through a URL. Can you provide more background on whether this applies?

**Comment by kenzieschmoll** [comment]
We would also want a way to prevent the browser from launching if a user is using embedded DevTools views.

**Comment by kenzieschmoll** [comment]
This has been implemented in the flutter framework for render overflow errors

Implementation in IDEs is being tracked here: https://github.com/Dart-Code/Dart-Code/issues/3088, https://github.com/flutter/flutter-intellij/issues/5198
