### ISSUE TITLE
How can I update my devtools?

### ISSUE THREAD

**Issue by tongyangsheng** [flutter/devtools#2512]
Hi there, although I have updated my Flutter, my devtools version is still old, how can I update it, any help?
![image](https://user-images.githubusercontent.com/32046282/99493505-47c1e280-29aa-11eb-8260-f4d27784c104.png)

**Comment by tongyangsheng** [comment]
As I run **pub global activate devtools**,this is my log:
Package devtools is currently active at version 0.1.15.
Resolving dependencies... (46.5s)
+ args 1.6.0
+ async 2.4.2 (2.5.0-nullsafety.3 available)
+ browser_launcher 0.1.7
+ charcode 1.1.3 (1.2.0-nullsafety.3 available)
+ collection 1.14.13 (1.15.0-nullsafety.5 available)
+ convert 2.1.1 (3.0.0-nullsafety.0 available)
+ crypto 2.1.5
+ devtools 0.1.15 (0.9.4 available)
+ devtools_server 0.1.13 (0.9.4 available)
+ http 0.12.2
+ http_multi_server 2.2.0
+ http_parser 3.1.4 (4.0.0-nullsafety available)
+ logging 0.11.4 (1.0.0-nullsafety.0 available)
+ meta 1.2.3 (1.3.0-nullsafety.6 available)
+ mime 0.9.7
+ path 1.7.0 (1.8.0-nullsafety.3 available)
+ pedantic 1.9.2 (1.10.0-nullsafety.3 available)
+ shelf 0.7.9
+ shelf_static 0.2.8
+ source_span 1.5.5 (1.7.0 available)
+ sse 3.6.0
+ stack_trace 1.9.6 (1.10.0-nullsafety.6 available)
+ stream_channel 2.0.0 (2.1.0-nullsafety.3 available)
+ string_scanner 1.0.5 (1.1.0-nullsafety.3 available)
+ term_glyph 1.1.0 (1.2.0-nullsafety.3 available)
+ typed_data 1.2.0 (1.3.0-nullsafety.5 available)
+ usage 3.4.1 (3.4.2 available)
+ uuid 2.2.2
+ vm_service 2.1.4 (5.5.0 available)
+ webkit_inspection_protocol 0.7.4
Precompiling executables... (1.8s)
Precompiled devtools:devtools.
Installed executable devtools.

**Comment by kenzieschmoll** [comment]
How are you launching DevTools? When DevTools is loaded in Chrome, try doing a hard refresh (click in the url bar and hit enter), or go into Chrome DevTools (right click - inspect), and open the Application Tab at the top. From there, click "Clear site data" to clear the browser cache. Then try refreshing the page

**Comment by kenzieschmoll** [comment]
`flutter pub global activate devtools` should install the latest version, so it is strange that it is not. You can try `flutter pub cache repair`, but fair warning, the pub cache repair command performs a clean reinstall of all hosted and git packages in the system cache.

**Comment by faithomotoso** [comment]
Hi, I tried this and it didn't work. My current version is `0.9.3+4`, haven't been able to update.
