### ISSUE TITLE
Support search (Cmd+f) in log view

### ISSUE THREAD

**Issue by admarwick** [flutter/devtools#2542]
This log in DevTools has information that isn't in logcat (e.g. frame timing) but it's very difficult to find an event of interest without a search (aka find). 

Thanks.

**Comment by kenzieschmoll** [comment]
Are you using the latest version of DevTools (0.9.5)? The logging view has search and filter fields:
![image](https://user-images.githubusercontent.com/43759233/101678417-c7275c80-3a12-11eb-998a-b2ca6f5efc7b.png)
![image](https://user-images.githubusercontent.com/43759233/101678446-cee70100-3a12-11eb-909b-32c706243a75.png)

**Comment by kenzieschmoll** [comment]
Closing this issue - please re-open if the existing search functionality is not enough to meet your use case. thanks.
