### ISSUE TITLE
Inspector tree is empty on initial load

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#2544]
This is a regression. When loading the inspector in the past, it would load the inspector tree without clicking "Refresh Tree". Now, the initial load yields an empty tree:
<img width="1139" alt="Screen Shot 2020-12-09 at 2 43 43 PM" src="https://user-images.githubusercontent.com/43759233/101697694-1d08fe00-3a2d-11eb-83e6-74035968e1f9.png">
and only once "Refresh Tree" is clicked are widgets populated.
@jacob314

**Comment by jacob314** [comment]
Fixed but forgot to close.

**Comment by InMatrix** [comment]
I ran into this issue today. Steps to reproduce:

* Create a default Flutter starter app
* Run the app in Chrome in the debug mode
* Open DevTools
* The inspector is blank until I clicked the "Refresh Tree" button

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.1.0-12.1.pre, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.0)
[✓] Connected device (2 available)

**Comment by kenzieschmoll** [comment]
this should be resolved now.
