### ISSUE TITLE
layout explorer unavailable in chrome

### ISSUE THREAD

**Issue by benedicte69** [flutter/devtools#2554]
The layout explorer is not available while debugging in Chrome.

**Comment by helin24** [comment]
@kenzieschmoll what's expected for this situation?

**Comment by kenzieschmoll** [comment]
@benedicte69 can you give some more information? What kind of device are you running your app on? What version of DevTools are you using? 

I am running a flutter app on an iOS simulator and using the latest DevTools on Chrome, and I can use the layout explorer as expected. The layout explorer is only available for Flex widgets (Column, Row, etc.) and their children. Have you selected a flex widget?

**Comment by benedicte69** [comment]
@kenzie @helin 

I am speaking about flutter run-d chrome, when you launch your app in the browser the result is the following:

CHROME IN ITSELF _
![chrome_tool](https://user-images.githubusercontent.com/19499129/102142937-77f28900-3e63-11eb-961a-2cc40674d1e4.PNG)

You can not inspect element through the Chrome tool, apparently, there is no fit-semantic but only a fit-glass-pane. So either some map js are missing or .... or ... or .. is it deliberately that way? Since the beginning of Flutter, I never managed to use this inspector with a flutter app.

CHROME AND DART DEVTOOLS
![dart_tool](https://user-images.githubusercontent.com/19499129/102142957-7fb22d80-3e63-11eb-9c8e-0cd54a338c41.PNG)

As you can see in the Dart DevTools there is the Details Tree but there is not the layout explorer!

Those screenshots have been taken in last channel master with last Devtools activated (9.5) 

So the question is,  how to make the DartDevTool really cross-platform?

**Comment by kenzieschmoll** [comment]
What version of flutter are you on?

**Comment by benedicte69** [comment]
Depends on which channel I am in.

Envoyé depuis Yahoo Mail pour Android 
 
  Le mar., déc. 15, 2020 à 20:11, Kenzie Schmoll<notifications@github.com> a écrit :   


What version of flutter are you on?

**Comment by kenzieschmoll** [comment]
What version of flutter were you running your app with when you encountered this issue?

**Comment by benedicte69** [comment]
I was in Master Channel

**Comment by benedicte69** [comment]
Now I have recently seen that:
https://groups.google.com/g/flutter-announce/c/nuz1cjsEMzU/m/m9CZr6evBgAJ
May be it will change something. I can not test anything for the moment, my PC having a big, very big refreshing. Which means it will be like a brand new one :) but it will imply lots of resentings 
Anyway thanks a lot for helping and for taking in consideration this layout problem which I am not the only one to suffer from.

**Comment by elliette** [comment]
The layout explorer is now available for Flutter web, therefore closing as obsolete.
