### ISSUE TITLE
Can't use 0.9.3+4 and installing newer versions of dartdev tool fails

### ISSUE THREAD

**Issue by JulianBissekkou** [flutter/devtools#2559]
The current version 0.9.3+4 is not able to scroll enough on the timeline which makes it hard to debug performance issues.
I saw that this issue is already fixed in this PR https://github.com/flutter/devtools/pull/2447, and I think you shipped the fix in 0.9.4.

I am installing 0.9.4 with this command : `pub global activate devtools 0.9.4`
which produces this error:
```
Because devtools >=0.9.4 <0.9.5 depends on devtools_server 0.9.4 which depends on intl ^0.17.0-nullsafety.1, devtools >=0.9.4 <0.9.5 requires intl ^0.17.0-nullsafety.1.
So, because intl >=0.17.0-nullsafety requires SDK version >=2.11.0-180.0.dev <3.0.0 and pub global activate depends on devtools 0.9.4, version solving failed.
```

What is the issue here? 🤔 

Might be related to this issue:
https://github.com/flutter/devtools/issues/2512

**Comment by kenzieschmoll** [comment]
try `pub global activate devtools` without specifying a version number. Also can you add the output of `flutter --version`? Thanks

**Comment by JulianBissekkou** [comment]
I already tried `pub global activate devtools` and `flutter pub global activate devtools`. This is the output:

```
Package devtools is currently active at version 0.9.3+4.
Resolving dependencies... (1.8s)
... 
Precompiling executables... (2.5s)
Precompiled devtools:devtools.
Installed executable devtools.
Activated devtools 0.9.3+4.
```


Here are the flutter and dart version outputs:
`flutter --version`:

```
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (8 days ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4
```

`pub --version`:
```
Pub 2.10.4
```

This might be interesting as well:
`pub global list`
```
aqueduct 3.2.0
coverage 0.12.4
devtools 0.9.3+4
intl_utils 1.9.0
stagehand 3.3.7
webdev 2.5.4
```

**Comment by kenzieschmoll** [comment]
Can you try deactivating and reactivating the package?
`pub global deactivate devtools`
`pub global activate devtools`

**Comment by JulianBissekkou** [comment]
Yes, but it didn't work. 

Here the output:
```
➜  ~ pub global deactivate devtools
Deactivated package devtools 0.9.3+4.
➜  ~ pub global activate devtools
Resolving dependencies... (1.7s)
+ args 1.6.0
+ async 2.4.2
+ browser_launcher 0.1.8
+ charcode 1.1.3
+ collection 1.14.13
+ convert 2.1.1
+ crypto 2.1.5
+ devtools 0.9.3+4 (0.9.5+1 available)
+ devtools_server 0.9.3+4 (0.9.5+1 available)
+ devtools_shared 0.9.3+4 (0.9.5+1 available)
+ http 0.12.2
+ http_multi_server 2.2.0
+ http_parser 3.1.4
+ intl 0.16.1
+ logging 0.11.4
+ meta 1.2.4
+ mime 0.9.7
+ path 1.7.0
+ pedantic 1.9.2
+ shelf 0.7.9
+ shelf_proxy 0.1.0+7
+ shelf_static 0.2.9+1
+ source_span 1.7.0
+ sse 3.6.0
+ stack_trace 1.9.6
+ stream_channel 2.0.0
+ string_scanner 1.0.5
+ term_glyph 1.1.0
+ typed_data 1.2.0
+ usage 3.4.2
+ uuid 2.2.2
+ vm_service 5.5.0
+ webkit_inspection_protocol 0.7.4
Precompiling executables... (2.6s)
Precompiled devtools:devtools.
Installed executable devtools.
Activated devtools 0.9.3+4.
```

**Comment by kenzieschmoll** [comment]
@jacob314 this is strange. Any ideas?

**Comment by JulianBissekkou** [comment]
Is there an update on this, or a workaround? I want to install the new version to be able to debug performance issues in my flutter app.

**Comment by jacob314** [comment]
https://github.com/flutter/devtools/pull/2571
will fix the issue.

**Comment by JulianBissekkou** [comment]
Nice! When will the fix be deployed?
