### ISSUE TITLE
add static analysis based features to devtools

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#2572]
There are a number of compelling use cases for DevTools that would require the support of static analysis. For example:

- showing syntax highlighting in the source view (in the debugger tab)
- showing code completion in the expr. eval area
- jump to declaration in the source view
- having an outline view in the source view

@jacob314 has suggested integrating the analysis server functionality into DevTools in the past. I've been hesitant about this, as the amount of computation it might be asked to perform is unbounded (is it a very large project on disk? do we know how the client is configured in terms of excluding / including directories? do we even have access to the source on disk - is the app running on a separate device?).

However I believe there's a way to integrate static analysis into DevTools in a way where the computation it might be asked to perform is fairly constrained. In short:
- DDS would provide specific analysis server based services to clients in the form of new service extension methods / APIs (return the syntax highlighting given a script ID; return the outline for a given script ID; return the resolved location of the symbol at a given script ID and line/col, ...)
- DDS would start the analysis server, and on demand, provide it the sources for the given scripts in the running apps. I.e., the analysis server would not analyze code on disk, but would essentially be using a virtual file system based on the source for the scripts in the running app
- the analysis server would not need to perform a full analysis of the app - we're not going to need things like errors and warnings. We could be very lazy about just calculating things when we need them. This could end up being very similar to the micro-language server we built for Cider support

So:
- several new static analysis related service protocol APIs are available to clients
- DDS starts the analysis server on demand and provides the sources for the scripts to it
- the analysis server works on a VFS based on the VM's scripts and performs most analysis lazily

cc @jacob314; @kenzieschmoll for DevTools; @DanTup as we'd discussed some static analysis service extensions; @bkonyi for DDS; @scheglov for the analyzer's micro server

**Comment by jacob314** [comment]
Additional analysis server APIs that would be interest to DevTools but weren't relevant for Cider:
1. APIs to refactor Flutter build method code for the layout explorer and general build method editing.
2. The Flutter outline API (useful for showing widget indent guides and some inspector functionality).

**Comment by bkonyi** [comment]
Starting the analysis server from DDS should be doable, assuming we only start it when we need it. However, I'm not 100% sure things will work in all situations, particularly with respect to having access to sources on disk. I _think_ we should be okay, but we should probably sit down and talk through the various usage scenarios and development environments to make sure.

**Comment by devoncarew** [comment]
> Starting the analysis server from DDS should be doable, assuming we only start it when we need it. However, I'm not 100% sure things will work in all situations, particularly with respect to having access to sources on disk.

We'd run the analysis server in such a way that it wouldn't need access to source on disk; we'd do something like populate the analysis server's content overlays w/ the [analysis.updateContent](https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html#request_analysis.updateContent) call, or have a mode where it could call back into DDS to get the contents of a file when it needed them.

> we should probably sit down and talk through the various usage scenarios and development environments to make sure.

Yup, this issue just sketches out an idea. We'd need to better understand the costs and benefits, and various other implementation strategies, before we commit to doing anything here.

**Comment by DanTup** [comment]
I'd previously started playing around with having the DevTools Server spawn the LSP server, though didn't get too far with it yet. I'd hoped to be able to share a server with the IDE but it seems LSP has no plans to support multiple clients for a single server anytime soon.

> showing code completion in the expr. eval area

This is something I'd like in VS Code too (though it's part of DAP rather than LSP). I filed an issue at https://github.com/dart-lang/sdk/issues/44581 with some notes on how DAP defines it that might be a useful reference.

**Comment by bwilkerson** [comment]
The analysis server's legacy protocol also had an API to support some similar functionality. It was used in some predecessor of devtools, but I think it's currently unused. See `sdk/pkg/analysis_server/doc/api.html#domain_execution` for a description of the protocols.

**Comment by elliette** [comment]
Closing as obsolete since the Debugger panel is now in maintenance mode.
