### ISSUE TITLE
build macos release error

### ISSUE THREAD

**Issue by wanglikun7342** [flutter/devtools#2574]
[   +9 ms] CodeSign /Users/wanglikun/projects/devtools/packages/devtools_app/build/macos/Build/Products/Profile/Dart\ DevTools.app (in target 'Runner' from project 'Runner')
[        ]     cd /Users/wanglikun/projects/devtools/packages/devtools_app/macos
[        ]     export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
[        ] Signing Identity:     "-"
[        ]     /usr/bin/codesign --force --sign - --entitlements /Users/wanglikun/projects/devtools/packages/devtools_app/build/macos/Build/Intermediates.noindex/Runner.build/Profile/Runner.build/Dart\ DevTools.app.xcent --timestamp=none
/Users/wanglikun/projects/devtools/packages/devtools_app/build/macos/Build/Products/Profile/Dart\ DevTools.app
[  +24 ms] /Users/wanglikun/projects/devtools/packages/devtools_app/build/macos/Build/Products/Profile/Dart DevTools.app: bundle format unrecognized, invalid, or unsuitable
[        ] In subcomponent: /Users/wanglikun/projects/devtools/packages/devtools_app/build/macos/Build/Products/Profile/Dart DevTools.app/Contents/Frameworks/App.framework

**Comment by wanglikun7342** [comment]
@kenzieschmoll i need help

**Comment by kenzieschmoll** [comment]
Try running `flutter clean` and upgrading flutter to the latest master. If you have any local edits to macos build files (e.g. `git status`), try reverting those. If that doesn't work and you are blocked, a temporary workaround would be to run the DevTools app on Chrome. `flutter run -d chrome`

**Comment by wanglikun7342** [comment]
@kenzieschmoll treeshakeicons will cause this error when build release mode mac app https://github.com/flutter/flutter/pull/73141  @dnfield
