### ISSUE TITLE
Dart DevTools, network tab - not working

### ISSUE THREAD

**Issue by AntonFesun** [flutter/devtools#2594]
https://prnt.sc/wlaqn6 <----link for screenshot

When I open network tab - there is only inifinite spinner and "Showing 0 of 0 requests". (Chrome)

Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (5 weeks ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4

DevTools 0.9.6
Windows 10 
IDE: Android Studio 4.1.1.

**Comment by KingAlawaka** [comment]
I am having the same issue. I want to check my firestore requests. 
But I can't see any network calls in my network tab.
Any idea?
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18363.1379], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Android Studio (version 4.0)
[√] VS Code, 32-bit edition (version 1.51.1)
[√] Connected device (2 available)

**Comment by marko-mlinarevic** [comment]
@AntonFesun I see that you closed it, what was the problem

**Comment by AntonFesun** [comment]
> @AntonFesun I see that you closed it, what was the problem
> 

just upgraded flutter

**Comment by obogz** [comment]
same issue, flutter up to date

**Comment by obogz** [comment]
Aparently it is not fixed but will be in the next release:
https://github.com/flutter/devtools/issues/2860
