### ISSUE TITLE
what is the unread indicator above the 'Flutter Inspector' and 'Logging' tab about?

### ISSUE THREAD

**Issue by SeasonLeee** [flutter/devtools#2607]
Please check out the screenshot below:

![image](https://user-images.githubusercontent.com/13610283/104539746-1cc9d700-5659-11eb-97f8-46565ec3a147.png)

These indicator only show up after the devTool was upgraded to 0.9.6.

I find it quite misleading and confusing... mainly I don't really understand what it's about.... so what is it....

Some info about my flutter:
![image](https://user-images.githubusercontent.com/13610283/104539931-7df1aa80-5659-11eb-8db1-f2ac9a242039.png)

info about the devTool:
![image](https://user-images.githubusercontent.com/13610283/104539976-8fd34d80-5659-11eb-9684-d1aca1cadf5d.png)

Thanks for reading!

**Comment by kenzieschmoll** [comment]
When errors are thrown from your application, like Overflow errors for example, we badge the relevant DevTools page that contains related information. `Flutter.error` events with inspector-related information, will badge both the the Inspector tab and logging tab with a red dot and count for the error. `Flutter.error` events without inspector-related information with badge the Logging tab only.

If you check your run console, there is likely some flutter error events that have been emitted. We are working on ways to direct you to the relevant error information once you navigate to the badged page.

**Comment by jacob314** [comment]
Maybe we should add a tooltip for the unread icons to explain what they are referring to?

**Comment by SeasonLeee** [comment]
@kenzieschmoll Thanks for the explanation!

And just like what you said, I can see that the run panel in the IDE does print some errors.

But I wonder if there's a way to make the badge go away?

Normally, it seems like a unread dot to guide the user to read the message, but I read the console, that badge just don't go away and stays there... kind of bugs me😅

@jacob314 And I agree with you, there should be some sort of tooltip to explain background of that badge.

Right now it feels like this is an undone feature... and pretty unhelpful yet kind of annoying haha...😅

**Comment by kenzieschmoll** [comment]
this should be improved by https://github.com/flutter/devtools/pull/2630 and https://github.com/flutter/devtools/issues/2694 and both will be in the next release. closing.
