### ISSUE TITLE
Improve navigation of Timeline events and CPU Profiler Flame Chart

### ISSUE THREAD

**Issue by cobblest** [flutter/devtools#2609]
Based on [UI perf diary homework study](https://docs.google.com/presentation/d/19PAAeBjXqXKxP1OpyHCq72Z9B2SIpctpPFBZ7KpOGlU/edit?resourcekey=0-GNMH_FHchg68YfpiXMWgBg#slide=id.g6007120c36_0_311), participants were struggled with information overload in Timeline event chart and Flame chart. 
- There are a lot of native system code and it was hard to identify code directly related to their own code. 
- The charts are complex and hard to understand by new users. 
- Participants were also complaining about navigation (zoom in, zoom out, and scrolling) in charts. e.g. The shortcut (opt+scroll) for navigation was not intuitive to use and users want to use more intuitive gesture (e.g. scroll on touchpad). 

![timeline_nav](https://user-images.githubusercontent.com/1214679/104770981-54eb1b80-5726-11eb-94e0-87cb833ea457.gif)

We could fix this by 
- 

- [x] Add scroll bar in the Timeline event chart (fixed in https://github.com/flutter/devtools/pull/2678)
- [x] Hide or filter native system code from on Flame Chart 
- [ ] Provide better search feature in performance tools to help users identify relevant pragmatic code in their apps
- [x] Provide more intuitive and interactive documentation and tooltips of different charts and visualizations 
- [x] Improve navigation experience and shortcuts (zoom in, zoom out, scrolling) of timeline event and flame charts. 
- [x] ~~Fix the the zoom-in issue (in version < 0.9.4) and make sure DevTools are automatically updated for users~~
(update from @kenzieschmoll: we cannot retroactively fix this issue for older versions - users should be on the latest version of DevTools by default launch from CLI and IDEs so this issue is resolved)
- [ ] Consider adding menus, tabs or more compact view to help users navigate between different event information

**Comment by kenzieschmoll** [comment]
Closing this as these issues have been resolved or are obsolete.
