### ISSUE TITLE
Ensure that Flutter devtools can function properly if dds is disabled in the flutter tool

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/devtools#2612]
For the next stable release of Flutter, we may need to disable dds on-by-default functionality in the flutter tool. This is a tracking issue to ensure that devtools still functions correctly.

@kenzieschmoll @devoncarew

**Comment by kenzieschmoll** [comment]
DevTools should function properly - if no historical logs are being sent over any streams, then the error badging feature should look accurate. We don't currently pull the historical logs on every stream with the recent RPCs @bkonyi added, so we can just delay that work.

@bkonyi am I correct that historical logs will not be sent at all if DDS is disabled?

**Comment by bkonyi** [comment]
@kenzieschmoll that's correct. Log history is completely implemented in DDS.

**Comment by kenzieschmoll** [comment]
@jonahwilliams @bkonyi this can be closed as obsolete right?

**Comment by jonahwilliams** [comment]
Correct!
