### ISSUE TITLE
"Lost app connection" when trying to start debug extension

### ISSUE THREAD

**Issue by drstonebraker** [flutter/devtools#2618]
Every time I try to start the chrome debug extension, via remote or locally served ddr app, I get a popup stating "Lost app connection". This has been true since I first installed the extension.

**Comment by kenzieschmoll** [comment]
@grouma

**Comment by grouma** [comment]
I assume this issue is related to your internal workflow. See https://github.com/flutter/devtools/issues/2619#issuecomment-764390340. Please open an internal tracking issue with more details and I'll dig in.
