### ISSUE TITLE
Cannot use devtools with dart-dev-runner

### ISSUE THREAD

**Issue by drstonebraker** [flutter/devtools#2619]
When I run the following steps:
1) run `dart-dev-runner run my-app --launch-in-chrome`
2) open chrome and navigate to http://localhost:8080/
3) press alt + D

I get a popup with the following message:
```
localhost:8080 says

DevTools failed to open with:
Unable to connect debug services to your application. Most likely this means you are trying to load in a different Chrome window than was launched by your development tool.

Your workflow alternatively supports debugging through the Dart Debug Extension.

Would you like to install the extension?

Cancel|OK
```
I do have the Dart Debug Extension install but can't get that to work either (https://github.com/flutter/devtools/issues/2618). I've tried following the steps I've found in documentation but am not sure what's going wrong.

**Comment by kenzieschmoll** [comment]
@grouma

**Comment by grouma** [comment]
`dart-dev-runner` is an internal tool only. Please open an internal tracking bug with exact details on your launch command and I'll dig in.
