### ISSUE TITLE
Cache cpu profile information when refreshing data in the Performance view

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/devtools#2631]
Hi thanks for the lib! I find that, once in a while, the Performance page says "No CPU profile data" while sometimes it behaves normally. Even stranger, once, I successfully see the profile data, but when I click somewhere in the same frame, it re-analyzes and then tells me *no* cpu profile data...

This is quite annoying, because I need the flamechart to see where the performance is bad.

Thanks!

e.g.

![image](https://user-images.githubusercontent.com/5236035/105933007-b5fce280-6088-11eb-8826-71576a250be6.png)

**Comment by kenzieschmoll** [comment]
The dart vm collects CPU profile samples at a specific frequency (specified by profile granularity selector at top of performance page), and stores those samples on a buffer. So it could either be the case that A) the vm did not collect any cpu samples during the time period you have selected in the timeline, or B) activity is continuing to occur in your application while you are looking at this timeline, and in between the time you refreshed the performance page and clicked on an event to view the cpu profile for, the samples have fallen out of the buffer. 

Based on the frame times shown in this screenshot, B) is more likely. Based on my description, does it sound like B) could be what's happening in your app? If this were the case, you'd be more likely to be able to access CPU profile data for later frames in the flutter frames chart (far right) than you would for earlier frames.

We could do something to mitigate this. We could pull all the CPU profiles available at "Refresh" and then generate "sub-profiles" for each time the profiler needs new data. This would allow us to hang on to all the available CPU profile data even if the samples fall out of the VM's buffer.

**Comment by fzyzcjy** [comment]
Hi thanks for the reply! I originally thought that, the `Refresh` will stop once the buffer is full (actually, it does not collect forever, but only collect a bunch of frames and then no more). So how can I manually pause the profiling such that I can look into a frame without its samples lost?

**Comment by kenzieschmoll** [comment]
Unfortunately, I don't think there is a way to do this. We can help on our end by caching the data available upon refreshing. 

Clicking Refresh pulls all available timeline data, so it is not intended to be a live view. If something happens in your app that you want to take a look at, clicking Refresh again would pull all recent data. We are considering changing the performance page to more of a "live" view of performance, that constantly pulls new data in instead of requiring users to refresh.

**Comment by fzyzcjy** [comment]
By the way, I also find the `CPU Profiler` tab quite helpful. That profiler faithfully record the cpu instructions :)

Thus, I wonder *what is the difference between CPU Profiler tab and the Performance tab*? Thanks! (I guess the Performance tab has more other information?)

**Comment by kenzieschmoll** [comment]
The CPU profiler is a standalone profiler with a record/stop data collection method. Example usage of this would be if you notice some specific action in your app that is slow and you want to get a recording of the profile for that one action (without including a bunch of data from tasks you are not interested in). You can read more about the CPU profiler here: https://flutter.dev/docs/development/tools/devtools/cpu-profiler

The performance page shows a more broad scope of performance information and has additional data like Flutter frame rendering times, average FPS for your running app, and timeline trace. The performance page will call out UI jank (Flutter frames that missed the FPS target and took too long to render) and give you the option to dig into the specific timeline events for that frame. Doing this will allow you to see what was happening on which thread during the frame rendering process and investigate what caused the slowdown. You can drill further down into those events and see a CPU profile for what was happening on the CPU during that timeframe. You can read more about the performance page here: https://flutter.dev/docs/development/tools/devtools/performance

**Comment by kenzieschmoll** [comment]
Obsolete.
