### ISSUE TITLE
MultiProvider like MultiBlocProvider is bloated in inspection tree

### ISSUE THREAD

**Issue by cedvdb** [flutter/devtools#2641]
Multi providers, in my case MultiBlocProvider, makes the inspection tree really bloated. If you have a bunch of service at the root of the app it just nest every providers instead of 1 multiple providers.

As you can see on this image:

![image](https://user-images.githubusercontent.com/22280985/106205425-c616de00-61be-11eb-823b-9327c525a591.png)

Also generally speaking I wish there was a way to hide things in the devtools. For example you can see in the picture that I have MyLocalization and then EasyLocalization. I don't really need to see EasyLocalization there, it would be nice if there was a way to hide it so it would be seen only in the details view.

What's in the image could be then represented like so:

```

root 
   -MyLocalization 
       -MyMaterialApp 
           -LoaderGuard 
                -MyBlocProvider 
                     -MyAuthGuard
```

Which would be more readable. I don't know how it would be possible to do though. Maybe a flag to show only user defined classes.

**Comment by jacob314** [comment]
Working on it.

**Comment by kenzieschmoll** [comment]
This is resolved by Inspector v2 work that is shipping as opt-in very soon.
