### ISSUE TITLE
unable to connect to vm getDartDevelopmentServiceVersion method not found

### ISSUE THREAD

**Issue by AhmedAbouelkher** [flutter/devtools#2652]
Hi,
When I try to open DevTools on my browser as usual I was prompted with this message, I have downgraded my Flutter and Dart VS code extension but no luck with that.  
I reproduced the issue while running `Dart: Caputer Logs` and here are the resulted logs [Dart Log](https://gist.github.com/AhmedAbouelkher/9370c6658b3859d72eb2d709b6dd1eb8#file-dartlog-txt) and this my `flutter doctor -v `  resulted in [Flutter Doctor](https://gist.github.com/AhmedAbouelkher/9370c6658b3859d72eb2d709b6dd1eb8#file-flutter_doctor)

![Screen Shot 2021-01-31 at 11 59 52 AM](https://user-images.githubusercontent.com/56558577/106380590-f5df0500-63bb-11eb-8eeb-e2e95cb36e97.png)

**Comment by GilesLeRockeur** [comment]
Hey there's an recent and active thread about this here : #75055

**Comment by AhmedAbouelkher** [comment]
Duplicate of #75055

**Comment by AhmedAbouelkher** [comment]
Duplicate of [flutter/flutter#75055](https://github.com/flutter/flutter/issues/75055)
