### ISSUE TITLE
Invalid argument(s): A directory corresponding to fileSystemPath "devtools-0.9.7+1/build" could not be found

### ISSUE THREAD

**Issue by jeiea** [flutter/devtools#2653]
It seems published `devtools-0.9.7+1` missed build directory. I checked it by downloading package directly from [pub.dev](https://pub.dev/packages/devtools/versions).

```
✗ flutter pub global run devtools
Unhandled exception:
Invalid argument(s): A directory corresponding to fileSystemPath "/Users/jeiea/.pub-cache/hosted/pub.dartlang.org/devtools-0.9.7+1/build" could not be found
#0      createStaticHandler (package:shelf_static/src/static_handler.dart:50:5)
#1      defaultHandler (package:devtools_server/src/external_handlers.dart:40:23)
<asynchronous suspension>
#2      serveDevTools (package:devtools_server/src/server.dart:183:21)
#3      _serveDevToolsWithArgs (package:devtools_server/src/server.dart:125:10)
#4      serveDevToolsWithArgs (package:devtools_server/src/server.dart:72:16)
#5      main (file:///Users/jeiea/.pub-cache/hosted/pub.dartlang.org/devtools-0.9.7+1/bin/devtools.dart:9:3)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by cyanlink** [comment]
can confirm

**Comment by bkonyi** [comment]
Confirmed that this is an issue.

**Comment by bkonyi** [comment]
It looks like we might just need to rebuild and republish. I'll try and get someone with the right permissions to take a look tonight, but we might not be able to get something out until early morning PST tomorrow.

**Comment by cyanlink** [comment]
@bkonyi Anything we can do for now? I mean what can we user do when such thing happens (like rolling back to normal 0.9.7 versions). how can we do that?

**Comment by jeiea** [comment]
@cyanlink `flutter pub global activate devtools 0.9.6+3`

**Comment by bkonyi** [comment]
`flutter pub global activate devtools` should pull down `0.9.7+2` which should fix the issue. Thanks for your patience!
