### ISSUE TITLE
http://127.0.0.1:9100/assets/canvaskit/profiling/canvaskit.js net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by jeiea** [flutter/devtools#2656]
## Steps
- Activate devtools 0.9.7+2.
- Execute vscode command `Flutter: Open Devtools` -> `Open DevTools in Web Browser`.

## Expected behavior
Devtool page appears.

## Actual behavior
White page appears.

```
DevTools failed to load SourceMap: Could not load content for http://localhost:8000/sourcemaps/content.js.map: 
main.dart.js:60056 GET http://127.0.0.1:9100/assets/canvaskit/profiling/canvaskit.js net::ERR_ABORTED 404 (Not Found)
reset$0 @ main.dart.js:60056
DomRenderer$ @ main.dart.js:1372
(anonymous) @ main.dart.js:212940
holder.<computed> @ main.dart.js:137
initializeEngine @ main.dart.js:265
(anonymous) @ main.dart.js:16475
(anonymous) @ main.dart.js:11488
call$2 @ main.dart.js:78194
_asyncStartSync @ main.dart.js:11452
_initializePlatform @ main.dart.js:16515
webOnlyInitializePlatform @ main.dart.js:16460
(anonymous) @ main.dart.js:29018
(anonymous) @ main.dart.js:11488
call$2 @ main.dart.js:78194
_asyncStartSync @ main.dart.js:11452
main0 @ main.dart.js:29026
(anonymous) @ main.dart.js:214009
(anonymous) @ main.dart.js:213992
dartProgram @ main.dart.js:214003
(anonymous) @ main.dart.js:214011
DevTools failed to load SourceMap: Could not load content for http://localhost:8000/sourcemaps/content.js.map: 
```

**Comment by helin24** [comment]
@bkonyi it looks like this issue was discussed in https://github.com/flutter/devtools/issues/2648 - do you know what could be wrong with 0.9.7+2 ?

**Comment by bkonyi** [comment]
@helin24 no clue. This is basically the same version as 0.9.7, so maybe @kenzieschmoll would know.

**Comment by kenzieschmoll** [comment]
@jacob314 @dnfield

**Comment by dnfield** [comment]
I just activated 0.9.7+2 and it works for me locally :\

I don't think we include the source maps, so seeing that part fail is unsurprising. 

I did not use the VSCode plugin though - I just did `dart pub global activate devtools && dart pub global run devtools` and then opened the printed URL in my browser.

**Comment by dnfield** [comment]
I also just launched it from VSCode in the browser, verified I'm using 0.9.7+2, and it seems to run as expected

**Comment by jeiea** [comment]
I can't reproduce it neither after reboot. Close this issue.

**Comment by kenzieschmoll** [comment]
@DanTup in case you have any ideas.
