### ISSUE TITLE
Call stack "view all" is not sticky

### ISSUE THREAD

**Issue by Hixie** [flutter/devtools#2664]
The call stack sometimes truncates itself and shows a "view all" button. When you press it, the list goes truncates again when you step forward in the code.

Ideally this list would be sticky. An alternative if this is a performance optimization would be to only compute as many lines as is necessary to fill the call stack window, using a lazy list.

**Comment by jacob314** [comment]
Using a lazy list is easy enough polish and will make the UI less annoying to use.
Fyi @grouma @kenzieschmoll

**Comment by grouma** [comment]
One other alternative is to put the `SHOW ALL` button in the list itself. So users scroll to the bottom and click the button and the button is replace with additional frames keeping the list sticky.
