### ISSUE TITLE
App exits when exporting, and sometimes viewing traces

### ISSUE THREAD

**Issue by gspencergoog** [flutter/devtools#2672]
When connected to a large app, if I try to export traces, the app exits, and the observatory loses the connection to the app (presumably because it exited).

This is intermittent, and also sometimes happens when zooming in to a frame to see details. I was able to get a trace exported once without it exiting, but it happens very frequently.

I'm running it on an iPhone 6s+, and I've spoken with one other person on the Flutter team that has experienced this on their iPhone 6s.

There are no crash logs on the phone, so it doesn't appear to be crashing, the log just says "Lost connection to device" and it exits.

Any tips on how to collect more information to add to this issue would be welcome: this is blocking performance tuning of an important customer app.

**Comment by devoncarew** [comment]
Any chance this is the same crash as https://github.com/dart-lang/sdk/issues/44700?

**Comment by chunhtai** [comment]
I am also experiencing this, but it crashes a few second after I pressed refresh button. If I am fast enough, i am able to export the timeline data before it crashes

**Comment by kenzieschmoll** [comment]
Closing this as obsolete - we can re-open if new reports of this come up.
