### ISSUE TITLE
Check for updates and let a user know how to update.

### ISSUE THREAD

**Issue by dnfield** [flutter/devtools#2673]
There's logic in the flutter_tools that tries to activate devtools (https://github.com/flutter/flutter/blob/3490ae82d1be88668ebb16bc84db971dc49eb30b/packages/flutter_tools/lib/src/devtools_launcher.dart#L72-L78). It tries to guard this so it only tries twice a day (https://github.com/flutter/flutter/blob/3490ae82d1be88668ebb16bc84db971dc49eb30b/packages/flutter_tools/lib/src/devtools_launcher.dart#L136-L143).

This logic appears to serve the purpose of both getting and updating devtools. Ideally, it would not be used to update devtools - instead, devtools would just let a user know if there's a newer version available via a snackbar or banner or somesuch. It could do a check in the background while still rendering the UI, and pop up some notice about how to upgrade (click here, or run this command, or whatever).

The basic problem with this living in the tool is that it is likely to leave the user in a state where they are waiting for some condition even if they have no internet connection, and they have no idea that it actually required an internet connection to achieve. Flutter tool users end up having trouble with this if they are on a low bandwidth/metered connection, or just working offline and have no connection at all.

**Comment by Hixie** [comment]
This code doesn't actually block anything (other than loading devtools), FWIW.

**Comment by dnfield** [comment]
It doesn't block taking a new key input when you press v?

**Comment by Hixie** [comment]
I intend to hide "v" when devtools isn't running.
