### ISSUE TITLE
Step in, step over and step out don't work after a refresh

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#2682]
Steps to reproduce:

1) Set a breakpoint
2) Hit the breakpoint in your running application
3) Refresh DevTools
4) Notice that the state is properly set but only resume is enabled

**Comment by kenzieschmoll** [comment]
Sounds like the state of `DebuggerController.isPaused` isn't getting set properly on refresh

**Comment by grouma** [comment]
I believe the pause state is correct since you can select resume. It's the rest of the functionality that isn't correctly updated.

**Comment by kenzieschmoll** [comment]
Ah you're right. This is the problem: `_hasFrames` is set to false: https://github.com/flutter/devtools/blob/4f76dfe77e478a7e5a67d0318d51b652a5a1728c/packages/devtools_app/lib/src/debugger/debugger_controller.dart#L101 when the controls are built https://github.com/flutter/devtools/blob/ccc6c60750dd9e195127600d6a5888e1e014fe90/packages/devtools_app/lib/src/debugger/controls.dart#L28
