### ISSUE TITLE
Share filter dialog at a higher level across all of DevTools

### ISSUE THREAD

**Issue by terrylucas** [flutter/devtools#2685]
Currently, the filter dialog is used by only the memory profiler to not display (if the user selects) classes from Dart, Flutter, private classes (prefixed with an underscore), etc. in snapshots, allocation monitoring or stacktraces (allocation tracking).

Sounds like profiling and maybe (debugging) might want to share this code.

Look at moving to a higher level (top-level settings).

Kenzie, is this the kind of functionality you wanted in profile and debug view?  If so, assign to me and I'll move out the code from memory to general settings.

@kenzieschmoll

**Comment by kenzieschmoll** [comment]
I'm not sure that the same filters would apply to other parts of DevTools. IMO the data on each page is unique enough that it makes sense for each page to implement its own filter. It could also be the case that a user wants to apply different filters to different pages, and locking them into a common filter wouldn't allow that. For example, maybe a user doesn't care about package:flutter libraries for memory profiling, but they do want to see package:flutter methods in CPU profiling and debugging?

Do you have a specific filter in mind that you think would apply to all of DevTools?

**Comment by kenzieschmoll** [comment]
Closing as obsolete. We have default filter settings specific to each page.
