### ISSUE TITLE
Can't copy values from Response body in the Network inspector

### ISSUE THREAD

**Issue by jlubeck** [flutter/devtools#2691]
It would be very valuable to be able to select and copy values from the Network inspector. Specially form the Response body (and Request body when available)

Although I'm assuming all the other tabs might benefit from selecting/copying as well.

**Comment by casvanluijtelaar** [comment]
When devtools are embedded in vscode, you can't copy paste at all. when opening devtools in the browser it's impossible to copy text in bulk:

https://user-images.githubusercontent.com/67225314/171386234-df00d7e3-5dda-4e46-84ed-ab3f4aa10a1a.mov

for me a "copy text" button would suffice, but in the long term this should be looked at.

**Comment by sharpsan** [comment]
This is still an issue.
MacOS Sonoma.

**Comment by sauravkumarsahoo** [comment]
Still an issue on VSCode on Mac OS Tahoe.
