### ISSUE TITLE
Polish scrollbars on performance page

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#2695]
There is no horizontal scrollbar even though the content can scroll horizontally and the vertical scrollbar includes the header line when it should not.
Notice the scrollbar includes he header line when that content doesn't scroll and there is no horizontal scrollbar even though that content scrolls.
![image](https://user-images.githubusercontent.com/1226812/107567960-364c3900-6b9b-11eb-8d16-bed2d0caeb8e.png)

Fyi @kenzieschmoll 
It would be nice to polish this for 2.0

**Comment by Piinks** [comment]
@InMatrix I think what you are seeing is a scrollbar applied by the ScrollBehavior and the scrollbar manually added in the app. Reference: https://flutter.dev/docs/release/breaking-changes/default-desktop-scrollbars 

The MaterialScrollBehavior does not show horizontal scrollbars be default, which may be why they are hiding here.

The header looks to be similar to this issue: https://github.com/flutter/flutter/issues/13253

**Comment by kenzieschmoll** [comment]
Obsolete since we switched to the Perfetto trace viewer
