### ISSUE TITLE
<30FPS for hello world app with profile mode build when the DevTools webpage is opened or has been opened

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/devtools#2703]
Hi thanks for the lib!

I find that, when running the app in Profile mode, and *open the DevTools webpage*, the performance overlay reveals the rastering to be *very* slow. It is even <30fps for a simple hello world flutter app. Moreover, even if I close that webpage, the performance is stilly strongly impacted.

### Severity

It is common to open DevTools webpage (espeically because there are lots of helpful tools there for debugging performance problems). But if a developer opens that page, then the rendering FPS values will be strongly influenced (e.g. down to 30FPS for a simple page). The developer may then think either his code has big problems, or Flutter framework is too slow.

### Possible reason

The possible reason may be the following: When opening the DevTools, even if I did nothing and the webpage shows no hints like "data is being recorded", it seems that the Flutter dart code is doing some kind of CPU profiling (is it?) and transfering data to my computer. Thus this kind of CPU profiling makes the performance very bad.

**Comment by kenzieschmoll** [comment]
Thanks for the report. A few questions for you:
1) When you say "DevTools webpage", what specific tab or screen in DevTools are you opening (inspector, performance, memory, etc.)?
2) What is the FPS of the app you are running without running DevTools?
3) How are you measuring FPS?

**Comment by fzyzcjy** [comment]
1. Performance tab
2. 60fps
3. the official performance overlay

**Comment by kenzieschmoll** [comment]
The Performance page no longer collects CPU samples by default. Closing as obsolete.
