### ISSUE TITLE
depends on devtools_shared 0.9.7+3

### ISSUE THREAD

**Issue by xiaocode337317439** [flutter/devtools#2712]
Because flutter_tools depends on devtools_shared 0.9.7+3 which doesn't match
  any versions, version solving failed.

https://pub.flutter-io.cn address could not find

**Comment by kenzieschmoll** [comment]
Which version of flutter are you using? Can you provide repro steps for this issue? thanks

**Comment by huanghongxun** [comment]
https://pub.flutter-io.cn does not sync the latest version. Unset `PUB_HOSTED_URL` and retry.

**Comment by xiaocode337317439** [comment]
> https://pub.flutter-io.cn does not sync the latest version. Unset `PUB_HOSTED_URL` and retry.

But if you don't use https://pub.flutter-io.cn in China, you can't use the latest version of Master

**Comment by xu-baolin** [comment]
Waiting for `https://pub.flutter-io.cn` updating or using a VPN
