### ISSUE TITLE
Create a minimal performance view for embedding in IDEs

### ISSUE THREAD

**Issue by gspencergoog** [flutter/devtools#2722]
I initially filed https://github.com/flutter/flutter-intellij/issues/5275 for this, but after doing some manual timings with `WidgetsBinding.addTimingsCallback`, I'm finding that those times agree with the Performance tab in IntelliJ, and it's the DevTools performance information that seems off.

I'm doing some benchmarking on Linux, and when I run the app in --profile mode, I get the following output from the IntelliJ Flutter Performance tab:
![image](https://user-images.githubusercontent.com/8867023/108549038-7e591300-72a1-11eb-92ab-5b696c6ba814.png)

But when I load it in the DevTools, I get this:
![image](https://user-images.githubusercontent.com/8867023/108549154-a6e10d00-72a1-11eb-835b-db4797207b37.png)

Those are for the same time period.  Why does the IntelliJ plugin show lots of jank, and the DevTools show perfectly acceptable performance?

## Flutter Doctor details
<details>
<pre>
[✓] Flutter (Channel unknown, 1.27.0-2.0.pre.107, on Linux, locale en_US.UTF-8)
    • Flutter version 1.27.0-2.0.pre.107 at /home/gspencer/code/flutter
    • Framework revision 86a51b16f6 (3 days ago), 2021-02-16 11:04:46 -0800
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/gspencer/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /home/gspencer/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 11.0.1-2
    • cmake version 3.18.4
    • ninja version 1.8.2
    • pkg-config version 0.29.2

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /opt/my-intellij-ce-latest
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.182

• No issues found!
</pre>
</details>

**Comment by jacob314** [comment]
Fyi @kenzieschmoll.
Greg can you click on the export button and add the output to this bug so we can drill into what data DevTools is getting?

**Comment by gspencergoog** [comment]
Sure, here it is:

[dart_devtools_2021_2_19-1613761025970000.json.zip](https://github.com/flutter/devtools/files/6012859/dart_devtools_2021_2_19-1613761025970000.json.zip)

**Comment by kenzieschmoll** [comment]
The example you linked has frames with high latency between the UI and the Raster thread events.
<img width="1045" alt="Screen Shot 2021-03-05 at 9 24 47 AM" src="https://user-images.githubusercontent.com/43759233/110151151-f8ef5b80-7d94-11eb-8005-ec6fe5fd0b22.png">

This brings us back to the discussion of how we should be calculating Flutter Frame time: https://docs.google.com/document/d/1YGLELXWdC6YIN03QzEzcIRJc56gCnabPBW8BHCAFR58/edit.

In DevTools, we do not account for latency in FPS calculations (related https://github.com/flutter/devtools/issues/450). We calculate jank as either the UI thread work or the Raster thread work exceeding the target frame time for the device (16.6 for 60 FPS device). I believe in IntelliJ, we calculate frame time based on the Flutter.frame events:

```
{
  "number": 1,
  "startTime": 265521121149,
  "elapsed": 886958,
  "build": 2385,
  "raster": 111294,
  "vsyncOverhead": 622626
}
```

**Comment by kenzieschmoll** [comment]
Regardless of what the calculation consensus is though, we should make sure that IntelliJ and DevTools have consistent data. These flutter.frame events did not used to have separate times for the build and raster threads in the json. I think this was added a while ago, but the IntelliJ performance view still only shows one bar per frame, rather than two bars per frame like DevTools (one for UI and one for Raster). We should probably update the performance view in IntelliJ to show both UI and Raster frame timing info like DevTools does. Or better yet, we could experiment with embedding the DevTools frames chart in IntelliJ. CC @helin24

**Comment by kenzieschmoll** [comment]
Another report of inaccurate frame times here: https://github.com/flutter/flutter-intellij/issues/4815

**Comment by kenzieschmoll** [comment]
the Intellij performance view has been removed in favor of the DevTools performance view, which is now available through a DevTools tool window in IntelliJ / Android Studio
