### ISSUE TITLE
Failed to precompile devtools:devtools

### ISSUE THREAD

**Issue by m1narul** [flutter/devtools#2729]
Package devtools is currently active at version 0.9.7+3.
Resolving dependencies...
+ args 1.6.0 (2.0.0 available)
+ async 2.4.2 (2.5.0 available)
+ browser_launcher 0.1.8
+ charcode 1.1.3 (1.2.0 available)
+ collection 1.14.13 (1.15.0 available)
+ convert 2.1.1 (3.0.0 available)
+ devtools 0.9.7+3
+ devtools_server 0.9.7+3
+ devtools_shared 0.9.7+3
+ http 0.12.2 (0.13.0 available)
+ http_multi_server 2.2.0
+ http_parser 3.1.4 (4.0.0 available)
+ intl 0.16.1 (0.17.0 available)
+ logging 0.11.4 (1.0.0 available)
+ meta 1.2.4 (1.3.0 available)
+ mime 0.9.7 (1.0.0 available)
+ path 1.7.0 (1.8.0 available)
+ pedantic 1.9.2 (1.10.0 available)
+ shelf 0.7.9 (1.0.0 available)
+ shelf_proxy 0.1.0+7
+ shelf_static 0.2.9+2
+ source_span 1.7.0 (1.8.1 available)
+ sse 3.8.1
+ stack_trace 1.9.6 (1.10.0 available)
+ stream_channel 2.0.0 (2.1.0 available)
+ string_scanner 1.0.5 (1.1.0 available)
+ term_glyph 1.1.0 (1.2.0 available)
+ typed_data 1.2.0 (1.3.0 available)
+ usage 3.4.2 (4.0.0 available)
+ vm_service 5.5.0 (6.1.0+1 available)
+ webkit_inspection_protocol 0.7.5
Precompiling executables...

Failed to precompile devtools:devtools:
/D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/devtools_server-0.9.7+3/lib/src/client_manager.dart:7:8: Error: Error when reading '/D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/sse-3.8.1/lib/server/sse_handler.dart': The system cannot find the path specified.

import 'package:sse/server/sse_handler.dart';
       ^
/D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/devtools_server-0.9.7+3/lib/src/external_handlers.dart:15:8: Error: Error when reading '/D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/sse-3.8.1/lib/server/sse_handler.dart': The system cannot find the path specified.

import 'package:sse/server/sse_handler.dart';
       ^
/D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/devtools_server-0.9.7+3/lib/src/client_manager.dart:32:21: Error: Type 'SseConnection' not found.
  void acceptClient(SseConnection connection) {
                    ^^^^^^^^^^^^^
/D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/devtools_server-0.9.7+3/lib/src/client_manager.dart:172:9: Error: Type 'SseConnection' not found.
  final SseConnection _connection;
        ^^^^^^^^^^^^^
/D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/devtools_server-0.9.7+3/lib/src/client_manager.dart:32:21: Error: 'SseConnection' isn't a type.
  void acceptClient(SseConnection connection) {
                    ^^^^^^^^^^^^^
/D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/devtools_server-0.9.7+3/lib/src/client_manager.dart:172:9: Error: 'SseConnection' isn't a type.
  final SseConnection _connection;
        ^^^^^^^^^^^^^
/D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/devtools_server-0.9.7+3/lib/src/external_handlers.dart:81:22: Error: Method not found: 'SseHandler'.
  final sseHandler = SseHandler(Uri.parse('/api/sse'))
                     ^^^^^^^^^^
D:\Dev\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1379], locale en-US)
    • Flutter version 1.22.6 at D:\Dev\flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\..\..\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • VS Code at C:\..\..\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by kenzieschmoll** [comment]
Are you still seeing this issue if you try to run the latest devtools? You can check by running `flutter pub global activate devtools`
