### ISSUE TITLE
Add more lints.

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#2750]
We should be adopting more of the Flutter lints. For example, there is a lint to not use print that would save us time in code reviews.

**Comment by kenzieschmoll** [comment]
Can you link to a list of lints you'd like to be added? thanks

**Comment by jacob314** [comment]
There are a bunch. We should at least have all the lints enabled in g3. We
could start with that and then turn on all other lints without massive
false positives.

**Comment by kenzieschmoll** [comment]
We use flutter_lints and dcm lints now so this issue should be resolved.
