### ISSUE TITLE
JSON network response is not formatted in JSON, Hard to read and debug with massed up data

### ISSUE THREAD

**Issue by sbswami** [flutter/devtools#2758]

**Comment by devoncarew** [comment]
Can you provide a screenshot? Thanks!

**Comment by SeasonLeee** [comment]
I believe it's something like this:

![image](https://user-images.githubusercontent.com/13610283/117627127-6c08ba00-b1aa-11eb-86bf-cd33b5ded0cd.png)

by the way, is this issue related to this: #2604 ?
