### ISSUE TITLE
Dvorak WASD (,AOE) support in timeline view

### ISSUE THREAD

**Issue by Hixie** [flutter/devtools#2763]
Chrome's chrome://tracing, and Observatory, support ",aoe" navigation in the timeline view, which is useful for Dvorak users. (It's the same as WASD, `,`=W, `a`=A, `o`=S, `e`=D). It would be great if we could do the same.

**Comment by devoncarew** [comment]
Contributions welcome :)

https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/charts/flame_chart.dart#L336

**Comment by Hixie** [comment]
Is there a test I should update as well?

**Comment by kenzieschmoll** [comment]
You can add a test similar to https://github.com/flutter/devtools/blob/b4d0613ab5f80a66f8e68bd9da0c434486e091ce/packages/devtools_app/test/flame_chart_test.dart#L50

**Comment by Hixie** [comment]
thanks

**Comment by Hixie** [comment]
It would be relevant for anywhere where the WASD keys navigate.
