### ISSUE TITLE
Search in the timeline view is synchronous and abysmally slow

### ISSUE THREAD

**Issue by Hixie** [flutter/devtools#2765]
I took a trace of an animation and typed "driver" into the search field and my browser hung for multiple seconds.

**Comment by friebetill** [comment]
For now one can export the timeline and view it in chrome://tracing/ with a Chromium-based browser, the search is very fast there.

**Comment by kenzieschmoll** [comment]
A significant performance improvements will be included with today's DevTools release 2.2.0. Going to close this issue out as a duplicate of https://github.com/flutter/devtools/issues/2941
