### ISSUE TITLE
When a frame is selected there's no way to unselect it

### ISSUE THREAD

**Issue by Hixie** [flutter/devtools#2766]
It would be great if, after selecting a frame, you could unselect it, e.g. by clicking anywhere that doesn't have a frame in the top view or generally clicking anywhere in the bottom view. That way the nice rounded corner highlights would go away when you're no longer focusing on one frame.

**Comment by kenzieschmoll** [comment]
as of #2921 you can unselect a frame by clicking the already selected frame again. Unselecting based off of other clicks in the charts may cause some undesired behavior when scrolling the charts around. This adds the option for users to remove the selection, but does not force them into unselecting when they are navigating around charts.
