### ISSUE TITLE
CPU profiler "Total Time" column is sometimes truncated

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#2779]
While doing some profiling of the analysis server, the Total Time column is truncated hiding the percentages (even on an ultrawide screen):

![Screenshot 2021-03-10 at 11 10 34](https://user-images.githubusercontent.com/1078012/110620755-51f23180-8191-11eb-8d27-1c57a1fa745d.png)

As far as I can tell there's no way to resize this column, nor a tooltip showing the full contents of the cell.

**Comment by kenzieschmoll** [comment]
Danny can you click "Export" and email the file to me? that way I can repro easily and take a look. thanks.

**Comment by DanTup** [comment]
Sorry for the delay! Here's a new capture:

[dart_devtools_2021_3_15-1615818858678000.json.txt](https://github.com/flutter/devtools/files/6142101/dart_devtools_2021_3_15-1615818858678000.json.txt)

It's the Call Tree table that shows it:

![Screenshot 2021-03-15 at 14 35 16](https://user-images.githubusercontent.com/1078012/111170292-ad5e5e00-859b-11eb-9aa1-e8c65a4e49e6.png)
