### ISSUE TITLE
Support a dense mode for DevTools Inspector

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#2781]
The default DevTools UI is too sparse particularly when pages like the inspector are embedded in the IDE.
The dense mode should more closely match the density of the old IntelliJ based inspector implementation.
The layout explorer also needs to be polished to work better at smaller screen sizes.

**Comment by InMatrix** [comment]
A screenshot of embedded DevTools is available at: https://visualstudiomagazine.com/articles/2020/08/06/~/media/ECG/visualstudiomagazine/Images/2020/08/flutter_vscode_b.ashx

**Comment by kenzieschmoll** [comment]
Work for the inspector was done in https://github.com/flutter/devtools/pull/3149
