### ISSUE TITLE
Tree table scroll bar doesn't resize until scroll area touched

### ISSUE THREAD

**Issue by terrylucas** [flutter/devtools#2788]
Could deceive users that all rows are displayed.

Notice tree table now has items outside of the visible area:
![image](https://user-images.githubusercontent.com/2055873/110801689-56baf200-8232-11eb-888d-110140b56fe1.png)

Until I click and drag a row (heading down) the scrollbar then appears.

![image](https://user-images.githubusercontent.com/2055873/110802045-ab5e6d00-8232-11eb-8385-bfee9338215c.png)

Collapsed everything but scrollbar is still active and visible but nothing to scroll and scrollbar though visible is dead (also as I dynamically collapse rows the scroll size doesn't change either when there are rows not visible below):

![image](https://user-images.githubusercontent.com/2055873/110802154-c630e180-8232-11eb-98b8-f17d71610aa1.png)

Also, the height of the scrollbar (showing its relative position to the # of rows) doesn't update until the scrollbar is touched, and there are many more rows that the scrollbar would lead one to believe that there are only a few rows below in reality many many more:

![image](https://user-images.githubusercontent.com/2055873/110802936-874f5b80-8233-11eb-8bf4-d840e178725a.png)

Once the scrollbar is touched the scrollbar relative height of data viewing to the total # of rows is correctly updated:

![image](https://user-images.githubusercontent.com/2055873/110803214-d2696e80-8233-11eb-96d3-2c4f33c0726f.png)

**Comment by kenzieschmoll** [comment]
I added `isAlwaysShown: true` to tables in https://github.com/flutter/devtools/pull/2689. @jacob314 did you discover any rules of thumb to make scrollbars behave when you were looking at inspector scrollbars? These already have `isAlwaysShown: true`, and a `scrollController` assigned to the `ScrollBar` widget.

**Comment by Piinks** [comment]
This looks like it may be related to https://github.com/flutter/flutter/issues/75613

If the content of a scrollable widget changes, the scrollbar won't know about it until it receives a scroll notification with updated scroll metrics. https://github.com/flutter/flutter/pull/82687 is an active proposal to resolve this issue, I will add this use case to the test set. :)
