### ISSUE TITLE
"Connect to a Running App" input box doesn't allow for normal text selection

### ISSUE THREAD

**Issue by nshahan** [flutter/devtools#2792]
When running DevTools as a web app the "Connect to a Running App" input box doesn't allow me to highlight text like I would expect.

Repro:
1) Lauch DevTools as a web app
2) Type some text into the "Connect to a Running App" input box
3) Try to highlight some or all of the text in the input box

Clicking and dragging the mouse in the input box when it already contains text just moves the text around and it bounces back into place when I release the mouse button.

**Comment by jacob314** [comment]
This needs to be a SelectableText.

**Comment by kenzieschmoll** [comment]
I can no longer reproduce this.
