### ISSUE TITLE
Timeline events chart zoom-in glich

### ISSUE THREAD

**Issue by InMatrix** [flutter/devtools#2793]
After I zoom into the chart past a certain point, it starts to scroll by itself. See the video below. I was running the World Clock demo from https://github.com/InMatrix/perf_diagnosis_demo.

https://user-images.githubusercontent.com/348942/110900362-7cd6a580-82b7-11eb-92c0-4fc0fb679103.mov

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.1.0-10.0.pre, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the
        Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.2)
[✓] Connected device (2 available)

**Comment by jacob314** [comment]
Fyi @kenzieschmoll. This is probably an unfortunate interaction where the scroll controller doesn't yet realize the new larger scroll extent and triggers a bounce to the old obsolete scroll extent.
