### ISSUE TITLE
Hover over shows compilation errors

### ISSUE THREAD

**Issue by annagrin** [flutter/devtools#2796]
**Issue:**

Hover over variables shows compilation errors:

![image](https://user-images.githubusercontent.com/12737689/111010956-d76e1100-834c-11eb-97ec-be5618713d94.png)

**Compilation error from expression compiler**

```
[FINEST] ExpressionCompilerService: Failed to compile " galleryInjector)": org-dartlang-debug:synthetic_debug_expression:1:17: Error: Expected one expression, but found additional input.
 galleryInjector)
```

**Suggestion**

We currently hide compilation errors on hover over in VSCode and IntelliJ in order to keep the popups meaningful, should we match that behavior in devtools? We do show compilation errors in expression compilation box and in watch window.

**Comment by annagrin** [comment]
@grouma  - should we match the behavior in other UIs here?

**Comment by grouma** [comment]
This should be the behavior in DevTools. When the corresponding request throws and error we silently ignore it: https://github.com/flutter/devtools/blob/a05ebe4c1e70b9feafca844a7e7e5674fc7662dc/packages/devtools_app/lib/src/debugger/codeview.dart#L629

My guess is that `package:dwds` is not returning the correct error response.

**Comment by annagrin** [comment]
This result is a valid result from dwds.evaluateInFrame - it does not throw and returns an `ErrorRef` which is treated differently dependent on the context (in VSCode, at least):
- in hover over - do not show
- in expression evaluation box or watch window - show.

**Comment by grouma** [comment]
Thanks for the details. I'll take a look next week.

**Comment by grouma** [comment]
@annagrin I'm having difficulty reproducing this. Can you provide repro steps, maybe with some edited code [here](https://github.com/dart-lang/webdev/blob/master/example/web/main.dart)?

**Comment by annagrin** [comment]
@grouma I am having problems using the latest devtools with that example, some constraint solving fails. My repro is in google3 and it requires https://critique-ng.corp.google.com/cl/362633754 to work for now. We can also wait until all SDK and dwds changes propagate to flutter for an easy repro.
