### ISSUE TITLE
Trim parentheses from hover spans 

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#2797]
The current debugger hover logic reuses the syntax highlighting parser logic for splitting spans to hover over. It looks like this logic may include parentheses in the span. We should implement a simple heuristic to remove these spans so that hover is more reliable. Related: https://github.com/flutter/devtools/issues/2796

**Comment by annagrin** [comment]
Another example (with `=>` getting into the span):

![image](https://user-images.githubusercontent.com/12737689/111013223-7eee4200-8353-11eb-9c06-83b6da502529.png)

**Comment by grouma** [comment]
I was able to reproduce this with several `=>` examples. Since we piggy back off the syntax grammar I don't think it makes sense to add a bunch of heuristics on top of it.

@bkonyi is this something you can look into fixing? Can we update the grammar such that parens, spaces and fat arrows cause new spans?

**Comment by devoncarew** [comment]
I suspect that the syntax grammar might not be optimized to create tokens that work well with expression evaluation. How is it (the grammar) being used currently? Would you just want to identify the character position under the cursor and then work backwards and forwards from there, looking for valid dart identifier chars?

**Comment by grouma** [comment]
> I suspect that the syntax grammar might not be optimized to create tokens that work well with expression evaluation. How is it (the grammar) being used currently? 

The grammar produces a tree of spans.

> Would you just want to identify the character position under the cursor and then work backwards and forwards from there, looking for valid dart identifier chars?

Currently we find the underlying span that we are hovered over then potentially merge spans due to `.`'s. That works well for the most part because the spans generally contain just the information we need. I'm hesitant to go with the character approach as I imagine we'll end up something very similar to the grammar which seems redundant in my mind.

**Comment by bkonyi** [comment]
> I was able to reproduce this with several `=>` examples. Since we piggy back off the syntax grammar I don't think it makes sense to add a bunch of heuristics on top of it.
> 
> @bkonyi is this something you can look into fixing? Can we update the grammar such that parens, spaces and fat arrows cause new spans?

In theory we could, (I'd have to take a closer look at the grammar)  but it's possible it could have an impact on the performance of the syntax highlighter if we break things into smaller spans. If we're only interested in tokens that can be inspected, Devon's proposal might make more sense than hacking the textmate grammar to produce more fine-grained spans.
