### ISSUE TITLE
Support disabling breakpoints

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#2805]
We currently only support deleting breakpoints. A request from an internal user is to disable a given breakpoint. This can either be implemented solely in Dart DevTools or we can consider updating the VM Service protocol to better support it across all tools.

**Comment by grouma** [comment]
cc @bkonyi @kenzieschmoll

**Comment by kenzieschmoll** [comment]
closing as duplicate https://github.com/flutter/devtools/issues/696
