### ISSUE TITLE
devtools_server args dependency is blocking flutter version upgrade

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/devtools#2816]
> Because devtools_server 2.0.0 depends on args ^1.5.1 and flutter_tools depends on args 2.0.0, devtools_server 2.0.0 is forbidden.

While the tool does not directly depend on devtools anymore, we do still get it transitively through dwds. Without an updated args dep, we're stuck on an old version of test, snapshot analysis, and native stack traces.

**Comment by kenzieschmoll** [comment]
published 2.0.0+1 with upgraded deps
