### ISSUE TITLE
File history picker shows stale files after restarting your Dart application

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#2819]
There are duplicate files in the file history picker, e.g. `main.dart`:

![5TgXR6ZwwGTtFAj](https://user-images.githubusercontent.com/1840773/111717292-fff67f00-8814-11eb-9317-907d4b8511a8.png)

Selecting those files displays an indeterminate "spinny" that never ends.

**Comment by elliette** [comment]
Closing, I'm unable to reproduce this.
