### ISSUE TITLE
Update github repo URL to point to https://flutter.dev/docs/development/tools/devtools/

### ISSUE THREAD

**Issue by kevmoo** [flutter/devtools#282]
As is tradition

**Comment by kevmoo** [comment]
...like the actual GitHub repo settings...I don't have access

**Comment by devoncarew** [comment]
It's likely that we'll use this for github hosted jekyll docs, at least for the short term.

**Comment by kenzieschmoll** [comment]
@devoncarew should we point this to https://flutter.dev/docs/development/tools/devtools/ now? I also don't have access to change.

**Comment by kevmoo** [comment]
Yes, https://flutter.dev/docs/development/tools/devtools/ seems better

**Comment by devoncarew** [comment]
@Hixie @kf6gpe - can you make this change? Thanks!

**Comment by Hixie** [comment]
Sorry it took so long.
