### ISSUE TITLE
Variables window does not show global variable

### ISSUE THREAD

**Issue by annagrin** [flutter/devtools#2821]
The example below is from ACX demo. Not sure if the problem is in the devtools or the debugger though, needs investigation.

![image](https://user-images.githubusercontent.com/12737689/111816939-a173e400-889a-11eb-8e75-6d069669bd54.png)

**Comment by elliette** [comment]
This is an issue with DWDS, closing in favor of https://github.com/dart-lang/webdev/issues/2442
