### ISSUE TITLE
Colorization fails on some code

### ISSUE THREAD

**Issue by annagrin** [flutter/devtools#2822]
Example:

![image](https://user-images.githubusercontent.com/12737689/111817543-5c03e680-889b-11eb-94a3-2e9a02b188c8.png)

**Comment by devoncarew** [comment]
Ah, good example. Can you attach the source code for this?

cc @bkonyi

**Comment by bkonyi** [comment]
Ah I think I see the issue. We open a code block with ``` but it's never closed, so the highlighter just highlights the rest of the document.

**Comment by annagrin** [comment]
Here is the link to the full file: http://google3/third_party/dart_src/angular/angular/lib/src/bootstrap/run.dart
I didn't notice unclosed quotes by I might be wrong:)
