### ISSUE TITLE
Header takes up too much space when the window is not maximized

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#2823]
The tabs are rendered below the title which takes up a ton of space when the window is not maximized:
![W2c88u9McpGVkfH](https://user-images.githubusercontent.com/1840773/111852752-6c38b780-88d5-11eb-891a-2d7b9b891b75.png)

There is still plenty of space to keep the tabs on the same line so I'm not sure why this is happening.

**Comment by grouma** [comment]
cc @kenzieschmoll

**Comment by kenzieschmoll** [comment]
Our logic for whether to use the stacked scaffold (title and tabs) is hard coded to a specific px size. We should instead calculate using a layout builder or by an estimate based off of the number of tabs.
