### ISSUE TITLE
Hover window is not vertically scrollable

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#2830]
You can't scroll vertically in a hover window. Note you can scroll horizontally for a given property. This causes issues for heavily nested responses making it impossible to see all the properties. For example:
![6EzAZc4vKVqqJbP](https://user-images.githubusercontent.com/1840773/112212544-5c251e80-8bda-11eb-9eac-325e03f30e17.png)

**Comment by kenzieschmoll** [comment]
This has been fixed
