### ISSUE TITLE
Enable layout explorer in widget inspector on web platform

### ISSUE THREAD

**Issue by annagrin** [flutter/devtools#2832]
We are publishing new version of dwds that now supports `VMService.evaluate()` for dart expressions. Widget inspector will work with this version when dwds is updated in flutter, so it would be great to enable it in devtools  at the same time.

See: https://github.com/dart-lang/webdev/pull/1285

**Comment by kenzieschmoll** [comment]
@jacob314 do you see any issues with this?

**Comment by annagrin** [comment]
Additions:
- required SDK changes are already in flutter
- required dwds changes will be published in next dwds version (10.0.0+)

**Comment by kenzieschmoll** [comment]
> required SDK changes are already in flutter

Which version of Flutter? we'll want to gate enabling the layout explorer for web on the first version of flutter your changes are included with. We don't want users to have a broken experience with the layout explorer if they are running on a version of flutter that does not include your sdk changes

**Comment by annagrin** [comment]
I know for sure they are in 2.1.0-13.0.pre.223, but we are still working on putting  dwds changes in.  Once we have everything, I will try to check for that version for enabling layout explorer for web and will send a PR.

**Comment by jacob314** [comment]
It will be great to see this enabled as soon as we have a Flutter version that supports it.

**Comment by kenzieschmoll** [comment]
In an offline discussion with Anna, it seems that we are blocked because the `flutterVersion` service is not registered by flutter_tools for web targets (see [resident_web_runner.dart](https://github.com/flutter/flutter/blob/d39d450594dc3e9f1273a9e7df10165b8150fdc5/packages/flutter_tools/lib/src/isolated/resident_web_runner.dart#L819)). Anna also found that the `registerService` method is not supported by dwds:
```
  @override
  Future<Success> registerService(String service, String alias) async {
    return _rpcNotSupportedFuture('registerService');
  }
  ```
She is looking into both issues.

**Comment by jacob314** [comment]
Fyi @grouma.

**Comment by grouma** [comment]
cc @jonahwilliams for the flutter_tools changes

**Comment by jonahwilliams** [comment]
We'll need registerService supported by dwds in order to make this work

**Comment by kenzieschmoll** [comment]
> We'll need registerService supported by dwds in order to make this work

Since `registerService` is not supported, wouldn't that mean the the call to [register `reloadSources`](https://github.com/flutter/flutter/blob/d39d450594dc3e9f1273a9e7df10165b8150fdc5/packages/flutter_tools/lib/src/isolated/resident_web_runner.dart#L814) is broken? I'm surprised we don't have a test that would have caught this.

**Comment by annagrin** [comment]
Thanks @kenzieschmoll @jonahwilliams. Registering flutter version service in `resident_web_runner.dart`  solves the issue - i believe this code is not registering the service on dwds VM but on the client wrapper of it? 

```
      unawaited(_vmService.service.registerService('reloadSources', 'FlutterTools'));
      _vmService.service.registerServiceCallback('reloadSources', (Map<String, Object> params) async {
        final bool pause = params['pause'] as bool ?? false;
        await restart(benchmarkMode: false, pause: pause, fullRestart: false);
        return <String, Object>{'type': 'Success'};
      });
     

      // My addition:
      unawaited(_vmService.service.registerService('flutterVersion', 'FlutterTools'));
      _vmService.service.registerServiceCallback('flutterVersion', (Map<String, dynamic> params) async {
        final FlutterVersion version = context.get<FlutterVersion>() ?? FlutterVersion();
        final Map<String, Object> versionJson = version.toJson();
        versionJson['frameworkRevisionShort'] = version.frameworkRevisionShort;
        versionJson['engineRevisionShort'] = version.engineRevisionShort;
        return <String, dynamic>{
          'result': <String, Object>{
            'type': 'Success',
            ...versionJson,
          }
        };
      });
```

**Comment by jonahwilliams** [comment]
Right, I can see if this works today. Is there any easy way I can test layout explorer now? Should I just wire up flutterVersion and see what happens?

**Comment by annagrin** [comment]
@jonahwilliams I've already tried, it does work. We need to wait submitting it until new version of dwds is in flutter, otherwise the layout explorer will be broken. I can send a PR for the change in the meanwhile if you would like.

**Comment by annagrin** [comment]
@jonahwilliams spoken too early:) I am running into some issues with building devtools after syncing, will update this thread when I figure out what is going on.

**Comment by annagrin** [comment]
Update: I was able to make it work with the latest devtools and dwds.  

Note that it does not work with VSCode (using widget inspector) - not sure why, I thought changes in flutter_tools would be enough as I am not making any changes to the devtools app itself... @kenzieschmoll @jonahwilliams  I'd appreciate any ideas here. Not sure if this is expected and will start working as soon as my changes in flutter_tools are in, or I need to debug it further.

To try this out:
- pull latest local versions of devtools and dwds
- update flutter_tools pubspec to point to the local dwds
- add the code above to `resident_web_runner`
- rebuild flutter_tools
- run `flutter run -d chrome --debug` in `example/hello_world` directory
- run `flutter run -d chrome --debug` in the local `devtools/packages/devtools_app` directory
  - if the build breaks, update utils.dart to use `debugName` instead of `keyLabel`
- copy and paste the debug uri from the hello_world app to the devtools app
- observe layout explorer tab showing in flutter inspector:

![image](https://user-images.githubusercontent.com/12737689/112365905-6d7f3100-8c95-11eb-9a94-8c314babdf1d.png)

**Comment by kenzieschmoll** [comment]
> Note that it does not work with VSCode (using widget inspector) - not sure why, I thought changes in flutter_tools would be enough as I am not making any changes to the devtools app itself...

+ @DanTup

**Comment by annagrin** [comment]
We think the current issue is fixed by https://github.com/flutter/flutter/issues/78987.

Will keep the issue open for final validation, and also making sure layout explorer works in VSCode.

**Comment by DanTup** [comment]
I can reproduce this not working from VS Code, but I don't understand what's happening.

I've updated everything and made the changes above. I ran DevTools using `pub global run devtools` (I've activated the local version), and then ran the example_hello_world app from the console, and I see the layout explorer.

I then ran the same example app from VS Code, and pasted its VM Service URI into the same running instance of devtools (launched from the terminal), and Layout Explorer is _not_ visible.

So I grabbed the exact command VS Code used to run the app from the logs, and ran that from the terminal, then loaded that in DevTools - and I can see Layout Explorer.

So it seems as if there's a different running the app (not DevTools) from VS Code, though I can't explain what. What exactly determines whether the layout explorer appears? I could only find a version check (for 1.13) in the code, but I presume there must be something else if it was previously only available for non-web?

**Comment by DanTup** [comment]
The issue seems to be with this call returning `false` for `registered` when the app was run from VS Code:

https://github.com/flutter/devtools/blob/a4ac906cdb6399cc872d31977ac58c68b4a8a199/packages/devtools_app/lib/src/inspector/inspector_controller.dart#L931-L935

I added some logging around the new code in resident_web_runner in Flutter, and it definitely runs the code to register the service within Flutter tools, and I also see that in the VM Service traffic logged by VS Code:

```
[4:13:09 PM] [VmService] [Info] [Flutter App] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","event":{"type":"Event","kind":"ServiceRegistered","timestamp":1617030789030,"service":"flutterVersion","method":"flutterVersion"}}}
```

This all happens well before I try to connect in DevTools, so I think the issue might that DevTools isn't detecting that service correctly (although I'm not sure why yet).

**Comment by DanTup** [comment]
@kenzieschmoll @jacob314 @bkonyi

I have a theory, but I don't know if it makes sense. I noticed that if I stop VS Code from connecting to the VM service, it works. Is it possible that the VM service is buffering the ServiceRegistered events, and then sending them to the first client that connects (and clearing them from the buffer)? This would mean that when debugging from VS Code, it gets the ServiceRegistered events, but when DevTools connects it does not (thus, it does not see the `flutterVersion` service register, and does not activate the layout explorer). When running from the console, there is no other debugger connected, so when DevTools connects it gets all of the ServiceRegistered events, including `flutterVersion`.

And if this is the case, is it something that DDS can/should be able to solve?

**Comment by kenzieschmoll** [comment]
The [dds_protocol docs](https://github.com/dart-lang/sdk/blob/master/pkg/dds/dds_protocol.md#streams) state "...subscribing to the Service stream will result in a ServiceRegistered event being sent to the subscribing client for each existing service extension." @bkonyi - does that apply to every subscribing client, or only the first subscribing client?

**Comment by bkonyi** [comment]
Yes, each client will get `ServiceRegistered` events for each service extension when they subscribe to the `Service` stream.

**Comment by bkonyi** [comment]
Assuming it's wired up correctly, the [getSupportedProtocols RPC](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#getsupportedprotocols) should respond with DDS if DDS is enabled. I think DDS might be enabled for Flutter Web since DWDS has DDS integrated, but I'll have to take a closer look (on my TODO list for this week).

**Comment by grouma** [comment]
> Jonah previously mentioned he thought DDS was not enabled for Web - is that true (and if so, would that change this)?

It should be enabled. There is this [flag](https://github.com/flutter/flutter/blob/a603714610f8c9c831e7d85071274460d70c18da/packages/flutter_tools/lib/src/commands/run.dart#L190) which defaults to false and is plumbed through to DWDS.

**Comment by DanTup** [comment]
> Assuming it's wired up correctly, the getSupportedProtocols RPC should respond with DDS if DDS is enabled.

Yep, looks like it is:

```
{"jsonrpc":"2.0","result":{"type":"ProtocolList","protocols":[{"protocolName":"VM Service","major":3,"minor":43},{"protocolName":"DDS","major":1,"minor":2}]},"id":"5"}
```

So I'm not sure what's going wrong, but let me know if you can't repro (or think VS Code is doing something bad).

**Comment by annagrin** [comment]
Jonah's PR for https://github.com/flutter/flutter/issues/78987 is in, so the registration works in standalone devtools_app but still does not in VSCode. I tried adding printing to DDS, did not see any flutter version requests sent to it. @bkonyi could that be that DDS is with dwds is on the other side of the VMConnection that has its own service extensions and does not propagate service registration to dwds?
 
VM connection:
https://github.com/dart-lang/sdk/blob/7f3f3e66ac5254c55986d7bcf3036171be05d332/pkg/vm_service/lib/src/vm_service.dart#L1248

Used in dwds here:
https://github.com/dart-lang/webdev/blob/51ad9e76a8283499059a7357f7ada8a48aacd87d/dwds/lib/src/dwds_vm_client.dart#L46

**Comment by annagrin** [comment]
Repro instructions (on latest flutter)

Without VSCode:

- run devtools via  'pub global run devtools' 
- Run ‘flutter run -d chrome --debug’ in flutter/example/hello_world directory
- Copy the debug uri to the devtools 
- Open widget inspector, see the layout explorer tab

In VSCode:

- Debug flutter/example/hello_world
- Click cmd-shift-p
- Type widget … choose “Flutter: open devtools widget inspector page”
- Observe widget inspector showing with no layout explorer tab

**Comment by annagrin** [comment]
@kenzieschmoll @DanTup from my logs it seems  that the Devtools restarts when I start using Widget Inspector, is it supposed to happen? If yes, does it connect to dwds directly somehow, or is it using vmservice that flutter tools created to connect to dwds? In the former case there would be no registrations from flutter tools on dwds itself (and on DDS as well, I presume, due to the VMConnection I mentioned above. In the latter case, would it receive old registration events from flutter tools?

Here is the restart:

```
[2:26:42 PM] [VmService] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","timestamp":1617139602133,"isolate":{"type":"@Isolate","id":"1","number":"1","name":"main()","isSystemIsolate":false},"extensionKind":"Flutter.ServiceExtensionStateChanged","extensionData":{"extension":"ext.flutter.inspector.structuredErrors","value":true}}}}
[2:27:31 PM] [General] [Info] Using only available debug session
[2:27:31 PM] [General] [Info] Spawning /Users/annagrin/source/flutter/flutter/bin/cache/dart-sdk/bin/pub with args ["global","list"]
[2:27:31 PM] [DevTools] [Info] Process terminated! null, SIGTERM
[2:27:31 PM] [VmService] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","event":{"type":"Event","kind":"ServiceUnregistered","timestamp":1617139651915,"service":"launchDevTools","method":"s0.launchDevTools"}}}
[2:27:32 PM] [General] [Info] devtools version 2.0.0+4 appears to be latest so returning Valid
[2:27:32 PM] [DevTools] [Info] Spawning /Users/annagrin/source/flutter/flutter/bin/cache/dart-sdk/bin/pub with args ["global","run","devtools","--machine","--try-ports","10","--allow-embedding","--port","9101"]
[2:27:32 PM] [DevTools] [Info] ..  with {"toolEnv":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code"}}
[2:27:32 PM] [DevTools] [Info]     PID: 68821
[2:27:32 PM] [DevTools] [Info] <== {"event":"server.started","method":"server.started","params":{"host":"127.0.0.1","port":9101,"pid":62377,"protocolVersion":"1.1.0"}}
[2:27:32 PM] [DevTools] [Info] ==> {"id":"1","method":"vm.register","params":{"uri":"http://127.0.0.1:63859/yLYycUtoI_g=/"}}
```

**Comment by jacob314** [comment]
@DanTup It does seem a bit odd that VSCode is killing the devtools server with SIGTERM before opening DevTools.
However, that shouldn't make a difference in how DevTools runs as DevTools the Flutter Web app is connecting to the VMService the same way regardless of whether the DevTools server was restarted or not.

**Comment by bkonyi** [comment]
It looks like we're not reporting all the service extensions when a client subscribes for the first time. If I modify DDS to send the historic events when a client subscribes to the `Service` stream, things work properly. Before we were only reporting the services registered directly with DDS.

I'll dig more tomorrow to find out why things are working this way and why we didn't encounter it before. There's a few subtly different ways to register extensions, so this is probably just a case I missed.

**Comment by DanTup** [comment]
> from my logs it seems that the Devtools restarts when I start using Widget Inspector, is it supposed to happen?

No, this seems like a bug. I reproduced it once, but not again. I have a theory though..

When opening DevTools, we check whether the command line args we would send to it are the same as the ones used to launch it initially. If they are not, we terminate it and start it again. I think what happened is that either the Flutter version file had not been created yet when you first opened VS Code (eg. if you'd just switched branch and Flutter was initialising), or a race condition (where DevTools was spawned before the version file was read).

In any case, this check seems superfluous now, as the only different in args is `--allow-embedding` and I think that's been available in live DevTools long enough we can drop support for versions without it, and make the args fixed (removing this restart code altogether). I'll fix that and include it in todays release.

(it shouldn't have caused any issues though, beyond being a little wasteful).

**Comment by DanTup** [comment]
> (it shouldn't have caused any issues though, beyond being a little wasteful).

Actually, that's might not be true. The original URL would've been given to Flutter, so if you'd ended up with DevTools open (or for some reason the new version was unable to find to the original port), you might've seen issues.

In any case, I've [removed the code](https://github.com/Dart-Code/Dart-Code/commit/eadf1bffb6828b1e1d230533e75fb70f9dd0ee8a) that was causing the restarts and increased the minimum version of DevTools supported by VS Code to 0.9.6 so this can't happen anymore.

**Comment by annagrin** [comment]
@bkonyi   I added some printing in DDS and flutter tools, it looks like DDS does not have a method `registerService` setup yet when `flutterVersion` is registered by flutter tools. Could this be the reason for DDS's clients not getting the `flutterVersion` registration event?

```
[+1704 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
DDS: taking control!
DDS: took control!
DDS: Started.
[  +68 ms] DevHandler: Debug service listening on ws://127.0.0.1:61886/7WG-adtZDEc=/ws
Flutter tools: registering flutter version service...
vm_service (in DWDS): Registering service {service: reloadSources, alias: Flutter Tools} in VMServerConnection
vm_service (in DWDS): Registering service {service: flutterVersion, alias: Flutter Tools} in VMServerConnection
vm_service (in DWDS): Registering service {service: flutterMemoryInfo, alias: Flutter Tools} in VMServerConnection
[  +13 ms] Debug service listening on ws://127.0.0.1:61886/7WG-adtZDEc=/ws
[        ] 💪 Running with sound null safety 💪
Connecting to VM Service at ws://127.0.0.1:61886/7WG-adtZDEc=/ws
DDS: Registered method "registerService"
DDS: Registered service launchDevTools alias: DevTools Server
...
 ```

**Comment by bkonyi** [comment]
I've confirmed the same:

```
DWDS request: {jsonrpc: 2.0, id: 1, method: registerService, params: {service: hotRestart, alias: DWDS fullReload}}
DWDS request: {jsonrpc: 2.0, id: 2, method: registerService, params: {service: fullReload, alias: DWDS}}
DWDS request: {jsonrpc: 2.0, id: 3, method: registerService, params: {service: ext.dwds.screenshot, alias: DWDS}}
DWDS request: {jsonrpc: 2.0, id: 4, method: registerService, params: {service: _yieldControlToDDS, alias: DWDS}}
// DDS is starting with the requests below.
DWDS request: {jsonrpc: 2.0, method: streamListen, id: 0, params: {streamId: Debug}}
DWDS request: {jsonrpc: 2.0, method: streamListen, id: 1, params: {streamId: Isolate}}
DWDS request: {jsonrpc: 2.0, method: streamListen, id: 2, params: {streamId: Extension}}
DWDS request: {jsonrpc: 2.0, method: streamListen, id: 3, params: {streamId: Logging}}
DWDS request: {jsonrpc: 2.0, method: streamListen, id: 4, params: {streamId: Stderr}}
DWDS request: {jsonrpc: 2.0, method: streamListen, id: 5, params: {streamId: Stdout}}
DWDS request: {jsonrpc: 2.0, method: streamListen, id: 6, params: {streamId: Service}}
DWDS request: {jsonrpc: 2.0, method: getVM, id: 7}
DWDS request: {jsonrpc: 2.0, method: getIsolate, id: 8, params: {isolateId: 1}}
DWDS request: {jsonrpc: 2.0, method: _yieldControlToDDS, id: 9, params: {uri: http://127.0.0.1:62283/dp287kkPIJU=/}}
...
```
Somehow flutter_tools is getting access to the DWDS URI when it shouldn't be. I'll do some digging.

**Comment by annagrin** [comment]
Thanks @bkonyi for finding the issue and the fix! Will work on adding tests to it.

@kenzieschmoll @jacob314 I tested Ben's change and works but throws the following exception in the process. It does show the layout explorer when hit continue after the exception. I'd appreciate any hints!

```
"Error: Bad state: A RenderObject does not have any constraints before it has been laid out.
    at Object.throw_ [as throw] (http://localhost:62806/dart_sdk.js:5037:11)
    at view.RenderView.new.get constraints [as constraints] (http://localhost:62806/packages/flutter/src/rendering/layer.dart.lib.js:2769:49)
    at <anonymous>:87:52
    at widget_inspector.InspectorSerializationDelegate.new.additionalNodeProperties (http://localhost:62806/packages/flutter/src/widgets/widget_span.dart.lib.js:17744:86)
    at http://localhost:62806/packages/flutter/src/foundation/debug.dart.lib.js:1378:36
    at http://localhost:62806/packages/flutter/src/foundation/debug.dart.lib.js:1383:11
    at framework._ElementDiagnosticableTreeNode.new.toJsonMap (http://localhost:62806/packages/flutter/src/foundation/debug.dart.lib.js:1385:26)
    at framework._ElementDiagnosticableTreeNode.new.toJsonMap (http://localhost:62806/packages/flutter/src/widgets/widget_span.dart.lib.js:48123:24)
    at <anonymous>:82:110
    at widget_inspector.InspectorSerializationDelegate.new.additionalNodeProperties (http://localhost:62806/packages/flutter/src/widgets/widget_span.dart.lib.js:17744:86)
    at http://localhost:62806/packages/flutter/src/foundation/debug.dart.lib.js:1378:36
    at http://localhost:62806/packages/flutter/src/foundation/debug.dart.lib.js:1383:11
    at framework._ElementDiagnosticableTreeNode.new.toJsonMap (http://localhost:62806/packages/flutter/src/foundation/debug.dart.lib.js:1385:26)
    at framework._ElementDiagnosticableTreeNode.new.toJsonMap (http://localhost:62806/packages/flutter/src/widgets/widget_span.dart.lib.js:48123:24)
    at <anonymous>:82:110
    at widget_inspector.InspectorSerializationDelegate.new.additionalNodeProperties (http://localhost:62806/packages/flutter/src/widgets/widget_span.dart.lib.js:17744:86)
    at http://localhost:62806/packages/flutter/src/foundation/debug.dart.lib.js:1378:36
    at http://localhost:62806/packages/flutter/src/foundation/debug.dart.lib.js:1383:11
    at framework._ElementDiagnosticableTreeNode.new.toJsonMap (http://localhost:62806/packages/flutter/src/foundation/debug.dart.lib.js:1385:26)
    at framework._ElementDiagnosticableTreeNode.new.toJsonMap (http://localhost:62806/packages/flutter/src/widgets/widget_span.dart.lib.js:48123:24)
    at widget_inspector._WidgetInspectorService.new.[_nodeToJson] (http://localhost:62806/packages/flutter/src/widgets/widget_span.dart.lib.js:15646:37)
    at getLayoutExplorerNode (<anonymous>:70:73)
    at http://localhost:62806/packages/flutter/src/foundation/binding.dart.lib.js:288:30
    at Generator.next (<anonymous>)
    at http://localhost:62806/dart_sdk.js:37374:33
    at _RootZone.runUnary (http://localhost:62806/dart_sdk.js:37245:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:62806/dart_sdk.js:32501:29)
    at handleValueCallback (http://localhost:62806/dart_sdk.js:33028:49)
    at Function._propagateToListeners (http://localhost:62806/dart_sdk.js:33066:17)
    at _Future.new.[_complete] (http://localhost:62806/dart_sdk.js:32906:25)
    at http://localhost:62806/dart_sdk.js:32085:30
    at internalCallback (http://localhost:62806/dart_sdk.js:24224:11)"
```

**Comment by annagrin** [comment]
The layout inspector works (still throws the exception above). Closing this issue, thanks everyone!
