### ISSUE TITLE
Support jump to line from the sources panel in the debugger.

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#2844]
We should match the keyboard shortcut for jump to line users are familiar with.
The default in VSCode is control-g 
Command + / + g is also reasonable on mac.
There may be a conflict with contrl-g / command-g in web browsers

**Comment by grouma** [comment]
Alternatively we could add an option in the newly created drop down menu. I think that's more discoverable.

**Comment by jacob314** [comment]
Is there any other editor that puts jump to line on that menu? VSCode, IntelliJ, and Chrome DevTools don't. I'm open to putting the item in that menu short term to improve discoverability for the keyboard shortcut but long term it would be good to keep that menu clean and focused on operations related to manipulating the files open in DevTools rather than manipulating a file.

**Comment by grouma** [comment]
So it looks like Chrome uses the general search box for this functionality. Users should enter `:<line-number>`. I think at first we can have the drop down option then eventually when we support general text search we can merge the functionality like in Chrome.
