### ISSUE TITLE
DevTools does not show POST request body

### ISSUE THREAD

**Issue by giaur500** [flutter/devtools#2852]
I can show request url, method, headers, but not request body. So I am not able to inspect api calls. There should be also shown requests body, without it network inspector is unusable

**Comment by kenzieschmoll** [comment]
@bkonyi do we have the ability to support request bodies?

**Comment by bkonyi** [comment]
> @bkonyi do we have the ability to support request bodies?

The HTTP profiler does record request bodies, but I don't think we surface them anywhere in DevTools at this point.

**Comment by giaur500** [comment]
Any plans to add it?

**Comment by Anjula** [comment]
bump.

**Comment by giaur500** [comment]
Please, anybody? Without ability to see request, how even network monitor can be considered usable? In my case, it's useless, as I need to use other tools to capture network traffic and I can see all traffic there.
