### ISSUE TITLE
Cannot profile the app starting process easily (as we know, the startup time is important to user experience)

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/devtools#2853]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Run the app using profile mode
3. Try to profile the app starting process

**Expected results:** 

As we know, the startup time is important to user experience. Therefore, I want to know why my app needs several seconds to start - which parts need how much time, such that I can try to optimize the startup time.

**Actual results:** 

In order to profile the app and see detailed stack, I need to open the DevTools (you know, that web page). However, it takes seconds to initialize and open devtools. Unfortunately, when devtools is finally opened, the app startup has almost finished! So I cannot profile anything for the startup procedure... :(

**Comment by elliette** [comment]
Thanks for filing a bug! You can use the [CPU profiler ](https://docs.flutter.dev/tools/devtools/cpu-profiler) to profile your app on start-up.

**Comment by fzyzcjy** [comment]
Thanks! (Though 3 years has passed...)
