### ISSUE TITLE
How to check CPU Utilization of Mobile while using Flutter App using DevTools

### ISSUE THREAD

**Issue by AmbujaAK** [flutter/devtools#2893]
I want to know the CPU Utilization used by Mobile while using Flutter App

**Comment by jacob314** [comment]
Can you tell me more about how you would use this information? I agree this is a useful feature but it will require getting additional information from the operating system. I assume you want CPU utilization not just for the Dart code for your application but any platform code running as part of plugins you are using as well.

**Comment by AmbujaAK** [comment]
this is basically need for monitoring my app. If CPU utilization is more then battery consumption will be more that must be taken care of.  So I want to know CPU utilization of my Flutter App like what percentage of CPU is being used by the App. It would be great if we can find which code section is making CPU utilization more. By knowing this, we can identify the issue and can write more optimized app.

**Comment by elliette** [comment]
Documentation for the CPU Profiler is here: https://docs.flutter.dev/tools/devtools/cpu-profiler

Please open a new issue if that doesn't address your concerns. Thank you!
