### ISSUE TITLE
Not possible to select text in Network tab

### ISSUE THREAD

**Issue by maks** [flutter/devtools#2926]
I would like to be able to select text shown in the Network tab, eg. url in the Overview subtab, a header value in the Headers sub-tab, etc,  but its not possible to select any of the text.

I'm using Chrome:
```

Google Chrome | 89.0.4389.128 (Official Build) (64-bit)
-- | --
Revision | 6d949d51e94419a5014d249141019d8bffc75f69-refs/branch-heads/4389@{#1640}
OS | Linux
```

**Comment by kenzieschmoll** [comment]
Can you still reproduce this with the latest DevTools? The text should be selectable.

**Comment by maks** [comment]
Sorry for the slow reply @kenzieschmoll , yes I'm running Devtools 2.2.3 now (on Flutter stable channel) and yes! I can now select fields text like Url and Header values.

As a UX improvement sidenote, it would be nice to be able to select for example all the request or response headers text, but current you need to do it one by one and its not possible to select the text of the labels for each field, but thats a more minor issue, as for now, being able to at least  select the value of each field gets me what I need.

Should I rename this issue to be specifically only about selecting text of the field labels?

**Comment by kenzieschmoll** [comment]
Sure, we can make the labels selectable too. Multiline text selection is a known issue - here is the related flutter issue tracking that https://github.com/flutter/flutter/issues/81839
