### ISSUE TITLE
fuzzy file name matching in the libraries list is far too fuzzy

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#2928]
Lots of matches that make no sense get in.
![Screen Shot 2021-04-22 at 3 03 00 PM](https://user-images.githubusercontent.com/1226812/115790674-f1ebcf00-a37b-11eb-8a3a-63e04fd74729.png)

**Comment by jacob314** [comment]
only matches that are for main.dart files should show up.
When there are multiple matches we should show the # of matches under a directory to clarify what is going on or show the first couple matches with a ...

**Comment by elliette** [comment]
Might be an issue with our fuzzy-match logic, we should try to repro this to see if it's still relevant.
