### ISSUE TITLE
Libraries view is too cluttered for dart: libraries

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#2929]
Rather than showing
```
math
dart:math
```
We should just show 
`dart:math`
![Screen Shot 2021-04-22 at 3 05 20 PM](https://user-images.githubusercontent.com/1226812/115790909-5f97fb00-a37c-11eb-8ec7-5fa60a20f521.png)

**Comment by elliette** [comment]
Closing since there is now a new libraries view for the file explorer.
