### ISSUE TITLE
Support list and map paging

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#2950]
The VM service protocol supports an optional offset parameter in [getObject](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#getobject).  This should allow Dart DevTools to support paging of list and map entries.

This is especially useful for web based debugging as extremely large maps could cause the debugger to crash. For example a map with over 4k entries. Moreover, Dart DevTools does a poor job of rendering these extremely large objects.

**Comment by jacob314** [comment]
I would suggest we default to displaying paged results in a way consistent with VSCode or Chrome DevTools.

**Comment by jacob314** [comment]
@kenzieschmoll this is a high priority issue for g3 users.
