### ISSUE TITLE
Use searchable, collapsible tree for network response tab

### ISSUE THREAD

**Issue by bryanhinkson** [flutter/devtools#2952]
I don't know if this is by design or not, but you are not able to select (and as a result copy) text in the network tab section.  This would especially be useful for responses.  There are times that I want to copy the text so I can format and search it for what I am looking for.  With some API's I am presented with a wall of plain text which is painful to read through.

I am not sure if that is a bug or a feature request but it would be really nice.  As long as I am requesting changes here are some other improvements that I think would make the Network experience better:

It would also be nice to be able to search the Network->response for text.

It would be really nice to be able to format that text into a collapsible JSON tree. (perhaps just for application/json responses) That would make it much easier to navigate through the responses.

These features are in the chrome dev tools experience and I believe that they would translate very well to the flutter dev tools as well.

Thanks for all you do!

**Comment by kenzieschmoll** [comment]
These are great improvements - thank you for the feature requests!

**Comment by kenzieschmoll** [comment]
What text in particular are you trying to select but are unable to?

**Comment by kenzieschmoll** [comment]
some additional user feedback around the response tab: "i would like to have nicer formatting for responses. view response is too slow if the response body is too big"
