### ISSUE TITLE
Stop manually truncating strings in the CPU profiler.

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#2960]

**Comment by bkonyi** [comment]
Is this related to this buggy formatting of URIs by any chance?

<img width="2560" alt="Screen Shot 2022-05-05 at 2 01 05 PM" src="https://user-images.githubusercontent.com/24210656/167010032-a0e38186-e0a2-4a2c-8c37-09daab1bd2a6.png">

**Comment by kenzieschmoll** [comment]
most likely. For now, we could increase the column width. I haven't seen this weird left align, right align thing before though. FYI @CoderDake
