### ISSUE TITLE
Port devtools server and devtools shared to use null safety

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#2978]
This is blocking packages that depend on devtools_shared and devtools_server from running in sound null safety mode. For example, flutter_tools.

**Comment by kenzieschmoll** [comment]
devtools_shared port here: https://github.com/flutter/devtools/pull/2995.
devtools_server port is blocked on package:sse and package:browser_launcher being migrated. @grouma @natebosch @kevmoo

**Comment by kenzieschmoll** [comment]
package:browser_launcher is migrated and published 1.0.0. Now just blocked on package:sse
