### ISSUE TITLE
we should consider compiling dart2js with -O3

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#300]
From Siggi:

> One thing to bear in mind is that we don't try to optimize away Dart-2 checks because -O3 is so commonly used. If you hit perf issues in the app, definitely worth looking into it.

**Comment by jacob314** [comment]
The checks did catch a real double vs int bug on windows. In general it would also be nice to run without checks so that ignore-able type errors don't crash things.

**Comment by kenzieschmoll** [comment]
this issue pertained to the html app - closing as obsolete
