### ISSUE TITLE
"Track Widget Builds" makes frame rates considerably lower

### ISSUE THREAD

**Issue by InMatrix** [flutter/devtools#3002]
I was running a profile build of https://github.com/InMatrix/perf_diagnosis_demo/blob/master/lib/clock_demo.dart. After turning on "Track Widget Builds" the average frame rate dropped from 59 to 24. Is it working as intended? 

"Track Widget Builds" off:
![image](https://user-images.githubusercontent.com/348942/117730381-1976d000-b1a1-11eb-9e50-287d13bb5ec6.png)

"Track Widget Builds" on: 
![image](https://user-images.githubusercontent.com/348942/117730362-111e9500-b1a1-11eb-816d-b22406a8dc6a.png)

$ flutter doctor -v

<details>
flutter doctor -v
[✓] Flutter (Channel dev, 2.3.0-0.1.pre, on macOS 11.3.1 20E241 darwin-x64, locale en-US)
    • Flutter version 2.3.0-0.1.pre at /Users/taodong/fvm/versions/dev
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d72bfb8d07 (2 weeks ago), 2021-04-26 06:05:55 -0700
    • Engine revision de6e1adf97
    • Dart version 2.14.0 (build 2.14.0-18.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/taodong/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ CE (stable).app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • Nexus 6P (mobile) • 8XV5T15A12004485 • android-arm64  • Android 8.1.0 (API 27)
    • macOS (desktop)   • macos            • darwin-x64     • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 90.0.4430.93

</details>

**Comment by kenzieschmoll** [comment]
This is expected. This is why we can't have this feature on by default because it has performance implications (AFAIK we haven't designed a performant way to use this feature). Brings us back to the classic problem with building performance tooling: "how do we measure performance without hurting the performance we are trying to measure 🤔 ".

**Comment by jacob314** [comment]
We should test whether the performance hit scales linearly with the # of timeline events. There is some prior art where chrome devtools fudges profile times to account for the overhead of profiling. 

I think we can also make progress by defaulting to a filtered version of track widget builds that tracks fewer widget builds. I think users only care about widget builds for widgets they created from their package/project as those are the only widgets they have control over. That could help the usability of this feature as well as the performance as the trace of widget builds would be less overwhelming.

**Comment by InMatrix** [comment]
> I think users only care about widget builds for widgets they created from their package/project as those are the only widgets they have control over.

+1. This could make the feature more useful, IMO.
