### ISSUE TITLE
Editing value on provider throws eval error

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#3003]
Repro steps:
1. run the flutter gallery app
2. Click the "Reply" app from the carousel of apps at the top of the flutter gallery homescreen
3. On the provider page of DevTools, the EmailStore provider will become available
4. try to edit the _count field

<img width="874" alt="Screen Shot 2021-05-11 at 2 06 06 PM" src="https://user-images.githubusercontent.com/43759233/117885197-666eab00-b262-11eb-87b0-2154f2b2d6ae.png">
<img width="865" alt="Screen Shot 2021-05-11 at 2 06 12 PM" src="https://user-images.githubusercontent.com/43759233/117885201-679fd800-b262-11eb-8a34-cd963ea663f6.png">

@rrousselGit @jacob314

**Comment by rrousselGit** [comment]
When I try, before this exception I get another one:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
#0      new Script._fromJson
package:vm_service/src/vm_service.dart:6773
#1      Script.parse
package:vm_service/src/vm_service.dart:6732
#2      createServiceObject
package:vm_service/src/vm_service.dart:68
#3      VmService._processResponse
package:vm_service/src/vm_service.dart:2173
#4      VmService._processMessageStr
package:vm_service/src/vm_service.dart:2152
#5      VmService._processMessage
package:vm_service/src/vm_service.dart:2104
#6      _rootRunUnary (dart:async/zone.dart:1436:47)
#7      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#11     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#12     _HandleErrorStream._handleData (dart:async/stream_pipe.dart:256:10)
#13     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#14     _rootRunUnary (dart:async/zone.dart:1436:47)
#15     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#19     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#20     _HandleErrorStream._handleData (dart:async/stream_pipe.dart:256:10)
#21     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#22     _rootRunUnary (dart:async/zone.dart:1436:47)
#23     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#27     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#28     _StreamController._add (dart:async/stream_controller.dart:607:7)
#29     _rootRunUnary (dart:async/zone.dart:1436:47)
#30     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#34     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#35     _StreamController._add (dart:async/stream_controller.dart:607:7)
#36     _StreamController.add (dart:async/stream_controller.dart:554:5)
#37     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#38     _rootRunUnary (dart:async/zone.dart:1436:47)
#39     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#40     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#43     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#44     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#45     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#46     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#47     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#48     _rootRunUnary (dart:async/zone.dart:1436:47)
#49     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#50     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#51     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#52     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#53     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#54     _StreamController._add (dart:async/stream_controller.dart:607:7)
#55     _StreamController.add (dart:async/stream_controller.dart:554:5)
#56     _Socket._onData (dart:io-patch/socket_patch.dart:2160:41)
#57     _rootRunUnary (dart:async/zone.dart:1444:13)
#58     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#59     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#60     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#61     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#62     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#63     _StreamController._add (dart:async/stream_controller.dart:607:7)
#64     _StreamController.add (dart:async/stream_controller.dart:554:5)
#65     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1696:33)
#66     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1208:14)
#67     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#68     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

```



I wonder if this is related, as editing `_count` on other apps works fine.

**Comment by rrousselGit** [comment]
Oh, I found the problem.

It's because `EmailStore` is defined as:

```dart
class EmailStore with ChangeNotifier
```

rather than:

```dart
class EmailStore extends ChangeNotifier
```

That messes up with how the information about where `_count` is coming from.

With mixins, `_count`'s `Instance.owner` is
```
Instance(name: _EmailStore&Object&ChangeNotifier, uri: package:gallery/studies/reply/model/email_store.dart)
```

rather than:

```
Instance(name: ChangeNotifier, uri: package:flutter/.../foundation.dart)
```


That's a problem because since it is a private property, the eval needs to use the library that defines the property for the mutation to work.  
 But with mixins, the vm_service gives an incorrect uri. So we don't know where the private property was defined and are unable to update it.


I don't think this can be fixed.

**Comment by rrousselGit** [comment]
Mixins also are a source of problem with https://github.com/flutter/devtools/pull/3006 / #3004 by the way, for the same reasons.

https://github.com/flutter/devtools/pull/3006 relies on checking whether the property's owner URI matches with the name of the inspected application.
But since with mixins, ChangeNotifier._count is said to be defined by the class that mixes-in `ChangeNotifier`, then the property is not considered as "defined by a dependency", so it is visible.

**Comment by jacob314** [comment]
Until we get the mixin issues sorted out how about we disable edits on private properties to be safe. I'd also be happy with disabling edits on all properties by default and only showing it as "experimental: edit property values" in the settings page.

**Comment by kenzieschmoll** [comment]
Seeing this issue again with a different use case. Here I am trying to edit the _value of a ValueNotifier field
<img width="391" alt="Screen Shot 2021-05-13 at 3 06 27 PM" src="https://user-images.githubusercontent.com/43759233/118194075-a0c07f80-b3fd-11eb-90e5-f2c20500b16e.png">
doing so yields this error:
<img width="901" alt="Screen Shot 2021-05-13 at 3 06 33 PM" src="https://user-images.githubusercontent.com/43759233/118194085-a6b66080-b3fd-11eb-96e4-8eabf2ee6f92.png">

Repro steps:
1. run DevTools (A) on the web (this is the test app) *pro tip: change this to light theme so there is no confusion about which app is the debugger and which app is being debugged. 
2. Connect this instance of DevTools to an arbitrary flutter app (this is so that the PerformanceController will show up in the list of providers).
3. run another instance of DevTools (B)(desktop or web, whichever you prefer). 
4. Connect this DevTools to the DevTools web app (A) you launched in step 1).
5. Navigate to the provider page in DevTools (B). You should see the PerformanceController in the list of providers. Try to change the value of the matchIndex notifier as the screenshot shows.

**Comment by elliette** [comment]
Now that the Provider panel is a DevTools extension, I'm closing this issue in favor of https://github.com/rrousselGit/provider/issues/883.
