### ISSUE TITLE
frame tracking code can get out of sync (and possibly not terminate)

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#301]
I've noticed that the code to determine where frames are in the timeline data can get out of sync occasionally; I normally see a symptom of this where we stop producing frames in the timeline UI.

When this happens, we may also not terminate some calculations - I've noticed runaway CPU usage as well. I'm attaching some console output, and a screenshot of the cpu profiler, for one case I noticed.

```
Error - already set startTime 349489449902 for frame e69.
TraceEvent - {name: PipelineItem, cat: Embedder, tid: 47619, pid: 98195, ts: 349489449904, ph: s, id: e69, args: {}}
dart_sdk.js:18331 Error - already set startTime 349489466505 for frame e6a.
TraceEvent - {name: PipelineItem, cat: Embedder, tid: 47619, pid: 98195, ts: 349489466507, ph: s, id: e6a, args: {}}
dart_sdk.js:18331 Error - already set startTime 349487833446 for frame e10.
TraceEvent - {name: PipelineItem, cat: Embedder, tid: 47619, pid: 98195, ts: 349487833449, ph: s, id: e10, args: {}}
dart_sdk.js:18331 Error - already set startTime 349487850857 for frame e11.
TraceEvent - {name: PipelineItem, cat: Embedder, tid: 47619, pid: 98195, ts: 349487850859, ph: s, id: e11, args: {}}
dart_sdk.js:18331 Error - already set endTime 349493988997 for frame f70.
TraceEvent - {name: PipelineItem, cat: Embedder, tid: 81155, pid: 98195, ts: 349493988997, ph: f, bp: e, id: f70, args: {}}
dart_sdk.js:18331 Error - already set endTime 349493998178 for frame f71.
TraceEvent - {name: PipelineItem, cat: Embedder, tid: 81155, pid: 98195, ts: 349493998178, ph: f, bp: e, id: f71, args: {}}
dart_sdk.js:18331 Error - already set endTime 349497921785 for frame 1046.
TraceEvent - {name: PipelineItem, cat: Embedder, tid: 81155, pid: 98195, ts: 349497921785, ph: f, bp: e, id: 1046, args: {}}
```

<img width="635" alt="screen shot 2019-02-16 at 1 27 56 pm" src="https://user-images.githubusercontent.com/1269969/52905450-42d96900-31ef-11e9-9030-17c83010c2d1.png">

cc @kenzieschmoll

**Comment by devoncarew** [comment]
And the console output for another instance:

```
Error - already set endTime 350026186303 for frame 1d.
TraceEvent - {name: DispatchPointerDataPacket, cat: Embedder, tid: 46339, pid: 15964, ts: 350056189232, ph: f, bp: e, id: 1d, args: {}}
dart_sdk.js:18331 Error - already set endTime 350044801687 for frame 26.
TraceEvent - {name: DispatchPointerDataPacket, cat: Embedder, tid: 46339, pid: 15964, ts: 350058631161, ph: f, bp: e, id: 26, args: {}}
dart_sdk.js:18331 Error - already set endTime 350045778996 for frame 27.
TraceEvent - {name: DispatchPointerDataPacket, cat: Embedder, tid: 46339, pid: 15964, ts: 350058631162, ph: f, bp: e, id: 27, args: {}}
dart_sdk.js:18331 Error - already set endTime 350046512025 for frame 28.
TraceEvent - {name: DispatchPointerDataPacket, cat: Embedder, tid: 46339, pid: 15964, ts: 350058631162, ph: f, bp: e, id: 28, args: {}}
dart_sdk.js:18331 Error - already set endTime 350047228077 for frame 29.
TraceEvent - {name: DispatchPointerDataPacket, cat: Embedder, tid: 46339, pid: 15964, ts: 350058631162, ph: f, bp: e, id: 29, args: {}}
dart_sdk.js:18331 Error - already set endTime 350056190321 for frame 30.
TraceEvent - {name: DispatchPointerDataPacket, cat: Embedder, tid: 46339, pid: 15964, ts: 350058631163, ph: f, bp: e, id: 30, args: {}}
dart_sdk.js:18331 Error - already set endTime 350056220994 for frame 31.
TraceEvent - {name: DispatchPointerDataPacket, cat: Embedder, tid: 46339, pid: 15964, ts: 350058631163, ph: f, bp: e, id: 31, args: {}}
dart_sdk.js:18331 Error - already set endTime 350056253125 for frame 32.
TraceEvent - {name: DispatchPointerDataPacket, cat: Embedder, tid: 46339, pid: 15964, ts: 350058631163, ph: f, bp: e, id: 32, args: {}}
dart_sdk.js:18331 Error - already set endTime 350056287050 for frame 33.
TraceEvent - {name: DispatchPointerDataPacket, cat: Embedder, tid: 46339, pid: 15964, ts: 350058631163, ph: f, bp: e, id: 33, args: {}}
dart_sdk.js:18331 Error - already set endTime 350056298003 for frame 34.
TraceEvent - {name: DispatchPointerDataPacket, cat: Embedder, tid: 46339, pid: 15964, ts: 350058631163, ph: f, bp: e, id: 34, args: {}}
```

**Comment by devoncarew** [comment]
I think the CPU usage is independent from getting out of sync with determining frame boundaries. From very brief investigation, it looks like we're sorting frames and events inside some loops, leading to perhaps n^2 or n^3 behavior.

**Comment by kenzieschmoll** [comment]
We were determining frame uniqueness solely based on the flow event id. We could be receiving other flow events that are not matched to the PipelineItem flow events we care about. Each flow event type has its own global counter for ids, so we were seeing collisions between different flow event types. This issue will be solved by including the event name as part of the frame-id (i.e. 'PipelineItem-e45').

This does not completely solve the issue, however. We are receiving duplicate trace events from the engine. Some trace events have identical JSON, and some trace events have almost-identical JSON differing only on the event timestamp. If this delta is small, we will drop the duplicate event silently. If it is not, we will drop the duplicate event and log a warning to console.

**Comment by kenzieschmoll** [comment]
Been digging into this issue and I think I know what is happening.

The events from the engine can come in out of timestamp order. The current logic assumes that nested events will come in in the proper order and we can add child events in this manner. In reality, we can receive CPU events from frame a) while we are processing CPU events from frame b). The timestamps in the trace events are our source of truth for properly nesting children and building each CPU/GPU event tree, so we'll just need to tweak the logic to depend on timestamp.

This complicates the logic, but hopefully we can get some changes in the engine that will simplify this in the future.
