### ISSUE TITLE
Expose value of ValueNotifiers in Provider page

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#3020]
I would expect to be able to see the value of a value notifier by default
<img width="276" alt="Screen Shot 2021-05-13 at 1 56 02 PM" src="https://user-images.githubusercontent.com/43759233/118186900-1c68ff00-b3f3-11eb-838a-6bf515f62ccb.png">
I know this is possible by enabling the setting
<img width="465" alt="Screen Shot 2021-05-13 at 1 57 45 PM" src="https://user-images.githubusercontent.com/43759233/118187023-44586280-b3f3-11eb-9bbf-df086214aaa9.png">
but maybe there are certain classes we should special case for? ValueNotifier being one of them?
@rrousselGit @jacob314

**Comment by elliette** [comment]
Now that the Provider panel is a DevTools extension, I'm closing this issue in favor of https://github.com/rrousselGit/provider/issues/883.
