### ISSUE TITLE
provider field values do not update on changes

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#3022]
In this example, I am looking at the `_value` field of the `matchIndex` ValueNotifier. In the connected app (which is another instance of DevTools running on the web), I perform some interactions that will result in `matchIndex.value` changing. The value displayed in the provider page does not change. If I select a different provider and then come back and re-select the original provider, the correct value is shown in the `_value` field.

<img width="386" alt="Screen Shot 2021-05-13 at 3 08 17 PM" src="https://user-images.githubusercontent.com/43759233/118193977-75d62b80-b3fd-11eb-884e-6172b8746a8e.png">
@rrousselGit @jacob314

**Comment by kenzieschmoll** [comment]
If it is not feasible to listen for changes to a provided object's data, perhaps we could add a force refresh button to allow a user to update the data on the provider?

**Comment by rrousselGit** [comment]
Listening to the objects should be feasible.

I can see the value in a refresh button anyway as users may write custom listenable classes. 

Alternatively, we could try and refresh things every x seconds?

**Comment by elliette** [comment]
Now that the Provider panel is a DevTools extension, I'm closing this issue in favor of https://github.com/rrousselGit/provider/issues/883.
