### ISSUE TITLE
Field value displaying <unknown error> on provider page

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#3023]
<img width="420" alt="Screen Shot 2021-05-13 at 3 32 08 PM" src="https://user-images.githubusercontent.com/43759233/118195686-889e2f80-b400-11eb-95bf-8231e5c835c9.png">

Repro steps:
1. run DevTools (A) on the web (this is the test app) *pro tip: change this to light theme so there is no confusion about which app is the debugger and which app is being debugged. 
2. Connect this instance of DevTools to an arbitrary flutter app (this is so that the PerformanceController will show up in the list of providers).
3. run another instance of DevTools (B)(desktop or web, whichever you prefer). 
4. Connect this DevTools to the DevTools web app (A) you launched in step 1).
5. Navigate to the provider page in DevTools (B). You should see the PerformanceController in the list of provider and see <unknown error> for the above pictured field
@rrousselGit @jacob314

**Comment by elliette** [comment]
Now that the Provider panel is a DevTools extension, I'm closing this issue in favor of https://github.com/rrousselGit/provider/issues/883.
