### ISSUE TITLE
Migrate devtools_app to null safety

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#3025]
devtools_testing and devtools_app depend on one another, so they will need to be migrated and published at the same time.

The following packages need to be migrated before devtools_app can be migrated:

- [x] package:ansi_up (https://github.com/flutter/devtools/pull/3027)
- [x] package:codicon (https://github.com/flutter/devtools/pull/3026)
- [x] package:dds

**Comment by leafpetersen** [comment]
Any plans on this?  cc @jacob314

**Comment by polina-c** [comment]
First tasks:

- [x] move dependencies from root to subfolders (https://github.com/flutter/devtools/pull/3594)
- [ ] update dependencies to null safe (https://github.com/flutter/devtools/pull/3600)
- [ ] migrate primitives

**Comment by polina-c** [comment]
Next tasks:
[ ] migrate shared
[ ] remove `// ignore_for_file: import_of_legacy_library_into_null_safe`

**Comment by polina-c** [comment]
[Gradual Null-Safety Faster](https://docs.google.com/document/d/1bdHO0J00I8tIYBv636nlSTpPUsx1IV4ojxW7Poj8iNE/edit#)

**Comment by polina-c** [comment]
DevTools are sound null safe now.
