### ISSUE TITLE
Provide some padding at the bottom in Details tree list to allow easier mouse click. 

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/devtools#3028]
![image](https://user-images.githubusercontent.com/40364434/118234100-2c382000-b493-11eb-8738-bc580333af48.png)

As you can see in the image, I've already scrolled down to the bottom and due to insufficient padding, it's difficult to click `renderObject` option because horizontal scrollbar also gets activated in doing so.

**Comment by elliette** [comment]
Looks like this was fixed in the above PR.
