### ISSUE TITLE
Surface shader compilation time on the DevTools performance page

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#3043]
Now that some CLs for https://github.com/flutter/flutter/issues/78500 has landed, we should be able to surface ski shader events by adding a flag when a Flutter app app runs to enble tracing `skia.shaders`.
It would be good to surface the total time spent each frame spent on shader compilation so it is very clear just from the chart of frames which of the slow frames were due to shader compilation.
Currently, teams have a lot of difficulty telling whether they have gotten all the benefit from shader caching because they can't immediately tell whether their slow frames are due to shader caching or some other performance issue.

**Comment by jacob314** [comment]
Fyi @kenzieschmoll

**Comment by kenzieschmoll** [comment]
Do we have specific information on what the shader trace events will look like, and if not, who should we loop in to find out? Maybe @jason-simmons? 

Will shader time also be added to the Flutter.Frame events coming from the framework? @jonahwilliams

**Comment by jonahwilliams** [comment]
I believe this would only show up in engine trace events and not the frame timings

**Comment by kenzieschmoll** [comment]
Engine trace events meaning the events that come on the Raster thread (same as GPU::RasterizerDraw events and similar)? If we can pull the data from there, that should be sufficient once we have the frame ids included in the Flutter.Frame events (https://github.com/flutter/flutter/issues/80735).

**Comment by kenzieschmoll** [comment]
@jason-simmons is going to add a flutter run flag `--trace-skia-allowlist` to support an easy option for turning these trace events on. 

@jonahwilliams @iskakaushik what would it take to get the shader time per frame piped into the Flutter.Frame events? I know this was just done for frame ids - would it also be possible to make shader time part of the frame timing api?

**Comment by iskakaushik** [comment]
@kenzieschmoll this would require that we have the ability to pass additional args to skia trace events, @jason-simmons is that possible? We would need to add `frame_number` as an argument with value `FrameTimingsRecorder->GetFrameNumberTraceArg()` to the relevant timeline events.

@kenzieschmoll , If that is not possible, we would have to either:

1. Have skia return the stats about shader compilation in a consumable way to the Flush/Raster operations in rasterizer so we could capture them in the `FrameTimings` object to send it back to the framework and then devtools.
2. Devtools will have to use some heuristics to infer the frame number from the nearest `GpuRasterizer::Draw` trace event which would have the `frame_number` trace arg.

**Comment by jonahwilliams** [comment]
would it be sufficient to count all timeline events between frameStart events as part of the last frame number? This could be done for the framework too based on Flutter.frame events. Now that they have the same frame number you don't need to compare timestamps across timelines.

that should be fairly straightforward - I don't think we can or should add a frameNumber to every single timeline event

**Comment by kenzieschmoll** [comment]
In order to group all skia.shader events together in the timeline, we will need https://github.com/flutter/flutter/issues/83835 to be resolved.

**Comment by kenzieschmoll** [comment]
@jonahwilliams @jason-simmons @iskakaushik What trace events should we be expecting to see relating to skia shaders? I am running this app (https://github.com/timsneath/cupabox - if you have a better sample app to show skia shader issues, please let me know), and I'm running the app with the flag `--trace-skia-allowlist=skia.shaders,skia.gpu`, but I'm not seeing any timeline events that scream "you have a problem with shader compilation time".

**Comment by jason-simmons** [comment]
If you zoom in on the initial DoMakeRasterSnapshot and GPURasterizer::Draw event trees on the raster thread, then you should see some shader_compile events toward the bottom.

The events might be more noticeable if you run something more complex like Gallery.

**Comment by kenzieschmoll** [comment]
Here is a timeline trace from flutter gallery. I see the `DoMakeRasterSnapshot` event, but not any shader_compile events (note: remove .txt extension to import into DevTools - workaround to attach json to github message).
[dart_devtools_2021_6_8-1623192100682469.json.txt](https://github.com/flutter/devtools/files/6619981/dart_devtools_2021_6_8-1623192100682469.json.txt).

Once flutter/flutter#83835 is fixed, we'll be able to better call these events out in DevTools so that we aren't string matching on event names.
