### ISSUE TITLE
Improve debugger file search UX

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#3075]
From an internal user:

The current fuzzy search experience has some usability issues.

1. The expand if < 5 results often times hides useful information due to repeated matches from generated files
2. Folders do not stay expanded on new search

We should try to take better advantage of the space and save the user a click when possible,

ex1) always show the top X results from each folder expanded with show more... as the final options.
ex2) dont seperate by folder

**Comment by kenzieschmoll** [comment]
After an offline discussion, here are some improvements we will make to the libraries pane, search experience, and history picker
- [ ] remove filter text field from libraries view
- [ ] (internally) add edited files to the top of the libraries view with a subheader and a separator between those files and the rest
- [ ] convert the libraries view to be a tree file explorer
- [ ] search will become a hotkey (cmd + p or cmd + o) that launches a modal dialog where a query can be entered and search results will be populated for the user to select
- [ ] remove duplicate entries in history picker
- [ ] color edited files a different color (maybe blue like IntelliJ) in the libraries pane and history picker

**Comment by kenzieschmoll** [comment]
The remaining work for this is tracked at https://github.com/flutter/devtools/issues/3383 and https://github.com/flutter/devtools/issues/3418. Closing.
