### ISSUE TITLE
create and document a release process for devtools

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#308]
Perhaps similar to what we use for flutter-intellij now, where we choose a reasonable commit, branch into a named release branch (`release_12`), and publish from that branch?

Once we come up with something reasonable, we should document it, and try and automate some steps of it.

**Comment by kenzieschmoll** [comment]
@devoncarew, is this resolved?

**Comment by devoncarew** [comment]
Looks like https://github.com/flutter/devtools/blob/master/tool/publish.sh exists; not sure the docs are there, but enough is done that we can close this out.
