### ISSUE TITLE
Devtool does not connect to device in Windows 10

### ISSUE THREAD

**Issue by parmarravi** [flutter/devtools#3080]
How to fix the issue?

![image](https://user-images.githubusercontent.com/7616089/120598900-742fde80-c464-11eb-92f4-c3bcf5fe680a.png)

**Comment by kenzieschmoll** [comment]
How are you launching DevTools? Looks like you are on an outdated version. The latest DevTools version is 2.2.4

**Comment by parmarravi** [comment]
Same problem with  2.2.4
I am launching via android studio 

![image](https://user-images.githubusercontent.com/7616089/120671346-ecbb8d00-c4ae-11eb-9db6-9c4cb9f05d0f.png)

**Comment by parmarravi** [comment]
Found the problem.!! 

In the android studio, there are two different IP address that comes.
One is in the Logcat console and the second is in the run console. 

We need to pick the Ip address in Run Console and not from the Logcat Console.
I don't know how both Logcat and run console end up with two different addresses.

This solved my issue and now I can debug the app easily thank you for such an amazing tool.

**Comment by kenzieschmoll** [comment]
glad you resolved your issue. FYI if you are running your app from Android Studio, you can open devtools automatically connected to your app by clicking the Dart icon in the run/debug console:

![Screen Shot 2021-06-03 at 11 19 52 AM](https://user-images.githubusercontent.com/43759233/120693381-c7eaf980-c45d-11eb-9ab4-7a86662f749a.png)
