### ISSUE TITLE
Extra scrollbars on the performance page

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#3092]
If you hover over the next previous block icons on the performance page can see a spurious scrollbar.
![Screen Shot 2021-06-07 at 8 54 40 AM](https://user-images.githubusercontent.com/1226812/121051473-57e6b700-c76e-11eb-8369-08bc29e89605.png)

**Comment by kenzieschmoll** [comment]
I can't repro this. Can you provide more detailed steps on how you are producing this issue?

**Comment by Piinks** [comment]
I have been poking around checking out some scrolling issues in my quest to  resolve https://github.com/flutter/devtools/issues/2012. 😜 

This might be an orphan scrollbar added by the ScrollBehavior on desktop.
There are a lot of custom implementations of scrolling widgets here, so I am not certain if this could be the case, but here's a reference if it helps: https://flutter.dev/docs/release/breaking-changes/default-desktop-scrollbars

**Comment by kenzieschmoll** [comment]
Closing since we now use the Perfetto trace viewer.
