### ISSUE TITLE
Autcomplete polish burndown list

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#3095]
Autocomplete is close to being done but there a few more edge cases that should be polished.
![autocomplete_demo](https://user-images.githubusercontent.com/1226812/121062950-94201480-c77a-11eb-82e9-b1774cdb8aa5.gif)
- [x] The autocomplete card should be aligned with the period, not the cursor. This is how Chrome and other IDEs render their autocomplete options.
- [x] The current autocomplete match should be show in grey directly in the text box as well as in the autocomplete list.
- [x] Autocomplete is slow for very large classes https://github.com/flutter/devtools/issues/3089
- [x] Reduce padding between list items.

**Comment by TimWhiting** [comment]
I would suggest having less padding as well for the list items. (Similar spacing to VSCode or Intellij).
