### ISSUE TITLE
analytics is not sending the user ID with the analytics ping

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#3102]
It does not appear as though analytics is sending the user ID with the analytics ping.

I believe there's some low hanging fruit in the analytics implementation wrt simplifying the implementation.

**Comment by devoncarew** [comment]
Perhaps the `gtag()` library is using its own client ID? If so, this would be cached in the browser - not something that's persisted to disk. That might be already for our purposes. We'd just want to make sure that many sessions for a user were grouped together? I.e., that not every session appeared like a unique users.

**Comment by devoncarew** [comment]
cc @terrylucas, who likely has the most context here

**Comment by kenzieschmoll** [comment]
Closing as obsolete with the switch to unified_analytics
