### ISSUE TITLE
Consider surfacing some metrics for shader cache usage in DevTools

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#3141]
Possible metrics:
What % of your shader were actually pre-cached? This helps you understand what fraction of the way you are to precaching all the shaders you care about to reduce jank.
What percent of the shaders in your cache were actually used. This helps you understand the difference between "I have an enormous shader cache because I am caching a ton of shaders that don't actually matter on startup" and "I have an enormous shader cache because my app uses a lot of shaders".

Fyi @xster @kenzieschmoll

**Comment by kenzieschmoll** [comment]
This is obsolete with the Impeller effort.
