### ISSUE TITLE
Debug toggle buttons redesign proposal

### ISSUE THREAD

**Issue by CodemateTechAgency** [flutter/devtools#3144]
# Overview

Hello, here are the Codemate team's initial suggestions for redesigning the debug toggle buttons.

We initially interviewed several of our own developers, including some unfamiliar with Flutter or the DevTools, to understand how well they understood the current design.

There were some toggles that almost nobody fully understood, including developers familiar with Flutter. We've used their feedback to guide our redesign.

For each debug toggle we provide a summary of our findings from interviewing users, and a proposal for a new design.

# Proposal

We propose making the icons monochrome and more legible, and grouping the buttons together:

![Screenshot 2021-06-17 at 13 20 40](https://user-images.githubusercontent.com/82218649/122461485-164edb00-cfbc-11eb-8c7b-5ed8c7275952.png)

## **Slow Animations**

**Findings:** all users we interviewed fully understood what this toggle does without requiring any additional explanation.

**Proposal:** change the clock icon to a stopwatch. Not a huge change, but we feel this reflects a bit more of the “toggling time” intention of the action.

<img src="https://user-images.githubusercontent.com/82218649/122461899-99703100-cfbc-11eb-9e7b-b36e3c4bc0ef.png" height="50">

## **Debug Paint**

**Findings:** users found it extremely hard to guess what this button does; guesses included believing it would be used to find performance issues. Once enabling it, users found the visual guidelines overwhelming, and found it difficult to understand that the various colors, borders and arrows represent. They also found it hard to understand what the guidelines would be useful for.

**Proposal:** change the icon to be simpler and more legible, rename the action to “Show Guidelines” to better describe the functionality.

<img src="https://user-images.githubusercontent.com/82218649/122462023-bf95d100-cfbc-11eb-8c0e-24e15ed9713b.png" height="50">

For further improvements outside the current scope, we propose finer-grained control of which guidelines to show; this would require adding functionality to the Flutter framework:

<img alt="Screenshot 2021-06-18 at 19 01 27" src="https://user-images.githubusercontent.com/82218649/122588391-b6157300-d067-11eb-9854-8a89600b0f14.png">

## **Paint Baselines**

**Findings:** users who were familiar with the concept of font baselines understood this function, but several were unaware of what baselines are, so didn't understand the meaning of this button. Developers struggled with understanding what this function is useful for.

**Proposal:** change the icon to a clearer version to more clearly indicate that this relates to text, especially to guide users unfamiliar with the concept of baselines. Change the wording to “Show Baselines”.

<img src="https://user-images.githubusercontent.com/82218649/122462233-071c5d00-cfbd-11eb-8477-8647903d78f7.png" height="50">

## **Repaint Rainbow**

**Findings:** this was the least-understood debug toggle from just looking at the button. Users had many ideas on what it might do, but almost nobody guessed correctly. After toggling it, most users could guess the functionality.

**Proposal:** change the icon to a one that better illustrates the functionality. Rename the action to “Highlight Repaints”, since that is what it actually does. Rainbow describes the visual effect of the overlay, not the action itself. Alternative name suggestions are “Colorize Repaints” or “Show Repaints”.

<img src="https://user-images.githubusercontent.com/82218649/122462289-16030f80-cfbd-11eb-9202-5c8206f1d7b5.png" height="50">

## **Invert oversized images**

**Findings:** most users roughly guessed the functionality, but not all were sure what “oversized” means. Some thought it might be to do with images being visually clipped (e.g. an image partially hidden behind another widget).

**Proposal:** keep the current icon, but change the label to “Highlight oversized images”, to better describe why the action is used - to spot oversized images.

<img src="https://user-images.githubusercontent.com/82218649/122462382-329f4780-cfbd-11eb-9f22-3246f41b7968.png" height="50">

# Tooltips

![tooltips](https://user-images.githubusercontent.com/82218649/122462436-421e9080-cfbd-11eb-891e-ab1f1d7fe3a3.png)

To aid users with functionality, we propose adding rich tooltips with links to documentation.

These would show after a short delay, explaining what the functionality exactly does, and ideally give an example of what that functionality is useful for. The links would go to expanded documentation on flutter.dev, with solutions and code examples of how to fix problems found with the tools.

For example, the Show Baselines tooltip would be something like:

> "Shows the baselines of text
>
> Baselines are horizontal lines that are used to layout text. This option can be useful for checking whether text is aligned vertically.
>
> [More info...](https://flutter.dev/docs/development/tools/devtools/inspector)"

We need to strike a good balance between these tooltips being informative, but not a distracting large wall of text. 

We'd love feedback on these suggestions! In the meantime we are working on our suggested content for the tooltips and the  documentation for these toggles.  

Thanks
Tom, Olli and Alex at Codemate

cc @inmatrix, @csells, @jacob314

_Edit June 18th: fix spelling on dropdown screenshot_

**Comment by jacob314** [comment]
Proposals look good overall. In the future, I would find it helpful to see screenshots of the old UI next to the screenshots of the proposed replacements.

**Comment by csells** [comment]
+1. That was my exact feedback -- would love to see before/after.

**Comment by timsneath** [comment]
This is a great initial proposal. One question I had -- how will this appear in a more horizontally-constrained environment (e.g. a VSCode half pane where there is less than half of the overall screen width available)? Does it collapse into some kind of breadcrumb bar? Do lower priority buttons collapse to icon only?

**Comment by InMatrix** [comment]
I like how you made the button labels more about the user's goal and less about the specific mechanisms (e.g., showing a rainbow for repaints or inverting large images). 

The changes proposed to Debug Paint might require more discussion for a few reasons:

* The name "debug paint" might be used elsewhere (e.g., the IDE and the command line tool). We need to make sure the changes are coordinated.
* The "show guidelines" label reminds me of the "guides" in image editing tools and slides making apps for aligning objects. Is it intended to invoke this analogy? Does this analogy hold for all use cases of this feature? And finally should we call them "guidelines" or "guides?" Maybe @sfshaza2 can weigh in on the word choice here. 
* I think a finer-grained control of which guidelines to show makes a lot of sense. However, I'm not sure about the technical feasibility. @jacob314 Can you advise on this? 

And +1 to the rich tooltips. This is something we need in many areas of DevTools ([example](https://github.com/flutter/devtools/pull/3125#discussion_r651961756)). We need to coordinate on how to implement this. Cc: @kenzieschmoll

**Comment by CM-Olli** [comment]
Here's a quick old vs. new -screenshot:

![Screenshot 2021-06-18 at 10 20 08](https://user-images.githubusercontent.com/86104144/122540111-f86f8d80-d030-11eb-8d55-aa25c1a08ace.png)

**Comment by CM-Olli** [comment]
...and here's a tighter layout. My initial thought is that i'd collapse them all at once, when screen gets too narrow for the full version. You'll learn to recognize them quickly, and the tooltip would be there to help too.

![ide](https://user-images.githubusercontent.com/86104144/122569755-b9066880-d053-11eb-9ade-d44cc3290f52.jpg)

**Comment by tomgilder** [comment]
Thanks for the great feedback! We'll make sure to post before/after designs in the future. 

> You'll also want to familiarize yourselves with the Google style guide (e.g. title case or sentence case? is the use of ampersand appropriate in "Margins &amp; Paddings"?) I also noticed a spelling nit ("Clickable", not "Clicable").

Good spot, have fixed the screenshot, thanks.

> The name "debug paint" might be used elsewhere (e.g., the IDE and the command line tool). We need to make sure the changes are coordinated.

Yes, in VSCode the command is "Toggle Debug Painting" and Android Studio it's "Show Debug Paint". And the repaint overlay is "Repaint Rainbow" in both, too.

The Android Studio plugin also uses some of the same icons as DevTools, I assume it would nice to update those in sync? Only issue is AS toolbars mostly have colour icons, whereas we're proposing monochrome:

<img width="320" alt="Screenshot 2021-06-18 at 19 27 19" src="https://user-images.githubusercontent.com/756862/122591136-34274900-d06b-11eb-8b1f-e37d20ba89e4.png">

> And +1 to the rich tooltips. This is something we need in many areas of DevTools (example). We need to coordinate on how to implement this.

I've made an early prototype of rich tooltips, mostly based on Flutter's `Tooltip` widget, but it needs quite a lot more work. Happy to continue on it, but obviously don't want to duplicate work. Here's what it currently looks like (doesn't yet have Olli's design input):

https://user-images.githubusercontent.com/756862/122590426-34731480-d06a-11eb-9125-8958c95fdd67.mov

**Comment by InMatrix** [comment]
> The Android Studio plugin also uses some of the same icons as DevTools, I assume it would nice to update those in sync? Only issue is AS toolbars mostly have colour icons, whereas we're proposing monochrome:

Do we plans to replace the Swing-based inspector with the Flutter-based one in IntelliJ? @jacob314

**Comment by InMatrix** [comment]
@tomgilder @CodemateTechAgency Have you considered the "enabled" state for the toggle buttons and their labels? It's not every easy to tell from the existing design:  
![image](https://user-images.githubusercontent.com/348942/122835886-0f6ae580-d2a6-11eb-9389-3477c72e6c17.png)

**Comment by jacob314** [comment]
There is a rich tooltip in DevTools used for hover of values in the DevTools debugger. `HoverCardTooltip`
The default in IntelliJ is to use the Inspector from DevTools embedded in IntelliJ. We will soon remove the legacy swing based code for the inspector.

**Comment by CM-Olli** [comment]
> @tomgilder @CodemateTechAgency Have you considered the "enabled" state for the toggle buttons and their labels? It's not every easy to tell from the existing design:

Yes, here are the screenshots:

![Screenshot 2021-06-22 at 19 11 38](https://user-images.githubusercontent.com/86104144/122962081-b8404000-d38d-11eb-9565-7585c9ba1b6f.png)
![Screenshot 2021-06-22 at 19 09 56](https://user-images.githubusercontent.com/86104144/122962085-ba0a0380-d38d-11eb-8929-f5688e737897.png)

**Comment by InMatrix** [comment]
We discussed this proposal in our team meeting today, attended by @devoncarew @jacob314 @kenzieschmoll @helin24 and a few others. In general, we think the proposed UI changes are good to go with a few follow-up comments:

- Selective enabling of debug paints requires changes in the Flutter framework. It's unclear how much effort is required. I've [asked about this](https://discord.com/channels/608014603317936148/608021234516754444/857369506548547596) in the framework channel in Flutter's Discord server. Unless you've done some investigations, we can table this until we learn more from the framework engineers.  
- Please post actual copies for the button tooltips for review. The project scope also includes updates to relevant docs linked from the tooltips to teach developers how to use those features. You could either submit proposed changes as a Github issue or submit a preliminary PR for relevant pages on flutter.dev.

**Comment by tomgilder** [comment]
Thanks @InMatrix, I don't think the actual change in the Flutter framework would be the large, but adding different flags might have a wider affect on IDEs and plugins that would need coordinating?

Below are our proposals for tooltips. They would all have a "more info" link to the documentation.

For the draft documentation, are you happy with a public Google doc where we can collect comments, before making it into a PR?

## Tooltips

**Slow Animations**
> "Run animations slower to help fine-tune them."

**Show Guidelines**
> "Draw a debugging overlay on your app.
> 
> Shows paddings, scroll views, clippings and render boxes."

**Show Baselines**
> "Show the baseline of all text widgets. Useful for aligning multiple text widgets."

**Colorize Repaints**
> "Show borders that change color when elements repaint. Useful for finding unnecessary repaints."

**Invert Oversized Images**
> "Highlight images that use more memory than necessary by turning them upside down and inverting their colors."

**Comment by InMatrix** [comment]
> Thanks @InMatrix, I don't think the actual change in the Flutter framework would be the large, but adding different flags might have a wider affect on IDEs and plugins that would need coordinating?

Yes, according to the answer I got from the Framework discord chat channel, different layers of debug paints are controlled by different flags. So it might not be hard to implement the proposed checkboxes UI after all. I'm not particularly worried about coordination with IDEs here. We can sort them out later. 

> For the draft documentation, are you happy with a public Google doc where we can collect comments, before making it into a PR?

Yes, that's a good idea. I assume you already know where to find the template for Flutter's public design docs? 

Since you plan on doing that, could you include the copies of the button tooltips in that doc as well, so they can be reviewed together with the associated docs?

**Comment by tomgilder** [comment]
Hi all

Here’s a public Google Doc with both tooltip text and documentation: https://docs.google.com/document/d/1xBJpVykI7-UYP61MX6bKZMl6awQwNvEc3jurDjSZEVE/ - you should be able to comment on it directly.

PR open here for the initial button text and icon changes: https://github.com/flutter/devtools/pull/3167. I'll do the tooltips as a separate PR; I’m using the existing HoverCard but adding functionality to them. Might need to discuss how the positioning of the tooltips work, material guidelines call for them being centred but it feels a bit strange to me.

cc @InMatrix, @csells, @jacob314
