### ISSUE TITLE
frame start time seems suspicious

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#315]
The frame start time occasionally seems suspicious:

<img width="1361" alt="screen shot 2019-02-20 at 1 29 06 pm" src="https://user-images.githubusercontent.com/1269969/53125787-99a6b180-3513-11e9-9625-c4214d0a5854.png">

above, the frame time starts in the middle of the presented frame.

cc @kenzieschmoll

**Comment by kenzieschmoll** [comment]
Haven't seen any repros since https://github.com/flutter/devtools/pull/394. Feel free to re-open if new cases come up.
