### ISSUE TITLE
CupertinoApp layout not showing up in the Layout Explorer

### ISSUE THREAD

**Issue by muddi900** [flutter/devtools#3151]
Pretty self explanatory. When I click on the widget in DevTools, the layout explorer is blank. I have tested it on VS Code and in Chrome.

**Comment by kenzieschmoll** [comment]
Can you add a screenshot? That would help us to understand the state of your widget tree

**Comment by muddi900** [comment]
![image](https://user-images.githubusercontent.com/37051110/123505379-321b4680-d678-11eb-9458-c3282ea185d9.png)

I have selected the icon and no LayoutInfo is showing up.

**Comment by kenzieschmoll** [comment]
@jacob314

**Comment by muddi900** [comment]
This issue happens on both Windows and MacOS. And regardless of if I am using Android Emulator or iOS simulator.

**Comment by muddi900** [comment]
Is there a update on this? Working blind is a pain.

thank you

**Comment by kenzieschmoll** [comment]
@jacob314 do you know why the layout explorer would be blank for Cupertino app layouts? do we have tests that test Cupertino widgets?

**Comment by mgesmundo** [comment]
Nothing about this?

**Comment by elliette** [comment]
I'm unable to reproduce this with the Cupertino widgets in the Flutter gallery:

<img width="781" alt="Screenshot 2024-10-24 at 1 50 08 PM" src="https://github.com/user-attachments/assets/ff1b41a1-6c65-4d20-a001-2bb3a460aa3b">

If you are still experiencing this, please reopen with a code sample we can try. Thanks!
