### ISSUE TITLE
Showing only the [root] not jumping back to source when clicking any widget from detailed view

### ISSUE THREAD

**Issue by NishantSinghh** [flutter/devtools#3153]
Hi, 

I am using flutter 1.24.0-10.2.pre for a web based application trying to use the locators using flutter inspector but when trying to find the details and want to go back to source its not working.  Only the [root] is displaying and in detailed view when clicking on any widget I am not navigating back to the source code.
Please help.

<img width="460" alt="Screenshot 2021-06-22 at 5 09 22 PM" src="https://user-images.githubusercontent.com/11394228/122918963-52e45300-d37d-11eb-8ca0-da267efb5dde.png">

**Comment by kenzieschmoll** [comment]
Can you try to upgrade your flutter to the latest stable 2.2.2?

CC @jacob314

**Comment by NishantSinghh** [comment]
@kenzieschmoll Thanks for reply but I can't upgrade the flutter. So need to have some solutions if its possible with the same version.

**Comment by kenzieschmoll** [comment]
Can you open DevTools in the browser and see if there are any errors in the Chrome dev console?

**Comment by NishantSinghh** [comment]
@kenzieschmoll Thanks for the suggestion and I have tried using DevTools on browser So here are my observation
On Android Studio IDE
1. When ran the application directly using command "flutter run -d chrome" I am able to view the expected tree widget instead of only [root]
2. When ran the application using the "Run" button on android studio getting the same only [root] object on the inspector view and as suggested by @kenzieschmoll  there are error on Chrome dev console as well 
`Unrecognized error: evaluate: (-32603) evaluate: Unexpected error from chrome devtools:
text: Uncaught
exception:
  description: SyntaxError: Unexpected token '('
  type: object
  value: null
attempted JS eval: `(function() {
     var sdkUtils = require('dart_sdk').dart;
   var library = sdkUtils.getLibrary('package:flutter/src/widgets/widget_inspector.dart');
   if (!library) throw 'cannot find library for package:flutter/src/widgets/widget_inspector.dart'; .....`
   
Workaround used VS code editor in VS code editor flutter inspector working perfectly fine.

**Comment by jacob314** [comment]
Fyi @annagrin it appears something has regressed in eval and evaluating the large expression for the inspector is now triggering a JavaScript syntax error.

**Comment by annagrin** [comment]
@jacob314 @kenzieschmoll @NishantSinghh Flutter inspector need support for `VMService.evaluate()` API that the web debugger only started supporting on the version demonstrated at google.io - I believe it is Flutter 2.2.

**Comment by kenzieschmoll** [comment]
Closing as obsolete.
