### ISSUE TITLE
devtools can't open the service URL that flutter tools prints

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#3158]
When you run an app from the command line (`flutter run`), it prints the following text:

```
The Flutter DevTools debugger and profiler on iPhone 12 Pro Max is available at:
http://127.0.0.1:9101?uri=http%3A%2F%2F127.0.0.1%3A56142%2FHOwgrxalK00%3D%2F
```

When you try and copy and paste the given url into an existing DevTools instance, in the initial connect page, the given url doesn't work - we can't resolve it to a service protocol uri. You have to know to copy the portion after the `...9101?uri=` into the connect field. We should:

- have flutter tools print a more user friendly url - for the one above, the service protocol url is itself uri encoded. We'd want something like `'http://127.0.0.1:9101?host=127.0.0.1&port=56142&token=HOwgrxalK00'`
- have the DevTools app understand the host, port, and token url parameters and know how to then create the service protocol ws: uri
- special case a devtools url (look for `?uri=http`) and paste the bits after the equals

**Comment by devoncarew** [comment]
cc @jonahwilliams wrt the extra encoded service url appended to the devtools uri; we should make that printout a bit cleaner (through, that will take some upstream work in how devtools processes the uri params).

**Comment by jonahwilliams** [comment]
I could un-format things so they come out more normal looking. Let me try that

**Comment by devoncarew** [comment]
I have a DevTools PR which will let us do: `'<devtools uri>?port=xxx&token=yyy'` - that should clean up the URI quite a bit.
