### ISSUE TITLE
display information about widget rebuild and repaint counts

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#3163]
We should display information about widget rebuild and repaint counts. The Flutter IntelliJ plugin has this capability - we should add this to DevTools as well. The likely steps are:

- expose a toggle (on the Performance page?) to enable widget rebuild counts
- collect the resulting rebuild/repaint events - one per frame - and accumulate the counts; clear them out whenever we get a reload or restart event
- display the information somewhere - as per frame info? - in the performance page

Once we have a steel thread through in terms of collecting and displaying the information, we should iterate on where and how the best way to display the info is. 

cc @kenzieschmoll @jacob314 @InMatrix

**Comment by jacob314** [comment]
Exposing on the performance page SGTM.
I could see a version of the performance page for Flutter Web that just showed these counts along with the overall frame timing being useful.

Just showing the same table of aggregated stats like in intellij seems reasonable. We do get a fair amount of positive feedback about those stats helping users catch issues where they did something very inefficient. 


Displaying as per frame info would be interesting. We didn't have a clickable per-frame graph in IntelliJ. One catch is we'll need to make sure we can associate the counts with the correct frame. We might need to add a frame id to the event dispatched by package:flutter.

**Comment by kenzieschmoll** [comment]
This is complete
