### ISSUE TITLE
Devtools Performance and CPU activity not working and shows Empty

### ISSUE THREAD

**Issue by ObranS** [flutter/devtools#3184]
Dart devtools not working neither Chrome nor Mozila.

I tried to test app with devtools but no info wasn't displayed on the screen (Performance, CPU) for except Memory but I can see Performance on IntelliJ widget.

Additionally I tried to downgrade version and clean browser data but still doesn't work. I've used terminal and IntelliJ to run and use Debug and Profile mode but both shows the same empty screen.

Screenshots attached.

<img width="408" alt="Screenshot 2021-07-06 at 12 21 40" src="https://user-images.githubusercontent.com/5585509/124576209-c2b20d80-de54-11eb-8a28-40a64caf17d0.png">
<img width="1680" alt="Screenshot 2021-07-06 at 12 20 16" src="https://user-images.githubusercontent.com/5585509/124576223-c5146780-de54-11eb-90fd-a99d0d5a0044.png">
<img width="1676" alt="Screenshot 2021-07-06 at 12 20 54" src="https://user-images.githubusercontent.com/5585509/124576230-c6de2b00-de54-11eb-88d7-3e114861e814.png">

❯ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale
    en-GB)
    • Flutter version 2.2.3 at /Users/newfire/flutter
    • Framework revision f4abaa0735 (5 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/newfire/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (2 available)
    • iPad (mobile)  • ios
      • iOS 14.6
    • Chrome (web)  • chrome                                   • web-javascript
      • Google Chrome 91.0.4472.114

**Comment by jacob314** [comment]
Are there any exceptions in the chrome console? Clicking the export button on the Performance page may also help us repro.

**Comment by kenzieschmoll** [comment]
It also looks like you are on an old version of DevTools. You can see what version of DevTools you are on by clicking the question mark help icon in the top right corner of DevTools. The latest is 2.4.0.

**Comment by kenzieschmoll** [comment]
Closing as stale.
