### ISSUE TITLE
Flutter Inspector , Profile Issues not Shown in Dart Dev Tools in VS Code

### ISSUE THREAD

**Issue by Kiran-Khadka** [flutter/devtools#3194]
When I opened the dart dev tools in VS code, the web-browser does not display the Flutter Inspector and other options. 
How to resolve it? Any suggestions. :)

![image](https://user-images.githubusercontent.com/63924970/125188229-c7126800-e252-11eb-8b9b-ef18ee88d23e.png)

**Comment by kenzieschmoll** [comment]
Is this screenshot taken from within VS code? (i.e. is this an embedded version of DevTools? CC @DanTup

**Comment by DanTup** [comment]
As well as the above, could you also confirm:

- What version of the Flutter SDK you're using
- What version of the Dart extension for VS Code you're using
- Exactly how you launched DevTools from VS Code

Thanks!

**Comment by Kiran-Khadka** [comment]
Well, Actually I found later, I was not running the application in debugging mode. That's why the dart dev tools were not provided with multiple options. Later it work on. 

Thanks for reaching out. :)

**Comment by DanTup** [comment]
@Kiran-Khadka if that's the case, maybe it could be made clearer. If you can share instructions on how you got to this point, I can see if we can handle it better in VS Code. Thanks!
