### ISSUE TITLE
testWidgetsWithWindowSize does not play well with tester.tap

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#3196]
When using `initializeLiveTestWidgetsFlutterBindingWithAssets` to use the `LiveTestWidgetsFlutterBinding` and `testWidgetsWithWindowSize`, something goes wrong with computing offsets that breaks `finder.tap` break unittests that need to tap on widgets.

**Comment by jacob314** [comment]
This worked at one point with Flutter but regressed.

**Comment by kenzieschmoll** [comment]
We use `initializeLiveTestWidgetsFlutterBindingWithAssets` and `tester.tap` in several Inspector test, so this regression must have been fixed. Closing.
