### ISSUE TITLE
Provider related null safety error when building DevTools

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#3200]
Seeing this whenever building DevTools from the latest flutter.

```
../../../../.pub-cache/hosted/pub.dartlang.org/provider-5.0.0/lib/src/inherited_provider.dart:391:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!.addPostFrameCallback((_) {
```
cc @rrousselGit

**Comment by rrousselGit** [comment]
How did you get this warning?

SchedulerBinding.instance is nullable both on the stable and master channels https://github.com/flutter/flutter/blob/81c91924f026465c9ba9ee2a370da46cb3231840/packages/flutter/lib/src/scheduler/binding.dart#L311

**Comment by kenzieschmoll** [comment]
I'm just building DevTools on the MacOs target. Haven't tried chrome. I've also seen this on a couple sample apps so I don't think it is specific to DevTools.
```
Flutter 2.4.0-5.0.pre.31 • channel master • git@github.com:flutter/flutter.git
Framework • revision e2490f2906 (27 hours ago) • 2021-07-13 12:41:03 -0700
Engine • revision c74f25f4cb
Tools • Dart 2.14.0 (build 2.14.0-309.0.dev)
```

**Comment by rrousselGit** [comment]
Do you still have the warning? I think it can be closed now, as `provider` is not using `SchedulerBinding` anymore
