### ISSUE TITLE
Performance page toggle button icons need to be updated

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#3206]
The improvments to the Inspector toggle buttons
<img width="336" alt="Screen Shot 2021-07-19 at 9 04 01 AM" src="https://user-images.githubusercontent.com/43759233/126191609-f7146bbc-c262-46ba-8bee-c741e3f2d9b1.png">

 had side effects on the toggle buttons on the performance page:
<img width="382" alt="Screen Shot 2021-07-19 at 9 07 43 AM" src="https://user-images.githubusercontent.com/43759233/126191760-1246b461-b155-44f5-9e07-fb4e66ba88e3.png">

The icons are still using color on the performance page, which makes them difficult to see with the blue highlight color. These icons should be updated.

**Comment by tomgilder** [comment]
These icons have now been updated in the rich tooltips PR #3183

Updated icons look like this:

<img width="385" alt="Screenshot 2021-07-27 at 16 59 20" src="https://user-images.githubusercontent.com/756862/127167360-14cd0c04-d371-4126-bec5-601aa813a8c1.png">
<img width="384" alt="Screenshot 2021-07-27 at 16 59 15" src="https://user-images.githubusercontent.com/756862/127167367-3e4b74d1-50a1-4424-873a-9643f09219c7.png">
<img width="388" alt="Screenshot 2021-07-27 at 16 59 08" src="https://user-images.githubusercontent.com/756862/127167370-55471b30-6302-4bba-8c1f-cf240607159e.png">
<img width="389" alt="Screenshot 2021-07-27 at 16 58 51" src="https://user-images.githubusercontent.com/756862/127167372-76235c00-3715-409b-81f0-bb442e427a9d.png">
