### ISSUE TITLE
Update embedded mode to include navigation to switch between pages

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#3210]
Currently the embedded view shows only a single page. The intention was for the editor to embed a view-per-tab for better integration. This turned out to be a bit of a maintenance issue because the editor needs to know about all tabs and doesn't know which are valid for the app.

The best option is probably to simplify this and have editors just embed a single "DevTools" view and have a nav inside the view to move between pages. This might not differ significantly from embedding the whole view, but we probably want to avoid large headers or any functionality that significantly overlaps with what's already visible in the editor.

@helin24 does IntelliJ use the &embed= argument for embedding the inspector or is it just embedding the whole of DevTools? If the former, this might impact it (but perhaps in a good way if the goal is to expose the other pages that currently are not available).

**Comment by helin24** [comment]
IntelliJ uses embed= for the inspector only. We similarly intended for the embedding to be for particular tabs only, e.g. the tabs are managed by the plugin and the "inspector" title is displayed as part of the plugin not the browser. I don't see a problem with making DevTools generally available though.

**Comment by DanTup** [comment]
> We similarly intended for the embedding to be for particular tabs only, e.g. the tabs are managed by the plugin and the "inspector" title is displayed as part of the plugin

This is what VS Code does today, though some concerns were:

- Don't know which tabs are actually valid for the app without repeating a lot of conditions from DevTools in the editor (eg. when you run a Dart CLI app we still have a command to open the Widget Inspector) 
- Don't know about additional tabs contributed by other packages

Switching to a single view is likely the simplest way, but there may be other options if we think retaining this would be much better (for example some sort of API that would allow the editor to fetch which pages are valid for a given debug session). (fyi @jacob314)

**Comment by kenzieschmoll** [comment]
This was implemented by supporting `embedMode=many`.
