### ISSUE TITLE
layout overflow for the toolbar buttons in the inspector page

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#3214]
I only see this for a small range of window widths. Larger than a certain width and the buttons have enough space; smaller than that width and they collapse to a narrower rendering.

<img width="1347" alt="Screen Shot 2021-07-21 at 11 48 04 AM" src="https://user-images.githubusercontent.com/1269969/126562791-ddbc5b2e-a951-4e20-a167-451457a66da0.png">

**Comment by tomgilder** [comment]
I'll look at this
