### ISSUE TITLE
Poor performance on "Logging" tab when lots of events are emmited

### ISSUE THREAD

**Issue by nshahan** [flutter/devtools#3238]
Repro: 
1. Open the Flutter Gallery using Flutter Web `flutter run -d chrome`.
2. Navigate to a page with constant animation running. Ex: Material -> Progress indicators
3. Open DevTools and connect to the app.
4. Switch to the "Logging" tab in DevTools.

The DevTools app becomes unresponsive when events are flowing in for every animation frame.

I'm running flutter from master.

```
$ flutter --version
Flutter 2.5.0-2.0.pre.118 • channel master • git@github.com:nshahan/flutter.git
Framework • revision 22436cca0e (82 minutes ago) • 2021-08-02 14:40:04 -0700
Engine • revision 29f9df723f
Tools • Dart 2.14.0 (build 2.14.0-368.0.dev)
```

cc @kenzieschmoll

**Comment by KlausJokisuo** [comment]
Any news on this? Performance is terrible on the logging tab. Also, the logging gets spammed with Flutter's log messages.

**Comment by CoderDake** [comment]
I've found out that this issue can amended by setting an itemExtent on the ListView. I'm looking into adding this functionality into our table builder to ensure that the logger will have a much cleaner scrolling experience :)

**Comment by CoderDake** [comment]
Master now has the changes that make the event log useable when there are lots of events :)
