### ISSUE TITLE
Viewing an object fields in the inspector (hovering) can cause exception.

### ISSUE THREAD

**Issue by terrylucas** [flutter/devtools#3240]
Hovering over a AppBar, expand the _inheritedWidgets  field, then expand the _buckets fields inside of _inheritedWidgets will cause an exception see below:

![image](https://user-images.githubusercontent.com/2055873/128026643-0c85176e-623e-4516-a10c-a15596eb7b7b.png)

Exception thrown

![image](https://user-images.githubusercontent.com/2055873/128026275-ae8fd9cb-87cc-43b4-b0da-3fb8b3d8aeaf.png)

**Comment by elliette** [comment]
I'm not able to reproduce this - ` _inheritedWidgets` has been replaced by `_inheritedElements`, and I can expand all of its children without an error.
