### ISSUE TITLE
TimelineHttpRequestData needs some cleanup 

### ISSUE THREAD

**Issue by bleroux** [flutter/devtools#3244]
Since dartIOVersion 1.6, VM Service doesn't log HTTP request and response bodies in timeline Event (bodies are logged separately using HttpProfile)

```TimelineHttpRequestData```  could be simplified by removing code dealing with ```responseBody```

See  https://github.com/flutter/devtools/pull/3233#discussion_r681260906

**Comment by parlough** [comment]
Fixed by https://github.com/flutter/devtools/pull/3907 :D
