### ISSUE TITLE
"Debug Paint" button disappeared

### ISSUE THREAD

**Issue by fatadel** [flutter/devtools#3256]
With the latest update of Dart and Flutter, the "Debug Paint" button has disappeared from the DevTools.

![image](https://user-images.githubusercontent.com/14371560/128604354-67e60c76-7579-4c31-9066-a23a5a432de7.png)

### Version Info

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.1 20D74 darwin-arm, locale ru-RU)
    • Flutter version 2.2.3 at /Users/%username%/.flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

**Comment by MrBirb** [comment]
I think it was renamed to Show Guidelines

**Comment by fatadel** [comment]
> I think it was renamed to Show Guidelines

Looks like indeed. Thank you @MrBirb!
