### ISSUE TITLE
ElevatedButton and CircleAvatar icons not found in widget tree

### ISSUE THREAD

**Issue by bleroux** [flutter/devtools#3257]
#3215 introduces new icons for the widget tree.

ElevatedButton and CircleAvatar icons are not found : 

![image](https://user-images.githubusercontent.com/840911/128731843-2f34e5db-8e66-412f-ad50-5b26157d310e.png)

**Comment by kenzieschmoll** [comment]
CC @tomgilder

**Comment by MrBirb** [comment]
@bleroux Did your PR fix this?

**Comment by bleroux** [comment]
@MrBirb Yes

![image](https://user-images.githubusercontent.com/840911/129313608-375268ef-ddc7-47ca-b326-7c5481f4fcdb.png)

**Comment by tomgilder** [comment]
Oops, sorry for stupid typo, thanks for fixing @bleroux!
