### ISSUE TITLE
Fixed - Grey panels when selecting some HTTP Requests

### ISSUE THREAD

**Issue by bleroux** [flutter/devtools#3260]
When selecting an HTTP Requests, 'Overview', 'Header' and 'Response' tabs sometimes display a grey panel (or a red one when launching DevTools in debug mode).

![ReleaseMode](https://user-images.githubusercontent.com/840911/128894364-0e227f05-de03-4d81-96df-3218302e50af.png)

This is at least true for the following requests :
- request to a non-existing domain
- request to initiate a WebSocket to ```echo.websocket.org```
 
Underlying problem is that there are several calls to nullable fields. Existing tests (```network_profiler_test.dart```) don't cover those cases because they rely on HTTP Requests collected from the timeline and not on ones collected by the new ```HttpProfile```

@kenzieschmoll Kenzie, if you want you can assign this issue to me. I will try to make a PR with :
- a new group in network_profiler_test.dart that will turn on HttpProfile
- fixes in UI and non UI code (DartIOHttpRequestData)

**Comment by kenzieschmoll** [comment]
Sure @bleroux, thanks! Go ahead and add me as a reviewer when you are ready.
