### ISSUE TITLE
[Debugger page] Add go-to declaration through wheel click for function

### ISSUE THREAD

**Issue by Skeemet** [flutter/devtools#3275]
Hi,

It would be nice to use the wheel click to go to the declaration of the clicked function like IntelliJ to browse your code.
What do you think ?

PS: DevTools are awesome and thanks a lot for documentation !!

**Comment by kenzieschmoll** [comment]
Closing this as not planned, since the DevTools debugger is in maintenance mode. We recommend that users use a more full-featured debugger from their IDE.
