### ISSUE TITLE
[Network] HTTP not show Request Headers 

### ISSUE THREAD

**Issue by iceDays** [flutter/devtools#3283]
![Image](https://chedudu.oss-cn-beijing.aliyuncs.com/upload/20210816/20210817-143925.png)

Here it always shows content-length:0 or transfer-encoding

DevTools 2.5.0

**Comment by pinguluk** [comment]
Same issue, can't see the headers & body, I can only see the response

**Comment by kenzieschmoll** [comment]
this should be resolved.
