### ISSUE TITLE
Empty frame chart

### ISSUE THREAD

**Issue by fernando-s97** [flutter/devtools#3288]
I launched my app in profile mode in Android Studio by clicking on the toolbar profile icon. In the Flutter performance side pane I was able to see the frame times and there was a link to open the DevTool. I clicked on the DevTool link, it launched the DevTool in my default browser (chrome) window, from there I clicked on the Performance tab to view the frames chart but it was empty (the timelines chart was fulfilled). The app's performance overlay shows the raster chart as it should.

![image](https://user-images.githubusercontent.com/20338690/129889407-6a14db57-5254-4ffd-9575-b3df57602eed.png)

This problem only happens in profile mode. In debug mode I always have this chart filled

Tested on
DevTools version: 2.5.0
Android Studio version: 4.2.2

Below is the output generated by the flutter doctor -v command

[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [versÃ£o 10.0.19043.1165], locale pt-BR)
    • Flutter version 2.2.3 at C:\Users\fosan\Documents\flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\fosan\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.59.0)
    • VS Code at C:\Users\fosan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (3 available)
    • ASUS X00QD (mobile) • 192.168.1.176:5555 • android-arm64  • Android 11 (API 30)
    • Chrome (web)        • chrome             • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)          • edge               • web-javascript • Microsoft Edge 92.0.902.73

• No issues found!

**Comment by kenzieschmoll** [comment]
Do you see this same issue if you switch to the Flutter beta channel? I suspect you won't because this version of the Performance page is only shown for flutter versions < 2.3.0-pre.16.0.

**Comment by fernando-s97** [comment]
Few hours agora I've noticed the following behaviour: if I run the app and open dev tools, this problem happens. With the the app running, if I go to Android Studios' menu "Run > Flutter  run 'main.dart' in profile mode" again, the app will restart and I'll be able to open a new dev tools "instance" (?). This intance will have this chart working as expected. 

Unfortunetely I cannot ensure this behaviour, I just *think* that this happened. What I know for sure, is that at some point that chart started working.

I'll check if I can make this test tomorrow again, using the beta channel.

**Comment by Shvet** [comment]
I have got same problem. I am trying to run app in profile mode and i think i am using version 2.3.3 with stable so i wont be working. you can check image.

![Screenshot 2021-08-19 102034](https://user-images.githubusercontent.com/7760064/130011570-6b926571-92e1-44a2-9a63-b16648b6def9.png)

Here is my `flutter doctor`
```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1165], locale en-IN)
    • Flutter version 2.2.3 at G:\Android\sdk\flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at G:\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = G:\Android\sdk
    • ANDROID_SDK_ROOT = G:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (3 available)
    • ONE E1003 (mobile) • b70b330 • android-arm    • Android 6.0.1 (API 23)
    • Chrome (web)       • chrome  • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)         • edge    • web-javascript • Microsoft Edge 92.0.902.73

• No issues found!

```

**Comment by kenzieschmoll** [comment]
At this point, this is a deprecated version of the performance page, so we likely won't fix this issue. If you can use a newer version of flutter > 2.3.0-pre.16.0, you will see the new version of the performance page. The new version has 'Pause', 'Resume', and 'Clear' buttons at the top left instead of 'Refresh' and 'Clear', so that is an easy way to tell which version of the performance page you are seeing.

There are several beta candidates to switch to that are > 2.3.0-pre.16.0: https://flutter.dev/docs/development/tools/sdk/releases

**Comment by fernando-s97** [comment]
For now I won't be able to change to the beta channel, but knowing this is indeed a bug is enough for me. That's not something that will impossibilite me in any point for now.

I won't close the issue because of @Shvet, but feel free to do it if you want
