### ISSUE TITLE
Can not set a breakpoint on an if statement with only a boolean variable in DevTools

### ISSUE THREAD

**Issue by jsroest** [flutter/devtools#3289]
It is not possible to set a breakpoint on an if statement with only a boolean variable.

![image](https://user-images.githubusercontent.com/17854207/129907227-0e3ac052-473d-4083-90f0-fd2beb3fad7e.png)

Android Studio lets you set a breakpoint, but it will not get hit the first time. The second time the breakpoint is passed, it breaks a few lines further in the code.

DevTools does not allow to set a breakpoint.

Especially with Android Studio, this is confusing, because it looks like the code where the breakpoint is, is not executed.

I suggests two fixes:

- Do not allow to set a breakpoint in Android Studio where it is also not allowed in DevTools (to be consistent and clear to the developer).
- Allow to set a breakpoint on an if statement with just a variable like the example.

Sample project can be found here:
https://github.com/jsroest/breakpoint_bug

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-x64, locale en-NL)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)

Sample here in Android Studio:
The breakpoint is skipped on the first button press and hits somewhere below on the second button press.

1. Hot restart
2. Press Floating Action Button
3. One of the breakpoints is not hit
4. Press Floating Action Button
5. The app breaks a few lines below the breakpoint

https://user-images.githubusercontent.com/17854207/129878981-d07bbc0f-62b8-4c80-8d17-06f0ff3fdde1.mov

Related issues:
https://github.com/flutter/flutter/issues/88306
https://github.com/flutter/flutter/issues/81051#issuecomment-826677359

**Comment by jsroest** [comment]
Hi @kenzieschmoll,

I would like to ask your attention to this issue. I filled the issue 26 days ago and it seems to get lost or forgotten.

At this point, I experienced this issue above again while debugging my own code and thought that it might be a good idea to write this reminder.

Thanks.
Sander

**Comment by kenzieschmoll** [comment]
@bkonyi looks like we are grabbing the breakable positions here: https://github.com/flutter/devtools/blob/554a0cbbda362785cab18172a3457f5de1fbbc38/packages/devtools_app/lib/src/debugger/debugger_controller.dart#L989. Any idea why the case described above wouldn't be showing up in the list of breakable lines?

**Comment by bkonyi** [comment]
It looks like we're missing a `DebugStepCheck` in cases where we're not invoking a function as part of evaluating the condition (the 3 working cases described in the issue all invoke either a getter, `operator==`, or both, which will all insert `DebugStepCheck`s). This should just need a simple fix in the flow graph builder in the VM.

**Comment by bkonyi** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/c51f885613177f18a5516eda4bed62f701e0631d.
