### ISSUE TITLE
UI thread timeline events for a flutter frame are being improperly grouped

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#3295]
Sometimes a `MessageLoop::FlushTasks` event can parent the event groups for multiple flutter frames. We currently look for an event with the "frame_number" arg and assign the root of that event to a flutter frame object. This scenario breaks that logic.
<img width="1107" alt="Screen Shot 2021-08-20 at 9 21 09 AM" src="https://user-images.githubusercontent.com/43759233/130264122-2303d1a1-8154-4720-9605-fc6d0fb564d3.png">

**Comment by LeonManolo** [comment]
Could someone please clarify if the "MessageLoop::FlushTasks" event has been removed or renamed? I'm looking to measure the total CPU time spent running Dart code by examining the extent of this event in the timeline. However, I can't seem to find it in my timeline anymore. Any guidance or updates on this would be greatly appreciated. Thank you!

**Comment by kenzieschmoll** [comment]
To measure CPU usage, I would recommend using the DevTools CPU profiler to record a CPU profile and look at CPU samples. Right now, CPU samples are not included in the Timeline events. This is blocked on https://github.com/flutter/devtools/issues/4755.

Regarding the "MessageLoop::FlushTasks" event, @dnfield can you comment on what conclusions are safe to draw around this event? Or if it exists anymore?

**Comment by LeonManolo** [comment]
> To measure CPU usage, I would recommend using the DevTools CPU profiler to record a CPU profile and look at CPU samples. Right now, CPU samples are not included in the Timeline events. This is blocked on #4755.
> 
> Regarding the "MessageLoop::FlushTasks" event, @dnfield can you comment on what conclusions are safe to draw around this event? Or if it exists anymore?

Thank you, @kenzieschmoll, for your suggestion regarding the DevTools CPU profiler. I'll definitely explore using CPU samples for a broader performance analysis.

My current approach is somewhat targeted, as I'm specifically looking to compare the performance of two slightly different algorithms within a feature of my app. To do this, I've written an integration test for this feature and used `IntegrationTestWidgetsFlutterBinding.traceAction` to capture the timeline JSON. My understanding is that Dart code executes on the UI thread `name.startsWith('1.ui')`, as I'm not utilizing isolates for this test. I then focused on the top-level events in the timeline (those that appear at the top in the chrome://tracing visualization) for each algorithm's implementation.
![Screenshot 2024-03-07 at 11 49 06](https://github.com/flutter/devtools/assets/87019114/dea54e1a-9cff-4e8e-9aa2-810357625c4e)


By repeating this process 100 times for versions A and B of the feature and calculating the median, I aimed to make an informed decision on which version is more performant. All of this is conducted in profile mode to maintain a consistent test environment.

Given this context, I'm curious if you believe this approach is reasonable for comparing the performance of small, specific features within my app? Particularly, I'm interested in any insights or feedback on utilizing the timeline events in this manner, and if the absence of "MessageLoop::FlushTasks" affects the validity of this approach.

I appreciate any guidance or suggestions you might have.

**Comment by kenzieschmoll** [comment]
Is the algorithm you are measuring business logic or flutter code? If it is business logic, a simplistic approach could be to just time the operation for each test run, and then follow your same approach to measure the median of the 100 runs for A / B. 
```
final now = DateTime.now().millisecondsSinceEpoch;
callback();
// record this value somewhere where you can aggregate over 100 runs to calculate median
final time = DateTime.now().millisecondsSinceEpoch - now;
```

Another approach using the CPU profiler would be to use UserTags to measure the CPU performance with set start and end times. This article gives a tutorial of using UserTags: https://medium.com/dartlang/dart-devtools-analyzing-application-performance-with-the-cpu-profiler-3e94a0ec06ae

And finally, you can send custom timeline events from your application using dart:developer's [Timeline API](https://api.flutter.dev/flutter/dart-developer/Timeline-class.html). These will show up in the Performance page timeline along with all the events sent from the Flutter framework.

Regarding your questions surrounding "MessageLoop::FlushTasks", I will leave @dnfield to comment.
