### ISSUE TITLE
Track hover events through DWDS analytics

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#3331]
We capture internal analytics for Dart DevTools and track the number of evaluations. When a user hovers over a member it shows up as an evaluation. We'd like to be able to differentiate between evaluations provided through the console and these hover requests. 

We could create a custom event for hover actions using the DWDS [provided](https://github.com/dart-lang/webdev/blob/5bd3dc65000b20f571ee26658e9103c19155b7c4/dwds/lib/src/dwds_vm_client.dart#L162) service callback.

**Comment by kenzieschmoll** [comment]
We can add a custom dimension for what type of eval is triggered in the DevTools analytics. We don't currently count evals in our analytics so we'll need to add that too. Related to https://github.com/flutter/devtools/issues/3270

**Comment by kenzieschmoll** [comment]
Closing since this is no longer a priority. We can re-open if that changes.
