### ISSUE TITLE
Misleading "report feedback" -button

### ISSUE THREAD

**Issue by alexlindroos** [flutter/devtools#3366]
I might be the only one, but it happens to me way too many times that I am supposed to press settings and I am pressing the "report feedback". The icons are little bit similar and it would be nice that the shape of the "report feedback" -icon would not be too similar to "settings" -icon.

![settings_bug_report](https://user-images.githubusercontent.com/17140689/133611697-42b73e60-bbee-468e-92e3-a2ab51285fef.jpg)

**Comment by jacob314** [comment]
I wonder if there is some Google standard report feedback icon we can use.

**Comment by alexlindroos** [comment]
We have these Material Design icons "Report" and "Report problem". There was no icon for "Report feedback" atleast on Material Design. 

![outline_report_white_24dp](https://user-images.githubusercontent.com/17140689/134137636-25642a32-178d-4dc0-a710-9bb3c324ee8b.png)
(Report)

![outline_report_problem_white_24dp](https://user-images.githubusercontent.com/17140689/134137650-14810a91-6e15-4eb3-b31f-eaa8994e45ab.png)
(Report problem)

**Comment by alexlindroos** [comment]
One of these icons from Material Design could also work?

![outline_email_white_24dp](https://user-images.githubusercontent.com/17140689/134165649-c4c9c6a3-ac7f-46b1-86c8-2300e081da04.png)

![outline_create_white_24dp](https://user-images.githubusercontent.com/17140689/134165675-e1657780-629b-4f05-873d-1e67a96ade1e.png)

![outline_chat_white_24dp](https://user-images.githubusercontent.com/17140689/134165811-28ee900c-3dc3-44b7-bea3-781191114c9e.png)

Or this from community material icons:

![comment-quote-outline](https://user-images.githubusercontent.com/17140689/134165825-e227a79c-0f6e-4a33-b404-a513002b5262.png)

**Comment by elliette** [comment]
The report feedback button is no longer next to the settings button, so hopefully this is no longer confusing. Please reopen if that's not the case. Thanks.
