### ISSUE TITLE
widget tree is empty

### ISSUE THREAD

**Issue by maxzod** [flutter/devtools#3374]
flutter : 2.5
OS : windows 10
ide : VsCode

i have created test app 
``` 
flutter create test_dev_tools
```
then run the app 
also running the dev tools project
running in debug mode
give the ws url provided from the test app console 
the devtools opens but noting in the widget tree

![image](https://user-images.githubusercontent.com/47630729/133843341-6294ee7e-700f-4f38-b381-8e0766a04d59.png)

**Comment by kenzieschmoll** [comment]
Does the chrome devtools console for the Flutter DevTools window show any errors? Does anything happen if you click the Refresh tree button (to the right of Select Widget Mode)?

**Comment by kenzieschmoll** [comment]
this looks like the same issue as https://github.com/flutter/devtools/issues/3150. Inspector not working for web. @jacob314

**Comment by kenzieschmoll** [comment]
This should be resolved. We can open a new issue if this comes up again.
