### ISSUE TITLE
Events being lost from stream?

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#34]
If I uncomment the code to call `_loadHeapSnapshot` and run it, it seems like we don't process ever other frame of data from the stream (and therefore never complete). Testing with iOS Simulator, flutter_gallery (last pulled yesterday):

![screen shot 2018-10-02 at 12 19 12 pm](https://user-images.githubusercontent.com/1078012/46345771-ac404d00-c63d-11e8-9e72-ccb76365fb55.png)
![screen shot 2018-10-02 at 12 18 55 pm](https://user-images.githubusercontent.com/1078012/46345773-b06c6a80-c63d-11e8-9f8e-c768ce633842.png)

As far as I can tell, this shows all 6 packages coming over the WS, but we only fired events for 3 of them.

**Comment by DanTup** [comment]
@devoncarew I can't figure out what's going on here.. If I listen to the `ws.onMessage` it seems to get all events, but if I log inside the `asyncMap` call it doesn't seem to have them all. As far as I can see, nothing else is reading from its subscription so I'm not sure where they're going (I wondered if asyncMap would drop events while it's processing, but couldn't find anything conclusive).

```dart
ws.onMessage.listen((s) => print('${msg++} RAW ${s.toString()}'));

  final Stream<dynamic> inStream =
      ws.onMessage.asyncMap<dynamic>((MessageEvent e) {
    print('${msg++} ASYNC ${e}');

    if (e.data is String) {
      return e.data;
    } else {
      final FileReader fileReader = new FileReader();
      fileReader.readAsArrayBuffer(e.data);
      return fileReader.onLoadEnd.first.then<ByteData>((ProgressEvent _) {
        final Uint8List list = fileReader.result;
        return new ByteData.view(list.buffer);
      });
    }
  });
```

![screen shot 2018-10-02 at 1 05 08 pm](https://user-images.githubusercontent.com/1078012/46347553-d6950900-c643-11e8-9aa9-8cf81ee28f64.png)

**Comment by devoncarew** [comment]
Without any other investigation, we may not be (and likely aren't) handling the binary websocket messages.

**Comment by devoncarew** [comment]
OK, I dug into the source code and nothing stood out.

No exception are being thrown? A possible type error somewhere is one possibility (code that didn't expect a binary message).

**Comment by DanTup** [comment]
Looks like the issue is definitely the `asyncMap` - this is what happens in its implementation:

```dart
if (newValue is Future<E>) {
  subscription.pause();
  newValue
      .then(add, onError: addError)
      .whenComplete(subscription.resume);
```

So it'll dropping any events that arrive while it's processing the future (this isn't clear from the docs IMO). I'll try and change this to something else. I guess the reason for the async was that we don't want to start processing any messages while others are still in-flight (since they have async work), so I guess we need something that can buffer them.

**Comment by DanTup** [comment]
Oooooh.....

> https://api.dartlang.org/stable/2.0.0/dart-async/StreamSubscription/pause.html

** Currently DOM streams silently drop events when the stream is paused. This is a bug and will be fixed. **

I'm not sure if this qualifies as a "DOM stream" but I'm wondering if this is related.

Apparently I found this out 4 years ago 😄

https://stackoverflow.com/a/26087093/25124

I can't find any info on this bug (I'm going to open an issue in the SDK repo since that text has been there for over 5 years) and for now I'll see if I can just wrap a single-listener stream around this or something.

**Comment by devoncarew** [comment]
Opening an issue sounds good. The comment doesn't make sense re: DOM streams. This _could_ be considered one because it is coming from some underlying JS APIs?

**Comment by DanTup** [comment]
Yeah, that confused me too - yet the behaviour seems exactly what's described. I opened https://github.com/dart-lang/sdk/issues/34656 (edited into comment above) to try and get confirmation (and an idea of whether it's still likely to be fixed or just the accepted behaviour - in which case docs should be updated).
