### ISSUE TITLE
Frame rendering chart shows false jank

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#340]
Sometimes the frame rendering chart shows jank when the duration is under 8 ms. We should only consider cpu/gpu jank to be when the portion of the frame takes > 8 ms.
<img width="147" alt="screen shot 2019-02-21 at 4 01 33 pm" src="https://user-images.githubusercontent.com/43759233/53257205-71879180-367e-11e9-889c-c71ffb6cad84.png">

**Comment by jacob314** [comment]
I think this was a bug where the labels were going wrong. Please reopen if you are able to reproduce.
