### ISSUE TITLE
Private classes are missing from memory dumps

### ISSUE THREAD

**Issue by AAverin** [flutter/devtools#3423]
It is a common pattern to keep the State class private by prefixing it with `_`.
All such private classes are missing from memory dump analysis making it very difficult to find potential leaks.

**Comment by kenzieschmoll** [comment]
@terrylucas

**Comment by kenzieschmoll** [comment]
You can unhide private classes by adjusting the snapshot filter:
<img width="1310" alt="Screen Shot 2021-10-04 at 9 56 08 AM" src="https://user-images.githubusercontent.com/43759233/135892736-5405ca3f-2d82-4a6f-be6e-fb0e775590cc.png">
<img width="821" alt="Screen Shot 2021-10-04 at 9 56 15 AM" src="https://user-images.githubusercontent.com/43759233/135892754-cc4717aa-dfd3-48a2-8eee-70529f81f1f2.png">
