### ISSUE TITLE
No way to see what references leaked instance

### ISSUE THREAD

**Issue by AAverin** [flutter/devtools#3424]
In Android the common way to find a leak is to:
- find which instance is leaking by finding duplicates (for example)
- switching to the references view and finding which other instance is still holding reference to our leaking instance

Such analysis is not possible in devtools for Flutter because it's not possible to see who/what references the instance.

**Comment by kenzieschmoll** [comment]
@terrylucas

**Comment by polina-c** [comment]
Duplicate to https://github.com/flutter/devtools/issues/3951
