### ISSUE TITLE
Add warning for users that DevTools will no longer be shipped on pub.

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#3433]
One thing to think about here is how we'll be able to tell if a user launched from pub or from the SDK, and do we need to? Maybe we can add a warning as a tooltip over the version number and in the About devtools dialog. We'll also want to update the documentation to stop pointing to pub (this change likely needs to wait until the flutter tools changes to launch from sdk are in flutter stable).

**Comment by kenzieschmoll** [comment]
@DanTup when can VS code switch to launching from the SDK instead of pub (https://github.com/Dart-Code/Dart-Code/issues/3584)? For the 2.8.0 release of DevTools, when a user is on Flutter version >= 2.7.0-3.0.pre (the first version that includes https://github.com/flutter/flutter/commit/5a85c0d81c2a1c101c1ebc38af15922f72ff1e30), we will show a warning that says devtools should no longer be launched from pub, but instead via `dart devtools`. IntelliJ launches devtools from the flutter daemon, so this warning should not show up for IntelliJ users. This warning would show up for a user that manually ran `pub global activate devtools` or for VS code users if VS code does not switch to launching from the sdk SDK. 

@stevemessick we should remove the "Loading DevTools" modal dialog from IntelliJ for Flutter version >= 2.7.0-3.0.pre, as that is the first version of flutter for which flutter tools will launch DevTools will be launched from the SDK and not pub.

**Comment by DanTup** [comment]
It's not done yet, but my plan is to include it in the next release (end of the month). Is that soon enough?

Where will the warning be shown? In stdout output, or in the app itself?
