### ISSUE TITLE
Timeline is empty for Dart apps

### ISSUE THREAD

**Issue by mit-mit** [flutter/devtools#3444]
### Repro app

Create a new Dart CLI app with `dart create reproapp` and replace `bin/reproapp.dart` with:

```dart
import "dart:developer";

main() {
  while (true) {
    print('loop');
    Timeline.timeSync('Work loop iteration', () {
      fibonacci(10);
      Timeline.timeSync('Doing heavy work', () {
        // We want to log how long this call takes compared to the entire loop on the timeline.
        fibonacci(40);
      });
    });
  }
}

int fibonacci(int n) => n <= 2 ? 1 : fibonacci(n - 2) + fibonacci(n - 1);
```

### Repro steps:

1. Run the app: `dart run --observe`
2. Open the VM Service UI (Observatory) from the first printed uri ("Observatory listening...")
3. Open the DevTools from the second printed uri ("The Dart DevTools...)

The timeline in the Performance tab of DevTools is empty, but the timeline in Observatory shows this:
![Screen Shot 2021-10-11 at 13 03 58](https://user-images.githubusercontent.com/13644170/136780364-a203acd6-273e-4761-8aaf-a59bd0baf26a.png)

**Comment by jacob314** [comment]
@kenzieschmoll

**Comment by mit-mit** [comment]
> @mit-mit does this work if you use startSync and finishSync instead of timeSync? https://api.flutter.dev/flutter/dart-developer/Timeline-class.html

No, that doesn't seem to make a difference

**Comment by mit-mit** [comment]
> You need to run with dart run --observe --timeline-streams=Dart for the Dart stream to be enabled.

@bkonyi, that command fails:
```
$ dart run --observe --timeline-streams=Dart
Could not find an option named "timeline-streams".
```

And as Kenzie asked: Why is a second flag even needed?

**Comment by bkonyi** [comment]
> > You need to run with dart run --observe --timeline-streams=Dart for the Dart stream to be enabled.
> 
> @bkonyi, that command fails:
> 
> ```
> $ dart run --observe --timeline-streams=Dart
> Could not find an option named "timeline-streams".
> ```

Ah whoops, looks like you need to do `dart --timeline-streams=Dart run --observe`. This is another common VM option that needs to be exposed as a valid `dart run` option, I'll create a CL to do that.

> And as Kenzie asked: Why is a second flag even needed?

Timeline tracing isn't free, so it's something we don't necessarily want on by default if we're recording a lot of timeline streams. However, I'm not 100% sure why we don't always enable the `Dart` stream since that's what most developers will care about (maybe @rmacnak-google has more context as this has been how things have worked since before my time on the project).

**Comment by mit-mit** [comment]
> Timeline tracing isn't free, so it's something we don't necessarily want on by default if we're recording a lot of timeline streams.

Not even when running with the `--observe` flag?

**Comment by bkonyi** [comment]
> > Timeline tracing isn't free, so it's something we don't necessarily want on by default if we're recording a lot of timeline streams.
> 
> Not even when running with the `--observe` flag?

Some of the timeline streams are quite noisy and write a lot of events. Most streams are written to by the VM for events like background compilation and garbage collection, and these aren't really valuable to the average developer. The `Dart` stream is where all timeline events from Dart code are written, so I could see the argument for enabling it by default (along with maybe the `Embedder` stream for Flutter maybe?).

**Comment by mit-mit** [comment]
Yeah, lets go ahead and change `dart run --observe` to enable the Dart stream. Can you do that ~Ben?

I don't think `dart run` needs to enable the Flutter stream -- shouldn't that be the `flutter` tool?

**Comment by bkonyi** [comment]
> Yeah, lets go ahead and change `dart run --observe` to enable the Dart stream. Can you do that ~Ben?

Sure, this shouldn't be hard to do. @rmacnak-google @a-siva, do either of you see any issues with enabling this stream by default for the standalone VM?

> I don't think `dart run` needs to enable the Flutter stream -- shouldn't that be the `flutter` tool?

Yes, that would be up to flutter_tools to enable

**Comment by a-siva** [comment]
> Sure, this shouldn't be hard to do. @rmacnak-google @a-siva, do either of you see any issues with enabling this stream by default for the standalone VM?
> 
turning Dart Stream on by default when --observe is used should be fine.

**Comment by mit-mit** [comment]
@a-siva @rmacnak-google can we go ahead and get this stream enabled when `--observe` is passed?

**Comment by mit-mit** [comment]
Thanks @bkonyi
