### ISSUE TITLE
No Flutter Frames Chart In Flutter DevTools in profile mode

### ISSUE THREAD

**Issue by zhihongzhang123** [flutter/devtools#3452]
I ran my app in profile mode  in console:
`Launching lib/main.dart on M2006C3LC in profile mode...`
`Running Gradle task 'assembleProfile'...`
`Signing with key.properties`
`✓  Built build/app/outputs/flutter-apk/app-profile.apk (155.6MB).`
`Installing build/app/outputs/flutter-apk/app.apk...`
`Debug service listening on ws://127.0.0.1:51581/t0MzF1U0txE=/ws`

**Comment by zhihongzhang123** [comment]
�help！！！I cann`t find flutter frame chart in Flutter DevTools when I run my flutter app with profile mode.

![image](https://user-images.githubusercontent.com/53854612/137468505-9f047cc8-8126-4d10-b4c6-0b055fe2ba35.png)

**Comment by kenzieschmoll** [comment]
We hide that chart if your app is not recognized as a flutter app. If you do a hard refresh of Chrome or open the link in an incognito window, does it show up then? You could be hitting a race condition.

What version of DevTools are you using? (click the question mark in the upper right to find out)

**Comment by zhihongzhang123** [comment]
> The CPU samples are recorded by the VM and stored in a ring buffer - one thing that could have happened is that the samples for the time range of the selected event could have fallen out of the buffer, and therefore no samples were available.
> 
> Can you record a CPU profile in the CPU Profile Page?
Thank your help...I recorded CPU profile， it show as below:
![image](https://user-images.githubusercontent.com/53854612/138205786-cf9621f4-e001-41ac-93a1-107a8900f659.png)

**Comment by zhihongzhang123** [comment]
> We hide that chart if your app is not recognized as a flutter app. If you do a hard refresh of Chrome or open the link in an incognito window, does it show up then? You could be hitting a race condition.
> 
> What version of DevTools are you using? (click the question mark in the upper right to find out)

The Frames chart still doesn`t show up. I am using 2.7.0 of DevTools.

**Comment by kenzieschmoll** [comment]
If you run the flutter gallery app on your device, do you see the same issue? What device are you using?
