### ISSUE TITLE
Nudge users to turn on advanced tracing options based on performance problems observed.

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#3460]
Currently we surface options to trace build, paint, and layout times but the options are hard to discover.

We cannot enable the options by default as they may skew performance. We could however surface tips to use the options when we notice an app is having a problem that the option could help debug.
![image](https://user-images.githubusercontent.com/1226812/137998292-4f89dc66-fcc1-449b-a014-e7cfb165c8d5.png)

For example, if the build time shown in a profile build is slow, we should show an overlay explaining that build time was slow and surfacing the checkbox to enable tracking builds.

If paint time is slow in a debug or profile build, we should show a message explaining that paint time was slow and surfacing the checkbox to track paint times along with a link to a doc explaining how to draw conclusions.

**Comment by kenzieschmoll** [comment]
This is implemented in the Frame Analysis tab
