### ISSUE TITLE
Flutter devtools gray network screen 

### ISSUE THREAD

**Issue by ibnetahirr** [flutter/devtools#3462]
![image](https://user-images.githubusercontent.com/51880112/138330312-35deac35-2000-4ab7-a934-525db4b6b73d.png)

**Comment by kenzieschmoll** [comment]
What are the errors? and what version of DevTools are you on (click help icon in upper right to find out)?

**Comment by dewbambs** [comment]
I face the same issue. It seems the issue comes when the data in network tab changes. These are my chrome's console log. 
DevTool version: 2.9.2+1
flutter version: 2.10
dart version 2.16.0

```
Uncaught TypeError: Cannot read properties of null (reading 'toString')
    at RenderMouseRegion.getTransformTo$1 (:9103/main.dart.js:194946:12)
    at _TooltipState._createNewEntry$0 (:9103/main.dart.js:184724:48)
    at _TooltipState.ensureTooltipVisible$0 (:9103/main.dart.js:184708:13)
    at tear_off.<anonymous> (:9103/main.dart.js:7882:45)
    at _TimerImpl_internalCallback.call$0 (:9103/main.dart.js:91448:21)
    at invokeClosure (:9103/main.dart.js:7776:26)
    at :9103/main.dart.js:7797:18
main.dart.js:63280 NoSuchMethodError: method not found: 'endTime' on null
log @ main.dart.js:63280
main.dart.js:63030 Another exception was thrown: Instance of 'ErrorSummary'
main.dart.js:63280 NoSuchMethodError: method not found: 'endTime' on null
log @ main.dart.js:63280
main.dart.js:63030 Another exception was thrown: Instance of 'ErrorSummary'
main.dart.js:63280 NoSuchMethodError: method not found: 'endTime' on null
log @ main.dart.js:63280
main.dart.js:63030 Another exception was thrown: Instance of 'ErrorSummary'
```

**Comment by godofsleepy** [comment]
i have encounter same issue, but in Request (Network Tab)
<img width="1440" alt="Screen Shot 2022-11-10 at 15 49 03" src="https://user-images.githubusercontent.com/45101689/201044658-22a5fec0-a867-4303-b4e5-dcc486906607.png">


**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Dart Version: 2.18.4
Flutter Version: 3.3.8 / stable
Framework / Engine: 52b3dc25f6 / 857bd6b74c
Connected app type: Flutter native (debug build)
