### ISSUE TITLE
Debugger screen throws uncaught "ext.dwds.sendEvent" exception on load

### ISSUE THREAD

**Issue by matt-ragonese** [flutter/devtools#3467]
Navigating to the Debugger screen results in an "ext.dwds.sendEvent" exception on load.

See screenshot below taken from Chrome DevTools.
<img width="565" alt="DebuggerScreenException" src="https://user-images.githubusercontent.com/46503192/138789464-82c95eb6-bc59-441c-b288-559ea5c64e40.png">

**Comment by kenzieschmoll** [comment]
Seeing another error related to `ext.dwds.sendEvent` @annagrin. This is in a release build from head (preparing for the 2.8.0 release)
<img width="487" alt="Screen Shot 2021-11-01 at 1 42 22 PM" src="https://user-images.githubusercontent.com/43759233/139739415-9a991a91-09bd-44c4-9a05-18b1a5fc5db7.png">

**Comment by annagrin** [comment]
@matt-ragonese @kenzieschmoll how can I repro this? Do you know what version of dwds is used in those cases?

**Comment by kenzieschmoll** [comment]
Repro steps:
1. create a release build from HEAD, run `./tool/build_release.sh`
2. run DevTools `dart packages/devtools/bin/devtools.dart`
3. navigate to the debugger page

```
Flutter 2.6.0-12.0.pre.568 • channel master • git@github.com:flutter/flutter.git
Framework • revision ef137e56b0 (12 minutes ago) • 2021-11-03 11:16:31 -0400
Engine • revision 6ae304aeef
Tools • Dart 2.15.0 (build 2.15.0-268.0.dev)
```

**Comment by annagrin** [comment]
Fixed in a couple of PRs in dwds: 
https://github.com/dart-lang/webdev/pull/1470
https://github.com/dart-lang/webdev/pull/1518

Closing for now, please feel free to reopen if it happens again (I'd need repro steps in that case).
