### ISSUE TITLE
No CPU samples recorded

### ISSUE THREAD

**Issue by lofei117** [flutter/devtools#3471]
![image](https://user-images.githubusercontent.com/1164836/139075144-86988be6-120e-4f34-9a45-117a93bbd642.png)
![image](https://user-images.githubusercontent.com/1164836/139075241-ccdf0ec5-8a91-4bdb-8d18-c4a6b61fa93e.png)

**Comment by kenzieschmoll** [comment]
@bkonyi are there any known issues with pulling CPU samples from XiaoMi devices? (like there were with pulling from a real iOS device a while back)

**Comment by bkonyi** [comment]
@kenzieschmoll not that I'm aware of. Those issues on iOS were due to decisions made by the Flutter team that hit a known LLDB + profiling bug just the right way. It's not something that would start happening on specific types of Android devices.

**Comment by kenzieschmoll** [comment]
@lofei117 can you still reproduce this issue? Do did you see this issue on other devices, or only the XiaoMi 10 Pro?

**Comment by elliette** [comment]
This issue looks like it occurred on an old version of DevTools. Are you still experiencing this issue with DevTools on the latest Flutter stable? If so, please reopen and we will take a look. Thanks.
