### ISSUE TITLE
File explorer does not show file contents after a hot restart

### ISSUE THREAD

**Issue by annagrin** [flutter/devtools#3521]
**Repro**

- run a flutter example using `flutter run -d chrome`
- run devtools and connect it to the running app above. 
- open file explorer, find a main.dart file and observe the code opening.
- put a breakpoint anywhere in that file
- click hot restart
- try to open main.dart or changing to another file. 
- observe that the same contents (in my case. web_entrypoint.dart) is shown instead, and the devtools reports "Invalid object id" exceptions.

Note that after hot restart, refresh, or reload file explorer shows two or more sets of the same files, where only the last set is actually working. Looks like the fix needs to make sure that file explorer clears and re-initializes its state on hot restart and refresh.

![image](https://user-images.githubusercontent.com/12737689/144146520-1a800114-e700-43c0-8323-dc7bb33998cf.png)

**Comment by elliette** [comment]
This issue is not restricted to web, it is reproducible on all platforms.
