### ISSUE TITLE
Can't open Filters dialog twice

### ISSUE THREAD

**Issue by johnpryan** [flutter/devtools#3524]
DevTools gets stuck if you try to open the Logging -> Filters dialog twice. The screen is blank until you refresh the page.

## Steps to reproduce
1. Run a Flutter app with DevTools
2. Open the Logging tab
3. Open the filters dialog:
<img width="54" alt="Screen Shot 2021-12-03 at 4 31 19 PM" src="https://user-images.githubusercontent.com/1145719/144689248-4c053e0d-e5d6-4d88-8630-54fa32625e8c.png">

4. Click apply
5. Try to open the filters dialog, but the screen is blank.

**Comment by kenzieschmoll** [comment]
I cannot reproduce this at head. @johnpryan are you still seeing this issue? If not, we can close.

**Comment by johnpryan** [comment]
Nope! closing.
