### ISSUE TITLE
I can build the app, but I get the following error: Invalid argument(s): A directory corresponding to fileSystemPath "/Users/develien/.pub-cache/hosted/pub.dartlang.org/devtools-2.9.2/build" could not be found

### ISSUE THREAD

**Issue by kyudongDev** [flutter/devtools#3549]
Invalid argument(s): A directory corresponding to fileSystemPath "/Users/develien/.pub-cache/hosted/pub.dartlang.org/devtools-2.9.2/build" could not be found

There seems to be a problem with the 2.9.2 commit as there were no problems until yesterday.

**Comment by sangwon95** [comment]
So am I. Did you find a solution?

**Comment by xxqwf** [comment]
So am I. Did you find a solution?

**Comment by nabeel001** [comment]
I'm facing a similar issue too, Any solutions yet..?

**Comment by yangweiyi** [comment]
I have a similar problem. Have you solved it?

**Comment by thanhchelsea** [comment]
delete my life !!! :)

**Comment by liaozhiqun** [comment]
I have the same problem today,I fixed it with running "dart pub global active devtools -v 2.8.0"

**Comment by thanhchelsea** [comment]
wwoahhh ... thank liaozhiqun. i fix with running "dart pub global activate] devtools -v 2.8.0"

**Comment by xxqwf** [comment]
> I have the same problem today,I fixed it with running "dart pub global active devtools -v 2.8.0"

thanks！！

**Comment by Vaytrex** [comment]
You can fix that by adding that directory "$YOUR_PATH\flutter\.pub-cache\bin" to your system's "Path" environment variable.

**Comment by liaozhiqun** [comment]
thanks,i first try this way,but did not work , then downgrade the devtools version, it works.












 
You can fix that by adding that directory "$YOUR_PATH\flutter.pub-cache\bin" to your system's "Path" environment variable.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Vaytrex** [comment]
You can fix that by adding that directory "$FLUTTER_PATH\flutter.pub-cache\bin" to your system's "Path" environment variable.

**Comment by Vaytrex** [comment]
You can fix that by adding that directory "$FLUTTER_PATH\flutter\.pub-cache\bin" to your system's "Path" environment variable.

**Comment by Vaytrex** [comment]
You can fix that by adding that directory "$FLUTTER_PATH\flutter\\.pub-cache\bin" to your system's "Path" environment variable.

**Comment by ayushxx7** [comment]
how to use this fix with android studio?

**Comment by ayush-mandowara-bst** [comment]
> problem

use `activate` instead of `active` to avoid subcommand error.

**Comment by bkonyi** [comment]
`2.9.2` has been retracted, please run `dart pub global active devtools -v 2.8.0` to resolve this issue.

**Comment by tylergasperlin** [comment]
> dart pub global active devtools -v 2.8.0

activate not active
dart pub global activate devtools -v 2.8.0

**Comment by SURAJSPS** [comment]
I have a similar problem.

**Comment by burakomer** [comment]
I am having an issue that prevents starting Dart DevTools on VS Code. It says `Dart DevTools exited with code 255`. I used `dart pub global activate devtools -v 2.8.0` but it does not work for Flutter version 2.2.2. I am using fvm with Sidekick to manage flutter versions on projects. The new error is `Dart DevTools exited with code 1.` My other project on Flutter 2.8.0 is fine, DevTools runs with no problem.

Some people on [stackoverflow](https://stackoverflow.com/questions/70446275/failed-to-start-devtools-dart-devtools-exited-with-code-255) say that this fixed their problem, but mine didn't get fixed.
I am on macOS Monterey 12.0.1.

**Comment by kenzieschmoll** [comment]
@DanTup for VS code issue.

**Comment by burakomer** [comment]
> DanTup for VS code issue.

Took an hour of my life to upgrade my project to 2.8.1. Now the issue went away.

**Comment by evansherry** [comment]
Use `dart pub global activate devtools -v 2.8.0` to lower the devtools version, it will always automatically upgrade to 2.9.2, how to prevent devtools from automatically upgrading to 2.9.2

**Comment by chornbe** [comment]
> I have the same problem today,I fixed it with running "dart pub global activate devtools -v 2.8.0"

Hi. Where did you find this documented? Thanks.

**Comment by xcraftx** [comment]
> I have the same problem today,I fixed it with running "dart pub global activate devtools -v 2.8.0"

I had been looking for a solution for weeks. Thanks dude!!!!

**Comment by rahulvyas** [comment]
> Use `dart pub global activate devtools -v 2.8.0` to lower the devtools version, it will always automatically upgrade to 2.9.2, how to prevent devtools from automatically upgrading to 2.9.2

Same issue is happening with me. I always get this message next day when I start my machine I get error 255

**Comment by DanTup** [comment]
I can reproduce the issue noted above outside of VS Code by running `dart pub global activate devtools` and `dart pub global run devtools` using a Dart 2.13.3 SDK (from Flutter 2.2.2 stable).

I think what's happening is that there is a broken (missing its `build` folder) - but retracted - v2.9.2 of DevTools on Pub (2.8.0 is fine). The version of `pub` included in Dart v2.13.3 (included in Flutter 2.2.2) is installing it anyway.

Perhaps handling retracted packages is only done in the client, and therefore it's ignored by this version (@jonasfj?)

I think possible fixes are:

- Upgrade to a newer version of Flutter (whose version of Pub will ignore the retracted version of DevTools)
- Publish a new version of DevTools with a version greater than 2.9.2 to Pub (which includes the `build` folder)

(@kenzieschmoll, @bkonyi - was 2.9.2 retracted because it was accidentally broken, and a 2.9.3 is reasonable, or is there a reason it shouldn't be on Pub?)

**Comment by DanTup** [comment]
> (@kenzieschmoll, @bkonyi - was 2.9.2 retracted because it was accidentally broken, and a 2.9.3 is reasonable, or is there a reason it shouldn't be on Pub?)

I should've read all of the comments above - @bkonyi noted this at https://github.com/flutter/devtools/issues/3549#issuecomment-998961200. The reason the downgrade doesn't work correctly for people with older versions of Dart/Pub because the IDEs may try to auto-update DevTools by running `pub global activate` which picks up the retracted version.

**Comment by yakupbilgen** [comment]
As a workaround, run "dart pub global activate devtools -v 2.8.0" in terminal but I get the same error every time vs code is opened. How can I solve it?

**Comment by DanTup** [comment]
@yakupbilgen if you're able to upgrade to the latest stable Dart/Flutter SDK, that should prevent the issue as those versions will stick with v2.8.0.

**Comment by sureshbb** [comment]
### I have solved the issue running these commands from terminal,
```
flutter upgrade
flutter pub global activate devtools -v 2.9.2
```

**Comment by ayush-mandowara-bst** [comment]
> @yakupbilgen if you're able to upgrade to the latest stable Dart/Flutter SDK, that should prevent the issue as those versions will stick with v2.8.0.

I can't upgrade, my organisation is sticking with flutter 2.2.1 and I can't do much about that. Can we please just release a version of devtools which has the appropriate files so that the auto upgrade of latest devtools doesn't hamper our work?

**Comment by chornbe** [comment]
“Breaking changes” are the way of the world these days.

**Comment by DanTup** [comment]
I suspect those with the ability to publish DevTools are out on vacation right now.

I'm going to add a setting to the VS Code extension to allow disabling the auto-update of DevTools (https://github.com/Dart-Code/Dart-Code/issues/3750) which will be available in the pre-release channel soon which may help in the meantime.

**Comment by DanTup** [comment]
The next release of the Dart extension for VS Code contains a setting that will let you opt-out of automatic updating of DevTools:

<img width="996" alt="Screenshot 2021-12-30 at 13 17 14" src="https://user-images.githubusercontent.com/1078012/147755389-8db3e5c2-c926-4fcb-9e8c-3533b370c156.png">

This only applies to older SDKs, as the latest SDKs ship with DevTools and VS Code will just use the one from there.

If you'd like to be able to use this setting before the stable extension release, you can switch to the pre-release channel of the Dart/Flutter extensions in VS Code here:

<img width="665" alt="Screenshot 2021-12-30 at 13 08 04" src="https://user-images.githubusercontent.com/1078012/147755382-3e8275cf-4687-44ac-85ff-41164cd5cdbf.png">

You'll need to run `pub global activate devtools 0.8.0` after unticking this, then restart VS Code. You can switch between the release/pre-release channels of the extensions at any time.

**Comment by Ldev007** [comment]
@DanTup Hi Dan, are you sure we should use the devtools version 0.8.0 and not 2.8.0. Is the reason behind it to handle this auto updation internally specifically in 0.8.0 version or is it just a typo ?

**Comment by DanTup** [comment]
@Ldev007 oops, well spotted - that was indeed a typo and 2.8.0 is the correct version. I've edited the command in my comment above. Thanks!

**Comment by jonasfj** [comment]
> Perhaps handling retracted packages is only done in the client, and therefore it's ignored by this version that doesn't know about it

FYI, retraction only works for Dart `>= 2.15`, see [dart.dev/go/package-retraction](https://dart.dev/go/package-retraction).

**Comment by sandwichstealer** [comment]
I've installed v3.29.0 as stated, however the blue box "Switch to Pre-Release Version" isn't there. A search of "update dev" results in "No Settings Found". 

The root cause is Flutter updates to beta versions by default instead of stable.

**Comment by Ldev007** [comment]
@sandwichstealer I guess 3.32 is already available being the reason pre-release option isn't showing up but I can't confirm about the beta and stable versions involvement. Secondly, search for **update dev** won't work unless you restart the VS Code I guess that might be the case here as it was in my case too at first attempt.

**Comment by DanTup** [comment]
@sandwichstealer version 3.29.0 is the older version (it was the stable version at the time of my screenshot above, and not the pre-release version). Version 3.32.0 has now been published so you don't need the pre-release version to get this fix. Please update to v3.32.0 and then the setting should appear (if you don't see v3.32.0 you may need to update VS Code).

**Comment by DanTup** [comment]
@jonasfj in VS Code we're using the API to get the latest version number to decide if we should try to update. This means even on the latest version of the SDK, we read the `latest` version from https://pub.dev/api/packages/devtools and conclude there's an update even though it's retracted (the update does nothing, but it seems wasteful).

What's the correct/best way from that API data to pick the "latest stable that is not retracted" version? Are the items in `versions` guaranteed to be sorted by version, or publish dates? (I couldn't find anything specific about this in [these docs](https://github.com/dart-lang/pub/blob/master/doc/repository-spec-v2.md#list-all-versions-of-a-package)).

**Comment by kenzieschmoll** [comment]
Published 2.9.3 on pub to resolve this issue.

**Comment by jonasfj** [comment]
> What's the correct/best way from that API data to pick the "latest stable that is not retracted" version? Are the items in versions guaranteed to be sorted by version, or publish dates? (I couldn't find anything specific about this in these docs).

No guarantees is given on the ordering. You could probably use something like [Version.prioritize](https://pub.dev/documentation/pub_semver/latest/pub_semver/Version/prioritize.html).

But the logic we use in `dart pub` is actually somewhat complicated.
 * If the current version is a _stable release_, we only consider newer _stable releases_ (stable release is one that doesn't have a `-dev...` component in the version number -- also called a prerelease component).
 * If the current version is a _pre-release_ then we prefer any newer _stable releases_ if one exist, otherwise, we check if a newer _pre-release_ is available.

This might be too complicated for your use-case. So I would suggest just using `latest` from the API, and ensuring that the _latest version_ on pub.dev is _not retracted_. In general, the latest version of a package should not be retracted -- I guess we would even tweak `latest` in the API to not be a retracted version.

**Comment by DanTup** [comment]
@jonasfj 

> I guess we would even tweak `latest` in the API to not be a retracted version.

I think that would be nice, but I don't know if it's breaking. I think probably I'll leave things as-is for now - like you say, chances are the latest version won't be retracted and it won't matter, and for the latest SDKs we're not pulling DevTools from Pub anyway so it's probably only `webdev` left being activated by us (`stagehand` was another, but that's also been migrated to the SDK).

Thanks!
