### ISSUE TITLE
Flutter devtools not connecting

### ISSUE THREAD

**Issue by ayushxx7** [flutter/devtools#3550]
All members of my team including myself are not able to connect devtools.
We had the same issue as this question: https://stackoverflow.com/questions/70429102/invalid-arguments-a-directory-corresponding-to-filesystempath-users-user-pub.

We cleared the cache. Now the error is gone, but devtools is still not connecting.

**Comment by HarGarX** [comment]
Same issue also once i run the app it gives the same error

**Comment by ayushxx7** [comment]
Closing as the same issue has been reported here: https://github.com/flutter/devtools/issues/3549.

**Comment by ayushxx7** [comment]
reopening as this and https://github.com/flutter/devtools/issues/3549 are slightly different questions, although the fix for both should be the same.

**Comment by ayushxx7** [comment]
refer for quick fix: https://stackoverflow.com/a/70432385/7048915

**Comment by ayush-mandowara-bst** [comment]
https://github.com/flutter/devtools/issues/3549#issuecomment-998592215

**Comment by bkonyi** [comment]
2.9.2 has been retracted, please run dart pub global active devtools -v 2.8.0 to resolve this issue.
