### ISSUE TITLE
Flutter build error: Unhandled exception: Invalid argument(s): A directory corresponding to fileSystemPath "C:\Users\Bluestacks\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\devtools-2.9.2\build" could not be found

### ISSUE THREAD

**Issue by ayush-mandowara-bst** [flutter/devtools#3559]
This error keeps coming up again and again. I have already run the command to downgrade the devtools but after some time the error comes up again.
Refer: https://github.com/flutter/devtools/issues/3550#issuecomment-998961822

**Comment by ayush-mandowara-bst** [comment]
@bkonyi can you please assist?

**Comment by ayushxx7** [comment]
this question is same as https://github.com/flutter/devtools/issues/3560

**Comment by sandwichstealer** [comment]
This has something to do with Flutter not being able to run 2.9.2, so we're forced to install and use 2.8.0. Then when loading the emulator it's still trying to load 2.9.2 which isn't enabled. Please fix the bug that forces us to use version 2.8.0 instead of 2.9.2. Thanks,

**Comment by kenzieschmoll** [comment]
2.9.2 has been retracted, please run `dart pub global activate devtools -v 2.8.0` to resolve this issue. See https://github.com/flutter/devtools/issues/3549. You could also try `dart pub cache repair` followed by `dart pub global activate devtools -v 2.8.0` if just activating 2.8.0 does not solve your issue.

**Comment by kenzieschmoll** [comment]
Published 2.9.3 on pub to resolve this issue. Running `flutter pub global activate devtools` should pull down the fixed DevTools build.
