### ISSUE TITLE
flutter_diet_and_exercise

### ISSUE THREAD

**Issue by Niwamanya** [flutter/devtools#3565]

**Comment by Niwamanya** [comment]
How can i fix this error, am using VS Code

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.core:core:1.7.0.
        AAR metadata file: C:\Users\nixc\.gradle\caches\transforms-2\files-2.1\1978c8540575e4da29114a40e6bf1a1a\core-1.7.0\META-INF\com\android\build\gradle\aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.lifecycle:lifecycle-viewmodel-savedstate:2.4.0.
        AAR metadata file: C:\Users\nixc\.gradle\caches\transforms-2\files-2.1\e3923512c822e4f000946a473468e2bd\jetified-lifecycle-viewmodel-savedstate-2.4.0\META-INF\com\android\build\gradle\aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.lifecycle:lifecycle-viewmodel:2.4.0.
        AAR metadata file: C:\Users\nixc\.gradle\caches\transforms-2\files-2.1\84a0b4f063e71708aba68a0f9142e97b\lifecycle-viewmodel-2.4.0\META-INF\com\android\build\gradle\aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.lifecycle:lifecycle-service:2.4.0.
        AAR metadata file: C:\Users\nixc\.gradle\caches\transforms-2\files-2.1\6dbf881728784cc9605b2f20ec76e4c0\jetified-lifecycle-service-2.4.0\META-INF\com\android\build\gradle\aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.lifecycle:lifecycle-process:2.4.0.
        AAR metadata file: C:\Users\nixc\.gradle\caches\transforms-2\files-2.1\905b75140256175900249fa3cdf80332\jetified-lifecycle-process-2.4.0\META-INF\com\android\build\gradle\aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.lifecycle:lifecycle-reactivestreams:2.4.0.
        AAR metadata file: C:\Users\nixc\.gradle\caches\transforms-2\files-2.1\fe8dc26e281f703d4cc2a9fa29c3445a\lifecycle-reactivestreams-2.4.0\META-INF\com\android\build\gradle\aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.lifecycle:lifecycle-runtime:2.4.0.
        AAR metadata file: C:\Users\nixc\.gradle\caches\transforms-2\files-2.1\c1e11ba5aa57bc31665ec18e0194c06c\lifecycle-runtime-2.4.0\META-INF\com\android\build\gradle\aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.lifecycle:lifecycle-livedata:2.4.0.
        AAR metadata file: C:\Users\nixc\.gradle\caches\transforms-2\files-2.1\6f89f6a8d02328dd268436e4d56509cb\lifecycle-livedata-2.4.0\META-INF\com\android\build\gradle\aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.lifecycle:lifecycle-livedata-core:2.4.0.
        AAR metadata file: C:\Users\nixc\.gradle\caches\transforms-2\files-2.1\028e2cbeefc94464a5c5d89d22bbdfd0\lifecycle-livedata-core-2.4.0\META-INF\com\android\build\gradle\aar-metadata.properties.

**Comment by bkonyi** [comment]
Hi @Niwamanya,

This doesn't look like a DevTools related issue so I'm going to mark this as closed. You might want to try asking for help on a Flutter forum or chat room, or take a look at StackOverflow for people who have had similar issues.
