### ISSUE TITLE
Prototyping a continuous on-screen widget selection mode

### ISSUE THREAD

**Issue by InMatrix** [flutter/devtools#3567]
When selecting a widget on screen using the inspector, it could require a few tries until the right widget is selected, due to lack of feedback from hover-overing over the UI on a mobile device / simulator. In the current workflow, the user exits the active selection mode after making their first click on the UI. User input gets captured by the app again instead the inspector, which might not be what the user is intended. See that in the video below:

https://user-images.githubusercontent.com/348942/149208618-cf595fc2-c780-4dfc-9281-563eb01a92a0.mp4

To select another widget, the user must either click the magnifier button injected to the UI at the lower-left corner or holding down their mouse's left button if using a simulator or their finger if using a physical device. Both mechanisms are not obvious. 

The request is to prototype an alternate workflow where the inspector doesn't exit the active selection mode after the user has selected the first widget. The user will be able to click elsewhere on the device / simulator and select the widget underneath, until they explicitly toggle off the widget selection mode in the Inspector UI. 

Cc: @jacob314 @kenzieschmoll

**Comment by elliette** [comment]
Closing in favor of https://github.com/flutter/devtools/issues/8155 (de-duping all open issues into this one).
