### ISSUE TITLE
devtools doesn't account for post-frame callbacks in frame time?

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/devtools#3584]
I'm profiling a test application that adds an expensive post-frame callback every time a text field changes its content. I added a `Timeline` event called `TextField` to measure the time each invocation of the callback takes. Here's the result: the callback alone (60 ms) exceeded the frame budget but devtools is still telling me everything is fine (not a red frame).

<img width="1395" alt="Screen Shot 2022-01-05 at 11 12 06 AM" src="https://user-images.githubusercontent.com/31859944/148276250-3fc4710f-16ba-485a-908a-aeaccbde914d.png">

**Comment by kenzieschmoll** [comment]
@LongCatIsLooong can you please export the performance screen data with this frame selected (click the Export button in the upper right of the performance page) and attach it to this bug report? Thanks.

The top chart of frame times come from the FrameTiming API, so there may be a bug there causing the UI frame time to be improperly calculated. @iskakaushik

**Comment by elliette** [comment]
Without additional information, we cannot debug this issue. Please re-open if you can provide an export of the performance screen data. Thanks.

**Comment by LongCatIsLooong** [comment]
(I think this was fixed by https://github.com/flutter/flutter/pull/136435)
