### ISSUE TITLE
Dart DevTools incorrectly believes we're in a profile build with Dart SDK `2.17.0-69.0.dev `

### ISSUE THREAD

**Issue by elliette** [flutter/devtools#3636]
This is the connected app: https://github.com/kevmoo/slide_puzzle/

### Instructions to reproduce:
* Install Dart version `2.17.0-69.0.dev`
* Run the app with `dart run --observe solve/solve.dart`
* Open the Dart DevTools URI printed in the terminal 

**Expected:** Debugger panel is included in the panels
**Actual:** Debugger panel is not included in the panels 

This is because the `value` for [this eval](https://github.com/flutter/devtools/blob/e6a1c5803e9fde6e09632ff8467428f930a09cca/packages/devtools_app/lib/src/shared/connected_app.dart#L102-L107) is `null` (and therefore we return `true` for `_connectedToProfileBuild` because `!(value?.kind == 'Bool')` is `true`). 

We then skip loading the Debugger panel [here](https://github.com/flutter/devtools/blob/a616832995d13410a4078b506c91927865ff6904/packages/devtools_app/lib/src/shared/screen.dart#L248-L252) because `serviceManager.connectedApp.isProfileBuildNow` is `true`. 

**This does not happen on Dart stable (`2.16.0`)!**
If you install Dart version `2.16.0`, then the `value` for the eval is an `InstanceRef` with kind `Bool`. Therefore  `serviceManager.connectedApp.isProfileBuildNow` is `false`.

**Comment by kenzieschmoll** [comment]
It looks like we are just performing that eval to see if eval is supported, so we should be able to change it to something even more simple like '1+1'.

**Comment by elliette** [comment]
Added error logging to the `eval` to see what the error was, seems to be the same as https://github.com/dart-lang/sdk/issues/48169 / https://github.com/flutter/flutter/issues/97500. Going to go ahead and close this.
