### ISSUE TITLE
Laggy bar chart in timeline

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#364]
The bar chart seems to have a hard time handling a lot of frames one after the other. This video shows this issue, but basically it adds the bars to the chart in a choppy manner, and eventually stops adding them until the chart has time to "catch up" in a sense. When I clicked the back button on the app to make the app stop drawing frames, the bar chart eventually catches up and draws the missing frames.

[slowBarChart.mp4.zip](https://github.com/flutter/devtools/files/2906702/slowBarChart.mp4.zip)
@terrylucas

**Comment by jacob314** [comment]
we do rate limit rendering updates to the chart at 6fps but this looks much lower.

**Comment by jacob314** [comment]
Is this still an issue in the package:flutter version of the app?

**Comment by kenzieschmoll** [comment]
Verified this isn't an issue in the flutter bar chart.
