### ISSUE TITLE
Dart DevTools Flutter Inspector empty on High-DPI displays

### ISSUE THREAD

**Issue by sionicion** [flutter/devtools#366]
Just trying out the new Dart Dev Tooling, unfortunately the Flutter Inspector shows the widget tree for a brief second and then it disappears. Running Chrome 72.0.3626.119 on Windows 10.

<img width="928" alt="annotation 2019-02-26 212414" src="https://user-images.githubusercontent.com/2309224/53460963-fb33b800-3a0c-11e9-8ff1-3c63f62da290.png">

**Comment by Katekko** [comment]
Need more information, like your project, to shot what is happening... I'm using DevTools now and something like yours don't happened for while

**Comment by sionicion** [comment]
I've tried creating entirely new projects, happens with all of them. I tried debugging the app using VS Code, command line, and Android Studio. All show the same result in Dart DevTools.

**Comment by sionicion** [comment]
I don't know if this helps but here are some errors I found for the webpage.

<img width="1509" alt="annotation 2019-02-28 115226" src="https://user-images.githubusercontent.com/2309224/53583350-684f6680-3b4f-11e9-85e9-0281ca98382c.png">

**Comment by sionicion** [comment]
Ah... I had a breakthrough.. It's because I have a high-DPI display.. Works just fine when setting my 4K monitor to 100% DPI..

**Comment by kenzieschmoll** [comment]
@sionicion does this happen on the other pages (Timeline, Debugger, Logging) as well, or only the Inspector?

**Comment by devoncarew** [comment]
@sionicion, when you see the issue, are there any exceptions or other output to the Chrome DevTools console?

**Comment by jacob314** [comment]
https://github.com/flutter/devtools/pull/376 will fix the issue. Thanks for the bug report!

**Comment by sionicion** [comment]
Sorry for the late response, thanks for issuing the fix so quickly! At first I didn't notice a change, but I figured it was because I couldn't update the DevTools correctly. I updated them via command-line, so I tried launching DevTools from the command-line which worked. I just have to figure out how to update the DevTools VS Code is launching, because it's currently serving the older release.

But anyways, looks great!! Thanks for the quick fix! :)

**Comment by devoncarew** [comment]
Great, thanks for verifying the fix!

@DanTup for the VS Code / updating DevTools question. Perhaps we should update the docs to briefly mention how to upgrade?

**Comment by DanTup** [comment]
@devoncarew vNext will auto-update when it's below the "minmum required" version (https://github.com/Dart-Code/Dart-Code/issues/1478) but I think we should also detect newer versions outside of what's hard-coded and prompt to update (or auto-update if we're sure users would be ok with that). I've opened https://github.com/Dart-Code/Dart-Code/issues/1500. I'm not sure if running `pub global activate` every time is the best way since it seems quite slow (for me, at least) but I'll do a little more testing.

**Comment by DanTup** [comment]
Sorry, missed @sionicion's question:

>  I just have to figure out how to update the DevTools VS Code is launching, because it's currently serving the older release

VS Code just runs `pub global run devtools` so whatever version you have activated with `pub global activate` will run. However, the server hangs around for the duration of your VS Code window, so if you already had it running it might seem like it's running an older version, but a VS Code restart will probably fix.

**Comment by sionicion** [comment]
I've restarted VS Code several times, and just tried restarting my computer. For some reason VS Code is launching an older version of Dart DevTools. If I use the terminal inside VS Code to run the command "flutter packages pub global run devtools" then it serves the page on port 9100, and DevTools works correctly.

I will say though, I have the Flutter SDK installed, I didn't install the Dart SDK, so pub isn't in my path. So is it possible the Flutter SDK and VS Code have different copies of pub, different directories where these files exist?

**Comment by DanTup** [comment]
> I have the Flutter SDK installed, I didn't install the Dart SDK, so pub isn't in my path. So is it possible the Flutter SDK and VS Code have different copies of pub, different directories where these files exist?

Quite the opposite - if you only have the Flutter SDK you'll only have one pub, so things should be simpler.

Pub lives inside the Flutter SDK, so you can run:

```
(flutter_sdk_path)/bin/cache/dart-sdk/bin/pub global list
```

To see what VS Code would see. As far as I can tell, there's only one global list. You can then activate the latest version with:

```
(flutter_sdk_path)/bin/cache/dart-sdk/bin/pub global activate devtools
```

Does that help? If so, what command did you run previously to upgrade it that didn't work?

**Comment by sionicion** [comment]
I was running the "flutter packages pub global activate devtools" command, I would restart VS Code, the computer, but for some reason that didn't reflect in VS Code. Now if I ran "flutter packages pub global run devtools", it would end up serving the newer version.

I ultimately deleted the Flutter SDK and git cloning from the master branch. I went back into VS Code, launched DevTools which was supposed to automatically get DevTools first, which it did, but it ended up serving the older version still. What ended up working was git cloning again, running Flutter via command-line, running the "flutter packages pub global activate devtools" command, and then launching DevTools from VS Code, now I have no issues.

**Comment by sionicion** [comment]
Want to add...that's why it seems strange to me, I would run that command and it went from .11 to .12, but VS Code kept serving the older version, despite elsewhere it would serve the newer version. It wasn't until I deleted the whole SDK, manually issued that activate command, then tried to launch it via VS Code - that it ultimately decided to use the newer release. It just kept running it side by side.

**Comment by DanTup** [comment]
I can't explain what's happened here, it all sounds a bit strange. If you see it again and/or can reproduce, I'd definitely be interested in tracking it down though. If at any point VS code seems to be serving the a different version so what you see when running it manually, please run `(flutter_sdk_path)/bin/cache/dart-sdk/bin/pub global list` and let me know whether it's showing the old or new version listed there.

**Comment by sionicion** [comment]
I can't replicate it now. I'll report back if it happens again with the next version. It appears VS Code isn't looking to activate DevTools now, after I delete the Flutter SDK, run flutter doctor, and then launch DevTools from inside VS Code, it isn't running that pub command and goes straight to launching DevTools.

**Comment by sionicion** [comment]
What I'm saying is it works as intended, but DevTools already seems to be in place and it doesn't need to activate it. I've wiped the whole Flutter SDK. But regardless, at it's working now.

**Comment by DanTup** [comment]
When a package is activated with `pub global activate` it's [installed globally](https://www.dartlang.org/tools/pub/cmd/pub-global) (see https://www.dartlang.org/tools/pub/cmd/pub-global). This means it will be in your pub cache folder. to uninstall it, you need to run `pub global deactivate devtools` (this will require an SDK) or manually wipe out your pub cache folder.

If everything is working, don't worry about messing things up to diagnose this. But if you do see something strange happen again, please do let us know. Thanks!

**Comment by sionicion** [comment]
Alrighty! Will do, thank you!
