### ISSUE TITLE
Widget Inspector values overlap label text in Brave browser

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#367]
Opened by @Sh1d0w at https://github.com/Dart-Code/Dart-Code/issues/1487

---

Just updated to the latest version 2.24 and this is how it looks when I launch the Dart DevTools:

<img width="1779" alt="screenshot 2019-02-27 at 11 12 10" src="https://user-images.githubusercontent.com/5074917/53478983-bd707700-3a80-11e9-855c-5239e106043b.png">

The widget attributes seems to overflow the widget name and everything becomes unreadable.

**Comment by Sh1d0w** [comment]
After a short investigation it seems to be caused by the browser's built in ad-blocker. It prevents third party fingerprinting on the canvas element used, which seems to break the UI. After disabling this, everything looks good.

This issue can be closed I guess, thanks for the fast reaction 👍

**Comment by DanTup** [comment]
> caused by the browser's built in ad-blocker

Is this enabled by default? Which browser/version is it on which OS? It may be worth keeping this open to see if there's a way we can fix it, or at least warn users if they're using that browser.

**Comment by Sh1d0w** [comment]
@DanTup I am on the latest version of MacOS using [Brave Browser](https://brave.com). Yes this is enabled by default.

**Comment by jacob314** [comment]
To keep our velocity high writing the devtools app we only have time to support Chrome. We should make that clearer when you start the app to avoid confusion.

**Comment by DanTup** [comment]
> We should make that clearer when you start the app to avoid confusion.

Do you mean in the web app? Should we open an issue for this?

I had a quick look to see if there might be a quick fix for this, but it seems like Brave's anti-fingerprinting breaks quite a lot of stuff that uses canvas:

https://github.com/brave/brave-browser/issues/1025

So I doubt there's something simple we could tweak to avoid it. I guess a lot of legit use looks like fingerprinting.

**Comment by kenzieschmoll** [comment]
Open issue for warning users is here: https://github.com/flutter/devtools/issues/66.

**Comment by lookfirst** [comment]
Just ran into this myself. Having a warning for missing canvas would be nice.

**Comment by DanTup** [comment]
@lookfirst Brave deliberately makes itself look like Chrome (it used to identify itself, but stopped because it was another variable that could be used for fingerprinting), so I don't think it's possible to show a warning for Brace without all Chrome users seeing it.

**Comment by Sh1d0w** [comment]
I don’t think the warning should be based on browser detection, rather than if canvas is available. There are plugins from chrome that prevents fingerprinting as well, which then will result broken UI again.

**Comment by DanTup** [comment]
Oh sorry, I may have misunderstood. I thought Brave was just messing with the rendering on the canvas. If it's just not available, then that might be easy to warn for.

Can you run this code in the JS console and confirm if it outputs `false`?

```js
var elm = document.createElement('canvas'); !!(elm.getContext && elm.getContext('2d'));
```

**Comment by Sh1d0w** [comment]
@DanTup That's close.

Canvas fingerprinting is well described here https://browserleaks.com/canvas#how-does-it-work

Because the way it works, the only way to prevent it is to disable `toDataUrl` method of the canvas, so the data can not be read, and thus no "fingerprint" can be obtained.

I think you can tweak the check like this:

```
var elm = document.createElement('canvas'); (elm.toDataURL() === '')
```

If fingerprinting is disabled, this will output true.

**Comment by DanTup** [comment]
Ok, though we don't use `toDataURL` in DevTools so it might not be the best check. I wonder if it's `measureText` that's being blocked (looks like we use that to align the value, and the screenshot shows the value written over the label).

Does this return 0 for you?

```js
document.createElement('canvas').getContext('2d').measureText('Text that is quite long')
```

**Comment by Sh1d0w** [comment]
@DanTup Yep, the output is

```
TextMetrics {width: 0}
```

I've just ran observatory with the latest version of Brave, as I wasn't using it for a while and found out a bunch of new problems:

<img width="651" alt="Screenshot 2019-07-09 at 11 29 25" src="https://user-images.githubusercontent.com/5074917/60873689-70c35680-a23f-11e9-9d97-52ad2cb22988.png">

It seems like the CSS and JS assets are not served with correct mime type from the observatory thus white screen appears as those files are not loaded at all.

**Comment by DanTup** [comment]
@Sh1d0w ok, then I think we can probably easily show a warning at the top of the Inspector page when `measureString` returns 0. I've opened https://github.com/flutter/devtools/issues/777.

As for the Observatory issue - I think that's best raised at dart-lang/sdk since it's a different app to the Dart DevTools (though I'm not sure what the support is intended to be for that).

**Comment by alexis-andino** [comment]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/44984721/85485672-d151bd80-b58e-11ea-8fa7-3255aa9a17d0.png">

I turned off the shields for the website and the overlap issue was gone.
