### ISSUE TITLE
Add network profiler

### ISSUE THREAD

**Issue by leisim** [flutter/devtools#368]
This tool is already a great help but it would be amazing if it had a network profiler like Android Studio.

Maybe even with support for intercepting network calls and creating custom responses.

![](https://developer.android.com/studio/images/profile/networkprofiler_2x.png)

**Comment by devoncarew** [comment]
Thanks for the feature request!

cc @jacob314 @pq

**Comment by jacob314** [comment]
Here is a somewhat related package to help debug network traffic with flutter.
https://github.com/blankapp/flutter_flipperkit/

**Comment by leisim** [comment]
Thanks, I'll try this package. But I still think this would be a great fit for the devtools 👍

**Comment by jacob314** [comment]
@terrylucas, it looks like there will be a lot of interest when we ship a network profiler.

**Comment by jamesdixon** [comment]
This will be huge!

**Comment by KarimAbdo** [comment]
@jacob314 Any updates? current solutions are quite problematic, especially for a big team with different operating systems.
Stetho works only for android, and quite annoying when upgrading flutter.
FlipperKit is only on mac

**Comment by JunusErgin** [comment]
I agree. It would be awesome to use the network profiler in flutter :)

**Comment by kenzieschmoll** [comment]
The Flutter Web version of DevTools includes a network profiler.

**Comment by jlubeck** [comment]
Is it me or does the network tab on the DevTools don't include the actual body of the responses?? If that is the case this should definitely be re-opened. 

I can't seem to find it

**Comment by jlubeck** [comment]
Looks like it is an issue and it was re-opened here: https://github.com/flutter/devtools/issues/1952

**Comment by rknell** [comment]
@jlubeck looks like it was completed yesterday for the Sep. 2020 milestone
https://github.com/dart-lang/sdk/issues/42952
