### ISSUE TITLE
Performance scroll bar is wonky

### ISSUE THREAD

**Issue by gaaclarke** [flutter/devtools#3703]
## Seen result

Scrolling the scrollbar in the performance tab causes the scroll indicator to resize and jump around.

## Expected result

I expect the scroll indicator to stay the same size and be attached to my mouse.

## Environment

Seen on chrome on macos.  Devtools 2.10.0.

## Video

https://user-images.githubusercontent.com/30870216/154365603-50e65298-537a-4dc1-afa4-93623a278e8a.mov

**Comment by kenzieschmoll** [comment]
closing as dupe of https://github.com/flutter/devtools/issues/3568
