### ISSUE TITLE
Sent event to dwds from Inspector window

### ISSUE THREAD

**Issue by annagrin** [flutter/devtools#3711]
Currently DevTools sends an event to dwds from Debugger window. Tools that start DevTools use this information to measure startup times of DevTools.

https://github.com/flutter/devtools/blob/a616832995d13410a4078b506c91927865ff6904/packages/devtools_app/lib/src/debugger/debugger_screen.dart#L158
For flutter apps, however, the first tab that opens is the Inspector, which means the time to start DevTools is measured incorrectly.

Related: https://github.com/dart-lang/webdev/issues/1517

**Comment by jacob314** [comment]
Fyi @elliette
