### ISSUE TITLE
Migrate screens/provider to null safety.

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#3767]
Child issue of https://github.com/flutter/devtools/issues/3025.
Tips for faster migration: https://github.com/flutter/devtools/issues/3025#issuecomment-1058800219

**Comment by polina-c** [comment]
@rrousselGit , is it what you would take to complete?

**Comment by rrousselGit** [comment]
I can have a look

**Comment by polina-c** [comment]
@rrousselGit , we have a goal to migrate DevTools to null safety in Q1. Is there a chance you could help us achieve the goal?

**Comment by rrousselGit** [comment]
I gave a first shot to the migration https://github.com/flutter/devtools/pull/3915

I haven't verified if tests pass yet though

**Comment by polina-c** [comment]
migrated!
Thank you, @rrousselGit !
