### ISSUE TITLE
Navigate to source code when clicking widgets in devtools browser

### ISSUE THREAD

**Issue by gadfly361** [flutter/devtools#377]
AFAIK the only way to navigate to a widget's source code (in vscode) is by selecting "Select Widget Mode" and then clicking on something in an emulator.

It would be amazing if, when selecting on a widget in the devtools browser, that vscode would also navigate to the widget's source code.

Btw, loving the devtools so far!

**Comment by jacob314** [comment]
I'll take a look. This should just work in VSCode but there may be a bug in DevTools or VSCode blocking it.

**Comment by jacob314** [comment]
Do you see the issue when you open a widget in the summary tree? I just tested locally and it seems to be working as intended. We could also navigate to the source location of where you are in the summary tree if you select in the detail tree if that is what you want.

**Comment by gadfly361** [comment]
@jacob314 I'll try to enumerate the possible options I've experienced and indicate which ones work for me:

Is "Select Widget Mode" toggled on -> SWM?
Does vscode jump to the related source code on click = J2SC?

In the devtools browser (clicking on the widget summary tree and/or the detail tree)
- SWM false, J2SC _false_
- SWM true, J2SC _false_

In an android emulator (clicking on a widget on screen)
- SWM false, J2SC _false_
- SWM true, J2SC *true**
* Only jumps to source code on initial click, subsequent clicks dont update the focus of source code

**Comment by jacob314** [comment]
Thanks for the details. I've tracked down what is going wrong and I'll land a fix Monday. Glad you are enjoying the devtools so far. Keep the feedback coming!

**Comment by DanTup** [comment]
@jacob314 will this fix need any work in the editor, or will it just send the same events we're already handling?

**Comment by kenzieschmoll** [comment]
This is no longer reproducible
