### ISSUE TITLE
Network Tab is not showing any requests

### ISSUE THREAD

**Issue by Lennart-Franck** [flutter/devtools#3777]
### Specs
Flutter Version: 2.10.3
Flutter Channel: stable
DevTools Version: 2.9.2+1

### Problem
I wanted to look up the requests made by my application in the Network tab of the DevTools. The requests in my application are with Firebase and also with the dart http packet. I can understand that the DevTools may can not show the Firebase request but  the usual http requests are also not being shown. 

The network tab is only showing the loading indicator shown in the picture below. 
![image](https://user-images.githubusercontent.com/69119365/156772901-088d7806-f647-4ca7-a7fc-d41bb361a7a9.png)

**Comment by kenzieschmoll** [comment]
CC @bkonyi 

Thanks for the issue. Can you please provide a small repro case so that we can reproduce this issue?

**Comment by rmRizki** [comment]
This issue is also happening to me when I'm doing hot restart

**Comment by tienlam79** [comment]
any update?

**Comment by PrimeTimeTran** [comment]
Is the Network tab able to show requests for assets? 
My situation is when I load an asset on one screen and load the same asset on a different screen, I see different videos. I've confirmed the IDs are the same yet get different results. Strange.

https://gifyu.com/image/SKV9Q

**Comment by ShafiMunshi** [comment]
Use physical device instead of emulator. It's shows all the network connection in devTools
