### ISSUE TITLE
CPU profiler is slow, freezes, dies

### ISSUE THREAD

**Issue by scheglov** [flutter/devtools#3799]
The attached JPG is actually BZIP2 file with `Export` result.

Expand all, click on the scroll thumb and try to scroll.
It freezes, does not actually scroll, then Chrome complains that the tab is not responding, try to scroll a few more times, the tab just dies.

**Comment by scheglov** [comment]
[dart_devtools_2022_3_7-1646698474397000.json.gz](https://github.com/flutter/devtools/files/8201671/dart_devtools_2022_3_7-1646698474397000.json.gz)

**Comment by scheglov** [comment]
I did not actually tried to open this file, I used whatever was initially produced, but this is the export.

**Comment by kenzieschmoll** [comment]
Even when replacing each table row with a very simple colored container, the janky scrolling continues to occur. You can see in the widget rebuild stats chart in intelliJ that when we scroll very quickly, it seems that we are still building every item from the previous scroll position to the new one. Sometimes 1000s of widgets. When we have the more complicated table row for a cpu stack frame (with lots of text and listeners), this doesn't just jank, but completely freezes the list view.
![janky-scrolling](https://user-images.githubusercontent.com/43759233/233726993-bc9985ea-0cee-4930-b57c-1ad694bfebca.gif)

Sounds like this is an instance of this issue: https://github.com/flutter/flutter/issues/75399

**Comment by kenzieschmoll** [comment]
Edit: we were setting `itemExtent: widget.rowItemExtent`, and after digging a bit deeper, it turns out `widget.rowItemExtent` was in fact null 😅
