### ISSUE TITLE
Use `package:` uris instead of `file://` uris in CPU profiler

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#3802]
additionally, we should convert `org-dartlang-sdk` to `dart`.

Requested by @scheglov

**Comment by scheglov** [comment]
Thank you for tracking this!

**Comment by jacob314** [comment]
@bkonyi's API surfacing the mapping between file uris and pretty dart uris solves this exact issue and similar.
Fyi @helin24 who was just using it in IntelliJ.

**Comment by kenzieschmoll** [comment]
related https://github.com/flutter/devtools/issues/3865

**Comment by kenzieschmoll** [comment]
When using the `lookupPackageUris` and `lookupResolvedPackageUris` APIs in DevTools, show a warning if a user is using a vm service protocol version < 7.4.0

**Comment by kenzieschmoll** [comment]
Here is an example of the Flutter IntelliJ plugin using these APIs: https://github.com/flutter/flutter-intellij/pull/6044
