### ISSUE TITLE
Export Network Tab as HAR file

### ISSUE THREAD

**Issue by EthanShoeDev** [flutter/devtools#3806]
Hi, I would really like to be able to export all the filtered requests on the network tab to a HAR file. That way I can import the requests into postman or any other request viewing utility.

**Comment by Hixie** [comment]
Some great work on this was contributed by @SherlockShoe in https://github.com/flutter/devtools/pull/3807, and just needs a little more work (see the review comments in that PR). If anyone has the bandwidth to pick that work up and run with it, I'm sure @SherlockShoe and the rest of us would be very grateful!

**Comment by hrajwade96** [comment]
@kenzieschmoll @Hixie  I was thinking to give this a try,
Can I raise a new pr for this functionality? or do you have some other plans for implementing the export network calls as '.har' functionality.

**Comment by kenzieschmoll** [comment]
@hrajwade96 yes feel free to raise a PR. Thanks! When you are working on this, it would be great if you can implement both code to serialize data from the DevTools network page into a .har file, but also code to deserialize the har file back to the DevTools network data model.

**Comment by hrajwade96** [comment]
Sure @kenzieschmoll, so I have added some implementation and testing it
currently facing below challenge while testing which I am trying to solve, if anyone has idea lmk -
https://github.com/flutter/devtools/issues/7878 (refer to my comment).

After testing I will begin on adding offline support logic outlined here - https://github.com/flutter/devtools/pull/3807#issuecomment-1067062723

**Comment by hrajwade96** [comment]
> Sure @kenzieschmoll, so I have added some implementation and testing it currently facing below challenge while testing which I am trying to solve, if anyone has idea lmk - #7878 (refer to my comment).
> 
> After testing I will begin on adding offline support logic outlined here - [#3807 (comment)](https://github.com/flutter/devtools/pull/3807#issuecomment-1067062723)


No http requests showing up (only InternetAddress) - this issue was due to my vanilla app pointing to an older flutter SDK.
Started working for me now.

**Comment by hrajwade96** [comment]
https://github.com/flutter/devtools/pull/7967 
Initial changes added, working on offline support

**Comment by hrajwade96** [comment]
@EthanShoeDev @Hixie My PR has been merged in master branch.
@kenzieschmoll when would this be available in beta/stable?

**Comment by kenzieschmoll** [comment]
This change will be available in the Flutter main channel by early next week. You can read about Flutter channels and release cadence here: https://github.com/flutter/flutter/blob/master/docs/releases/Flutter-build-release-channels.md#flutters-channels.
