### ISSUE TITLE
Feature request - search (simple CTRL-F) flutter inspector

### ISSUE THREAD

**Issue by diver2** [flutter/devtools#381]
It would be nice to be able to search for a word in flutter inspector.
My case to illustrate: 
trying to change the "Search" word that shows in appbar in showSearch(context, searchdelegate, query). Decided to go to inspector to understand the tree... and then, a simple find "Search" should have taken me to the widget that defines it...
A suggestion, for you guys to put in priority. Here to help if possible.
Cheers
(I'm with last version of flutter/dev tools, flutter 1.2)

**Comment by jacob314** [comment]
Thanks for the feedback! It is very helpful for us to know what features users care about.

**Comment by diver2** [comment]
@jacob314 - I don't know to whom I should send this out, passing to you just in case... 
bug with flutter/dart extension in VS Code...
https://github.com/Microsoft/vscode/issues/70059
Cheers

**Comment by jacob314** [comment]
This is likely the highest priority M16 item.

**Comment by kenzieschmoll** [comment]
this is complete.
