### ISSUE TITLE
Codemirror 0.5.1+5.44.0 has breaking changes.

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#384]
Locked version at 0.5.0+5.43.0 to avoid breakages, but we should address and fix the issues with the next version of codemirror.
![screen shot 2019-03-04 at 12 57 19 pm](https://user-images.githubusercontent.com/43759233/53762482-15dab680-3e7d-11e9-9f47-1e95c8ffb8af.png)

**Comment by devoncarew** [comment]
Yeah, this publish is broken; we're going to re-publish asap; cc @domesticmouse.

**Comment by devoncarew** [comment]
@kenzieschmoll, do you mind re-testing with `0.5.2+5.44.0`?

**Comment by kenzieschmoll** [comment]
looks like that version works. I'll update the pubspec.

**Comment by domesticmouse** [comment]
Apologies for the broken build. Adding documentation to the CodeMirror.dart publish process to catch my error in the future: https://github.com/google/codemirror.dart/pull/91
