### ISSUE TITLE
[Logging] Pressing ENTER in query input in filters modal does not submit form

### ISSUE THREAD

**Issue by crtl** [flutter/devtools#3850]
**Current behavior:**

Under "Logging" > Filters Button > "Filters" Modal
when entering a filter query in the input box and pressing `ENTER` the form is not submitted.
Instead the input field losses focus and nothing else happens.
To submit the form you have to manually click the "APPLY" button.

**Expected Behavior:**
Form should submit when pressing the `ENTER` key in any field because this is the default behavior in browsers.

**Environment:**

Devtools Version: 2.6.0
Flutter Version:
```
[✓] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.19044.1586], locale en-DE)
    • Flutter version 2.5.1 at C:\Users\Marvin\fvm\versions\2.5.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (6 months ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2
```

**Comment by kenzieschmoll** [comment]
Closing as obsolete since the filter text field is no longer included in the modal filter, but rather is accessible from the top level controls.
