### ISSUE TITLE
DevTools CPU profiler pane functionality should be on-par with Observatory

### ISSUE THREAD

**Issue by bkonyi** [flutter/devtools#3861]
**[See Observatory -> DevTools Tracking Issue](https://github.com/flutter/devtools/issues/3858).**

Performance tooling functionality from Observatory that’s not present in DevTools:

- [x] Changing between code/function CPU profiles ([PR](https://github.com/flutter/devtools/pull/4622))
- [x] Call tree filtering
- [x] Tag ordering (VM, User, None) ([PR](https://github.com/flutter/devtools/pull/4693))
- [ ] Last refresh time
- [x] profiler stats (@kenzieschmoll) 
- [x] Go-to source from tree entry
- [x] Method table view (tracked at https://github.com/flutter/devtools/issues/841) (@kenzieschmoll)
- [x] closure display is incomplete (https://github.com/flutter/devtools/issues/5354)

**Observatory CPU Profile View**

![image](https://user-images.githubusercontent.com/24210656/158471844-6dc12d45-d801-4769-929e-8e86c59260f5.png)

**Observatory CPU Profile Method Table View**

![image](https://user-images.githubusercontent.com/24210656/158471712-91a253f8-9d27-4c92-9f44-3ed9cd79e3de.png)

**Comment by kenzieschmoll** [comment]
tracking the last refresh time data at https://github.com/flutter/devtools/issues/5382. This is non critical and marked as such. Closing this issue now that the method table has been added.
