### ISSUE TITLE
Function signatures aren't centered in File Explorer Outline view

### ISSUE THREAD

**Issue by bkonyi** [flutter/devtools#3868]
Function signatures should be vertically centered in the File Explorer outline but appear to be bottom aligned.

Example:
![image](https://user-images.githubusercontent.com/24210656/158478216-72946a01-c524-498c-9477-dba927f4d638.png)

**Comment by CoderDake** [comment]
![image](https://user-images.githubusercontent.com/1386322/164763868-0f85b335-6b61-4d34-a75d-300addb00c6f.png)
It looks like not every method is effected the same. I'm currently looking for what might be causing them to act differently

**Comment by CoderDake** [comment]
My current working theory is that the unicode => is causing the formatting issue
