### ISSUE TITLE
Add general support for jump to source

### ISSUE THREAD

**Issue by bkonyi** [flutter/devtools#3869]
**[See Observatory -> DevTools Tracking Issue](https://github.com/flutter/devtools/issues/3858).**

Observatory allows for users to easily inspect source code from various contexts where file names and line numbers are displayed:

![image](https://user-images.githubusercontent.com/24210656/158478829-ea9b369e-3433-43e9-bb97-ec9bdf0903db.png)

DevTools should support similar functionality. When a URI is selected, DevTools should either:

- Bring up a small source preview window with an option to jump to the debugger
- Jump to the source location in the debugger view

**Comment by kenzieschmoll** [comment]
@bkonyi Is this completed?

**Comment by kenzieschmoll** [comment]
This is completed with object links that switch to a file on the debugger screen. If there are more specific use cases of this functionality we can open new issues.
