### ISSUE TITLE
Add handling for `flutter_web` in addition to `flutter`?

### ISSUE THREAD

**Issue by jakemac53** [flutter/devtools#388]
When connecting to a flutter web app, the `flutter` package is actually called `flutter_web`.

Today the way the `EvalOnDartLibrary` class is used it assumes the `flutter` package exists, and doesn't know about the `flutter_web` package, which causes a LibraryNotFound error to be thrown right after connecting to the isolate.

Ideally devtools would be able to detect this situation and fall back on the `flutter_web` package name.

Alternatively in the proxy we could rewrite the library names but that is not ideal, I think it would be better to fix it in devtools.

**Comment by jakemac53** [comment]
cc @jacob314 lets chat about this when you get in

**Comment by jacob314** [comment]
Thanks for the report. We'll fix this in EvalOnDartLibrary. No reason why it can't just take an alternate fallback package name.
E.g.
EvalOnDartLibrary(["flutter", "flutter_web"])
