### ISSUE TITLE
`build_e2e.dart` doesn't start a local server

### ISSUE THREAD

**Issue by elliette** [flutter/devtools#3898]
Steps to repro:

* Run `dart tool/build_e2e.dart`
* See the following error: `Error when reading 'pkg/dds/tool/devtools_server/serve_local.dart': No such file or directory.`

I'm guessing this occurred when moving devtools server into the dds package.

**Comment by kenzieschmoll** [comment]
I think your dart sdk may be out of date. When is the last time you updated your branch?

**Comment by kenzieschmoll** [comment]
unless you are on flutter master, you may have to point the `LOCAL_DART_SDK` env var at a locally checked out dart sdk from master: https://github.com/dart-lang/sdk/blob/main/CONTRIBUTING.md#getting-the-code. You can also point this environment variable at the dart sdk from the flutter master branch instead.

This eventually won't be an issue as the change that included adding `serve_local.dart` makes its way though the build pipeline.

**Comment by elliette** [comment]
I was pointing to the wrong SDK, thanks! Closing this.
