### ISSUE TITLE
Inspector: Widget tree of widgets in a package doesn't show up

### ISSUE THREAD

**Issue by exaby73** [flutter/devtools#3919]
In the below screenshot, you can see a widget called `SchoolDetailsScreen`. This comes from a package we are using internally. I am getting some layout issues with this package and I wanted to inspect the widget tree but alas the widget tree below the direct dependency of the app isn't visible here. Any idea on how I could enable it?

<img width="550" alt="image" src="https://user-images.githubusercontent.com/50555895/160077237-66955d9d-eed5-4877-a734-b450382e8914.png">

**Comment by exaby73** [comment]
<summary><code>flutter doctor -v</code></summary>
<details>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.3 21E230 darwin-arm, locale en-US)
    • Flutter version 2.10.3 at /Users/nabeelparkar/fvm/versions/2.10.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /opt/homebrew/opt/openjdk@11/bin/java
    • Java version OpenJDK Runtime Environment Homebrew (build 11.0.12+0)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 65.2.4
    • Dart plugin version 213.7227

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] VS Code (version 1.66.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • iPhone 8 (mobile) • 3AEE293D-BA92-4C0A-BDC1-81A9F810BFD7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)   • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)      • chrome                               • web-javascript • Brave Browser 99.1.36.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by kenzieschmoll** [comment]
Are you able to see the widgets below `SchoolDetailsScreen` if you look at this widget in the Details Tree?
![Screen Shot 2022-03-25 at 8 14 51 AM](https://user-images.githubusercontent.com/43759233/160148641-2f3ea621-35e5-4724-b817-cfd01a5aeaeb.png)

@jacob314 is this expected?

**Comment by jacob314** [comment]
Are you running from IntelliJ or VSCode? If you are, you should see SchoolDetailsScreen in the summary tree as long as the package SchoolDetailsScreen is included in one of the directories as part of your project.

If you run from the command line, then DevTools will guess what directory is your project and it may get it wrong so your project is missing directories that you think should be in your project like SchoolDetailsScreen.

We should improve this in the future by giving command line users an escape hatch to specify their project directories from within DevTools.

**Comment by exaby73** [comment]
So the package I am including, comes from git. Though what I don't get is why not pull the directory from the pub cache where all the packages include would already be there? If performance with large widget trees or unwieldy UI is a problem, maybe a toggle could be integrated like the widget selector toggle for viewing trees of widgets outside the immediate code base.

**Comment by kenzieschmoll** [comment]
> Though what I don't get is why not pull the directory from the pub cache where all the packages include would already be there? If performance with large widget trees or unwieldy UI is a problem, maybe a toggle could be integrated like the widget selector toggle for viewing trees of widgets outside the immediate code base.

We only show widgets from user code in the summary tree to keep large trees manageable and performant. The details tree will show every widget in the tree, from both inside your packages and from outside packages. You may be able to use `setPubRootDirectories` to work around this and you want to see widgets from more packages than just your own in the summary tree: https://github.com/flutter/devtools/issues/3941#issuecomment-1109973110. I'm going to close this issue as WAI since https://github.com/flutter/devtools/issues/3941 already tracks the FR to allow a user to set custom project directories.

**Comment by kenzieschmoll** [comment]
@CoderDake is working on a solution for this that will allow you to set pub root directories from the inspector directly: https://github.com/flutter/devtools/issues/4152.
