### ISSUE TITLE
Stop showing inspector widget evals on hover

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#3921]
Feedback from the user survey: "Popups on hover are annoying and don’t scroll".

We could do one of two things here:
1) Replace hover trigger with Right click + evaluate (relies on right click menus working for flutter web)
2) Eliminate hover functionality and rely on the evaluation that is already populated in the console when a widget from the tree is selected.

Option 2) could simplify things for the user - there may be no need to show the same data in two locations (console and in a hover card). Thoughts @InMatrix @jacob314?

**Comment by kenzieschmoll** [comment]
Related https://github.com/flutter/devtools/issues/3920

**Comment by jacob314** [comment]
Showing hover for source code in the debugger page is a key highly requested feature we should not remove. The same feedback about not scrolling applies to that page and we should prioritize polishing our hover overlays.

We do need to be more thoughtful of how we support hover in the inspector. Current impl is heavy handed and needs to be improved or replaced with right click as suggested.
Relying on evaluation could work athough there are edge cases to think through. Hover works for showing complex properties of widgets not just widgets themselves. I don't think those complex properties (e.g. State objects) are shown in the console.

**Comment by kenzieschmoll** [comment]
Broke the scrolling issue out into https://github.com/flutter/devtools/issues/3922 to track.

**Comment by InMatrix** [comment]
I just tried it in VS Code. It seems that the console is not shown when the inspector opens within VS Code as a side panel. So we probably still need to provide an affordance for requesting that information. 

A small tweak we can try now is to reduce the area responding to the hover event to the Text label of the widget instead of the entire row it occupies (i.e., the yellow box instead of the red box in the screenshot below): 
![image](https://user-images.githubusercontent.com/348942/160199775-c06f9b35-b650-4318-8310-c2a675a3536d.png)

This should allow the user to avoid activating the popup by staying out of the labels. 

Another idea is to show a little icon next to the selected widget for activating the popup.

**Comment by jacob314** [comment]
+1 to reducing the hover area. That is an easy fix. 
@InMatrix we could easily show the console in the embedded view in VSCode. We didn't initially due to concerns about already being low on space. We could revisit that.

**Comment by kenzieschmoll** [comment]
I took a quick look and it appears that reducing the hover area isn't as easy as we might have thought. The text is in an Expanded so it takes up the remaining available space in the row. I tried removing the Expanded and adding a Spacer() widget after the RichText widget to take up the remaining space of the row, but this resulted in renderflex overflows. Everything I tried created layout issues with the text ellipsizing in the wrong place or the row overflowing. I can think of hacky ways to do it with measuring text and layering widgets but I don't think we want to do that. 

Backing up a step though - is hover a better option than right click + evaluate? We may improve the problem by reducing the hover area, but the noisy hover cards could still get in the user's way.

**Comment by InMatrix** [comment]
What's the original motivation for adding this hover card? Unless we know how often it's needed, I'd err on the side of not showing it proactively. So yes, right click + evaluate (or another passive affordance) is probably better than hover.

**Comment by umlx5h** [comment]
This is really annoying. I never used it at all.
Could you please change behaiviour or add disable option?

**Comment by kenzieschmoll** [comment]
In the meantime, we could add a setting to allow users to disable the hover eval
