### ISSUE TITLE
Highlight selected widget on device screen without entering the on-screen selection mode

### ISSUE THREAD

**Issue by InMatrix** [flutter/devtools#3926]
Feedback from Q1 2022 DevTools survey: "when I click on a component, I wish to see it's bounding box on the actual screen displayed as well.” We can just highlight the bounding box of the selected widget in the tree view without the user explicitly enabling the on-screen selection mode. 

Cc: @jacob314

**Comment by kenzieschmoll** [comment]
Closing in favor of https://github.com/flutter/devtools/issues/7762
