### ISSUE TITLE
Network tab filled with gray and shows nothing

### ISSUE THREAD

**Issue by Ae-Mc** [flutter/devtools#3940]
Trying to see my requests made from dio package. That's results:
#### First
![image](https://user-images.githubusercontent.com/43097289/161042379-441c7268-8596-41ed-bc23-5c2968546f02.png)
#### Second
![image](https://user-images.githubusercontent.com/43097289/161042426-0d9e5c37-5944-4229-a299-a4066868eede.png)

**Comment by kenzieschmoll** [comment]
Couple questions:
1) Can you open the chrome devtools console and check if there are any errors, and if so can you paste them here?
2) what version of DevTools are you on?

**Comment by luomuhanxue** [comment]
DevTools 2.9.2+1
Flutter 2.10.4
<img width="1280" alt="bug" src="https://user-images.githubusercontent.com/3324353/162107533-c1c23037-58b9-49ab-a111-6b5666328c8b.png">

**Comment by kenzieschmoll** [comment]
@polina-c this looks like a null-safety related error

**Comment by polina-c** [comment]
It seems the issue is outdated: master version of DevTools is 2.12.2 (that is fresher than 2.9.2+1), I cannot repro the issue and the error looks as non-null-safe error.

**Comment by luomuhanxue** [comment]
It's works,every things is ok. but when I click the hot restart button,and click network uri list,the console will show some errors.
![截屏2022-04-18 上午12 54 44](https://user-images.githubusercontent.com/3324353/163725625-a9140435-1c18-4ece-af37-3ce1438aa4be.png)

**Comment by polina-c** [comment]
The errors look as outdated again. What is your flutter version now? Can you try `flutter upgrade`?
