### ISSUE TITLE
Memory screen: implement profile diff.

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#3949]
[go/devtools-memory-page-vision](https://goto.google.com/devtools-memory-page-vision)

Build:
- [x] crud for snapshots
- [x] fakes for memory page
- [x] show snapshot stats
- [x] show diff stats
- [x] show diff details
- [x] export to CSV
- [x] filter by class / library
- [x] Move button 'Clear' 
- [x] Preserve sorting between data sets of classes and pathes

Clean up:
- [x] experiment with Gallery
- [x] test cover
- [x] in-app documentation - http://go/devtools-snapshots-help-wording
- [x] release notes - http://go/wording-for-memory-diff-release-notes
- [x] UX research - [go/devtools-memory-diff-ux-research](https://goto.google.com/devtools-memory-diff-ux-research)
- [x] audit analytics events and perf counters - https://github.com/flutter/devtools/pull/4705

After MVP clean up:
- [x] update documentation: https://github.com/flutter/website/issues/7830
- [x] clean up retired code

**Comment by polina-c** [comment]
Initial PR: https://github.com/flutter/devtools/pull/3234

**Comment by polina-c** [comment]
tasks:
[ ] - add screenshot(s) of diff functionality for Chrome
[ ] - describe diff UI CUJ(s)

**Comment by polina-c** [comment]
Diff snapshot in Chrome devtools:

<img width="930" alt="Screen Shot 2022-04-05 at 3 30 50 PM" src="https://user-images.githubusercontent.com/12115586/161861664-3211a1cb-1191-4e89-9093-08aee4dcb793.png">

**Comment by terrylucas** [comment]
Got it.

**Comment by polina-c** [comment]
[go/devtools-memory-page-vision](https://goto.google.com/devtools-memory-page-vision)
