### ISSUE TITLE
DevTools mocks should use new codegen based version of Mockito

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#3964]
Example file that is using the older style of mocks:

https://github.com/flutter/devtools/blob/c5103d3a43fb9fca5dd88c1c609e9ef3a296514d/packages/devtools_test/lib/src/mocks.dart

We should use the code generation solution for mocks that will generally work more cleanly with null safety and have fewer sharp edges
https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md#solution-1-code-generation

**Comment by kenzieschmoll** [comment]
This is resolved.
