### ISSUE TITLE
Performance Controller Test Flake

### ISSUE THREAD

**Issue by CoderDake** [flutter/devtools#3968]
[This failed test run](https://github.com/flutter/devtools/runs/5973469053?check_suite_focus=true) passed after re-running it.

Any failures in that run can be investigated for test flake.

**Comment by CoderDake** [comment]
I put a debug statement on the failing spec and hit it first time after pushing up.
if you look for "DAKE" you will see the places where I printed the condition of the failing check, so we could compare the values

https://github.com/flutter/devtools/runs/6328517425?check_suite_focus=true

**Comment by CoderDake** [comment]
digging into the diff it looks like b.selectedframe == null

**Comment by CoderDake** [comment]
after digging deeper into this it looks like the expected behaviour is that b.selectedFrame== null should be true.
The mysterious part is that a.selectedFrame should also == null.
I will look further into this to see why it is mysteriously getting set sometimes

**Comment by CoderDake** [comment]
Another flakey performance controller failure
https://github.com/flutter/devtools/runs/6413610721?check_suite_focus=true
Here is another failure of the performance controller
https://github.com/flutter/devtools/runs/6413847260?check_suite_focus=true

**Comment by CoderDake** [comment]
Looking into this further but the above failures may be because I added an ephemeral test storage class and was trying to add it at the top level for all tests envs.
This may be worth looking into when returning to this

**Comment by kenzieschmoll** [comment]
The first failure is a timeout:
```
00:55 +30 -1: /home/runner/work/devtools/devtools/packages/devtools_app/test/performance/performance_controller_test.dart: PerformanceController processOfflineData [E]                                
  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts
  dart:isolate  _RawReceivePortImpl._handleMessage
```
Try merging master - i just submitted a PR that increased the timeout for this test

**Comment by CoderDake** [comment]
While Chatting with Kenzie on Friday I came up with a hypothesis as to why these tests are flakey.
I realized that there is a lot of global state being shared between tests. I believe that these errors may be happening because another test is tearing down or overwriting that state while another is running. I tried rewriting the tests so they have their own state but ran into some weirdness with them still.
When I get a chance I'm going to see if I can isolate these tests to run with j1 for now to see if that at least alleviates the issue.
If that ends up being the case then these may need some longer term consideration about keeping flutter state isolated between unit tests

**Comment by CoderDake** [comment]
So i've been doing a lot of testing to try to suss out what is going on with these flutter environment tests. So far it looks like the following do NOT work to stabilize the tests:
- using j1
- using j1 for just the environment tests
- Forcing the flutter test environment to recreate itself each time  by setting ` bool reuseTestEnvironment = false;` in flutter_test_environment

This leads me to believe that: 
A) State still bleeds between tests regardless of synchronicity
B) That the flutter test environment has a problem initializing such that it is not fully initialized when it says it is.


To suss out the difference between A and B I am going to run a lot of test on just a single flutter environment test  to see if I can ever see this issue with just a solitary test
