### ISSUE TITLE
Clicking isolate selector shows menu item in the wrong place 

### ISSUE THREAD

**Issue by elliette** [flutter/devtools#3985]
Clicking on the isolate selector in the footer opens the menu item at the top left of DevTools: 

![Screen Shot 2022-04-15 at 2 31 04 PM](https://user-images.githubusercontent.com/21270878/163634808-4f683def-2b44-40a7-9a96-8ed63aafa4d9.png)

I see the following assertion failing:
```
Assertion failed:
file:///Users/elliottbrooks/dev/flutter/packages/flutter/lib/src/material/dropdown.dart:363:
16
menuLimits.top + menuLimits.height <= size.height
is not true
```

This is reproducible from master but not on DevTools `v.2.12.2`

**Comment by jacob314** [comment]
That is ugly.
