### ISSUE TITLE
Support HATS for user feedback

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#403]
Aadding HaTS on the Dart web DevTool? HaTS is a little pop-up window for short satisfaction survey question (go/hats). Flutter currently has HaTS on its API docs website to track the satisfaction with documentation.

Having this on the Dart DevTool could be useful too :)

**Comment by kenzieschmoll** [comment]
This form of CSAT survey was considered but decided against due to difficulty in gaining actionable information. We run a DevTools survey 2x a year to track user CSAT and solicit qualitative feedback.
