### ISSUE TITLE
Type error: JSDouble is not a subtype of int

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#405]
Looks like the error is coming from the SourceEditor:

```
main.dart.js:1135 Uncaught TypeError: 18015.384765625: type 'JSDouble' is not a subtype of type 'int'
    at Object.wrapException (main.dart.js:1135)
    at Object.intTypeCheck (main.dart.js:1653)
    at SourceEditor.displayScript$2$scrollTo (main.dart.js:28844)
    at SourceEditor.displayScript$1 (main.dart.js:28879)
    at DebuggerScreen._displaySource$1 (main.dart.js:27712)
    at main.dart.js:28410
    at _wrapJsFunctionForAsync_closure.$protected (main.dart.js:3482)
    at _wrapJsFunctionForAsync_closure.call$2 (main.dart.js:16953)
    at _awaitOnObject_closure.call$1 (main.dart.js:16939)
    at _RootZone.runUnary$2$2 (main.dart.js:19088)
```

**Comment by devoncarew** [comment]
@grouma, are you aware of what artifacts we should be archiving, or how we should be going about reversing dart2js stacktraces? It would be great to be able to get Dart source line numbers from these exceptions.

**Comment by devoncarew** [comment]
Potentially the ScrollInfo.top info we're getting from codemirror is a double (not an int as we're assuming)?

**Comment by grouma** [comment]
I'm using DevTools as a consumer and not actually developing changes within it hence using Dart2JS and not DDC. @sigmundch would know best on how to reverse the traces.

**Comment by sigmundch** [comment]
If you have the main.dart.js.map file, then use this tool from the sdk repo:
```
pkg/dart2js_tools/bin/deobfuscate.dart
```

It takes as an input a file with the content of the stack trace above, and needs the main.dart.js file and main.dart.js.map file available locally right next to it.

The tool also works with minified code, so it will work if you compile with `-O2` or even `-O3` (what we recommend). @devoncarew - last time I forgot to mention that if you still like to debug the tool without obfuscation, but want to use the optimizations in `-O3`, you can also do `-O3 --no-minify`

**Comment by devoncarew** [comment]
@sigmundch, thanks for the pointers!

**Comment by devoncarew** [comment]
> then use this tool from the sdk repo: pkg/dart2js_tools/bin/deobfuscate.dart

Have you considered rolling the functionality into the dart2js binary? Most users won't have access or knowhow to run something from the sdk repo.

**Comment by sigmundch** [comment]
> Have you considered rolling the functionality into the dart2js binary? Most users won't have access or knowhow to run something from the sdk repo.

Our plan was to eventually release the package itself, so users can do `pub global activate dartjs_tools` and use it from there.
