### ISSUE TITLE
VSCode: "Dart DevTools required an active debug session"

### ISSUE THREAD

**Issue by atamocius** [flutter/devtools#408]
When opening DevTools on VSCode, all I am getting is a notification that says:

__Dart DevTools required an active debug session.__

I have already upgraded to the latest stable Flutter version (1.2.1) and have also upgraded to the latest Dart and Flutter extensions for VSCode.

Another thing to note is that I was never prompted regarding activation (ie. "Dart DevTools needs to be installed wiht 'pub global activate devtools' to use this feature"). Since I was not prompted, I took it upon myself to run `pub global activate devtools` (and even `flutter packages pub global activate devtools`), but I am still getting the notification as mentioned above.

**Comment by atamocius** [comment]
`flutter doctor -v` output for reference.

```
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.590], locale en-US)
    • Flutter version 1.2.1 at D:\flutter
    • Framework revision 8661d8aecd (3 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\_android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\_android\sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code, 64-bit edition (version 1.32.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.24.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)

• No issues found!
```

**Comment by atamocius** [comment]
Apologies. This seems to be related to https://github.com/Dart-Code/Dart-Code/issues/1518.

**Comment by DanTup** [comment]
(v1.32.2 of VS Code is live and contains the fix)

**Comment by subramanya4shenoy** [comment]
I use vscode 1.52 on Mac (M1 chip) i see the same issue, any proper fix for this ?
