### ISSUE TITLE
Provider Screen Integration test flake

### ISSUE THREAD

**Issue by CoderDake** [flutter/devtools#4084]
https://github.com/flutter/devtools/runs/6356784092?check_suite_focus=true

**Comment by kenzieschmoll** [comment]
CC @rrousselGit

**Comment by rrousselGit** [comment]
Hum I'm not quite sure what causes the flake.

**Comment by CoderDake** [comment]
Closing since the log is expired now. If this ends up being an issue in the future we can open up a new one.
