### ISSUE TITLE
[question]How to enable this function by code?

### ISSUE THREAD

**Issue by mdddj** [flutter/devtools#4085]
hello i would like to know if it is possible to use dart code to turn this switch on

<img width="298" alt="image" src="https://user-images.githubusercontent.com/29020213/167565753-b8e7fdce-c759-486d-b1ab-9cb6f941cf99.png">

**Comment by polina-c** [comment]
@mdddj , can you please, elaborate?
What are you trying to achieve?
Why click by mouse does not work for you?

**Comment by mdddj** [comment]
@polina-c  Hello, I am making a flutter plugin, and I want to enable the function of selecting widgets in the mobile phone through the function or interface of dart, and then do something, just like the screenshot above, but I don't want the user to be in the idea's Click the button in the plugin, is there any way to open it in the dart code?

**Comment by polina-c** [comment]
So, you want the widgets to change their state as result of some events in your program, right?

To get help on this I suggest to create a very small application that illustrates your question and ask the question on http://stackoverflow.com with tag 'flutter'. Add the code of your application to the question body, to make your context easier to understand.

I am closing the issue, because it is not request for change in DevTools.

**Comment by mdddj** [comment]
@kenzieschmoll   Thanks, this is exactly what I want ☺️

**Comment by lunaticcoding** [comment]
@kenzieschmoll Is there a way to do this without copying half the dev tools over :/ I found calls like:


```dart
    WidgetInspectorService.instance.postEvent(
      'ext.flutter.inspector.show',
      {'enabled': false},
    );
    developer.postEvent(
      'ext.flutter.inspector.show',
      {'enabled': false},
    );
```

is there a way to do it like that? :/

**Comment by kenzieschmoll** [comment]
@bkonyi is there a way to call a service extension without establishing a vm service connection?

**Comment by bkonyi** [comment]
> @bkonyi is there a way to call a service extension without establishing a vm service connection?

You mean there's an app with a VM service available and we want to call a service extension without establishing a web socket connection?

**Comment by hardiklakhalani** [comment]
Could anyone please help me out with the POST Request to toggle this button?
I want to create a VSCode Extension to toggle this using a Hotkey from VSCode-to-DevTools.
I tried digging in devtools code but could not find the endpoint not browser inspector showing post request payload,

**Comment by kenzieschmoll** [comment]
The service extension is 'ext.flutter.inspector.show' with the query parameter 'enabled=true'.
