### ISSUE TITLE
DevTools stopped connecting

### ISSUE THREAD

**Issue by tgreene55** [flutter/devtools#4110]
After one of the most recent flutter upgrades, DevTools no longer connects to my client. I am running both iOS android and iOS simulators, I didn't have any issues until recently, it always just connected to the widget inspector just fine on launch. No instead of widget inspector/devtools connecting the page shows up to "Connect to a Running app" and it won't connect. I've run "flutter clean" and "flutter upgrade" and still not working. 

Devtools work if run from command line but not from VS Code

Here is my flutter doctor in case that helps: 
[✓] Flutter (Channel master, 3.1.0-0.0.pre.745, on macOS 11.5.2 20G95
    darwin-arm, locale en-US)
    • Flutter version 3.1.0-0.0.pre.745 at /Users/taylorgreene/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c248854d17 (14 hours ago), 2022-05-16 23:57:08
      -0400
    • Engine revision fce741dd83
    • Dart version 2.18.0 (build 2.18.0-120.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK
    version 31.0.0)
    • Android SDK at /Users/taylorgreene/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.11+0-b60-7772763)

[✓] VS Code (version 1.62.2)
    • VS Code at /Users/taylorgreene/Downloads/Visual Studio
      Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 860210D9-BD30-4E6D-B52B-0DE7FDCBE124 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)    • macos                                •
      darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)       • chrome                               •
      web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by jacob314** [comment]
Is there any message when DevTools fails to connect? Can you repro with a clean Flutter app project?

**Comment by szilardkantor** [comment]
I get WebSocketChannelException so I can not connect either

**Comment by tgreene55** [comment]
Looks like it can connect now after I updated a bunch of packages and flutter again. And ran flutter clean a few times after updates. So for me the issue has resolved itself for now
