### ISSUE TITLE
Hot reload/restart buttons should be able to appear independently

### ISSUE THREAD

**Issue by jakemac53** [flutter/devtools#413]
Today they are both guarded by a `reloadServiceAvailable` check, but for flutter web we support hot restart but not hot reload.

It would be great if we could still get the hot restart button to appear, even though hot reload isn't supported (yet).

See the code here: https://github.com/flutter/devtools/blob/9bdc7d575a9041468c864492d6f1c681761ab6f2/packages/devtools/lib/src/main.dart#L156

**Comment by kenzieschmoll** [comment]
Thanks, Jake. I'll look into this.
