### ISSUE TITLE
Dev tools does not show developer log message in column view (only when clicking in details)

### ISSUE THREAD

**Issue by suiluj** [flutter/devtools#4130]
I use the `developer.log(...)` command like described here: https://docs.flutter.dev/testing/code-debugging

```dart
import 'dart:developer' as developer;

void main() {
  developer.log('log me', name: 'my.app.category');

  developer.log('log me 1', name: 'my.other.category');
  developer.log('log me 2', name: 'my.other.category');
}

```

I can see the logs in the logging view. But i would like to see the log message already in the column table view. At the moment I have to click on the row entry to see the details in the bottom details.

Current status:

- the table column `kind` shows entries with *my.app.category*
- the message *log me 1* or *log me 2* are only shown in details when clicking on the table row

My wish:

- the message *log me 1* or *log me 2* are shown in the `message` column

Output from `flutter --version`:

```
Flutter 3.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fb57da5f94 (3 days ago) • 2022-05-19 15:50:29 -0700
Engine • revision caaafc5604
Tools • Dart 2.17.1 • DevTools 2.12.2
```

**Comment by changyiyao** [comment]
want it to be fixed.
