### ISSUE TITLE
Use same in-app toggle select widget mode as in Widget Inspector 

### ISSUE THREAD

**Issue by guidezpl** [flutter/devtools#4160]
<img width="65" alt="Screen Shot 2022-06-02 at 12 14 30" src="https://user-images.githubusercontent.com/6655696/171608418-0888389f-5234-4e1c-a3a5-189d698080a1.png"> should be updated to look and behave like  <img width="203" alt="Screen Shot 2022-06-02 at 12 14 12" src="https://user-images.githubusercontent.com/6655696/171608435-6ffed9e0-f078-4100-aa74-1ef24cbed7aa.png">

**Comment by guidezpl** [comment]
Where is the code for the search icon, I looked for `Icons.search` and didn't find anything in flutter/flutter or here?

**Comment by CoderDake** [comment]
@guidezpl is https://github.com/flutter/devtools/blob/master/packages/devtools_app/icons/widget-select-white.png the icon file you are looking for?

**Comment by guidezpl** [comment]
That's useful, thanks, but I'm looking for the where the current blue circle with search icon is located.

**Comment by CoderDake** [comment]
Ah in that case you would be looking for the icon that gets passed to the WidgetInspector's `selectButtonBuilder.
For example I think this would be the one for a CupertinoApp:
https://github.com/flutter/flutter/blob/4cac07b716737457f420513a72f935a789b536f5/packages/flutter/lib/src/cupertino/app.dart#L522

**Comment by elliette** [comment]
Closing in favor of https://github.com/flutter/devtools/issues/8155 (de-duping all open issues into this one).
