### ISSUE TITLE
Review which dependencies could be moved to dev_dependencies to speed up `pub global activate`

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#417]
I *think* that most of our dependencies could be moved to dev_dependencies (since we bundle everything in as JS), which would speed up `pub global activate` significantly. It currently takes 6 seconds on my machine, and 4 seconds of that is (seemingly sequential) HTTP requests for each package. If I understand correctly, IntelliJ *always* runs this when launching DevTools in a session, so it could be 6 seconds of waiting on almost every launch of DevTools for some users.

We'd still need `shelf`, and anything needed to support a real server in future, but I think many of those we have are not required to be pulled to end users (path, pedantic, vm_service_lib, all the CSS ones, etc.).

**Comment by kenzieschmoll** [comment]
I see one more that can be moved: `mockitio`  

@DanTup other than that, is this issue resolved?

**Comment by DanTup** [comment]
I'm not sure if my understanding of this is correct, but we also have things like vm_service_lib, rxdart, platform_detect, etc. as `dependencies`, but my understanding is that the published package on Pub doesn't need any  of these - since we're just shipping a folder full of HTML+JS and a small webserver.

This made me believe that almost all of our dependencies would work in `devDependencies`, but the reason I raised this issue instead of just doing it is that I'm not confident and hoped for someone that understood it better to confirm/reject 😄

**Comment by jacob314** [comment]
We've actually solved this by making package:devtools a placeholder for the devtools content.
