### ISSUE TITLE
Dart DevTools exited with code 127 in VSCode.

### ISSUE THREAD

**Issue by magic3584** [flutter/devtools#4202]
After upgrade flutter to 3.0.1, devTools cannot be opened and the error is:

> Dart DevTools exited with code 127.
> /bin/sh: /Users/Desktop/flutter/bin/cache/dart-sdk/bin/pub: No such file or directory

**Comment by kenzieschmoll** [comment]
@magic3584 does DevTools launch normally if you run your app from command line (`flutter run`)? You should see something like: "The Flutter DevTools debugger and profiler on iPhone SE (3rd generation) is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:54200/EgMhxjn9fbk=/"

@DanTup what are we using pub for in VS code?

**Comment by DanTup** [comment]
We use `pub global run devtools` to run DevTools when the Dart SDK is < 2.15.0.

It doesn't seem correct for `/Users/Desktop/flutter/bin/cache/dart-sdk/bin/pub` to be missing regardless, so I wonder whether there's something wrong with the Dart SDK at `/Users/Desktop/flutter/bin/cache/dart-sdk` (for ex. it's missing), and that also prevents us reading its version number (which means we may treat it as 0.0 and try to use `pub global run`).

@magic3584 could you:

- Run the **Flutter: Run Flutter Doctor** command in VS Code from the command Palette (`F1`) and post the full output here? Note: **This is not guaranteed** to be the same as `flutter doctor` from the command so please be sure to run it from the command palette.
- Confirm what you see in the `/Users/Desktop/flutter/bin/cache/dart-sdk/` and `/Users/Desktop/flutter/bin/cache/dart-sdk/bin` folders?

**Comment by DanTup** [comment]
It occurred to me just now that `/Users/Desktop/flutter/bin/cache/dart-sdk/bin/pub` missing is actually normal for recent SDKs.

So things to check:

- What are the contents of the file `/Users/Desktop/flutter/bin/cache/dart-sdk/version`
- What version of the **Dart** VS Code extension is installed?

**Comment by magic3584** [comment]
Sorry for the late!

The Dart VS Code extension is **3.14.1**

``` shell
[flutter] flutter doctor -v
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-x64, locale en-CN)
    • Flutter version 3.0.1 at /Users/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (5 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✗] Android toolchain - develop for Android devices
    • Android SDK at /usr/local/Caskroom/android-platform-tools/30.0.0
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.

[!] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 38DF446C-AAB0-4FC2-875B-C77AFA58CC99 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 94.0.4606.81

[!] HTTP Host Availability
    ✗ HTTP host "https://maven.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: Operation timed out
    ✗ HTTP host "https://cloud.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: Operation timed out

! Doctor found issues in 4 categories.
exit code 0
```

``` shell
➜  dart-sdk git:(stable) pwd && ls -F
/Users/Desktop/flutter/bin/cache/dart-sdk
LICENSE               dartdoc_options.yaml  revision
README                include/              version
bin/                  lib/

➜  bin git:(stable) pwd && ls -F
/Users/Desktop/flutter/bin/cache/dart-sdk/bin
dart*           dartanalyzer*   dartdevc*       snapshots/
dart2js*        dartaotruntime* resources/      utils/


➜  dart-sdk git:(stable) pwd && cat version
/Users/Desktop/flutter/bin/cache/dart-sdk
2.17.1
```

**Comment by DanTup** [comment]
> The Dart VS Code extension is 3.14.1

This is a very old version of the Dart extension from almost two years ago. The problem is that it does not know that the top level `pub` command was removed and is still trying to use it. Your version of VS Code is also quite old (which might prevent you from seeing newer versions of the Dart extension).

Please upgrade to the latest VS Code (v1.69) and Dart extension (v3.44) and I believe the issue will be resolved.

**Comment by DanTup** [comment]
@magic3584 were you able to upgrade your Dart VS Code extension? Did it resolve the issue?

**Comment by magic3584** [comment]
@DanTup Hi, I have updated the VS Code the error still remains, I will update the extension tonight.

**Comment by DanTup** [comment]
The Dart extension is the important thing to update. Old versions of the extension always called the `pub` command and only newer versions know that `pub` was removed and they must now call `dart pub`.

**Comment by magic3584** [comment]
Thanks guy, I will try it tonight.

**Comment by magic3584** [comment]
Hi @DanTup 
Sorry for the late.
I have updated VS Code to version 1.69.2 and Flutter extension version  to 3.46.0, it works fine.

So appreciate for the help!

**Comment by DanTup** [comment]
Great, thanks for confirming!
