### ISSUE TITLE
using the "next event" buttons should highlight the next event

### ISSUE THREAD

**Issue by gaaclarke** [flutter/devtools#4206]
## observed
When navigating events with the "next event in thread" buttons the next event isn't selected.  That means when you are looking for something you have to click "next event in thread" then click the event that was just jumped to, a 2 click operation.

## expected
Clicking the "next event in thread" should select the next event so the information is visible at the bottom of the screen, like the duration and the parameter.

**Comment by kenzieschmoll** [comment]
This bug was related to the legacy trace viewer in DevTools, which has since been removed. Closing as obsolete.
