### ISSUE TITLE
Flutter Inspector Missing on Safari

### ISSUE THREAD

**Issue by zgosalvez** [flutter/devtools#422]
**Safari 12.0.3:**
<img width="1280" alt="Screen Shot 2019-03-13 at 17 39 19" src="https://user-images.githubusercontent.com/1798166/54268813-05ca8180-45b7-11e9-9022-3c369c780d3a.png">

**Google Chrome 72.0.3626.121**
<img width="1279" alt="Screen Shot 2019-03-13 at 17 39 41" src="https://user-images.githubusercontent.com/1798166/54268814-06631800-45b7-11e9-8189-3a71fd83eb40.png">

**Comment by kenzieschmoll** [comment]
For our development velocity, we only have time to support Google Chrome. We have an open [issue](https://github.com/flutter/devtools/issues/66) to warn users when they hit this scenario. Apologies for the confusion.
