### ISSUE TITLE
Scorecard Actions failing on master with "Bad Credentials"

### ISSUE THREAD

**Issue by CoderDake** [flutter/devtools#4225]
https://github.com/flutter/devtools/runs/7098626415?check_suite_focus=true

all of the workflows on our master branch are failing as a result of the Scorecard Actions entry failing.

I've already tried updating our scorecard actions version in this PR https://github.com/flutter/devtools/commit/9cb2c83b433c0b42c2c4cb77eb68470c67784fb9 as it fixed this issue for another repo. It didn't seem to fix ours though.

**Comment by godofredoc** [comment]
Fixed. This was caused by a repository secret overriding the global secret.
