### ISSUE TITLE
Support filters for logging

### ISSUE THREAD

**Issue by Alby-o** [flutter/devtools#427]
Having a filter on the logging page would be really nice to help isolate logs relevant to what I'm debugging!

**Comment by kenzieschmoll** [comment]
Duplicate of https://github.com/flutter/devtools/issues/785

**Comment by GitHubMurt** [comment]
Can't stand that logging spam, Even If I add some logs `developer.log` dartdev tool refresh log list so quickly that i can't find my logs since it allso scroll down automatically to the bottom Its horrible
