### ISSUE TITLE
Query Params in Network sections

### ISSUE THREAD

**Issue by marcusedu** [flutter/devtools#4276]
Sometimes the http request has many query params that must be analyzed by developer to debug something related of the http requests.
In the Network section no has friendly way to see all query params in the request.

![image](https://user-images.githubusercontent.com/8517730/180241539-df6407fd-4026-4dbc-83b5-d96332767d4e.png)
![image](https://user-images.githubusercontent.com/8517730/180241796-3d42f7f7-052e-4fbb-b1d1-e03a2afe22a9.png)

If possible includes this resource at Network sections.

**Comment by kenzieschmoll** [comment]
Fixed by https://github.com/flutter/devtools/pull/7825
