### ISSUE TITLE
the emulator showes this message when running the app ("System UI isn't responding")

### ISSUE THREAD

**Issue by Harez2020** [flutter/devtools#4290]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: ia32 (32 bit) android
Dart Version: 2.18.0-252.0.dev
Flutter Version: 3.1.0-0.0.pre.1497 / master
Framework / Engine: 160e0712a8 / 93bd92af23
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
This sounds like an issue with your flutter app and not with DevTools. If there is indeed a problem with DevTools, please feel free to re-open and add some more information. Thanks!
