### ISSUE TITLE
Populate memory view with real data

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#43]
The memory view currently has a real first table, but the other tables are fake data.

**Comment by DanTup** [comment]
@devoncarew I made a little progress with this. There's a changeset here:

https://github.com/DanTup/devtools/commit/efd9e7d0ddf80536cfec67e05248715bf7a37fac

It uncomments your code for fetching the snapshot, and then uses the object_graph classes I've "reused" from [sdk/runtime/observatory](https://github.com/dart-lang/sdk/blob/master/runtime/observatory/lib/object_graph.dart). The step to process the snapshot seems *really* slow (like 10+ seconds) and for now I've just made it dump what I think are the root objects with their counts/sizes.

There are some further classes that might make it easier to parse this data (like in https://github.com/dart-lang/sdk/blob/master/runtime/observatory/lib/src/heap_snapshot/heap_snapshot.dart) but I'm not sure how much code we want to just be lifting like this (the classes in that file implement classes from other files!).

I haven't wired this up to the table yet, as I wasn't sure exactly how we want to represent this. Should the first table be all classes, or just things in the root list (is there a difference?). And should this replace the existing data (from `_loadAllocationProfile`)?

**Comment by devoncarew** [comment]
FYI, @terrylucas, @DanTup:

Danny's looking at decoding the heap data for this (Dart web based app); Terry's looking at decoding the same data from the Android Studio plugin (w/ a Java client for the protocol). I just wanted to make sure you're both aware so you guys get the benefit of the other's findings if you hit similar issues.

**Comment by devoncarew** [comment]
> The step to process the snapshot seems really slow (like 10+ seconds) and for now I've just made it dump what I think are the root objects with their counts/sizes.

This is roughly the same as the time the Observatory takes to decode it. Some thoughts:
- having it slow for now is ok; we can speed things up later
- we're compiling with DDC; dart2js may have a better performance profile
- we can look at optimizing the code
- we can look at decoding on a web worker
- we could try and partition the decode, so the event loop isn't blocker for multi-seconds

> There are some further classes that might make it easier to parse this data (like in https://github.com/dart-lang/sdk/blob/master/runtime/observatory/lib/src/heap_snapshot/heap_snapshot.dart) but I'm not sure how much code we want to just be lifting like this (the classes in that file implement classes from other files!).

Borrowing, and cleaning up the impl. for better understandability, seems fine to me.

> I haven't wired this up to the table yet, as I wasn't sure exactly how we want to represent this. Should the first table be all classes, or just things in the root list (is there a difference?).

We could show classes first, and see if we want to iterate on that from there.

> And should this replace the existing data (from _loadAllocationProfile)?

My assumption is yes.

**Comment by devoncarew** [comment]
Temporarily - until we can decode the heap snapshot - perhaps move back to using `_loadAllocationProfile`?

**Comment by terrylucas** [comment]
Okay, trying to understand how to call _getAllocationProfile looks like I
can call this at anytime.  This will return a list of allocated objects is
that right?  I'm assuming I'll need to maintain an object graph should I
poll this request or is the event fired on every allocation?  I presume I
would not hook to a snapshot button but would populate my normal timeline?

**Comment by devoncarew** [comment]
Hey @terrylucas - that note was more for @DanTup; we have some mock data hooked up in the memory view (for this tool) currently. That was a note that we should either 1) remove the mock data, or 2) hook back up the `_getAllocationProfile()` call that we'd previously had. It doesn't take a snapshot in time of the heap, but is a reasonable placeholder until we've decoded the heap snapshot format :)

**Comment by terrylucas** [comment]
Does it seem reasonable for me to use same data so I can hookup UI and data
model too?

**Comment by DanTup** [comment]
I'll remove the mock data; though the allocation profile data is still visible (my mock data was the second table onwards).

@terrylucas The only work I've done so far is here:

https://github.com/DanTup/devtools/commit/efd9e7d0ddf80536cfec67e05248715bf7a37fac

Basically it just gets a snapshot and processes it with the ObjectGraph class (which I lifted from Observatory). I dump some data out to the console, but I haven't done enough investigating to figure out if it's what we want (or if I'm interpreting it correctly).

If you're using Java, porting all of this code may be tedious and error prone.. I wonder if there's a better way? @devoncarew how do Flutter's service extensions work in Observatory - can we load our own into it? If we could expose a simpler API to get the tables of data, it'd avoid us duplicating a lot of this in Java+Dart?

**Comment by devoncarew** [comment]
> Does it seem reasonable for me to use same data so I can hookup UI and data
model too?

@terrylucas - using `_getAllocationProfile` and then requesting objects via `getObject` seems like a reasonable way to get unblocked. It would allow you to build out and validate more of the UI w/o having to decode the heap snapshot.

Be aware that some of the responses from `getObject` will be sentinels, and not the actual object. That's because we won't be working from a snapshot in time, and some of the objects will have been collected after the call to `_getAllocationProfile`.

**Comment by terrylucas** [comment]
Memory profiler view is now live.
