### ISSUE TITLE
Scripts from pub cache should show package: uris instead of file: uris

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#430]
This looks weird (and makes the URIs really long), I think they should show `package:` URIs.

![Screenshot 2019-03-14 at 12 58 44 pm](https://user-images.githubusercontent.com/1078012/54358735-f8fe6a00-4658-11e9-88ba-97aee952087f.png)

**Comment by devoncarew** [comment]
For some reason, Flutter apps report some specific packages as file: uris, and the rest as package uris. They may be doing something creative with pubspecs for those specific packages?

**Comment by DanTup** [comment]
@bkonyi you previously mentioned there were some known issues with URIs - could this be related? If you open Observatory and review the loaded libraries/scripts for a Flutter app, some of them seem to be `package:` URIs and some are not.

**Comment by devoncarew** [comment]
I suspect this is either a pub thing, or something very specific to how the deps on these packages are specified by flutter.

**Comment by kenzieschmoll** [comment]
@jacob314 Based on the survey you sent out regarding users' uri display preference, do we have a clear choice of what we should display?

**Comment by jacob314** [comment]
Users would prefer package: uris or relative paths from the root of their project so something like 
packages/package_name/lib/foo.dart

**Comment by natebosch** [comment]
The ends of those `file://` URIs are cut off - are they all within the `lib/` directory of their respective packages?

**Comment by DanTup** [comment]
Good question! I don't know, but presumably it's possible that loaded scripts from pub cache can be outside of the lib folder? In which case, relative paths from the project root won't work here (they'd end up as `../../../../.pub-cache/hosted/pub.dartlang.org/...`) 🤔

**Comment by natebosch** [comment]
> it's possible that loaded scripts from pub cache can be outside of the lib folder

I very much hope not if it is Dart code. It's possible in the case of flutter assets to reference stuff outside of lib. We really don't like that, we'd prefer if `lib/` was the only directory usable from outside that package, but there isn't much we can do about it at this point.

If the files are outside of `lib/` then we can't construct a `package:` URI.

**Comment by DanTup** [comment]
Whoops, I confused myself - I was thinking about scripts in `lib/src`, which is ofc inside `lib` 🙈

**Comment by elliette** [comment]
<img width="520" alt="Screenshot 2024-11-05 at 2 37 56 PM" src="https://github.com/user-attachments/assets/426f7dd9-666f-4fd0-bcd9-69ff75748564">

We now show package uris when possible
