### ISSUE TITLE
potentially add a landing page

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#433]
This could be a combination of feature overviews and 'what's new in this release'.

**Comment by InMatrix** [comment]
IntelliJ has an official plugin called [IDE Features Trainer](https://plugins.jetbrains.com/plugin/8554-ide-features-trainer). It could be a useful reference.

**Comment by InMatrix** [comment]
Add some context about this issue from email discussion:
> One of the ideas was for an informational / orientation landing page for DevTools; I'm curious what your initial thoughts are there? We do have an issue currently about what page to show by default; the current Inspector page works well for Flutter apps (the majority of apps I'd assume), but less well for Dart CLI apps.

**Comment by devoncarew** [comment]
We could have this landing page be accessible from the 'Dart DevTools' logo text. 

<img width="283" alt="Screen Shot 2019-06-19 at 1 16 18 PM" src="https://user-images.githubusercontent.com/1269969/59797464-95f22400-9294-11e9-9d98-c649375f95dd.png">

The page could contain the connection dialog, and the drag-and-drop dialog. Having a page like this, perhaps served from `/`, would address a few workflow issues. Right now for instance there's no good way to go from a page with a disconnected device (like the debugger page or something) back to the original connection dialog.

**Comment by devoncarew** [comment]
As a note to myself, I have some in progress work on a local `landing_page` branch.

**Comment by kenzieschmoll** [comment]
closing in favor of https://github.com/flutter/devtools/issues/2354
