### ISSUE TITLE
Rework `Allocations` Tab in Memory Page

### ISSUE THREAD

**Issue by bkonyi** [flutter/devtools#4335]
**Feature work:**

- [x] Reimplement allocation profile (e.g., breakdown memory + # of instances by class) (https://github.com/flutter/devtools/pull/4257)
- [x] Reimplement allocation tracing (e.g., record and display stack traces for allocations of specified classes)
    - [x] https://github.com/flutter/devtools/pull/4364

**Cleanup:**
- [x] Sort table by memory consumed rather than by class name
    - [x] In the tab Profile
    - [x] In the tab Tracing
- [ ] explain in documentation what is included in inner (shallow) size of an object
- [x] https://github.com/flutter/devtools/issues/4300
- [ ] Add button 'Deselect All' for tracing
- [x] https://github.com/flutter/devtools/issues/4484
- [ ] Support button 'Clear' and 'Export' on the control pane?

cc @polina-c

**Comment by polina-c** [comment]
Related issue: https://github.com/flutter/devtools/issues/4314

**Comment by InMatrix** [comment]
Is there a separate bug tracking documentation updates for the new memory screen? These two docs will become out of date once this change land in stable: 
- https://docs.flutter.dev/development/tools/devtools/memory
- https://github.com/flutter/devtools/blob/master/case_study/memory_leaks/images_1_null_safe/README.md
