### ISSUE TITLE
Only log network traffic if a user is on the Network page

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#4353]
This is causing memory bloat for user application. See for more details and some suggested solutions (making this opt in, showing a warning on memory page when this is enabled, etc.) - https://github.com/dart-lang/sdk/issues/49506

**Comment by mraleph** [comment]
I suggest this issue to be reprioritised to something closer to ~P1.

**Comment by kenzieschmoll** [comment]
@mraleph fix for this is up for review and will make it into the next beta / stable release.

**Comment by mraleph** [comment]
@kenzieschmoll thank you!
