### ISSUE TITLE
kkkkkkk'

### ISSUE THREAD

**Issue by FarruxMustafo** [flutter/devtools#4373]
<--Please describe your problem here-->
___
**DevTools version**: 2.14.0
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Dart Version: 2.18.0-165.1.beta
Flutter Version: 3.1.0-9.0.pre / dev
Framework / Engine: f28e570c8c / 74ee6b5afd
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
Please reopen and add a description and title if you'd like to report an issue. Thanks.
