### ISSUE TITLE
Add ability to add "Watch" variables on the left panel.

### ISSUE THREAD

**Issue by julian-yang** [flutter/devtools#4401]
The debug tool's "Variables" panel is great for finding top-level variables, but sometimes I have a nested object that I want to keep track of properties as I'm stepping through.  It'd be nice to be able to add my own watch variables.

Chrome inspector has something like this: https://snipboard.io/mJNkBP.jpg

**Comment by kenzieschmoll** [comment]
closing as a duplicate of https://github.com/flutter/devtools/issues/2663
