### ISSUE TITLE
Clicking on file search results does not select file on Flutter master branch

### ISSUE THREAD

**Issue by elliette** [flutter/devtools#4407]
Clicking on a file in the file search results should open and select a file. When on the Flutter master branch, clicking one of the results causes the file search to lose focus, therefore closing the file search dropdown (and not selecting the file). 

I can reproduce this on the Flutter master channel, but not when synced to the [`3.3.0-0.4.pre` beta tag](https://github.com/flutter/flutter/releases/tag/3.3.0-0.4.pre) (from 4 days ago). This seems like it's a regression introduced by a recent Flutter change.

![Screen Shot 2022-08-23 at 12 33 39 PM](https://user-images.githubusercontent.com/21270878/186250128-b7af2fe7-d215-4d97-80de-a4a92aaf3c3f.png)

**Comment by elliette** [comment]
Actually, looks like there are a quite a few changes between the `3.3.0-0.4.pre` beta tag and master: https://github.com/flutter/flutter/compare/3.3.0-0.4.pre...master

**Comment by elliette** [comment]
Looks like this was introduced in https://github.com/flutter/flutter/pull/107262 When using Flutter at the commit right before that commit, clicking a file works. When using Flutter at that commit, clicking a file doesn't work. 

@gspencergoog is it expected that clients will need to change how they are handling focus for things to continue working after https://github.com/flutter/flutter/pull/107262? For context, a lot of the focus logic for DevTools' file search was added in https://github.com/flutter/devtools/pull/3612. 

As a side note, I'm surprised this wasn't caught by this test case: https://github.com/flutter/devtools/blob/master/packages/devtools_app/test/debugger/file_search_test.dart#L35-L76 I will need to do some investigation to figure out why this wasn't caught.

**Comment by elliette** [comment]
Actually thinking about this more:

I wonder if the issue is due to https://github.com/flutter/devtools/pull/3602, which was a workaround we implemented in DevTools to resolve https://github.com/flutter/flutter/issues/97389

It seems like  https://github.com/flutter/flutter/issues/97389 might be fixed by https://github.com/flutter/flutter/pull/107262. @gspencergoog is that correct? Thanks!

**Comment by gspencergoog** [comment]
> It seems like https://github.com/flutter/flutter/issues/97389 might be fixed by https://github.com/flutter/flutter/pull/107262. @gspencergoog is that correct? Thanks!

Yes, that should be the case, at least I hope so.  If you are still having trouble after you remove your workaround, (for instance, if you have your own implementation of autocomplete), you'll need to wrap the list of candidates in a `TextFieldTapRegion` to prevent the list from being considered "outside" of the text field.  If you're using Flutter's autocomplete, then it already does that.

**Comment by elliette** [comment]
Thank you! Wrapping in a `TextFieldTapRegion` works like a charm

**Comment by gspencergoog** [comment]
@elliette So is this issue considered fixed, then?

**Comment by elliette** [comment]
Yes, thanks! This is set to be marked as fixed once https://github.com/flutter/devtools/pull/4409 is merged

**Comment by elliette** [comment]
> Yes, thanks! This is set to be marked as fixed once #4409 is merged

Oops, the Flutter changed required is on the `master` branch, but not in the latest `beta`. Reaching out to Flutter release team to try to figure out when this will be in beta

**Comment by CoderDake** [comment]
@magacao I believe that #4409  is in `DevTools 2.19.0` so you should probably see the fix when using `Flutter 3.6.0-0.1.pre`
