### ISSUE TITLE
Add DevTools tests to Flutter Customer Test Registry

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#4433]
Test registry repo: https://github.com/flutter/tests.

This was motivated by https://github.com/flutter/devtools/issues/4407 where we were broken by a change to Flutter master, and where that change simultaneously contained the solution for the breakage.

**Comment by Piinks** [comment]
I'll need tor write a different test script than the one that already exists. I will see about doing that tomorrow.

**Comment by Piinks** [comment]
I added a test script in https://github.com/flutter/devtools/pull/5785 to run tests in flutter/tests, but in https://github.com/flutter/tests/pull/258 we found many of them were timing out or failing on mocks npt being generated properly. Here is one of those results:

https://cirrus-ci.com/task/5895187193397248

**Comment by kenzieschmoll** [comment]
The best step forward here would be to tag a representative set of tests to run with the flutter test registry. Running all of our tests will likely be too slow. I will update this comment with good candidates to add the `flutterTestRegistry` tag to:
- cpu_profile_model_test.dart
- extent_delegate_list_test.dart
- inspector_service_test.dart

**Comment by kenzieschmoll** [comment]
Work is in progress for this at https://github.com/flutter/tests/pull/267. Currently blocked on https://github.com/flutter/flutter/pull/135726.
