### ISSUE TITLE
Is there an option to switch between the new JsonViewer format and the old JSON format in Network response?

### ISSUE THREAD

**Issue by xieenming** [flutter/devtools#4442]
In Flutter DevTools 2.15.0 , it adds a new feature, "a Json viewer with syntax highlighting for network responses", see

https://docs.flutter.dev/development/tools/devtools/release-notes/release-notes-2.15.0 and https://github.com/flutter/devtools/pull/4167

But it seems that it does not have an option to switch between the new JsonViewer format and the old JSON format in Network response.

When I say old JSON format, it means something like below : 

```json
{
    "err": {
        "ec": 0,
        "em": "ok",
        "dm": "ok"
    },
    "ret": {
        "has_prev": false,
        "has_next": false,
        "limit": 100,
        "offset": 0,
        "data": [
            {
                "id": "box_1001",
                "services": []
            },
        ]
    }
}
```

There is a button on the right to copy the content of Network response, when I paste the content into some Editor (e.g. VS Code), it will be JSON format.

I think it is not convenient, because the new JsonViewer format I have to expand manually each level to view all the data. Sometimes I want to view the whole JSON format like the old JSON format does.

Why does Flutter DevTools team provide a new format without letting user to switch between new format and old format ? Someone maybe still loves the old format.

Thanks a lot!

**Comment by jacob314** [comment]
Fyi @bkonyi

**Comment by bkonyi** [comment]
I thought we had added a "copy to clipboard" button that would give users access to the original JSON body, but I guess that didn't end up happening. That's probably the right thing to do here, since I don't think it makes sense to add back the original viewer. Maybe @CoderDake can throw something together?

**Comment by bkonyi** [comment]
I think the solution here is to add `Expand/Collapse All` buttons to `JsonViewer` and maybe default to expanding the JSON tree. Would that address your main concern @xieenming?

**Comment by kenzieschmoll** [comment]
+1 to adding expand all / collapse all to this viewer.

**Comment by xieenming** [comment]
@bkonyi @kenzieschmoll @jacob314 

Thanks a lot for your quick reply.

It is good to have "Expand/Collapse All buttons to JsonViewer".

But if you could also add a button or something to be able to switch between the new JsonViewer format and the old JSON format? Because currently, if I want to view the old JSON format content, I have to click the "Copy" button at the top-right corner, and paste the content to an editor (for example, VS Code) and format the code to view the nice JSON format content. It is not convenient.

Thank you very much.

**Comment by kenzieschmoll** [comment]
Does the work being done here address your concerns? https://github.com/flutter/devtools/pull/5816

**Comment by xieenming** [comment]
DevTools version 2.20.1

**Comment by kenzieschmoll** [comment]
The work in https://github.com/flutter/devtools/pull/5816 is still in progress, but I was asking if you could take a look and see if that work would address the concerns you raised in this issue. The PR description has an explanation and screenshots.

**Comment by xieenming** [comment]
@kenzieschmoll OK. Thanks a lot.
I feel that the work in #5816 could address the concerns.
Thanks~~
