### ISSUE TITLE
Hot Reload / Hot Restart buttons missing after pressing Refresh

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#446]
As @devoncarew observed earlier, I see these buttons vanish if I hit Refresh in my browser while attached to a Flutter app. If I click something like "Refresh Tree" they come back.

**Comment by kenzieschmoll** [comment]
Is this the behavior you are referring to? When we refresh the page, we need to ensure hot restart and hot reload are supported before we show the respective buttons. 

I think defaulting to not showing the buttons is better than defaulting to showing them and then removing them if we don't find the hot restart / hot reload services.

![hot_restart_reload](https://user-images.githubusercontent.com/43759233/63385264-755a4f00-c355-11e9-851b-d42445bcd47b.gif)

**Comment by DanTup** [comment]
The issue I saw was that they never came back until I did something like clicked Refresh tree (eg. they didn't do it after reconnecting). It's been a while though, I'll do some testing to see if I can repro and post back.

**Comment by DanTup** [comment]
Can't reproduce. Not sure if flaky, or it's just been fixed at some point accidentally.

I'll close, we can re-open if it's seen again so we know it still happens.
