### ISSUE TITLE
Flutter network view debugger not tracking network requests. Stops tracking requests after reload. 

### ISSUE THREAD

**Issue by Gantushig77** [flutter/devtools#4472]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Dart Version: 2.18.0
Flutter Version: 3.3.0 / stable
Framework / Engine: ffccd96b62 / 5e9e0e0aa8
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
@CoderDake just fixed this issue in https://github.com/flutter/devtools/pull/4438, so this should be out in the next DevTools release (note that DevTools releases on the Flutter release schedule, so our latest released version is in Flutter master and that is where you'll see this change soon).
