### ISSUE TITLE
Add YourKit like merged paths to the memory page

### ISSUE THREAD

**Issue by scheglov** [flutter/devtools#4492]
https://www.yourkit.com/docs/java/help/merged_paths.jsp

**Comment by kenzieschmoll** [comment]
FYI @polina-c @bkonyi

**Comment by polina-c** [comment]
We plan to show retaining paths as part of these efforts:

https://github.com/flutter/devtools/issues/3951
https://github.com/flutter/devtools/issues/3949

**Comment by kenzieschmoll** [comment]
The DevTools memory page now supports showing retaining paths for objects in the heap.
