### ISSUE TITLE
don't show weight model 

### ISSUE THREAD

**Issue by wangyangke** [flutter/devtools#4494]
version:
android studio -4.1.1
dart -2.14
flutter-2.5.0
Run the debug mode with real machine debugging and open Flutter DevTools with no information in the Flutter Inspector,please help me

**Comment by wangyangke** [comment]
The widget tree is not shown in widget mode

**Comment by kenzieschmoll** [comment]
This issue looks like it occurred on an old version of DevTools. Are you still experiencing this issue with DevTools on the latest Flutter stable? If so, please reopen and we will take a look. Thanks.
