### ISSUE TITLE
helping please

### ISSUE THREAD

**Issue by Deo-Cell** [flutter/devtools#4498]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: x64 (64 bit) linux
Dart Version: 2.18.0
Flutter Version: 3.3.1 / stable
Framework / Engine: 4f9d92fbbd / 3efdf03e73
Connected app type: Flutter native (debug build)

**Comment by jacob314** [comment]
Please describe the problem you are seeing with DevTools.

**Comment by CoderDake** [comment]
@Deo-Cell Could you please add some more information to help clarify what you need help with?
Feel free to reopen this issue or file a new one at any time :)
