### ISSUE TITLE
Clarify which frame raster stats correspond to

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#4517]
When the Raster Stats tab is selected, it is not clear which frame the raster stats are for.  We could include the frame # in the UI and or show "Now raster stats for current frame" if a frame without raster stats is selected.

**Comment by kenzieschmoll** [comment]
Right now, the Raster Metrics tab does not correspond to any particular "frame" in the Flutter frames chart at the top of the page. This is one of the enhancements we'd like to add to the tool (@iskakaushik). Right now, the Raster Metrics tab lets you take a single snapshot of whatever is visible on the current screen of your app, which could have layers from multiple frames.

**Comment by kenzieschmoll** [comment]
This feature has been removed from DevTools, so closing this as obsolete.
