### ISSUE TITLE
Better integration with IDEs 

### ISSUE THREAD

**Issue by CoderDake** [flutter/devtools#4533]
Better integration with IDEs to support two way communication between IDEs and DevTools. This could be used for a variety of features, including selecting widgets in the inspector when they are selected in code (from ide or debugger).

**Comment by CoderDake** [comment]
Suggested order of operations
order of operations I'd take here:
1) clarify user journeys we want to cover
2) meet with Ben  to gather some of his thoughts around this problem and the DDS api. (invite kenzie too)
3) write up design doc & get sign off from IDE team DevTools team, and Vm team ./

**Comment by jacob314** [comment]
The core user journey is that DevTools and package:flutter need an API to tell IDEs to open a particular file + line + column.
