### ISSUE TITLE
Consult with UX on memory diffing user journey

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#4539]
Meta issue to track questions we want to discuss with UXR before shipping:

- [ ] Should we preserve the selected class between snapshots (e.g. I have snapshot 1 and 2. I select class A in snapshot 1. Upon switching to snapshot 2, class A is automatically selected). There are pros and cons to this. Maybe we could consider a setting, but what should be the default behavior?
- [ ] Is it ok to apply sorting to all snapshots or user will ever want to have different sorting for different snapshots?

**Comment by polina-c** [comment]
Closing as duplicate, because the questions are covered in [go/devtools-memory-diff-ux-research](https://goto.google.com/devtools-memory-diff-ux-research), linked in https://github.com/flutter/devtools/issues/3949
