### ISSUE TITLE
Hover cards do not automatically close

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#4571]
When you hover over a variable in the source view of the debugger a hover card will be shown. If you move your mouse into this card then the card is not removed until you hover back over the originating variable.

This may be related to https://github.com/flutter/devtools/issues/3839.

**Comment by kenzieschmoll** [comment]
@CoderDake

**Comment by CoderDake** [comment]
This should be resolved in https://github.com/flutter/devtools/pull/4627 please let us know if this issue is still present past 2.19.0-dev.1
