### ISSUE TITLE
Investigate if we can share resources between github actions jobs

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#4592]
Right now, every job pays the cost of cloning the flutter repo and building flutter tools (right now twice - see https://github.com/flutter/devtools/issues/4591). This is part of the bots.sh script. We should investigate if there is a way to perform this action in a setup step so that we only have to pay this cost once, not for every job.

**Comment by CoderDake** [comment]
@kenzieschmoll  Looks like github has https://github.com/actions/cache If we want to cache files between jobs. This looks like it would be pretty easy to setup and would probably have some pretty drastic improvements to run time.

GH Actions have the ability to have jobs depend on each other, so we could start with the build step, then all of the other jobs could start together after that initial step
----------
Alternatively I think if we want to punt the work out of the actions completely we could use docker images to create environments that match what we want to start with exactly. Then we would just have the cost of downloading the updated image, that we want to operate against.

**Comment by kenzieschmoll** [comment]
> we could use docker images to create environments that match what we want to start with exactly

How would we create the environments? would this happen on each PR? The flutter environment we want to use will change quite often (daily) so we should take that into consideration.

My initial thoughts are we should start with option 1) to have an initial gh action job to run the build step if this is easy to setup, and then if we still are struggling with testing time, we can investigate the docker option.

**Comment by CoderDake** [comment]
I think you are right that we start with option 1.

 I also just did a quick read of the cache docs and it looks like it might even persist between separate runs, which would be pretty mint. I'm not 100% on this so it will need a bit of testing to confirm this.
 
 Looks we will have a limit of 10GB total for our repository. Do you know how much data we will want to be caching?

----------

I took a second to double check something about docker and realize now that it isn't viable anyways. We wouldn't be able to run macos docker images so it would make it pretty useless for us. We have the priority of needing to run on the machines anyways. Sorry about not realizing this at first :P

**Comment by kenzieschmoll** [comment]
The flutter SDK should not have an issue fitting under a 10GB limit.

**Comment by kenzieschmoll** [comment]
done - we now cache the flutter sdk we use for actions jobs
