### ISSUE TITLE
Create a tool for getting the size of a Widget on a device

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#460]
It would be very helpful to have a tool that could measure a Widget in a running App.

Sometimes I have `RaisedButton` and its size isn't matching the one in my Designs Specs, so I would like to easily get its dimensions, but this isn't simple using Flutter Inspector.

**Comment by aytunch** [comment]
Size + position while at it

**Comment by NoizyCr1cket** [comment]
You might be able to find this in the inspector by drilling down to `renderObject`:

![Screen Shot 2019-12-24 at 4 55 00 PM](https://user-images.githubusercontent.com/24799567/71426396-76d2b580-266e-11ea-9463-d9618fb399a7.png)

**Comment by feinstein** [comment]
As I said **this isn't simple using Flutter Inspector**

**Comment by kenzieschmoll** [comment]
This is possible with the inspector today and will become even more prominent with the Inspector V2 work.
