### ISSUE TITLE
dfhgddfg

### ISSUE THREAD

**Issue by joelapache** [flutter/devtools#4612]
// Copyright 2018 The Flutter team. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:english_words/english_words.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    final wordPair = WordPair.random();
    return MaterialApp(
      title: 'Pannel d\'authentification',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Pannel d\'authentification'),
        ),
        body: const Center(
          child: Text(wordPair.asPascalCase),
        ),
      ),
    );
  }
}
[Sti_Trace.log](https://github.com/flutter/devtools/files/9792710/Sti_Trace.log)
)

**Comment by CoderDake** [comment]
@joelapache It is unclear what this issue is addressing. If you are having an issue with flutter/devtools, could you please provide more context?

**Comment by CoderDake** [comment]
Closing until there is more context about what the issue might be
