### ISSUE TITLE
Update `v2.18.0` tag to a buildable commit.

### ISSUE THREAD

**Issue by BrianCraig** [flutter/devtools#4630]
Hi! I'm running a github action to build and export devtools on https://github.com/BrianCraig/flutter-devtools-binary, and the current commit at the tag `v2.18.0` [does not compile](https://github.com/BrianCraig/flutter-devtools-binary/actions/runs/3292821949/jobs/5428638747), nor the commit [9345b11](https://github.com/BrianCraig/flutter-devtools-binary/actions/runs/3293112904). The first i found was the commit 6284d4d because the fix of the Perfetto assets. [here is the working build](https://github.com/BrianCraig/flutter-devtools-binary/actions/runs/3293201614).

I cannot make a PR for updating the tag, i reccomend to update `v2.18.0` to 6284d4d.

Thanks, Brian

**Comment by CoderDake** [comment]
@BrianCraig something about this makes me wonder if something odd happened in the pub cache. The errors seem like there are conflicting versions present.

In regards to the current v2.18.0
Could you please try adding a `flutter clean` step before your build steps in your [workflow file](https://github.com/BrianCraig/flutter-devtools-binary/actions/runs/3293112904/workflow#L22)?

This would allow us to see if the pub_cache getting cleaned up would allow things to resolve themselves

**Comment by CoderDake** [comment]
For some added context, I checked out the 3.3.0-0.5.pre flutter version that your workflow uses and was able to build the web build on my local machine without issue.
