### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by guilherme-noguiera-ferraz1203** [flutter/devtools#4637]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: Web windows
Dart Version: 2.18.2
Flutter Version: 3.3.5 / stable
Framework / Engine: d9111f6402 / 3ad69d7be3
Connected app type: Flutter web (debug build)

**Comment by CoderDake** [comment]
@guilherme-noguiera-ferraz1203 We will need a little bit more information about any issues you may be having with the Devtools.
Please feel free to reopen this ticket when you add more details about the issue you may be having.
