### ISSUE TITLE
while trying verify OTP im getting this  below mentioned Error

### ISSUE THREAD

**Issue by rajcrozz0594** [flutter/devtools#4649]
<--Error: Expected a value of type 'String', but got one of type 'Null'
 -->
___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: Web linux
Dart Version: 2.18.2
Flutter Version: 3.3.5 / stable
Framework / Engine: d9111f6402 / 3ad69d7be3
Connected app type: Flutter web (debug build)

**Comment by CoderDake** [comment]
@rajcrozz0594 Could you please provide some more information about what part of Devtools is failing for you?
Feel free to reopen this issue, when you get a chance to provide some more context :)

**Comment by rajcrozz0594** [comment]
![Screenshot from 2022-11-08 11-37-52](https://user-images.githubusercontent.com/115996502/200488209-a0c2c254-4b7b-4cb0-99ac-88c957116f83.png)




hi !  I'm  new to programming language...... 
Im try to login throw otp..... after submitted the Otp I'm  getting this kind of error in debugConsole..
my teammates using this  same code, but they're not getting any issues.... could you please help me to solve this issue
