### ISSUE TITLE
Flutter inspector problem

### ISSUE THREAD

**Issue by bzdbss** [flutter/devtools#4650]
Flutter version 3.3.5 on channel stable 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (5 days ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

Since last update Flutter Inspector doesn't work properly,
Sometimes doesn't show the widgets and some times does show the widgets but Select Widget Mode is unavailable

Thanks in advance
Daniel

**Comment by CoderDake** [comment]
@bzdbss has your app has been paused, on a breakpoint, when you are experiencing these issues?

**Comment by bzdbss** [comment]
No
There are times it first work ok and then after hot restart suddenly the
widget tree is empty or even if it show the widget tree is not possible to
select a widget from the app (web app)

**Comment by CoderDake** [comment]
I've spent some time trying to reproduce this and still haven't had any luck.
@bzdbss could you please provide the following information, and any screenshots or recordings of the issue occurring?
1. What device are you running your application on?
2. how are you opening the devtools inspector?
3. how are you hot restarting your application?
4. Do you still run into the same issue if you run a different application, like the [Flutter Gallery](https://github.com/flutter/gallery)
5. Does switching to a previous version of flutter resolve this issue for you? If so which versions work for you?
6. Any other information or screenshots that might help reproduce this would be greatly appreciated.

**Comment by bzdbss** [comment]
Hello,
The problem was solved by performing the following actions
- Upgraded flutter to latest version
- Reinstall android studio
- run flutter pub upgrade --major-versions

Thanks for your support
Daniel

BTW: "Waiting for connection from debug service on Chrome... " takes about
20 to 25 seconds when first running the program in debug mode. Is this
normal or is there a fine tuning that can be done ?

**Comment by CoderDake** [comment]
@bzdbss It looks like this may be "normal" behaviour as others have mentioned similar slowness.
This issue seems similar to the slowness you have mentioned: https://github.com/flutter/flutter/issues/84353

**Comment by CoderDake** [comment]
Also I'm happy that you are back up and running again :D
