### ISSUE TITLE
Add performance panel for web apps

### ISSUE THREAD

**Issue by elliette** [flutter/devtools#4652]
We've received a request from a customer to add the performance panel when debugging Flutter Web apps. 

Opening this as a tracking bug for that work.

**Comment by jacobsimionato** [comment]
We'd absolutely love this for Google apps, mostly to quantify the cost of different parts of the render process, e.g. build, layout, paint etc when fixing jank issues in web apps. We can try using devtools with the mobile versions of these apps, but given the platforms have very different characteristics, it'd be very helpful to be able to drill into the Web traces specifically. Chrome Devtools does help a lot, but it can be difficult to digest the information it provides.

See internal bug b/281577784 and the linked doc there for more context.

**Comment by kenzieschmoll** [comment]
Currently the vm service APIs that are used in the performance page are:
`getVMTimelineMicros`, `getVMTimeline`, `setVMTimelineFlags`. These would need to be implemented in dwds for the chrome equivalent. 

The `onTimelineEvent` stream is already listened to in the service_manager setup, so I assume this already works for DWDS? But if not, that would need to be implemented as well.

**Comment by elliette** [comment]
Opened https://github.com/dart-lang/webdev/issues/2110

@jacobsimionato are you interested in doing performance profiling in release mode? Or are you also interested in profiling in debug mode?

DWDS currently only supports DDC-compiled apps (debug mode) so unfortunately supporting release mode would be more work than just adding the missing APIs.

**Comment by jacobsimionato** [comment]
Hi sorry I missed this comment, Elliott. Yep we're definitely interested in profiling in release mode e.g. with dart2js seeing as DDC doesn't provide representative performance. There is some benefit to profiling in dev mode so we can at least figure out what is rebuilding and why, so that could be a good interim stage.

How does this work for mobile apps? We do support connecting devtools somehow in profile mode, I guess?

**Comment by kenzieschmoll** [comment]
> How does this work for mobile apps? We do support connecting devtools somehow in profile mode, I guess?

Yes we can connect to debug and profile builds for native apps.

**Comment by kenzieschmoll** [comment]
This is supported by pointing users to Chrome DevTools, which now shows dart timeline events
