### ISSUE TITLE
Modify isFlutterWebApp() once flutter and flutter_web merge.

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#466]
Right now we look for the package:flutter_web lib to determine whether we are connected to a Flutter Web app. This will not work once flutter merges with flutter_web.

If, at the time of the merge, certain pages still need to be disabled for Flutter web, we will need to come up with a different way to distinguish between Flutter and Flutter web.

**Comment by jacob314** [comment]
This issue was fixed but the bug wasn't closed.
