### ISSUE TITLE
login

### ISSUE THREAD

**Issue by iitshala** [flutter/devtools#4666]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: x64 (64 bit) windows
Dart Version: 2.18.2
Flutter Version: 3.3.6 / stable
Framework / Engine: 6928314d50 / 3ad69d7be3
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
Without more information, we won't be able to investigate this issue. Please feel free to re-open if you have more information to share about the problem you encountered. Thanks!
