### ISSUE TITLE
request  not showing in devtool

### ISSUE THREAD

**Issue by libsonprompttech** [flutter/devtools#4682]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Dart Version: 2.18.2
Flutter Version: 3.3.3 / stable
Framework / Engine: 18a827f393 / 5c984c26eb
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
@libsonprompttech without more information we won't be able to help with this issue.
Please feel free to reopen this issue with more information, or to open a new one with more information :)
