### ISSUE TITLE
Error: OperationError

### ISSUE THREAD

**Issue by rajcrozz0594** [flutter/devtools#4709]
after submit the OTP ,i'm getting this Error.
![Screenshot from 2022-11-08 13-54-19](https://user-images.githubusercontent.com/115996502/200516410-92879573-40fc-4b58-aa86-dc8d4c1647b1.png)

**Comment by CoderDake** [comment]
Hey @rajcrozz0594 could you please provide some more information about how this is happing?
How do you submit the OTP?
Is the error always triggered?
How are you specifically triggering it?

Any extra information here, can help us narrow down where any issues might be occuring.
