### ISSUE TITLE
Timeline performance/functionality should match Observatory

### ISSUE THREAD

**Issue by zanderso** [flutter/devtools#4711]
Performance of DevTools timeline makes it difficult to use. I've discussed this in the past with @bkonyi and @kenzieschmoll, so I know there's a plan for this, but I wanted to be sure this was being tracked under the `observatory migration` label, and didn't see it there already. Sorry if this is a duplicate.

In addition to performance of the timeline view itself, Observatory also has the functionality of saving/loading traces with no attached app that we use to share traces for debugging purposes.

**Comment by kenzieschmoll** [comment]
Closing this now that the embedded Perfetto effort is complete. Missing cpu samples are tracked here: https://github.com/flutter/devtools/issues/4755
