### ISSUE TITLE
Unconstrain our archive dependency

### ISSUE THREAD

**Issue by CoderDake** [flutter/devtools#4728]
An issue with archive is causing our build to break, see: https://github.com/brendan-duncan/archive/issues/221 

When that issue is resolved we should be able to remove the `archive: <3.3.3`  constraint that was  added in: https://github.com/flutter/devtools/compare/master...CoderDake:archieve?expand=1

**Comment by kenzieschmoll** [comment]
This is still happening with package:archive 3.3.4. Constraint added back in https://github.com/flutter/devtools/pull/4751.

**Comment by parlough** [comment]
Fixed by https://github.com/flutter/devtools/commit/d457d49002c97f4320f2e5adbbe6272eb6f2035e
