### ISSUE TITLE
ASFLUTTER

### ISSUE THREAD

**Issue by MehmetYungul** [flutter/devtools#4746]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: x64 (64 bit) android
Dart Version: 2.18.4
Flutter Version: 3.3.8 / stable
Framework / Engine: 52b3dc25f6 / 857bd6b74c
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
What is the issue you are encountering? I'm going to close this issue, but feel free to reopen and add details of your problem so that we can help.
