### ISSUE TITLE
Misleading widget creation location leads to bad debugging experience

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#4772]
This is a tracking issue on the devtools side for this issue: https://github.com/dart-lang/sdk/issues/50067. The TL;DR is that the widget creation location for widgets created in an extension method is misleading for debugging purposes. @jacob314

**Comment by elliette** [comment]
I don't think there is anything to do on the DevTools side here. Extension methods annotated with `@widgetFactory` will set the creation location to the call site, not to the extension method.
