### ISSUE TITLE
No-content message in desktop app should be aligned the same way as content.

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#4773]
When screen is large, eyes search for the content at the top left and thus do not see the message in the center.

Suggested:
<img width="1646" alt="Screenshot 2022-11-17 at 2 21 15 PM" src="https://user-images.githubusercontent.com/12115586/202572687-46154e70-b39b-455b-9bf1-a836985ad65f.png">

Current:
<img width="1660" alt="Screenshot 2022-11-17 at 2 22 13 PM" src="https://user-images.githubusercontent.com/12115586/202572713-8181d484-982c-4556-b0ba-b0cbdcef07a9.png">

**Comment by InMatrix** [comment]
I don't feel strongly about either alignment, but I'm leaning towards center-alignment strictly for describing actions the user need to take to see information in that view. The size of the text can be larger to make it more noticeable.

**Comment by InMatrix** [comment]
In addition, it could be useful to add an example action to the help text. For example, we can add a link "Example: select the first row" next to the help text.

**Comment by InMatrix** [comment]
The main reason I'm leaning towards center-alignment is that it visually distinguish this type of instruction from regular text more. But that's not the only way this can be achieved. Using an icon preceding the text could be another option.

**Comment by polina-c** [comment]
Thanks. Resolving.
