### ISSUE TITLE
Performance > timeline events: hard to find out size of one column

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#4785]
<img width="1234" alt="Screenshot 2022-11-18 at 9 50 35 AM" src="https://user-images.githubusercontent.com/12115586/202770281-81ee3be8-cc92-4dde-93dc-d69b254521d5.png">

**Comment by kenzieschmoll** [comment]
There is a tooltip over each timeline event that shows the duration of the event. Since we are moving away from this trace viewer soon anyway, I'm going to close.
