### ISSUE TITLE
Poor performance when selecting "Group by: User tag" in the cpu profiler

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#4807]
The UI freezes for a bit while we execute the grouping / filtering logic

**Comment by bkonyi** [comment]
Can you provide some reproduction steps? I don't encounter any performance issues locally.

**Comment by kenzieschmoll** [comment]
I was running with a Flutter app that had been running for a while, so likely had a full buffer of CPU samples and deep samples due to it being a flutter app.

**Comment by bkonyi** [comment]
I just ran with gallery and enountered general performance issues when building profiles, so I don't think this is specific to the "Group by" filters. If we improve performance for building individual user tag profiles, the "Group by" filters will see a corresponding performance improvement.
