### ISSUE TITLE
Add a control to show release notes in DevTools

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#4847]
Right now these are only shown once the first time a user opens a DevTools version, but it would be useful to be able to re-open these release notes.

**Comment by polina-c** [comment]
Or, we can just convert version number to link:

<img width="616" alt="Screenshot 2022-11-29 at 2 22 07 PM" src="https://user-images.githubusercontent.com/12115586/204661361-19932818-e0ae-4ded-9c9d-58f6de1aae72.png">
