### ISSUE TITLE
Is it possible to change tab Network/Request to its original state, to have a possibility of coping request content 

### ISSUE THREAD

**Issue by ivanovai0310** [flutter/devtools#4860]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Dart Version: 2.18.0
Flutter Version: 3.3.0 / stable
Framework / Engine: ffccd96b62 / 5e9e0e0aa8
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
In the latest version of DevTools (which is available on Flutter master), there is a button to copy the request, similar to the button to copy the network response. It was added here: https://github.com/flutter/devtools/pull/4509. If this does not solve the issue you are describing, please re-open this issue. Thanks!
