### ISSUE TITLE
Perfetto - message about cookies is confusing.

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#4877]
1. It is unclear that Timeline events is a frame from another application
2. It is unclear what to do if user does not agree for cookies

The message should explain both questions.

<img width="1237" alt="Screenshot 2022-12-02 at 10 34 17 AM" src="https://user-images.githubusercontent.com/12115586/205363502-5ae27cc8-bf99-4158-a8f0-fbe42d09386e.png">

**Comment by kenzieschmoll** [comment]
Posting some information from an offline conversation I had with @chromy:

If we disable Google analytics for the embedded Perfetto in DevTools, we can remove the popup. On the Perfetto side, it uses local storage to make sure it doesn't show this popup multiple times: https://github.com/google/perfetto/blob/master/ui/src/frontend/cookie_consent.ts#L27. However, this may not work with iFrames. Maybe this https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API/Using ?
When you click 'Okay' it should save the cookieAck key here: https://github.com/google/perfetto/blob/master/ui/src/frontend/cookie_consent.ts#L51. So either it must be failing to do that set or else localStorage gets cleared every time for iframes.

We should investigate and consider disabling analytics for the embedded case as a workaround.

**Comment by kenzieschmoll** [comment]
CL to disabled perfetto analytics in embedded mode: https://android-review.git.corp.google.com/c/platform/external/perfetto/+/2399113
