### ISSUE TITLE
I have updated Dart to the latest version, but still having DevTools 2.15 ver

### ISSUE THREAD

**Issue by ivanovai0310** [flutter/devtools#4893]
updated Dart ver to latest in my project at Android Studio 
<img width="272" alt="image" src="https://user-images.githubusercontent.com/58144046/205630492-55565a1f-7106-4694-a958-a30eac5d6611.png">

but Devtool still have 2.15, without Copy response button at Network/Request tabs.
<img width="546" alt="image" src="https://user-images.githubusercontent.com/58144046/205630795-b3b33b50-cb87-4a0f-ae8a-8a07c378cb78.png">

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/58144046/205630990-abb387b6-1fcf-42de-ae7d-4a0ad7a87c06.png">

___
**DevTools version**: 2.15.0

**Comment by kenzieschmoll** [comment]
can you type `flutter --version` into the command line and paste the output? Also, I'd make sure that your Flutter path in your IDE matches the flutter path from typing `which flutter` into the command line.

**Comment by ivanovai0310** [comment]
@kenzieschmoll : 

user@Aleksejs-MacBook-Pro test_gradle % flutter --version
Flutter 3.3.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b8f7f1f986 (13 days ago) • 2022-11-23 06:43:51 +0900
Engine • revision 8f2221fbef
Tools • Dart 2.18.5 • DevTools 2.15.0
user@Aleksejs-MacBook-Pro test_gradle % which flutter
/Users/user/Documents/flutter_3.3.9/bin/flutter

**Comment by kenzieschmoll** [comment]
> Tools • Dart 2.18.5 • DevTools 2.15.0

DevTools 2.15.0 is the expected DevTools version with the 2.18.5 Dart SDK. The DevTools version number and Dart SDK version numbers are independent, so what you are seeing is expected. 

As far as not seeing the Copy button in the Network Request and Response tabs, not seeing the copy button in the request tab is expected, as this wasn't added until DevTools version 2.19.0. Can you post a screenshot of the Network response tab missing the copy button? This functionality should be included in DevTools 2.15.0.

**Comment by ivanovai0310** [comment]
@kenzieschmoll I've installed the latest version of Flutter and expected the latest version of Dart and Devtools releases. Should I install it manually ? 

Sorry, I mean Request Copy Button on Request Network Tab.
Here is the screenshot
<img width="600" alt="image" src="https://user-images.githubusercontent.com/58144046/205721582-ea71eb86-b1a4-43e7-8d35-690b898178ae.png">

**Comment by kenzieschmoll** [comment]
The DevTools release schedule is tied to the Dart and Flutter SDK release schedule
- If you are on the latest Flutter stable, then you will get the latest stable DevTools (which is 2.15.0)
- If you are on the latest Flutter beta, then you will get the latest beta DevTools (which is 2.19.0)
- If you are on Flutter master, you will get bleeding edge DevTools (2.20.0)

So what you are seeing with the Request copy button missing is expected because this was not added until DevTools 2.19.0. If you switch to the Flutter beta or master channels, you will see this copy button in the Network Request tab. Hope this helps!
