### ISSUE TITLE
memory tab has no profile tab

### ISSUE THREAD

**Issue by johnnypcc** [flutter/devtools#4912]
The [guide](https://docs.flutter.dev/development/tools/devtools/memory#profile-tab) says there should be a Profile tab inside the Memory tab, but it's missing from both the VSCode version and Chrome browser version. No Diff or Trace tab either. This is a iOS app running in profile mode. What can I do to make it show?

To reproduce: 
1) Launch an app on iOS in profile mode.
2) In VSCode, open DevTools performance page, open Memory page. Or use Chrome (browser) to go to the observatory.

![Screen Shot 2022-12-08 at 20 41 45](https://user-images.githubusercontent.com/69480535/206623218-f0fdaf79-e225-4793-87a2-d8cd1f213c5d.png)

<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Dart Version: 2.18.2
Flutter Version: 3.3.3 / stable
Framework / Engine: 18a827f393 / 5c984c26eb
Connected app type: Flutter native (profile build)

**Comment by kenzieschmoll** [comment]
These features are available on the flutter master and beta channels.

@polina-c we might want to add a temporary note to the docs that make it clear which version of DevTools the Profile and Diff tabs will be included in.

**Comment by Cool-PKY** [comment]
Sorry, i still can't find this "temporary note" in the [doc](https://docs.flutter.dev/tools/devtools/memory#diff-snapshots-tab). My current dev-tool version is 2.9.2+1 with flutter verison 2.10.5/  If i need a upgrade? Or could i only upgrade dev-tool when keep the flutter version

**Comment by kenzieschmoll** [comment]
> Do i need a upgrade?  could i only upgrade the dev-tool when keep the flutter version not changed.

Yes you will need to upgrade. DevTools is shipped as part of the Flutter SDK, so you'll need to upgrade your Flutter SDK to get the latest DevTools.
