### ISSUE TITLE
Support Firefox

### ISSUE THREAD

**Issue by 12people** [flutter/devtools#492]
I'd really like to be able to use my browser of choice, Firefox, with Flutter's DevTools.

(Not only that, but I'd also appreciate if web projects in general weren't tied to specific browsers — it hurts web standards and I'd hate another IE-like situation where standards don't matter.)

**Comment by stevemessick** [comment]
Dup of #66

**Comment by 12people** [comment]
@stevemessick #66 is about displaying messages in unsupported browsers. This bug is about supporting a browser other than Chrome. Two very different things.

**Comment by stevemessick** [comment]
#66 is a pretty extensive discussion about what it takes to support browsers other than Chrome. Including Firefox.

However, I may be mis-interpreting it. I'll let @jacob314 chime in as to whether this should be re-opened.

**Comment by 12people** [comment]
@stevemessick It does mention other browsers, yet the issue at hand is different. That issue comes down to "only Chrome is officially tested, should we display a warning in other browsers?".

This "support Firefox" issue asks, "only Chrome is officially tested, should we still allow it to run DevTools, fix bugs for it, and/or add Firefox to the browsers we test in?" It's about broadening support rather than asking if a warning is needed.

**Comment by jacob314** [comment]
Flutter Web will support all modern browsers. If we are able to switch all of this application to use Flutter Web at that point we will begin to support more browsers. Until that point, our time is better spent adding features than making sure we avoid browser compatibility bugs.

**Comment by Afsar-Pasha** [comment]
@12people Try changing UA string using [this addon](https://addons.mozilla.org/en-US/firefox/addon/uaswitcher/).

**Comment by 12people** [comment]
@jacob314 I understand your need for effectiveness.

What if DevTools could be opened in Firefox, but there was a dismissable message on first open saying "Firefox is not officially supported. DevTools may not function properly" or something along those lines?

Changing the UA string really feels like I'm going back to IE-incompatibility times and I'd really like to avoid that.

**Comment by jacob314** [comment]
I agree that warning that Firefox is not tested but still allowing it to open is fine.
The main thing we want to avoid is giving users a bad experience because they accidentally opened the tool with a browser we don't support.

**Comment by TamasBarta** [comment]
Just curiosity: is there anything specific you know about which feature won't work in Firefox, or you just generally don't trust Firefox?

**Comment by agilob** [comment]
I spoofed UA in firefox using https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher and devtools works fine.

**Comment by Blend3rman** [comment]
This just feels dirty now. Basically DevTools is just looking at the useragent string and deciding whether or not to show up. Just add a warning banner saying that Firefox support is untested, why do you have to completely disallow running DevTools on Firefox? As far as I have used DevTools it works perfectly fine on FF, seeing as how it's just a regular websocket, which is supposed to be universally supported by all browsers. 

I just feel like gatekeeping which browsers users may use is not a good way to go about this.

**Comment by 12people** [comment]
@jacob314 Would you consider reopening this issue? It seems like Devtools work just fine in Firefox and allowing it along with a warning about the browser not being tested would be a good solution for those wanting to use the browser.

**Comment by Kogia-sima** [comment]
I love Firefox. I hope this will be fixed.

**Comment by hacker1024** [comment]
It should be possible to get to the beta Flutter DevTools implementation in Firefox.

**Comment by Nico04** [comment]
What about now, with new Flutter release of the Dart Devtools?

**Comment by devoncarew** [comment]
Re-opening to track up-votes.

**Comment by kenzieschmoll** [comment]
From some local testing, it looks like firefox may just work now that we are shipping with Flutter.

**Comment by Nico04** [comment]
> 
> 
> From some local testing, it looks like firefox may just work now that we are shipping with Flutter.

I've just tested myseft, and yes, it seems that it opens in Firefox without any issue nor warning now, that's great !

**Comment by desthercz** [comment]
It works great, but how can i set it by default? Its annoying to always copy&paste url from Chrome to FF.

**Comment by kenzieschmoll** [comment]
transferred request to set default browser to a different issue https://github.com/flutter/devtools/issues/2357. Closing this as fixed.

**Comment by stagefright5** [comment]
Also, the official flutter web docs still says you "require" chrome for debugging.
Please change it to something like, "we recommend chrome". [Here is the link](https://flutter.dev/docs/get-started/web#requirements)

![image](https://user-images.githubusercontent.com/15051871/94259892-da1aac80-ff4c-11ea-8fd9-131dae542e74.png)

**Comment by NatoBoram** [comment]
That's because you can't `flutter run -d firefox`

**Comment by realchandan** [comment]
Is there a way to do It now? It's July 2021, any updates?

**Comment by NatoBoram** [comment]
> Is there a way to do It now?

You can `flutter run -d web-server` and open it in Firefox, but [Dart Debug](https://chrome.google.com/webstore/detail/dart-debug-extension/eljbmlghnomdjgdjmbdekegdkbabckhm) is[n't available for Firefox](https://github.com/dart-lang/webdev/issues/1224), so no DevTools available either.

> It's July 2021, any updates?

No. https://github.com/flutter/flutter/issues/55324

**Comment by silpol** [comment]
It's July 2024 and it's clear now Google is gatekeeping Firefox. If there was will, it could be done with [GSoC](https://summerofcode.withgoogle.com/) program so main resources are not engaged. Three years...
