### ISSUE TITLE
Create Flutter Owned Account For Auto Commits To Master

### ISSUE THREAD

**Issue by CoderDake** [flutter/devtools#4949]
Daily Dev bumps on the master branch are being added in https://github.com/flutter/devtools/pull/4908

Currently, my email is being used as the Author of the commit, so that the CLA workflow will pass.

We should create a Flutter owned account that can be marked as the author instead, so that this process doesn't depend on my account.

**Comment by kenzieschmoll** [comment]
We use the https://github.com/DartDevtoolWorkflowBot for this
