### ISSUE TITLE
Memory: enable eval and browse

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#4962]
The features are needed to retire observatory.

Related issues:
eval: https://github.com/flutter/devtools/issues/4191
browse: https://github.com/flutter/devtools/issues/4757

**Comment by polina-c** [comment]
- [ ] http://go/devtools-memory-eval-and-browse-design

**Comment by annagrin** [comment]
Related: conversations about full repl support (in the debugger and outside) https://github.com/dart-lang/webdev/issues/1480

We don't have a solution yet but do have ideas. Let us know if this becomes a priority (changes would need to be done in CFE, ddc, vm?, dwds, devtools, and also probably setup tools like flutter tools and wevdev)
