### ISSUE TITLE
devtools show "No tabs available for this application"

### ISSUE THREAD

**Issue by mhmtdgnofficial** [flutter/devtools#4964]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: x64 (64 bit) android
Dart Version: 2.18.5
Flutter Version: 3.3.9 / stable
Framework / Engine: b8f7f1f986 / 8f2221fbef
Connected app type: Flutter native (debug build)

**Comment by TangLei96** [comment]
DevTools version: 2.12.2
Connected Device:
CPU / OS: arm64-64/linux
Dart Version: 2.16.6
Flutter Version: 3.0.5 / stable
Connected app type: Flutter native (profile build)

I have an embedded device,and i want to use devtools to analysis my application. I use adb forward to connect PC and my embedded device. it works. but the devtools display **No tabs available for this application**,i don't know why.

**Comment by kenzieschmoll** [comment]
Is this still reproducible on the latest version of DevTools (available on the most recent flutter stable)? It looks like you are on a very old DevTools version based on the provided version info.
