### ISSUE TITLE
devtools show "No tabs available for this application"

### ISSUE THREAD

**Issue by TangLei96** [flutter/devtools#4967]
DevTools version: 2.12.2
Connected Device:
CPU / OS: arm64-64/linux
Dart Version: 2.16.6
Flutter Version: 3.0.5 / stable
Connected app type: Flutter native (profile build)

I have an embedded device,and i want to use devtools to analysis my application. I use adb forward to connect PC and my embedded device. it works. but the devtools display **No tabs available for this application**,i don't know why.

**Comment by kenzieschmoll** [comment]
closing as duplicate of https://github.com/flutter/devtools/issues/4964
