### ISSUE TITLE
Dialog buttons in all dialogs do not work if they are close to bottom of the DevTools window.

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#4972]
1. Open logging screen
2. Click filter button
3. Resize window so that dialog buttons are close to the bottom
4. Click button 'Apply'

Expected result: dialog closes
Actual result: dialog does not close

**Comment by polina-c** [comment]
Closing as could not reproduce at current version.

**Comment by CoderDake** [comment]
Found one way to reproduce this, and that is when a notification overlay is showing.
After doing some debuging i found out that the notification's root element is the width of the parent column which is much wider than the notification itself.

Fixing this would require making the notifications take up the whole width or else making the transparent background actually clickable.

After doing someresearch though it looks like overlay and dialog "z" values can't really be changed. So pursuing making the notifications full width might be the first best approach.

<img width="939" alt="Screenshot 2023-06-27 at 2 10 45 PM" src="https://github.com/flutter/devtools/assets/1386322/b7552d20-5993-431f-9195-b7a04d961c37">
