### ISSUE TITLE
Chrome 75 (dev) is doubling up the buttons

### ISSUE THREAD

**Issue by domesticmouse** [flutter/devtools#498]
Looks like Google Chrome 75.0.3745.4 (Official Build) dev (64-bit) is breaking things. 

![doubled](https://user-images.githubusercontent.com/30503/55509063-1ac38f00-5610-11e9-875f-468111b82656.png)

**Comment by stevemessick** [comment]
@jacob314

**Comment by devoncarew** [comment]
Also cc'ing @kenzieschmoll, who's done some work in this area in terms of extension detection.
