### ISSUE TITLE
DevTools are just empty in Visual Studio Code

### ISSUE THREAD

**Issue by gidrokolbaska** [flutter/devtools#4989]
Hi!
So basically I have an empty DevTools for some reason:
![image](https://user-images.githubusercontent.com/54116985/209323694-b24db09e-0d98-43bf-8b0a-87090cc378c5.png)
I've tried to reinstall flutter, use an android simulator but to no avail.
No errors in flutter doctor.
Is there anything I can do to fix that?...
BTW, it works in the browser and on channel master
___
**DevTools version**: 2.20.0
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Dart Version: 2.18.5
Flutter Version: 3.3.9 / stable
Framework / Engine: b8f7f1f986 / 8f2221fbef
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
@DanTup

**Comment by DanTup** [comment]
@gidrokolbaska if you click Help -> Toggle Developer Tools in VS Code, and then go to the Console tab, are there any warnings or errors listed there?

**Comment by gidrokolbaska** [comment]
> 

Hi!
Yep, there are some errors:
![image](https://user-images.githubusercontent.com/54116985/210968333-2f6f45c2-4b9c-4156-81cf-54a2fec0c061.png)

**Comment by DanTup** [comment]
@gidrokolbaska if you change this setting in VS Code (for example to `9201`) and restart VS Code, does the issue go away?

<img width="708" alt="Screenshot 2023-01-09 at 14 53 53" src="https://user-images.githubusercontent.com/1078012/211337213-c8482581-82d7-47cd-8fd1-c7a379367994.png">

If so, it could be something being cached. Based on the error it looks like `api/ping` is being looked for inside the `inspector/` folder, which suggests the `base href` might not be correct.

**Comment by gidrokolbaska** [comment]
> @gidrokolbaska if you change this setting in VS Code (for example to `9201`) and restart VS Code, does the issue go away?
> 
> <img alt="Screenshot 2023-01-09 at 14 53 53" width="708" src="https://user-images.githubusercontent.com/1078012/211337213-c8482581-82d7-47cd-8fd1-c7a379367994.png">
> 
> If so, it could be something being cached. Based on the error it looks like `api/ping` is being looked for inside the `inspector/` folder, which suggests the `base href` might not be correct.

Hi! That seems to be working as expected, tyvm.

**Comment by DanTup** [comment]
The error printed to the console about not being able to connect to the server is fixed by https://github.com/flutter/devtools/pull/5016. I believe the original issue here is one of caching which is #3896 is tracking, so I think there's nothing extra to do here.
