### ISSUE TITLE
DevTolls Network Tab Not Showing Any Request

### ISSUE THREAD

**Issue by Muhammad-Sharif-Ullah** [flutter/devtools#4998]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Dart Version: 2.18.4
Flutter Version: 3.3.7 / stable
Framework / Engine: e99c9c7cd9 / 857bd6b74c
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
@Muhammad-Sharif-Ullah Could you please provide some more information about how you are running into this issue?
 For example:
- how are you accessing Devtools
- how are you sending the requests
- do you have the network tab open while you are trying to record the requests?

Feel free to reach out when you have some more details about how you are running into this issue :)
