### ISSUE TITLE
In Network Page: Request object doesn't change on click of different uri request

### ISSUE THREAD

**Issue by mr-srini** [flutter/devtools#5000]
Assume there are 3 requests going with the different request bodies. 
The request body doesn't seem to reflect the right one, it's still pointing to the previously selected request (Network call)
Observed only in POST requests

Plus: 'Copy as URL' or 'Copy as cURL'  is not copying to my clipboard.
___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: x64 (64 bit) ios
Dart Version: 2.18.2
Flutter Version: 3.3.4 / stable
Framework / Engine: eb6d86ee27 / c08d7d5efc
<img width="239" alt="Screenshot 2023-01-03 at 19 28 13" src="https://user-images.githubusercontent.com/59933024/210371564-71a6152e-305e-4efe-9574-548ac82731e0.png">

Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
I was not able to reproduce the issue with copy url and copy clipboard.

I was able to see that devtools has a hard time getting some of the requests though.
```
Unable to find request with id: '3090183977817812000'
ext.dart.io.getHttpProfileRequest: (-32602) Invalid params
Unable to find request with id: '3090183977817812000'
ext.dart.io.getHttpProfileRequest: (-32602) Invalid params
Unable to find request with id: '3090183977817812000'
```
I noticed that the  Request tab was empty.
I noticed that the copied curl contents didn't contain the params
![Screen Shot 2023-01-03 at 10 42 33 AM](https://user-images.githubusercontent.com/1386322/210391061-8b083f73-95d4-4d73-805f-693eebe3db02.png)

I kind of wonder if perhaps some types of params have a hard time displaying.

@mr-srini what kind of data are you sending in your POST body?
Do you have an example of a body that you might be trying to POST, or perhaps would you be able to create one that reproduces your issue?

**Comment by kenzieschmoll** [comment]
This issue is resolved.
