### ISSUE TITLE
Flutter widget inspector dont follow my code

### ISSUE THREAD

**Issue by LuisHernandezL** [flutter/devtools#5002]
I try to inspect an element in the android emulator and in the vs code it does not show me the section of code that I want to inspect when selecting it in the emulator
___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: x64 (64 bit) android
Dart Version: 2.18.2
Flutter Version: 3.3.3 / stable
Framework / Engine: 18a827f393 / 5c984c26eb
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
@LuisHernandezL are you using one of the pre-release versions of flutter?
If so I  think this resolution may help you:
https://github.com/flutter/devtools/issues/4615#issuecomment-1282775925

**Comment by LuisHernandezL** [comment]
thanks!! that fix my problem
