### ISSUE TITLE
Perfetto does not load correctly in the Dart SDK

### ISSUE THREAD

**Issue by bkonyi** [flutter/devtools#5023]
When opening DevTools for a Dart CLI application, the iframe for Perfetto displays various errors depending on what flags were provided to the VM.

**`dart --observe foo.dart`**: `missing or invalid authentication code`

**`dart --observe --disable-service-auth-codes foo.dart`**: `{"jsonrpc":"2.0", "error":{"code":-32601,"message":"Method not found","data":{"request":{"method":"assets","params":{"mode":"embedded","hideSidebar":"true"}}}},"id":""}`

There's currently no way to work around these errors, making the Performance page effectively useless when debugging Dart CLI applications.

**Comment by kenzieschmoll** [comment]
![image](https://user-images.githubusercontent.com/43759233/213552759-1a3cdd6c-198d-40de-9d1e-864d40fc0faa.png)
