### ISSUE TITLE
Page become non responsive for tab - "Logging"

### ISSUE THREAD

**Issue by harshitphoenix** [flutter/devtools#5029]
When switched to the Logging tab, the page becomes non responsive. This might be due to the blocking of the call stack due to large batch processing in the main stack. It can be avoided by breaking the entire batch into pages.
![Screenshot from 2023-01-11 19-56-46](https://user-images.githubusercontent.com/56081331/211831430-c64cd0ed-5541-4c0a-a55e-b368cff21382.png)

**Comment by kenzieschmoll** [comment]
this is resolved by a recent performance fix for DevTools tables
