### ISSUE TITLE
Various issues with inspection teardrops on debugger page

### ISSUE THREAD

**Issue by elliette** [flutter/devtools#5043]
Can't figure out a reliable repro, this happened the first time I set a breakpoint but I haven't been able to reproduce it:

* Connect to the default Flutter test app (counter)
* Set a breakpoint in the counter increment method
* When resuming, will see a teardrop and "Select all" 
![Screenshot 2023-01-13 at 10 39 57 AM](https://user-images.githubusercontent.com/21270878/212395117-551a0db7-2f9d-42fa-ace1-b73a667d605b.png)

**Comment by elliette** [comment]
You can end up with multiple teardrops if you click on multiple variables to inspect while paused. They make it hard to read what the variable are

![Screenshot 2023-01-13 at 10 46 03 AM](https://user-images.githubusercontent.com/21270878/212395987-89813575-caac-4b58-8631-f8be0613be09.png)

**Comment by elliette** [comment]
Clicking on inspect shows error:

![multiple_teardrops](https://user-images.githubusercontent.com/21270878/212396517-490e27c7-2ef7-46e3-a395-49ee07e7278a.gif)

**Comment by jacob314** [comment]
That looks like

**Comment by elliette** [comment]
<img width="453" alt="Screenshot 2024-11-05 at 2 20 18 PM" src="https://github.com/user-attachments/assets/de314a25-996c-4da3-af20-28b298e6cf44">

I'm no longer seeing this, closing.
