### ISSUE TITLE
light mode, link on selected row is not visible

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#5046]
<img width="906" alt="Screenshot 2023-01-13 at 11 01 06 AM" src="https://user-images.githubusercontent.com/12115586/212405694-5cc97c2e-faa2-4494-b8e3-a721364d909d.png">

Suggestion for selected row:

<img width="782" alt="Screenshot 2023-01-13 at 11 01 45 AM" src="https://user-images.githubusercontent.com/12115586/212401092-22a5653c-32f8-4bc7-815a-7beb61c213ce.png">

**Comment by polina-c** [comment]
@malloc-error

**Comment by malloc-error** [comment]
I recommend using the bright blue background, but then check the white text for legibility. If that white text is too hard to read, then change it to black.
