### ISSUE TITLE
Flutter inspector going blank

### ISSUE THREAD

**Issue by ramanan-ramesh** [flutter/devtools#5054]
<-- Launched my flutter app for Windows(Dekstop) in x64(64-bit) debug mode, but the flutter inspector shows blank screen without widget tree, without any warning messages/labels.>
___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: x64 (64 bit) windows
Dart Version: 2.18.5
Flutter Version: 3.3.9 / stable
Framework / Engine: b8f7f1f986 / 8f2221fbef
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
@ramanan-ramesh, in VSCode can you please navigate to `Help > Toggle Developer Tools`. Then in the console can you please post any relevant errors that you see there?
