### ISSUE TITLE
Add scan/attach options to DevTools homepage

### ISSUE THREAD

**Issue by Zazo032** [flutter/devtools#5061]
Use case:

- I have `dart devtools` running in a terminal
- I have a device/emulator connected
- I have installed a debug/profile version in the device/emulator
- I want to be able to debug just using DevTools and scan for/attach to running debug/profile Flutter apps

Right now, you can only see a "Connect to a Running App", but there's no info provided on how to look for the observatory url if the app was not directly run from the same laptop that has the DevTools running

**Comment by CoderDake** [comment]
@Zazo032 Is there a particular reason why you don't want to run your application from your machine?

As  long as you just need a way to run your app on the device, and debug it, then you can run `flutter devices` to ensure that your device is connected and setup correctly.

As long as your device shows up there then you should be able to `flutter run -d <your_device>`. This will run the app on your device and  ensure you have access to the `VM Service Url` that gets generated.

Feel free to reach back out if there is something more specific you are looking for

**Comment by Zazo032** [comment]
The specific reason for this was that, for example, QA team would like to be able to also debug network requests and provider states, so the team has installed Dart/Flutter, but they don't have access to the source code so they're not able to directly run the app. The debug/profile build is deployed internally

**Comment by Zazo032** [comment]
That worked and also provides the observatory urls for devtools, thanks!

**Comment by Zazo032** [comment]
Hey @CoderDake, got some feedback from the QA team, seems like they're getting this error:
```
PS C:\<elided>> flutter attach
Target file "lib\main.dart" not found.
```
Seems like they do indeed need the source code to be able to attach DevTools to a running (debug/profile) app

**Comment by CoderDake** [comment]
@Zazo032 
sorry to hear that!
Out of curiosity, if a blank lib/main.dart file is present are they able to attach?
It looks like if I just create a blank one then flutter attach proceeds with trying to attach. Maybe this could be a shortcut to avoid needing the code?
![Screenshot 2023-01-27 at 9 30 02 AM](https://user-images.githubusercontent.com/1386322/215111340-4d9ca803-c942-4a19-89e0-1e01d87fafa1.png)

**Comment by Zazo032** [comment]
That alone doesn't work (it'll also need an empty `android` folder to attach to an Android app, but after adding that, there's this error now:
```
Error: Error when reading '.dart_tool/package_config.json':`` System couldn't find the specified route.
Syncing files to device <elided>...                                236ms
```

**Comment by CoderDake** [comment]
aw darn, I was hopeful we could be sneaky

**Comment by Zazo032** [comment]
Could we then reopen this to track if implementing this would be feasible?

**Comment by CoderDake** [comment]
I think that would be more of something to bring up in the main [Flutter repo issues](https://github.com/flutter/flutter/issues)
The devtools repo wouldn't have very much control over stuff like that :)
