### ISSUE TITLE
Experiments are enabled by default

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#5073]
This is happening in the released version of DevTools. Marking as P0 as we need to get this resolved and see if a cherry pick is possible.
@polina-c

**Comment by polina-c** [comment]
kReleaseMode is false for some reasons in the build created by `dart ./tool/build_e2e.dart`

**Comment by itsjustkevin** [comment]
Thanks for calling this out @kenzieschmoll.  I’m assuming in this situation, we need a new dart build and not a new flutter build?  I’m still not versed around the devtools release process.

**Comment by bkonyi** [comment]
We'll need both a Flutter and Dart SDK release since DevTools is shipped as part of the Dart SDK.

**Comment by itsjustkevin** [comment]
Thanks @bkonyi.  

CC: @XilaiZhang and @godofredoc

**Comment by XilaiZhang** [comment]
thanks for the info! is the bad build also included in the dart version that we used for flutter beta hotfix?

**Comment by kenzieschmoll** [comment]
Yes this is on every flutter version starting with 3.7.0-1.1.pre

**Comment by XilaiZhang** [comment]
thanks for explaining! @itsjustkevin in terms of flutter beta hotfix, shall we keep moving forward with the remaining steps, or shall we wait to grab a new dart version, engine cp etc.?

**Comment by itsjustkevin** [comment]
I think the safest bet here is to push a release with the newest dart hash.  I may be wrong here, opinions on the matter @godofredoc?

**Comment by godofredoc** [comment]
What would be the impact if we push the beta release as expected and release a hotfix early next week?

**Comment by kenzieschmoll** [comment]
The risk would be that the DevTools Performance page is broken and our analytics are turned off until the hotfix goes out.

**Comment by kenzieschmoll** [comment]
This is resolved. The 2.20.1 cherrypick made it into the stable release.
