### ISSUE TITLE
Flame chart results appear in the wrong order with async code

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#5090]
I don't know if this is a DevTools issue, but I figured I'd start here. The following code has a function called `doStuff()` which calls `step1()` which does 1 second of sync work, `step2()` which triggers 3s of sync work "out-of-band" and awaits it, and `step3()` which is the same as `step1()` (1s of sync work):

```dart
import 'dart:async';
import 'dart:developer';
import 'dart:io';

import 'package:flame_chart_testing/flame_chart_testing.dart'
    as flame_chart_testing;

Future<void> main(List<String> arguments) async {
  print('Pausing...');
  debugger();

  await doStuff();

  print('Pausing...');
  debugger();
}

Future<void> doStuff() async {
  print('Doing step 1 (1s)');
  step1();
  print('Doing step 2 (3s)');
  await step2();
  print('Doing step 3 (1s)');
  step3();
  print('Done!');
}

void _workFor(String name, int seconds) {
  print(name);
  final start = DateTime.now();
  while (DateTime.now().difference(start) < Duration(seconds: seconds)) {}
}

void step1work() => _workFor('step1', 1);
void step2work() => _workFor('step2', 3);
void step3work() => _workFor('step3', 1);

Future<void> step1() async {
  step1work();
}

final completer = Completer<void>();
Future<void> step2() async {
  Future.delayed(const Duration(seconds: 0))
      .then((_) => step2work())
      .then(completer.complete);
  await completer.future;
}

Future<void> step3() async {
  step3work();
}
```

If I profile this and view the flame chart, the results appear to be out-of-order:

![Screenshot 2023-01-23 at 17 11 27](https://user-images.githubusercontent.com/1078012/214104401-4cd9297e-324c-44a2-8fb6-d8a95e6ff48b.png)

Here, `step2work` is last, and `step3work` is in the middle. This is not (at least as far as I can tell 😄) the order that they executed.

It's also a shame that `step2` doesn't appear in the chart at all (I think because it had no real sync work and wasn't on the real stack when `step2work` executed). I hit this while profiling the analyzer, where there's a lot of code that's kicked off out-of-band like that, and the calling code seems to collapse and not appear in the chart while it was just awaiting those results.

**Comment by DanTup** [comment]
It occurred to me after posting this, that maybe the flame chart isn't intended to show things in-order, because it's just showing complete timings (eg. two calls to the same function are collapsed together, even if they have other calls between them).

I think while trying to investigate an issue with not seeing the numbers I expected I ended up going down the wrong rabbit hole and it's not related to the order. I'll dig back into that and file another issue if it looks like there's something wrong there.

**Comment by kenzieschmoll** [comment]
You are correct in that the CPU profile flame chart is not intended to show samples in order. This is impossible due to the way the profiler aggregates samples (for example, you could have a sample at the very end of the profile that matches a sample in the beginning of the profile - those two samples would be aggregated in the results). If you are looking to debug timing, consider adding timeline events and using the Performance page instead.
