### ISSUE TITLE
Audit performance of the various DevTools screens and components

### ISSUE THREAD

**Issue by bkonyi** [flutter/devtools#5091]
A common concern raised by some Dash engineers is that DevTools often feels slower than existing tooling in Observatory.

Some examples of scenarios with poor performance:

- Opening DevTools while connecting to a CLI application automatically fetches and loads a timeline, locking up the UI thread until the timeline is fetched and processed
- Poor performance when creating filtered CPU profiles

Performance of the various tools should be audited to ensure that current power users of Observatory do not experience a degradation of their development workflows.

This is a blocker for deprecating and removing Observatory from the Dart SDK.

cc @a-siva @jacob314

**Comment by kenzieschmoll** [comment]
Another possible performance optimization: stop copying data for flat tables https://github.com/flutter/devtools/pull/5384/files#r1132405605

**Comment by kenzieschmoll** [comment]
> Opening DevTools while connecting to a CLI application automatically fetches and loads a timeline, locking up the UI thread until the timeline is fetched and processed

@bkonyi is this still an issue with the new perfetto integration? If it's not a problem now, there may not be a reason to invest in creating an "index" screen for cli apps.

**Comment by bkonyi** [comment]
I'm personally content with the landing page performance as Perfetto doesn't seem to cause the UI thread to jank when loading the initial timeline like it did before, so users can still switch to another tab while the timeline is being processed. However, I do feel having an overview landing page could be useful, particularly in VM developer mode (cc @a-siva for his thoughts), but that can be pulled out into its own issue.

I think we can close this issue once https://github.com/flutter/devtools/issues/5703 is resolved.

**Comment by kenzieschmoll** [comment]
Landing screen is tracked here: https://github.com/flutter/devtools/issues/4603. Since #5703 has been broken out into smaller tracking issues and is a meta tracking issue for all the smaller items, I'm going to let that work be tracked there. I will close this out, and I will add the appropriate labels to the other issues.
