### ISSUE TITLE
Flutter devtool network tab not working as expected

### ISSUE THREAD

**Issue by sunilhari9** [flutter/devtools#5094]
<-- Please describe your problem here. Be sure to include repro steps. -->
It just shows the spinner showing 0 of 0 requests.

___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: x64 (64 bit) android
Dart Version: 2.18.6
Flutter Version: 3.3.10 / stable
Framework / Engine: 135454af32 / 3316dd8728
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
Can you add some more information about how you are sending the network requests that you expect to show up?

**Comment by CoderDake** [comment]
@sunilhari9 Some changes are coming through soon that may address this issue.
Keep an eye on https://github.com/flutter/devtools/issues/2860 For updates on progress.

**Comment by CoderDake** [comment]
Once the changes from #2860 make it through, please feel free to report back if you are still having issues :)

**Comment by CoderDake** [comment]
@sunilhari9  this issue should be addressed with the fixes in `Devtools 2.22.1`, now available on flutter master.

See https://github.com/flutter/devtools/issues/2860#issuecomment-1442313329 for more info.

Feel free to reach out if you run into any issues :D
