### ISSUE TITLE
Inspect unreactive requests in the Network tab

### ISSUE THREAD

**Issue by joaodos3v** [flutter/devtools#5095]
When analyzing several requests in sequence, the work is hampered because the Request and Response tabs do not update when we change the request.

### Expected behavior

That the content of each individual request is loaded as soon as the request is selected, regardless of which tab (Header, Request, Response...) we are on (just like browsers do).

### Obtained behavior

When changing requisitions in the left panel, the requisition details are not updated in the right side.

### Steps to reproduce

1. Open Flutter DevTools from a running app
2. Run some HTTP calls
3. On the Network tab of DevTools, select the first request
4. Activate the Request tab
5. Go to another request and notice that the contents of the Request tab have not been updated

___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: x64 (64 bit) ios
Dart Version: 2.18.2
Flutter Version: 3.3.5 / stable
Framework / Engine: d9111f6402 / 3ad69d7be3
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
@joaodos3v There should be some fixes coming through that improve this in https://github.com/flutter/devtools/pull/5056
Once that change makes it through the request and response tabs should be much more consistent.
