### ISSUE TITLE
consider exposing the `debugProfileWidgetBuilds` service extension

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#510]
See https://github.com/flutter/flutter/pull/30867 for context. This service extension will cause all widget build methods to appear in the timeline view. It does skew the overall build times, but is useful to know what's being built, and perhaps to get a sense of the proportional times.

**Comment by devoncarew** [comment]
@jacob314 @kenzieschmoll 

I'm not sure if we would want to expose this as an additional button, or if we've reached the point where we need the common extensions as first class buttons, and the less common ones in an overflow area.

**Comment by kenzieschmoll** [comment]
Would the build events be coming in as trace events? Or as part of the CPU samples?

**Comment by devoncarew** [comment]
They should be sent as additional trace events (generally, you should see a lot more trace events).

**Comment by filiph** [comment]
Just want to add this is extremely helpful functionality — I recommend people use this (hit `a` when `flutter run`) any time they suspect some performance issue in builds.

Without the flag (the pink trace events just say "Build"):

![Screen Shot 2020-01-14 at 5 49 29 PM](https://user-images.githubusercontent.com/919717/72397995-538fa900-36f6-11ea-8b6f-493081ee659b.png)

With the flag (many new trace events, saying which widget was which):

![Screen Shot 2020-01-14 at 5 50 00 PM](https://user-images.githubusercontent.com/919717/72398019-702be100-36f6-11ea-842f-898f9cae97ef.png)

**Comment by filiph** [comment]
To be clear: the events show up in DevTools, but there is no way to toggle the flag from either DevTools or the Flutter Plugin.
