### ISSUE TITLE
Pressing Cmd+a makes widget inspector selected entirely

### ISSUE THREAD

**Issue by jeiea** [flutter/devtools#5107]
### Steps to reproduce
**Environment**
<img width="585" alt="image" src="https://user-images.githubusercontent.com/4188984/214528709-9b0028c5-a769-4f15-9301-cbb1a8026ae4.png">
```
> flutter doctor   
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.0.1 22A400 darwin-x64, locale en-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.74.3)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```
Just press Cmd+a while focusing vscode widget inspector.

### Expected behavior

Nothing happens.

### Actual behavior

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/4188984/214528036-895bd9a9-1eab-4e04-a298-87d3c9838ddf.png">

**Comment by kenzieschmoll** [comment]
@DanTup

**Comment by DanTup** [comment]
I moved this to https://github.com/Dart-Code/Dart-Code/issues/4363 and have fixed it for the next VS Code extension release.
