### ISSUE TITLE
Request and response content not visible in the network tab

### ISSUE THREAD

**Issue by manueltag** [flutter/devtools#5108]
After upgrading Flutter to version 3.7.0, I can't see the contents of the "Request" and "Response" tabs of a request. As you can see there are some errors in console.

![Screenshot 2023-01-25 alle 11 19 08](https://user-images.githubusercontent.com/18601109/214537973-b9072b51-25c9-4e58-bc4d-141487dd9254.png)

___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Dart Version: 2.19.0
Flutter Version: 3.7.0 / stable
Framework / Engine: b06b8b2710 / b24591ed32
Connected app type: Flutter native (debug build)

**Comment by webforuse** [comment]
confirm

**Comment by kenzieschmoll** [comment]
@CoderDake

**Comment by CoderDake** [comment]
@manueltag I've got some fixes coming through for this in the next little while.
Context can be found in my posts in the following issue:
https://github.com/flutter/devtools/issues/2860

**Comment by CoderDake** [comment]
@manueltag  this issue should be addressed with the fixes in `Devtools 2.22.1`, now available on flutter master.

See https://github.com/flutter/devtools/issues/2860#issuecomment-1442313329 for more info.

Feel free to reach out if you run into any issues :D
