### ISSUE TITLE
no show response and request data

### ISSUE THREAD

**Issue by webforuse** [flutter/devtools#5109]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: x64 (64 bit) ios
Dart Version: 2.19.0
Flutter Version: 3.7.0 / stable
Framework / Engine: b06b8b2710 / b24591ed32
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
There is a tracking issue here: https://github.com/flutter/devtools/issues/2860. If what you are experiencing seems different than what has been described here, please feel free to reopen this issue and add more information. This is actively being worked on and a fix for this should be available soon.
