### ISSUE TITLE
Performance/perfetto: it is not clear name of what is printed

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#5123]
![Screenshot 2023-01-26 at 2 57 39 PM](https://user-images.githubusercontent.com/12115586/214937732-a6985d62-ac37-4fae-ad9e-dc2498dfef38.png)

**Comment by kenzieschmoll** [comment]
This is part of the Perfetto app. What would make this more clear? This is the name of the trace event that you have selected ("Current Selection"). All this data is for the current selection.

**Comment by polina-c** [comment]
And category. Category of what? what are other options?

I thing question mark on this specific tab that leads to documentation that explains how to zoom other ux issues, would help.

**Comment by kenzieschmoll** [comment]
closing in favor of https://github.com/flutter/devtools/issues/5118.
