### ISSUE TITLE
"Snapshot" button in memory view

### ISSUE THREAD

**Issue by terrylucas** [flutter/devtools#513]
- May need to tell use that ‘snapshot’ needs to be clicked in order to see the heap.
- Consider changing name - technically snapshot means something else in the VM.
- Look at moving "Snapshot and Reset" buttons as a group on the left side (keep Filter and GC buttons on the right-side).

Fix for I/O

**Comment by jacob314** [comment]
The button now says "Take Heap Snapshot" But we don't yet display a message warning you that you need to take a snapshot to see data in the table.
