### ISSUE TITLE
Response does not show anything while network debugging

### ISSUE THREAD

**Issue by salba360496** [flutter/devtools#5136]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: x64 (64 bit) ios
Dart Version: 2.19.0
Flutter Version: 3.7.0 / stable
Framework / Engine: b06b8b2710 / b24591ed32
Connected app type: Flutter native (debug build)

**Comment by CoderJava** [comment]
I have the same issue.

**Comment by kenzieschmoll** [comment]
@CoderDake is actively working on this issue. Stay tuned for an update 👍

**Comment by CoderJava** [comment]
https://github.com/flutter/devtools/issues/5140

**Comment by kenzieschmoll** [comment]
This should be resolved by the latest version of flutter stable
