### ISSUE TITLE
[Network] No content in Request/Response tabs

### ISSUE THREAD

**Issue by BaudouinCS** [flutter/devtools#5140]
Hello,

I don't have any content in my Requests/Response tabs when the rest is fine, just a black page.
I noticed it worked only once but I can't submit any reproductible step, sorry.

I'm using GraphQL for my queries btw. Latest version of the flutter package.

___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Dart Version: 2.19.0
Flutter Version: 3.7.0 / stable
Framework / Engine: b06b8b2710 / b24591ed32
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
@BaudouinCS this issue should be addressed with the fixes in `Devtools 2.22.1`, now available on flutter master.

See https://github.com/flutter/devtools/issues/2860#issuecomment-1442313329 for more info.

Feel free to reach out if you run into any issues :D
