### ISSUE TITLE
Can not see the response result in network tab

### ISSUE THREAD

**Issue by DangTuCS** [flutter/devtools#5147]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Dart Version: 2.19.0
Flutter Version: 3.7.0 / stable
Framework / Engine: b06b8b2710 / b24591ed32
Connected app type: Flutter native (debug build)

**Comment by CoderJava** [comment]
https://github.com/flutter/devtools/issues/5140

**Comment by kenzieschmoll** [comment]
This should be resolved on the latest version of Flutter stable.
