### ISSUE TITLE
Flutter DevTools Network Tab missing Network Request & Response Information

### ISSUE THREAD

**Issue by lookevink** [flutter/devtools#5157]
<-- Please describe your problem here. Be sure to include repro steps. -->

Neither is showing up since upgrading to Flutter 3.7 & Dart 2.19

<img width="1728" alt="Screenshot 2023-01-31 at 5 22 14 PM" src="https://user-images.githubusercontent.com/28720907/215897327-77e9cf78-eabc-40c4-80a4-259f8b02619b.png">
<img width="1728" alt="Screenshot 2023-01-31 at 5 22 12 PM" src="https://user-images.githubusercontent.com/28720907/215897353-52b7ff78-c3b0-494c-bca8-e00067ad21b6.png">

___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Dart Version: 2.19.0
Flutter Version: 3.7.0 / stable
Framework / Engine: b06b8b2710 / b24591ed32
Connected app type: Flutter native (debug build)

**Comment by VanLong-official** [comment]
The same problem

**Comment by CoderDake** [comment]
Improvements are being made to the Network tab.
Updates are being provided in the comments on: https://github.com/flutter/devtools/issues/2860

**Comment by CoderDake** [comment]
@lookevink flutter master now has some fixes that should address this.
Please feel free to reach out if you continue to have issues with this though :D

See https://github.com/flutter/devtools/issues/2860#issuecomment-1442313329 for more info
