### ISSUE TITLE
P1: Need to show where a object was created and referenced.

### ISSUE THREAD

**Issue by terrylucas** [flutter/devtools#517]
Ultimately VMService should give us this but we need to get it running with a kernel transformer.  Hook into memory allocations (get stack trace, etc.) a bit expensive but once running and showing usefulness create an API in the VMService API.

**Comment by jacob314** [comment]
The VMService provides an api to track creation stack traces for a specified list of classes. We should use that API in the memory page allowing users to understand where memory for classes they are concerned about was allocated.
