### ISSUE TITLE
Describe what the Diff Snapshots view is for in onboarding instructions

### ISSUE THREAD

**Issue by InMatrix** [flutter/devtools#5178]
The instructions shown at the starting state of the tab were very helpful. However, it’s focused on _how_ to use the tab instead of telling the user _what_ the tab can do for them. The following text from the [Memory screen doc](https://docs.flutter.dev/development/tools/devtools/memory#diff-tab) might be useful: 

> Use the Diff tab to investigate a feature’s memory management. Follow the guidance on the tab to take snapshots before and after interaction with the application, and diff the snapshots:

**Comment by polina-c** [comment]
Resolved

<img width="579" alt="Screenshot 2023-03-29 at 4 20 25 PM" src="https://user-images.githubusercontent.com/12115586/228689217-74f40909-2913-45a2-8a31-910b35a21f15.png">
