### ISSUE TITLE
Column 'Message' is empty in Logs tab, even though details show the actual message!?

### ISSUE THREAD

**Issue by ced1check** [flutter/devtools#5182]
![image](https://user-images.githubusercontent.com/104206200/216564310-1bf9d176-0bd4-4719-919f-e01af3376642.png)

___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Dart Version: 2.18.5
Flutter Version: 3.3.9 / stable
Framework / Engine: b8f7f1f986 / 8f2221fbef
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
How are you logging this information? Are you using dart:developer's [log](https://api.flutter.dev/flutter/dart-developer/log.html) function?

**Comment by CoderDake** [comment]
@ced1check could you please provide more information about how you are trying to log this information?
I tried using developer.log and it seems to show up in the Message column when I do

**Comment by ced1check** [comment]
Sorry for late reply, I didn't open the flutter project in a while.

I used to use developer.log, and now using debugPrint to get logs in logcat.

That said, using developer.log(message), I get this:

[log] message

But I can't find the URL to the debugging anymore?!

**Comment by CoderDake** [comment]
It looks like debugPrint is meant to just print to the console.
https://github.com/flutter/flutter/blob/main/packages/flutter/lib/src/foundation/print.dart#L79

Which leads to the sky_engine::print()
![Screenshot 2023-07-13 at 10 24 29 AM](https://github.com/flutter/devtools/assets/1386322/96230a68-8828-4b90-b65f-6103c0a67f7d)

Looking at the Message column code it looks like it should try to show the summary or details.
https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/screens/logging/_message_column.dart#L25

So this makes me thing that debugPrint might have some sort of empty summary that overrides the details when displaying as a message.

**Comment by kenzieschmoll** [comment]
Fixed by https://github.com/flutter/devtools/pull/8421, which shows both the summary and details in each log row, and immediately fetches log details instead of computing them lazily
