### ISSUE TITLE
in network request and response there is no information at all

### ISSUE THREAD

**Issue by omar6533** [flutter/devtools#5191]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: x64 (64 bit) ios
Dart Version: 2.19.0
Flutter Version: 3.7.0 / stable
Framework / Engine: b06b8b2710 / b24591ed32
Connected app type: Flutter native (debug build)

**Comment by merenyimiklos** [comment]
same here... any good news?

**Comment by CoderDake** [comment]
There are some changes that are coming through soon that should improve the network tab.
See the thread in this issue for updates:
https://github.com/flutter/devtools/issues/2860

**Comment by CoderDake** [comment]
@omar6533 this issue should be addressed with the fixes in `Devtools 2.22.1`, now available on flutter master.

See https://github.com/flutter/devtools/issues/2860#issuecomment-1442313329 for more info.
