### ISSUE TITLE
Network Response "Copy to Clipboard" doesn't work

### ISSUE THREAD

**Issue by hansmboron** [flutter/devtools#5192]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Dart Version: 2.19.1
Flutter Version: 3.7.1 / stable
Framework / Engine: 7048ed95a5 / 800594f1f4
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
@hansmboron could you please provide more information about which copy button wasn't working for you?

**Comment by hansmboron** [comment]
![image](https://user-images.githubusercontent.com/47091709/217058659-a24da7dc-dd35-4f06-867c-f3578f8d1d7d.png)
The icon from the Response in a network request. I was using Linux and now using Windows don't copy nothing too.

**Comment by CoderDake** [comment]
Thank you i'll take a look into this once we fix some other issues in the network tab
