### ISSUE TITLE
Flutter DevTools networking response tab empty

### ISSUE THREAD

**Issue by merenyimiklos** [flutter/devtools#5194]
I just upgraded my flutter to this:
Flutter 3.7.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7048ed95a5 (5 days ago) • 2023-02-01 09:07:31 -0800
Engine • revision 800594f1f4
Tools • Dart 2.19.1 • DevTools 2.20.1

And my flutter devtools in the previous versions working well, but this new one in the response tab is empty, all api call is empty, but it's actually not empty. Can you help me this because it's a bad issue.

**Comment by CoderDake** [comment]
There are some changes that are coming through soon that should improve the network tab.
See the thread in this issue for updates:
https://github.com/flutter/devtools/issues/2860

The issue you are running into may be caused by an integer overflow that causes devtools to not be able to see the requests

**Comment by merenyimiklos** [comment]
@CoderDake and is there any option to use the network tab? or i just need to wait the improve?

**Comment by CoderDake** [comment]
You may have some luck if you run devtools using your desktop instead of through  browser/IDE.
You can clone our repo, then run 
```
cd packages/devtools_app;
flutter pub get;
flutter run -d macos; # you may need to change this if you don't have macos
```

Then you can attach to your app using the app's VMService url.

The integer overflow only happens when devtools is running in a browser (since Javascript numbers are limited to 52 bits).
So running devtools locally avoids this.

**Comment by CoderDake** [comment]
Other for the IDEs and chrome you will just have to be a bit patient until I can get the rest of the changes through and we can do a new release that makes it into flutter master :)
The first step is done though, and that was getting the fix for the overflow into the actual Dart SDK :D. So now I canstart moving some of the other pieces forwards :D

**Comment by merenyimiklos** [comment]
@CoderDake you are awsome! i will be patient, it looks like soon will be good!

Thank you very much!!!

**Comment by rich-j** [comment]
@CoderDake tried to run using desktop on MacOS following your instructions - failing with:

```
 % flutter pub get
Running "flutter pub get" in devtools_app...
Resolving dependencies... 
Because every version of integration_test from sdk depends on vm_service 9.4.0 and devtools_app depends on vm_service ^10.1.0, integration_test from sdk is forbidden.
So, because devtools_app depends on integration_test from sdk, version solving failed.
pub get failed
command: "/Users/x/Library/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --color --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "/Users/x/Library/flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "/Users/x/.pub-cache",
}
exit code: 1
```

Is there a particular branch we should use?

**Comment by kenzieschmoll** [comment]
you likely need to upgrade your flutter version to run DevTools. Can you switch to flutter master and try again?

**Comment by PiN73** [comment]
Full script to build Desktop DevTools from source:
```
cd ~/StudioProjects
git clone https://github.com/flutter/flutter.git
cd ~/StudioProjects/flutter
git checkout b1c4d5686e79ea8f32ad67469e663fb9d0d2a0ca
cd ~/StudioProjects
git clone https://github.com/flutter/devtools.git
cd ~/StudioProjects/devtools/packages/devtools_app
git checkout c0057efa28d071cbc09b00f157e6937590252b67
~/StudioProjects/flutter/bin/flutter pub get
~/StudioProjects/flutter/bin/flutter build macos --no-tree-shake-icons
cp -r build/macos/Build/Products/Release/devtools_app.app ~/Desktop/FlutterDevtools.app
open ~/Desktop/FlutterDevtools.app
```

Or download [my build](https://github.com/flutter/devtools/files/10693392/FlutterDevTools.app.7z.zip)

Now run your app on iOS Simulator as usual, you'll see
```
Launching lib/main.dart on iPhone SE (3rd generation) in debug mode...
Running Xcode build...
Xcode build done.
Debug service listening on ws://127.0.0.1:port/token=/ws
Syncing files to device iPhone SE (3rd generation)...
```

Copy the `ws://` address to DevTools

**Comment by rich-j** [comment]
The above mentioned bug [Flutter DevTools not showing Network response on iOS device (since 3.7 update)](https://github.com/flutter/flutter/issues/120164) provides an important note - this is a bug only for iOS (simulator?), the Android emulator DevTools works! (We confirmed our issue isn't bad server data :-)

@kenzieschmoll yes we're running on Flutter stable and generally use the iOS simulator for debugging. The update to 3.7 broke the DevTools network view. Switching over to Flutter master to run the fixed DevTools would also require upgrading our code and dependencies - not a task that we want to undertake just to debug... Much simpler to run on Android.

**Comment by merenyimiklos** [comment]
@kenzieschmoll 
i just updated flutter version to 3.7.2 and with my ios simulator there is still no response in network -> response tab :((

**Comment by merenyimiklos** [comment]
@CoderDake it's the response tab on the right

**Comment by CoderDake** [comment]
Ahh my misunderstanding originally then! unfortunately those fixes aren't posted yet and will be coming up soon.
As it stands the Response tab is a bit flaky :(

**Comment by rich-j** [comment]
@CoderDake - concur, the left list of requests is populating. On the right panel, for a "POST" request, both the `Request` tab and the `Response` tab are blank. The `Overview` and `Headers` tabs are populated. This also only happens when running against an iOS simulator, they work when running against the Android emulator. I am running on an Apple silicon Mac.

**Comment by merenyimiklos** [comment]
@CoderDake is there any information about this update? I still have only empty response tab when I use iOS simulator. I checked and when I use Android it works fine.

**Comment by CoderDake** [comment]
Hey @merenyimiklos I am getting the fixes through to the dart-sdk today.
I'll update you when the changes make their way into the beta branches of flutter :D

**Comment by merenyimiklos** [comment]
@CoderDake thank you!!! I look forward to your response

**Comment by CoderDake** [comment]
@merenyimiklos the response tab should behave much better with the fixes in `Devtools 2.22.1`.
these changes are now on flutter master.

See https://github.com/flutter/devtools/issues/2860#issuecomment-1442313329 for more info.

Feel free to reach out if you run into any more issues with this though!

**Comment by merenyimiklos** [comment]
@CoderDake which flutter version exactly?  3.7.5?

**Comment by merenyimiklos** [comment]
@CoderDake and one more question, we have a flutter version 3.7.5 and we got blurry images, not all images some of the project are blurry, is it a common bug? Is there any options to fix this bug? Is it a flutter bug? Because we got this bug after the new big update  (3.7.1)

**Comment by merenyimiklos** [comment]
And by the way @CoderDake it's still not showing the response in the response tab :((

**Comment by CoderDake** [comment]
@merenyimiklos it is fresh enough that it isn't even on any of the tags yet :) you would have to check out flutter master to see the changes right now :D

**Comment by CoderDake** [comment]
As for the blurry images issue you might need to file an issue in flutter/flutter. I'm not familiar with that area.

**Comment by merenyimiklos** [comment]
@CoderDake is there any opinion for the blurry image? Tomorrow I can post here photo too.

**Comment by aligurelli-gymshark** [comment]
flutter 3.7.12 --> stil have same issue

**Comment by mirabo-vuong-nt** [comment]
any update for this issue?

**Comment by leventkantaroglu** [comment]
> any update for this issue?

It seems that it's solved with Flutter 3.10

**Comment by merenyimiklos** [comment]
> any update for this issue?

Yes!
The latest flutter version has the fixed dart version and now works for me the networking tab. Like one and a half month since

**Comment by cheny-github** [comment]
![image](https://github.com/flutter/devtools/assets/25857441/650d783b-933d-4e08-87b5-45eebfba76e9)

flutter --version
Flutter 3.10.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 682aa387cf (2 weeks ago) • 2023-06-05 18:04:56 -0500
Engine • revision 2a3401c9bb
Tools • Dart 3.0.3 • DevTools 2.23.1

 flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.4 22F66 darwin-arm64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] Network resources

I upgraded my flutter version, but I can't see the response return in DevTools, what should I do?

**Comment by merenyimiklos** [comment]
> ![image](https://user-images.githubusercontent.com/25857441/247013485-650d783b-933d-4e08-87b5-45eebfba76e9.png)
> 
> flutter --version Flutter 3.10.4 • channel stable • https://github.com/flutter/flutter.git Framework • revision 682aa387cf (2 weeks ago) • 2023-06-05 18:04:56 -0500 Engine • revision 2a3401c9bb Tools • Dart 3.0.3 • DevTools 2.23.1
> 
> flutter doctor Doctor summary (to see all details, run flutter doctor -v): [✓] Flutter (Channel stable, 3.10.4, on macOS 13.4 22F66 darwin-arm64, locale zh-Hans-CN) [!] Android toolchain - develop for Android devices (Android SDK version 31.0.0) ✗ cmdline-tools component is missing Run `path/to/sdkmanager --install "cmdline-tools;latest"` See https://developer.android.com/studio/command-line for more details. ✗ Android license status unknown. Run `flutter doctor --android-licenses` to accept the SDK licenses. See https://flutter.dev/docs/get-started/install/macos#android-setup for more details. [✓] Xcode - develop for iOS and macOS (Xcode 14.3.1) [✓] Chrome - develop for the web [✓] Android Studio (version 2021.3) [✓] VS Code (version 1.79.2) [✓] Connected device (3 available) [✓] Network resources
> 
> I upgraded my flutter version, but I can't see the response return in DevTools, what should I do?

it seems you need to run this two command:

`path/to/sdkmanager --install "cmdline-tools;latest"`

`flutter doctor --android-licenses`

which device you trying this? Android or iOS?

**Comment by cheny-github** [comment]
ios

**Comment by merenyimiklos** [comment]
> ios

strange...my project working well this scenario

**Comment by cheny-github** [comment]
I don't know what caused it, but in any case I chose to fall back to version 3.3.0 This version is very stable and does not have the above problems, thank you for your reply.

**Comment by kenzieschmoll** [comment]
I think you may be on a stale version of DevTools. Tracking this issue on https://github.com/flutter/devtools/issues/5930
