### ISSUE TITLE
Take snapshot option taking more time

### ISSUE THREAD

**Issue by msarkrish** [flutter/devtools#5195]
Take Snapshot option taking more than 30 minutes and still loading. If 1 time is working, then next 2 time is not working. 

Chart also got stuck.
![image](https://user-images.githubusercontent.com/45334931/217008082-14c44e53-4f9e-4ff6-97e9-c206abb667e6.png)

**Comment by kenzieschmoll** [comment]
@polina-c

**Comment by polina-c** [comment]
@msarkrish , may I ask you to follow [BETA_TESTING.md](https://github.com/flutter/devtools/blob/master/BETA_TESTING.md) and check if the latest version of memory screen works better for you?

**Comment by kenzieschmoll** [comment]
@msarkrish it would also be helpful if you could tell us which DevTools version you are on (see the question mark in the upper right of DevTools)

**Comment by msarkrish** [comment]
@kenzieschmoll DevTools version 2.20.1

**Comment by msarkrish** [comment]
@polina-c  The steps mentioned in the link will work for Windows to?

**Comment by polina-c** [comment]
@msarkrish, the steps are not tested for windows. If you can test them and suggest updates for the steps to fix windows-related friction points, I will highly appreciate.
Or, I can try to find windows around and make sure the steps work. It will take little longer though. Let me know what you prefer.

**Comment by msarkrish** [comment]
@polina-c I will try with beta version in the coming weekend, if not possible I will recreate the scenario with sample code and share the repo, because I can't share my company project.

**Comment by msarkrish** [comment]
Answers: 

> 1. What device your application is running on?

Model: Redmi Note 4
Processor: Snapdragon 625
RAM: 4GB
ROM: 64GB

> 2. What is your windows version?
```
Windows 11 Pro(22H2)
```

> 3. What is your Flutter version (run flutter --version)?
```
Flutter 3.7.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7048ed95a5 (8 days ago) • 2023-02-01 09:07:31 -0800
Engine • revision 800594f1f4
Tools • Dart 2.19.1 • DevTools 2.20.1
```

**Comment by polina-c** [comment]
Thank you. An, which platform (like windows, macos, android, iOS, chrome, iOS emuator, Android emulator) your app is running on? I.e. what do pass to `flutter run` parameter `-d`? or select in VSCode:

<img width="617" alt="Screenshot 2023-02-09 at 10 47 03 AM" src="https://user-images.githubusercontent.com/12115586/217908543-dc94bacc-647d-42c0-8aa2-6e4c6c071b9f.png">

**Comment by polina-c** [comment]
For application to repro, you may want to start with checking if the issue reproduces for https://github.com/flutter/gallery.
(most likely it will require flutter master, not stable)

**Comment by polina-c** [comment]
Improved performance for the current version. Feel free to reopen issue if the problem persists.
