### ISSUE TITLE
not showing the widget tree while opening widget inspector

### ISSUE THREAD

**Issue by rohan165-boop** [flutter/devtools#5205]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Dart Version: 2.19.1
Flutter Version: 3.7.1 / stable
Framework / Engine: 7048ed95a5 / 800594f1f4
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
Thanks for the report. A few questions:
1) Can you add a screenshot? 
2) are there any errors in the chrome devtools console?
3) how did you run your flutter app and launch devtools?
