### ISSUE TITLE
Debugger keyboard shortcuts.

### ISSUE THREAD

**Issue by terrylucas** [flutter/devtools#521]
Now that we support CTRL+o to open a file on the Debugger Page should be add additional shortcut keys e.g., step in, over, out, etc.

What should the shortcut be match DevConsole?

**Comment by natebosch** [comment]
Would be nice to have a shortcut to jump to a line.

**Comment by stevemessick** [comment]
https://github.com/flutter/flutter-intellij/issues/4905 requests shortcuts for Flutter Inspector actions.

**Comment by kenzieschmoll** [comment]
closing in favor of https://github.com/flutter/devtools/issues/3867
