### ISSUE TITLE
Response value not visible in devtools

### ISSUE THREAD

**Issue by voomin** [flutter/devtools#5219]
The signal is caught in the network tab, but the response value is not shown.

___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Dart Version: 2.19.2
Flutter Version: 3.7.2 / stable
Framework / Engine: 32fb2f948e / f40b73f8a4
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
This should be resolved when https://github.com/flutter/devtools/pull/5056 gets merged.

**Comment by dipak2726** [comment]
anytimeline where this will be relased on beta or stable

**Comment by CoderDake** [comment]
@dipak2726 the fixes will be in the next beta. I'm not sure when that is specifically though.

If you want to test out those changes you will be able to test them on the `master` channel of flutter :D
