### ISSUE TITLE
Add an option in DevTools to trigger `debugDumpSemanticsTree()`

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#5240]
We may be able to access this through a service extension or through calling `evaluate('debugDumpSemanticsTree()')` in the semantics/binding.dart library. We may want to expose other `debugDump*` options as well.

**Comment by kenzieschmoll** [comment]
Confirmed that these are available from service extensions. Example: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/binding.dart#L168-L183

**Comment by kenzieschmoll** [comment]
These service extensions are available in debug and profile mode, so we'll need to expose these somewhere outside of the inspector.

**Comment by jacob314** [comment]
rather than dumping to the console, why not display it as a tree using the existing InspectorTree UI that would fully support this use case?

**Comment by jacob314** [comment]
This is a duplicate of https://github.com/flutter/devtools/issues/1397
