### ISSUE TITLE
flutter

### ISSUE THREAD

**Issue by Cyber321-glit-majer** [flutter/devtools#5261]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: x64 (64 bit) windows
Dart Version: 2.19.2
Flutter Version: 3.7.3 / stable
Framework / Engine: 9944297138 / 248290d6d5
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
Hey @Cyber321-glit-majer could you please provide some more information about the issue you were having?
