### ISSUE TITLE
Breakpoints disappear after hot restart

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#5265]
In this .gif, you can see we have one breakpoint before hot restarting. Then we hot restart, and the breakpoint disappears. The test application is running on an iOS simulator.
![breakpoints-gone-after-hot-restart](https://user-images.githubusercontent.com/43759233/219756905-dc9bff78-5613-48de-9711-c305ec0492d5.gif)

(the gif is a bit misleading since when it loops back to the beginning, it looks like the breakpoint comes back, but that is just the gif starting over)

This is a good candidate for an integration test where we can use a real application and trigger a real hot restart.

**Comment by elliette** [comment]
This might be related to https://github.com/flutter/devtools/issues/3359. I thought this was limited to `macos`, but it seems to be more widespread. Breakpoints don't disappear when connected to a web app, which makes me think this might be an issue with the `vm_service`.

**Comment by elliette** [comment]
Opened https://github.com/dart-lang/sdk/issues/52794 to track the work required for the VM service. Once that's resolved, I will add an integration test. FYI @bkonyi @derekxu16

**Comment by elliette** [comment]
This is now fixed after https://github.com/flutter/devtools/issues/7231
