### ISSUE TITLE
Debugger, when connected to web app, opens web_entrypoint.dart by default

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#5266]
actually opened file: file:///Users/polinach/Downloads/apprecordtypes/web_entrypoint.dart
expected file: file:///Users/polinach/Downloads/apprecordtypes/lib/main.dart

**Comment by polina-c** [comment]
@elliette

**Comment by kenzieschmoll** [comment]
closing as a duplicate of https://github.com/flutter/devtools/issues/5350
