### ISSUE TITLE
Eval write operation evaluates to `null`

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#5267]
![Screenshot 2023-02-17 at 10 50 10 AM](https://user-images.githubusercontent.com/43759233/219759259-9903ddec-e757-4db5-9b3f-c2ae180601d4.png)

Is this expected? Should we be returning the object that was modified as a result of the write operation (e.g. the evaluation result of `record.c`? This might be a judgement call - we should probably default to the behavior of other debuggers (intellij / vs code)

**Comment by kenzieschmoll** [comment]
This appears to be what VS code does as well:
![Screenshot 2023-02-17 at 11 06 33 AM](https://user-images.githubusercontent.com/43759233/219764159-778d1c4b-477c-4319-9eb3-18d15fe22756.png)

**Comment by elliette** [comment]
I think this is expected, `addAll` has a void return value: https://api.flutter.dev/flutter/dart-core/Map/addAll.html

**Comment by kenzieschmoll** [comment]
we can probably close this then.
