### ISSUE TITLE
Indices of `Lists` are displayed improperly 

### ISSUE THREAD

**Issue by elliette** [flutter/devtools#5271]
See ![Screenshot 2023-02-17 at 1 02 56 PM](https://user-images.githubusercontent.com/21270878/219795954-f9de828d-c961-4352-85b5-d9f671545f97.png)

**Comment by jacob314** [comment]
What is the actual content of myList. Is it a list of lists?

**Comment by elliette** [comment]
It's an int list: `final myList = [1, 3, 45, 6, 9];`
