### ISSUE TITLE
"No frames available" error when debugger is paused inside async javascript code.

### ISSUE THREAD

**Issue by annagrin** [flutter/devtools#5287]
Repro steps:

Flutter's `example/hello_world` directory:
- run `flutter run -d chrome`
- open the Dart DevTools uri
- hit pause and run until you DevTools does not show where it stopped (takes about 5-6 attempts for me)
- evaluate "true" in the evaluation box
- observe "No frames available" error

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/12737689/220459489-4b4115a8-00e3-4c33-92e4-fbe9520e0aa0.png">

Chrome does show a list of frames available, but all of them async and pretty sure they are all from js code:

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/12737689/220460400-35386ad6-7e00-4146-8292-396eabddc79b.png">

**Some background**

In this example I paused the app, and hit javascript code with no frames on the stack related to dart.

@elliette  looks like the error comes from DevTools, and it happens before the call to `chromeProxyService.evaluateInFrame`. 
https://github.com/flutter/devtools/blob/79099e863bc45795be63d85f5479c65e1953a7d6/packages/devtools_app/lib/src/shared/console/eval/eval_service.dart#L137

Potential solutions: 

- Make dwds continue executing until dart code is hit. Not sure what happens if it never does - in that case the pause will appear not working, so maybe we need a timeout with a warning? This change, if we prefer it, would be most easily done in dwds: https://github.com/dart-lang/webdev/issues/1999

- Or simply assume we only have javascript frames in that case and report an error from DevTools describing that evaluating inside javascript code is not currently supported.

**Comment by annagrin** [comment]
Update: tried to repro the issue in VSCode but could not. Here is the output for the same scenario described in a repro, but using debugger from VSCode:

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/12737689/220462704-619c8dad-a5e8-4156-8ff3-b743df440bed.png">

**Comment by annagrin** [comment]
Update: dwds does have frames when the app is paused:

```[[Frame index: 3433], [Frame index: 3434], [Frame index: 3435], [Frame
index: 3446], [Frame index: 3456], [Frame index: 3457], [Frame index: 3460], [Frame index: 3461],
[Frame index: 3470], [Frame index: 3476], [Frame index: 3477], [Frame index: 3480], [Frame index:
3481], [Frame index: 3484]]```

So my guess is that the current frames index cannot be found there. If this is correct, I think we can just change the error message to something like "The program paused in async code, evaluation is not currently supported in async code by chrome"

**Comment by elliette** [comment]
I investigated this first solution:

> Make dwds continue executing until dart code is hit. Not sure what happens if it never does - in that case the pause will appear not working, so maybe we need a timeout with a warning? This change, if we prefer it, would be most easily done in dwds: https://github.com/dart-lang/webdev/issues/1999

It's a pretty simple change to make that happen (simply set `_isStepping` to `true` [here](https://github.com/dart-lang/webdev/blob/aef715da7aafcdef7c0c97ccaabb288d3347dc60/dwds/lib/src/debugging/debugger.dart#L93)) , however if we never hit a dart location (and keep stepping further into JS code), it's an awful experience (see gif below, basically Chrome is stuck in an infinite stepping loop). I'm not sure a timeout could alleviate that. 
![Mar-15-2023 15-13-00](https://user-images.githubusercontent.com/21270878/225455411-99b94084-f351-4f27-b957-9875dd2c7180.gif)


I think the solution I like a bit better is when we got to calculate the stack frames when an app is paused, we include JS frames if there are not dart frames available. I will open up a PR for that.

**Comment by annagrin** [comment]
I don't think we should show JS frames - they are numerous and not useful. Let's brainstorm on this.

**Comment by elliette** [comment]
Adding some notes from discussion:

- Currently, if we pause in the injected client, we don't hit Dart SDK code by continuing to stepping (tried by pausing in Chrome DevTools and manually stepped >100 times. If we try to keep stepping we will end up in the situation above. 
- One option is to include source maps for the injected client, so if we pause there at least we will show the Dart stack trace and variables. 
- Another option is to use the new [`skipList`](https://chromedevtools.github.io/devtools-protocol/1-3/Debugger/#method-stepInto) option to exclude the injected client. I'm curious if this would also preventing us from pausing in the injected client in the first place. 

Related: https://github.com/dart-lang/webdev/issues/2034

**Comment by elliette** [comment]
This has been fixed, we are now showing "No Dart frames, likely paused in JS" ( see https://github.com/flutter/devtools/pull/5427)

Opened DWDS bug to track what is left for DWDS: https://github.com/dart-lang/webdev/issues/2467
