### ISSUE TITLE
On application hot restart selected isolate silently switch from main to vm-service

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#5288]
both application and devtools are on macos in debug mode

https://user-images.githubusercontent.com/12115586/220461799-b1eacca7-5234-461d-b4d1-fe99782a4d13.mov

**Comment by kenzieschmoll** [comment]
this seems related to https://github.com/flutter/devtools/issues/5017 (see @bkonyi's comment)

**Comment by CoderDake** [comment]
Fixed in https://github.com/flutter/devtools/pull/6436
