### ISSUE TITLE
Support expression evaluation while the app is running 

### ISSUE THREAD

**Issue by annagrin** [flutter/devtools#5292]
Dart code allows evaluation in a root library when app is not paused, but dart DevTools currently does not.
  - Suggestions:
    - call `vmService.evaluate()` on root library ID in DevTools if app is not paused. 
    - See dart-code:
     https://github.com/Dart-Code/Dart-Code/blob/aeea8df97ebe3de1c805f7767bd662cb3bc8f895/src/debug/dart_debug_impl.ts#L1595

**Comment by kenzieschmoll** [comment]
@polina-c implemented this last week: https://github.com/flutter/devtools/pull/5248. Does this completely solve your FR @annagrin?
