### ISSUE TITLE
Network response tab fails to build

### ISSUE THREAD

**Issue by CoderDake** [flutter/devtools#5314]
https://github.com/flutter/devtools/issues/2860#issuecomment-1442662680
![image](https://user-images.githubusercontent.com/1386322/221586494-48130180-a711-4acd-b0af-d3c62b80f204.png)

Shows a grey box in the response tab which means there may have been an error building the response tab.

**Comment by CoderDake** [comment]
@VanLong-official could you please provide some more information about the issue you are having?
- Does the response tab ever get to a better state?
- If you "Toggle Developer Tools", do you seen any errors that pop up when you reproduce this?
    - ![Screenshot 2023-02-27 at 9 18 20 AM](https://user-images.githubusercontent.com/1386322/221587742-af3cfbf0-25f8-468b-b5bc-c1fea07b2735.png)
- Is there anything special about the requests you are trying to inspect?

Any other information would be greatly appreciated

**Comment by merenyimiklos** [comment]
@CoderDake hey, i have the same issue, not grey screen, just the last error still have, no response data in the response page
<img width="1676" alt="kep" src="https://user-images.githubusercontent.com/89610165/221594651-cad4aa1c-98cc-4963-a561-19ff93c198fc.png">

**Comment by CoderDake** [comment]
@merenyimiklos fascinating :O 
Could you please try toggling the  vscode developer tools to see if there are any errors showing up in the console?

**Comment by merenyimiklos** [comment]
@CoderDake no error in the debug console, or in the output, so don't know this

**Comment by CoderDake** [comment]
@merenyimiklos if I was to put together a special DevTools branch, with detailed logging, would you be open to reproducing this so that I can get a more in depth Idea of what is going on behind the scenes?

**Comment by DarrellBrogdon** [comment]
I'm having the same problem.  I'm running Dart DevTools version 2.20.1.

Attached is my VSCode with the console.

![Screenshot 2023-03-01 at 10 21 17 PM](https://user-images.githubusercontent.com/196196/222469884-41c2159a-1a99-44dc-aeec-f06c6a16bcc5.jpg)

**Comment by CoderDake** [comment]
@DarrellBrogdon Could you please try this again with the master channel of flutter? It has some fixes pertaining to the network tab.
to change your flutter channel you can use
`flutter channel master`
If you run your app with that version, then you should get access to the new version, `Devtools 2.22.1`.

**Comment by DarrellBrogdon** [comment]
Yep, that works.  Thanks!

**Comment by CoderDake** [comment]
@merenyimiklos @DarrellBrogdon If you would like to try out the new logging behaviour I'm getting ready, you can try out the following:

1. Clone the[ flutter/devtools](https://github.com/flutter/devtools) repo
2. checkout the [`network-logging`](https://github.com/flutter/devtools/tree/network-logging) branch
3. Change your flutter to master using `flutter channel master; flutter upgrade`
4. `cd devtools/packages/devtools_app`
5. `flutter pub get`
6. `flutter run -d chrome`
7. Once Devtools open up you should be able to connect to your app.
8. Click on the settings at the top right
 
![Screenshot 2023-03-07 at 10 12 42 AM](https://user-images.githubusercontent.com/1386322/223464504-5b082dd9-d570-47b3-a58e-81324b957f7e.png)

9. Enable the verbose logging setting.
10. Next click the clear button beside the "enable verbose logging" setting
![Screenshot 2023-03-07 at 10 12 58 AM](https://user-images.githubusercontent.com/1386322/223465193-4dec5385-4472-42ef-bf86-0a368bda1ba8.png)

11. Now go reproduce the behaviour
12. after reproducing, come back to the settings and click the copy button beside the logging setting
13. check to make sure there is no sensitive information.
14. then you should be able to upload those logs here, hopefully it will help point out what is going wrong.

**Comment by CoderDake** [comment]
@DarrellBrogdon unfortunately there is nothing we can do to accelerate Devtools through the master, beta and stable channels.

Until the changes make it through to stable, you may just need to flip to master while doing network debugging. (Assuming we can get this stuff working smoothly for everyone)

**Comment by merenyimiklos** [comment]
@CoderDake i will wait for this, and until i will work with Android if i need network table i guess... :D 

how long is it take to take the feature to the stable channel?

**Comment by CoderDake** [comment]
Oh oops sorry for pinging you About the master channel stuff Darrell I was supposed to ping in a different issue about that.

**Comment by CoderDake** [comment]
@merenyimiklos I believe that changes are made to the stable channel once per quarter. So about once every three months

**Comment by CoderDake** [comment]
I believe this issue should be fixed in https://github.com/flutter/devtools/issues/5327

We are doing a release in the next coming weeks so it should make it to the next flutter beta.
