### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by abduraimovdev** [flutter/devtools#5332]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: arm64 (64 bit) macos
Dart Version: 2.18.6
Connected app type: Dart CLI

**Comment by CoderDake** [comment]
Hey @abduraimovdev  could you please provide some more information about the issue you are running into? :)

**Comment by abduraimovdev** [comment]
> Hey @abduraimovdev  could you please provide some more information about the issue you are running into? :)

Yeah

**Comment by kenzieschmoll** [comment]
Without more information, we cannot resolve this issue. Please upgrade to the latest version of DevTools 2.23.1, as it seems you are on a pretty old version. The latest version can be found on the newest flutter stable. Thanks.
