### ISSUE TITLE
Embedded DevTools Debugger in chrome is not dense

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#5335]
The inspector appears to be properly in dense mode,  but the debugger does not. We either need to ensure dense mode is enabled, or tweak the debugger to have more "dense-aware" UI.

Separate but related issue - we probably want to expose the DevTools settings button in the footer like we do for the report feedback and about devtools buttons in embedded mode. 

![Screenshot 2023-03-01 at 10 15 42 AM](https://user-images.githubusercontent.com/43759233/222227852-34574d0c-264c-4a85-b68c-29730fb12f78.png)

**Comment by elliette** [comment]
Note: Seems like the logging page also doesn't have "dense mode"
