### ISSUE TITLE
Eval hovercard should show evaluation error when eval fails

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#5336]
![eval-fail-hover](https://user-images.githubusercontent.com/43759233/222240025-843892d4-1f97-41ef-b718-02b055ac69da.gif)

In the current state, the eval card shows and then is quickly removed when the evaluation fails. As a user, I would want to know that the evaluation failed and not just that DevTools is buggy and broken. 

When this same evaluation is done on the console, we see the error:
![Screenshot 2023-03-01 at 10 46 31 AM](https://user-images.githubusercontent.com/43759233/222240378-58a919fb-886a-4da1-8975-c0828e9aa78c.png)

**Comment by elliette** [comment]
Related: https://github.com/dart-lang/webdev/issues/2009

**Comment by elliette** [comment]
I'm going to close this as not reproducible, I can't think of an example to try that would cause an evaluation error that wouldn't cause a runtime error now that the null-safety migration is complete.
