### ISSUE TITLE
Suggestion: Support webadb connect Android device

### ISSUE THREAD

**Issue by FourLeafTec** [flutter/devtools#5341]
In WebIDE(like Github Codespaces), it's very hard to debug on Android device.
We can use network debug, but it's complicated.

I found out there is [WebUSB_API](https://developer.mozilla.org/en-US/docs/Web/API/WebUSB_API) in modern browser.
And it is able to implement [WebADB for Android](https://bielej.org/adb/#/)
In vscode, also support for using [WebUSB](https://developer.mozilla.org/docs/Web/API/WebUSB_API), [Web Serial](https://developer.mozilla.org/docs/Web/API/Web_Serial_API), and [WebHID](https://developer.mozilla.org/docs/Web/API/WebHID_API) from [web extensions](https://code.visualstudio.com/api/extension-guides/web-extensions).
[WebUSB, WebSerial, and WebHID access on web](https://code.visualstudio.com/updates/v1_69#_webusb-webserial-and-webhid-access-on-web)

If devtools and vscode extensions could support debug Android device in broweser just like [esp-web-flash-server](https://github.com/bjoernQ/esp-web-flash-server) ,it will be Amazing.

**Comment by elliette** [comment]
You should be able to use DevTools, regardless of your IDE. Please follow instructions here: https://docs.flutter.dev/tools/devtools#start

Please re-open or file a new issue if this did not answer your question. Thanks!
