### ISSUE TITLE
Native stack frames are missing their names

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#5343]
![Screenshot 2023-03-02 at 1 59 45 PM](https://user-images.githubusercontent.com/43759233/222568304-7d212d3e-63e4-4847-bc7f-8fd61d1d1554.png)

In the [code that generates stack frame json](https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/screens/profiler/cpu_profile_model.dart#L1316) from a `vm_service.CpuSamples` object, something must be going awry. The data for `_code` looks suspicious @bkonyi 
![Screenshot 2023-03-02 at 2 24 04 PM](https://user-images.githubusercontent.com/43759233/222573480-8b57b91a-9175-4fcf-ac04-ab3cac7a3e09.png)

**Comment by kenzieschmoll** [comment]
Looks like this is the issue: https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/screens/profiler/cpu_profile_model.dart#L1240

@bkonyi can `ProfileFunction.function` only be `FuncRef` or `NativeFunction`? It would be helpful if this was specified by the vm service specs

**Comment by bkonyi** [comment]
> @bkonyi can `ProfileFunction.function` only be `FuncRef` or `NativeFunction`? It would be helpful if this was specified by the vm service specs

Yep, and [it is... :-)](https://github.com/dart-lang/sdk/blob/main/runtime/vm/service/service.md#profilefunction)
