### ISSUE TITLE
[Impeller] Tune messaging about Impeller as it relates to shader compilation jank in DevTools.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/devtools#5349]

**Comment by kenzieschmoll** [comment]
> For instance, it should not suggest using Impeller for Android users before the stable preview.

What is the timeline for this? For now, should I add the suggested messaging only for iOS? What about desktop?

**Comment by jonahwilliams** [comment]
only for iOS for now. We don't have a certain timeline for other platforms yet.
