### ISSUE TITLE
The Network tab always show empty Request and Response data

### ISSUE THREAD

**Issue by TheManuz** [flutter/devtools#5360]
<-- Please describe your problem here. Be sure to include repro steps. -->

I can see the requests list fine.
I can inspect single request and see the **Overview** and the **Headers** tab.
However, the **Request** and **Response** tabs are always empty.

The problems is present in both web based tools and VsCode tools.
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Dart Version: 2.19.2
Flutter Version: 3.7.3 / stable
Framework / Engine: 9944297138 / 248290d6d5
Connected app type: Flutter native (debug build)
![Overview](https://user-images.githubusercontent.com/2032334/223161727-4ce06f0a-e7b9-4c4e-9e42-07249ef94b33.png)
![Headers](https://user-images.githubusercontent.com/2032334/223161750-60be3110-04c9-4c1f-b7ec-ab246b6d410d.png)
![Request](https://user-images.githubusercontent.com/2032334/223161776-ab913544-2bdd-498b-99de-851f0d651c65.png)
![Response](https://user-images.githubusercontent.com/2032334/223161794-4d9ff562-71fc-41d2-8ec0-42a4cfb02947.png)

**Comment by kenzieschmoll** [comment]
@CoderDake

**Comment by gogovan-jacksonchung** [comment]
same. the request and response tab content are both empty in iOS builds, but it can show in Android builds.

flutter version: 3.7.6
DevTools version: 2.20.1

**Comment by TheWalkingDead1024** [comment]
got the same issue. flutter version：3.7.3，DevTools version:2.20.1
