### ISSUE TITLE
project not debugging on web

### ISSUE THREAD

**Issue by donsolace01** [flutter/devtools#5374]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: Web windows
Dart Version: 2.18.6
Flutter Version: 3.3.10 / stable
Framework / Engine: 135454af32 / 3316dd8728
Connected app type: Flutter web (debug build)

**Comment by elliette** [comment]
Hi @donsolace01! Could you provide a few more details, including how you are running your app and connecting to DevTools? Thanks!
