### ISSUE TITLE
Not able to see response of HTTP call

### ISSUE THREAD

**Issue by zulkarnainshah** [flutter/devtools#5385]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Dart Version: 2.19.0
Flutter Version: 3.7.0 / stable
Framework / Engine: b06b8b2710 / b24591ed32
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
@zulkarnainshah If you need to do some network debugging, there are some fixes to the network inspector that are available on flutter master. You can switch to it using:
`flutter channel master; flutter upgrade`
When you want to change back to stable you can:
`flutter channel stable; flutter upgrade`

The fixes are on `Devtool 2.22.1`

If you continue to have issues loading the responses please feel free to add more context here: https://github.com/flutter/devtools/issues/5314
Or to open up a new issue if you feel like it is unrelated to that issue.
