### ISSUE TITLE
Request tab json formatter

### ISSUE THREAD

**Issue by MarcinHradowicz** [flutter/devtools#5413]
Previously (using Flutter 3.3.7), `Request` tab was showing data formatted, which was way more readable. Now in Flutter 3.7.1 it is just raw text. I think it's related to this PR https://github.com/flutter/devtools/pull/4602/files.
Btw `Response` tab shows data exactly the same for both Flutter versions.

**Flutter 3.7.1:**
<img width="701" alt="image" src="https://user-images.githubusercontent.com/89776748/224990372-ead3c87d-ff8a-412a-9222-5b4ffde1582e.png">

**Flutter 3.3.1:**
<img width="403" alt="image" src="https://user-images.githubusercontent.com/89776748/224991745-5a134647-28a3-42bf-af9e-a241e71f203d.png">

I have content-type set to json. 🤔 Any idea what’s the problem?
<img width="298" alt="image" src="https://user-images.githubusercontent.com/89776748/224992022-3d231719-af02-4a93-8716-c4e6f6843674.png">

**Comment by CoderDake** [comment]
Thanks for the great issue here @MarcinHradowicz .
I've been able to reproduce this. It looks like the content-type is an array of strings, `contains('json')` is returning false.

I will fix this up soon :)
