### ISSUE TITLE
Widget Tree doesn't display

### ISSUE THREAD

**Issue by shekerhack** [flutter/devtools#5415]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: x64 (64 bit) ios
Dart Version: 2.19.2
Flutter Version: 3.7.4 / stable
Framework / Engine: b4bce91dd0 / 248290d6d5
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
Duplicates https://github.com/flutter/devtools/issues/5415

**Comment by shekerhack** [comment]
Widget tree doesn't work, can anyone help.

**Comment by CoderDake** [comment]
@shekerhack I've got a PR coming through soon that will add some logging to Devtools.
To get information about when that happens, you can watch this issue: https://github.com/flutter/devtools/issues/5237#issuecomment-1470861086

When that logging code goes through it would be great if you could help by providing some logs. Perhaps there will be something there that will help us diagnose what is going on.

**Comment by shekerhack** [comment]
<img width="1440" alt="Screenshot 2023-03-16 at 12 58 24 PM" src="https://user-images.githubusercontent.com/99459110/225710690-2ea213d6-52ee-4096-b7c3-7f6beac74acf.png">

**Comment by CoderDake** [comment]
Yes sorry you will need to wait a little bit.
The pull request to get it on to flutter/devtools master hasn't landed yet :)

This is the PR That I need to get approved to go through first:
https://github.com/flutter/devtools/pull/5404

After that happens then you should be able to follow these instructions:
https://github.com/flutter/devtools/issues/5237#issuecomment-1470861086

**Comment by CoderDake** [comment]
@shekerhack The PR has been submitted.
Please feel free to give https://github.com/flutter/devtools/issues/5237#issuecomment-1470861086 a try, and report back in that issue with logs if possible :D
