### ISSUE TITLE
Investigate logging of errors in futures

### ISSUE THREAD

**Issue by CoderDake** [flutter/devtools#5425]
While developing the logging code, I discovered that an error happening in `getFullRequestData` was not being reported to the error logging.

After some research I found out that using `unawaited` is only ever meant to be used on code that is always excepted to return a value. It's documentation states:
```
If the future completes with an error,
/// it was likely a mistake to not await it.
/// That error will still occur and will be considered unhandled
/// unless the same future is awaited (or otherwise handled) elsewhere too.
/// Because of that, `unawaited` should only be used for futures that
/// are *expected* to complete with a value.
```

As a result of this research we should investigate our use of unawaited, and whether errors thrown in futures will be logged

**Comment by CoderDake** [comment]
It may also be worth logging any javascript errors. I'm not sure if this is possible though.
example:

**Comment by CoderDake** [comment]
After doing some research it appears that this may be a web specific bug.
I haven't been able to create a minimum reproduction of it yet though.

**Comment by CoderDake** [comment]
Reminder: Tag @elliette if I end up making a dart-sdk bug for this.

**Comment by elliette** [comment]
Note: We "solved" this in DWDS by creating a helper function to catch any exceptions thrown in `unawaited` futures. See https://github.com/dart-lang/webdev/pull/1938

```

void safeUnawaited(
  Future<void> future, {
  void Function(dynamic, StackTrace)? onError,
}) {
  onError ??= (error, stackTrace) =>
      _logger.warning('Error in unawaited Future:', error, stackTrace);
  unawaited(future.catchError(onError));
}
```

**Comment by CoderDake** [comment]
It looks like #5456 addressed this issue. I've tested with other unawaited sections and the errors seem to now get appropriately reported.
While investigating this I found that we should be adding a newline to the last log entry when copying though.
That has been addressed here: https://github.com/flutter/devtools/pull/5538
