### ISSUE TITLE
RenderFlex children have non-zero flex but incoming height constraints are unbounded.

### ISSUE THREAD

**Issue by OlimpiaLuxury** [flutter/devtools#5428]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Dart Version: 2.19.2
Flutter Version: 3.7.3 / stable
Framework / Engine: 9944297138 / 248290d6d5
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
This doesn't appear to be an issue with Flutter DevTools, but rather with your Flutter app. If you are experiencing issues with DevTools itself, please feel free to open another issue with more details. Thanks!
