### ISSUE TITLE
una duda donde puedo ver el codigo que se modifica para poderlo utilizar

### ISSUE THREAD

**Issue by ealvarado777** [flutter/devtools#5434]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Dart Version: 2.19.0
Flutter Version: 3.7.0 / stable
Framework / Engine: b06b8b2710 / b24591ed32
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
Hey @ealvarado777 the widget inspector is only used to preview changes that are made.
For now if you want to make a change permanent, you will need to manually modify the widget properties in your code.

This is something that we want to accomplish in the future, it is just not implemented yet though.
