### ISSUE TITLE
inconsistent fonts used in the about box

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#5442]
The DevTools about box has some inconsistent fonts used:

<img width="582" alt="Screenshot 2023-03-17 at 4 12 09 PM" src="https://user-images.githubusercontent.com/1269969/226068040-8a727ee7-6762-414e-9bd2-5729e6e998b7.png">

In particular, the links seem to be using a smaller font and are aligned to a different baseline than the non-hyperlink text.

___
**DevTools version**: 2.22.2

**Comment by kenzieschmoll** [comment]
this is resolved
