### ISSUE TITLE
need some padding under a 'clear' button

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#5443]
In the app size screen, there's no padding between the 'Clear' button on the upper right of the screen, and the page's contents:

<img width="250" alt="Screenshot 2023-03-17 at 4 15 15 PM" src="https://user-images.githubusercontent.com/1269969/226068237-76512408-8375-44e3-addb-4b5fe52ab2a9.png">

___
**DevTools version**: 2.22.2

**Comment by kenzieschmoll** [comment]
This is obsolete on master
![Screenshot 2023-03-20 at 11 46 53 AM](https://user-images.githubusercontent.com/43759233/226437201-39ca04ea-547c-4733-aec7-46e4adacf1b8.png)
