### ISSUE TITLE
unable to connect vm service in flutter

### ISSUE THREAD

**Issue by rana05042022** [flutter/devtools#5445]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: ia32 (32 bit) android
Dart Version: 2.19.4
Flutter Version: 3.7.7 / stable
Framework / Engine: 2ad6cd72c0 / 1837b5be5f
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
@rana05042022 I'm sorry to hear you are having issues.
Without more information it is difficult for us to diagnose what might be going wrong.
Could you please provide some more information about how you are encountering the issue?
