### ISSUE TITLE
Provider is not working in devtools

### ISSUE THREAD

**Issue by phubh** [flutter/devtools#5447]
___package:provider (6.0.5) doesn't show any thing in devtools.
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: Web windows
Dart Version: 2.19.2
Flutter Version: 3.7.3 / stable
Framework / Engine: 9944297138 / 248290d6d5
Connected app type: Flutter web (debug build)

**Comment by polina-c** [comment]
Can you add steps to repro please?
