### ISSUE TITLE
Setup DCM for bots

### ISSUE THREAD

**Issue by CoderDake** [flutter/devtools#5479]

**Comment by polina-c** [comment]
CC @incendial

**Comment by polina-c** [comment]
- [ ] configure keys (@CoderDake )
- [ ] configure bot (draft: https://github.com/flutter/devtools/pull/5582)
- [ ] create README on how to maintain keys (@CoderDake )
- [ ] add steps on how to turn on DCM locally (@incendial )
- [ ] enable/fix first set of lints (@polina-c https://github.com/flutter/devtools/pull/5623)
- [ ] enable/fix other valuable lints

**Comment by polina-c** [comment]
https://github.com/flutter/devtools/pull/5655
