### ISSUE TITLE
Network tab not working with WebSocket

### ISSUE THREAD

**Issue by jorgerider** [flutter/devtools#5489]
I cannot see WebSocket being sent/received in Network. I can see how the WebSocket was being triggered, but I cannot see data received/sent though it
___
**DevTools version**: 2.15.0

**Comment by CoderDake** [comment]
@jorgerider there are a lot of network fixes in `Devtools 2.22.1`. Right now it is on the flutter master channel, but will soon be moving forwards to the beta.

If you would like to try out these new changes you can change your flutter channel to master using:
`flutter channel master; flutter upgrade`

Then if you want to switch to stable afterwards you can:
`flutter channel stable; flutter upgrade`

If you still end up having issues with the most recent version of DevTools on flutter master, feel free to open up another ticket :D
