### ISSUE TITLE
There is no body for requests and response in the network inspector 

### ISSUE THREAD

**Issue by omar6533** [flutter/devtools#5512]
<-- Please describe your problem here. Be sure to include repro steps. -->

I used to inspect the parameters sent in my request in the network, it is been like 2 months and the same issue is there I hope the Flutter team fixes this ASAP
___
**DevTools version**: 2.20.1
<img width="825" alt="Screenshot 2023-03-24 at 3 38 36 PM" src="https://user-images.githubusercontent.com/87979640/227523412-388e734f-60fe-4491-b9a3-183bdfd60daa.png">

**Connected Device**:
CPU / OS: x64 (64 bit) ios
Dart Version: 2.19.2
Flutter Version: 3.7.5 / stable
Framework / Engine: c07f788888 / 0f359063c4
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
@omar6533 there are a lot of network fixes in Devtools 2.22.1. Right now it is on the flutter master channel, but will soon be moving forwards to the beta.

If you would like to try out these new changes you can change your flutter channel to master using:
flutter channel master; flutter upgrade

Then if you want to switch to stable afterwards you can:
flutter channel stable; flutter upgrade

If you still end up having issues with the most recent version of DevTools on flutter master, feel free to open up another ticket :D
