### ISSUE TITLE
Enabling VM developer mode results in unexpected UI changes

### ISSUE THREAD

**Issue by elliette** [flutter/devtools#5523]
Steps to repro:

- Connect DevTools to web app (`flutter run -d chrome`)
- Open the settings dialog and toggle VM developer mode on, off, and on again (**question: should this even be an option for web apps?**)
- UI updates itself inconsistently (see gif)

FYI @bkonyi 

![vm mode small](https://user-images.githubusercontent.com/21270878/227661787-21ae6f9a-4f40-4c4c-bf20-db86be02f75b.gif)

**Comment by kenzieschmoll** [comment]
This is obsolete now that extra tabs are rendered in an overflow menu. WRT "question: should this even be an option for web apps? - yes, this is a top level DevTools setting so it should always be present regardless of the connected app type or whether or not there is a connection.
