### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by git-frenzy** [flutter/devtools#5547]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Dart Version: 2.19.5
Flutter Version: 3.7.8 / stable
Framework / Engine: 90c64ed42b / 9aa7816315
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
@git-frenzy we need a little bit more information to help us understand any issues you are running into.
Please feel free to reopen this with some more information :)
