### ISSUE TITLE
Support horizontal scrolling in DevTools tables, and show scrollbar

### ISSUE THREAD

**Issue by TheCarpetMerchant** [flutter/devtools#5596]
![image](https://user-images.githubusercontent.com/5080204/229312674-2eeeacaf-a45d-4b54-81b6-de68ba9a9dd0.png)

I cannot see the full call tree because it is not horizontally scrollable. Is there any workaround ?

DevTools v2.20.1

**Comment by kenzieschmoll** [comment]
The table is horizontally scrollable with a mousewheel or trackpad. Can you try shift + scroll if your mouse wheel does not have horizontal scrolling?

What OS are you on?

**Comment by TheCarpetMerchant** [comment]
I tried with a trackpad and indeed it works. But Shift+Mouse scroll doesn't. I'm on Windows.

In addition to that, there should be an horizontal scrollbar (not only for usability but just to know horizontally scrolling is a possibility).

**Comment by kenzieschmoll** [comment]
Closing as a dupe of https://github.com/flutter/devtools/issues/4732
