### ISSUE TITLE
Self-time column sort not sorting properly

### ISSUE THREAD

**Issue by TheCarpetMerchant** [flutter/devtools#5597]
![image](https://user-images.githubusercontent.com/5080204/229312928-fd7cd11a-04fa-4ed4-b2e1-180ea2e11cf9.png)
![image](https://user-images.githubusercontent.com/5080204/229312938-3e2522e9-6363-4c8c-acbe-c5d97814632e.png)

I'm not sure what it's sorting on exactly here.

DevTools v2.20.1

**Comment by kenzieschmoll** [comment]
Can you post a full screenshot? Since this is a tree table, sorting does not modify the tree structure. I suspect that the elements with 1.31 ms are sub nodes of the 0.00 ms entry directly above.

**Comment by TheCarpetMerchant** [comment]
That makes sense. However, it would still be nice to have an easy way of identifying single functions with high CPU usage.
Maybe in another tab where you can see a list of all functions used (sorted by usage), and have a way of selecting one and listing the functions calling it. And this recursively.

In any case, I have my answer and this is not a bug. Thanks !

**Comment by kenzieschmoll** [comment]
Good news! We just added a Method Table to the CPU profiler, which sounds like exactly what you are looking for: https://github.com/flutter/devtools/pull/5366. This is now on Dart master `dart devtools` and should be on Flutter master soon.

**Comment by TheCarpetMerchant** [comment]
Glad to see you're ahead of the curve !
