### ISSUE TITLE
Enable visibility for CPU footprint of GC events.

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#5616]
We need it to help user to detect if frequent GC impacts performance or no.

This issue is referenced in comment in [go/devtools-memory-documentation-updates](http://goto.google.com/devtools-memory-documentation-updates), for the section ''GC happens too often".

<img width="693" alt="Screenshot 2023-04-05 at 2 02 28 PM" src="https://user-images.githubusercontent.com/12115586/230211446-77b237ef-ef9b-4150-b973-d3122a54697c.png">

**Comment by kenzieschmoll** [comment]
This is fixed since there is now a setting to show CPU samples in the timeline
