### ISSUE TITLE
Network tab does not show any request or response body

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter/devtools#5618]
Hello,

I want to trace network and I am able to see network requests with headerrs but request and response body are empty. I am using graphql API

Fluter doctor
```
[✓] Flutter (Channel stable, 3.7.9, on macOS 13.2.1 22D68 darwin-x64, locale en-CH)
Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.76.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

![Screenshot 2023-04-06 at 11 31 08](https://user-images.githubusercontent.com/3918999/230336076-1dafeb36-04ec-43c2-b849-4dc809e39fdc.png)

**Comment by kenzieschmoll** [comment]
What DevTools version are you on? running `flutter --version` should tell you. The error you are seeing is likely resolved on DevTools from the Flutter beta and master branches. If you can reproduce with DevTools 2.22.2 and newer, please re-open this issue. Thanks!

**Comment by 99yhf** [comment]
> DevTools 版本
2.20.1
