### ISSUE TITLE
Memory screen - dead "More info" links

### ISSUE THREAD

**Issue by anderdobo** [flutter/devtools#5620]
On the Memory screen, the "More info" on the Help popovers of the Profile and Trace tabs lead to to a dead link (https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/screens/memory/panes/allocation_tracing/ALLOCATION_TRACING.md)
`DevTools 2.20.1`
`Flutter 3.7.10 • channel stable `

**Trace tab**
<img width="1336" alt="Screenshot 2023-04-06 at 3 41 41 PM" src="https://user-images.githubusercontent.com/5350105/230507296-33b942b5-3b2e-4bbf-9066-9648fc9c6228.png">

**Profile tab**
<img width="1334" alt="Screenshot 2023-04-06 at 3 41 22 PM" src="https://user-images.githubusercontent.com/5350105/230507251-10f26e00-431d-46a0-a6d6-f52807bf8ae2.png">

URL destination
<img width="1331" alt="Screenshot 2023-04-06 at 3 53 12 PM" src="https://user-images.githubusercontent.com/5350105/230508170-e1a3be25-364a-4603-a1c7-fab68f8dbced.png">

**Comment by elliette** [comment]
FYI @polina-c

**Comment by kenzieschmoll** [comment]
This is now fixed
