### ISSUE TITLE
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)

### ISSUE THREAD

**Issue by navdeepsingh84** [flutter/devtools#5633]
Can any one help me to resolve this issue..

![image](https://user-images.githubusercontent.com/26953725/231096990-92a4e61e-c07b-42df-a977-8c256e4f73c6.png)
![image](https://user-images.githubusercontent.com/26953725/231097445-09d912ee-70af-4c69-840c-45517568a407.png)

**Comment by elliette** [comment]
Hi @navdeepsingh84 ! Could you please provide repro steps and the output of `flutter doctor`? Thanks
