### ISSUE TITLE
Response tab is empty on Flutter devtools' network page.

### ISSUE THREAD

**Issue by James-Don** [flutter/devtools#5634]
I started the [ashitaprasad](https://github.com/ashitaprasad)
/
[network_view_demo](https://github.com/ashitaprasad/network_view_demo and clicked scenario1, I can see the json on response tab of Flutter's devtools in vs code. I set a breakpoint, checked request and response values in the http call and the response tab on Flutter devtool's network page could not show anything.
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: x64 (64 bit) android
Dart Version: 2.19.5
Flutter Version: 3.7.8 / stable
Framework / Engine: 90c64ed42b / 9aa7816315
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
If you are able to try using DevTools from the flutter beta or master channels, this issue is likely resolved. Can you try and report back whether the issue is fixed?

**Comment by James-Don** [comment]
> If you are able to try using DevTools from the flutter beta or master channels, this issue is likely resolved. Can you try and report back whether the issue is fixed?

Could you please paste the link here?

**Comment by kenzieschmoll** [comment]
This will require that you change your flutter channel. `flutter channel master` or `flutter channel beta`. You may also need to run `flutter upgrade` after switching branches. Then run your flutter app as normal and open DevTools. You should see a newer version of DevTools than 2.20.1.

**Comment by James-Don** [comment]
Tried Flutter 3.9.0 beta for the project network_view_demo seems the problem of empty response tab on network page is solved. Thanks!

However I can not use the latest Flutter version for my own project due to dependency issue. When will you release a stable version?

**Comment by kenzieschmoll** [comment]
Great! Flutter has a quarterly stable release due soon. Keep an eye out for this some time next month 👍
