### ISSUE TITLE
Run DCM as a Github workflow in a PR from a forked repository 

### ISSUE THREAD

**Issue by elliette** [flutter/devtools#5636]
All DevTools development work is done in a fork of DevTools, instead of branching off the `flutter/devtools` repo. This means that PRs to DevTools are opened from the contributor's fork. 

Unfortunately, this is causing problems when trying to add DCM analyze as a Github workflow step when a PR is opened:

-  I believe the only way to share the email / key with the workflow (and not leak it) is to use encrypted secrets. This is what the `${{ secrets.DCM_CI_KEY }}` refers to here: ttps://github.com/flutter/devtools/pull/5582
- But Github does not allow secrets to be run on workflows triggered from a PR coming from a fork of the repo:

> "With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository." [source](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow)

@incendial We'll need a way to support running `dcm analyze` for Github workflows coming from a forked repository.

**Comment by incendial** [comment]
@elliette any chance you'd be comfortable moving DCM checks to [`pull_request_target`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) event instead of `pull_request`? Since DCM does not build or run the code looks like using this event is safe.

**Comment by elliette** [comment]
Hi @incendial! That should work for us, thanks! However, I'm now running into a different issue while setting up DCM (on DevTools and on https://github.com/dart-lang/webdev/tree/master/dwds). I've filed https://github.com/dart-code-checker/dart-code-metrics/issues/1220, thanks!

**Comment by incendial** [comment]
> That should work for us, thanks! 

Happy to hear that! 🎉

> However, I'm now running into a different issue while setting up DCM

Sorry for inconvenience, in the latest release the underlying caching was refactored a bit too much, deleting `.dartServer/dart-code-metrics-teams/` should help. Won't happen again.
