### ISSUE TITLE
Flutter DevTools Performance Tab Frame Chart is not show up.

### ISSUE THREAD

**Issue by lgh001** [flutter/devtools#5642]
As title

When I use Flutter DevTools to check the performance of my app, I found that the Frame Chart is not displayed, which troubles me a lot.

Is there any wrong configuration that caused this issue, or is there any way to solve this problem?

As shown below：
![image](https://user-images.githubusercontent.com/15257811/231409650-8dd635a4-47b0-4a93-b1b5-489651660b86.png)

 flutter doctor   
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 13.2.1 22D68 darwin-arm, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.64.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

```
Flutter Plugins:
flutter.dev 73.0.1

**Comment by kenzieschmoll** [comment]
Looks like you are using an outdated version of Flutter. Can you switch to the latest flutter stable 3.7.11 and see if you are still experiencing this issue? You can run `flutter upgrade` to update your stable channel.

**Comment by lgh001** [comment]
> Looks like you are using an outdated version of Flutter. Can you switch to the latest flutter stable 3.7.11 and see if you are still experiencing this issue? You can run `flutter upgrade` to update your stable channel.

Oh~ thx, It can be displayed normally now, When I installed the Flutter SDK to the latest version.
