### ISSUE TITLE
In the response does not appear to the information

### ISSUE THREAD

**Issue by lucasbarretoluz** [flutter/devtools#5657]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Dart Version: 2.19.6
Flutter Version: 3.7.11 / stable
Framework / Engine: f72efea43c / 1a65d409c7
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
Are you talking about responses not showing up on the Network page? If so, this issue has been resolved. The solution is on the flutter beta or master channel, so if you can switch flutter channels, this should solve your problem. If you cannot switch, you may have to wait for the next Flutter stable release sometime next month. Please feel free to re-open this issue and add more details if this is not the issue you are referring to.
