### ISSUE TITLE
Integration tests are broken on the bots due to an old chromedriver version

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#5663]
Currently investigating and trying to find a solution: https://github.com/flutter/devtools/pull/5662

**Comment by kenzieschmoll** [comment]
this issue seems to have resolved itself. closing.

**Comment by elliette** [comment]
That sounds like we need to update the chromedriver version the bots are using. Do you know if the chromedriver version is determined by the flutter version, or are we downloading chromedriver as part of our bots workflow?

**Comment by kenzieschmoll** [comment]
I don't think we manually install it anywhere - @CoderDake do you know how the `chromedriver` executable is installed on our CI? AFAICT we just get it for free. Does this come out of the box with github actions?

**Comment by CoderDake** [comment]
@kenzieschmoll it looks like it comes built into the image from github:
https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md

This is what macos-latest is currently pointing at

**Comment by kenzieschmoll** [comment]
This is likely a dupe of https://github.com/flutter/flutter/issues/133617, but we can leave this issue open to track on our side

**Comment by archie934** [comment]
So the way I fixed it on windows(can be fixed similarly on other OS):

- Install an older version of chromium that is compatible with the chromedriver version [Chromium instructions](https://www.chromium.org/getting-involved/download-chromium/)
- Modify CHROME_EXECUTABLE variable to point to the chromium version
- In the flutter driver command add `--browser-name=chrome --chrome-binary=your/chromium/path`
