### ISSUE TITLE
The request and response panels in the devtools network panel of the Flutter desktop application (Windows, Mac OS) are both empty and nothing

### ISSUE THREAD

**Issue by luguicheng** [flutter/devtools#5668]
<-- Please describe your problem here. Be sure to include repro steps. -->

Problem: The request and response panels in the devtools network panel of the Flutter desktop application (Windows, Mac OS) are both empty and nothing. But the console can already print out the request result of dio.

Supplement: You can normally see response data in the response panel on Android and web; try to add the following configuration in "Project Name/macos/Runner/DebugProfile.entitlements" or it doesn't solve the problem

com.apple.security.network.client

![2023-04-18 22 02 51](https://user-images.githubusercontent.com/50764950/232802661-931d433e-8121-4496-984d-100c454b84cc.png)

___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: x64 (64 bit) macos
Dart Version: 2.19.6
Flutter Version: 3.7.11 / stable
Framework / Engine: f72efea43c / 1a65d409c7
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
This issue has been resolved in the latest version of DevTools. If you switch to the flutter beta or flutter master channel, you'll be able to get the fix. Please let us know if you are still seeing this on either of those flutter channels. Thanks!
