### ISSUE TITLE
Flame chart cursor position gets off when you scroll 

### ISSUE THREAD

**Issue by jakemac53** [flutter/devtools#5675]
When using the flame chart, if I scroll down then the cursor position becomes broken. It seems to not be taking into account the scroll position when determining the click position. So for instance below, I actually clicked where the red circle is, yet you can see it selected much higher up:

![image](https://user-images.githubusercontent.com/984921/233142753-c387735f-e16a-4655-80d5-81c0cc24e576.png)

**Comment by jakemac53** [comment]
Note that my Dart version is `Dart SDK version: 3.1.0-edge.cb4c9c74de5169a61febc94b0e8a5983791e826e`

**Comment by jacob314** [comment]
Fyi @kenzieschmoll

**Comment by jakemac53** [comment]
Thanks for the quick fix!
