### ISSUE TITLE
Devtools in Vscode does not highlight the overflow widget

### ISSUE THREAD

**Issue by ghost** [flutter/devtools#5685]
1. write any UI with a overflow widget, say a Text("")
2. run with DevTools open in vscode
3. the overflow-ing Text is not highlighted in VSCode DevTools
4. but if you open the devtool in browser, then both the devtools in browser & vscode will highlight it
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: x64 (64 bit) windows
Dart Version: 2.19.6
Flutter Version: 3.7.11 / stable
Framework / Engine: f72efea43c / 1a65d409c7
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
When you say "highlight it" do you mean in red showing the error?

**Comment by kenzieschmoll** [comment]
Thanks for the explanation. Can you reproduce this issue on the latest flutter stable? Looks like you are on an old version of DevTools.
