### ISSUE TITLE
Lost connection to device

### ISSUE THREAD

**Issue by banhcuonbathanh** [flutter/devtools#5686]
the real device Iphone was lost connection when I was trying to get information from dev tool. If i run in profile mode then connect to dev tool, I saw  Shader compilation jank, when I clicked at that shaded frame and check detail information in raster tab " Lost connection to device"  warning appear and I can not connection with dev tool. I already put the below infor :

	**
```

> <key>NSBonjourServices</key>
> 	<array>
> 		<string>_dartobservatory._tcp</string>
> 	</array>

```
**

to info.plist in folder runner of folder Ios, 
 internet connection is stable, i still can access internet.
on my real device on local net work, i already allow my application has right to access local net work 
on my mac location service allow for google chrome to access 
for proxy setting all are locked should I allow to open all 
as i check flutter doctor, every thing is good.
i run flutter clean already
___
**DevTools version**: 2.20.1

**Comment by banhcuonbathanh** [comment]
<img width="1306" alt="Screenshot 2023-04-20 at 09 11 30" src="https://user-images.githubusercontent.com/109460697
<img width="1305" alt="Screenshot 2023-04-20 at 09 11 54" src="https://user-images.githubusercontent.com/109460697/233240161-126d9a2c-99cd-4a1c-a8a5-09607d86a1f9.png">
/233240131-7b00c785-6209-403c-af2f-2b428ee1a0c9.png">
<img width="419" alt="Screenshot 2023-04-20 at 09 13 18" src="https://user-images.githubusercontent.com/109460697/233240171-d98ea570-d6bc-448c-8171-09a92e14c601.png">

**Comment by banhcuonbathanh** [comment]
![Screenshot 2023-04-20 at 09 21 25](https://user-images.githubusercontent.com/109460697/233241188-85e91af1-359a-4a1d-b056-d1b0c50ae0a4.png)

**Comment by kenzieschmoll** [comment]
This issue looks like it occurred on an old version of DevTools. Are you still experiencing this issue with DevTools on the latest Flutter stable? If so, please reopen and we will take a look. Thanks.
