### ISSUE TITLE
Empty widget tree in Flutter Inspector

### ISSUE THREAD

**Issue by ciurkoj** [flutter/devtools#5702]
I'm trying to debug an app that is entirely built and imported from packages. Everything else works just fine , breakpoints, overlay guidlines and the app responds to hot reload.  I tried invalidating cache, restarting the ide, but nothing helps.
Any ideas?

![image](https://user-images.githubusercontent.com/44451303/233945426-f5a2b314-8d91-4186-a44f-290f76912243.png)

PS C:\Program Files\Android\Android Studio> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel unknown, 3.7.5, on Microsoft Windows [Version 10.0.22621.1555], locale pl-PL)
    ! Flutter version 3.7.5 on channel unknown at C:\tools\flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Warning: `dart` on your path resolves to C:\tools\dart-sdk\bin\dart.exe, which is not inside your current Flutter SDK checkout at C:\tools\flutter. Consider adding
      C:\tools\flutter\bin to the front of your path.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.77.3)
[√] Connected device (4 available)
[√] HTTP Host Availability

___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: x64 (64 bit) android
Dart Version: 2.19.2
Flutter Version: 3.7.5 / unknown
Framework / Engine: c07f788888 / 0f359063c4
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
If you click on the settings button in the upper right corner of the inspector, this will allow you to add package directories to the inspector. These directories are how the inspector determines what widgets have been added by "your" code. By default, the package directories are set to the packages that are open in your IDE. Do you have more widgets defined in your project files than MyApp?

Can you add a screenshot of what the current state of the package directories setting looks like in the Inspector settings menu? Can you also add a screenshot of what the Widget Details Tree tab shows (next to the Layout Explorer)?

If you can share what the content of your Build method looks like for MyApp, that would also be helpful.

**Comment by ciurkoj** [comment]
@kenzieschmoll Thank you, it's working now!

**Comment by nmfisher** [comment]
> If you click on the settings button in the upper right corner of the inspector, this will allow you to add package directories to the inspector. These directories are how the inspector determines what widgets have been added by "your" code. By default, the package directories are set to the packages that are open in your IDE. Do you have more widgets defined in your project files than MyApp?
> 
> Can you add a screenshot of what the current state of the package directories setting looks like in the Inspector settings menu? Can you also add a screenshot of what the Widget Details Tree tab shows (next to the Layout Explorer)?
> 
> If you can share what the content of your Build method looks like for MyApp, that would also be helpful.

Can I suggest this be added to the Flutter Inspector documentation (https://docs.flutter.dev/tools/devtools/inspector)? I had to dig through quite a few GitHub issues to find this solution, it's not obvious at all that you need to do this if you're working with widgets imported from other packages.

**Comment by kenzieschmoll** [comment]
We have an open issue tracking the work for adding documentation for this feature to the flutter website: https://github.com/flutter/website/issues/9420. We plan to link to this from DevTools: https://github.com/flutter/devtools/issues/6425
@CoderDake

**Comment by nmfisher** [comment]
@kenzieschmoll  that's great, thanks.
