### ISSUE TITLE
devtools 0.0.16/ios flutter 1.5.5 timeline not working

### ISSUE THREAD

**Issue by tallinn1960** [flutter/devtools#571]
With the most recent devtools version and flutter 1.5.5 (Dart 2.3) timeline has stopped working in devtools with ios device running flutter app in profile mode. It still works in the same environment with an Android device. Edit: stopped working means that no frames are registered, timeline stays empty.

[✓] Flutter (Channel dev, v1.5.5, on Mac OS X 10.14.4 18E226, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.33.1)
[✓] Connected device (3 available)

Occasionally I find this line in the profile build output:

Launching lib/main.dart on iPhone in profile mode...
**[VERBOSE-2:FlutterObservatoryPublisher.mm(147)] Could not register as server for FlutterObservatoryPublisher. Check your network settings and relaunch the application.**
Automatically signing iOS for device deployment using specified development team in Xcode project: xxxxxx
Xcode build done.                                           14,2s

Trying to access the running profile app on ios with Observatory gives:

**missing or invalid authentication code**

in the browser window

Downgrading flutter to channel stable (v1.2.1/Dart 2.1.2) did not resolve the issue.

**Comment by kenzieschmoll** [comment]
Interesting. Can you confirm that the timeline is WAI for iOS debug, Android debug, and Android profile builds?

Have you used the DevTools timeline with an iOS profile build before?

**Comment by tallinn1960** [comment]
I do not understand, what WAI means. I just can say, that iOS profile and debug builds do not deliver frames to the timeline of devtools, Android does. The weird thing is, iOS does deliver frames to the Android Studio profile window (with, regarding Flutter, very satisfying results).

I once had a devtool version that run in Firefox and with that version frames where delivered by IOS to the timeline. At least with debug builds. I didn't test profile builds then. I was more in developing the app than testing its performance since then and only returned just recently to the timeline window and that's when I noticed that iOS no longer works with it.

The only other thing that changed and may be related to my issue is that I recently changed my iOS development team and got all new provisioning profiles for development and deployment.  Does an iOS app need a special entitlement for devtools timeline?

**Comment by kenzieschmoll** [comment]
WAI --> Working as intended 😊 

I don't think this issue should be related to your development team and provisioning profiles. I just tried an iOS profile build and the timeline worked fine. The timeline also is WAI with an iOS debug build on a simulator. What version of flutter are you on? Can you try upgrading and see it you can repro?

**Comment by tallinn1960** [comment]
I am on flutter 1.5.5, the dev channel.

I was able to narrow the problem down to my specific project at hand. The dummy app provided by flutter create -i swift ... does work with devtools timeline (as intended) on iOS simulator and device in all suitable modes. I did all the modifications to the project settings of the runner app in Xcode as I did for my project (like e.g. upgrading the workspace to Swift 5.0 and setting the deployment target to 12.2) but that did not break anything for the dummy app.

My project instead does not work with devtools timeline and now I am puzzled what to do next. Could one of the plugins I am using break devtools timeline? Here is the list of plugins, taken from the pubspec.yaml:

> intl: ^0.15.7
>   scoped_model: ^1.0.1
>   firebase_core: ^0.3.1+1
>   firebase_auth: ^0.8.3
>   firebase_database: ^2.0.2
>   firebase_storage: ^2.1.0+1
>   google_sign_in: ^4.0.1+1
>   google_maps_flutter: ^0.5.5
>   geolocator: ^4.0.0
>   image_picker: ^0.5.2
>   url_launcher: ^5.0.2
> 

In order to get google maps and geolocation to work I had to modify AppDelegate.swift (note that this is the Swift 5 version of AppDelegate, but as said I modified the dummy app to use the same version without breaking timeline for the dummy app):

```
import UIKit
import Flutter
import GoogleMaps

 @UIApplicationMain
 @objc class AppDelegate: FlutterAppDelegate {
   override func application(
     _ application: UIApplication,
     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
   ) -> Bool {
     GMSServices.provideAPIKey("...")
     GeneratedPluginRegistrant.register(with: self)
     return super.application(application, didFinishLaunchingWithOptions: launchOptions)
   }
 }
 
```

Now I am clueless.

**Comment by kenzieschmoll** [comment]
Ah I think I might know what is happening. For Google Maps, did you add the `io.flutter.embedded_views_preview` key to your `info.plist` file? This entry forces Flutter on iOS into a single threaded mode, which is required for the platform view embedding to work. This technical restriction is being worked on and will be lifted before Google Maps moves out of Developer Preview.

As of right now, the DevTools Timeline depends on having two different threads for UI and GPU events. My guess is that `io.flutter.embedded_views_preview` is forcing single threaded mode and therefore is breaking the timeline.

Once this technical restriction is lifted from the Google Maps plugin, the timeline should work fine. We also are working on a solution on the Flutter engine/DevTools side that should solve the problem.

**Comment by tallinn1960** [comment]
Sure, I did set that property as instructed. So that seems to be the issue. 

So, let's say the issue is resolved. As I am able to do some profile checking in Android Studio, I can live with that for now. Keep up the good work. Thank you.

**Comment by kenzieschmoll** [comment]
Sounds good. Keep an eye out for when the Google Maps plugin goes out of Developer Preview, as that will allow you to use the DevTools timeline. I'll update this issue if the fix on our end comes in before then. Thanks for the feedback - cheers!

**Comment by WATER1350** [comment]
@kenzieschmoll does io.flutter.embedded_views_preview flag affect the performance of flutter on ios?

**Comment by kenzieschmoll** [comment]
Yes, it does. The restriction for using this flag for the maps plugin on iOS is hopefully going to be going away soon.

**Comment by lwky** [comment]
thanks for the info, it would've been nice to have an error message in the developer console. We use webview_flutter, so embedded_views_preview is probably there to stay for us.
