### ISSUE TITLE
Set breakpoints via writing

### ISSUE THREAD

**Issue by elliette** [flutter/devtools#5712]
Broken out from https://github.com/flutter/devtools/issues/5703, find repro steps there

FR to be able to set breakpoints by writing (similar to how observatory worked)

FYI @bkonyi

**Comment by bkonyi** [comment]
I think we discussed this functionality before and decided we weren't going to port it cc @kenzieschmoll

**Comment by kenzieschmoll** [comment]
I agree this doesn't seem like high enough impact to migrate. We should make sure opening files and jumping to a line / searching for a function name is seamless, and then it will be easy to set breakpoints through the UI.
