### ISSUE TITLE
The responses are empty on this version for every request

### ISSUE THREAD

**Issue by AntonRobertVladPaul** [flutter/devtools#5725]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Dart Version: 2.19.4
Flutter Version: 3.7.7 / stable
Framework / Engine: 2ad6cd72c0 / 1837b5be5f
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
Looks like you are on an old version of DevTools. If you switch to Flutter beta or master channel, this issue will be resolved. There will be a new flutter stable released next month if you cannot switch to a different flutter channel.
