### ISSUE TITLE
Libraries Pane doesn't appear

### ISSUE THREAD

**Issue by brendantuckey** [flutter/devtools#5735]
<-- Please describe your problem here. Be sure to include repro steps. -->
When debugging a flutter web application the dart devtools debugger does not show the libraries pane so that I can choose my main.dart file to set debug breakpoints. I'm using latest macOS and builds running in Chrome (web) device.

repro steps:
In terminal ran: 
flutter pub global activate devtools

In VS Code:
Ran application in Chrome device

In terminal from within VS Code ran:
dart devtools

in Chrome browser entered connection number from debugging console page in 'Connect to running App':
ws://127.0.0.1:56767/8-blGaE5e38=/ws

In Flutter DevTools page:
Selected Debugger menu option.

No libraries pane visible.
Click gear (Settings) icon and get:
<img width="283" alt="Screenshot 2023-04-28 at 6 47 40 AM" src="https://user-images.githubusercontent.com/44008275/235147825-f5bd4561-1172-4892-a065-b51f1a3f381c.png">

No option to 'show libraries' or anything similar.

Hence I cannot set breakpoints for my app.

___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: Web macos
Dart Version: 2.19.6
Flutter Version: 3.7.12 / stable
Framework / Engine: 4d9e56e694 / 1a65d409c7
Connected app type: Flutter web (debug build)

**Comment by brendantuckey** [comment]
Here's my device info too...

<img width="503" alt="Screenshot 2023-04-28 at 7 36 35 AM" src="https://user-images.githubusercontent.com/44008275/235149346-f9715f01-49da-4453-90b7-893d4a2daea9.png">

**Comment by kenzieschmoll** [comment]
If you click the "folder" button in the top left of the debugger, this will open the file explorer:
![Screenshot 2023-05-01 at 10 40 53 AM](https://user-images.githubusercontent.com/43759233/235499536-52a92b9d-3152-409b-923d-34635bafc60c.png)

You can also use CMD + P to open the file search window, or click on the file name itself to open the file search window:
![Screenshot 2023-05-01 at 10 43 43 AM](https://user-images.githubusercontent.com/43759233/235499548-f5bb2a71-30af-4e36-ae9e-1defbf4e59fa.png)

Also just as an FYI, DevTools has not been shipped on pub for ~15 months now. DevTools is shipped with the Dart and Flutter SDKs so running `dart devtools` will launch the version of DevTools included with your dart sdk (the one at the path of `which dart` on your machine).
