### ISSUE TITLE
Cannot view response json api

### ISSUE THREAD

**Issue by phucpham-infinity** [flutter/devtools#5740]
Cannot view response json api in network tab.
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Dart Version: 2.19.6
Flutter Version: 3.7.10 / stable
Framework / Engine: 4b12645012 / ec975089ac
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
This is resolved in the latest version of DevTools. Please switch to the flutter beta or master channel to get the fix, or if you cannot switch branches, please wait for the flutter stable release that will be coming this month. Thanks!

**Comment by ppshobi** [comment]
https://github.com/flutter/devtools/issues/5740
