### ISSUE TITLE
How to deal with "empty" flame charts?

### ISSUE THREAD

**Issue by modulovalue** [flutter/devtools#5750]
Consider the following snippet of a flame chart from devtools:

<img width="745" alt="Bildschirm­foto 2023-05-04 um 01 19 33" src="https://user-images.githubusercontent.com/24444584/236072101-c255fa55-8b15-484b-ba13-f34d8daaf84e.png">

The whole `dfa_state_factory` takes 7 seconds, but the flame chart is only able to give me info about less than 2 seconds of what happened within `dfa_state_factory`.

I wanted to ask if there is a way to use devtools to help me find out how I can best optimize the other 5 seconds of `dfa_state_factory` that the flame chart in devtools provides no info about?

Or are there perhaps guidelines for how I should structure my code that would allow the Dart VM (and therefore devtools) to be more helpful here?

**Comment by kenzieschmoll** [comment]
Are there filters applied here to hide native code? You can click the filter button on the CPU profiler page to see what filters have been applied. If you uncheck all the filter options, that may reveal more information. You can also consider using UserTag's from dart:developer to split up different logical areas of your code and to narrow down where the bottleneck may be.

**Comment by kenzieschmoll** [comment]
Looking at the flame chart, it does appear that work is happening in the `dfa_state_factory<closure>`. You could try turning up the sampling rate (there is a drop down on the CPU profiler page and you can set it to high to sample once per 50 micros).

@bkonyi do you have any further ideas here?

**Comment by bkonyi** [comment]
If I had to guess, `dfa_state_factory<closure>` is doing work the entire remaining 5s. It's hard to say without knowing what the closure looks like though.
