### ISSUE TITLE
Devtools not connect to host

### ISSUE THREAD

**Issue by antogalli** [flutter/devtools#5753]
<-- Cant' connect to host. -->
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: ia32 (32 bit) android
Dart Version: 2.19.6
Flutter Version: 3.7.12 / stable
Framework / Engine: 4d9e56e694 / 1a65d409c7
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
@antogalli could you please provide some more information about how to reproduce this?
