### ISSUE TITLE
unable to view widgets 

### ISSUE THREAD

**Issue by XERZES27** [flutter/devtools#5758]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Dart Version: 2.19.4
Flutter Version: 3.7.7 / stable
Framework / Engine: 2ad6cd72c0 / 1837b5be5f
![image](https://user-images.githubusercontent.com/39665735/236641608-567d3f2d-e729-4fe6-8bb5-d825f9a65720.png)

Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
@CoderDake Here's an example of where it would be nice to have some analytics sent when an inspector is loaded with 0 widgets in the summary tree.

**Comment by XERZES27** [comment]
fixed in 3.10
