### ISSUE TITLE
Focus and hover for the devtools buttons look too similar in dark mode

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#576]
@timsneath noted the Dark theme is looking much better butr that it is a bit hard to tell selected from hovered buttons.
I would suggest we keep the selected button color as is but make the hover color less noticeable.
In addition, we need a different over color for selected and deselected.

Fyi @DanTup

**Comment by DanTup** [comment]
I spent some time trying to come up with/tweak colours, but my design skills are somewhat lacking (and there weren't many colours in the spec to copy from). It would be good to have someone elses input on the colours that might do a better job :-)

**Comment by kenzieschmoll** [comment]
Dark buttons
<img width="117" alt="Screen Shot 2019-04-25 at 7 41 42 AM" src="https://user-images.githubusercontent.com/43759233/56744603-ade27700-672d-11e9-86bb-3f56b7399b60.png">
background-regular: #1f2023
background-hover: #24262b
border-regular: 1px solid #5f6368
border-hover: 1px solid rgba(138,180,248,.24)
text-color: #8ab4f8

Blue buttons
<img width="114" alt="Screen Shot 2019-04-25 at 7 41 47 AM" src="https://user-images.githubusercontent.com/43759233/56744974-52fd4f80-672e-11e9-9043-d62a833949ef.png">
background-regular: #8ab4f8
background-hover: #81a9e7
text-color: #202124

Disabled button
<img width="119" alt="Screen Shot 2019-04-25 at 7 53 16 AM" src="https://user-images.githubusercontent.com/43759233/56745438-357cb580-672f-11e9-91f4-f0a8d916f7d4.png">
background: #1f2023
border: 1px solid #3c4043
text-color: rgba(255,255,255,.47)

Unfortunately I couldn't find a great example of a button in a permanently selected state, like ours can be. Maybe we could do something like this where all non selected buttons have the grayed out text/icons, and then when they are selected the text/icon would be the material blue color
<img width="346" alt="Screen Shot 2019-04-25 at 7 55 54 AM" src="https://user-images.githubusercontent.com/43759233/56745687-ac19b300-672f-11e9-96cf-c4c144ded420.png">

**Comment by DanTup** [comment]
Yeah, these look like the colours I had from the doc, but we have many more states than they cover (enabled+disabled, pressed+not pressed, hover+not hover and most of the combinations of those). I previously tried just using the same colours for some (eg. making all hover colours the same), but that feels weird when you use it (eg. if you hover a toggle button and then press it, if the hover state is the same, there's no visual feedback - so each combination needs its own colour).

**Comment by jacob314** [comment]
Hover is a nice to have feature. Clarity about which buttons are selected and which aren't is a must have feature. Given this I would be content to sacrifice hover completely if selection was clearer. 
I think there is a middle ground where we still slightly tweak the color on hover but still keep the selected colors very different from the deselected colors.

**Comment by DanTup** [comment]
We discussed this today and agreed to leave this as-is for now, as we'll probably change these buttons to be more Flutter/material-like soon as we can move more over to Flutter for web.
