### ISSUE TITLE
Enabling more DCM rules

### ISSUE THREAD

**Issue by incendial** [flutter/devtools#5762]
Hey, if I'm not mistaken the current set of DCM rules was picked even before the Teams version was released.
But there are actually around 140 rules now.

So, do you want to enable more? Let me know if you need my help with this and feel free to close if you're fine with the current set of rules in use.

**Comment by kenzieschmoll** [comment]
The current set of rules is sufficient for now, and if we want new rules, we can adopt them as needed. Thanks.
