### ISSUE TITLE
Widget tree not display: have a root folder in display

### ISSUE THREAD

**Issue by MayuriXx** [flutter/devtools#5773]
Widget tree not display: have a root folder in display

<img width="358" alt="Capture d’écran 2023-05-11 à 10 58 07" src="https://github.com/flutter/devtools/assets/26456981/6571f2d0-9ac9-4e84-9fd4-115c232c3880">

___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: Web macos
Dart Version: 2.18.6
Flutter Version: 3.3.10 / stable
Framework / Engine: 135454af32 / 3316dd8728
Connected app type: Flutter web (debug build)

**Comment by kenzieschmoll** [comment]
Looks like you are on a very old version of Flutter. Can you upgrade to the latest flutter stable to see if you can reproduce there? The DevTools version on the latest flutter stable is 2.23.1

**Comment by debuggerx01** [comment]
The same problem, upgrade Flutter can solve, but unfortunately, I am working for a business project, I have to use the old version.
