### ISSUE TITLE
Daily Dev Bump broken due to autosubmit issue

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#5777]
The release notes not required label ensures the release notes check is skipped for the automatic version bump action. Due to a bug with the autosubmit label (https://github.com/flutter/flutter/issues/125826), the skip is registered as a failure instead of a pass. The daily dev bump PRs will have to be merged manually until this issue is resolved.
CC @ricardoamador

**Comment by ricardoamador** [comment]
@kenzieschmoll I had looked into this last week and this is something GitHub does in the background. We are reading the statuses they set so we need to find a way to work around this. Can you link that specific PR with the failure here please?

**Comment by kenzieschmoll** [comment]
@ricardoamador does the PR I linked give you the information you need? Or do you need an open PR?

**Comment by ricardoamador** [comment]
Thank you! Taking a look.

**Comment by kenzieschmoll** [comment]
@ricardoamador thanks for digging into this. @CoderDake can you take a look at Ricardo's suggestions?

**Comment by CoderDake** [comment]
I will take a look :)

**Comment by CoderDake** [comment]
It looks like the labels really have a hard time resolving in a way that is helpful for the workflows.

I found a reasonable way to approach the problem by just making an exception for the Author of the PR instead. If it is our workflow bot, then we know we don't care about release notes, and we want to run DCM.

https://github.com/flutter/devtools/pull/5811

Let me know what you think :)

**Comment by ricardoamador** [comment]
Quick question: is the change here just not to run the release notes check?

**Comment by CoderDake** [comment]
Yes, since this is just a version bump, we don't need to add release notes. So we don't need to run the check.

It also changes the DCM workflow to always run for the DartDevtoolsWorkflowBot (Which is responsible for pushing up the version bump PRs)

**Comment by ricardoamador** [comment]
Ah okay. Thanks for clarifying.
