### ISSUE TITLE
Request and Response not showing please fixed it. I need it.

### ISSUE THREAD

**Issue by Sardor-art** [flutter/devtools#5780]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: x64 (64 bit) ios
Dart Version: 2.19.4
Flutter Version: 3.7.7 / stable
Framework / Engine: 2ad6cd72c0 / 1837b5be5f
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
Hey @Sardor-art can you please try running `flutter upgrade` to upgrade your flutter to the most recent stable version?

Some fixes for the network tab have already been posted in `DevTools 2.22.1`, so these may resolve your issues :)
