### ISSUE TITLE
launchDevTools should use ChromeOS native browser

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#582]
Currently the `launchDevTools` command will try to launch Chrome-for-Linux on ChromeOS. I believe it needs to launch the default browser in that case.

I don't know if this is the best way, but I think it needs to do something like this:

```
final isCrOS = Platform.isLinux && File('/dev/.cros_milestone').existsSync();
if (isCrOS) {
  Process.start('x-www-browser', ['https://www.google.co.uk/']);
} else {
  // Current way
  Process.start(_executable, [
    'https://www.google.co.uk/', /* + Chrome flags? */
  ]);
}
```

@jacob314 can you confirm this sounds right? Webdev is doing is own launching, and will require Chrome for Linux (because it needs to pass flags), but for non-Webdev we expect to always use the native browser?

**Comment by DanTup** [comment]
Wait, this gets more complicated... I think it needs to spawn the default browser a) when on ChromeOS and b) both the port it's listening on and the port of the VM service it's launching are known tunnelled ports. Since for Web we'll need to spawn Chrome-for-Linux still?

**Comment by jacob314** [comment]
Yes it would make sense to add custom logic to use chrome-for-linux if either of the ports are outside of the list of tunnelled ports. We should add a TODO to remove the logic once CROS supports more ports.
