### ISSUE TITLE
Cannot activate devtools from pub using dart 3.0.1

### ISSUE THREAD

**Issue by Pacane** [flutter/devtools#5823]
I'm currently using Dart 3.0.1 and I'm trying to pub global active devtools. I'm using asdf to manage my dart/flutter versions, but I don't think it should matter. Here are my logs:

```
λ ~/job/platform/dart/apps/admin/ main* dart pub global activate devtools
The current Dart SDK version is 3.0.1.

Because pub global activate depends on devtools any which doesn't support null safety, version solving failed.

The lower bound of "sdk: '>=2.1.0-dev <3.0.0'" must be 2.12.0 or higher to enable null safety.
For details, see https://dart.dev/null-safety
λ ~/job/platform/dart/apps/admin/ main* dart --version
Dart SDK version: 3.0.1 (stable) (Tue May 16 11:57:19 2023 +0000) on "macos_x64"
λ ~/job/platform/dart/apps/admin/ main* which dart
/Users/joel/.asdf/shims/dart
λ ~/job/platform/dart/apps/admin/ main* flutter --version
Flutter 3.10.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d3d8effc68 (25 hours ago) • 2023-05-16 17:59:05 -0700
Engine • revision b4fb11214d
Tools • Dart 3.0.1 • DevTools 2.23.1
λ ~/job/platform/dart/apps/admin/ main* which flutter
/Users/joel/.asdf/shims/flutter
λ ~/job/platform/dart/apps/admin/ main* 
```

**Comment by kenzieschmoll** [comment]
DevTools is no longer shipped on pub: https://pub.dev/packages/devtools/versions. Instead it is included with your Dart or Flutter SDK. When you run your flutter or dart app, a link to DevTools will either be printed to command line or DevTools will be available to launch from your IDE. You can also run `dart devtools` to launch devtools in a standalone process. Running `flutter --version` will print which version of DevTools is included with your flutter sdk.
