### ISSUE TITLE
How to view exported CPU profiling results in Flutter Devtools?

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/devtools#5849]
(Copied from https://github.com/flutter/flutter/issues/127639 as is suggested by @huycozy )

Hi, I am looking at the CPU profiling results in Flutter devtools. The GUI is super janky, so I want to export it and view externally, just like how we view timelines with Perfetto or chrome://tracing. There does exist an "Export" button, but I am not sure what is the format of the exported data. It looks like plain JSON, and I have tried flamegraph tools without success (surely). The doc https://docs.flutter.dev/tools/devtools/cpu-profiler also does not mention how to use the exported data. A quick google search and Discord search also do not reveal answers.

I am worried this is just an ad-hoc format and no viewers at all support it, that's why I create this issue. Is there anyone who uses export button in the profiling - I wonder what (external) viewer do you usually use?

I am happy to PR for doc once I know how can I use the exported data!

![image](https://github.com/flutter/flutter/assets/5236035/de58169a-3d39-4c08-a6d3-96c5a7ad5f96)

**Comment by kenzieschmoll** [comment]
This exported data is intended to be imported back into DevTools. The json is generated here: https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/screens/profiler/cpu_profile_model.dart#L747.

What viewers / expected formats were you hoping you could use?

**Comment by fzyzcjy** [comment]
> This exported data is intended to be imported back into DevTools.

I see. Thanks!

> What viewers / expected formats were you hoping you could use?

Anyone that is not super janky. Btw do you feel the devtool profiling page super janky?

**Comment by kenzieschmoll** [comment]
The flame chart view in your screenshot does have some known performance issues. The tables, however, should be performant. What version of DevTools are you using? Are you noticing performance problems in just the flame chart or in all of the profiler views (call tree, bottom up, etc.)?

There were some performance improvements to the tables that did not make it in the last release. There is a DevTools release going into flutter master this week, so if those weren't available in the version you are on, they should be available on Flutter master soon.

**Comment by fzyzcjy** [comment]
> The flame chart view in your screenshot does have some known performance issues. The tables, however, should be performant.
There were some performance improvements to the tables that did not make it in the last release. There is a DevTools release going into flutter master this week, so if those weren't available in the version you are on, they should be available on Flutter master soon.

Thanks, but I do hope to use flamechart - which is so commonly used! Tables are good but framecharts are non-replaceable ;)

> What version of DevTools are you using? Are you noticing performance problems in just the flame chart or in all of the profiler views (call tree, bottom up, etc.)?

IIRC flame chart mostly (I used it at the time of creating this issue, so cannot remember exactly).
