### ISSUE TITLE
Allow filtering profile samples based on named intervals and function names

### ISSUE THREAD

**Issue by yjbanov** [flutter/devtools#585]
One thing that I find myself wanting to do frequently but can't in Chrome's Timeline is to filter out profile samples based on some timeline interval name or function name.

Consider one Flutter frame. In it you would `Build`, `Layout`, `Paint`, `flushSemantics`, `compositeFrame`, etc. Now imagine you have a timeline that recorded 100 frames and you are interested in knowing what's going on inside `flushSemantics`. The tool should allow you to select a time range that includes several frames, but then in addition to that, it should allow you focus on `flushSemantics` only by including only the profile samples that fall into `flushSemantics`. This would tell you what's going on inside `flushSemantics` so you can optimize it. Without this feature a given time range would include stuff that has nothing to do with `flushSemantics` thus obfuscating useful signal.

The profiler should support the following filters:

- Function/method name
- Named timeline marks, such as [startSync](https://docs.flutter.io/flutter/dart-developer/Timeline/startSync.html), [timeSync](https://docs.flutter.io/flutter/dart-developer/Timeline/timeSync.html)

**Comment by jacob314** [comment]
@kenzieschmoll this is an interesting way to provide higher resolution sampling data for problems where there isn't just one slow frame but a general feeling an operation is slower than it could be.

We could promote this option to users if we identify that multiple frames are missing the target instead of just a single really bad frame.

**Comment by kenzieschmoll** [comment]
We could start by allowing filtering with the current CPU profiler flame chart. This same filtering would ideally trickle over into the Bottom Up and Call Tree view. It's also seeming like having the ability to view multiple frames at a time is becoming increasingly important.

Here are the two action items I see here:
1) support a multi-frame flame chart / cpu profiler
2) add the ability to filter the cpu profile

**Comment by kenzieschmoll** [comment]
This request is possible through a combination of the Perfetto timeline and using UserTags in the CPU profiler
