### ISSUE TITLE
Support eval-and-browse on web platform

### ISSUE THREAD

**Issue by annagrin** [flutter/devtools#5874]
Currently eval-and-browse feature (https://github.com/flutter/devtools/issues/4962) is not fully supported on web platform due to dwds API limitations (not allowing scope in `VmServiceInterface.evaluateInFrame`)

Work to allow scope passing is in progress in dwds: https://github.com/dart-lang/webdev/pull/2122

After the work is done and a new dwds version is released, we need to remove the following check from DevTools: https://github.com/flutter/devtools/blob/260c266576eb7bb1b39ff2df026bd3ac85a7efe6/packages/devtools_app/lib/src/shared/console/eval/eval_service.dart#L190

**Comment by annagrin** [comment]
Update: dwds work is done in https://github.com/dart-lang/webdev/pull/2122

Should be included in dwds version 19.0.1 (to be released)

**Comment by elliette** [comment]
Ideally when we enable this for web it would be good to have a test to catch any regressions. The `eval_and_browse_test` currently cannot be enabled for web, because it is using the memory panel which is not supported for web devices: https://github.com/flutter/devtools/blob/2a106f3bda53d6925a55599060a4cd7b29933229/packages/devtools_app/integration_test/test_infra/run/_test_app_driver.dart#L428

**Comment by polina-c** [comment]
I think you need to create different test like 'eval_web_test'. You can start with copying `eval_and_browse_test`.
The test first checks basic console functionality and then switches to memory screen.
So, you need to remove the second part and configure the bot to test the feature for web, not for headless.

Makes sense?

**Comment by polina-c** [comment]
It will be just `eval`. `browse` part will not be available for web, because there is no VM, that is needed for this.

**Comment by elliette** [comment]
@polina-c Would you be willing to add the test? I don't have much context on this feature since I didn't write it. Thanks!

**Comment by annagrin** [comment]
We need to enable this for our customers, I'll give it a try.
