### ISSUE TITLE
Ability to Copy text from Network Screen

### ISSUE THREAD

**Issue by nmagathan** [flutter/devtools#5910]
There are times where i would like to be able to either copy the network request, or the response. Currently, that is not possible in either the Browser version or the VSCode extension

**Comment by kenzieschmoll** [comment]
@CoderDake

**Comment by CoderDake** [comment]
We are currently exploring a larger issue where it seems that VSCode is blocking the copy.
The progress on this task will be tracked on https://github.com/flutter/devtools/issues/5775

The bug we filed with VSCode can be seen on https://github.com/microsoft/vscode/issues/182642
