### ISSUE TITLE
Unable to preview layout

### ISSUE THREAD

**Issue by zhaobinsir** [flutter/devtools#5920]
<-- Please describe your problem here. Be sure to include repro steps. -->
Can't find the preview interface of Flutter in Android studio? How can I enable the preview interface?
___
**DevTools version**: 2.23.1
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Dart Version: 3.0.3
Flutter Version: 3.10.4 / stable
Framework / Engine: 682aa387cf / 2a3401c9bb
Connected app type: Flutter web (debug build)

**Comment by CoderDake** [comment]
Hi @zhaobinsir, [here is some documentation about how to open up different views in android studio](https://docs.flutter.dev/tools/devtools/android-studio#launch-devtools-from-the-toolbarmenu)

I'm not sure there is a preview interface though. It sounds like you want to preview what your app would look like, but I don't think that is supported.
