### ISSUE TITLE
My expense app

### ISSUE THREAD

**Issue by Sam-diom** [flutter/devtools#5927]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.23.1
**Connected Device**:
CPU / OS: x64 (64 bit) ios
Dart Version: 3.0.3
Flutter Version: 3.10.4 / stable
Framework / Engine: 682aa387cf / 2a3401c9bb
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
Hey @Sam-diom could you please provide some information about what issue you are seeing?
