### ISSUE TITLE
flutter 3.10.4 版本 DevTools 2.23.1版本，看不到network中的response返回（flutter version 3.10.4 DevTools version 2.23.1, can't see the response return in network）

### ISSUE THREAD

**Issue by cheny-github** [flutter/devtools#5930]
![image](https://github.com/flutter/devtools/assets/25857441/57bffa3e-4779-47a9-8991-ec724b727799)

flutter --version
Flutter 3.10.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 682aa387cf (2 weeks ago) • 2023-06-05 18:04:56 -0500
Engine • revision 2a3401c9bb
Tools • Dart 3.0.3 • DevTools 2.23.1

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.4 22F66 darwin-arm64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
✗ cmdline-tools component is missing
Run path/to/sdkmanager --install "cmdline-tools;latest"
See https://developer.android.com/studio/command-line for more details.
✗ Android license status unknown.
Run flutter doctor --android-licenses to accept the SDK licenses.
See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] Network resources

I upgraded my flutter version, but I can't see the response return in DevTools, what should I do?

你好，我升级了我的flutter版本，但我在DevTools中看不到响应返回，我应该怎么做？

**Comment by kenzieschmoll** [comment]
How are you launching DevTools? the flutter --version output says DevTools 2.23.1 but the screenshot looks like an older version of DevTools. DevTools 2.23.1 had a large design update to material 3 that your screenshot does not reflect, so I wonder if you seeing a stale version of DevTools somehow.

**Comment by cheny-github** [comment]
As much as I would like to continue working on this issue, we decided to stay with version 3.3.0 due to the above unresolved issues. The way it works above is that I opened opend devtooles in vscode directly in webbrowser

**Comment by CoderDake** [comment]
@cheny-github to check which version you are opening could you please click on the `?` at the bottow right of the network inspector. Then report back with what version you are using. (see image below)

Something tells me that VSCode's version of flutter is different from the one in your console. If that ends up being the case then you can change the version of flutter that you point to using the following instructions: https://stackoverflow.com/a/71196455

<img width="1010" alt="Screenshot 2023-07-04 at 9 54 36 AM" src="https://github.com/flutter/devtools/assets/1386322/e2d42139-9143-4f0c-8c41-4ed9570142f7">

**Comment by ccforeverd** [comment]
Same issue

<img width="1354" alt="image" src="https://github.com/flutter/devtools/assets/7246675/b4924052-bb76-45d0-82bc-66cb55b82ffe">
<img width="1346" alt="image" src="https://github.com/flutter/devtools/assets/7246675/dc0b2401-01a2-4736-b637-3f00436ad057">

@CoderDake

**Comment by CoderDake** [comment]
@ccforeverd a lot of Network tab fixes were added in Devtools 2.23.0.
In order to get access to those fixes you will need to update your Flutter version to at least `Flutter 3.10.0`.

**Comment by CoderDake** [comment]
Closing since [cheny-github](https://github.com/cheny-github) mentioned that they are just going to stay on flutter 3.3.0
