### ISSUE TITLE
Widget inspection Magnifying glass experience broken in Multi View app

### ISSUE THREAD

**Issue by CoderDake** [flutter/devtools#5931]
Magnifying glasses should be showing up on each seperate view when in Widget Inspection mode on a Multi View app

**Comment by CoderDake** [comment]
It looks like the magnifying glass and inspection works on some multi view but not others.
For the https://github.com/goderbauer/mvp repo, 
- `widgets_counter.dart` example works with widget inspection
- `widgets_static.dart` **DOES NOT** work with widget inspection
- `widgets_dynamic.dart` **DOES NOT** work with widget inspection

**Comment by goderbauer** [comment]
`widgets_static.dart` and `widgets_dynamic.dart` do not use a MaterialApp/CupertinoApp/WidgetsApp widget. That's the widget that inserts the `WidgetInspector` widget in the tree [1]. So, it is expected that these don't support widget inspecting (these examples also wouldn't support inspecting if they were just single view).

`widgets_counter.dart` is the more interesting one. It currently uses multiple MaterialApp/CupertinoApp/WidgetsApp widgets (one for each view), so there will be multiple `WidgetInspector` widgets as well. I am not sure if the `WidgetInspector` widget was designed for this. That'd be something to audit.

[1] https://github.com/flutter/flutter/blob/6ae22ef4e9f7ef1e26c248d23338f38c26bde25d/packages/flutter/lib/src/widgets/app.dart#L1705

**Comment by CoderDake** [comment]
Note: in the app that does work the state of the magnifying glasses is a bit confusing. The states between windows could be unified.
