### ISSUE TITLE
Widget Inspector Selection broken in Multi View App

### ISSUE THREAD

**Issue by CoderDake** [flutter/devtools#5932]
When Widget selection mode is turned on in Devtools, I am unable to click in a view to inspect an element.

**Comment by CoderDake** [comment]
It looks like the magnifying glass and inspection works on some multi view but not others.
For the https://github.com/goderbauer/mvp repo, 
- `widgets_counter.dart` example works with widget inspection
- `widgets_static.dart` **DOES NOT** work with widget inspection
- `widgets_dynamic.dart` **DOES NOT** work with widget inspection

**Comment by CoderDake** [comment]
for the `widgets_counter.dart` example, nothing is highlighted when clicking on:
- [root]
- MultiViewApp
- ViewCollection
- View
- Builder
- Counter
- MaterialApp

**Comment by goderbauer** [comment]
For `widgets_static.dart` and `widgets_dynamic.dart` it is likely expected that widget inspecting doesn't work, see https://github.com/flutter/devtools/issues/5931#issuecomment-1599290232

It should work for `widgets_counter.dart`, though. The `WidgetInspector` widget that powers this likely needs to e updated to deal with being in the tree multiple times?

**Comment by CoderDake** [comment]
Fixed in https://github.com/flutter/flutter/pull/129452/files#diff-f3f2945fbb3193cf8c53a711a4192a1ea75cea729c4316c7b3f9ae701c4bc079R3240
