### ISSUE TITLE
Unable to connect to VM service at https... WebSocket connection failed

### ISSUE THREAD

**Issue by intfract** [flutter/devtools#5948]
Flutter DevTools won't work after `flutter run` and `2` for chrome. I can't connect to my flutter app. 
- [Gitpod](https://gitpod.io) 
- Brave Browser 

Manually connecting doesn't work either. 
![image](https://github.com/flutter/devtools/assets/110207136/f61fa9d0-9121-42f9-a79c-c52550532b24)

**Comment by CoderDake** [comment]
Hey @intfract  I've tried to reproduce but it seems to work fine for me.
Can you please give more detail about how you are running your app, and how you are trying to connect to it?
Could you also please post the results of running `flutter doctor`?

**Comment by intfract** [comment]
# Issue
Sure, thanks for the reply. I am currently relying on Gitpod's slow linux noVNC because I can't use flutter devtools. It would be nice to get this working.

## Flutter Doctor
The `flutter doctor` command only found 1 issue because I don't have android studio installed (not possible on Gitpod). 
![image](https://github.com/flutter/devtools/assets/110207136/adc63f12-7fb4-48b5-b5e2-9971e534022d)

## Source Code
If it helps, the source code can be found at [this](https://github.com/intfract/flutter) repo. I've checked my dart extension and it looks fine. However, my `gitpod.yml` and `analysis_options.yaml` both have 1 warning. 

### Gitpod Config
```
dart-code.dart-code extension is not synced, but not added in .gitpod.yml
```

### Analysis Options
```
The include file 'package:lints/recommended.yaml' in '/home/gitpod/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_lints-2.0.1/lib/flutter.yaml' can't be found when analyzing '/workspace/flutter'.
```

**Comment by polina-c** [comment]
Thanks. For app started with `flutter run` the options to starte DevTools are:

1. Click DevTools URL in the output of `flutter run`:
<img width="808" alt="Screenshot 2023-07-03 at 10 05 52 AM" src="https://github.com/flutter/devtools/assets/12115586/410cf4a7-2535-4152-8d44-2116098ce4cb">
If you use this way, DevTools should be already connected to the app. 

2. Run `dart devtools`, copy VM Service URL to the textbox, and click 'Connect' 
<img width="965" alt="Screenshot 2023-07-03 at 10 08 55 AM" src="https://github.com/flutter/devtools/assets/12115586/725cf5da-036d-44e4-a490-70c02439f3cf">

Can you try both ways and check if there is error in console?

May I also ask you to experiment with latest DevTools, and, if it fails, provide the error details in console: https://github.com/flutter/devtools/blob/master/BETA_TESTING.md

**Comment by intfract** [comment]
## DevTools
I just get a blank page after running `flutter run` and selecting `2` for chrome. I clicked the link and waited for some time. The brave browser console (not linux terminal) showed some errors along with a **Disconnected** message.

```
main.dart.js:15698 WebSocket connection to 'ws://127.0.0.1:37565/nwxpJ58sXt8=/ws' failed:
WebSocketChannelException: WebSocket connection failed.
GET https://docs.flutter.dev/tools/devtools/release-notes/release-notes-2.12.2-src.md
```

I get a blank page again if I type `dart devtools` in the terminal. 

![image](https://github.com/flutter/devtools/assets/110207136/f0508025-05ad-42d6-bd34-d69c70dc0450)

It just says that I can't connect to the flutter VM service. 

## Other Info
Gitpod is a **linux** VM. This might be a problem because apparently kubernetes doesn't support VM nesting.

**Comment by polina-c** [comment]
It seems release notes for 2.12.2 are missing: https://docs.flutter.dev/tools/devtools/release-notes/release-notes-2.12.2-src.md

It was cherrypick: https://github.com/flutter/devtools/pull/3961

**Comment by polina-c** [comment]
Preparing fix.

**Comment by polina-c** [comment]
Fix: https://github.com/flutter/website/pull/8977

**Comment by intfract** [comment]
Do I have to update flutter devtools or has nothing changed?

**Comment by CoderDake** [comment]
https://docs.flutter.dev/tools/devtools/release-notes/release-notes-2.12.2-src.md now has the release notes posted to it, thanks for Polina's fix.
@intfract I think that you should be able to give it a whirl without any extra effort on your part.

**Comment by kenzieschmoll** [comment]
The failure to load release notes should not block connection. The failure to connect to the vm service is a separate and independent issue.

**Comment by kenzieschmoll** [comment]
Please leave this issue open - the release notes fix did not solve the issue. The failure to connect is a separate error that we need to investigate and solve.

**Comment by bernaferrari** [comment]
Sorry, I have no idea what happened. Apparently I forked flutter website and it affected this somehow. Crazy!
