### ISSUE TITLE
Highlight currently selected widget in Debug Paint mode

### ISSUE THREAD

**Issue by andriy-gul** [flutter/devtools#598]
Flutter dev tools would be more helpful if it additionally highlights currently selected widget in widgets tree in the Debug Paint mode.

**Comment by adolfdsilva** [comment]
This should be a basic feature.

**Comment by fogelfish** [comment]
This is probably an obvious thing to say but especially in complex and crowded layouts it would greatly assist the design process to visually cue which widget is selected in the Flutter Inspector.

**Comment by Tasen-pro** [comment]
+1

**Comment by kenzieschmoll** [comment]
This is supported. When select widget mode is enabled
![Screenshot 2024-10-24 at 1 26 26 PM](https://github.com/user-attachments/assets/e7e229a3-b48e-49e6-9ba1-e476f4181c40)

 (which enables the on-device widget inspector)
![Screenshot 2024-10-24 at 1 26 16 PM](https://github.com/user-attachments/assets/717b3098-fe96-4deb-818d-3e8755b12b57)

you can select widgets in your application, and the selected widget will be highlighted and automatically scrolled to in the Inspector.
