### ISSUE TITLE
Missing release notes should not kill flutter stable.

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#5983]
DevTools should be more resilient to missing release notes: https://github.com/flutter/devtools/issues/5948

Release notes can be missing because of two reasons:
1. They do not exist on website
2. Internet connection is poor

So, we need to:
1. Convert failure to warning if release notes cannot be loaded
2. Add testing to make bots detecting missing release notes. For this we need to update release instructions to begin release process with release notes.

**Comment by polina-c** [comment]
@kenzieschmoll @CoderDake , thoughts?

**Comment by CoderDake** [comment]
I agree that Devtools should still function regardless of whether Release Notes are able to load. A warning sounds like a good idea. I can imagine we might want to make sure the failure is reported to the analytics as well so we can track that it is happening. I think @kenzieschmoll could comment more on that aspect though.

**Comment by kenzieschmoll** [comment]
We already fail gracefully when release notes cannot be found: https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/framework/release_notes/release_notes.dart#L133-L137.

I don't thing we need to warn the user explicitly - we log warnings in the Chrome dev console if we can't find any release notes. There is no need to make the user think something is wrong when nothing is functionally wrong with DevTools. 

> Add testing to make bots detecting missing release notes. For this we need to update release instructions to begin release process with release notes.

I'm not sure it makes sense to publish release notes for a DevTools version before it is actually available in the Dart SDK. If something were to go wrong with the release that delayed getting it out the door, it would be a bit odd to publish release notes for a non existent DevTools version (that may or may not change - for example if something went wrong and we need to do another patch bump).

**Comment by kenzieschmoll** [comment]
Closing this, as I don't think there is a bug here.
