### ISSUE TITLE
Doctor App

### ISSUE THREAD

**Issue by Mahmudul-Hasan00071** [flutter/devtools#6035]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.23.1
**Connected Device**:
CPU / OS: x64 (64 bit) android
Dart Version: 3.0.0-417.4.beta
Flutter Version: 3.10.0-1.5.pre / beta
Framework / Engine: b1c77b7ed3 / 50e509c2bd
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
Without further information, we will not be able to fix this issue. Feel free to reopen if you can provide a description of the issue you were seeing. Thank you.
