### ISSUE TITLE
response page not showing please check issue

### ISSUE THREAD

**Issue by abdulazeez-picco** [flutter/devtools#6073]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Dart Version: 2.19.6
Flutter Version: 3.7.12 / stable
Framework / Engine: 4d9e56e694 / 1a65d409c7
Connected app type: Flutter native (debug build)
response page not showing please check issue

**Comment by CoderDake** [comment]
@abdulazeez-picco we have some fixes for this that are present in Devtools 2.23.0.

To get access to these fixes you will need to update your flutter version to at least `Flutter 3.10.0`
