### ISSUE TITLE
Select / copy bugs in the debugger

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#6079]
1) highlight something in the code view, then go to an element in the console view and highlight something there
expected behavior: highlighted content in the code view should be released from focus, and I should only see text selected in the console view

2) selecting text in the console and right clicking sometimes removes the selection
![selection-removed](https://github.com/flutter/devtools/assets/43759233/89e4dea6-cf78-44b4-b5f5-afefbdfa5c7d)

3) cmd + c does not copy content to the clipboard, even though right click + copy does. This reproduces in both the code view and the console

**Comment by elliette** [comment]
I can only reproduce issue #3 in the console, it works for me in the codeview area

**Comment by elliette** [comment]
Fixed in https://github.com/flutter/devtools/pull/6099
