### ISSUE TITLE
Console text is cut off

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#6080]
copy a large string of text and paste it into the eval console:
<img width="527" alt="Screenshot 2023-07-21 at 11 07 22 AM" src="https://github.com/flutter/devtools/assets/43759233/e5a63493-18ed-436d-9ad7-22e20e29ee24">

**Comment by elliette** [comment]
Note: this is not a new regression with our latest release, I'm able to reproduce this on 2.23.1

<img width="1135" alt="Screenshot 2023-07-25 at 4 07 04 PM" src="https://github.com/flutter/devtools/assets/21270878/a80a5f6b-92da-4a66-85c2-6f3f8e96a3df">
