### ISSUE TITLE
Support launching browser from STDIN without going via the VM service

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#611]
This came up at https://github.com/Dart-Code/Dart-Code/issues/1505#issuecomment-486858525 but that Dart-Code issue will be closed soon.

@devoncarew is this something you need urgently?

**Comment by devoncarew** [comment]
It's not urgent, but will be nice polish for IntelliJ going forward.

**Comment by devoncarew** [comment]
I believe this is done.

**Comment by devoncarew** [comment]
https://github.com/flutter/devtools/blob/master/packages/devtools_server/docs/daemon.md#devtoolslaunch-request
