### ISSUE TITLE
Support closing browser tabs when the VM service terminates as an option for launchDevTools

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#612]
When we launch a browser window with launchDevTools we should have an option to have DevTools close it automatically when the VM terminates (I think this should be a param passed to `launchDevTools`).

@jacob314 believes we may already have code that does this somewhere.

**Comment by DanTup** [comment]
(Or, at least re-use the tabs)

**Comment by csells** [comment]
+1 to reuse the DevTools tab if that's possible or to close the tab if it's not.

**Comment by jacob314** [comment]
This is high priority as it blocks us launching devtools more automatically.

**Comment by DanTup** [comment]
@jacob314 did you have ideas on how best to do this? I don't mind taking a look. Should it happen automatically when the VM goes away, or maybe there should be another VM service (similar to `launchDevTools` to `closeDevTools`) that would close that tab/window?

**Comment by DanTup** [comment]
@jacob314 you said you had some ideas on how to do this - I don't mind having a look with some pointers.

**Comment by kenzieschmoll** [comment]
@DanTup can this issue be closed?

**Comment by DanTup** [comment]
Yeah, I'm not sure there's much value in this now. We support disconnect/reconnect fairly well and we're embedded by default now anyway.
