### ISSUE TITLE
card in flutetr

### ISSUE THREAD

**Issue by Sukhmeetsingh306** [flutter/devtools#6122]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.23.1
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Dart Version: 3.0.6
Flutter Version: 3.10.6 / stable
Framework / Engine: f468f3366c / cdbeda788a
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
@Sukhmeetsingh306 Could you please provide more information about the issue you are having?
