### ISSUE TITLE
Browser network option, stuck

### ISSUE THREAD

**Issue by LeiYao123** [flutter/devtools#6141]
![image](https://github.com/flutter/devtools/assets/99799032/6ece9b46-0948-4001-91b9-a65aebd7bb4d)

When an API reports an error and returns a large amount of error information, the response will get stuck, and then crash after a while

---
Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f468f3366c (3 weeks ago) • 2023-07-12 15:19:05 -0700
Engine • revision cdbeda788a
Tools • Dart 3.0.6 • DevTools 2.23.1

**Comment by kenzieschmoll** [comment]
@CoderDake

**Comment by CoderDake** [comment]
This should be fixed now that we truncate the response & request text. 

Probably fixed in this PR: https://github.com/flutter/devtools/pull/6254
