### ISSUE TITLE
Some characters not displayed correctly on web

### ISSUE THREAD

**Issue by bkonyi** [flutter/devtools#6149]
In a [sample program](https://github.com/dart-lang/sdk/blob/main/runtime/observatory/tests/ui/inspector.dart) meant to create instances of most types that can be displayed in a debugger, `stringTrebleClef` contains the character "𝄞", which is a [UTF-16 surrogate pair](https://learn.microsoft.com/en-us/windows/win32/intl/surrogates-and-supplementary-characters). On desktop, this character is rendered correctly, but on web a black character is rendered instead.
 
On desktop:

![image](https://github.com/flutter/devtools/assets/24210656/df16e742-cf1c-4927-b193-0d6790074615)

On web:

![image](https://github.com/flutter/devtools/assets/24210656/0ae73e7f-7e8e-4252-9d99-38d06a81acfe)

**Comment by jacob314** [comment]
How do other similar debugging tools handle this? Including more fonts would be nice but I don't think we really want to include every possible font.
Possible solutions:
add an extra api registered on the VMService by flutter tools that lets us dynamically load exactly the font we need.
just include an extra 50mb of fonts with devtools covering more unicode characters and call that good enough.
