### ISSUE TITLE
Http Request detail view does not refresh when selecting a different request with the same path

### ISSUE THREAD

**Issue by Wouter12** [flutter/devtools#6163]
When selecting 2 different HTTP requests in the Network tab that have the same path, the detail view does not get updated with the details of the newly selected request

steps:
1. open devtools on the network tab
2. have an application send a HTTP request to the same endpoint, but with different request data.
3. select the first request, and open the request detail view
4. select the second request
5. notice that the data of the first request maintains visible
6. When selecting a request to a different endpoint, the detail view updates correctly
___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: x64 (64 bit) android
Dart Version: 2.18.5
Flutter Version: 3.3.9 / stable
Framework / Engine: b8f7f1f986 / 8f2221fbef
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
@Wouter12 DevTools 2.23.0 has a lot of network fixes.
I believe these changes are now in flutter stable so you should be able to run `flutter upgrade` which I believe will upgrade your flutter to the head of stable.

**Comment by Wouter12** [comment]
Indeed, running it with the latest devtools fixes this issue
