### ISSUE TITLE
Provide more stats on each platform message

### ISSUE THREAD

**Issue by jiahaog** [flutter/devtools#6166]
When optimizing for latency, it is helpful to identify *interesting* platform messages. These can be, but is not limited to:

- Platform messages that send a large amount of data
- Platform messages that take a long time in the method codecs during encoding and decoding
- Platform messages that wait a long time when jumping from the Dart UI thread to the host task queue (for that platform channel)
- Platform messages that wait a long time when jumping from the host task queue to the Dart UI thread
- Platform messages handlers (e.g. `onMethodCall`) that take a long time to run

This can guide performance work by developers. For example, if a platform message takes a long time to jump from the Dart UI thread to the host task queue, such as in instances where the platform thread servicing the default host task queue is blocked, one option would be to use a background task queue for that channel.

Related is https://github.com/flutter/flutter/pull/104531 which provides aggregated stats on the platform messages, but we would like similar data for *each* platform message.

go/flutter-e2e-pm-hack is an internal document that explains a hack for this in more detail, by passing down an identifier from Dart to the engine and host to track the platform message invocation, and then using a perfetto query to parse the timeline events. There are probably better ways to do this though, and it would be nice if this can be eventually integrated into devtools in some sort of table.

cc @gaaclarke @kenzieschmoll

**Comment by kenzieschmoll** [comment]
The "Track platform channels" setting has been added to the Performance page in DevTools. If there is additional work here that needs to be done on the DevTools side, please feel free to reopen this issue. Thanks.
