### ISSUE TITLE
Can't select/copy body of HTTP request

### ISSUE THREAD

**Issue by OSA413** [flutter/devtools#6176]
Can neither select nor copy the body of HTTP POST request from the Network tab.
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: x64 (64 bit) android
Dart Version: 2.19.1
Flutter Version: 3.7.1 / stable
Framework / Engine: 7048ed95a5 / 800594f1f4
Connected app type: Flutter native (debug build)

**Comment by udit6023** [comment]
Ensure that the Content-Type header of the HTTP response is set to an appropriate value, such as "application/json". This will help the debugging tools recognize and display the response body properly.

**Comment by CoderDake** [comment]
@OSA413 DevTools 2.23.0 has a lot of network fixes.
These changes are now in flutter stable so you should be able to run flutter upgrade which I believe will upgrade your flutter to the head of stable.

Feel free to re-open this if you continue to have issues with DevTools >= 2.23.0

**Comment by OSA413** [comment]
Still experiencing the issue, the copy button doesn't seem to work.
___
**DevTools version**: 2.23.1
**Connected Device**:
CPU / OS: x64 (64 bit) android
Dart Version: 3.0.6
Flutter Version: 3.10.6 / stable
Framework / Engine: f468f3366c / cdbeda788a
Connected app type: Flutter native (debug build)

**Comment by OSA413** [comment]
Please, reopen the issue, I can't do this

**Comment by OSA413** [comment]
@CoderDake

**Comment by CoderDake** [comment]
@OSA413 there seems to be a larger issue with copy that is being tracked here:https://github.com/flutter/devtools/issues/5775
