### ISSUE TITLE
Add more in depth tests to pkg:vm_service before migrating to new package.

### ISSUE THREAD

**Issue by CoderDake** [flutter/devtools#6194]
we need to make sure that the service event and stream behaviour does not break during the migration.

More end to end tests will help with this

**Comment by kenzieschmoll** [comment]
Should the issues related to the DTD be tracked on the dart-lang/sdk repo where the work is going to be done? DevTools will just be a client of the DTD, so it seems misleading to track the work here.

**Comment by CoderDake** [comment]
Fair enough. I will see about creating the issues there, and potentially creating the project there as well.
It won't let me transfer it there though 🤔

**Comment by CoderDake** [comment]
Moved to dart-lang/sdk project
https://github.com/orgs/dart-lang/projects/80/views/1
