### ISSUE TITLE
Add an inspector page

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#62]
Match functionality of intellij inspector. Write code so it is straightforward to port to Hummingbird.

**Comment by devoncarew** [comment]
I think we can host this in the `Device` page, or move the (currently minimal) contents of the device page into an `Inspector` page.

**Comment by jacob314** [comment]
I like it. The existing Device icon works better for the inspector than the ugly hour glass I had been using.
![expand_collapse_fun](https://user-images.githubusercontent.com/1226812/50673190-47282a80-0f91-11e9-9adb-6e2eecb5bac6.gif)

**Comment by rrousselGit** [comment]
👋 (not sure if this is fine to ask it here, but I don't see any other related location, and this is related)

I'm working on integrating a new kind of widgets with the widget inspector. And I've been wondering a few things about how the style of a `Diagnosticable` node is rendered:

- What determines if a node should have an icon or not?
- How is that icon picked? Some widgets seem to have a custom icon (animated widgets, which have a play button). 
- What makes the name of a node **bold**?
- Why does sometimes a property can be expended and sometimes not? For example on the previous screen capture, `renderObject` have nested fields. But if we added a renderObject within that `renderObject`, the nested one would be printed as `toString`.

Also:
Will this tool have the _exact same rendering_ as found in IntelliJ, or is it possible that there will be some differences?

Sorry for the inconvenience and thanks in advance!

**Comment by jacob314** [comment]
Answers:
1. https://github.com/flutter/devtools/blob/master/packages/devtools/lib/src/inspector/flutter_widget.dart
loads the json defining the categories for widgets and defines the icon mapping. We could do more to polish the icons and the mapping and allow users to provide annotations on their widget classes so user widgets are categorized as well.
2. Bold nodes are widgets created by the local project. This is done by running with the --track-widget-creation flag to figure out which widgets are local.
3. Actually that sounds like  a bug and you should see all properties where the value implements Diagnosticable be expandable in the web based devtools app.

The rendering is quite consistent but we may add features in one place (typically Devtools) before adding back to Intellij.
