### ISSUE TITLE
Flutter inspect is not directing to source code

### ISSUE THREAD

**Issue by satishs22** [flutter/devtools#6222]
When I inspect a widget in my device it usually will direct it to the source code directly but for some reason its not doing that now although it shows in the dev tool on what widget im inspecting
___
**DevTools version**: 2.25.0
**Connected Device**:
CPU / OS: ia32 (32 bit) android
Dart Version: 3.1.0
Flutter Version: 3.13.0 / stable
Framework / Engine: efbf63d9c6 / 1ac611c64e
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
@satishs22 are you using android studio?
It looks like there is an open issue right now for this already: https://github.com/flutter/flutter-intellij/issues/6875#issuecomment-1685507314

**Comment by satishs22** [comment]
yep im using android studio

**Comment by redfieldchristabel** [comment]
I'm having the same issue with this. , It worked just fine a minute ago and after upgrading to the latest Flutter it stop working

**Comment by CoderDake** [comment]
progress for this issue will be tracked in: https://github.com/flutter/flutter-intellij/issues/6875 so I will close this ticket
