### ISSUE TITLE
Make request uri more readable in network tab

### ISSUE THREAD

**Issue by miDeb** [flutter/devtools#6225]
Currently, it is difficult to see the path of the uri, because only the initial part (i.e. the host part) is partially visible.
![Screenshot 2023-08-21 144504](https://github.com/flutter/devtools/assets/44171190/fc694327-0433-4803-bc08-d734a14b29bd)

To see more of the url, you have to increase the devtools width significantly or select each individual request.

There might be two ways to fix this:
- Make the columns resizable individually
- Separate columns for the host and path parts of the url

When comparing with browser devtools, firefox has two columns for host and path, while chrome does not even show the host. Both browsers allow resizing columns.

**Comment by kenzieschmoll** [comment]
This should be resolved.
