### ISSUE TITLE
fusca_full

### ISSUE THREAD

**Issue by brunojr01** [flutter/devtools#6227]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.25.0
**Connected Device**:
CPU / OS: ia32 (32 bit) android
Dart Version: 3.1.0
Flutter Version: 3.13.0 / stable
Framework / Engine: efbf63d9c6 / 1ac611c64e
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
@brunojr01 Couple you please provide some more information about the issue you are having?
