### ISSUE TITLE
Icon not show

### ISSUE THREAD

**Issue by Hunter1725** [flutter/devtools#6248]
<-- Please describe your problem here. Be sure to include repro steps. -->

The icon in the Flutter Inspector page in the browser do not show like the following
"https://docs.flutter.dev/assets/images/docs/tools/devtools/visual_debugging_options.png"
The same goes for the icons in the widget tree.
___
**DevTools version**: 2.25.0
**Connected Device**:
CPU / OS: x64 (64 bit) android
Dart Version: 3.1.0
Flutter Version: 3.13.1 / stable
Framework / Engine: e1e47221e8 / b20183e040
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
@Hunter1725 could you please provide more details about not showing?
When I test this I can see them.

Perhaps could you attach some screenshots?

**Comment by Hunter1725** [comment]
@CoderDake
The problem I encountered is shown as shown below:
![Screenshot 2023-08-25 220215](https://github.com/flutter/devtools/assets/98210343/5eac3537-fa27-4aae-b2b6-e65a60dae54f)

What I actually want it to display is something like this:
![image](https://github.com/flutter/devtools/assets/98210343/ae4b48c3-8720-41a3-a836-990b86c7f864)

I tried using another browser, but it still has this problem.

**Comment by CoderDake** [comment]
Oh wow that is interesting. Could you please open the developer tools, can check the console for errors?


If you find anything there could you please send a screenshot of that too?

![Screenshot 2023-08-25 at 11 13 32 AM](https://github.com/flutter/devtools/assets/1386322/38ec6de6-869f-49e1-b04c-770e2c3b3f77)

**Comment by Hunter1725** [comment]
@CoderDake 
I got some of the following errors:
![image](https://github.com/flutter/devtools/assets/98210343/136ff0b4-e22e-4e44-9783-2ea570368ef4)

I am learning Flutter so I don't understand these errors very well :(((

**Comment by CoderDake** [comment]
So i wonder if this is related to: https://github.com/flutter/flutter/issues/126839
Where the file was getting blocked by the windows download manager.
Could you please run `flutter upgrade` to upgrade your stable version to see if the fix helps?

**Comment by Hunter1725** [comment]
@CoderDake 
Thanks for helping me. I have tried to update Flutter, but it still has this problem. I will disable IDM as a temporary solution.

**Comment by CoderDake** [comment]
@Hunter1725 just in case can you copy the contents of `flutter --version` so I can double check if the fix is on that particular version?
