### ISSUE TITLE
Add ImageViewer for network requests and responses

### ISSUE THREAD

**Issue by CoderDake** [flutter/devtools#6261]
Currently we just display the image bytes as text.
Adding an imageViewer would greatly improve the experience here.

**Comment by kenzieschmoll** [comment]
@bkonyi added this functionality a couple years ago: https://github.com/flutter/devtools/pull/2922. Did we regress or rip this out somehow?

**Comment by kenzieschmoll** [comment]
> I'm not sure we can (or should) display images in a JSON response, so this issue is probably not relevant.

@bkonyi can you elaborate more on your concern with supporting this feature?

**Comment by bkonyi** [comment]
> > I'm not sure we can (or should) display images in a JSON response, so this issue is probably not relevant.
> 
> @bkonyi can you elaborate more on your concern with supporting this feature?

How do we determine if a JSON payload has an image that should be displayed? Where would we display it? In the JSON viewer? It just seems like there's possibly a lot of edge cases and won't really give us much benefit.

**Comment by kenzieschmoll** [comment]
Agreed. Let's close for now and if there is increasing user request for this feature we can reconsider.
