### ISSUE TITLE
Reporting error: Failed to parse package:s_cash_mobile_app/main.dart.

### ISSUE THREAD

**Issue by Ncho74** [flutter/devtools#6279]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.25.0
**Connected Device**:
CPU / OS: arm (32 bit) android
Dart Version: 3.1.0
Flutter Version: 3.13.1 / stable
Framework / Engine: e1e47221e8 / b20183e040
Connected app type: Flutter native (profile build)

**Comment by kenzieschmoll** [comment]
Can you please add more information to this bug? Where did you see the error in the issue title? Was this a DevTools error or did this come from Flutter?
