### ISSUE TITLE
Reporting error: Failed to parse package:joiner_1/main.dart.

### ISSUE THREAD

**Issue by nellahmarie** [flutter/devtools#6309]
inspector not showing
___
**DevTools version**: 2.25.0
**Connected Device**:
CPU / OS: x64 (64 bit) android
Dart Version: 3.1.0
Flutter Version: 3.13.1 / stable
Framework / Engine: e1e47221e8 / b20183e040
Connected app type: Flutter native (profile build)

**Comment by CoderDake** [comment]
@nellahmarie could you please provide some more information about how you are running into this issue? Any information that could help us reproduce this would be helpful.
