### ISSUE TITLE
when i try run my flutter app in web (chrome)

### ISSUE THREAD

**Issue by rafealthehlah18** [flutter/devtools#6313]
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
This app is linked to the debug service: ws://127.0.0.1:1575/fAxNXt1LBZ0=/ws
Debug service listening on ws://127.0.0.1:1575/fAxNXt1LBZ0=/ws
Debug service listening on ws://127.0.0.1:1575/fAxNXt1LBZ0=/ws
Error: Assertion failed: file:///C:/Users/E.Rafe/AppData/Local/Pub/Cache/hosted/pub.dev/firebase_core_web-2.6.0/lib/src/firebase_core_web.dart:255:11
options != null
"FirebaseOptions cannot be null when creating the default app."
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3    assertFailed
packages/firebase_core_web/src/firebase_core_web.dart 255:18                  initializeApp
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
dart-sdk/lib/async/zone.dart 1661:54                                          runUnary
dart-sdk/lib/async/future_impl.dart 159:18                                    handleValue
dart-sdk/lib/async/future_impl.dart 843:44                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 872:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 644:5                                     [_completeWithValue]
dart-sdk/lib/async/future.dart 529:22                                         <fn>
dart-sdk/lib/async/zone.dart 1661:54                                          runUnary
dart-sdk/lib/async/future_impl.dart 159:18                                    handleValue
dart-sdk/lib/async/future_impl.dart 843:44                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 872:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 644:5                                     [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 718:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:15           <fn>
___
**DevTools version**: 2.26.1
**Connected Device**:
CPU / OS: Web windows
Connected app type: Flutter web (debug build)
Dart Version: 3.2.0-42.2.beta
Flutter Version: 3.14.0-0.2.pre / beta
Framework / Engine: 123453dc41 / b93c76ab94

**Comment by CoderDake** [comment]
@rafealthehlah18 this doesn't appear to be related to Dart Devtools.
Please take a look at your error message to help you resolve this issue:
> "FirebaseOptions cannot be null when creating the default app."

It looks like you need to pass along FirebaseOptions with a value in order to avoid this issue.
