### ISSUE TITLE
Reporting error: Failed to parse package:elearingapp/main_prod.dart.

### ISSUE THREAD

**Issue by aravithapa** [flutter/devtools#6322]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.25.0
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Dart Version: 3.1.0
Flutter Version: 3.13.0 / stable
Framework / Engine: efbf63d9c6 / 1ac611c64e
Connected app type: Flutter native (profile build)

**Comment by CoderDake** [comment]
@aravithapa could you please provide more information about the issue you are having with Dart DevTools?

**Comment by kenzieschmoll** [comment]
https://github.com/flutter/devtools/pull/6440 should help with making error reports like this more actionable.
