### ISSUE TITLE
Flutter Devtools Grey Screen in Request Tab

### ISSUE THREAD

**Issue by justjcool** [flutter/devtools#6339]
![image](https://github.com/flutter/devtools/assets/25983532/a874b11e-3117-486c-9bc8-c7934acf012c)

**Request tab not showing any data**

Request Json is not visible in devtool. in the browser showing the error 'Invalid JSON'. 

check done:
- payload JSON is valid
- All APIs are working and getting responses. 
- getting issue in all the requests.

___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Dart Version: 2.18.4
Flutter Version: 3.3.8 / stable
Framework / Engine: 52b3dc25f6 / 857bd6b74c
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
@justjcool DevTools 2.23.0 has a lot of network fixes.
These changes are now in flutter stable so you should be able to run `flutter upgrade`, to update your flutter version to the tip of stable.

Feel free to re-open this if you continue to have issues with DevTools >= 2.23.0
