### ISSUE TITLE
Flutter inspector does not go to code when I click

### ISSUE THREAD

**Issue by mo-neivor** [flutter/devtools#6349]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.25.0
**Connected Device**:
CPU / OS: Web linux
Dart Version: 3.1.0
Flutter Version: 3.13.1 / stable
Framework / Engine: e1e47221e8 / b20183e040
Connected app type: Flutter web (debug build)

**Comment by CoderDake** [comment]
This seems to work for me with your version. Are you using intellij?

**Comment by mo-neivor** [comment]
Yes

**Comment by kenzieschmoll** [comment]
Closing as a duplicate of https://github.com/flutter/flutter-intellij/issues/6894 @helin24 @jwren

**Comment by helin24** [comment]
See https://github.com/flutter/flutter-intellij/issues/6894#issuecomment-1714549150 for some options to fix this.
