### ISSUE TITLE
Environment variables provided by var option doesn't work for top right launch shortcuts.

### ISSUE THREAD

**Issue by DanBaDo** [flutter/devtools#6381]
After including a environment variable using `env` option and setting to `templateFor` a empty string value, variable value is accesible for all launching and testing cases, except when clicking top right shortcut icon.

Can see a example here: https://github.com/DanBaDo/dart-code-extension-4736-test

**Comment by DanTup** [comment]
I've moved this to https://github.com/Dart-Code/Dart-Code/issues/4746, since this is a VS Code (or DAP) issue, and not DevTools.
