### ISSUE TITLE
Flutter Inspector not working

### ISSUE THREAD

**Issue by armanlkodev** [flutter/devtools#6396]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.25.0
**Connected Device**:
CPU / OS: x64 (64 bit) android
Dart Version: 3.1.0
Flutter Version: 3.13.2 / stable
Framework / Engine: ff5b5b5fa6 / b20183e040
Connected app type: Flutter native (debug build)

**Comment by EArminjon** [comment]
Flutter devtools / inspector seems to be broken with Flutter 3.13.X
On widows, devtools cannot open, on MacOs inspector can't select widget and redirect well inside IDE ... 
What is happening.

**Comment by CoderDake** [comment]
@EArminjon there was a known issue with intellij where navigation wasn't working with devtools. 
Does this look like the issue you were having? https://github.com/flutter/flutter-intellij/issues/6894

As for devtools not opening on windows could you please open up a new issue with details about how you are trying to open devtools, and what issues you are running into. Any additional logs or error messages popping up can be helpful too.

**Comment by CoderDake** [comment]
@armanlkodev Could you please provide more information about how the flutter inspector is not working?

**Comment by Ankitkj1999** [comment]
I am facing the same issue macOs: 13.2 (22D49) Apple M1

Flutter version: 3.7.12

Android Studio Giraffe | 2022.3.1 Patch 1
Build #AI-223.8836.35.2231.10671973, built on August 17, 2023
Runtime version: 17.0.6+1-b653.34 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    com.tao.provider (1.5.3)
    com.github.copilot (1.2.22.3129)
    com.bloc.intellij_generator_plugin (3.4.0)
    Dart (223.8950)
    andrasferenczi.dart-data-plugin (0.2.0)
    com.mallowigi (85.1.0)
    io.flutter (75.1.2)
    nix-idea (0.4.0.10)

And the video solution provided above does not work for me!
