### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by hyeonjoonpark** [flutter/devtools#6409]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.23.1
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Dart Version: 3.0.6
Flutter Version: 3.10.6 / stable
Framework / Engine: f468f3366c / cdbeda788a
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
Without additional information, we cannot debug this issue. Please re-open if you can provide a description of your issue and repro steps. Thanks.
