### ISSUE TITLE
Flutter inspector is not pointing to widget at code editor

### ISSUE THREAD

**Issue by bzdbss** [flutter/devtools#6413]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.25.0
**Connected Device**:
CPU / OS: Web windows
Dart Version: 3.1.2
Flutter Version: 3.13.4 / stable
Framework / Engine: 367f9ea16b / 9064459a8b
Connected app type: Flutter web (debug build)

**Comment by kenzieschmoll** [comment]
Are you using Android Studio or VS Code?

**Comment by elliette** [comment]
Without additional information, we cannot debug this issue. Please re-open if you can provide a description of your issue and repro steps. Thanks.
