### ISSUE TITLE
DevTools network panel not capturing any request

### ISSUE THREAD

**Issue by ndasim** [flutter/devtools#6447]
We are using http-1.1.0 for network requests in our application. We noticed that the network panel is not working anymore, in previous Flutter versions it was working. 

<img width="1661" alt="image" src="https://github.com/flutter/devtools/assets/6561846/1ae90ce5-8e85-4b7b-9402-4c8d4ec52db9">

```
fvm flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.13.5, on macOS 13.4.1 22F82 darwin-arm64, locale en-GB)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.19.0/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/ndasim/fvm/versions/3.13.5. Consider adding /Users/ndasim/fvm/versions/3.13.5/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
[✓] VS Code (version 1.82.2)
[✓] Connected device (3 available)
[✓] Network resources
```

___
**DevTools version**: 2.23.1
**Connected Device**
CPU / OS: arm64 (64 bit) android
Dart Version: 3.1.2
Flutter Version: 3.13.5 / stable
Framework / Engine: 12fccda598 / bd986c5ed2
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
Hmm this is curious. Could you please "Toggle Developer Tools" if you are in VSCode. Then see if there are any errors in the console that seem relevant?

**Comment by ndasim** [comment]
Hi, sorry for my lateness, I'm not using VSCode, I'm using Android Studio. I'm sharing Chrome console view of it:

<img width="1675" alt="image" src="https://github.com/flutter/devtools/assets/6561846/a1888402-0d52-4e51-8a94-1a02287a343e">

**Comment by justjew** [comment]
Same problem. Running DevTools in Chrome (press `v` on `flutter run` process). Network panel not tracking anything (or rarely catches 2-3 requests and nothing more).
Not working on iOS Simulator nor Android Emulator.
I am using `dio` for http requests.

Here's the doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.83.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

**Comment by LeonManolo** [comment]
same for me:
![Screenshot 2023-12-01 at 12 56 21](https://github.com/flutter/devtools/assets/87019114/b3b69bc3-0b7c-4a53-b852-5da16667194f)

**Comment by endruszeit** [comment]
We have the same problem with flutter 3.16.5. 

We use http 1.1.2. 

We run the app on iOS and Android. 

The problem appears when open devtools in 

- Chrome startet from IntelliJ
And
- using build in devtools in vs code.

**Comment by laterdayi** [comment]
same

**Comment by kenzieschmoll** [comment]
Can you provide a small repro case that we can use to try and reproduce this issue? Thanks.
