### ISSUE TITLE
Alireza

### ISSUE THREAD

**Issue by AlirezaGhaznavi** [flutter/devtools#6458]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.25.0
**Connected Device**:
CPU / OS: x64 (64 bit) android
Dart Version: 3.1.2
Flutter Version: 3.13.4 / stable
Framework / Engine: 367f9ea16b / 9064459a8b
Connected app type: Flutter native (profile build)

**Comment by kenzieschmoll** [comment]
Please reopen this issue if you can provide a description and repro steps. Thanks.
