### ISSUE TITLE
[build_and_copy] If the command fails, a temporary folder created by the command isn't deleted

### ISSUE THREAD

**Issue by rrousselGit** [flutter/devtools#6460]
It appears that the command works by creating a temporary folder under a random name.

While trying the command out (and making mistakes on the way), I found out that if the command errors for any reason, a random directory at `--source` will be created.
Chances are there's a missing cleanup logic on error.

One way to reproduce the issue is to provide a valid `--source` but an incorrect `--dest`

**Comment by kenzieschmoll** [comment]
Fixed by https://github.com/flutter/devtools/pull/6472, which removed the creation of the temp directory altogether
