### ISSUE TITLE
Connection with WebSocket fails

### ISSUE THREAD

**Issue by ThomPoppins** [flutter/devtools#6461]
Connection with WebSocket failes:

![2023-09-25 09_42_30-DevTools for Flutter   Dart — Mozilla Firefox](https://github.com/flutter/devtools/assets/137917151/41ff9587-f1a3-4df5-9845-2d4d065d2feb)

___
**DevTools version**: 2.25.0

{"level":"INFO","message":"DevTools version 2.25.0.","timestamp":"2023-09-25 08:34:54.490Z","loggerName":"framework_core"}
{"level":"SEVERE","message":"[zoneGuarded]: WebSocketChannelException: WebSocket connection failed.","timestamp":"2023-09-25 08:35:00.980Z","loggerName":"app_error_handling","error":"WebSocketChannelException: WebSocket connection failed.","stackTrace":""}
{"level":"SHOUT","message":"WebSocketChannelException: WebSocket connection failed.","timestamp":"2023-09-25 08:35:00.980Z","loggerName":"framework_core","error":"WebSocketChannelException: WebSocket connection failed.","stackTrace":""}
{"level":"SEVERE","message":"[zoneGuarded]: getSupportedProtocols: (-32000) Service connection disposed","timestamp":"2023-09-25 08:35:00.981Z","loggerName":"app_error_handling","error":"getSupportedProtocols: (-32000) Service connection disposed","stackTrace":""}
{"level":"SEVERE","message":"[zoneGuarded]: WebSocketChannelException: WebSocket connection failed.","timestamp":"2023-09-25 08:36:07.199Z","loggerName":"app_error_handling","error":"WebSocketChannelException: WebSocket connection failed.","stackTrace":""}
{"level":"SHOUT","message":"WebSocketChannelException: WebSocket connection failed.","timestamp":"2023-09-25 08:36:07.199Z","loggerName":"framework_core","error":"WebSocketChannelException: WebSocket connection failed.","stackTrace":""}
{"level":"SEVERE","message":"[zoneGuarded]: getSupportedProtocols: (-32000) Service connection disposed","timestamp":"2023-09-25 08:36:07.200Z","loggerName":"app_error_handling","error":"getSupportedProtocols: (-32000) Service connection disposed","stackTrace":""}
{"level":"SEVERE","message":"[zoneGuarded]: WebSocketChannelException: WebSocket connection failed.","timestamp":"2023-09-25 08:36:08.557Z","loggerName":"app_error_handling","error":"WebSocketChannelException: WebSocket connection failed.","stackTrace":""}
{"level":"SHOUT","message":"WebSocketChannelException: WebSocket connection failed.","timestamp":"2023-09-25 08:36:08.557Z","loggerName":"framework_core","error":"WebSocketChannelException: WebSocket connection failed.","stackTrace":""}
{"level":"SEVERE","message":"[zoneGuarded]: getSupportedProtocols: (-32000) Service connection disposed","timestamp":"2023-09-25 08:36:08.558Z","loggerName":"app_error_handling","error":"getSupportedProtocols: (-32000) Service connection disposed","stackTrace":""}
{"level":"WARNING","message":"DevTool's log level changed to FINEST","timestamp":"2023-09-25 08:36:22.842Z","loggerName":""}
{"level":"FINE","message":"Event: select(screenName:settings, selectedItem:copyLogs, value:0, nonInteraction:false)","timestamp":"2023-09-25 08:36:24.241Z","loggerName":"_analytics_web"}

**Comment by kenzieschmoll** [comment]
The URI you are pasting into the connect dialog looks like it is missing the vm service auth token. How  are you running the app that you are trying to connect to DevTools?

**Comment by elliette** [comment]
Without additional information, we cannot debug this issue. Please re-open if you can provide a description of your issue and repro steps. Thanks.
