### ISSUE TITLE
Create a devtools-extension-authors Discord channel 

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#6480]
Once created, this channel should be linked in the DevTools extensions documentation.

The request to create this has already been made on the #server-support Discord channel (CC @Hixie)

**Comment by Hixie** [comment]
creating the channel alone isn't going to achieve much, we'll also need to make sure the channel has activity so that it appears welcoming and relevant. most people aren't going to talk in a channel that has had no recent conversation, because they don't want to stand out or be alone.

**Comment by kenzieschmoll** [comment]
Thanks for the input. We will be linking to this channel from DevTools extensions documentation and social posts. We will also be publicizing this channel for use among early adopters, so we will monitor usage as the extensions feature rolls out to more users.
