### ISSUE TITLE
a

### ISSUE THREAD

**Issue by ammaruo** [flutter/devtools#6495]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.25.0
**Connected Device**:
CPU / OS: x64 (64 bit) android
Dart Version: 3.1.2
Flutter Version: 3.13.4 / stable
Framework / Engine: 367f9ea16b / 9064459a8b
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
@ammaruo Could you please provide information about any issue you are having?
Feel free to open up a new issue when you can provide some more information.
