### ISSUE TITLE
DevTools Debugger: Keep breakpoints after hot restart.

### ISSUE THREAD

**Issue by jacovdbosch** [flutter/devtools#6532]
The debugger will lose the breakpoints you have set after a hot restart. This makes it hard to debug the startup of the app. Firstly, because it is impossible to set `--pause-isolates-on-start` with the Flutter CLI, so you have no time to set the breakpoints at first start, and then secondly, when you have set the breakpoints via the Devtools, once you hot restart the app, the Devtools will forget any breakpoints you have set and it will run like you have never set them.

An alternative would be the `debugger` method in `dart:developer`, but this can be quite annoying when you inevitably forget to remove the `debugger` call before commiting your code. It seems to me that this is a basic functionality that a debugger should have. For example, VSCode does remember breakpoints. I would rather not use VSCode since i'm using Vim and the CLI. Also, VSCode seems to kill the LSP in Vim, or atleast i think that is what is happening (but that is another issue 😄).

**Comment by jacovdbosch** [comment]
My bad, i found the `--start-paused` flag. I do still think this weird behaviour, epecially if you have a lot of breakpoints. You can close this if this is not something that is going to be fixed.

**Comment by elliette** [comment]
Breakpoints now get reestablished after hot-restart (tracking bug here: https://github.com/flutter/devtools/issues/7231) so this should now be possible!
