### ISSUE TITLE
Confusion about casing `extension/devtools/config.yaml`

### ISSUE THREAD

**Issue by simolus3** [flutter/devtools#6539]
According to the readme in `devtools_extensions`, fields for the icons and the issue tracker are are supposed to be in snake case:

https://github.com/flutter/devtools/blob/6c1c637122589a6dd4a27bb5c99578a19dd36794/packages/devtools_extensions/README.md?plain=1#L50-L55

However, the example uses camel case:

https://github.com/flutter/devtools/blob/6c1c637122589a6dd4a27bb5c99578a19dd36794/packages/devtools_extensions/example/foo/packages/foo/extension/devtools/config.yaml#L1-L4

And it seems like DevTools ignores extensions using snake case fields. Was snake case the intended casing or is this just a typo in the readme?

**Comment by kenzieschmoll** [comment]
Thank you for reporting! The snake case was a typo which I have now fixed in https://github.com/flutter/devtools/pull/6535. The `config.yaml` file expects camel case for the fields.
