### ISSUE TITLE
Add DartPad to Flutter devtools

### ISSUE THREAD

**Issue by melWiss** [flutter/devtools#6549]
## Use case

Sometimes I'd like to try something quickly on my laptop so I don't need a fully blown IDE to do that, a simple one like Dartpad will do the trick, but it would be better to run Dartpad directly on my laptop instead on visiting dartpad.dev because sometimes I have this internet connectivity issue so it won't be a great experience if I visit dartpad on the web.

## Proposal
Add Dartpad directly to Flutter devtools, I believe it would boost the Flutter development productivity just a little bit, but it may be very helpful.

**Comment by kenzieschmoll** [comment]
This feature request should actually live in the dart-pad repository, since the work to support this would likely be more on the dart-pad side than in DevTools. I am closing this and I filed a tracking issue there: https://github.com/dart-lang/dart-pad/issues/3048
