### ISSUE TITLE
flutter pub global activate devtools

### ISSUE THREAD

**Issue by Gunjesh2020** [flutter/devtools#6550]
The current Dart SDK version is 3.1.3.

Because pub global activate depends on devtools any which doesn't support null safety, version solving failed.

The lower bound of "sdk: '>=2.1.0-dev <3.0.0'" must be 2.12.0 or higher to enable null safety.

**Comment by kenzieschmoll** [comment]
Closing since DevTools is not shipped on pub.

> Hi! I'm curious where you found instructions to globally activate devtools with pub?

I am also curious about this since DevTools has been shipped as part of the Flutter SDK for a couple years now.
