### ISSUE TITLE
Create performance benchmarks for DevTools

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#6552]
See package https://pub.dev/packages/web_benchmarks. We will need somewhere to submit our benchmark numbers to. Flutter uses Skia Perf so maybe we can do this for DevTools too.

CC @mkustermann @kevmoo @sigmundch adding these benchmarks will help with the dart2wasm investigation.

**Comment by kenzieschmoll** [comment]
@kevmoo @mkustermann @srujzs @sigmundch 

What types of performance can we expect dart2wasm to improve? It would be good to get a small set of benchmarks put together that we expect to show improvements with dart2wasm. For example, do we expect IPL to improve? overall UI perf (scrolling, page transitions, etc.)? Business logic? RPC messaging to / from the VM service? Json parsing? etc.

We have some known expensive operations like collecting a heap snapshot over the VM and parsing it, but I'm not sure where we can expect perf improvements from wasm

**Comment by kevmoo** [comment]
Great question, @kenzieschmoll ! Ideally we'd see improvements across the board. Everything you list *should* get better–or, hopefully–not worse!

**Comment by kevmoo** [comment]
Starting with IPL is great. Any work we could do to track janking frames would be great, too.

**Comment by kenzieschmoll** [comment]
Do we have any IPL benchmarks for other Dart / Flutter products we could use as an example?

**Comment by mkustermann** [comment]
As @kevmoo says, we're interested in benchmarks that are a proxy for user experience of DevTools. The set of benchmarks that would (if dart2wasm is on-par of better than dart2js) convince DevTools team to enable WASM for end users. If dart2wasm is meaningfully worse anywhere, we'd like to know about it and work on it.

> Do we have any IPL benchmarks for other Dart / Flutter products we could use as an example?

@yjbanov What benchmarking infrastructure does flutter use for measuring IPL / ...?

**Comment by kevmoo** [comment]
`web_benchmarks` is now published with Wasm support. Are you unblocked @kenzieschmoll ?
