### ISSUE TITLE
fix not work, devtools cause HttpClient memroy leak

### ISSUE THREAD

**Issue by HXiaoMing** [flutter/devtools#6587]
https://github.com/flutter/devtools/issues/4353

this fix not work, Performing multiple HttpClient.getUrl cause memory leak.

example source code: 源代码：
https://github.com/HXiaoMing/memory_profile_issue.git

Steps to reproduce:

run the example in profile mode, open devtools 

before click [startHttpRequest] button
![07175a913376c99d34ac58c765c5fd7c](https://github.com/flutter/devtools/assets/22089782/ab1b4606-be68-4b1a-8558-813d0422a7b0)

after click [startHttpRequest] button three times(each click after previous http Request success).

RSS 182.44MB -> 219.98MB
Allocated 57.05MB -> 83.91MB
Dart/Flutter 41.04MB -> 66.12MB
Dart/Flutter Native 0.3KB -> 0.85MB

![1b384949535b22854674a6ab915c70d1](https://github.com/flutter/devtools/assets/22089782/51723a42-f2d5-4a85-9255-cdd83e241d2f)

then take heap snapshot for the selected isolate and Filter Classes and Packages and Show all classe:

![image](https://github.com/flutter/devtools/assets/22089782/8a09445c-a19b-4492-8cd2-aa7a49e21467)

finally, find HttpProfileData leak. if download many file or large file will leak more memory.

![image](https://github.com/flutter/devtools/assets/22089782/a2ac55a1-3977-4bcc-b97c-df670fefc9e3)

flutter version:
tt@ttdeMac-mini-2 dimension % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.3 22E252 darwin-arm64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
tt@ttdeMac-mini-2 dimension %

**Comment by kenzieschmoll** [comment]
What version of DevTools are you on? The fix you linked was included in DevTools 2.26.1, so if you are on a version greater than that, you should have seen a warning like the one pictured here: https://github.com/flutter/devtools/pull/5998.

**Comment by HXiaoMing** [comment]
> What version of DevTools are you on? The fix you linked was included in DevTools 2.26.1, so if you are on a version greater than that, you should have seen a warning like the one pictured here: #5998.您使用的是哪个版本的 DevTools？您链接的修复程序已包含在 DevTools 2.26.1 中，因此如果您使用的版本高于该版本，您应该会看到如下图所示的警告：#5998。

DevTools version is 2.25.0. how to change DevTools to 2.26.1 ? i use android studio Open Flutter DevTool, it is 2.25.0.
![image](https://github.com/flutter/devtools/assets/22089782/80a64e0a-99fe-4d88-a71e-65009480f194)

**Comment by CoderDake** [comment]
The version of devtools is tied to the version of flutter you are using :) 

You can run `flutter upgrade` to upgrade your current version of flutter.
