### ISSUE TITLE
MacOS not longer works with this tool

### ISSUE THREAD

**Issue by ollyde** [flutter/devtools#6599]
After upgrading flutter and launching from VSC the app crashes. 
When loading the app via CLI it works fine.

Launch config

```
  {
    "name": "Mac",
    "type": "dart",
    "request": "launch",
    "deviceId": "macOS",
    "program": "lib/main.dart",
    "args": ["flutter run -d macos"],
  },
```

`Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale en-NO)`

**Comment by kenzieschmoll** [comment]
Are you trying to build DevTools or trying to build some other Flutter app and connect it to DevTools?

If it is the former, please follow the [CONTRIBUTING](https://github.com/flutter/devtools/blob/master/CONTRIBUTING.md) instructions for running DevTools. If you open the `devtools/packages` directory in VS code, you will see many launch configurations, and then you can just select the `macOS` device from VS code and click Run to run DevTools on macos. Make sure to follow the instructions about the [workflow for making changes](https://github.com/flutter/devtools/blob/master/CONTRIBUTING.md#workflow-for-making-changes) - there is an important step there to update your local flutter SDK `devtools_tool update-flutter-sdk --local`

**Comment by ollyde** [comment]
@kenzieschmoll interesting I found the issue. On the update it reset the option where-by all debugging was being captured for all events. Just need to disable that again.
