### ISSUE TITLE
Can't re-expand widget trees in inspector

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/devtools#6601]
I'm trying to dig through a widget tree in the inspector. I'm having a difficult time finding what I'm looking for, so I tried collapsing the whole tree and then re-expanding level by level. After I collapse the tree somewhere, I can't re-expand it. Tapping on that widget in the tree has no effect.
___
**DevTools version**: 2.28.1
**IDE**: Android-Studio
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Connected app type: Flutter native (debug build)
Dart Version: 3.3.0-26.0.dev
Flutter Version: 3.16.0-12.0.pre.41 / master
Framework / Engine: 4b72a6e831 / 472be42e90

**Comment by CoderDake** [comment]
@matthew-carroll I don't think I'm able to reproduce this, could you please provide a screen shot or recording of you encountering this issue? Any more detail about what type of widget fails or console errors that you encounter could be helpful too
