### ISSUE TITLE
Inspector search should scroll to results

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/devtools#6602]
I'm trying to find a subtree in the widget inspector in the browser. I used the search field for the widget tree inspector. It found what I was looking for, but visually the only effect of running a search is that most of the tree became darker. I had to scroll all the way to the very bottom of the tree to find the search result.

When searching for something in the tree, there should be some set of affordances to auto-scroll to results. Auto-scrolling should probably have up/down buttons like when searching for text in a typical document. But it's annoying to run a search and then still be responsible for finding the result in the tree.
___
**DevTools version**: 2.28.1
**IDE**: Android-Studio
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Connected app type: Flutter native (debug build)
Dart Version: 3.3.0-26.0.dev
Flutter Version: 3.16.0-12.0.pre.41 / master
Framework / Engine: 4b72a6e831 / 472be42e90

**Comment by CoderDake** [comment]
It may be a bug that the first time we search it doesn't auto scroll.

For now if you hit the arrows, in the search box, it should snap focus to the elements
