### ISSUE TITLE
How do we explore the render tree?

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/devtools#6603]
I'm trying to debug a layout constraints issue. I'm using the inspector in the browser. I don't see a render tree anywhere. Didn't we used to have a render tree in the inspector? Is it hidden somewhere? If there's no render tree in the inspector, how are developers expected to root cause layout constraint issues when the layout is controlled by render objects within the Flutter framework, and are therefore not visible in the widget tree inspector?
___
**DevTools version**: 2.28.1
**IDE**: Android-Studio
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Connected app type: Flutter native (debug build)
Dart Version: 3.3.0-26.0.dev
Flutter Version: 3.16.0-12.0.pre.41 / master
Framework / Engine: 4b72a6e831 / 472be42e90

**Comment by CoderDake** [comment]
@matthew-carroll do you see [root] at in the widget tree or is it completely blank?

If it is completely blank could you please "Toggle Developer tools" in vscode and copy any relevant errors that you see in the console?

**Comment by kenzieschmoll** [comment]
> Didn't we used to have a render tree in the inspector?

A render tree did exist in the IntelliJ plugin, but the render tree never got ported over to Flutter DevTools. 

When you are looking at a widget in the Widget Details Tree, you should be able to explore properties of the `renderObject`:
![Screenshot 2023-10-27 at 10 16 24 AM](https://github.com/flutter/devtools/assets/43759233/66287d34-609b-4b54-929e-0ea5ae9776b1)

When you select the `renderObject`, this will also be evaluated and dumped to console, where you can explore all the  properties (even private ones):
![Screenshot 2023-10-27 at 10 17 09 AM](https://github.com/flutter/devtools/assets/43759233/e2c98cb4-27d8-42b8-abf4-085d9b024e4c)

and perform further evaluations:
![Screenshot 2023-10-27 at 10 18 22 AM](https://github.com/flutter/devtools/assets/43759233/dd6c51e8-a799-453f-a06a-7f2e2bd904ff)

Does this allow you to do the debugging you are looking for?

**Comment by matthew-carroll** [comment]
I don't know if I saw "[root]" - I'll need to open this again to find out.

> If it is completely blank could you please "Toggle Developer tools" in vscode and copy any relevant errors that you see in the console?

I don't use VSCode.

> Does this allow you to do the debugging you are trying to do?

I don't think so. The issue isn't that I couldn't see the size of a single widget. The issue is that I couldn't explore the render object ancestors above that widget that caused those constraints to be used. In this particular example, I was trying to figure out why a Flutter bottom sheet had a particular height. I eventually dug around enough in the Flutter source code to figure it out, but the much more expedient option would have been to walk up the render tree, find the first render object with a different size, and then jump directly to the Flutter source code for that render object.

**Comment by kenzieschmoll** [comment]
Can't you ascertain the render object hierarchy from the widget tree hierarchy? For example, in the widget details tree here, I am walking down the widget tree, which also has a reference to the render object for each widget:
![Screenshot 2023-10-27 at 2 11 06 PM](https://github.com/flutter/devtools/assets/43759233/8480bf85-1936-4908-a8fe-5b9dff5bab4a)

You can also use the console to perform evaluations like `renderObject.parent`
![Screenshot 2023-10-27 at 2 12 32 PM](https://github.com/flutter/devtools/assets/43759233/95658f3f-4c0b-4c14-a118-4cc1347a9d87)

**Comment by kenzieschmoll** [comment]
> The widget tree, as far as I could tell, only shows certain widgets and not others

The Widget tree on the left shows only the widgets that were created from your app, while the Widget Details tree on the right shows all widgets. If the details tree is not showing all the widgets in the tree, then this is a bug (if you have a small repro case for that please share).

> If we're talking about exploring an unknown tree, I would imagine that playing with expression evaluations would take a very long time to get anywhere. Moreover, you'd have to manage the structure of the tree in your head as you do it. That doesn't seem like a good solution to this problem.

I agree. My suggestions were only for the short term while these other trees are not supported by the inspector today. I created a meta tracking issue to track all the trees we'd like to add to the inspector. This is something I hope we will have time for early next year, but not something our immediate team has the bandwidth to implement at the moment. We are of course happy to take contributions!

**Comment by elliette** [comment]
Since there hasn't been any activity here in a while, I'm going to close this issue. The meta-tracking issue for supporting the render tree (and other trees) is here: https://github.com/flutter/devtools/issues/6614
