### ISSUE TITLE
DevTools extensions feedback

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#6633]
I went through the readme at https://pub.dev/packages/devtools_extensions on Windows to build and test a sample extension and hit some bugs/had some feedback.

(note: I haven't yet tried to have my extension interact with the app, this testing was only getting the Flutter app working correctly inside DevTools both in the simulated and real environment).

- [x] The sample code for `FooPackageDevToolsExtension` is missing Flutter imports and also references a non-existent widget `FooDevToolsExtension`
  I think it'd be better to make it a complete file and use `Placeholder` or something so while trying to get the basics working the user doesn't need to create any additional widgets of their own
  - addressed by https://github.com/flutter/devtools/pull/6639
- [x] The path in the `launch.json` example doesn't seem to match the structure (`"foo/extension/foo_devtools_extension/lib"` vs `"packages/foo_devtools_extension/lib"`)
  While the user will need to tweak this, it should be consistent so it's clearer what should be changed
  - addressed by https://github.com/flutter/devtools/pull/6639
- [x] `Member not found: 'profilePlatformChannels'` when using current beta
  Fix in progress at https://github.com/flutter/devtools/pull/6632
- [x] The example command for `build_and_copy` is written using && and backslash continuations so is awkward to copy/paste for Windows
  Split across multiple lines?
  - addressed by https://github.com/flutter/devtools/pull/6639
- [x] build_and_copy fails due to trying to run `flutter` but needing to be `flutter.bat` on Windows
  https://github.com/flutter/devtools/blob/d5ce5a879060e515cfd52bb1af2c48ba8f04bb17/packages/devtools_extensions/bin/_build_and_copy.dart#L59
  - addressed by https://github.com/flutter/devtools/pull/6639
- [x] build_and_copy fails because it tries to run `chmod` which doesn't exist on Windows
  https://github.com/flutter/devtools/blob/d5ce5a879060e515cfd52bb1af2c48ba8f04bb17/packages/devtools_extensions/bin/_build_and_copy.dart#L75
  - addressed by https://github.com/flutter/devtools/pull/6639
- [x] Probably known, but doc has `<TODO: insert version>` - fixed by https://github.com/flutter/devtools/pull/6631
- [x] Initially I misread the docs and entered `name: "Danny's First Extension"` in my `config.yaml` (instead of the name of my package like `name: danny_library`). This prevented the "Enable" button from working when I loaded in DevTools
  - added a note in the config.yaml spec (https://github.com/flutter/devtools/pull/6639)  but I'd like to make this more fail safe too 
  - added validation in https://github.com/flutter/devtools/pull/6666
- [ ] When I go to the extension settings in DevTools (where I can enable/disable each extension), the toggle button is labelled "Enabled | Disabled" which looks odd
- [x] In the nav, the name has the first letter capitalised which looks odd
  I used `name: danny_library` and the nav has **Danny_library**. It'd look better if written as-is in the config (and maybe if the config is allowed uppercase even if the package name doesn't have it, that should be noted)
  - https://github.com/flutter/devtools/pull/6666

@kenzieschmoll

**Comment by kenzieschmoll** [comment]
Thanks for all this feedback Danny. I'm burning down this list. Question - were you able to successfully load your extension in DevTools by running an app that depends on your package (the one that provides the devtools extension) and opening the DevTools instance that was served from Flutter?

**Comment by DanTup** [comment]
> were you able to successfully load your extension in DevTools by running an app that depends on your package (the one that provides the devtools extension) and opening the DevTools instance that was served from Flutter?

Yep. I was running DevTools with `dart devtools` (where `dart` was in `cache/dart-sdk` of my Flutter repo) and connecting to my sample app which had a `path` dependency to my package that had the compiled extension.

However, my extension was just a `Placeholder` and didn't actually interact with the running app (so I didn't do any testing of the communication between extension/app over the VM Service).

**Comment by kenzieschmoll** [comment]
> When I go to the extension settings in DevTools (where I can enable/disable each extension), the toggle button is labelled "Enabled | Disabled" which looks odd

This is the only item I didn't address. This is a toggle state button and since the extension is neither enabled nor disabled, neither enabled or disabled are shown as selected.

**Comment by DanTup** [comment]
> and since the extension is neither enabled nor disabled

Ah, so it just looked odd because of the other error? In that case, this all sgtm - thanks! :-)
