### ISSUE TITLE
devtools_tool release-helper does not create PR

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#6679]
Used guidance: https://github.com/flutter/devtools/blob/master/tool/RELEASE_INSTRUCTIONS.md#create-a-release-pr

Output:

```
...

 > devtools_tool update-version current-version
2.30.0
 > git commit -a -m Prepare for release (exitCode: 0, stderr: , stdout: 2.30.0
)
fatal: paths 'for ...' with -a does not make sense
ProcessException: Failed with exit code: 128. 
  Command: git commit -a -m Prepare for release (exitCode: 0, stderr: , stdout: 2.30.0
)
```

**Comment by polina-c** [comment]
This is what was changed: https://github.com/flutter/devtools/pull/6678
Commit: https://github.com/flutter/devtools/pull/6678/commits/43d8fe8f4e9eb24b1fcd2e8c4c9692d39d6c7584

**Comment by DanTup** [comment]
I think the issue is that the commit message doesn't have quotes - but adding quotes raises another issue. I have a possible fix here:

https://github.com/flutter/devtools/pull/6684

But to avoid similar issues I think we should remove all of the splitting of args by spaces.
