### ISSUE TITLE
Consider making scaffold padding optional for DevTools extension screens

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#6725]
By default we have a horizontal padding of 16.0 around each DevTools screen, including extension screens. @vlidholt requested that this padding value be configurable. I'd like to get UX input before expanding the DevTools extensions api to allow this.

**Comment by vlidholt** [comment]
For context, I'm providing a screenshot of our tooling here. We're happy to do a redesign, but in it's current state it would look better without the padding. :)

<img width="1476" alt="Screenshot 2023-11-13 at 11 16 15" src="https://github.com/flutter/devtools/assets/1539812/7a440098-25b1-46b7-bcae-91666defe143">

**Comment by Nancyhu2023** [comment]
I think keep it as it is is fine. Devtoos's containment style is not implied. Unless in the future, there is a need to revisite the containment style of DevTools and change it holisticlly.

**Comment by kenzieschmoll** [comment]
Per UX guidance, I'm going to close this for now then. For the record @vlidholt, I think your extension looks great even with the padding! It looks like it seamlessly fits into DevTools like all the other first party screens. If you want an outline, consider wrapping your extension with `RoundedOutlinedBorder` from `package:devtools_app_shared`.

**Comment by vlidholt** [comment]
@kenzieschmoll Thank you! We are super close to our release now, so we're keeping it like this this update. Will fix it up a bit nicer in future updates.
