### ISSUE TITLE
Calling `serviceManager.isolateManager` immediately on startup throws exception

### ISSUE THREAD

**Issue by vlidholt** [flutter/devtools#6735]
In a Devtools extension, trying to access `serviceManager.isolateManager` immediately on startup throws an exception.

`Expected a value of type 'ServiceManager<VmService>', but got one of type 'Null'`

I would expect this to work, or have some explanation/documentation of at which point in time the `isolateManager` is available to use.

**Comment by kenzieschmoll** [comment]
The `serviceManager` global is initialized in `initState` from the `DevToolsExtension` stateful widget: https://github.com/flutter/devtools/blob/master/packages/devtools_extensions/lib/src/template/devtools_extension.dart/#L86

It is expected that any usage of the `serviceManager` and `extensionManager` globals should happen below that level of the widget tree.

**Comment by vlidholt** [comment]
Ok, cool. It would be nice with a more expressive error message here. :)
