### ISSUE TITLE
red screen of death

### ISSUE THREAD

**Issue by Turrell14** [flutter/devtools#6749]
<-- Please describe your problem here. Be sure to include repro steps. -->
__my flutter is showing the red screen of death how do I fix it  
![image](https://github.com/flutter/devtools/assets/131712404/d54a8b8c-36e4-4282-9e11-735164228b71)
_
**DevTools version**: 2.30.0-dev.1
**IDE**: VSCode
**Connected Device**:
CPU / OS: Web windows
Connected app type: Flutter web (debug build)
Dart Version: 3.3.0-120.0.dev
Flutter Version: 3.17.0-5.0.pre.63 / master
Framework / Engine: e33d4b8627 / 828e4dbf66

**Comment by CoderDake** [comment]
@Turrell14 this appears to be an issue you are running into with the app you are writing.

Please check the debug console in VSCode for a more detailed stack trace. It will hopefully point you in the right direction for the null access you are running into.
