### ISSUE TITLE
Timeline not working with more than one isolates

### ISSUE THREAD

**Issue by 2dxgujun** [flutter/devtools#679]
```
→ flutter doctor                                                                                                                           [36acd02c9]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.0, on Mac OS X 10.14.3 18D109, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 9.4)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup
[✓] Android Studio (version 3.4)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by devoncarew** [comment]
@2dxgujun, can you describe the behavior you're seeing, and what you want expect to see?

I expect that you're only getting data for the currently selected isolate? There's an isolate selector at th bottom left of the page.

@kenzieschmoll for fyi

**Comment by 2dxgujun** [comment]
@devoncarew I open one FlutterActivity (there is only one isolate), and the timeline view is working, and when I open more than one FlutterActivity (multiple isolates), and the timeline view is not working (no updates).

 Yes, I see the isolate selector, and I select the isolate one by one, still nothing update in the timeline view.

**Comment by 2dxgujun** [comment]
Dart DevTools version 0.1.0
Google Pixel XL API 28

And I can reproduce the problem by create a new flutter application with little changes:

1. Remove the `android:launchMode="singleTop"` from AndroidManifest.xml
2. Add the following code inside `MainActivity` onCreate:

```java
if (getIntent().getBooleanExtra("open_more", true)) {
    new Handler().postDelayed(new Runnable() {
        @Override
        public void run() {
            Intent intent = new Intent(MainActivity.this, MainActivity.class);
            intent.putExtra("open_more", false);
            MainActivity.this.startActivity(intent);
        }
    }, 5000);
}
```

then `flutter run`, connect to devtools

**Comment by 2dxgujun** [comment]
Is there any updates?

**Comment by kenzieschmoll** [comment]
The multiple isolate case is on our radar. I will have time to look into this soon, and I will reply to this issue when I have any updates.

**Comment by JackCho** [comment]
same issue, keep an eye on this

**Comment by JackCho** [comment]
@kenzieschmoll any progress ?

**Comment by kenzieschmoll** [comment]
There has not been any progress yet, but I will update this thread when there is. Thanks for following up!

**Comment by kenzieschmoll** [comment]
this is fixed. We pull timeline data from all isolates.
