### ISSUE TITLE
Explain debug paint in the inspector UI

### ISSUE THREAD

**Issue by difujia** [flutter/devtools#680]
Hi guys, it would be much useful if the inspector UI contains explanations about the debug paint (the yellow arrows, blue/grey boxes, etc.). 
Currently, I can find some info buried here:
https://flutter.dev/docs/testing/debugging#visual-debugging
However, this is not thorough and not obvious/convenient for new users like me.

Thanks.

**Comment by devoncarew** [comment]
We should likely describe it in our docs (https://flutter.github.io/devtools/inspector), and perhaps in-line in the UI as well (as a tooltip?).

**Comment by kenzieschmoll** [comment]
![Screenshot 2024-10-17 at 1 29 07 PM](https://github.com/user-attachments/assets/c8a78e94-b6a8-4388-bc8a-051e79cdd910)
