### ISSUE TITLE
Can not copy all details of a network request/response

### ISSUE THREAD

**Issue by CoderDake** [flutter/devtools#6803]

**Comment by leiflinse-trivector** [comment]
I tried to set it to text mode and clicked the copy button, but then when I try to paste into Notepad it has not written to the copy buffer of Windows 11.

![bild](https://github.com/flutter/devtools/assets/118986082/7ce4296d-7203-44e4-8892-74db367b2776)

**Comment by leiflinse-trivector** [comment]
Looks like this has already been addressed and is in queue for release:
https://github.com/flutter/devtools/issues/6752

**Comment by kenzieschmoll** [comment]
closing since this cherry-pick has landed.
