### ISSUE TITLE
Feature request: show traces outside the build method

### ISSUE THREAD

**Issue by filiph** [flutter/devtools#682]
Most well-designed apps will spend much of their time outside the build method. 

Any callbacks, for example, will be executed on the UI thread, but not in the build method. When these callbacks have performance issues, they can introduce jank that is invisible from the perspective of just build methods (see "Metrics" section of [this article](https://medium.com/flutter/performance-testing-of-flutter-apps-df7669bb7df7)).

I think we should show inter-frame UI thread work by default.

// cc @liyuqian

**Comment by devoncarew** [comment]
Thanks for the feedback! Showing inter-frame work does seem important.

**Comment by kenzieschmoll** [comment]
We show all trace information on all threads, so closing this as obsolete.
