### ISSUE TITLE
Widget Inspector size bug

### ISSUE THREAD

**Issue by Elfandy** [flutter/devtools#6828]
<-- Please describe your problem here. Be sure to include repro steps. -->
When i opened the widget inspector in vsCode in my System the screen of the tab is not correct i am pressing way down the actual location of the button in the UI 
it is like pressing in Empty space underneath the button to press the actual button 
it seems like the widget inspector screen is made for 1080p screens and above and it's stuck above the screen and i don't see the start of it

system specs:
Device: HP Pavilion g6 Notebook PC
Dual OS System:Windows 10 , kali linux (version  2023.3)
CPU:Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz
GPU:Intel(R) Graphics 4000 (on board)
Ram: 8GB DDR3 1600MT
Screen Reslotion:  1366x768  

___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Dart Version: 2.19.0
Flutter Version: 3.7.0 / stable
Framework / Engine: b06b8b2710 / b24591ed32
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
@Elfandy could you please provide a short screen recording reproducing this? That will definitely help us visualize the issue you are seeing.

**Comment by kenzieschmoll** [comment]
Without additional information, we cannot debug this issue. Please re-open if you can provide a description of your issue and repro steps. Thanks.
