### ISSUE TITLE
Network tab not found.

### ISSUE THREAD

**Issue by happy-san** [flutter/devtools#6830]
I'm using `Ubuntu 22.04.3 LTS`.

![image](https://github.com/flutter/devtools/assets/68999628/a490f55c-6a42-415b-bc8d-3d890964563f)

___
**DevTools version**: 2.28.2
**Connected Device**:
CPU / OS: Web linux
Connected app type: Flutter web (debug build)
Dart Version: 3.2.0
Flutter Version: 3.16.0 / stable
Framework / Engine: db7ef5bf9f / 74d16627b9

**Comment by kenzieschmoll** [comment]
This is because you are connected to a Flutter web app. We do not support every tool for web app connections because in some cases, Chrome DevTools already has the support you need. Try using the Network tab in Chrome DevTools to perform network debugging on your Flutter web app.

**Comment by AVert** [comment]
im so but open android emulator
