### ISSUE TITLE
Connecting to devtools

### ISSUE THREAD

**Issue by saadouabdoullahi1** [flutter/devtools#6851]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.28.2
**IDE**: VSCode
I wanna know how to connect to a running app in devtools

**Comment by kenzieschmoll** [comment]
Please see the instructions on flutter.dev for guidance on how to run DevTools from VS code: https://docs.flutter.dev/tools/devtools/vscode

**Comment by saadouabdoullahi1** [comment]
I have already resolved it.
Thanks

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
