### ISSUE TITLE
`devtools_tool update-flutter-sdk --from-path` is broken

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#6867]
I'm pretty sure this has to do with the change to always use the flutter-sdk from tools/. CC @DanTup 
```
 ~/develop/devtools/tool/ [master] devtools_tool update-flutter-sdk --from-path
Updating to Flutter version from cache: tags/3.17.0-18.0.pre 
Using Flutter SDK from /Users/kenzieschmoll/develop/devtools/tool/flutter-sdk
Updating local flutter/flutter repository...
Searching for a remote that points to flutter/flutter.git.
/Users/kenzieschmoll/develop/devtools/tool/flutter-sdk > git remote -v
origin  https://github.com/flutter/flutter (fetch)
origin  https://github.com/flutter/flutter (push)
Bad state: Couldn't find a remote that points to flutter/devtools.git. Instead got: 
origin  https://github.com/flutter/flutter (fetch)
origin  https://github.com/flutter/flutter (push)
```

**Comment by DanTup** [comment]
I think the error is caused by a mix of having `flutter/flutter` and `flutter/flutter.git` in the code vs the origin in the clone.

However, the reason these don't match now is probably because we're trying to update a different SDK to what we did before. My assumption with the previous changes was that we basically never wanted to use Flutter from `PATH` (except the flutter customer tests) and I forgot about this flag here.

I guess my first question is why do we want this - why would we use the DevTools scripts to update a different Flutter than the one that we'll use? (eg., why can't we just remove the `--from-path` flag and this code path and _everything_ for DevTools uses the `tool/flutter-sdk`)?

**Comment by kenzieschmoll** [comment]
> I guess my first question is why do we want this - why would we use the DevTools scripts to update a different Flutter than the one that we'll use? (eg., why can't we just remove the --from-path flag and this code path and everything for DevTools uses the tool/flutter-sdk)?

For local development, it is convenient to use the Flutter SDK on path (your local git checkout of flutter). For example, I often check out a specific flutter branch or have local changes in flutter/flutter that I want to develop with. The `--from-path` is supposed to be a convenient way to get your local flutter sdk to match what the bots will use.

**Comment by DanTup** [comment]
> The `--from-path` is supposed to be a convenient way to get your local flutter sdk to match what the bots will use.

I'm not sure I understand - isn't `tool/flutter-sdk` already matching what the bots will use? Why are you not using `tool/flutter-sdk` for _everything_ DevTools related? (my earlier assumptions were that everyone always would, so if those assumptions are not correct, some of the choices I made might not be optimal and we might want to do more than just change what this flag is doing)

**Comment by kenzieschmoll** [comment]
> isn't tool/flutter-sdk already matching what the bots will use?

It should, yes. And the `devtools_tool update-flutter-sdk` command is used by other commands to make sure things execute with the proper flutter version (e.g. updating goldens, generating mocks, etc.).

> Why are you not using tool/flutter-sdk for everything DevTools related?

For developing DevTools, I often need a git checkout of Flutter. For example, let's say I have a flutter/flutter PR that I want to test DevTools with. `tool/flutter-sdk` is not set up with git for development. It would be a bit strange to develop on the flutter framework as a subdirectory of a different git repository (devtools). 

So I may need to do something like analyze the DevTools codebase (which should use tool/flutter-sdk since this is a unmodified flutter SDK at the specific version used by the DevTools CI) at the same time that I have local changes on my local git checkout of flutter/flutter that I don't want to mess with.

I think the proper behavior is this:
1. the `devtools_tool` command should use `tool/flutter-sdk` unless it is manually specified that the Flutter SDK on Path (likely the git checkout where flutter/flutter development happens) should be used instead. This may not apply to every command.
2. The CI should use `tool/flutter-sdk` (as it does currently).
3. the DevTools developer will be using a separate Flutter sdk that is a git checkout on their local machine. This will be the flutter SDK that is on their path.
