### ISSUE TITLE
Re-enable a skipped test in inspector_service_test

### ISSUE THREAD

**Issue by bartekpacia** [flutter/devtools#6902]
A test has been excluded in PR #6903.

That test gives false positives for changes made in PR https://github.com/flutter/flutter/pull/138331. 

After that PR is merged, test fixtures must be updated and this test must be re-enabled.

affected files: [`inspector_service_test`](https://github.com/flutter/devtools/blob/7ff009753e57460fe3e82d0f22d4f4001b3cf996/packages/devtools_app/test/inspector/inspector_service_test.dart)

tests: [`widget tree`](https://github.com/flutter/devtools/blob/7ff009753e57460fe3e82d0f22d4f4001b3cf996/packages/devtools_app/test/inspector/inspector_service_test.dart#L383)

See also discussion on Discord ([link](https://discord.com/channels/608014603317936148/1179200000136319037/1181390182545641583))

**Comment by kenzieschmoll** [comment]
@bartekpacia now that your flutter/flutter PR has merged, can you prepare a DevTools PR (against flutter master that includes your change) to unskip the test and fix the text golden that was failing?
