### ISSUE TITLE
networking page the response is not proper the app endoints also not vsisibling please check that

### ISSUE THREAD

**Issue by Naveen-RS22** [flutter/devtools#6915]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.28.4
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.2.3
Flutter Version: 3.16.3 / stable
Framework / Engine: b0366e0a3f / 54a7145303

**Comment by kenzieschmoll** [comment]
Can you be more descriptive of the issue you are seeing? Can you provide steps to reproduce this issue as well as some screenshots to help us diagnose the problem?
