### ISSUE TITLE
dart fix adding const caused a runtime exception

### ISSUE THREAD

**Issue by kalafut** [flutter/devtools#6925]
Here is this relevant code after `dart fix` made `Row()` const:

```dart

  @override
  Widget build(BuildContext context) {
    final digits = [1, 2, 3];
    var rows = <Row>[];

    var col = 0;

    for (var i = 0; i < digits.length; i++) {
      if (col == 0) {
        // dart fix made Row() const ...
        rows.add(const Row(children: []));
      }

      // And then this line started throwing:
      // Unsupported operation: Cannot add to an unmodifiable list
      rows.last.children.add(CircularButtonWithDigit(
        digit: digits[i],
        onPressed: onPressed,
      ));

      col = (col + 1) % itemsPerRow;
    }

    return Column(children: rows);
  }
```

**Comment by parlough** [comment]
Thanks for opening an issue @kalafut!

For reference, `dart fix` issues generally should be filed against the Dart SDK repository at [`dart-lang/sdk`](https://github.com/dart-lang/sdk). This repository is for the Dart and Flutter DevTools tool. 

For this particular issue, it's unfortunately an inherit part of the [`prefer_const_constructors`](https://dart.dev/lints/prefer_const_constructors) lint. There's a few discussions which discuss it, such as https://github.com/dart-lang/linter/issues/3603, so I'm going to close this in favor of those issues. Please feel free to add your thoughts and experiences to those issues though! Thanks again.
