### ISSUE TITLE
Reporting error: Failed to parse package:calculadora/main.dart.

### ISSUE THREAD

**Issue by martinslegal-web** [flutter/devtools#6926]
Stack trace:
main.dart.js 6162:18    Object.qb
main.dart.js 68147:76   <fn>
main.dart.js 4771:62    bDd.a
main.dart.js 56657:14   bDd.$2
main.dart.js 56651:21   bB_.$1
main.dart.js 5067:19    Object.bCS
main.dart.js 163795:68  ajF.<fn>
main.dart.js 57774:12   Zz.qG
main.dart.js 57160:11   bnX.$0
main.dart.js 4937:40    Object.MA

<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.28.3
**IDE**: VSCode
**Connected Device**:
CPU / OS: Web windows
Connected app type: Flutter web (debug build)
Dart Version: 3.2.2
Flutter Version: 3.16.2 / stable
Framework / Engine: 9e1c857886 / cf7a9d0800

**Comment by kenzieschmoll** [comment]
closing in favor of https://github.com/flutter/devtools/issues/7192
