### ISSUE TITLE
debugger breakpoints list not populated when starting devtools

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#694]
The list of debugger breakpoints isn't populated when devtools starts, and there's already an existing breakpoint set for an isolate. You can repo this by setting a breakpoint in IntelliJ and launching devtools, or by setting a breakpoint in devtools and refreshing the page running devtools.

**Comment by devoncarew** [comment]
I see this as working now.

**Comment by jacob314** [comment]
From the comment on June 8th it sounds like this is working. Please reopen if you are able to reproduce.
