### ISSUE TITLE
Main isolate is paused in the debugger

### ISSUE THREAD

**Issue by hitarthparmar0412** [flutter/devtools#6951]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.28.4
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.2.3
Flutter Version: 3.16.3 / stable
Framework / Engine: b0366e0a3f / 54a7145303

**Comment by kenzieschmoll** [comment]
Hello @hitarthparmar0412. What is the issue you are seeing? If the main isolate is paused, this means that your app is paused on a breakpoint or an exception. You can resume your app from the banner at the top of DevTools that says "Main isolate is paused in the debugger" or from the Debugger page itself. OR if your app is paused in your IDE, you can also resume from there.

Please re-open this issue if you have details about the problem you are experiencing.
