### ISSUE TITLE
Instruction to open devtools is outdated.

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#6954]
This guidance is outdated: https://dart.dev/tools/dart-devtools 

1. There is no url printed if app is running in VSCode. 
2. All options should described in the doc: 
- when app is started with CLI (and what if there is a lot of output and the line with url is already unavailable)
- when app is started with VSCode

**Comment by parlough** [comment]
Thanks for keeping track of this! Would you be able to write something up? I'm not sure we'll have time to get to updating this for a bit.

**Comment by elliette** [comment]
Closing in favor of https://github.com/dart-lang/site-www/issues/5968 in the Dart website repo.
