### ISSUE TITLE
CI broken for flutter `3.18.0-10.0.pre`

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#6963]
Calling any of the below commands causes exceptions:
```
          ./tool/flutter-sdk/bin/flutter config --disable-analytics
          ./tool/flutter-sdk/bin/cache/dart-sdk/bin/dart --disable-analytics
          ./tool/flutter-sdk/bin/flutter doctor
```
Example failure:
https://github.com/flutter/devtools/actions/runs/7202881846/job/19621841010?pr=6961

**Comment by christopherfujino** [comment]
@eliasyishak can you take a look at this?

**Comment by bkonyi** [comment]
Fix up for review here: https://dart-review.googlesource.com/c/sdk/+/341401
