### ISSUE TITLE
Network tab not work

### ISSUE THREAD

**Issue by ductruong1991** [flutter/devtools#6965]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.25.0
**Connected Device**:
CPU / OS: x64 (64 bit) windows
Dart Version: 3.1.0
Flutter Version: 3.13.0 / stable
Framework / Engine: efbf63d9c6 / 1ac611c64e
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
The latest Flutter stable contains DevTools version 2.28.4. Please upgrade your Flutter to see if this resolves your issue. If it does not, please add more details to describe the issue you are seeing - without a more detailed description and reproduction steps, we will not be able to investigate what could be going wrong. Thanks.
