### ISSUE TITLE
Add a page to devtools showing what Dart VM flags were used

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#699]
https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#getflaglist
gives the list of flags.
This data is helpful for users to understand what flags were set when running the VM avoiding confusion about what flags were really on.

**Comment by devoncarew** [comment]
Perhaps behind a gear icon, or some other secondary mechanism than a first-class page?

**Comment by adalberht** [comment]
Hi there!
I want to take this issue as my first contribution to the devtools.
I can't find to find the gear icon and I don't understand the term first-class page here, is it screens like Flutter Inspector, Timeline, Memory, Performance, Debugger and Logging?
By adding a new page, do you mean that we should make a new Screen?
If it's not too much can I get more pointers for this issue?
For now what I'm thinking is to make a new `Screen` and calls `VmServiceWrapper.getFlagList()` then render all the flag.
How about the styling? Should we make different color for each flag?
Thank you very much!

**Comment by jacob314** [comment]
You are correct we haven't yet exposed a gear icon in the app. 
Lets use the gear icon from the octicons icon set that we are using elsewhere.
https://octicons.github.com/icon/gear/
You can see an example of how we use octicon icons here:
https://github.com/flutter/devtools/blob/master/packages/devtools/lib/src/logging/logging.dart#L26

I think making it a full page makes sense for now to get started.
Like you are saying that would mean making it a screen like the Inspector, Timeline, etc. The one difference is the screen would probably only have a gear icon and not a name in the main tab bar to keep the emphasis on the other pages.
We can move it to be an overlay exposed by clicking a gear icon later if the amount of content we want end up display is small.
I imagine we will also want to display details about what version of Flutter is running as well as the flags so keeping it on its own screen could be good.
Even if it is its own screen, we should probably make it a screen with only an icon and not a text name to save horizontal space and emphasize the other screens more.

See
`chrome://flags/`
for some inspiration although chrome has a lot more flags than the VM and I don't know if we have any accessible documentation on what the Dart VM flags are.

**Comment by adalberht** [comment]
Hi there!
I tried adding the new page, can you please review and give feedbacks/suggestions please?
Thank you very much!
