### ISSUE TITLE
Reporting error: Failed to parse package:sdaudit/main.dart.

### ISSUE THREAD

**Issue by IsmoilAzamov** [flutter/devtools#6991]
Stack trace:
main.dart.js 6162:18    Object.qb
main.dart.js 68152:76   <fn>
main.dart.js 4771:62    bDe.a
main.dart.js 56662:14   bDe.$2
main.dart.js 56656:21   bB0.$1
main.dart.js 5067:19    Object.bCT
main.dart.js 163777:68  ajG.<fn>
main.dart.js 57779:12   ZA.qF
main.dart.js 57165:11   bnV.$0
main.dart.js 4937:40    Object.MA

<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.28.4
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (profile build)
Dart Version: 3.2.3
Flutter Version: 3.16.4 / stable
Framework / Engine: 2e9cb0aa71 / 54a7145303

**Comment by kenzieschmoll** [comment]
closing in favor of https://github.com/flutter/devtools/issues/7192
