### ISSUE TITLE
Meta issue: Error collecting raster stats: _flutter.renderFrameWithRasterStats: (-32000) Failed to render the last frame with raster stats. Rasterizer does not hold a valid last layer tree. This could happen if this method was invoked before a frame was rendered

### ISSUE THREAD

**Issue by ChristineWasike** [flutter/devtools#6992]
Stack trace:
Error
    at Object.qb (http://127.0.0.1:9101/main.dart.js:6162:18)
    at http://127.0.0.1:9101/main.dart.js:160252:5
    at bDe.a (http://127.0.0.1:9101/main.dart.js:4771:62)
    at bDe.$2 (http://127.0.0.1:9101/main.dart.js:56662:14)
    at Object.m (http://127.0.0.1:9101/main.dart.js:4757:10)
    at za.aD0 (http://127.0.0.1:9101/main.dart.js:160266:10)
    at za.cb (http://127.0.0.1:9101/main.dart.js:160245:25)
    at za.jD (http://127.0.0.1:9101/main.dart.js:160230:13)
    at il.jD (http://127.0.0.1:9101/main.dart.js:88612:44)
    at http://127.0.0.1:9101/main.dart.js:100353:14
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.28.4
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (profile build)
Dart Version: 3.2.3
Flutter Version: 3.16.5-0.0.pre.1 / stable
Framework / Engine: 607199403a / 54a7145303

**Comment by pamafe1976** [comment]
i had this issue and it was related to the following line in android/app/build.gradle

```
 buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true   <------
```

**Comment by CoderDake** [comment]
Comment from duplicate issue:

> I am suddenly getting this now too. I used to be able to take raster snapshots in devtools but no longer.
> 
> Maybe related: I get this as a popup in bottom right of vscode:
> 
> Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state.

https://github.com/flutter/devtools/issues/7482#issuecomment-2105461958

**Comment by kenzieschmoll** [comment]
This feature has been removed from DevTools, so closing this as obsolete.
