### ISSUE TITLE
Find an elegant way to use DTDResponse in types.dart

### ISSUE THREAD

**Issue by CoderDake** [flutter/devtools#6996]
https://dart-review.googlesource.com/c/sdk/+/342980/4/pkg/dtd/lib/src/dtd_file_system_access/types.dart

The original design said to extend the response, but it seemed to make it more cumbersome.Talk to Ben to see how we can better do this.

**Comment by kenzieschmoll** [comment]
nit: this should be tracked on the dart-lang/ repo

**Comment by kenzieschmoll** [comment]
Moved to the SDK https://github.com/dart-lang/sdk/issues/56997
