### ISSUE TITLE
Reporting error: Failed to parse package:elearingapp/main_dev.dart.

### ISSUE THREAD

**Issue by ChandanLFC** [flutter/devtools#7011]
Reporting error: Failed to parse package:elearingapp/main_dev.dart.
___
**DevTools version**: 2.25.0
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Dart Version: 3.1.3
Flutter Version: 3.13.6 / stable
Framework / Engine: ead455963c / a794cf2681
Connected app type: Flutter native (profile build)

**Comment by kenzieschmoll** [comment]
closing in favor of https://github.com/flutter/devtools/issues/7192
