### ISSUE TITLE
alguna ayuda 

### ISSUE THREAD

**Issue by marios-bit** [flutter/devtools#7012]
<img width="960" alt="image" src="https://github.com/flutter/devtools/assets/112005180/0174dafe-75d7-41bc-8aa7-14ac831294dd">

hola soy nuevo usando flutter quiero acceder al devtools pero me pide que ingrese la url de la aplicación pero no se cual es la url

**Comment by Brunobnahorny** [comment]
¡Hola! Es más fácil pedir ayuda a través del servidor de discordia de Flutter. Siga el siguiente enlace. Te diré que probablemente solo necesites ejecutar la aplicación antes de abrir las herramientas de desarrollo.

**Comment by elliette** [comment]
¡Hola! La URL se imprime en la terminal cuando ejecutas su aplicación

![Screenshot 2024-01-19 at 10 16 30 AM](https://github.com/flutter/devtools/assets/21270878/56c44b9a-e24f-49c6-a265-b3544def18fe)
