### ISSUE TITLE
problem  not  work  mobail !!!  only  work  in cmd

### ISSUE THREAD

**Issue by ArazKoo** [flutter/devtools#7028]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.28.4
**IDE**: VSCode
**Connected Device**:
CPU / OS: x64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.2.3
Flutter Version: 3.16.5 / stable
Framework / Engine: 78666c8dc5 / 3f3e560236

**Comment by kenzieschmoll** [comment]
Is this an issue with DevTools? If so can you please describe your issue and provide repro steps. I will close this but feel free to re-open if you can provide more information.
