### ISSUE TITLE
test

### ISSUE THREAD

**Issue by ninofelino12** [flutter/devtools#7038]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.28.4
**Connected Device**:
CPU / OS: x64 (64 bit) linux
Connected app type: Flutter web (debug build)
Dart Version: 3.2.3
Flutter Version: 3.16.5 / stable
Framework / Engine: 78666c8dc5 / 3f3e560236

**Comment by kenzieschmoll** [comment]
What is the issue you are seeing? If you have more details to add and reproduction steps, feel free to re-open this issue.
