### ISSUE TITLE
I can't enable the extension, the "enable" button doesn't work

### ISSUE THREAD

**Issue by emanuel-braz** [flutter/devtools#7046]
I'm creating a Devtools Extension, in simulated env it works well, but when I deploy, it stops working on real environment.
I can see the tab "Flutter Micro App", but it's not possible to enable it

I tested version `Flutter 3.16.7` and `Flutter 3.16.5` but was unsuccessful :(

Any ideas what it can be?

![image](https://github.com/flutter/devtools/assets/3827308/67c532d7-4706-4321-91b6-783fd3564673)

In order to build the final assests:  
I have tried that 
```
dart run devtools_extensions build_and_copy --source=. --dest=../extension/devtools
```  
and that (and copy build folder to extension/devtools)
```
flutter build web --web-renderer canvaskit --pwa-strategy=offline-first --release --no-tree-shake-icons
```
___
**DevTools version**: 2.28.4
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.2.3
Flutter Version: 3.16.5 / stable
Framework / Engine: 78666c8dc5 / 3f3e560236

Log:
{"level":"INFO","message":"DevTools version 2.28.4.","timestamp":"2024-01-15 14:34:56.760Z","loggerName":"framework_core"}
{"level":"INFO","message":"Attempted to call extension 'ext.flutter.inspector.structuredErrors', but no service with that name exists","timestamp":"2024-01-15 14:34:56.938Z","loggerName":"service_extension_manager"}
{"level":"WARNING","message":"DevTool's log level changed to FINEST","timestamp":"2024-01-15 14:35:34.472Z","loggerName":""}

Browser Log
![image](https://github.com/flutter/devtools/assets/3827308/edf7b230-a344-4df7-bc1d-bb5620162940)

Error screen
![image](https://github.com/flutter/devtools/assets/3827308/039ef64f-f603-4efb-9ce9-ba910a468aab)

Expected screen
![image](https://github.com/flutter/devtools/assets/3827308/2f720893-4a82-4e63-b3de-68658acf6874)

<details>
  <summary>Flutter Doctor</summary>
[✓] Flutter (Channel stable, 3.16.5, on macOS 13.0 22A8380 darwin-arm64 (Rosetta), locale en-BR)
    • Flutter version 3.16.5 on channel stable at /Users/eb/.puro/envs/v3_16_5/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (4 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/eb/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = /Users/eb/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.81.20231227

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.0 22A8380 darwin-arm64 (Rosetta)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 120.0.6099.216

[✓] Network resources
    • All expected network resources are available.
</details>

I have mentioned this in https://github.com/flutter/devtools/issues/4973#issuecomment-1892322806 and I'm not sure if it is the same problem

**Comment by kenzieschmoll** [comment]
What versions of the `devtools_extensions` and `devtools_app_shared` packages are you using for your extension?

**Comment by kenzieschmoll** [comment]
Try bumping your dependencies to `devtools_extensions: ^0.0.12` and `devtools_app_shared: ^0.0.8` and see if you are still experiencing the issue. Also make sure you are running on the latest Flutter stable.

If that still doesn't work, try switching to the Flutter beta channel.
