### ISSUE TITLE
Feedback about stats in devools debugger

### ISSUE THREAD

**Issue by osaxma** [flutter/devtools#7059]
Hi there,

I have two feedbacks about the stats in the debugger:
- The green stats is a bit hard to read when using Dark theme
- The stat that is shown in line 37 should be in line 44 (that's where the code is waiting the majority of the time).
  - I noticed that most of the stats are off by one line or so, but this one seems to be a bit off (maybe because of the commented code?). 

<img width="948" alt="Screen Shot 2024-01-18 at 7 44 42 PM" src="https://github.com/flutter/devtools/assets/46427323/ed7e7a6b-be2b-41cf-9eb6-a6dd4f00e188">

**DevTools version**: 2.28.4
**Connected Device**:
CPU / OS: x64 (64 bit) macos
Connected app type: Dart CLI
Dart Version: 3.2.3

**Comment by osaxma** [comment]
For reference, the yellow one is also hard to read (not sure if there are other colors in between):

<img width="214" alt="Screen Shot 2024-01-19 at 8 41 58 AM" src="https://github.com/flutter/devtools/assets/46427323/ed2ea2ed-9809-44bc-b1fd-347696f85016">

**Comment by bkonyi** [comment]
> For reference, the yellow one is also hard to read (not sure if there are other colors in between):
> 
> <img alt="Screen Shot 2024-01-19 at 8 41 58 AM" width="214" src="https://private-user-images.githubusercontent.com/46427323/297964774-ed2ea2ed-9809-44bc-b1fd-347696f85016.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMTY1MzQsIm5iZiI6MTcwNzMxNjIzNCwicGF0aCI6Ii80NjQyNzMyMy8yOTc5NjQ3NzQtZWQyZWEyZWQtOTgwOS00NGJjLWIxZmQtMzQ3Njk2Zjg1MDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE0MzAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MTdiZWYxZGNjY2NlNzFmYjc4M2M2MzZmMDkxNTI3YzcwMWE1MTIyMjZiYmJhODhlMTMxOWUxODYzMjZhMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nD20kdeOFy8EMtthEv6ixSTBOCO8BtMlRqlxHng72U8">
> And since this is a feedback issue, I really like these stats column! They are pretty handy 😁

Thanks for the feedback @osaxma! Always glad to hear people find things useful!

I've got a fix up for these issues in https://github.com/flutter/devtools/pull/7178.
