### ISSUE TITLE
Web performance profiling instructions have too large of headers

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#7064]
We should match the text style we use for headers on the home screen.

![Screenshot 2024-01-19 at 10 17 50 AM](https://github.com/flutter/devtools/assets/43759233/fb144616-4842-47d2-8748-6364dc0fd180)

**Comment by parlough** [comment]
Where is this? Is it pulled from the website?

**Comment by kenzieschmoll** [comment]
This is in the DevTools repo itself. Addressed by https://github.com/flutter/devtools/pull/7069
