### ISSUE TITLE
Trim mixins from stack frame names in debugger

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#707]
In the timeline, we were getting extremely long class names for stack frames. `_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback`

The important information here would be `_WidgetsFlutterBinding._handlePersistentFrameCallback`, and is what we show in the profiler UI as of https://github.com/flutter/devtools/pull/706.

We may have a similar issue in the debugger UI, and should address it there as well.

**Comment by jacob314** [comment]
Fyi @bkonyi 
We should really fix this in the VM itself as these long names just confuse users.

**Comment by kenzieschmoll** [comment]
Original issue for that here: https://github.com/dart-lang/sdk/issues/36999

**Comment by bkonyi** [comment]
@jacob314, as discussed in dart-lang/sdk#36999 this isn't something we're planning on doing in the VM itself. However, this could be some functionality that lives in `package:vmservice`. If the VM team eventually takes over that package once we've gotten everyone off of using private APIs, we'd be happy to add it there.

**Comment by jacob314** [comment]
Let me follow up on the dart-sdk issue. The key point is the names with `&` are a misfeature and we should modify the VM so it never generates those names in the first place. I'll update the SDK bug ccing interested language team members.

**Comment by elliette** [comment]
I'm not able to repro this in the debugger:
<img width="275" alt="Screenshot 2024-11-19 at 2 01 41 PM" src="https://github.com/user-attachments/assets/6d3d9ec6-2206-468c-bbd7-a33aa8266cc4">
<img width="414" alt="Screenshot 2024-11-19 at 2 01 33 PM" src="https://github.com/user-attachments/assets/fdf85d47-b678-45da-a606-ab61ecb3ca67">
