### ISSUE TITLE
catalog the private service protocol APIs we're using

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#709]
We should catalog the private service protocol APIs we're using; we can either then work to make them (or similar ones) public, or look into other options.

cc @bkonyi

**Comment by devoncarew** [comment]
Here is a (possibly incomplete) list:

- `_clearVMTimeline`
- `_clearCpuProfile`
- `_getInstances`
- `_getCpuProfile`
- `_setVMTimelineFlags`

cc @kenzieschmoll @terrylucas to see if there are any others they're aware of. Some may not be critical - we'd have to dig into the code and use cases. Some - like the timeline related calls - definitely are important.

**Comment by kenzieschmoll** [comment]
`_getCpuProfileTimeline` also.

**Comment by bkonyi** [comment]
Thanks @devoncarew and @kenzieschmoll! I'm going to start looking into making these existing private RPCs public if they don't expose internal VM details or figure out what needs to be done to get public equivalents implemented.

In the meantime, if you find that you need additional functionality that's currently private please reach out to me first so we can figure out how to make that functionality public first :-) I'd like to get all of the customers of the service protocol off of private RPCs at some point in the near future.

**Comment by devoncarew** [comment]
I'll in-line this into our doc in order to have things co-located. We can also provide a bit more detail about how things are being used (or references to the devtools source) to help determine priorities and whether other APIs would work.

**Comment by jacob314** [comment]
Closing as I believe we have removed all our private API uses. Thanks Ben!
Feel free to reopen if we are not done yet.

**Comment by bkonyi** [comment]
We're not quite done yet (almost there though!).

**Comment by terrylucas** [comment]
Hi Ben we still need Platform name of the running application see [Platform Issue](https://github.com/flutter/devtools/issues/813#issuecomment-512852299).  Should this be part of this issue?  It's important because we need a way of fetching the platform for analytics w/o using eval.

**Comment by bkonyi** [comment]
> Hi Ben we still need Platform name of the running application see [Platform Issue](https://github.com/flutter/devtools/issues/813#issuecomment-512852299). Should this be part of this issue? It's important because we need a way of fetching the platform for analytics w/o using eval.

Hey Terry, this change landed awhile ago [here](https://dart-review.googlesource.com/c/sdk/+/111361). There's now an `operatingSystem` property in the `VM` object response that you can check for the OS version.

**Comment by bkonyi** [comment]
As of [this CL](https://dart-review.googlesource.com/c/sdk/+/112265) DevTools should no longer need to use any private RPCs.
