### ISSUE TITLE
can't handle the emulato

### ISSUE THREAD

**Issue by antogalli** [flutter/devtools#7094]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.28.2
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.2.0
Flutter Version: 3.16.0 / stable
Framework / Engine: db7ef5bf9f / 74d16627b9

**Comment by kenzieschmoll** [comment]
Are you experiencing an issue with DevTools? Please describe your issue and provide repo steps, if so. Thanks.
