### ISSUE TITLE
[Memory] Instance view - hide expanding arrows when there is nothing to expand.

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#710]
Right now we show expanding arrows for empty lists. The arrows should be removed in this case
<img width="280" alt="Screen Shot 2019-06-05 at 2 48 30 PM" src="https://user-images.githubusercontent.com/43759233/58993084-5f4ee080-87a1-11e9-80ac-a8dca75826bb.png">

**Comment by kenzieschmoll** [comment]
this is still happening - the expansion arrows are present when there is nothing to expand:
![memory-arrows](https://user-images.githubusercontent.com/43759233/107406085-e26b2280-6abc-11eb-933e-312811899556.gif)

**Comment by terrylucas** [comment]
Fixed
