### ISSUE TITLE
FabFlutter

### ISSUE THREAD

**Issue by konan-fabrice** [flutter/devtools#7117]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.28.5
**Connected Device**:
CPU / OS: x64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.2.5
Flutter Version: 3.16.8 / stable
Framework / Engine: 67457e669f / 6e2ea58a5c

**Comment by kenzieschmoll** [comment]
Are you experiencing an issue with DevTools? If so feel free to re-open and please add a description and repro steps so we can investigate. Thanks!
