### ISSUE TITLE
Reporting error: Failed to parse package:p_trade/main.dart.

### ISSUE THREAD

**Issue by mrahmad97** [flutter/devtools#7124]
Stack trace:
main.dart.js 6165:18    Object.qb
main.dart.js 68188:76   <fn>
main.dart.js 4774:62    bDg.a
main.dart.js 56680:14   bDg.$2
main.dart.js 56674:21   bB2.$1
main.dart.js 5070:19    Object.bCV
main.dart.js 163826:68  ajH.<fn>
main.dart.js 57797:12   ZA.qE
main.dart.js 57183:11   bnX.$0
main.dart.js 4940:40    Object.Mz

<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.28.5
**IDE**: Android-Studio
**Connected Device**:
CPU / OS: x64 (64 bit) android
Connected app type: Flutter native (profile build)
Dart Version: 3.2.6
Flutter Version: 3.16.9 / stable
Framework / Engine: 41456452f2 / f40e976bed

**Comment by kenzieschmoll** [comment]
closing in favor of https://github.com/flutter/devtools/issues/7192
