### ISSUE TITLE
Reporting error: Failed to parse package:toonflix/main.dart.

### ISSUE THREAD

**Issue by juri1135** [flutter/devtools#7128]
When I run with debugging my code, this error message come out.
Failed to parse package:toonflix/main.dart.
another error messages at terminal are reported the middle point in my report.
F5, ctrl+r, push the button of run with debugging I tried pushing all buttons.
My emulator is running well but my widget inspector doesn't it. 
Please help me.

Stack trace:
main.dart.js 6162:18    Object.qb
main.dart.js 68152:76   <fn>
main.dart.js 4771:62    bDe.a
main.dart.js 56662:14   bDe.$2
main.dart.js 56656:21   bB0.$1
main.dart.js 5067:19    Object.bCT
main.dart.js 163777:68  ajG.<fn>
main.dart.js 57779:12   ZA.qF
main.dart.js 57165:11   bnV.$0
main.dart.js 4937:40    Object.MA

These are my error messages at terminal.

Error: Dart library 'dart:ui' is not available on this platform.
import 'dart:ui' as ui show Canvas, Paint, Path, lerpDouble;  

/C:/flutter/packages/flutter/lib/src/material/app.dart:5:8: Error: Dart library 'dart:ui' is not available on this platform.
import 'dart:ui' as ui;
       ^
/C:/flutter/packages/flutter/lib/src/material/app_bar_theme.dart:5:8: Error: Dart library 'dart:ui' is not available on this platform.
import 'dart:ui' show lerpDouble;
       ^
/C:/flutter/packages/flutter/lib/src/material/arc.dart:6:8: Error: Dart library 'dart:ui' is not available on this platform.
import 'dart:ui' show lerpDouble;
       ^
/C:/flutter/packages/flutter/lib/src/material/badge_theme.dart:5:8:
 Error: Dart library 'dart:ui' is not available on this platform.  
import 'dart:ui' show lerpDouble;
       ^
/C:/flutter/packages/flutter/lib/src/material/banner_theme.dart:5:8: Error: Dart library 'dart:ui' is not available on this platform. 
import 'dart:ui' show lerpDouble;
       ^
/C:/flutter/packages/flutter/lib/src/material/bottom_app_bar_theme.dart:5:8: Error: Dart library 'dart:ui' is not available on this platform.
import 'dart:ui' show lerpDouble;
       ^
/C:/flutter/packages/flutter/lib/src/material/bottom_navigation_bar_theme.dart:5:8: Error: Dart library 'dart:ui' is not available on this platform.
import 'dart:ui' show lerpDouble;
       ^
/C:/flutter/packages/flutter/lib/src/material/bottom_sheet.dart:5:8: Error: Dart library 'dart:ui' is not available on this platform. 
import 'dart:ui' show lerpDouble;
       ^
___
**DevTools version**: 2.28.4
**IDE**: VSCode
**Connected Device**:
CPU / OS: x64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.2.3
Flutter Version: 3.16.5 / stable
Framework / Engine: 78666c8dc5 / 3f3e560236

**Comment by kenzieschmoll** [comment]
closing in favor of https://github.com/flutter/devtools/issues/7192
