### ISSUE TITLE
I cant able to get the response , If the response is a audio format the was gray color 

### ISSUE THREAD

**Issue by sufiyanas** [flutter/devtools#7150]
<img width="1421" alt="Screenshot 2024-02-02 at 9 35 31 PM" src="https://github.com/flutter/devtools/assets/76591972/e75e1c17-724f-4105-a5e9-e11c65832004">
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.28.4
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.2.3
Flutter Version: 3.16.3 / stable
Framework / Engine: b0366e0a3f / 54a7145303

**Comment by kenzieschmoll** [comment]
Looks like you are on a old version of the Flutter SDK. Please try upgrading to the latest stable to see if you are still experiencing this issue, because it should be fixed on the latest Flutter. Feel free to re-open this issue if you are still seeing this problem.
