### ISSUE TITLE
dart devtools --appSizeBase= opens 'appsize' but should open 'app-size'

### ISSUE THREAD

**Issue by dkbast** [flutter/devtools#7173]
Opening the devtools via the cli passing an appsize file via `--appSizeBase` does not open the devtools tab for the size - there seems to be a typo internally as it opens the devtools with this url:

`http://127.0.0.1:9100/appsize?appSizeBase=<path>/macos-code-size-analysis_02.json`

Going to home and then to the app size tab results in a working view:

`http://127.0.0.1:9100/app-size?appSizeBase=<path>/macos-code-size-analysis_02.json`

Reproduce:

```bash
flutter create example
cd example
flutter build macos --analyze-size      
dart devtools --appSizeBase=<path to file>
```

Found on:
Dart SDK version: 3.2.5 (stable) (Tue Jan 16 15:02:13 2024 +0000) on "macos_arm64"

flutter doctor                                                                                   
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.8, on macOS 14.2.1 23C71 darwin-arm64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.85.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

**Comment by kenzieschmoll** [comment]
Thanks for reporting! Looks like this was fixed last week: https://github.com/dart-lang/sdk/commit/cc309f25d5d9cf6e402368f3b74b7fe86a8eedb5. Closing since this has already been addressed.
