### ISSUE TITLE
the network doesn't show up most of the time after the flutter update

### ISSUE THREAD

**Issue by ZainAhmed17** [flutter/devtools#7202]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.28.5
**IDE**: VSCode
**Connected Device**:
CPU / OS: x64 (64 bit) ios
Connected app type: Flutter native (debug build)
Dart Version: 3.2.6
Flutter Version: 3.16.9 / stable
Framework / Engine: 41456452f2 / f40e976bed

**Comment by kenzieschmoll** [comment]
Do you have a consistent repro that you could provide? This would help us to debug the issue and provide a fix. Thanks.
