### ISSUE TITLE
Extension does not show up as a tab in DevTools.

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#7250]
Steps to repro:

1. Start [app_that_uses_foo] (https://github.com/flutter/devtools/tree/master/packages/devtools_extensions/example/app_that_uses_foo) for mac: open it in VSCode, click 'add support for mac' and then click button 'Run and Debug' for configuration `app_that_uses_foo'
2. Run DevTools for web and connect to app_that_uses_foo
3. Find there is no tab 'Foo' in devtools, while it is expected to be here

<img width="918" alt="Screenshot 2024-02-21 at 8 31 02 AM" src="https://github.com/flutter/devtools/assets/12115586/cfffb44e-a0b0-4632-b1ba-c7ddaea5c514">

**Comment by polina-c** [comment]
@kenzieschmoll

**Comment by polina-c** [comment]
Created PR to add steps to doc: https://github.com/flutter/devtools/pull/7251

**Comment by kenzieschmoll** [comment]
@polina-c I see you are running DevTools in debug mode. Extensions will not load in debug mode because the DevTools server is not available.

**Comment by polina-c** [comment]
Tried `flutter run -d chrome --release`. Tab is still not here :(

**Comment by kenzieschmoll** [comment]
You have to run DevTools with the server: `devtools_tool serve`. You can actually just open DevTools from VS code (not running locally from source) and you'll see the extension tab there.

**Comment by polina-c** [comment]
Yes, I could find foo in flutter panel and when run with `devtools_tool serve .`

<img width="290" alt="Screenshot 2024-02-21 at 12 14 24 PM" src="https://github.com/flutter/devtools/assets/12115586/a516c968-8b73-4b3b-b218-7822df2a0c17">
