### ISSUE TITLE
Text in inspector settings menu is not aligned

### ISSUE THREAD

**Issue by elliette** [flutter/devtools#7295]
![Screenshot 2024-02-01 at 10 40 16 AM](https://github.com/flutter/devtools/assets/21270878/c4f4aeeb-38ae-4e06-8820-b326ba53dcf5)

**Comment by Amitkumarkoli** [comment]
can u explain more about this issue.

**Comment by kenzieschmoll** [comment]
The description text (light gray) is not aligned vertically with the setting text "Enable hover inspection". These two text fields should share a text baseline.

**Comment by Amitkumarkoli** [comment]
ok . btw I am beginner at this but let's see ...
