### ISSUE TITLE
Missing key isPubliclyHosted 

### ISSUE THREAD

**Issue by jaumard** [flutter/devtools#7306]
Hello,

Since few time now I'm not able to use devtools at all, I'm getting an error each time IntelliJ is opening the dev tools (embedded or web page). 

Here is the error:
<img width="411" alt="Capture d’écran 2024-03-04 à 08 01 26" src="https://github.com/flutter/devtools/assets/2970449/650c8453-af42-4017-a526-a993906c215b">

I have a devtools_options.yaml containing nothing:

```yaml
extensions:

```

Not sure what I can do about this? Any ideas? 

Context:
```
Flutter (Channel stable, 3.19.2, on macOS 14.2.1 23C71 darwin-arm64, locale fr-CH)
    • Flutter version 3.19.2 on channel stable at /Users/jaumard/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (5 days ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
```

**Comment by kenzieschmoll** [comment]
Can you please try to open DevTools in the browser and see if you are still seeing this issue? Another user is experiencing this in VS code (https://github.com/flutter/devtools/issues/7248), but only in the embedded version and not in the browser.

**Comment by jaumard** [comment]
When I click on Open Devtools here it open it into the web browser, but I still have the same issue in the browser. 
<img width="556" alt="Capture d’écran 2024-03-04 à 19 19 33" src="https://github.com/flutter/devtools/assets/2970449/dbf2c86f-9963-4199-b6ce-66cd6d8d4099">

I there another way to launch devtools on the browser I can try?

**Comment by jaumard** [comment]
Just tried and it indeed work correctly this way, no more errors :)

**Comment by jaumard** [comment]
Sure here is what I have setup in my IDE:

<img width="709" alt="Capture d’écran 2024-03-04 à 19 43 11" src="https://github.com/flutter/devtools/assets/2970449/9ddab5e0-99f3-418e-bc75-8e57f3c83831">
<img width="698" alt="Capture d’écran 2024-03-04 à 19 43 04" src="https://github.com/flutter/devtools/assets/2970449/29e5561c-6afb-42d1-a2fe-3766b2b3f836">

To me looks good

**Comment by kenzieschmoll** [comment]
Thanks. And how did you run your app from CLI? Just `flutter run ...`? Also, does `which flutter` point to the same flutter SDK that your IDE uses?

**Comment by jaumard** [comment]
I have only one flutter installed on my machine, it point to same instance yes.
My command is 

`flutter run lib/main_development.dart --flavor=development`

Where flutter:

```bash
whereis flutter                                           
flutter: /Users/jaumard/flutter/bin/flutter
```

**Comment by kenzieschmoll** [comment]
Can you try to restart your IDE using "Invalidate caches and Restart"? And then see if the issue reproduces in IntelliJ?

**Comment by jaumard** [comment]
Look like it did the trick it now works perfectly in the IDE :) thanks for the help!

**Comment by kenzieschmoll** [comment]
@DanTup must have been what you thought - that the DevTools server was running from an older Dart SDK and the compiled app was running with a newer version after an upgrade.

@jaumard thanks for the help getting to the bottom of this!

**Comment by DanTup** [comment]
Yeah, that may add up for the VS Code report too (https://github.com/flutter/devtools/issues/7248#issuecomment-1977402722). We do try to detect and prompt for this in VS Code, but if we see this come up again we could consider trying to improve this (or perhaps having DevTools periodically ping the server and check the versions match).
