### ISSUE TITLE
Analyzer is supposed to run with `--no-fatal-infos` in flutter/tests

### ISSUE THREAD

**Issue by goderbauer** [flutter/devtools#7318]
Currently, the devtools code base is analyzed with `dart analyze --fatal-infos` when running as part of the https://github.com/flutter/tests test suite, while the rules for that repository request that the analyzer is run with `--no-fatal-infos`, see https://github.com/flutter/tests?tab=readme-ov-file#adding-more-tests:

> The tests must pass even if there are analysis 'info' level issues in the code. Generally, this means that if the test performs static analysis, it does so ignoring info level items (i.e., flutter analyze --no-fatal-infos).

Could the devtools analyzer invocation from https://github.com/flutter/tests be adjusted to comply with those rules?

**Comment by kenzieschmoll** [comment]
This is easy to fix. Once fixed, we need to update the DevTools hash used for the Flutter customer test registry.
