### ISSUE TITLE
Dev Tool issue

### ISSUE THREAD

**Issue by Aakash574** [flutter/devtools#7319]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.28.5
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.2.6
Flutter Version: 3.16.9 / stable
Framework / Engine: 41456452f2 / f40e976bed

**Comment by kenzieschmoll** [comment]
- Without additional information, we cannot debug this issue. Please re-open if you can provide a description of your issue and repro steps. Thanks.
