### ISSUE TITLE
mobile app

### ISSUE THREAD

**Issue by Delarime** [flutter/devtools#7339]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.31.1
**IDE**: VSCode
**Connected Device**:
CPU / OS: Web windows
Connected app type: Flutter web (debug build)
Dart Version: 3.3.1
Flutter Version: 3.19.3 / stable
Framework / Engine: ba39319843 / 2e4ba9c6fb

**Comment by kenzieschmoll** [comment]
Without additional information, we cannot debug this issue. Please re-open if you can provide a description of your issue and repro steps. Thanks.
