### ISSUE TITLE
"package_config.json not found" error when connecting to Dart web app

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#7340]
While investigating https://github.com/Dart-Code/Dart-Code/issues/5027 I tried connecting DevTools to a web app to see if I could repro the issue outside of VS Code. When I did, I got this error printed:

```
PS C:\Dev> dart devtools
Serving DevTools at http://127.0.0.1:9100.

          Hit ctrl-c to terminate the server.
package_config.json not found at: "file:///C:/Dev/Test%20Projects/dartcode_5027/web/main.dart/.dart_tool/package_config.json"
package_config.json not found at: "file:///C:/Dev/Test%20Projects/dartcode_5027/web/main.dart/.dart_tool/package_config.json"
```

Maybe similar to https://github.com/flutter/devtools/pull/6644?

**Comment by kenzieschmoll** [comment]
This may be related to DevTools extension detection.

**Comment by elliette** [comment]
Just trying reproducing and I'm not seeing this, so closing this issue out. Feel free to reopen if you still are encountering this.

**Comment by DanTup** [comment]
This is what the `rootLib` looks like in the VM Service traffic:

```
"rootLib": {
	"type": "@Library",
	"id": "org-dartlang-app:///web/main.dart",
	"name": "org-dartlang-app:///web/main.dart",
	"uri": "org-dartlang-app:///web/main.dart"
},
```

**Comment by kenzieschmoll** [comment]
I just tried to repro this following the steps you provided and could not repro. Maybe this only happens on windows? I have seen this "package_config.json" warning come up in other circumstances, but those have been legitimate cases where a package config was not present in the directory where there was a pubspec.yaml. This logic may have changed recently with the pub workspaces support.

Are you still able to repro this issue @DanTup? and does it only occur when connecting to a Dart web app?
