### ISSUE TITLE
we should have a keyboard shortcuts popup dialog

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#735]
We should have a way to see common keyboard shortcuts in devtools. In DartPad, this is done w/ a small keyboard icon; clicking on it shows a model dialog of available keyboard shortcuts.

<img width="54" alt="Screen Shot 2019-06-19 at 11 40 21 AM" src="https://user-images.githubusercontent.com/1269969/59791531-2fb2d480-9287-11e9-9554-c6273524f042.png">

**Comment by kenzieschmoll** [comment]
closing in favor of https://github.com/flutter/devtools/issues/735. Dupe.
