### ISSUE TITLE
First Time DevTools lands me in a confusing page

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/devtools#738]
VSC encouraged me to launch dev-tools, which is fine.  But then once it did, it landed me on a confusing page:

<img width="1524" alt="Screen Shot 2019-06-19 at 8 49 28 PM" src="https://user-images.githubusercontent.com/11857803/59863690-1159e100-933a-11e9-9885-2f3caa54b38b.png">

**Comment by kenzieschmoll** [comment]
Adding a [landing page](https://github.com/flutter/devtools/issues/433) could help here. @devoncarew

**Comment by kenzieschmoll** [comment]
We have a landing page and we also have a video tutorial linked from each page that gives a tutorial.
