### ISSUE TITLE
name

### ISSUE THREAD

**Issue by tungautomation** [flutter/devtools#7398]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.28.5
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.2.4
Flutter Version: 3.16.7 / stable
Framework / Engine: ef1af02aea / 4a585b7929

**Comment by kenzieschmoll** [comment]
Without additional information, we cannot debug this issue. Please re-open if you can provide a description of your issue and repro steps. Thanks.
