### ISSUE TITLE
`flutter pub global run devtools` blocks other `flutter` commands

### ISSUE THREAD

**Issue by liyuqian** [flutter/devtools#740]
I was following https://flutter.github.io/devtools/cli and `flutter pub global run devtools` blocked `flutter run --observatory-port=9200` from running. Maybe we should remove `flutter pub global run devtools` from the instruction and only suggest `pub global run devtools`.

**Comment by liyuqian** [comment]
CC @kenzieschmoll

**Comment by devoncarew** [comment]
I think that some portion of the `flutter pub` commands should release the flutter tools lock after they start. Perhaps all of them? Otherwise long running tasks, like `flutter pub global run`, will block other invocations of the tool.

cc @jonahwilliams
