### ISSUE TITLE
Null exception from `tracing_pane_controller.dart`

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#7428]
this happened after interacting with the memory screen tracing view, switching to the home screen, and then disconnecting from the app.

![Screenshot 2024-03-22 at 10 57 35 AM](https://github.com/flutter/devtools/assets/43759233/485eb9c0-4660-46cb-b2c2-f83e0ce11411)

**Comment by polina-c** [comment]
Tested there is no failure.
