### ISSUE TITLE
Sometimes, nested JSON Response not opening when i click on the right arrow icon

### ISSUE THREAD

**Issue by santhosh-inf** [flutter/devtools#7435]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.31.1
**IDE**: VSCode
**Connected Device**:
CPU / OS: x64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.3.0
Flutter Version: 3.19.2 / stable
Framework / Engine: 7482962148 / 04817c99c9

**Comment by kenzieschmoll** [comment]
@CoderDake is this a duplicate of an issue you've already resolved?

**Comment by elliette** [comment]
Confirmed that this is now fixed:

![network_panel](https://github.com/user-attachments/assets/cc45b40f-2dc1-4197-b529-7d5df5c17619)
