### ISSUE TITLE
Migrate to new flutter bootstrapping

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#7444]
Warnings we are now seeing during build:
![Screenshot 2024-03-25 at 4 17 49 PM](https://github.com/flutter/devtools/assets/43759233/4dc00303-a1b1-4a42-829f-184909321c5b)

I took a stab at migrating this but it was not as straightforward as I would have hoped.
![Screenshot 2024-03-25 at 4 21 55 PM](https://github.com/flutter/devtools/assets/43759233/c0665b16-6aff-4a9c-8dc1-8a6010c19407)

CC @eyebrowsoffire maybe the warning message can be tweaked to make the migration path more clear?

Bootstrapping changes: https://github.com/flutter/flutter/pull/144434

**Comment by eyebrowsoffire** [comment]
BTW, we are planning for the warnings to link to the documentation once it is finalized. Issue tracking the link in the warning: https://github.com/flutter/flutter/issues/145559

And the issue for documentation for the new bootstrapping in general: https://github.com/flutter/website/issues/10126

I can assist you getting devtools unblocked if you need. The TL;DR is:

* Add a file called `flutter_bootstrap.js` in the `web` directory in your project, next to `index.html`
* Put this in `flutter_bootstrap.js`:
```
{{flutter_js}}
{{flutter_build_config}}
_flutter.loader.load({
  serviceWorkerSettings: {
    serviceWorkerVersion: {{flutter_service_worker_version}},
  },
  config: {
    canvasKitBaseUrl: 'canvaskit/',
  }
});
```
* Get rid of any `flutter.js` script tags in the index.html, and just put the following script tag somewhere:
```
<script src="flutter_bootstrap.js" async></script>
```

If you need help with it, just let me know, I'm happy to help iron out any issues.
