### ISSUE TITLE
Patch release 2.24.1

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#7483]
This release will include the following commits on top of 2.24.0
- [x] https://github.com/flutter/devtools/pull/7475
- [x] https://github.com/flutter/devtools/pull/7480
- [x] https://github.com/flutter/devtools/pull/7478

**Comment by elliette** [comment]
Adding https://github.com/flutter/devtools/pull/7485 as well

**Comment by kenzieschmoll** [comment]
https://github.com/flutter/devtools/pull/7485 did not make it into the SDK since the roll CL including #7485 landed after 5pm PST (https://dart-review.googlesource.com/c/sdk/+/360123).

We will need to perform a cherry pick to get https://github.com/flutter/devtools/pull/7485 into the SDK's next beta release.

**Comment by kenzieschmoll** [comment]
We should also make sure that the version bump to 2.35.0-dev.0 is not included in the cherry-pick 
 (https://github.com/flutter/devtools/commits/master/)

**Comment by kenzieschmoll** [comment]
closing since the CP is tracked here: https://github.com/dart-lang/sdk/issues/55327
