### ISSUE TITLE
Android Studio: I can't switch to Light Mode When I launch Flutter Inspector 

### ISSUE THREAD

**Issue by ImadBouirmane** [flutter/devtools#7506]
Hi 
As I mentioned in the title check the video recorded below:
https://github.com/flutter/devtools/assets/8468212/3bd9984e-5ee6-46a8-a002-8a29a3df6c43
___
**DevTools version**: 2.28.5
**IDE**: Android-Studio
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.3.1
Flutter Version: 3.19.3 / stable
Framework / Engine: ba39319843 / 2e4ba9c6fb

**Comment by polina-c** [comment]
Thanks for reporting!
CC @CoderDake

**Comment by kenzieschmoll** [comment]
I recommend that we remove the setting to toggle theme when in embedded mode. In embedded mode, the DevTools screens should inherit the theme from the IDE. However, due to https://github.com/flutter/flutter-intellij/issues/7319, this is currently broken in IntelliJ.

**Comment by ImadBouirmane** [comment]
@kenzieschmoll Yeah will be good because in VSCode work fine !
