### ISSUE TITLE
flutter error solve 

### ISSUE THREAD

**Issue by kunalparmar5** [flutter/devtools#7566]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.25.0
**Connected Device**:
CPU / OS: ia32 (32 bit) android
Dart Version: 3.1.0
Flutter Version: 3.13.2 / stable
Framework / Engine: ff5b5b5fa6 / b20183e040
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
Without additional information, we cannot debug this issue. Please re-open if you can provide a description of your issue and repro steps. Thanks.

One tip: looks like you are on an outdated version of Flutter - I recommend running flutter upgrade to get the latest on the stable channel.
