### ISSUE TITLE
Find a way to expose the flutter_tools daemon protocol to the devtools app

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#76]
This would enable supporting hot restart and hot reload robustly from the devtools app.

This feature request is similar in spirit to 
https://github.com/flutter/devtools/issues/70

**Comment by jacob314** [comment]
One idea is to expose a way for VM Service clients to register their own service extensions.
These service extensions could be used to expose the flutter_tools daemon protocol, to expose IDE protocols like the analyzer protocol and methods to trigger navigation to specific source locations.

**Comment by devoncarew** [comment]
flutter_tools does expose hot reload to clients via service protocol 'services':

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/vmservice.dart#L149

And the one for 'compileExpression': https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/vmservice.dart#L187

**Comment by jacob314** [comment]
Excellent! I didn't realize this existed.

**Comment by devoncarew** [comment]
It may or may not be quite all there for what we need, but we can flesh it out as necessary. I had wanted to add a simple pub-sub implementation to the vm service layer; this is close, and allows clients to communicate with each other.

**Comment by jacob314** [comment]
It appears it is close but not quite trivial to use. `_registerService` pretty much does the right thing but the registered service has a prefix indicating which client added it. `openSourceLocation` is the example closest to doing what we would want.

**Comment by jacob314** [comment]
https://github.com/jacob314/devtools/pull/new/support_services
Example steel thread adds support for services.

**Comment by kenzieschmoll** [comment]
Hot reload and hot restart are implemented. We listen for `EventKind.kServiceRegistered` events.
Closing this issue as obsolete.
