### ISSUE TITLE
Need an efficient mechanism to compare ObjectRefs.

### ISSUE THREAD

**Issue by terrylucas** [flutter/devtools#766]
Need an efficient mechanism to do identity comparisons on ObjectRefs (Instances, etc.).  Today we use evaluate on an targetid with the expression of 'hashCode' and compare the hashCodes. This is expensive and causes memory to change (lots of temporary objects created).  Need a better solution available in VMService.

**Comment by bkonyi** [comment]
As discussed offline, this probably isn't something we can/would want to do as object IDs are short lived and would be expensive to keep track of for longer periods.
