### ISSUE TITLE
no run

### ISSUE THREAD

**Issue by rraniia** [flutter/devtools#7684]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: Web windows
Dart Version: 2.19.4
Flutter Version: 3.7.7 / stable
Framework / Engine: 2ad6cd72c0 / 1837b5be5f
Connected app type: Flutter web (debug build)

**Comment by kenzieschmoll** [comment]
Without additional information, we cannot debug this issue. Please re-open if you can provide a description of your issue and repro steps. Thanks.

Also, it looks like you are on an old version of Flutter. Please upgrade to the latest stable and your issue may be resolved.
