### ISSUE TITLE
Remove focus ring when clicking on toggle buttons

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#77]
Unless users are trying to keyboard navigate it would be nice to not display it particularly if the user just clicked on a button and didn't try to do anything explicitly toggling focus.
For example, see:
https://hackernoon.com/removing-that-ugly-focus-ring-and-keeping-it-too-6c8727fefcd2

**Comment by kenzieschmoll** [comment]
this only applies to the dart:html app, which is now deleted
