### ISSUE TITLE
Improve the overall logging experience.

### ISSUE THREAD

**Issue by CoderDake** [flutter/devtools#7703]
The current logging experience needs an overhaul to meet basic expectations around logging needs. This issue will track the overall  progress towards a new logging experience which we are referring to as "logging V2". For now it will be hidden behind a DevTools feature flag.

Bugs that should be resolved as part of creating the logging v2 experience:
- [x] https://github.com/flutter/devtools/issues/1108 
- [x] https://github.com/flutter/devtools/issues/2188
- [x] https://github.com/flutter/devtools/issues/6796
- [x] https://github.com/flutter/devtools/issues/7575
- [x] https://github.com/flutter/devtools/issues/5182
- [x] https://github.com/flutter/devtools/issues/8426
- [x] https://github.com/flutter/devtools/issues/6798
- [x] https://github.com/flutter/devtools/issues/6800
- [x] https://github.com/flutter/devtools/issues/8492

**Comment by bleonard252** [comment]
This is the part of DevTools I use the most, so I'm definitely looking forward to this.

**Comment by CoderDake** [comment]
<3

**Comment by CoderDake** [comment]
:salute:
