### ISSUE TITLE
Bad IDE embedded experience for the Network Screen

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#7725]
This should determine the split axis based on the view's aspect ratio like the inspector does. The column widths and search bar size should also be adjusted.

![Screenshot 2024-05-08 at 3 19 29 PM](https://github.com/flutter/devtools/assets/43759233/10cdeeae-f301-42ea-aebf-7faa45f17c76)

**Comment by Sten435** [comment]
@kenzieschmoll They should add resizable columns, that would help allot. I don't know why such a popular framework does not have such a wildly used feature...
