### ISSUE TITLE
Unable to connect to VM service

### ISSUE THREAD

**Issue by jay-web** [flutter/devtools#773]
Hi, when I start the dev tools from the android studio, then it shows the error on browser =  Unable to connect to VM service at ws ://localhost:55961/ws. I tried to change the port, but the problem remains the same.

**Comment by stevemessick** [comment]
@jacob314

**Comment by kenzieschmoll** [comment]
What version of the flutter-intelliJ plugin are you using? What version of DevTools? Try upgrading both (go to the plugins menu in Android Studio to see if there is an update and run `pub global activate devtools` to upgrade your global devtools version). Then see if you are still having the issue. Thanks.

**Comment by jay-web** [comment]
Hi, I updated the plugins as you suggested and it worked. Thanks for your help.
