### ISSUE TITLE
_SendNotifcation printing out JSON to console during normal DevTools runs

### ISSUE THREAD

**Issue by terrylucas** [flutter/devtools#774]
Noticed that integration tests prints out the JSON (e.g., _sendNotification) removing those prints causes timing problems with the integration tests. These prints show up in the console during normal DevTools runs and shouldn't, but removing the prints causes timing problems. If the prints are necessary it should be a test only function not executed normally.  Added a TODO but will file an issue on this too.

**Comment by DanTup** [comment]
The reason removing the `prints` cause things to fail is that it's the `console.log` events that the testing classes listen to (it's not just debug printing):

https://github.com/flutter/devtools/blob/c5df142d486cab2fd9efabd2cd8d6f65ccea3a32/packages/devtools/test/integration_tests/integration.dart#L121-L122

The tests have to wait for the first notification (`app.devToolsReady`) to know when things are set up, so I think there are two options:

1. Something like a querystring variable that enables the printing in the testing model
2. Always send `app.devToolsReady`, but then require the testing framework to send an event to enable all *other* notifications

2 is probably simplest, though will leave the first event printing to the console, but we might be able to switch from `console.log` to `console.info` so it's not visible with the default filters. I'll take a look.

**Comment by DanTup** [comment]
Actually, as far as I can tell the only notification sent is `app.devToolsReady`. @terrylucas are you seeing other things written to the console (when not running tests) or just this?

**Comment by DanTup** [comment]
@terrylucas ping! See question above - is there anything showing up except `app.devToolsReady` you think shouldn't be there? It might not be worth changing how this works if it's just that one.

**Comment by DanTup** [comment]
This code was all in the dart:html version of the app and has now been removed.
