### ISSUE TITLE
[deeplink] Need more instruments to collect anonymous user metrics

### ISSUE THREAD

**Issue by chunhtai** [flutter/devtools#7760]
Things to gather

1. how many users loaded projects
2. how many users ended up with a domain in Android and iOS
      * need to be able to differentiate between no domain vs error getting domains
3. Dashboard usage
      * how many users had errors
      * how many users clicked into detail views
      * how many users clicked recheck all

**Comment by kenzieschmoll** [comment]
We have a DevTools survey that we will be running hopefully in about a month. We can add questions specific to the Deep Links screen there. You can also look into the JIT survey framework provided by uniified_analytics. Now that DevTools is using the UA package, we may be able to run a targeted survey to users who are using the Deep links screen embedded in the IDE.
