### ISSUE TITLE
ebriks--cas

### ISSUE THREAD

**Issue by ccsnpvt** [flutter/devtools#7763]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.31.1
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.3.3
Flutter Version: 3.19.5 / stable
Framework / Engine: 300451adae / e76c956498

**Comment by CoderDake** [comment]
@ccsnpvt Could you please proved some more context about the issue you are facing?
