### ISSUE TITLE
Disable raster stats feature in the Performance page

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#7788]
@jonahwilliams @matanlurey before I move forward with this, I want to confirm from the Engine side of things - does this feature provide any useful data for Skia? We have already disabled this feature for Impeller, but we continue to get issue reports like https://github.com/flutter/devtools/issues/6992

If this feature is completely inaccurate / misleading for Skia, then it may be better to disable the tool entirely instead of trying to fix these issues.

**Comment by jonahwilliams** [comment]
This feature essentially measures the CPU side of certain operations, but without any insight into the operations being performed, caching, allocation, other operations that make things non-repeatable. The granularity is too coarse and we should point folks towards native profiles (for understanding the engine costs) and graphics profilers (for understanding GPU costs).
