### ISSUE TITLE
Flutter Google Maps

### ISSUE THREAD

**Issue by wireearp** [flutter/devtools#7789]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.34.3
**IDE**: Android-Studio
**Connected Device**:
CPU / OS: x64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.4.0
Flutter Version: 3.22.0 / stable
Framework / Engine: 5dcb86f68f / f6344b75dc

**Comment by CoderDake** [comment]
@wireearp could you please provide some more information about the issue you are encountering?
