### ISSUE TITLE
[web] Blue location arrow is not present when paused in a package colon location

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#780]
This isn't an issue with Flutter Native.

To reproduce simply set a breakpoint in a package colon location and hit said breakpoint.

For example run the gallery example and set a breakpoint here:
https://github.com/flutter/flutter_web/blob/master/examples/gallery/lib/demo/material/material_button_demo.dart#L35

**Comment by jacob314** [comment]
I suspect the issue has to do with how flutter web is reporting the package: uri. Likely it is subtly inconsistently displayed in the list of source files and the stack trace.

**Comment by grouma** [comment]
cc @alan-knight

**Comment by grouma** [comment]
Closing in favor of https://github.com/dart-lang/webdev/issues/505
