### ISSUE TITLE
Hi. Broken link to SDK on GitHub in CONTRIBUTING.md

### ISSUE THREAD

**Issue by gl-yziquel** [flutter/devtools#7802]
Link not giving access to github sources for the SDK: https://docs.flutter.dev/get-started/install/macos#downloading-straight-from-github-instead-of-using-an-archive

Location of link: https://github.com/flutter/devtools/blob/master/CONTRIBUTING.md?plain=1#L48

**Comment by nickf2k** [comment]
seem like this issue was fixed, right?
I see it was changed to https://github.com/flutter/flutter/blob/main/docs/contributing/Setting-up-the-Framework-development-environment.md

**Comment by parlough** [comment]
Looks like it was @nickf2k! Thanks for verifying the fix :)

**Comment by parlough** [comment]
Fixed by https://github.com/flutter/devtools/commit/98290c26d696d34393d77a7903cade956f208fb9
