### ISSUE TITLE
Analytics permission dialog should remember a user's selection

### ISSUE THREAD

**Issue by zhengger** [flutter/devtools#782]
Anytime I open the DevTool to debug my program it pops out and I had to disable it manually again and again...
So annoying...
![image](https://user-images.githubusercontent.com/2143234/60919528-8df03780-a2c8-11e9-9674-fd08ec6ebd8a.png)

**Comment by DanTup** [comment]
This is likely due to a new temp folder being being used for each run:

https://github.com/dart-lang/browser_launcher/blob/master/lib/src/chrome.dart#L69

@terrylucas FYI!

**Comment by jacob314** [comment]
We should use the devtools_server to make sure we track the opt in setting on the user's local machine like flutter_tools does.

**Comment by kenzieschmoll** [comment]
This issue was originally filed against the html app and is fixed in the flutter app. @grouma please re-open if I am mistaken.
