### ISSUE TITLE
todo_flutter

### ISSUE THREAD

**Issue by abcdefghijklmn1234** [flutter/devtools#7828]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.31.1
**Connected Device**:
CPU / OS: Web windows
Connected app type: Flutter web (debug build)
Dart Version: 3.3.4
Flutter Version: 3.19.6 / stable
Framework / Engine: 54e66469a9 / c4cd48e186

**Comment by kenzieschmoll** [comment]
Without additional information, we cannot debug this issue. Please re-open if you can provide a description of your issue and repro steps. Thanks.
