### ISSUE TITLE
Report MeroSchool

### ISSUE THREAD

**Issue by MirajThapa** [flutter/devtools#7830]
<-- Please describe your problem here. Be sure to include repro steps. -->

App size can be reduced through mainly assests and followed by other components.
UI can be rendered properly as it takes much time to load and it skips the frame. Jank is high for new frame type in UI.
Memory dispose of unwanted objects could be done.
Network is on time and it works fine.
Widget are properly maintained.

___
**DevTools version**: 2.31.1
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.3.4
Flutter Version: 3.19.6 / stable
Framework / Engine: 54e66469a9 / c4cd48e186

**Comment by kenzieschmoll** [comment]
Can you clarify whether you are experiencing an issue with DevTools? Or is this general feedback based on looking at the code for the DevTools repo?
