### ISSUE TITLE
add the ability to filter and search in tables

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#785]
I’d like to be able to filter tables easily. For example, int the memory view, I’d like a quick way to look for instances if the class `’Title’`.

<img width="556" alt="Screen Shot 2019-07-10 at 8 39 26 AM" src="https://user-images.githubusercontent.com/1269969/60983684-403af580-a2ef-11e9-8838-095008ea8d4a.png">

**Comment by terrylucas** [comment]
CTRL + f  or clicking on the search icon (magnifying glass) will bring up auto-complete list typing in Title will display classes that contain Title.

I was hoping this was easier and more robust than hacing to filter.  Filtering to me should be for selecting packages not classes.

**Comment by devoncarew** [comment]
Ah, cool! We may want some affordance on the table to indicate that search (or filtering) is possible.

**Comment by terrylucas** [comment]
Good point the search button maybe too far away - maybe it should be on the classes table.  Tao will be reviewing the memory UI next week.  I'll mention this as well.

**Comment by kenzieschmoll** [comment]
We should add this functionality to the Table class so that it will apply to all the tables in DevTools (memory page, timeline page, performance page, logging page).

**Comment by maks** [comment]
@terrylucas how does that work for the table used in the logging view? Being able to filter on the `Kind` column is a pretty important use case I think, eg. I want to filter out all the flutter.frame logs or I just want to see lines with my own specific tag.

**Comment by nemoryoliver** [comment]
I wish the Dart Team will add a filter to the Logging soon. It would be really helpful.

**Comment by GitHubMurt** [comment]
Please don't scroll down log list automatically I CANT FIND my logs, its so irritating.

**Comment by OrenLeung** [comment]
I will be a pretty useful feature to search my flame chart for a particular widget.

**Comment by kenzieschmoll** [comment]
this functionality has been added. See https://github.com/flutter/devtools/pull/2493 for how this was added to the logging view. Search and filter have also been added to the network profiler.
