### ISSUE TITLE
In debug mode when i open devtools and select widget mode and select widget on screen ... don't open widget file location

### ISSUE THREAD

**Issue by hanyyy5** [flutter/devtools#7877]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.31.1
**IDE**: Android-Studio
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.3.4
Flutter Version: 3.19.6 / stable
Framework / Engine: 54e66469a9 / c4cd48e186

**Comment by kenzieschmoll** [comment]
Can you please upgrade to the latest version of Flutter stable and see if this reproduces? Also be sure you have the most up to date version of the Dart and Flutter plugins in Android studio.
CC @helin24

**Comment by hanyyy5** [comment]
Thank you for your reply…… I have upgraded Android Studio to the latest version and the problem has been solved.
