### ISSUE TITLE
wyuuu

### ISSUE THREAD

**Issue by otgooJS** [flutter/devtools#7881]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.34.3
**Connected Device**:
CPU / OS: Web windows
Connected app type: Flutter web (debug build)
Dart Version: 3.4.1
Flutter Version: 3.22.1 / stable
Framework / Engine: a14f74ff3a / 55eae6864b

**Comment by parlough** [comment]
Hey @otgooJS, thanks for the issue!

Would you mind providing more details on the issue you faced or changes you'd like to see?
