### ISSUE TITLE
flutter rust bridge

### ISSUE THREAD

**Issue by girrel** [flutter/devtools#7889]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.36.0
**Connected Device**:
CPU / OS: Web windows
Connected app type: Flutter web (debug build)
Dart Version: 3.5.0-214.0.dev
Flutter Version: 3.23.0-13.0.pre.80 / master
Framework / Engine: 5e448f4ce5 / ea72558be7

**Comment by kenzieschmoll** [comment]
Are you experiencing an issue with DevTools? If so feel free to re-open and please add a description and repro steps so we can investigate. Thanks!
