### ISSUE TITLE
Analytics error in console

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#789]
Prints to console on connecting devtools to a Profile Mode app.
```
NoSuchMethodError: invalid member on null: 'valueAsString'
package:devtools/src/ui/analytics.dart 308:16  computeUserApplicationCustomGTagData
dart:sdk_internal 25277:9                      <fn>
```

Evals do not work in profile mode. Adding `&& !isProfile` to the check on line 295 fixes this, but I'm not sure if that has any implication on analytics. Terry, I'll defer to you here to decide if anything else needs to be done besides adding a check for `!isProfile`.
@terrylucas

**Comment by terrylucas** [comment]
However, I think it would be nice if we could compute this without an eval especially since profiling a profile build app is a common scenario.  I'll add an issue https://github.com/flutter/devtools/issues/813
