### ISSUE TITLE
Support light and dark themes

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#79]
We should start supporting both light and dark themes for all our UI sooner rather than later so it is less work to refactor later.
VS Code and Android Studio users tend to use a dark theme so having a dark theme will make the devtool tool feel more consistent.

**Comment by jacob314** [comment]
https://github.com/StylishThemes/GitHub-Dark
looks like a reasonable place to start.

**Comment by jacob314** [comment]
It would be fine to only support switching themes on app start. For example with a query parameter.
e.g.
?theme=dark

**Comment by jacob314** [comment]
I'll take a stab at adding the dark theme as an option.

**Comment by kenzieschmoll** [comment]
Dark theme being tracked here: https://github.com/flutter/devtools/issues/418.
