### ISSUE TITLE
Failed to extract `devtools_shared-10.0.0.tar.gz`: Invalid tar entry: ..

### ISSUE THREAD

**Issue by lijy91** [flutter/devtools#7925]
When I install `webdev` I get this error

```log
~ dart pub global activate webdev          
Downloading packages... . (1.4s)
Failed to extract `/private/var/folders/ns/flssk9351x9350ygdscdc66c0000gp/T/pub_I2YiF2/devtools_shared-10.0.0.tar.gz`: Invalid tar entry: ..
```

**Comment by gmpassos** [comment]
FYI: @kevmoo @mit-mit 

This is breaking any CI that uses `webdev`

**Comment by gmpassos** [comment]
It seems that 'devtools_app_shared: ^0.2.0' also has this issue (not being analyzed at pub.dev)

**Comment by mit-mit** [comment]
This is failing due to an regression in `pub`: https://github.com/dart-lang/pub/issues/4305

**Comment by mit-mit** [comment]
To stop the CI failures I've gone ahead and retracted these three package versions:
https://pub.dev/packages/devtools_extensions/versions/0.2.0
https://pub.dev/packages/devtools_app_shared/versions/0.2.0
https://pub.dev/packages/devtools_shared/versions/10.0.0

**Comment by mit-mit** [comment]
@kenzieschmoll this regression only impacts the Dart main and dev channels. So it should be safe to go ahead and publish these again using a stable Dart/Flutter SDK.

**Comment by kenzieschmoll** [comment]
New versions of the DevTools packages have been published, so this issue should be resolved.
