### ISSUE TITLE
Launching lib/main.dart on macOS in debug mode... --- xcodebuild: WARNING: Using the first of multiple matching destinations: { platform:macOS, arch:arm64, id:00006020-000E31A40E33C01E, name:My Mac } { platform:macOS, arch:x86_64, id:00006020-000E31A40E33C01E, name:My Mac } ld: warning: ignoring duplicate libraries: '-lc++' ld: warning: ignoring duplicate libraries: '-lc++' ld: warning: ignoring duplicate libraries: '-lc++' ld: warning: ignoring duplicate libraries: '-lc++'

### ISSUE THREAD

**Issue by tomus007** [flutter/devtools#7930]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.31.1
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) macos
Connected app type: Flutter native (debug build)
Dart Version: 3.3.3
Flutter Version: 3.19.5 / stable
Framework / Engine: 300451adae / e76c956498

**Comment by kenzieschmoll** [comment]
This doesn't appear to be an issue with Flutter DevTools, but rather with your Flutter app. If you are experiencing issues with DevTools itself, please feel free to open another issue with more details. Thanks!
