### ISSUE TITLE
Timeline not working

### ISSUE THREAD

**Issue by wangying3426** [flutter/devtools#795]
Timeline not working, seems websocket not send event normally.

![Screen Shot 2019-07-14 at 11 49 20 AM](https://user-images.githubusercontent.com/4476512/61179097-19056080-a62e-11e9-99ee-d0f100bd6c4d.png)

![Screen Shot 2019-07-14 at 11 51 58 AM](https://user-images.githubusercontent.com/4476512/61179084-e6f3fe80-a62d-11e9-98c5-756a4f387488.png)

**Comment by kenzieschmoll** [comment]
A few questions:

1) What version of Devtools are you using?
2) What device are you running your Flutter app on?
3) Is your running Flutter app drawing frames?
4) Are you running your app with more than one isolate?

**Comment by kenzieschmoll** [comment]
Without further information, we cannot debug the issue. If you experience this issue again in the future, feel free to re-open. Thanks!
