### ISSUE TITLE
Offline mode not loading for all screens

### ISSUE THREAD

**Issue by hrajwade96** [flutter/devtools#7968]
Trying to test offline functionality on performance tab in master branch.
When I disconnect getting this :
It infinitely gets stuck on loader
<img width="1177" alt="image" src="https://github.com/flutter/devtools/assets/33225260/33008f28-2e6d-4f13-9f1d-f4688634de4f">

Flutter 3.22.2 • channel [user-branch] • unknown source
Framework • revision 761747bfc5 (2 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3

Tried this with other tabs as well, offline mode is not working

When its connected :
<img width="1728" alt="image" src="https://github.com/flutter/devtools/assets/33225260/e5e6a2f2-52f5-40c5-aa44-a6e3f68164b2">

**Comment by kenzieschmoll** [comment]
This was fixed by https://github.com/flutter/devtools/pull/7992
