### ISSUE TITLE
HTTP Log issue

### ISSUE THREAD

**Issue by zantdev** [flutter/devtools#7974]
I can not see http network log. Only showing websocket log
___
**DevTools version**: 2.34.3
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.4.3
Flutter Version: 3.22.2 / stable
Framework / Engine: 761747bfc5 / edd8546116

**Comment by kenzieschmoll** [comment]
closing as a duplicate of https://github.com/flutter/devtools/issues/3033

**Comment by kenzieschmoll** [comment]
This is a duplicate of https://github.com/flutter/devtools/issues/3033, which is now fixed.
