### ISSUE TITLE
Enabling the repo setting to automatically delete merged branches

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#7977]
Suggested by @devoncarew here: https://github.com/flutter/devtools/issues/7929#issuecomment-2166436220.

I do not have admin privileges to modify repo settings. @Piinks can you help with this? Thanks.

**Comment by Piinks** [comment]
What setting this this referring to?

**Comment by devoncarew** [comment]
Under 'Pull Requests', `Automatically delete head branches`.

**Comment by devoncarew** [comment]
It should be on the first page of the admin settings (the 'General' settings), about 2/3 of the way down:

<img width="366" alt="Screenshot 2024-07-01 at 10 01 25 AM" src="https://github.com/flutter/devtools/assets/1269969/2eba7dbf-9532-4160-a058-e563cd48ba02">

**Comment by Piinks** [comment]
Ah thank you! Done!
