### ISSUE TITLE
LUCI builds don't notify on failure

### ISSUE THREAD

**Issue by elliette** [flutter/devtools#8023]
Our LUCI build integration was broken for a few weeks due to https://github.com/flutter/devtools/issues/7939

This wasn't caught until we went to do a release of DevTools, which required the Flutter team creating the expected tag and branch to unblock the process. 

It would be great if there was a way for the DevTools team to be notified when the LUCI build for a commit fails.

**Comment by kenzieschmoll** [comment]
CC @athomas is this possible today? If so, would you be able to point us in the right direction to add this to the DevTools LUCI recipe?

**Comment by athomas** [comment]
Luci can send emails on build failures. I'd need to know who to notify (if it's a group, it needs to be able to receive email from outside of google). Probably a good idea to ping me the email addresses on chat :)

**Comment by athomas** [comment]
Fixed.
