### ISSUE TITLE
NoSuchMethodError on memory page.

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#803]
Running an app in profile mode. Clicking the instance allocation icon results in this error.
![image](https://user-images.githubusercontent.com/43759233/61391173-fc0c9f80-a870-11e9-8539-4ae21a2d8c4b.png)

```
NoSuchMethodError: 'owner'
method not found
Receiver: Instance of 'InstanceRef'
Arguments: []
dart:sdk_internal 4662:17                               dload
package:devtools/src/memory/memory_service.dart 140:29  computeInboundRefs
package:devtools/src/memory/memory.dart 909:5           hoverInstanceAllocations
dart:sdk_internal 25277:9                               <fn>
```

**Comment by devoncarew** [comment]
What's the version of `package:vm_service_lib` for you locally?

**Comment by kenzieschmoll** [comment]
3.17

**Comment by kenzieschmoll** [comment]
Going to close this since the allocation icons are no longer there
