### ISSUE TITLE
Should release notes be shown in sidebar?

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#8046]
I see release notes pop up in the sidebar. I don't know if this is accidental or intended. I don't know whether there's a good reason to show, or to not show - but because of another bug I see it every time I load the sidebar (I'll file a separate issue about that) and I thought it was worth asking the question.

![image](https://github.com/flutter/devtools/assets/1078012/bc0eebb0-6df5-45ab-83bf-1062a1e3d871)

@kenzieschmoll any opinions?

**Comment by kenzieschmoll** [comment]
This must have regressed because I submitted a fix for this issue here: https://github.com/flutter/devtools/pull/7166/

**Comment by DanTup** [comment]
Oh, I see! Looking at that fix, this is on me then :) I'm using the new DTD sidebar which is its own page (so we can more easily drop the postMessage one later) and I haven't added it to that exclusion. The bug only exists in my PR. I'll fix there.
