### ISSUE TITLE
DevTools disconnected overlay superimposed on top of screen disconnected overlay

### ISSUE THREAD

**Issue by elliette** [flutter/devtools#8050]
Steps to repro:

- connect DevTools to a running app and open up a screen that requires a running app (debugger, inspector, etc)
- terminate the running app (e.g. ctrl+c in terminal if started in the terminal)

The disconnected overlay is superimposed on top of the "debugger screen is unavailable" messaging, so that there are two buttons "connect to new app" and "go to home screen" that are overlayed on top of each other. 

<img width="572" alt="Screenshot 2024-07-12 at 4 15 51 PM" src="https://github.com/user-attachments/assets/ef20a0de-ec9d-49dd-a4e7-b69bc3496aa9">

FYI @kenzieschmoll - put this down as p2 for now - do you think this should be a p1 or require a cherry-pick?

**Comment by kenzieschmoll** [comment]
Yes this should be cherry-picked. I have a fix in progress, and will push up a PR soon.
