### ISSUE TITLE
Not Showing any Network Request

### ISSUE THREAD

**Issue by ssoad** [flutter/devtools#8055]
Not Showing any Network Request
___
**DevTools version**: 2.34.3
**IDE**: VSCode
**Connected Device**:
CPU / OS: x64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.4.3
Flutter Version: 3.22.2 / stable
Framework / Engine: 761747bfc5 / edd8546116

**Comment by laterdayi** [comment]
same

**Comment by laterdayi** [comment]
https://github.com/flutter/devtools/issues/8010

**Comment by kenzieschmoll** [comment]
This is a duplicate of https://github.com/flutter/devtools/issues/3033, which is now fixed.
