### ISSUE TITLE
Json type responce stuck in network tab after update flutter version 3.22

### ISSUE THREAD

**Issue by Subhojit0101** [flutter/devtools#8073]
Json type responce stuck in network tab after update flutter version 3.22.
___
**DevTools version**: 2.34.3
**IDE**: Android-Studio
**Connected Device**:
CPU / OS: arm (32 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.4.3
Flutter Version: 3.22.2 / stable
Framework / Engine: 761747bfc5 / edd8546116

**Comment by kenzieschmoll** [comment]
Can you elaborate on what you mean by "Json type response stuck in network tab"? If you can provide a screenshot and some reproduction steps, that would help us to identify the issue you are seeing.
