### ISSUE TITLE
When will devtools be released to the new version

### ISSUE THREAD

**Issue by laterdayi** [flutter/devtools#8075]
When will devtools be released to the new version

![image](https://github.com/user-attachments/assets/21215bbf-7572-4239-8d61-724bbadab409)

I don't see any devtools updates here, and the current issues with network not seeing network requests make debugging very difficult

https://github.com/flutter/devtools/pull/8061

**Comment by kenzieschmoll** [comment]
The version of DevTools including network tooling fixes should be released to the beta channel with the next cherry-pick release. The cherry pick issue is here: https://github.com/dart-lang/sdk/issues/56270.

**Comment by tarcyys** [comment]
Thank you, when will stable channel be officially released?

> The version of DevTools including network tooling fixes should be released to the beta channel with the next cherry-pick release. The cherry pick issue is here: [dart-lang/sdk#56270](https://github.com/dart-lang/sdk/issues/56270).

**Comment by kenzieschmoll** [comment]
Flutter releases a new stable version quarterly. The last stable release for Flutter 3.22 occurred in May. You can see the past releases here: https://flutter-ko.dev/development/tools/sdk/releases?
