### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by RRocaP** [flutter/devtools#8076]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.34.3
**IDE**: VSCode

how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                                                                          ^^^^^^^^^^
lib/main.dart:130:344: Error: 'the' isn't a type.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                                                                          ^^^
lib/main.dart:130:344: Context: This isn't a type.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                                                                          ^^^
lib/main.dart:130:356: Error: Type 'application.To' not found.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                                                                          ^^^^^^^^^^^^^...
lib/main.dart:132:10: Error: Type 'more' not found.
To learn more about Flutter, check out the following resources:
         ^^^^
lib/main.dart:132:36: Error: Type 'out' not found.
To learn more about Flutter, check out the following resources:
                                   ^^^
lib/main.dart:132:44: Error: Type 'following' not found.
To learn more about Flutter, check out the following resources:
                                           ^^^^^^^^^
lib/main.dart:134:4: Error: 'Flutter' isn't a type.
- [Flutter Documentation](https://flutter.dev/docs)
   ^^^^^^^
lib/main.dart:134:4: Context: This isn't a type.
- [Flutter Documentation](https://flutter.dev/docs)
   ^^^^^^^
lib/main.dart:135:4: Error: 'Flutter' isn't a type.
- [Flutter Tutorials](https://flutter.dev/docs/reference/tutorials)
   ^^^^^^^
lib/main.dart:135:4: Context: This isn't a type.
- [Flutter Tutorials](https://flutter.dev/docs/reference/tutorials)
   ^^^^^^^
lib/main.dart:136:4: Error: 'Flutter' isn't a type.
- [Flutter Samples](https://flutter.dev/docs/cookbook)
   ^^^^^^^
lib/main.dart:136:4: Context: This isn't a type.
- [Flutter Samples](https://flutter.dev/docs/cookbook)
   ^^^^^^^
lib/main.dart:137:4: Error: Type 'Dart' not found.
- [Dart Documentation](https://dart.dev/guides)
   ^^^^
lib/main.dart:139:1: Error: Type 'Happy' not found.
Happy coding!
^^^^^
lib/main.dart:141:4: Error: Type 'Source' not found.
## Source Code
   ^^^^^^
lib/main.dart:143:1: Error: Type 'You' not found.
You can find the complete source code for this tutorial on [GitHub](
^^^
lib/main.dart:143:9: Error: Type 'find' not found.
You can find the complete source code for this tutorial on [GitHub](
        ^^^^
lib/main.dart:143:18: Error: Type 'complete' not found.
You can find the complete source code for this tutorial on [GitHub](
                 ^^^^^^^^
lib/main.dart:143:48: Error: 'tutorial' isn't a type.
You can find the complete source code for this tutorial on [GitHub](
                                               ^^^^^^^^
lib/main.dart:130:9: Context: This isn't a type.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
        ^^^^^^^^
lib/main.dart:40:29: Error: Method not found: 'TextEditingController'.
  final _bucketController = TextEditingController(text: 'TVR-shared');
                            ^^^^^^^^^^^^^^^^^^^^^
lib/main.dart:41:32: Error: Method not found: 'TextEditingController'.
  final _namespaceController = TextEditingController(text: 'sdu3zgrgdchi');
                               ^^^^^^^^^^^^^^^^^^^^^
lib/main.dart:130:96: Error: Field 'Storage' should be initialized because its type 'Object' doesn't allow null.
 - 'Object' is from 'dart:core'.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                                                                          ^^^^^^^
lib/main.dart:13:3: Error: Method not found: 'runApp'.
  runApp(MyApp());
  ^^^^^^
lib/main.dart:17:3: Error: Method not found: 'runApp'.
  runApp(MyApp());
  ^^^^^^
lib/main.dart:22:16: Error: 'BuildContext' isn't a type.
  Widget build(BuildContext context) {
               ^^^^^^^^^^^^
lib/main.dart:23:12: Error: The method 'MaterialApp' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'MaterialApp'.
    return MaterialApp(
           ^^^^^^^^^^^
lib/main.dart:25:14: Error: The method 'ThemeData' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ThemeData'.
      theme: ThemeData(
             ^^^^^^^^^
lib/main.dart:26:24: Error: The getter 'Colors' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Colors'.
        primarySwatch: Colors.blue,
                       ^^^^^^
lib/main.dart:27:24: Error: The getter 'VisualDensity' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'VisualDensity'.
        visualDensity: VisualDensity.adaptivePlatformDensity,
                       ^^^^^^^^^^^^^
lib/main.dart:46:5: Error: 'FilePickerResult' isn't a type.
    FilePickerResult? result = await FilePicker.platform.pickFiles();
    ^^^^^^^^^^^^^^^^
lib/main.dart:46:38: Error: The getter 'FilePicker' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'FilePicker'.
    FilePickerResult? result = await FilePicker.platform.pickFiles();
                                     ^^^^^^^^^^
lib/main.dart:48:7: Error: The method 'setState' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setState'.
      setState(() {
      ^^^^^^^^
lib/main.dart:80:5: Error: The method 'setState' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setState'.
    setState(() {
    ^^^^^^^^
lib/main.dart:86:16: Error: 'BuildContext' isn't a type.
  Widget build(BuildContext context) {
               ^^^^^^^^^^^^
lib/main.dart:92:24: Error: Couldn't find constructor 'EdgeInsets.all'.
        padding: const EdgeInsets.all(16.0),
                       ^^^
lib/main.dart:87:12: Error: The method 'Scaffold' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Scaffold'.
    return Scaffold(
           ^^^^^^^^
lib/main.dart:88:15: Error: The method 'AppBar' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'AppBar'.
      appBar: AppBar(
              ^^^^^^
lib/main.dart:89:16: Error: The method 'Text' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Text'.
        title: Text('OCI Uploader'),
               ^^^^
lib/main.dart:91:13: Error: The method 'Padding' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Padding'.
      body: Padding(
            ^^^^^^^
lib/main.dart:93:16: Error: The method 'Column' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Column'.
        child: Column(
               ^^^^^^
lib/main.dart:94:31: Error: The getter 'CrossAxisAlignment' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'CrossAxisAlignment'.
          crossAxisAlignment: CrossAxisAlignment.start,
                              ^^^^^^^^^^^^^^^^^^
lib/main.dart:96:13: Error: The method 'TextField' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'TextField'.
            TextField(
            ^^^^^^^^^
lib/main.dart:98:27: Error: The method 'InputDecoration' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'InputDecoration'.
              decoration: InputDecoration(labelText: 'OCI Bucket Name'),
                          ^^^^^^^^^^^^^^^
lib/main.dart:100:13: Error: The method 'TextField' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'TextField'.
            TextField(
            ^^^^^^^^^
lib/main.dart:102:27: Error: The method 'InputDecoration' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'InputDecoration'.
              decoration: InputDecoration(labelText: 'OCI Namespace'),
                          ^^^^^^^^^^^^^^^
lib/main.dart:104:13: Error: The method 'SizedBox' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'SizedBox'.
            SizedBox(height: 20),
            ^^^^^^^^
lib/main.dart:105:13: Error: The getter 'ElevatedButton' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ElevatedButton'.
            ElevatedButton.icon(
            ^^^^^^^^^^^^^^
lib/main.dart:106:21: Error: The method 'Icon' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Icon'.
              icon: Icon(Icons.file_open),
                    ^^^^
lib/main.dart:106:26: Error: The getter 'Icons' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Icons'.
              icon: Icon(Icons.file_open),
                         ^^^^^
lib/main.dart:108:22: Error: The method 'Text' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Text'.
              label: Text('Select Local File'),
                     ^^^^
lib/main.dart:110:13: Error: The method 'SizedBox' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'SizedBox'.
            SizedBox(height: 20),
            ^^^^^^^^
lib/main.dart:111:13: Error: The method 'Text' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Text'.
            Text(_filePath.isNotEmpty ? 'Selected File: $_filePath' : 'No file selected.'),
            ^^^^
lib/main.dart:112:13: Error: The method 'SizedBox' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'SizedBox'.
            SizedBox(height: 20),
            ^^^^^^^^
lib/main.dart:113:13: Error: The getter 'ElevatedButton' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ElevatedButton'.
            ElevatedButton.icon(
            ^^^^^^^^^^^^^^
lib/main.dart:114:21: Error: The method 'Icon' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Icon'.
              icon: Icon(Icons.upload_file),
                    ^^^^
lib/main.dart:114:26: Error: The getter 'Icons' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Icons'.
              icon: Icon(Icons.upload_file),
                         ^^^^^
lib/main.dart:116:22: Error: The method 'Text' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Text'.
              label: Text('Upload Local File'),
                     ^^^^
lib/main.dart:118:13: Error: The method 'SizedBox' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'SizedBox'.
            SizedBox(height: 20),
            ^^^^^^^^
lib/main.dart:119:13: Error: The method 'Text' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Text'.
            Text(_message, style: TextStyle(color: Colors.red)),
            ^^^^
lib/main.dart:119:35: Error: The method 'TextStyle' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'TextStyle'.
            Text(_message, style: TextStyle(color: Colors.red)),
                                  ^^^^^^^^^
lib/main.dart:119:52: Error: The getter 'Colors' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:oci_uploader/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Colors'.
            Text(_message, style: TextStyle(color: Colors.red)),
                                                   ^^^^^^
lib/main.dart:128:4: Error: 'Conclusion' isn't a type.
## Conclusion
   ^^^^^^^^^^
lib/main.dart:130:35: Error: Can't use 'to' because it is declared more than once.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                  ^^
lib/main.dart:130:45: Error: Can't use 'a' because it is declared more than once.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                            ^
lib/main.dart:130:52: Error: Can't use 'to' because it is declared more than once.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                                   ^^
lib/main.dart:130:104: Error: 'using' isn't a type.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                                                                          ^^^^^
lib/main.dart:130:133: Error: 'You' isn't a type.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                                                                          ^^^
lib/main.dart:130:145: Error: Can't use 'how' because it is declared more than once.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                                                                          ^^^
lib/main.dart:130:152: Error: 'use' isn't a type.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                                                                          ^^^
lib/main.dart:130:167: Error: 'package' isn't a type.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                                                                          ^^^^^^^
lib/main.dart:130:178: Error: 'send' isn't a type.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                                                                          ^^^^
lib/main.dart:130:185: Error: 'POST' isn't a type.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                                                                          ^^^^
lib/main.dart:130:203: Error: Can't use 'a' because it is declared more than once.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                                                                          ^
lib/main.dart:130:210: Error: 'and' isn't a type.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                                                                          ^^^
lib/main.dart:130:218: Error: Can't use 'to' because it is declared more than once.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                                                                          ^^
lib/main.dart:130:228: Error: Can't use 'file' because it is declared more than once.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                                                                          ^^^^
lib/main.dart:130:243: Error: 'using' isn't a type.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                                                                          ^^^^^
lib/main.dart:130:267: Error: 'package.You' can't be used as a type because 'package' isn't defined.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                                                                          ^^^^^^^^^^^^
lib/main.dart:130:297: Error: Can't use 'to' because it is declared more than once.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                                                                          ^^
lib/main.dart:130:307: Error: 'SSL' isn't a type.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                                                                          ^^^
lib/main.dart:130:323: Error: 'validation' isn't a type.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                                                                          ^^^^^^^^^^
lib/main.dart:130:344: Error: Can't use 'the' because it is declared more than once.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                                                                          ^^^
lib/main.dart:130:356: Error: 'application.To' can't be used as a type because 'application' doesn't refer to an import prefix.
In this tutorial, you learned how to upload a file to Oracle Cloud Infrastructure (OCI) Object Storage using a Flutter application. You learned how to use the `http` package to send a POST request with a file and how to handle file selection using the `file_picker` package. You also learned how to handle SSL certificate validation errors in the Flutter application.
                                                                                          ^^^^^^^^^^^^^...
lib/main.dart:132:10: Error: 'more' isn't a type.
To learn more about Flutter, check out the following resources:
         ^^^^
lib/main.dart:132:36: Error: 'out' isn't a type.
To learn more about Flutter, check out the following resources:
                                   ^^^
lib/main.dart:132:44: Error: 'following' isn't a type.
To learn more about Flutter, check out the following resources:
                                           ^^^^^^^^^
lib/main.dart:134:4: Error: Can't use 'Flutter' because it is declared more than once.
- [Flutter Documentation](https://flutter.dev/docs)
   ^^^^^^^
lib/main.dart:135:4: Error: Can't use 'Flutter' because it is declared more than once.
- [Flutter Tutorials](https://flutter.dev/docs/reference/tutorials)
   ^^^^^^^
lib/main.dart:136:4: Error: Can't use 'Flutter' because it is declared more than once.
- [Flutter Samples](https://flutter.dev/docs/cookbook)
   ^^^^^^^
lib/main.dart:137:4: Error: 'Dart' isn't a type.
- [Dart Documentation](https://dart.dev/guides)
   ^^^^
lib/main.dart:139:1: Error: 'Happy' isn't a type.
Happy coding!
^^^^^
lib/main.dart:141:4: Error: 'Source' isn't a type.
## Source Code
   ^^^^^^
lib/main.dart:143:1: Error: 'You' isn't a type.
You can find the complete source code for this tutorial on [GitHub](
^^^
lib/main.dart:143:9: Error: 'find' isn't a type.
You can find the complete source code for this tutorial on [GitHub](
        ^^^^
lib/main.dart:143:18: Error: 'complete' isn't a type.
You can find the complete source code for this tutorial on [GitHub](
                 ^^^^^^^^
Target kernel_snapshot failed: Exception

Command PhaseScriptExecution failed with a nonzero exit code
** BUILD FAILED **

Building macOS application...                                           
Error: Build process failed

**Comment by kenzieschmoll** [comment]
This doesn't appear to be an issue with Flutter DevTools, but rather with your Flutter app. If you are experiencing issues with DevTools itself, please feel free to open another issue with more details. Thanks!
