### ISSUE TITLE
Debugger code mirror has janky UI on start.

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#808]
When refreshing devtools on the debugger page, we see janky ui with code mirror. Navigating to a different file in the debugger makes the ui jank go away.

![Screen Shot 2019-07-17 at 2 00 49 PM](https://user-images.githubusercontent.com/43759233/61411671-b3b6a700-a89b-11e9-8ac3-2a48dbad4a49.png)

**Comment by grouma** [comment]
Note that this issue is the result of having a file with less than double digit lines.

**Comment by jacob314** [comment]
Have you considered just writing more code?
