### ISSUE TITLE
a

### ISSUE THREAD

**Issue by dragonahao** [flutter/devtools#8098]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.31.1
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.3.4
Flutter Version: 3.19.6 / [user-branch]
Framework / Engine: 54e66469a9 / c4cd48e186

**Comment by kenzieschmoll** [comment]
Without additional information, we cannot debug this issue. Please re-open if you can provide a description of your issue and repro steps. Thanks.
