### ISSUE TITLE
Handle multi-client case for profile granularity selector

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#810]
The selector should respect the current state of the `profile_period` flag. We should pull the current value from the vm to set the initial state of the selector (see https://github.com/dart-lang/vm_service_drivers/issues/255 as we'll have to workaround this until it is fixed). This will ensure that two tabs of DevTools will respect one another.

https://github.com/dart-lang/sdk/issues/37557 Tracks the request to get flag change events on a stream. State management for this value will be difficult without events to notify us of changes.

**Comment by jacob314** [comment]
The VM feature blocking this issue has landed. Lets use if it if we aren't already.
