### ISSUE TITLE
Gokul Santol Dev Tool

### ISSUE THREAD

**Issue by raju-dev-flutter** [flutter/devtools#8106]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.34.3
**IDE**: Android-Studio
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.4.4
Flutter Version: 3.22.3 / stable
Framework / Engine: b0850beeb2 / 235db911ba

**Comment by kenzieschmoll** [comment]
Without additional information, we cannot debug this issue. Please re-open if you can provide a description of your issue and repro steps. Thanks.
