### ISSUE TITLE
Devtool network tab didn't work

### ISSUE THREAD

**Issue by EArminjon** [flutter/devtools#8113]
## Steps to Reproduce

(I didn't have the issue on a fresh new project)

Inside Intelij Idea, the Devtools blue button didn't work. It try to open 

http://127.0.0.1:9101/home?ide=IntelliJ-IDEA&ideFeature=runConsole&uri=http://127.0.0.1:55019/KNm8XIKF3NY=

When i open this url network tab is always empty.
When i open http://127.0.0.1:55019/KNm8XIKF3NY=, it works...

![image](https://github.com/user-attachments/assets/af1415c9-ba64-4f0e-9b12-97b6c3a1e74e)

## Version info

[✓] Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale fr-FR)
    • Flutter version 3.22.3 on channel stable at /Users/earminjon/fvm/versions/3.22.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (2 days ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/earminjon/Library/Android/Sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/earminjon/Library/Android/Sdk
    • Java binary at: /Users/earminjon/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Users/earminjon/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] Android Studio (version 2023.2)
    • Android Studio at /Users/perso/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.7)
    • IntelliJ at /Users/earminjon/Applications/IntelliJ IDEA Ultimate 2023.3.7.app
    • Flutter plugin version 80.0.1
    • Dart plugin version 233.15325.11

**Comment by kenzieschmoll** [comment]
Can you provide a small code snippet to reproduce this issue? Better yet, there was a Flutter beta channel release that went out today that may fix your issue. Can you try the latest Flutter beta channel (version 3.24.0-0.2.pre), and see if you can still reproduce this issue? You should see DevTools version 2.37.2, which contains a fix for how socket web traffic is displayed.

**Comment by 88888888oleg** [comment]
snippet-
`            ElevatedButton(
                onPressed: () {
                  http
                      .get(Uri.parse(
                      'https://jsonplaceholder.typicode.com/albums/1'))
                      .then((response) {
                    print(response.body);
                  });
                },
                child: Text('Button')),`
                Beta channel does not solve the problem.

**Comment by kenzieschmoll** [comment]
@88888888oleg can you include the output of `flutter --version`? thanks.

**Comment by PawnBreak2** [comment]
Still experiencing the issue after upgrading to 3.24, here's my `flutter --version` output:

Flutter 3.24.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 80c2e84975 (13 days ago) • 2024-07-30 23:06:49 +0700
Engine • revision b8800d88be
Tools • Dart 3.5.0 • DevTools 2.37.2

**Comment by EArminjon** [comment]
> Can you confirm that the problem persist after cleaning flutter / ide and then after rebooting your mac ? 

Can anyone check this please?

**Comment by PawnBreak2** [comment]
> > Can you confirm that the problem persist after cleaning flutter / ide and then after rebooting your mac ?
> 
> Can anyone check this please?

After installing 3.24, `flutter clean` and restarting and cleaning IDE, it seems to be working now. 
I still see the SOCKET methods, but at least I can see all the requests and payloads, so I assume the bug is solved for now. I will update if I see the issue returning.

**Comment by innerk** [comment]
same problem here @PawnBreak2 answer didn't work devtools only shows socket methods and not the actual endpoint 

<img width="1599" alt="Screenshot 2024-08-13 at 4 43 03 PM" src="https://github.com/user-attachments/assets/9bac4f29-7449-4696-a884-a39035036ddb">

**Comment by kenzieschmoll** [comment]
@bkonyi Is this what you'd expect even after your fix?

**Comment by bkonyi** [comment]
@innerk are you using `package:http` or `dart:io`'s `HttpClient`?

**Comment by innerk** [comment]
@bkonyi  http package,  i tried again the above solution and it works, after cleaning and rebooting the mac now it's showing post and get methods correctly.

thanks

**Comment by huongrealest** [comment]
nó đã được sửa trên 3.24.0 version. thank you @kenzieschmoll

**Comment by RicharC293** [comment]
Same issue here:
___
**DevTools version**: 2.37.2
**IDE**: Android-Studio
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.5.1
Flutter Version: 3.24.1 / stable
Framework / Engine: 5874a72aa4 / c9b9d5780d

**Comment by chiphan-quickcare** [comment]
Any updates?

**Comment by chihuy105** [comment]
Any updates? I current fix is run flutter clean, invalidate and restart IDE, and run flutter pub get again
