### ISSUE TITLE
WS on network section

### ISSUE THREAD

**Issue by KayesAshfaQ** [flutter/devtools#8119]
When app running on a real device network section shows ws on every request!
___
**DevTools version**: 2.34.3
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.4.4
Flutter Version: 3.22.3 / stable
Framework / Engine: b0850beeb2 / 235db911ba

**Comment by kenzieschmoll** [comment]
This issue has been resolved. The fix is on the latest Flutter beta channel (3.24.0-0.2.pre), and should make it to Flutter stable soon. Thanks!
