### ISSUE TITLE
I can not find the 'Open DevTools' on My Android Studio 3.0

### ISSUE THREAD

**Issue by renferliu** [flutter/devtools#812]
I have installed flutter and dart plugin on android Studio, but I can't find the 'Open DevTools' button on AS. Is AS still not supported?
Flutter version ： 1.1.5-pre.17 
Android Studio Version :3.0

**Comment by kenzieschmoll** [comment]
Try updating Flutter (run `flutter upgrade`) and Android Studio (Android Studio -> Check for updates). Once you have the necessary updates, you will be able to launch DevTools from two places when running your flutter app:
1) From the run window
<img width="284" alt="Screen Shot 2019-07-19 at 8 19 06 AM" src="https://user-images.githubusercontent.com/43759233/61546326-322b5a00-a9fe-11e9-8ee8-98368ed1b67b.png">
2) From the "More Actions" dropdown in the inspector
<img width="295" alt="Screen Shot 2019-07-19 at 8 22 15 AM" src="https://user-images.githubusercontent.com/43759233/61546393-56873680-a9fe-11e9-99dc-c7b2448bedd2.png">

**Comment by renferliu** [comment]
thks ! it work !

**Comment by renferliu** [comment]
it work on android studio 3.3

**Comment by bjkroeger** [comment]
I did all updates , but have still the problem: Flutter inspector is inactive; message is: "Installing DevTools..." but nothing happens :( 
my version:  Android Studio 4.1.1

**Comment by bjkroeger** [comment]
I have to add this information: within the run window I directly find the open dev tools button but. not a more actions button. Clicking the open dev tools button opens my browser towards the dev tools internet page which does not help to solve my problem

**Comment by bjkroeger** [comment]
Ok ... I solved it: you get the whole performance of flutter inspector of your current app under development now in the browser, not anymore in the Android Studio inspector window .... but that is ok  ... it works :)
