### ISSUE TITLE
Fix analytics to use io.eval - its not available in Profile builds.

### ISSUE THREAD

**Issue by terrylucas** [flutter/devtools#813]
See Issue https://github.com/flutter/devtools/issues/789

The user's platform e.g., Android, iOS, fuschia, Linux, macOS and Windows is computed using an eval see Analytics.dart function computeUserApplicationCustomGTagData.

    // eval user's Platform for all possible values.
    final android = await io.eval('Platform.isAndroid', isAlive: null);
    final iOS = await io.eval('Platform.isIOS', isAlive: null);
    final fuchsia = await io.eval('Platform.isFuchsia', isAlive: null);
    final linux = await io.eval('Platform.isLinux', isAlive: null);
    final macOS = await io.eval('Platform.isMacOS', isAlive: null);
    final windows = await io.eval('Platform.isWindows', isAlive: null);
    final windows = await io.eval('Platform.isWindows', isAlive: null);

Check with Flutter devs is there an easier way to compute this w/o eval?

**Comment by terrylucas** [comment]
@ianloic is there something I can inspect/read, w/o eval, that would tell me the platform of the Flutter app?

**Comment by devoncarew** [comment]
Is this info we should add to the `VM` service protocol object?

```
class VM extends Response {
  static VM parse(Map<String, dynamic> json) =>
      json == null ? null : new VM._fromJson(json);

  /// A name identifying this vm. Not guaranteed to be unique.
  String name;

  /// Word length on target architecture (e.g. 32, 64).
  int architectureBits;

  /// The CPU we are generating code for.
  String targetCPU;

  /// The CPU we are actually running on.
  String hostCPU;

  /// The Dart VM version string.
  String version;

  /// The process id for the VM.
  int pid;

  /// The time that the VM started in milliseconds since the epoch.
  ///
  /// Suitable to pass to DateTime.fromMillisecondsSinceEpoch.
  int startTime;

  /// A list of isolates running in the VM.
  List<IsolateRef> isolates;
```

**Comment by terrylucas** [comment]
If Ian tells me there's no way to find that in a running Flutter app that's a good alternative.

**Comment by Hixie** [comment]
what's the context here? I don't know what "eval" is.

**Comment by terrylucas** [comment]
eval is a method exposed in VM Service, used by DevTools.  It allows us to evaluate an expression in the context of an isolate/frame/etc. In this particular case, its used to return the value of a static property e.g., Platform.isAndroid.  The problem is eval cannot be used with a profile build of a Flutter application.

I was just confirming that this is the only mechanism exposed in Flutter that lets us know the Platform information of a running Flutter application.  If so, we'll need to expose this via VMService as a property (outside of using eval).

@bkonyi

**Comment by bkonyi** [comment]
In general, we should avoid using `evaluate` and `invoke` RPCs for the service protocol whenever possible for tooling purposes for various reasons (e.g., it can change the state of the running user program, cause a large number of allocations to occur, etc.).

Adding a `getPlatform` call to the service protocol should be relatively trivial and achieve the same result.

**Comment by Hixie** [comment]
yeah, what ben said. Definitely never use `eval`, that's asking for trouble. If you want information from the flutter process, expose an API (**and document and test it**). We have lots already.

Regarding the platform thing specifically, what exactly do you want to know? The actual platform (e.g. in an Android simulator on Windows, it would be Windows), the platform for which the code was compiled (e.g. for an Android build, Android), the platform we're using for default UI behaviour (as controlled by "o" in `flutter run`), the platform we're using in this part of the subtree (the `Theme.platform`), something else? (You can have an app that is both in "iOS" mode _and_ in "Android" mode simultaneously, while running as a Windows app in a Wine running on a Linux box. What platform do you want that to report?)

**Comment by kenzieschmoll** [comment]
Any update on when this can be fixed? This issue causes a lot of noise in the dev console:
![Screen Shot 2019-09-05 at 1 16 07 PM](https://user-images.githubusercontent.com/43759233/64377479-6cb57a00-cfdf-11e9-8d20-c0851874cdb1.png)

**Comment by bkonyi** [comment]
As mentioned on #709:

> > Hi Ben we still need Platform name of the running application see [Platform Issue](https://github.com/flutter/devtools/issues/813#issuecomment-512852299). Should this be part of this issue? It's important because we need a way of fetching the platform for analytics w/o using eval.
> 
> Hey Terry, this change landed awhile ago [here](https://dart-review.googlesource.com/c/sdk/+/111361). There's now an `operatingSystem` property in the `VM` object response that you can check for the OS version.

**Comment by terrylucas** [comment]
Yes I'm changing the analytics code to fix this.

**Comment by kenzieschmoll** [comment]
fixed by https://github.com/flutter/devtools/pull/1006
