### ISSUE TITLE
Reporting error: Error collecting raster stats: _flutter.renderFrameWithRasterStats: (-32000) Failed to render the last frame with raster stats. Rasterizer does not hold a valid last layer tree. This could happen if this method was invoked before a frame was rendered

### ISSUE THREAD

**Issue by corepuncher** [flutter/devtools#8132]
It's been quite a while since I have been able to take raster snapshots.  Not sure what changed.

When I click "Take Snapshot", here is what pops up in bottom right:

**Error collecting raster stats:
_flutter.renderFrameWithRasterStats: (-32000) Failed to render the last frame with raster stats. Rasterizer does not hold a valid
last layer tree. This could happen if this method was invoked before a frame was rendered.**

___
**DevTools version**: 2.34.3
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (profile build)
Dart Version: 3.4.3
Flutter Version: 3.22.2 / stable
Framework / Engine: 761747bfc5 / edd8546116

**Comment by elliette** [comment]
Thanks for the report! Unfortunately the Raster Stats feature was removed because it is not supported for Impeller and provides misleading and inconsistent results for Skia.
