### ISSUE TITLE
Devtools latest version does not work on Ubuntu.

### ISSUE THREAD

**Issue by 88888888oleg** [flutter/devtools#8149]
Devtools latest version does not work on Ubuntu.
![Screenshot from 2024-08-04 23-27-44](https://github.com/user-attachments/assets/72b27ca8-3736-453d-a8ad-a5ebab68f654)

___
**DevTools version**: 2.34.3
**IDE**: Android-Studio
**Connected Device**:
CPU / OS: x64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.4.4
Flutter Version: 3.22.3 / stable
Framework / Engine: b0850beeb2 / 235db911ba

**Comment by elliette** [comment]
Thanks for the report! Is the issue that the URIs only show `internetAddress` instead of the actual URI, or are you reporting something else?

**Comment by 88888888oleg** [comment]
After the last update everything works. Thank you! Issue can be closed.
