### ISSUE TITLE
Capture logs of various traffic to track problems in DevTools and plugins.

### ISSUE THREAD

**Issue by terrylucas** [flutter/devtools#816]
Expose logging of VM service protocol traffic for problems like hot reload and debugging in IntelliJ.  Also expose same logging, plus profile logging, in DevTools.

Expose logging of other services/APIs e.g., analysis server, etc.

Needed to help track issues like https://github.com/flutter/flutter-intellij/issues/3664

**Comment by kenzieschmoll** [comment]
DevTools supports verbose logging which includes VM service traffic and other detailed information for debugging devtools behavior.
