### ISSUE TITLE
pratice

### ISSUE THREAD

**Issue by shore2511** [flutter/devtools#8169]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.34.3
**IDE**: Android-Studio
**Connected Device**:
CPU / OS: Web windows
Connected app type: Flutter web (debug build)
Dart Version: 3.4.4
Flutter Version: 3.22.3 / stable
Framework / Engine: b0850beeb2 / 235db911ba

**Comment by elliette** [comment]
Are you experiencing an issue with DevTools? If so feel free to re-open and please add a description and repro steps so we can investigate. Thanks!
