### ISSUE TITLE
Performance view expanding hierarchy scrolls to position zero.

### ISSUE THREAD

**Issue by terrylucas** [flutter/devtools#818]
1. record performance
2. stop recording
3. select "Bottom Up" tab.
4. Find a entry e.g., RenderObjectElement.widget (open the collapsed item) scrolls to top.
5. Scroll back down to the expanded RenderObjectElement.widget expand a child under this node again expands and scrolls to position zero again.

**Comment by kenzieschmoll** [comment]
Does what you are seeing sounds related to https://github.com/flutter/devtools/issues/725?

**Comment by kenzieschmoll** [comment]
Actually never mind. I figured out what was going on. If no object was selected, expanding and collapsing a node would automatically scroll to position 0. We can fix this by setting the expanding/collapsing object as `_selectedObject`. Will have a PR for this shortly.
