### ISSUE TITLE
Polling `getIsolate(...)` in the Memory Chart code can cause the VM to OOM

### ISSUE THREAD

**Issue by bkonyi** [flutter/devtools#8180]
Details from https://github.com/dart-lang/sdk/issues/56408:

> So the issue is related to the DevTools memory chart repeatedly polling getIsolate. See the example isolate response below:
> 
> ![image](https://github.com/user-attachments/assets/acf54779-8bf6-42a6-a97a-eff5859abbdf)
> 
> In the returned Isolate's pauseEvent, there's a list of bound variables associated with the top frame of the isolate when the getIsolate() request was processed by the VM. Since the example code above is spending a lot of time in List.filled(...), the generated list is being captured in the list of bound variables. This results in an object ID being generated for the large list which, after https://dart-review.googlesource.com/c/sdk/+/367440, prevents the list from being GC'd until its object ID expires (e.g., after 8192 more object IDs are allocated). This happens frequently enough that enough unreferenced lists are kept alive that the VM runs out of memory with --max_old_gen_size=1024.
> 
> The DevTools memory chart code should be making use of the Isolate stream to track events that determine if an isolate is alive or not rather than polling (see [here](https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/screens/memory/panes/chart/controller/memory_tracker.dart#L121) for where getIsolate() is polled).

**Comment by a-siva** [comment]
The polling code here which queries if an isolate is alive before getting memory usage seems unnecessary and it is racy also as the VM is not paused. between the two calls the isolate could have died.
It is probably just sufficient to call the get memory usage call as the VM will return an error sentinel if the isolate does not exist.
 
```
 Future<void> pollMemory() async {
    final isolateMemory = <IsolateRef, MemoryUsage>{};
    for (final isolateRef
        in serviceConnection.serviceManager.isolateManager.isolates.value) {
      if (await _isIsolateLive(isolateRef.id!)) {
        isolateMemory[isolateRef] = await serviceConnection
            .serviceManager.service!
            .getMemoryUsage(isolateRef.id!);
      }
    }
```
