### ISSUE TITLE
dart dev tools eerror

### ISSUE THREAD

**Issue by Yash-123-git** [flutter/devtools#8184]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.37.2
**Connected Device**:
CPU / OS: x64 (64 bit) windows
Connected app type: Flutter native (debug build)
Dart Version: 3.5.0
Flutter Version: 3.24.0 / stable
Framework / Engine: 80c2e84975 / b8800d88be

**Comment by kenzieschmoll** [comment]
Without additional information, we cannot debug this issue. Please re-open if you can provide a description of your issue and repro steps. Thanks.
