### ISSUE TITLE
Devtool network shows InternetAddress('****',IPv4) instead of actual URL

### ISSUE THREAD

**Issue by Istiak-Ahmed78** [flutter/devtools#8188]
Running network devtool, my all API requests are being shown like 'InternetAddress('****',IPv4)' this format.

![hhhh](https://github.com/user-attachments/assets/0e600190-4a55-4ff7-9fcd-485904d8ebb9)

Flutter doctor summery:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.19045.4717], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.5)
[√] Android Studio (version 2024.1)
[√] Connected device (5 available)
[√] Network resources

• No issues found!
```

**Comment by huongrealest** [comment]
@kenzieschmoll Can you give me a solution?

**Comment by julemand101** [comment]
Could you try with latest stable Flutter version and therefore latest stable DevTools version?

**Comment by kenzieschmoll** [comment]
This should be fixed by upgrading to the latest Flutter stable with DevTools version 2.37.2. Be sure to run flutter clean after upgrading.

**Comment by Istiak-Ahmed78** [comment]
> This should be fixed by upgrading to the latest Flutter stable with DevTools version 2.37.2. Be sure to run flutter clean after upgrading.

Yes. Solved after upgrading. Thanks
