### ISSUE TITLE
Eval error on memory page in profile mode

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#819]
Run app in profile mode -> Take snapshot -> Select object in first table to view instance table -> Select Instance -> Observe eval error:

```
Expression compilation error (113) from evaluate():
Debugger is disabled in AOT mode.
null
```

**Comment by kenzieschmoll** [comment]
@terrylucas is this a duplicate of https://github.com/flutter/devtools/issues/813 or is it a separate issue?

**Comment by terrylucas** [comment]
I'll verify this is fixed - by default this isn't enabled it's now an experiment.

**Comment by kenzieschmoll** [comment]
Terry, were you able to verify if this is fixed or not?

**Comment by kenzieschmoll** [comment]
I don't believe we are using eval anymore - closing as obsolete
