### ISSUE TITLE
It always not showing anything 

### ISSUE THREAD

**Issue by 5alafawyyy** [flutter/devtools#8212]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.34.3
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.4.4
Flutter Version: 3.22.3 / stable
Framework / Engine: b0850beeb2 / 235db911ba

**Comment by kenzieschmoll** [comment]
Can you provide some additional information on the tool you are trying to access and reproduction steps so that we can investigate?
