### ISSUE TITLE
FlutterFlow Error 

### ISSUE THREAD

**Issue by HimanshuGithub111** [flutter/devtools#8273]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.37.2
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.5.1
Flutter Version: 3.24.1 / stable
Framework / Engine: 5874a72aa4 / c9b9d5780d

**Comment by elliette** [comment]
Without additional information, we cannot debug this issue. Please re-open if you can provide a description of your issue and repro steps. Thanks.
