### ISSUE TITLE
Reporting error: Failed to parse package:my_new_project/main.dart.

### ISSUE THREAD

**Issue by JustineShumate** [flutter/devtools#8290]
Stack trace:
main.dart.js 6417:27    rF
main.dart.js 74390:78   <fn>
main.dart.js 4987:64    <fn>
main.dart.js 62876:15   $2
main.dart.js 62870:23   $1
main.dart.js 5283:21    bRH
main.dart.js 182573:13  <fn>
main.dart.js 64110:14   uq
main.dart.js 63437:13   $0
main.dart.js 5164:42    PZ
main.dart.js 63359:5    uV
main.dart.js 62861:10   bS
main.dart.js 4977:12    l
main.dart.js 74503:18   <fn>
main.dart.js 4987:64    <fn>
main.dart.js 62876:15   $2
main.dart.js 62870:23   $1
main.dart.js 5283:21    bRH
main.dart.js 182573:13  <fn>
main.dart.js 64110:14   uq
main.dart.js 63437:13   $0
main.dart.js 5164:42    PZ
main.dart.js 63359:5    uV
main.dart.js 63407:15   $0
main.dart.js 5280:11    bRF
main.dart.js 182571:69  <fn>
main.dart.js 64108:14   wA
main.dart.js 64083:12   zH
main.dart.js 64160:22   $0
main.dart.js 5196:7     cF1
main.dart.js 5198:10    cFw
main.dart.js 62815:5    $1

<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.37.2
**Connected Device**:
CPU / OS: x64 (64 bit) android
Connected app type: Flutter native (profile build)
Dart Version: 3.5.1
Flutter Version: 3.24.1 / stable
Framework / Engine: 5874a72aa4 / c9b9d5780d

**Comment by elliette** [comment]
This doesn't appear to be an issue with Flutter DevTools, but rather with your Flutter app. If you are experiencing issues with DevTools itself, please feel free to open another issue with more details. Thanks!
