### ISSUE TITLE
APK and Chrome behaviors are different 

### ISSUE THREAD

**Issue by leandromorera** [flutter/devtools#8295]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.37.2
**Connected Device**:
CPU / OS: x64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.5.1
Flutter Version: 3.24.1 / stable
Framework / Engine: 5874a72aa4 / c9b9d5780d

**Comment by elliette** [comment]
Are you experiencing an issue with DevTools? If so feel free to re-open and please add a description and repro steps so we can investigate. Thanks!
