### ISSUE TITLE
Add Right click option to the widget inspector tree view to expand inner tree for third-party widgets

### ISSUE THREAD

**Issue by FMorschel** [flutter/devtools#8297]
I have a project inside my company that uses some packages created by ourselves to be utilised internally.

I'd like to have a Right-click option to "Expand widget" so I can see the inner workings of those widgets similar to me opening the file to see the implementation. 

Currently, the tree stops at that widget, not allowing me to see its inner workings. So if I have something like a different padding/flex or whatever that I'd like to see/understand better with the widget outline, I can click in the widget tree of the Widget Inspector to see it.

Let me know if you need any more details. Here is an example (if needed I can share the code): 

![image](https://github.com/user-attachments/assets/782bcfd9-f7aa-45c5-9b38-bd48e0f6395f)

**Comment by elliette** [comment]
I believe the "inner workings" you are interested in are in the Widget Details Tree (tab to the right of the Layout Explorer). 

Please re-open if this does not answer your question.

**Comment by FMorschel** [comment]
Yes it it! Thanks! I'd still like to ask for an option where I can see the inner three without showing the other Widget properties like `direction`, `mainAxisAlignment` and others for a `Column` since some of the time those widgets can have lots of propieties and it could get really noisy.

I'll reopen this, if you agree that we can use this issue to track this specific request - toggle/check to see the proprieties - we can rename it. If you think it would be best for me to file a new issue, please let me know and close this one.
