### ISSUE TITLE
web error 

### ISSUE THREAD

**Issue by sumeshks02** [flutter/devtools#8315]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.36.0-dev.10
**IDE**: VSCode
**Connected Device**:
CPU / OS: Web macos

Connected app type: Flutter web (debug build)
Dart Version: 3.5.0-203.0.dev
Flutter Version: 3.23.0-13.0.pre.50 / main
Framework / Engine: bc30104be0 / df719e66bd
this app proper working in mobile but not working in chrome

![Screen Shot 2024-09-10 at 11 46 41 AM](https://github.com/user-attachments/assets/666108c6-3f30-40ee-8eb3-953139ed3674)

**Comment by elliette** [comment]
This doesn't appear to be an issue with Flutter DevTools, but rather with your Flutter app. If you are experiencing issues with DevTools itself, please feel free to open another issue with more details. Thanks!
