### ISSUE TITLE
TypeError running example application

### ISSUE THREAD

**Issue by afucher** [flutter/devtools#8321]
I've got an error when trying to use the `Example of calling service extensions to fetch data from your package`

```
Error fetching all things: TypeError: Instance of 'minified:F<dynamic>': type 'minified:F<dynamic>' is not a subtype of type 'List<String>?'
```

---   

Steps to reproduce:

1. Clone the repository
2. Run the `app_that_uses_foo` application
3. Open DevTools
4. Select the Foo dev extension
5. Try to access the `Example of calling service extensions to fetch data from your package` 

The table of things do not show anything, and the console shows an error
![Screenshot 2024-09-13 at 17 20 21](https://github.com/user-attachments/assets/66ea9875-0b63-40b9-b0a6-8f9f529a7c0b)

**Comment by kenzieschmoll** [comment]
What version of Flutter are you on?
