### ISSUE TITLE
unable to see request and response data in network section

### ISSUE THREAD

**Issue by js-fydaa** [flutter/devtools#8322]
<-- Please describe your problem here. Be sure to include repro steps. -->
I can see overview header but empty space in request and response tab :/ 
<img width="1265" alt="Screenshot 2024-09-16 at 12 24 38 PM" src="https://github.com/user-attachments/assets/a62597ec-9c1f-434c-b977-f1330c563c7b">

___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Dart Version: 2.19.1
Flutter Version: 3.7.1 / stable
Framework / Engine: 7048ed95a5 / 800594f1f4
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
You appear to be using an old version of DevTools. Can you please run `flutter upgrade` to get the latest DevTools on Flutter stable and see if you are still seeing this issue?
