### ISSUE TITLE
issue on the Flutter Inspector . it will not navigating the android studio code page

### ISSUE THREAD

**Issue by jishnuAs** [flutter/devtools#8326]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.37.2
**IDE**: Android-Studio
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.5.2
Flutter Version: 3.24.2 / stable
Framework / Engine: 4cf269e36d / a6bd3f1de1

**Comment by elliette** [comment]
Without additional information, we cannot debug this issue. Please re-open if you can provide a description of your issue and repro steps. Thanks.
