### ISSUE TITLE
pull request error

### ISSUE THREAD

**Issue by ahmedhossam1212** [flutter/devtools#8328]
fatal: invalid value for 'pull.ff': 'n'

**Comment by ahmedhossam1212** [comment]
when i try run this in command every thing be OK

$ git config pull.rebase
$ git config pull.rebase true
$ git config pull.ff only
git fetch
git merge
git push

**Comment by elliette** [comment]
This doesn't appear to be an issue with Flutter DevTools. If you are experiencing issues with DevTools itself, please feel free to open another issue with more details. Thanks!
