### ISSUE TITLE
Network

### ISSUE THREAD

**Issue by VadimLefter2001** [flutter/devtools#8329]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.37.2
**IDE**: Android-Studio
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.5.1
Flutter Version: 3.24.1 / stable
Framework / Engine: 5874a72aa4 / c9b9d5780d
don't show request details

**Comment by faizabdillah** [comment]
yeah, i'm using the same exact version as you using and experience the same issue
no http request being recorded

![image](https://github.com/user-attachments/assets/5cd64a4a-c642-4f11-9b93-a3316475cdf2)

**Comment by elliette** [comment]
Without additional information, we cannot debug this issue. Please re-open if you can provide a description of your issue and repro steps. Thanks.
