### ISSUE TITLE
improving the experience when profiling short live isolate

### ISSUE THREAD

**Issue by stephane-archer** [flutter/devtools#8335]
here is the code:
```
 _reallyExpensiveValue = compute(reallyExpensiveFunction, argument);
```
the profiler takes a long time to detect the isolate so I can select it, worst, when the isolate stops the recording stops without showing any data... and if I close the recording before the end of the isolate I can see the data briefly before the isolate stop, then the data disappear again... what a terrible experience... you can't profile temporary isolate with this tool...

**Comment by elliette** [comment]
Closing in favor of canonical issue https://github.com/flutter/devtools/issues/3363
