### ISSUE TITLE
...

### ISSUE THREAD

**Issue by Heba141** [flutter/devtools#8337]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.37.3
**IDE**: Android-Studio
**Connected Device**:
CPU / OS: x64 (64 bit) android
Connected app type: Flutter native (profile build)
Dart Version: 3.5.3
Flutter Version: 3.24.3 / stable
Framework / Engine: 2663184aa7 / 36335019a8

**Comment by elliette** [comment]
Without additional information, we cannot debug this issue. Please re-open if you can provide a description of your issue and repro steps. Thanks.
