### ISSUE TITLE
the memory popup often appears partially offscreen, marking in hard to interact with

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#834]
The memory popup often appears partially offscreen, marking in hard to interact with.

In the screenshot below, the right portion of it is offscreen off the right side of the page:

<img width="444" alt="Screen Shot 2019-07-24 at 7 57 59 AM" src="https://user-images.githubusercontent.com/1269969/61804484-d4758400-ade8-11e9-95fb-254d3fbd0dd5.png">

We may adjus how we position the popup on screen, or through user studies or other, decide that there's a better way to present and navigate the data.

**Comment by terrylucas** [comment]
Closed popup has been removed.
