### ISSUE TITLE
Clearing the flutter devtools network view also removes the filters

### ISSUE THREAD

**Issue by prateek601** [flutter/devtools#8346]
When I am clearing the requests in the network view of flutter devtools my purpose is to remove the requests not the filters. Filters should not get removed when we press clear on flutter devtools network view.

<img width="1710" alt="Screenshot 2024-09-25 at 10 27 32 AM" src="https://github.com/user-attachments/assets/1c81e027-ee10-463b-81fc-75719fff95d0">

**Comment by prateek601** [comment]
@kenzieschmoll is it deployed?

**Comment by kenzieschmoll** [comment]
This will be included with the next flutter beta and stable releases.
