### ISSUE TITLE
Reporting error: Failed to parse .

### ISSUE THREAD

**Issue by NaderAlyEltabey** [flutter/devtools#8368]
Stack trace:
main.dart.js 6528:18    Object.pE
main.dart.js 71467:76   <fn>
main.dart.js 5086:63    bQP.a
main.dart.js 61503:14   bQP.$2
main.dart.js 61497:21   bOt.$1
main.dart.js 5388:19    Object.bQr
main.dart.js 180278:10  aoG.$5
main.dart.js 62738:12   a35.um
main.dart.js 62061:11   bA2.$0
main.dart.js 5269:40    Object.PZ

<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.40.0-dev.1
**IDE**: VSCode
**Connected Device**:
CPU / OS: x64 (64 bit) windows
Connected app type: Flutter native (debug build)
Dart Version: 3.6.0-266.0.dev
Flutter Version: 3.26.0-1.0.pre.159 / master
Framework / Engine: d5aa73ba34 / bc7d519a33

**Comment by elliette** [comment]
Without additional information, we cannot debug this issue. Please re-open if you can provide a description of your issue and repro steps. Thanks.
