### ISSUE TITLE
Thanks for your pull request! It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

### ISSUE THREAD

**Issue by Sarsilmazxx02** [flutter/devtools#8371]
Thanks for your pull request! It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

View this [failed invocation](https://github.com/flutter/devtools/pull/8370/checks?check_run_id=30830074206) of the CLA check for more information.

For the most up to date status, view the checks section at the bottom of the pull request.

_Originally posted by @google-cla[bot] in https://github.com/flutter/devtools/issues/8370#issuecomment-2381857350_

**Comment by Sarsilmazxx02** [comment]
[devcontainer.json](https://github.com/user-attachments/files/17182850/devcontainer.json)
[logs_28990689997.zip](https://github.com/user-attachments/files/17182851/logs_28990689997.zip)
[top-up-history.txt](https://github.com/user-attachments/files/17182852/top-up-history.txt)

**Comment by elliette** [comment]
Without additional information, we cannot debug this issue. Please re-open if you can provide a description of your issue and repro steps. Thanks.
