### ISSUE TITLE
Network inspector is not showing any traffic

### ISSUE THREAD

**Issue by elson-akasa** [flutter/devtools#8375]
Run the app and start the debugger
Open the network tab and observe no network requests are being captured. It shows blank like in the screenshot

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/eb33ec15-8147-42fa-8b7c-b857714d1178">

Note: Other functionality like debugger and logs are working fine

___
**DevTools version**: 2.28.5
**IDE**: Android-Studio
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Connected app type: Flutter native (debug build)
Dart Version: 3.5.3
Flutter Version: 3.24.3 / stable
Framework / Engine: 2663184aa7 / 36335019a8

**Comment by elliette** [comment]
Hi @elson-akasa! We recently made some changes to the Network Panel, which are in DevToosl version 2.37.2 or later. Could you please upgrade your Flutter version and see if this still repros for you? Thank you!

**Comment by mityax** [comment]
I have the same problem in DevTools version 2.37.3
