### ISSUE TITLE
Not able to see the https requests

### ISSUE THREAD

**Issue by naninydhruva** [flutter/devtools#8376]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.37.2
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.5.0
Flutter Version: 3.24.0 / stable
Framework / Engine: 80c2e84975 / b8800d88be

Hi team,

I am not able to see any https request in the network just getting the web scoket requests after the latest flitter upgrade.

**Comment by elliette** [comment]
Hi @naninydhruva! Do you mind sharing a small repro as well as sharing the package you are using to send the requests? Thank you!

**Comment by naninydhruva** [comment]
Hi @elliette , I am using dio :^5.7.0 version for sending the requests

**Comment by Adrek** [comment]
same problem with flutter 3.24.3, dart 3.5.3, devtools 2.37.3 and dio 5.7.0

**Comment by zhhal** [comment]
The same issue, all GET requests have turned into SOCKET.

**Comment by LiamMarega** [comment]
same issue with   dio: ^5.5.0 but only with a physical device, if I am use android emulator works well

`    • Flutter version 3.24.3 on channel stable at C:\Users\Liam\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (6 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3
    `

**Comment by saeedprogrammer** [comment]
same issue with dio
![Screenshot 2024-10-31 at 4 54 11 AM](https://github.com/user-attachments/assets/6cc1f7ac-4b1e-40c2-8ce9-963b7a5321fb)

Flutter 3.24.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 603104015d (6 days ago) • 2024-10-24 08:01:25 -0700
Engine • revision db49896cf2
Tools • Dart 3.5.4 • DevTools 2.37.3

**Comment by kenzieschmoll** [comment]
closing as a duplicate of https://github.com/flutter/devtools/issues/8380
