### ISSUE TITLE
Flutter Inspector only display "FlutterView" and "FlutterSurfaceView"

### ISSUE THREAD

**Issue by angelof-exe** [flutter/devtools#8386]
I cannot use Flutter Inspector because my Widget Tree only have this two widget: FlutterView and FlutterSurfaceView
![image](https://github.com/user-attachments/assets/99be4fe9-cc2e-43b3-a9f6-d3dd130f126e)

<hr></hr>

**Flutter Version**: 3.24.3
**Dart Version**: 3.5.3
**IDE**: Android Studio Koala 2024.1.2

**Comment by elliette** [comment]
Hi @angelof-exe - that looks like the Jetpack Compose inspector not the Flutter Inspector. To use the Flutter Inspector, you will have to install the Flutter plugin. Please follow the instructions here: https://docs.flutter.dev/tools/android-studio
