### ISSUE TITLE
DevTools tables broken with the Wasm build

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#8401]
![Screenshot 2024-10-03 at 5 10 52 PM](https://github.com/user-attachments/assets/f1a457fb-46d3-4db1-ab7c-9f4f88abfa9c)

```
postEvent: (130) Custom stream does not exist
main.dart.mjs:72     at http://127.0.0.1:9101/main.dart.wasm:wasm-function[8274]:0x269518
    at http://127.0.0.1:9101/main.dart.wasm:wasm-function[9105]:0x27b697
    at http://127.0.0.1:9101/main.dart.wasm:wasm-function[9102]:0x27b5f2
    at http://127.0.0.1:9101/main.dart.wasm:wasm-function[9100]:0x27b55a
    at http://127.0.0.1:9101/main.dart.wasm:wasm-function[32304]:0x4afb78
    at http://127.0.0.1:9101/main.dart.wasm:wasm-function[2149]:0x1db299
    at http://127.0.0.1:9101/main.dart.wasm:wasm-function[2154]:0x1db2fb
    at http://127.0.0.1:9101/main.dart.wasm:wasm-function[1525]:0x1ca7e0
errors.dart:124 Uncaught Exception {}
$func1084 @ errors.dart:124
$func1041 @ errors_patch.dart:19
$$invokeCallback @ internal_patch.dart:116
(anonymous) @ main.dart.mjs:730Understand this error
main.dart.mjs:765 [zoneGuarded]: postEvent: (130) Custom stream does not exist
file:///b/s/w/ir/x/w/rc/tmpzgn2wydc/hosted/pub.dev/vm_service-14.3.0/lib/src/vm_service.dart 1872:14                    9105
file:///b/s/w/ir/x/w/rc/tmpzgn2wydc/hosted/pub.dev/vm_service-14.3.0/lib/src/vm_service.dart 1855:12                    9102
file:///b/s/w/ir/x/w/rc/tmpzgn2wydc/hosted/pub.dev/dds_service_extensions-2.0.0/lib/dds_service_extensions.dart 346:12  9100
file:///b/s/w/ir/x/w/rc/tmpzgn2wydc/hosted/pub.dev/dds_service_extensions-2.0.0/lib/dds_service_extensions.dart 77:12   32304
org-dartlang-sdk:///dart-sdk/lib/_internal/wasm/lib/async_patch.dart 103:30                                             2149
org-dartlang-sdk:///dart-sdk/lib/async/zone.dart 1422:47        
```

With JS:
![Screenshot 2024-10-03 at 5 10 30 PM](https://github.com/user-attachments/assets/07f2198c-cad2-4cfe-b371-50e806e4e2d3)

CC @eyebrowsoffire @bkonyi

**Comment by kenzieschmoll** [comment]
Similarly, the data in the CPU profiler does not load with WASM:

Wasm:
![Screenshot 2024-10-03 at 5 14 27 PM](https://github.com/user-attachments/assets/bf2a9c9a-405a-4ffc-b28c-326dded06c15)

JS:
![Screenshot 2024-10-03 at 5 13 51 PM](https://github.com/user-attachments/assets/292bc02f-3140-46ea-bde1-a7c6c17ca044)

**Comment by kenzieschmoll** [comment]
Memory page too. This could be bad enough to turn the experiment off, or at least to delay socializing it until we can get a fix for this issue, since it is still "opt-in" only at this point.
![Screenshot 2024-10-03 at 5 15 39 PM](https://github.com/user-attachments/assets/41cd0baa-7dba-43df-bf9b-ad10b848a2c1)

**Comment by bkonyi** [comment]
This is likely on the DevTools side of things, but I'm curious where we're calling `postEvent` and to what stream. The only way this exception should be thrown is if the stream we're trying to post to doesn't exist, so either A) whoever is registering the custom stream hasn't done so or B) the stream name passed to `postEvent` is being corrupted somehow.

**Comment by kenzieschmoll** [comment]
The exception actually only occurred on the Widget Rebuild Stats table, so I'm thinking that exception was due to that feature. But the other tables still were broken without any exceptions with the WASM build.

**Comment by kenzieschmoll** [comment]
It appears that any column that **does not** implement ColumnRenderer (like [this](https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/screens/logging/_kind_column.dart/#L15)) is not rendered with the WASM build. Everything is rendered as expected with JS.

**Comment by kenzieschmoll** [comment]
Repro steps:
1. From the devtools directory, run `dt serve`
2. Connect DevTools to a Dart or Flutter application
3. Select "View VM flags" from the main landing page, and observe a semi-empty table. This does not happen with dart2js + canvaskit.
![Screenshot 2024-10-07 at 10 16 09 AM](https://github.com/user-attachments/assets/f8de70ca-ebc5-436d-a0ef-a52713333a95)

**Comment by eyebrowsoffire** [comment]
After some investigation today, we discovered that the likely culprit of this is [n](https://github.com/flutter/engine/pull/55468), which I am reverting here: https://github.com/flutter/engine/pull/55715
