### ISSUE TITLE
Add method table to CPU profiler

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#841]
Observatory has a method table view for cpu profiles. The table shows the list of methods with their consumption percentages. It also shows a table of callees and callers.

![Screen Shot 2019-07-24 at 11 21 05 AM](https://user-images.githubusercontent.com/43759233/61818514-d863cf00-ae05-11e9-9ccf-7741a2e29863.png)

**Comment by escamoteur** [comment]
This would be extremely helpful to detect bottlenecks. Especially such a view should also show the number a function is called and its total time that it is used.

Here it would be helpful if we got functions in dart to start stop the sampling to analyse just a segment of out App.

**Comment by kenzieschmoll** [comment]
Thanks for the feedback! Tracking issue for programatic start / stop here: https://github.com/flutter/devtools/issues/947.

**Comment by kenzieschmoll** [comment]
Here is the source from observatory: https://github.com/dart-lang/sdk/blob/main/runtime/observatory/lib/src/elements/cpu_profile_table.dart
