### ISSUE TITLE
not being able to inspect widgets

### ISSUE THREAD

**Issue by Des-Hussain** [flutter/devtools#8417]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.37.3
**IDE**: VSCode
**Connected Device**:
CPU / OS: x64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.5.3
Flutter Version: 3.24.3 / stable
Framework / Engine: 2663184aa7 / 36335019a8

**Comment by parlough** [comment]
Thanks for opening an issue @Des-Hussain! Could you provide some more details or a screenshot of the problem?

**Comment by Des-Hussain** [comment]
It seemed like a temporary processing error i tried after restarting my PC and its working fine now.
