### ISSUE TITLE
Poor search / filter performance with a large number of sources

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#842]
I've been playing around with Devtools on the Angular Component Gallery:
https://github.com/dart-lang/angular_components

When running the gallery there are 1300+ sources. Searching for a specific source is quite sluggish.

**Comment by kenzieschmoll** [comment]
Are you talking about the popup menu triggered by `ctrl + o` or the Libraries pane on the bottom left of the Debugger?

**Comment by grouma** [comment]
TIL `ctrl + o` exists. That seems fast enough although I'm running into issues with it. When I hit `ctrl + o` the open file dialogue also opens. Once I close popup menu `ctrl + o` no longer works.

Anyway, the original issue was referring to the bottom left pane.

**Comment by kenzieschmoll** [comment]
Gotcha, thanks. Perhaps we should switch to using a virtual table for this section. cc @terrylucas

**Comment by grouma** [comment]
@terrylucas I'll stop by and show you how to reproduce this

**Comment by grouma** [comment]
Raising the priority on this one. We are getting a number of internal complaints due to this.

**Comment by jacob314** [comment]
@DaveShuckerow this bug will be fixed by migrating the debugger page to flutter web

**Comment by kenzieschmoll** [comment]
obsolete - this was for the html app
