### ISSUE TITLE
Reporting error: Failed to parse package:flutter_application_1/main.dart.

### ISSUE THREAD

**Issue by FikaduGetachew** [flutter/devtools#8429]
Stack trace:
main.dart.js 6416:18    Object.rF
main.dart.js 74369:76   <fn>
main.dart.js 4987:63    bS2.a
main.dart.js 62850:14   bS2.$2
main.dart.js 62844:21   bPK.$1
main.dart.js 5282:19    Object.bRG
main.dart.js 182529:10  apk.<fn>
main.dart.js 64084:12   a30.uq
main.dart.js 63411:11   bBq.$0
main.dart.js 5164:40    Object.PZ

<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.37.3
**IDE**: VSCode
**Connected Device**:
CPU / OS: Web windows
Connected app type: Flutter web (debug build)
Dart Version: 3.5.3
Flutter Version: 3.24.3 / stable
Framework / Engine: 2663184aa7 / 36335019a8

**Comment by elliette** [comment]
Without additional information, we cannot debug this issue. Please re-open if you can provide a description of your issue and repro steps. Thanks.
