### ISSUE TITLE
Ability to track down what's stopping an application from terminating (open ports)

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#844]
@devoncarew suggested raising this for discussion here. While doing some investigation on https://github.com/flutter/flutter/issues/36476 I ended up with the test runs finishing, but the VM didn't terminate (it printed "All tests passed" and then just sat there).

I opened Observatory and found it had a "Ports" page that listed there was something open (unfortunately I couldn't much about what - it seemed to be in the `multiplex` function inside socket_patch, but it didn't have any stack to show me where it was created - as of yet, the mystery is unsolved!).

I don't think DevTools has any equivalent to the Ports page in Observatory - is it something it should have?

**Comment by jacob314** [comment]
We should add a general network package and tracking ports that are open should be a part of that.
