### ISSUE TITLE
not showing Http requests/response, only SOCKET  how to solve that 

### ISSUE THREAD

**Issue by sujinlagoon** [flutter/devtools#8443]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.37.3
**IDE**: Android-Studio
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.5.3
Flutter Version: 3.24.3 / stable
Framework / Engine: 2663184aa7 / 36335019a8

**Comment by aharris** [comment]
Same issue.

**Comment by elliette** [comment]
This is most likely a dupe of https://github.com/flutter/devtools/issues/8380, please refer to the comments there. Thank you!
