### ISSUE TITLE
E/flutter (16848): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)]

### ISSUE THREAD

**Issue by EthanWin** [flutter/devtools#8471]
After flutter run app , it show the message as below,

<--Installing build\app\outputs\flutter-apk\app-debug.apk...
Debug service listening on ws://127.0.0.1:14557/7DenjTO040Q=/ws
Syncing files to device sdk gphone x86...
E/flutter (16848): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected character (at line 29, character 3)
E/flutter (16848):   "profilePicUpdated": "Profile picture updated successfully",-->
___
**DevTools version**: 2.37.3
**Connected Device**:
CPU / OS: ia32 (32 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.5.3
Flutter Version: 3.24.3 / stable
Framework / Engine: 2663184aa7 / 36335019a8

**Comment by elliette** [comment]
This doesn't appear to be an issue with Flutter DevTools, but rather with your Flutter app. If you are experiencing issues with DevTools itself, please feel free to open another issue with more details. Thanks!
