### ISSUE TITLE
Reporting error: Failed to parse package:app_asap_work/main.dart.

### ISSUE THREAD

**Issue by MamadAsap** [flutter/devtools#8475]
Stack trace:
main.dart.js 6417:18    Object.rF
main.dart.js 74390:76   <fn>
main.dart.js 4987:63    bS3.a
main.dart.js 62876:14   bS3.$2
main.dart.js 62870:21   bPL.$1
main.dart.js 5283:19    Object.bRH
main.dart.js 182573:10  apm.<fn>
main.dart.js 64110:12   a31.uq
main.dart.js 63437:11   bBr.$0
main.dart.js 5164:40    Object.PZ

<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.37.2
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.5.2
Flutter Version: 3.24.2 / [user-branch]
Framework / Engine: 4cf269e36d / a6bd3f1de1

**Comment by elliette** [comment]
Are you experiencing an issue with DevTools? If so feel free to re-open and please add a description and repro steps so we can investigate. Thanks!
