### ISSUE TITLE
DevTools network not showing the http Request it's show only the socket method

### ISSUE THREAD

**Issue by KarimMok** [flutter/devtools#8502]
DevTools network not showing the http Request it's show only the socket method
when i restart my Laptop and run the problème will be resolve it 
___
**DevTools version**: 2.37.3
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.5.4
Flutter Version: 3.24.4 / stable
Framework / Engine: 603104015d / db49896cf2

**Comment by elliette** [comment]
This is most likely a dupe of https://github.com/flutter/devtools/issues/8380, please refer to the comments there. Thank you!
