### ISSUE TITLE
Can not start devtools from Android Studio

### ISSUE THREAD

**Issue by jason721017** [flutter/devtools#851]
Installed Flutter plugin by following the steps [here]. (https://flutter.dev/docs/development/tools/devtools/android-studio)

I was able to run the app but when I clicked "open devtools", nothing happened.

Followed [steps](https://flutter.dev/docs/get-started/install/linux) to install Flutter SDK and added Flutter SDK path in AS. Clicking  "open devtools" showed the following error:
/usr/local/google/home/jasonch/flutter/bin/flutter --no-color packages pub global run devtools --machine --port=0
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.
Process finished with exit code 1

Ran "flutter pub global run devtools" to start devtools from the command line.
Clicking  "open devtools" now shows "installing devtools" task but it never finished.

"flutter doctor -v" showed:

[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.7.8+hotfix.4 at /usr/local/google/home/jasonch/flutter
    • Framework revision 20e59316b8 (8 days ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /usr/local/google/home/jasonch/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-experimental, build-tools 28.0.3
    • Java binary at: /opt/android-studio-with-blaze-3.4/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /opt/android-studio-with-blaze-3.4
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] Android Studio (version 3.0)
    • Android Studio at /opt/android-studio-3.0
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Connected device (1 available)
    • iot msm8x53 som • HUA06TGU • android-arm • Android 8.1.0 (API 27)

**Comment by jacob314** [comment]
Fyi @DaveShuckerow. The issue appears to be google internal. The likely fix is in the InteliJ Plugin.

**Comment by DaveShuckerow** [comment]
Hi @jason721017 it looks like you are working in a google workspace.  Can you send me a message internally?  There are slightly different steps to use DevTools there.

You can go/flutter-devtools-setup to get started.

**Comment by jacob314** [comment]
Closing for now as we have improved this code path.
