### ISSUE TITLE
how to export information from dart devtools network

### ISSUE THREAD

**Issue by Eduar8004** [flutter/devtools#8517]
Hello, please tell me how I can export the information regarding network traffic or API consumption in the network tab.
___
**DevTools version**: 2.28.5
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.2.6
Flutter Version: 3.16.9 / stable
Framework / Engine: 41456452f2 / f40e976bed

**Comment by kenzieschmoll** [comment]
If you upgrade to the latest version of DevTools (run `flutter upgrade` to get the latest Flutter, which includes the latest DevTools), you'll see a button to export network data as a .har file. There is also active work by @hrajwade96 to add full offline support to the DevTools Network screen: https://github.com/flutter/devtools/pull/8332. Hopefully this will be able to land soon and be included in the next DevTools stable release. Hope this answers your question, thanks!
