### ISSUE TITLE
API calls not showing in DevTools network tab.

### ISSUE THREAD

**Issue by SandunC000** [flutter/devtools#8521]
Can't view API calls in the app. only showing 'ws' type API calls. I'm sure the app gets data from API's. 
![Untitled](https://github.com/user-attachments/assets/2c8bcf40-6f81-4a8d-ab14-2721e1a8434f)

___
**DevTools version**: 2.34.3
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (debug build)
Dart Version: 3.4.0
Flutter Version: 3.22.0 / stable
Framework / Engine: 5dcb86f68f / f6344b75dc

**Comment by Sten435** [comment]
Same, i noticed that in my app to.

**Comment by kahindiagenisys** [comment]
Same , sometimes works and sometimes doesn't

**Comment by zigapovhe** [comment]
Can confirm. This is maybe related to #8518

**Comment by kenzieschmoll** [comment]
What type of API calls are you expecting to show up in the network tab? Can you please provide a repro?
