### ISSUE TITLE
Error XMLhttpRequest

### ISSUE THREAD

**Issue by DGDX1** [flutter/devtools#8547]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.37.3
**Connected Device**:
CPU / OS: Web windows
Connected app type: Flutter web (debug build)
Dart Version: 3.5.4
Flutter Version: 3.24.5 / stable
Framework / Engine: dec2ee5c1f / a18df97ca5

**Comment by elliette** [comment]
Without additional information, we cannot debug this issue. Please re-open if you can provide a description of your issue and repro steps. Thanks.
