### ISSUE TITLE
Unable to read multiple Timeline events from WS

### ISSUE THREAD

**Issue by FeelHippo** [flutter/devtools#8566]
I am trying to use the ws to monitor performance of a little test app, but I am not getting the expected events.

First of all, in my local Flutter SDK:
```dart
/// When this flag is set to true, timeline events will be recorded for each
/// post-frame callback that runs
bool debugTracePostFrameCallbacks = true;
```

The Widgets being monitored can be found in [here](https://github.com/FeelHippo/flutter_state_management_exploration/tree/main/lib/state_managements), and they all use `WidgetsBinding.instance.addPostFrameCallback`, since its implementation provides Timeline tracking out of the box:
```dart

  /// In debug mode, if [debugTracePostFrameCallbacks] is set to true, then the
  /// registered callback will show up in the timeline events chart, which can
  /// be viewed in [DevTools](https://docs.flutter.dev/tools/devtools).
  /// In that case, the `debugLabel` argument specifies the name of the callback
  /// as it will appear in the timeline. In profile and release builds,
  /// post-frame are never traced, and the `debugLabel` argument is ignored.

void addPostFrameCallback(FrameCallback callback, {String debugLabel = 'callback'}) {
    assert(() {
      if (debugTracePostFrameCallbacks) {
        final FrameCallback originalCallback = callback;
        callback = (Duration timeStamp) {
          Timeline.startSync(debugLabel);
          try {
            originalCallback(timeStamp);
          } finally {
            Timeline.finishSync();
          }
        };
      }
      return true;
    }());
    _postFrameCallbacks.add(callback);
  }
```

Now, [here ](https://github.com/FeelHippo/flutter_state_management_exploration/blob/main/packages/performance/lib/main.dart#L78 ) you will find the connection to the ws, and the list of messages sent to listen to Timeline events.

The app is run in debug mode, as suggested by addPostFrameCallback.

The problem is, I only seem to be receiving events for one label at a time ("Inherited", most likely because it's the first widget to be registered in app).

Before opening this issue I have spent days searching for an answer online, on Discord, direclty from the Dart VM, etc etc. I could also find past issues related to TImeline events, so could this be related to the ws itself?

**Comment by kenzieschmoll** [comment]
Are you able to see the Timeline events in the DevTools Performance page? I would recommend using that tool to view timeline events in the trace viewer (in the "Timeline Events" sub tab on the Performance page).

**Comment by FeelHippo** [comment]
@kenzieschmoll I actually do, thank you for the quick response. It looks like they are indeed created, but I don't seem to be able to read them. The reason why I am using the WS is that I am consuming those events in a package, not from the UI. Is there another way to do that? I know the `Service` class from  `dart:developer` has some utilities to access the services provided by the Dart VM.

**Comment by kenzieschmoll** [comment]
Are you trying to consume these events from the same process in which they are sent? Or a separate process? Dart / Flutter tooling uses package:vm_service to pull timeline data from the connected app. CC @bkonyi.

**Comment by FeelHippo** [comment]
Thank you very much for your hints, I was able to find [this](https://github.com/dart-lang/sdk/blob/main/pkg/vm_service/example/vm_service_tester.dart), which is exactly what i was looking for.
The takeaway is that `package:vm_service` is the best way to consume VM events.

**Comment by kenzieschmoll** [comment]
Some other packages that may be helpful for you:
- `package:devtools_shared`, which has logic that is shared between DevTools and the DevTools server contained in the Dart SDK. There is a `connect` method for connecting to the vm service: https://github.com/flutter/devtools/blob/master/packages/devtools_shared/lib/src/service/service.dart/#L83
- `package:devtools_app_shared`, which has logic that is shared between DevTools and [DevTools extensions](https://docs.flutter.dev/tools/devtools/extensions). The `service.dart` library in particular exports many helpful classes for interacting with the VM service: https://github.com/flutter/devtools/blob/master/packages/devtools_app_shared/lib/service.dart. For example, the [ServiceManager](https://github.com/flutter/devtools/blob/master/packages/devtools_app_shared/lib/src/service/service_manager.dart/#L59) class which manages a VM service interaction.
