### ISSUE TITLE
Small mention for `launch.json`->`cwd` at README for devtools_extension 

### ISSUE THREAD

**Issue by FMorschel** [flutter/devtools#8575]
I was following the readme for devtools_extensions https://pub.dev/packages/devtools_extensions#step-4-debug-your-extension and over at the `launch.json` part I'd copied the `launch.json` example and tried to run. 

But in my case, I was directly in the devtools extension folder with my vscode and so with the `cwd` on, it was not running anything. It took me a minute to figure out what was going on. 

I'd suggest maybe adding a comment to that line or commenting it out entirely and mentioning on the text what is it for so people with the folder configuration you suggested above can uncomment it.

**Comment by kenzieschmoll** [comment]
Thanks for the feedback! Made this section more clear in https://github.com/flutter/devtools/pull/8579.
