### ISSUE TITLE
leak-tracker: Support pure Dart package

### ISSUE THREAD

**Issue by Solido** [flutter/devtools#8576]
Hi,

**leak-tracker** is an important tool in the dart world as the language is moving from being mainly front to also model rich world logic.

I'm working on a large package that would greatly benefits from memory insights while dealing with deep data structures and operations.

Thanks!

**Comment by kenzieschmoll** [comment]
Hello. Please file this issue on the https://github.com/dart-lang/leak_tracker repository. Thanks!

**Comment by Solido** [comment]
Oups!!
