### ISSUE TITLE
DevTools not loading proper symbol names for Performance profiling

### ISSUE THREAD

**Issue by frmatthew** [flutter/devtools#859]
_Please forgive me if this is not the right forum, I'd be happy to be redirected somewhere else. I read through the contribution guidelines. I inquired also on stackoverflow for nearly the same issue, but have yet to receive a response._

Here's the scenario: I use DevTools on a vanilla Flutter app (`flutter create test_app`), run in Profiling config (or Debug), launch Dart DevTools through VS Code on Debug configuration, then record some performance data. My stack traces are not showing the proper symbol/function names or source references, but rather tags that look like `[Native] /data/app/com.example.test_app-cNSWkQz9YSo2W0iT_Ob9NQ==/lib/arm64/...` for each function call I'm running on Windows 10. Here's a screenshot of Dart DevTools:

<img width="1145" alt="devtools" src="https://user-images.githubusercontent.com/17261076/62096499-b5d41a80-b238-11e9-9fb4-895b524770da.png">

Other parts of DevTools seem to be working fine: the Inspector, Logging, etc.

This is with the app running on a device, but I get the same behavior in the emulator. I can't for the life of me figure out how to get the proper symbol names loaded. Things I have tried:

- Reinstall Flutter completely.
- Reinstall VS Code completely.
- Tried previous versions of VS Code.
- Change the port on DevTools.

I get the same behavior on Dart Observatory too.

Any ideas would be much appreciated, I'm at a loss at where to look next. Thank you...

**Comment by kenzieschmoll** [comment]
Thanks for the report. This issue is not related to VS Code, nor the DevTools port, so you can be reassured on that front. I am guessing you are using an Android device, is that correct?

@bkonyi in my experience, we see this in Android but not iOS. IIRC, you mentioned flags that we could pass to make the names more helpful. Do you have an example of this?

**Comment by frmatthew** [comment]
That's right, Android. Thanks!

**Comment by bkonyi** [comment]
> Thanks for the report. This issue is not related to VS Code, nor the DevTools port, so you can be reassured on that front. I am guessing you are using an Android device, is that correct?
> 
> @bkonyi in my experience, we see this in Android but not iOS. IIRC, you mentioned flags that we could pass to make the names more helpful (`-rdynamic` and `-fvisibility=default`). I have attempted passing these flags to the flutter run command via `--dart-flags`, but have not succeeded in fixing the [Native] naming issue. Do you have an example of passing these flags to fix the issue?

`-rdynamic` and `-fvisibility=default` are actually flags for the C++ compiler, so they'll have no effect when passed to the VM.

@frmatthew the unresolved symbols you're seeing are actually from within the native code in the Flutter engine. Flutter doesn't include symbols for their engine in their release binaries as they increase the size of the binaries and aren't terribly important for typical Flutter users, assuming they're not poking around in the engine code itself.

Do you need to know what these methods are for any reason in particular? Unless you're having some serious performance issues that you think are occurring in engine code, I'd just ignore these entries.

**Comment by frmatthew** [comment]
Thanks for the time @bkonyi. The problem I'm having is that all of the symbols are being represented this way in DevTools. Here's a screenshot from the actual real world app I'm trying to profile, to identify and eliminate some jank:

<img width="1153" alt="devtools" src="https://user-images.githubusercontent.com/17261076/62142574-6d9e1200-b2a3-11e9-8416-320b5fdfdd23.png">

No matter how far I drill down (either through the Call Stack or through Bottom Up view), I never get to any symbols from my app itself, it's always code marked as [Native].

**Comment by frmatthew** [comment]
And the flame chart for reference:

<img width="1155" alt="devtools" src="https://user-images.githubusercontent.com/17261076/62142956-0d5ba000-b2a4-11e9-95a7-6afa323db8af.png">

**Comment by bkonyi** [comment]
Looking at that flame chart, I do see some Dart entries in there (e.g., `_drawFrame`, `_invoke`, `_CustomZone.runGuarded`, etc). Maybe you need to zoom in closer?

**Comment by frmatthew** [comment]
@bkonyi Wow, you're absolutely right, found my code buried deep deep down the tree. Should've looked harder. :P Sorry for the bother, and many thanks for the help.

**Comment by bkonyi** [comment]
> @bkonyi Wow, you're absolutely right, found my code buried deep deep down the tree. Should've looked harder. :P Sorry for the bother, and many thanks for the help.

No problem! I believe this is something we're working on improving, so hopefully this will get better as time goes on :-)
