### ISSUE TITLE
[devtools_extensions] build_and_copy failing in newer flutter versions

### ISSUE THREAD

**Issue by adsonpleal** [flutter/devtools#8639]
The web renderer flag (`--web-renderer`) was removed in recent flutter versions on the dev channel. So running `dart run devtools_extensions build_and_copy` is causing this error:

```
Building package executable...
Built devtools_extensions:devtools_extensions.
[build_and_copy] Building the extension Flutter web app...
Could not find an option named "--web-renderer".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
Unhandled exception:
ProcessException: Failed with exit code: 64
  Command: flutter build web --web-renderer canvaskit --pwa-strategy=offline-first --release --no-tree-shake-icons
#0      BuildExtensionCommand._runProcess (file:///Users/adson.leal/.pub-cache/hosted/pub.dev/devtools_extensions-0.2.2/bin/_build_and_copy.dart:134:7)
<asynchronous suspension>
#1      BuildExtensionCommand.run (file:///Users/adson.leal/.pub-cache/hosted/pub.dev/devtools_extensions-0.2.2/bin/_build_and_copy.dart:57:5)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#3      SharedStdIn.terminate (package:io/src/shared_stdin.dart:91:3)
<asynchronous suspension>
#4      main (file:///Users/adson.leal/.pub-cache/hosted/pub.dev/devtools_extensions-0.2.2/bin/devtools_extensions.dart:16:3)
<asynchronous suspension>
```

Since now the default web renderer is `canvaskit` I think we should just remove the flag from [here](https://github.com/flutter/devtools/blob/2704e5d92d977abca0067382366e276236f60fc8/packages/devtools_extensions/bin/_build_and_copy.dart#L63).

This problem made us revert the this [PR](https://github.com/flutter/packages/pull/6749) on `flutter/packages`.

**Comment by adsonpleal** [comment]
@kenzieschmoll I can also make this change if you don't mind. 

@stuartmorgan Just tagging you so you're aware of this discussion.

**Comment by kenzieschmoll** [comment]
Hi @adsonpleal just seeing this issue. I prepared a fix here: https://github.com/flutter/devtools/pull/8640

**Comment by adsonpleal** [comment]
Hey @kenzieschmoll! Perfect!

**Comment by adsonpleal** [comment]
@kenzieschmoll should I close this one since https://github.com/flutter/devtools/pull/8640 got merged?

**Comment by adsonpleal** [comment]
Or do we wait for the `pub` release?

**Comment by kenzieschmoll** [comment]
I just published the devtools_extensions. So we can close this now. Thank you for flagging, you should be unblocked for your shared_preferences PR.
