### ISSUE TITLE
Warn if the CPU profile has too little data to be meaningful

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#868]
If the CPU sample has fewer than (10?) samples it isn't really useful and we should display a warning at the top of the profile that the sample is too small to draw useful conclusions and you need to run with a higher sampling rate or look at a wider time interval.
Currently you only see the # of samples when you select an item in the chart so it is easy to try to scroll down into the chart looking for data before realizing the flame chart is just a single sample.

Fyi @kenzieschmoll

**Comment by kenzieschmoll** [comment]
Closing as obsolete since we are now using the Perfetto trace viewer and CPU profiler.
