### ISSUE TITLE
Logging table: new events reset the scroll position to end of the list

### ISSUE THREAD

**Issue by khainke** [flutter/devtools#875]
Context:
- open logging table, scroll to search for an event you want the details of
- new event comes in

Current Behaviour:
- logging table scrolls to the bottom of the table

Desired Behaviour:
- logging table keeps the scroll position, so that you can actually find the item youre looking for, instead of having to search for it again, starting from the bottom. (this is kinda annoying, for any use cases with a moderate+ amount of logs, that you want to live debug)

**Comment by jacob314** [comment]
@jacob314 scrolling to the bottom should stop if the user has manually scrolled. We should also add an item to the toolbar to control scrolling behavior as some users will want scrolling to the bottom.

**Comment by kenzieschmoll** [comment]
This is not a problem in the flutter web app

**Comment by khainke** [comment]
Why was this closed? Was there a fix on the develop branch? 

I still experience the problem ...

**Comment by kenzieschmoll** [comment]
The released version of DevTools is the dart:html app. We will soon be shipping the Flutter Web version of DevTools (which no longer has this issue). If you click the beaker icon in the top right corner of DevTools you can try out the Flutter Web version.

**Comment by khainke** [comment]
Ah, i see, thank you.
