### ISSUE TITLE
Splitters not starting at specified start ratio

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#880]
Splitters are not starting at the correct ratio. These examples repro every time on initial page load.
<img width="1363" alt="Screen Shot 2019-08-06 at 7 58 51 AM" src="https://user-images.githubusercontent.com/43759233/62551189-65ece900-b820-11e9-8240-89704c706eaa.png">
<img width="1354" alt="Screen Shot 2019-08-06 at 7 59 09 AM" src="https://user-images.githubusercontent.com/43759233/62551195-69807000-b820-11e9-99f7-32d5dfa454e3.png">

@jacob314 I confirmed this started happening after https://github.com/flutter/devtools/pull/873 landed.

**Comment by devoncarew** [comment]
I believe John also published a new version of the splitter package; perhaps revert to the previous published version to see if that is the issue?

**Comment by kenzieschmoll** [comment]
Just tried downgrading the split package. Still seeing the issue.
