### ISSUE TITLE
Dragging to select a window on memory plotly chart causes errors

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#884]
repro steps:
`Uncaught (in promise) undefined` errors are caused by dragging to select a section on the moving plotly chart.

The `TypeError`s are caused upon releasing the mouse to select. If the chart is paused, these are the only errors thrown on each selection attempt.

![Screen Shot 2019-08-06 at 10 56 55 AM](https://user-images.githubusercontent.com/43759233/62564217-4e6e2a00-b839-11e9-8458-dcdf0cb68966.png)

**Comment by devoncarew** [comment]
cc @terrylucas

**Comment by terrylucas** [comment]
I'll take a look however, I think this is a known plotly bug.

**Comment by kenzieschmoll** [comment]
Plotly was used in the html app, which is now deleted
