### ISSUE TITLE
Make exporting data from DevTools to Perfetto easier

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#902]
Perfetto provides a best in class stand alone trace viewer. We should make it easy for power users to open data from our performance tools in Perfetto as that is the tool they are already familiar with when analyzing large trace files.

The data files we are saving on export should already be compatible with perfetto but we should provide a direct link to open the data in Perfetto instead.

https://ui.perfetto.dev/#!/viewer

**Comment by devoncarew** [comment]
I see `null` for the thread names in perfetto:

<img width="298" alt="Screen Shot 2019-08-09 at 9 57 55 AM" src="https://user-images.githubusercontent.com/1269969/62795737-41954480-ba8c-11e9-92e7-63efc8187d33.png">

Perhaps the service protocol data is not complete, or, we're not writing the names to our json output file?

**Comment by kenzieschmoll** [comment]
We don't record thread names to our json output. Perfetto must be inferring these threads from the "tid" field of the trace events. Adding the names would be simple - we'd just need to figure out the format that Perfetto is expecting them to be in.

**Comment by kenzieschmoll** [comment]
Closing this issue, as we now give users direct access to Perfetto inside the DevTools trace viewer.
