### ISSUE TITLE
Connect dialog is buggy

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#906]
Sometimes when attempting to connect devtools to an app via the connect dialog, pasting the vm service URI into the connect dialog and clicking connect does not work. The unable to connect toast comes up.

Taking the same uri and connecting by tacking `uri=http://127.0.0.1:59424/zA_05vyrTLI=/` to the page url connects just fine.

**Comment by jacob314** [comment]
Is there a reliable repro? I'm surprised this code path is buggy. If there is a clear repro, I'd like it in 0.1.6 to fix as part of polishing this week.

**Comment by kenzieschmoll** [comment]
I don't have a reliable repro... but the next time I see this, I can try to track it down.

**Comment by jacob314** [comment]
Closing for now as I made some changes to make this code more robust that likely fixed the issue.
