### ISSUE TITLE
restore package:split 0.0.4

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#914]
We reverted down to using package:split version 0.0.2 to address #880; see PR https://github.com/flutter/devtools/pull/913. We should investigate, and:

- unpin the older version of package:split and move to the latest
- ensure that initial splitter positions still look good
- revert the change from PR #913 to the logging page splitter - that won't size properly with `flutter.error` output in the logging details view

**Comment by jacob314** [comment]
Updated to 0.0.5
