### ISSUE TITLE
Support ansii escape codes in logging views

### ISSUE THREAD

**Issue by jakemac53** [flutter/devtools#917]
For package:test tests specifically the logs always contain ansii escape codes (for colors primarily). In chrome console these actually work, but in devtools they just show the nonsense characters.

It would be cool if we could see the colors in devtools as well!

**Comment by jacob314** [comment]
I assume the repro steps are run a command line test that is started paused and connect up devtools?
Is that correct?
flutter_tools has some build in ansii escape code support that we can probably repurpose.

**Comment by jakemac53** [comment]
This works for a web test as well - package:test still emits ansii escape codes even in the web console, which actually happens to work out really nicely :)

**Comment by jacob314** [comment]
Wow this can look pretty bad currently. Good news is there is an existing js library we can use to do most of the hard work. Let me see what I can do.
<img width="844" alt="Screen Shot 2019-08-19 at 5 06 22 PM" src="https://user-images.githubusercontent.com/1226812/63308581-260a1500-c2a8-11e9-94f4-202f98828682.png">

**Comment by jakemac53** [comment]
haha wow I haven't seen one that bad

**Comment by jacob314** [comment]
<img width="1243" alt="Screen Shot 2019-08-20 at 4 16 57 PM" src="https://user-images.githubusercontent.com/1226812/63643409-6260bb00-c684-11e9-8404-24b66fe3c0c8.png">
<img width="1346" alt="Screen Shot 2019-08-23 at 1 22 35 PM" src="https://user-images.githubusercontent.com/1226812/63643414-72789a80-c684-11e9-9067-35438f43de4f.png">
