### ISSUE TITLE
debug pane doesn't appear for dart web apps

### ISSUE THREAD

**Issue by jakemac53** [flutter/devtools#918]
I am getting a message like "This screen is disabled because you are running a profile build of your application" when trying to connect.

The workaround is to manually add `&hide=none` to the uri, but we don't want our users to have to do that.

You can repro by running any web app with `webdev serve --debug` and then hitting `alt+d` from the app. Try clicking on the debug tab and you will get the message.

This is currently blocking the next dwds release.

**Comment by kenzieschmoll** [comment]
which version of devtools are you on?

**Comment by jakemac53** [comment]
cc @grouma @alan-knight I thought we had already turned it on previously?

**Comment by jakemac53** [comment]
Our version of devtools is currently at `^0.1.6-dev.2`

**Comment by jakemac53** [comment]
aaaand apparently I just needed to pub upgrade. Sorry for the noise!
