### ISSUE TITLE
[Regression] Tree tables no longer support horizontal scroll

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#919]
Tree tables used to support horizontal scrolling once the data exceeded the bounds of the column, and now tree tables do not. 
<img width="1360" alt="Screen Shot 2019-08-13 at 3 20 14 PM" src="https://user-images.githubusercontent.com/43759233/62981485-36208100-bdde-11e9-8fe0-54f3f8bed889.png">

This is crucial, as trees can be very deep, and we need to be able to see all the data.
@jacob314 could this have been caused by some part of the table refactor?

**Comment by jacob314** [comment]
It could be although it would be a bit surprising. I would suggest bisecting the build to verify, Likely some CSS for the allowed width of the tables changed.

**Comment by kenzieschmoll** [comment]
Bisection confirms https://github.com/flutter/devtools/pull/873 is the culprit.
