### ISSUE TITLE
Consider dropping use of rxDart

### ISSUE THREAD

**Issue by natebosch** [flutter/devtools#926]
It's only used in 1 file today. The usage looks suspect:

https://github.com/flutter/devtools/blob/862a5fd6569e489ab63a62bb87cb0fad31420a8d/packages/devtools/lib/src/debugger/debugger_state.dart#L38

There are two `on*Changed` methods backed by a `BehaviorSubject` - this seems like a strange name to me, you'll always get the current value when you subscribe which doesn't line up quite with "change" - should the name be updated? Is the recent value on subscribe behavior intended?

https://github.com/flutter/devtools/blob/862a5fd6569e489ab63a62bb87cb0fad31420a8d/packages/devtools/lib/src/debugger/debugger_state.dart#L41

This `concat` isn't sensible. You'd only emit values from `_supportsStepping` if `_paused` was closed, but it's never closed. Should we be merging instead?

I think it would be fairly easy to write a small `_Property` class which doesn't suffer from the same design flaws of `BehaviorSubect` (like being both a `Stream` _and_ a `StreamController`). I can take a stab at it - the version that doesn't always send the initial value on listen is simple to write - can I assume based on the "change" names that this is expected behavior?

**Comment by devoncarew** [comment]
> Is the recent value on subscribe behavior intended?

It was when this was initially written; I don't know if we're still depending on that.

> This concat isn't sensible. You'd only emit values from _supportsStepping if _paused was closed, but it's never closed. Should we be merging instead?

If I remember correctly, the the intent there is that the `supportsStepping` stream would fire if we were both paused, and in a situation where we could step (had a non-zero number of frames on the stack).

I'll take a look at the PR. Reducing the number of deps sounds good, and we're using a lot less of the rx package than I thought we might initially.

**Comment by natebosch** [comment]
> the the intent there is that the `supportsStepping` stream would fire if we were both paused, and in a situation where we could step (had a non-zero number of frames on the stack).

That isn't what is happening today - today it behaves exactly like the `onPausedChanged` stream.

**Comment by natebosch** [comment]
Landed #927 to unblock things - there are some open questions about which of the "eager" updates are required, and how to resolve the duplication for those cases. The rest of the change brings us in line with flutter which should aid future migrations.
