### ISSUE TITLE
move to using the getMemoryUsage() API

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#935]
Our memory polling is currently based on getting a VM instance, and then getting info on each individual Isolate. We should update this to calling `getMemoryUsage()` API.

cc @terrylucas

**Comment by jacob314** [comment]
Which getMemoryUsage api do you mean? The one getMemoryUsage api I see on the VM Service expects an isolate ID. There is also a getProcessMemoryUsage api but it doesn't seem like it breaks down the memory usage by isolate. There is also an api to get all memory usage for an isolate group.

**Comment by jacob314** [comment]
@terrylucas perhaps you already updated this to call getMemoryUsage but didn't close the bug.

**Comment by devoncarew** [comment]
I think it was fixed by this guy: https://github.com/flutter/devtools/pull/1971.
