### ISSUE TITLE
Provide a way to start DevTools programmatically

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#939]
DevTools provides a server implementation which is intended to be used as a CLI package. It would be useful if it could also be used programmatically so `package:dwds` doesn't have to do something like this:
https://github.com/dart-lang/webdev/blob/master/dwds/lib/src/servers/devtools.dart#L28

**Comment by jacob314** [comment]
Punting from 0.1.6

**Comment by DaveShuckerow** [comment]
Unassigning myself on account of job change.  Good luck!

**Comment by kenzieschmoll** [comment]
@elliette is this resolved? or maybe obsolete?

**Comment by kenzieschmoll** [comment]
DevTools can be started programatically using `dart devtools` or other methods exposed by `package:dds`
