### ISSUE TITLE
Inspector hover reflects row position but not column

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#940]
The inspector highlights the items as being hovered over, no matter where in the row the cursor is. Example:
![Screen Shot 2019-08-20 at 2 44 42 PM](https://user-images.githubusercontent.com/43759233/63387178-a177cf00-c359-11e9-87f9-0b965cc349dc.png)

**Comment by jacob314** [comment]
That is by design and reasonably standard behavior for tree views. Forcing selection only within a small horizontal area hurts accessibility and makes the view slower to interact with.
There is only a single column so there isn't much potential for harm.
