### ISSUE TITLE
Enable Flutter structured errors by default

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#944]
Next version of VS code enables these by default (and I've opened [an issue for IntelliJ](https://github.com/flutter/flutter-intellij/issues/3808)).

@jacob314 something we need to consider is if a user turns it off in VS Code, but then launches Devtools will it come back on? Should we have DevTools read the existing value when launched from an editor?

**Comment by jacob314** [comment]
We could only turn it on by default when the user opens the logging page in DevTools.
At some point what we really need to do is to switch the default value in package:flutter to enabled.
