### ISSUE TITLE
CPU profiler start and end times should be able to be configured in user code

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#947]
In order to profile a single method or sequence of events, a user should be able to specify start and end times in their code.

Maybe there is something in the dart:developer API that the user can use to do this. Then, when recording a CPU profile, we can pull samples from the interval specified by the user-triggered events.

This mode could be enabled via a setting "explicit profile interval" or something more clever.

cc @lambdabaa

**Comment by escamoteur** [comment]
May I add I think a time interval might not be the best solution but just a **start/stop** function. Also not only for CPU profile but also Performance and a Future Method table.  
For Memory to **make snapshot** from the program and a command to  **reset the accumulator.**
