### ISSUE TITLE
consider widening the package:vm_service constraint from package:devtools_server

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#953]
package:devtools_server makes light use of package:vm_service; instead of having a specific version constraint (`1.1.1`), we could relax it to something like `^1.1.0`. 

This would give other packages in a dependency solve more options; clients that really did need tight version constraints (like `package:devtools`) would be more free to specify specific versions.

**Comment by jacob314** [comment]
Makes sense to me. In general currently I would suggest we just update devtools_server to exactly match the version constraint from devtools.

**Comment by devoncarew** [comment]
done
