### ISSUE TITLE
Windows bots are too flaky

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#963]
The windows bots are too flaky to run every build. We can either enable them more as FYI bots that don't block commits or track down all the windows specific flakes and fix them.

-----

- [x] [debugging console output, Expected '1\n', got ''](https://travis-ci.org/flutter/devtools/jobs/576220595) (fixed by #952)
- [x] https://travis-ci.org/flutter/devtools/jobs/577099741 (+lots) - Chocolatey Chrome checksum (https://github.com/flutter/devtools/pull/985)
- [ ] https://travis-ci.org/flutter/devtools/jobs/577973800#L532 - ("No output has been received in the last 10m0s") hang during tests
- [ ] https://travis-ci.org/flutter/devtools/jobs/578433072#L524 - ("No output has been received in the last 10m0s") hang during tests
- [ ] https://travis-ci.org/flutter/devtools/jobs/578433070#L438 - "timeout getting the browser channel object (0:00:30.014433)"

**Comment by jacob314** [comment]
Fyi @DanTup

**Comment by DanTup** [comment]
Marking them as allowed failures might be good - we get to see how often they're working (and get the errors to investigate) without them blocking.

Can you post links of the runs that failed here so I can take a look? The last few runs on master look green so I'm not sure if it was PRs where you saw failures?

**Comment by DanTup** [comment]
Found another cause of some of our Windows test failures:

https://github.com/flutter/devtools/blob/master/tool/travis.sh#L137

This line is running tests without `-j1`, but some of these tests are running Flutter and trying to write over each others files. On Windows I can narrow it down to this:

```
flutter test test/info_controller_test.dart test/inspector_controller_test.dart
```

This fails with:

```
 FileSystemException: Cannot copy file to 'build\flutter-tester-app.dill.track.dill', path = 'build\flutter_assets\kernel_blob.bin' (OS Error: The requested operation cannot be performed on a file with a user-mapped section open.
  , errno = 1224)
```

Running with `-j1` does not fail.

In our docs we've written that you only need `-j1` when running the tests in the `integration_tests` folder. I'm not sure whether these tests should therefore be in there, or whether the advice is bad?

**Comment by kenzieschmoll** [comment]
closing as obsolete since we no longer use travis
