### ISSUE TITLE
Expanding closures does not work

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#967]
Make a simple closure and assign it to a variable, e.g: `var foo = () {};` If you pause the debugger and inspect the variables the closure is displayed. However, if you attempt to expand the variable nothing happens. Doing the same in VS Code will actually show useful details.

**Comment by elliette** [comment]
Expanding a closure now works:

<img width="379" alt="Screenshot 2024-11-05 at 2 43 42 PM" src="https://github.com/user-attachments/assets/09800c27-01c0-4dfc-a9cc-39169c744694">
