### ISSUE TITLE
[FR] Please add connection throttling (like chrome devtools)

### ISSUE THREAD

**Issue by samuelg123** [flutter/devtools#969]
Hi,
I need a feature for debugging connection in flutter apps. My idea is to add some throttling options (Online, Mid-tier mobile, Low-tier mobile, and Offline) like chrome devtools.

Thank you.

**Comment by jacob314** [comment]
There are proxy servers that accurately simulate varying network speeds

**Comment by samuelg123** [comment]
Okay, I'll try that. Thanks

**Comment by kenzieschmoll** [comment]
closing as dupe of https://github.com/flutter/devtools/issues/4139
