### ISSUE TITLE
Inspector `recomputeTreeRoot` needs to be audited.

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#975]
Playing with this method to expand / collapse nodes in the inspector tree, and it didn't seem to be behaving as expected. Code should be audited for buggy behavior.

**Comment by jacob314** [comment]
More context: 
1. Consider making the method private
2. Audit why it seems to make some bad decisions about which node to select if passing in a subtree root that is not a direct child of the summary tree root.

**Comment by jacob314** [comment]
Removing assignment to try to leave assignment for items that are actively being worked on. Using @mentions is a good way to make sure the right people are made aware of the bug.
