### ISSUE TITLE
Memory page footer should be hidden when there is no information to show

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#993]
We should hide this footer until we have data.

No data (should be hidden): 
![Screen Shot 2019-09-04 at 12 55 17 PM](https://user-images.githubusercontent.com/43759233/64286970-580bb000-cf13-11e9-9128-a16019f3fb3b.png)

Data (should be visible): 
![Screen Shot 2019-09-04 at 12 56 56 PM](https://user-images.githubusercontent.com/43759233/64287030-7ffb1380-cf13-11e9-80ea-6b1a2b4a21f1.png)

**Comment by jacob314** [comment]
Closing as we don't show a footer anymore.
