### ISSUE TITLE
Although I start my App in profile mode I get a warning in DevTools that my App would be a debug build

### ISSUE THREAD

**Issue by escamoteur** [flutter/devtools#999]
Hi,

first thanks for this amazing tool!

I have Version V0.1.6

II started my App in profile mode

Debug output in VS code
```
Launching lib\main.dart on Pixel 3a in profile mode...
Built build\app\outputs\apk\profile\app-profile.apk (11.2MB).
I/OpenGLRenderer(31993): Initialized EGL, version 1.4
```

But when I start DevTools I get this here:

![image](https://user-images.githubusercontent.com/16635729/64361511-fb8cbb80-d00c-11e9-82b0-b7da621ef605.png)

Also when I look  at any performance charts I don't find my own Dart functions listed anywhere.

Cheers
Thomas

**Comment by kenzieschmoll** [comment]
I have a fix out for the debug / profile mode issue. As for the comment regarding the perf page, see my response here: https://github.com/flutter/devtools/issues/1000

**Comment by escamoteur** [comment]
Cool I wonder if it will then also behave differently or was it just the banner?

**Comment by kenzieschmoll** [comment]
After the bug fix lands in a release, certain pages will actually be disabled for profile builds instead of broken (like the inspector and the debugger).

**Comment by kenzieschmoll** [comment]
We will push out a release later today that will include the fix.

**Comment by escamoteur** [comment]
@kenzieschmoll Thanks for noticing me!
